### ISSUE TITLE
Support for new fpga-based accelerator in tvm

### ISSUE THREAD

**Issue by Mookel** [dmlc/tvm#1002]
Is there any example for fpga-based accelerators that use tvm as code generation backend?

**Comment by eqy** [comment]
@tmoreau89 might have some knowledge about this :)

**Comment by tqchen** [comment]
please stay tuned, we are at the stage of documenting the stuffs and will open source it once the documentation is finished

**Comment by tqchen** [comment]
We plan to move discussion type issues to [TVM Discuss forum](https://discuss.tvmlang.org), close this for now. Announcement will be made on the forum when it is available
