### ISSUE TITLE
[TOPI] How do Schedule Dispatch according to Target

### ISSUE THREAD

**Issue by AndyQi93** [dmlc/tvm#1004]
In NNVM，when Loading the Keras Model or other during the “execute on TVM” part, can TVM automatically use the suitable schedule according to the ctx?

**Comment by merrymercy** [comment]
Yes. But it is according to target (the argument for `tvm.build`) rather than context.
TVM has a target dispatching system in TOPI. Each target (cuda, opencl, llvm) overloads the schedule. When you call the generic schedule, tvm will automatically call the overloaded one.

**Comment by AndyQi93** [comment]
Thx, And after
////////////////////////////////////
deploy_graph, lib, params = nnvm.compiler.build(
    compute_graph, target="cuda", shape={"x": shape}, dtype="float32")
import tvm
import numpy as np
from tvm.contrib import graph_runtime, util
module = graph_runtime.create(deploy_graph, lib, tvm.gpu(0))
x_np = np.array([1, 2, 3, 4]).astype("float32")
y_np = np.array([4, 4, 4, 4]).astype("float32")
module.set_input(x=x_np, y=y_np)
////////////////////////////////////
when running "module.run()", can TVM automatically find and use the suitable schedule for this module?

**Comment by PariksheetPinjari909** [comment]
yes, define and register the scheduler for the target "cuda" in topi and call the generic scheduler from NNVM scheduler registration. Based on the target used for build, TVM automatically pick the scheduler definition. 
hope this will help you
