### ISSUE TITLE
about thread_axis

### ISSUE THREAD

**Issue by janboeye** [dmlc/tvm#1005]
How OpenCL know dim parameters when call clEnqueueDNRangeKernel?

How TVM generate thread_aix?

Thanks

Yuanbo

**Comment by merrymercy** [comment]
We explicitly bind axis to thread_axis. e.g.
```python
bx, tx = s[C].split(some_axis, 8)
s[C].bind(bx, tvm.thread_axis("blockIdx.x"))
s[C].bind(tx, tvm.thread_axis("threadIdx.x"))
```
The lengths of `bx`, `tx` can be inferred during lowering, which determine the dim parameters.

**Comment by janboeye** [comment]
How will bx, tx  be inferred to the number of block or thread?

**Comment by eqy** [comment]
bx, and tx will be inferred depending on the extent of the loop axis that it was bound to. For example, if a loop nest has 16 outer loop iterations and 16 inner loop iterations, and the outer loop axis is bound to say `threadIdx.y` and the inner loop axis is bound to say `threadIdx.x`, then each thread block will have 16*16 = 256 threads.

The same reasoning can be applied for `blockIdx` and the number of blocks in a grid.

**Comment by janboeye** [comment]
@eqy 
Why bx's extent is 64? is bx 256/8 = 32, right?

**Comment by eqy** [comment]
Yes, my mistake :)
