### ISSUE TITLE
TVM on Android

### ISSUE THREAD

**Issue by VincentLin78** [dmlc/tvm#1011]
Following up the post here https://github.com/dmlc/tvm/blob/master/apps/android_rpc/README.md. It seems a *.so file has to be built in development time and deployed to a target device with APK. OEM can embed TVM runtime to its customized Android devices for executing that *.so file.

The above case was for openCL whose API and compiler might be stable and backward-compatible. What if an non-standardized backend with standardized software stack and even worse their compilers might be incompatible in different generations. For this case, I think the tvm.build needs to be done in device-running-time. Do you support this way with C++ API ?

**Comment by tqchen** [comment]
I do not completely get your need here, maybe you could provide an example of what you want.  Shipping the entire compiler to the device is possible but may not be the best idea. 

Note that the dynamic library module does not have to deploy to APK during installation. TVM support dynamic module loading, which means you can generate newer modules with new generation of your compiler as long as you have customized runtime that is in the APK which can load the module

**Comment by VincentLin78** [comment]
The actual scenario is we might have multiple generations of backends in the market. We wanna know how to make all previously published APKs compatible with our all backends. 

It seems your suggestion is to upgrade APK with updated TVM runtime and dynamic module ?
Then we're worried that APK may have to bundle with multiple versions of runtime and dynamic module to work on our existed backends in the market.

**Comment by tqchen** [comment]
Depending on if you allow APK to access network, the easiest way might be allow APK to lazily download the modules depending on its driver version from a cloud pool. 

Also bundle + compression might not be a too bad idea, if the compiler generation do not change that drastically and the generated code are similar.

Runtime compilation can be viewed as a way to resort to a relative stable API. Note that this does not necessarily mean we have to put entire TVM compiler. Instead, we can define a relative stable IR part, have TVM generate to that IR and runtime take that over to the backend API.

**Comment by VincentLin78** [comment]
Lazily download is one of our possible solution, as well as Bundle + compression. But they're not perfect to us and our partners e.g. can't provide download service in certain countries, a system app. needs to be upgraded by OTA with system image.

So we prefer run-time compilation like the way you mentioned as well.
Actually, the current solutions published in the market are in the way.
An IR might be hardware-independent, too.
Is the output of tvm.build a suitable IR ?

**Comment by tqchen** [comment]
close due to in-activity, feel free to reopen. Currently, we have schedule-opt -> IR -> IR-optimizaiton -> codegen->TVM Runtime. You can make the cut at any of these level
