### ISSUE TITLE
TVMError: src/runtime/graph/graph_runtime.cc: cannot find _param among input

### ISSUE THREAD

**Issue by arassadin** [dmlc/tvm#1018]
Following `nnvm`'s **Keras** model [example](http://nnvm.tvmlang.org/tutorials/from_keras.html#sphx-glr-tutorials-from-keras-py), but with my own model, I got this error
```
TVMError: [21:02:35] src/runtime/graph/graph_runtime.cc:91: cannot find _param_63 among input
```
upon
```
m = graph_runtime.create(graph, lib, ctx)
m.set_input('data', sample.transpose([0, 3, 1, 2]), **params)
```
The layer corresponding `_param_63` is `Conv2D`.

Can someone explain what it really means and how to overcome this?

**Comment by tqchen** [comment]
Please make sure you are using params dict returned by the nnvm.compile(instead of the original parameters). Because it is possible for nnvm to pre-compute part of graph and create a new set of parameters.

If you can provide a reproducible script (starting from symbol, and params returned by from_keras), we can also take a deeper look into it

**Comment by arassadin** [comment]
So, above lines are:
```
net = get_model(PATH) # my own model declaration and weights loading
sym, params = nnvm.frontend.from_keras(net)
with nnvm.compiler.build_config(opt_level=2):
    graph, lib, params = nnvm.compiler.build(sym, 'cuda', {'data': data_shape}, params=params)
ctx = tvm.gpu(0)
```
What else information can help?

**Comment by tqchen** [comment]
if you can provide the sym, params (for example pickle them) in 
``` sym, params = nnvm.frontend.from_keras(net)```, it would enable reproduction of your code. 
If you don't want to share your parameter,s simply wipe params to all zero will still serve the purpose

**Comment by arassadin** [comment]
I accidentally run `sym.list_input_names()` and can't see few `_param` there including 63d one. Does it means that something wrong at the moment `nnvm.frontend.from_keras(net)`?
I'll try to provide necessary data soon.

**Comment by tqchen** [comment]
Hmm, that means there is a parameter that gets ignored by from_keras. You could try first exclude the params that are not in sym.list_input_names() and see if the compilation is successful

**Comment by arassadin** [comment]
Ok, nice idea. But I double checked beforehand that all layers in my model are supported (formally, only `Conv2d`, `MaxPooling`, 'Activation` and `Concatenate`).

**Comment by arassadin** [comment]
Looking in `nnvm.frontend.keras.from_keras` and seeing such construction
```
    returns = [symtab.get_var(i.name, must_contain=False) for i in model.output_layers]
    tvmparams = {k:tvm.nd.array(np.array(v, dtype=np.float32)) for k, v in symtab.params.items()}
    return returns[0], tvmparams
```
I can assume that `nnvm` doesn't work with more-one-output models and my model just such. If I assumed right, why `nnnvm` doesn't supports many ouputs? Looks artificially.

**Comment by tqchen** [comment]
SHould be problem that can be fixed, can you look into it and send a patch?

**Comment by tqchen** [comment]
Nnvm does work with multiple outputs, but the from keras may not add that support

**Comment by tqchen** [comment]
close due to inactive status, we adopt an aggressive issue closing policy so all issues can be act upon.  feel free to reopen or followup with new issues
