### ISSUE TITLE
"bf != nullptr Target llvm is not enabled", but LLVM_CONFIG is set in config.mk, make clean and make run fine

### ISSUE THREAD

**Issue by Bryanscott13** [dmlc/tvm#1020]
I fixed this issue yesterday and it was running fine, but today I come back to do some work and it is again telling me that "LLVM is not enabled". I tried re building and remaking a few times but it continues to give the same error. My config.mk is properly setup, and nothing has changed since yesterday except I restarted my machine at one point. Here is my config.mk (Which was working fine 24 hours ago)
LLVM_CONFIG = /usr/local/Cellar/llvm/6.0.0/bin/llvm-config

**Comment by eqy** [comment]
Can you check if the `LLVM_CONFIG` path in your `config.mk` is being used? A simple check would be setting it to a clearly bad path, and seeing if the build breaks.

**Comment by Bryanscott13** [comment]
I tried setting a bad path, and the make failed. So it is definitely using the path from the `config.mk`

**Comment by tqchen** [comment]
close due to inactive status, feel free to reopen

**Comment by henrywu2019** [comment]
I still got this issue.
