### ISSUE TITLE
Expressing SGPR use in AMDGPU/rocm?

### ISSUE THREAD

**Issue by eqy** [dmlc/tvm#1021]
I've been looking at the strategy in MIOpen's Resnet layer 1 [implementation](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/master/src/kernels/conv7x7c3h224w224k64u2v2p3q3f1.s) (direct convolution) with the help of @adityaatluri. It seems that the strategy is to share filter weights in the scalar general purpose registers (SGPR), which are shared among all work items in a wavefront (or threads in a warp) as a form of "shared" local memory (registers). 

It seems that the current "local" cache_read primitive causes each thread to allocate its own memory exclusively, even when the stored values are identical across all threads in a block, as trying to imitate the strategy exceeds the local memory limits.

Is there another way that we can currently implement a similar strategy? It seems that we might be able to get the code generation to produce what we want by simply leaving filters in `__global` memory scope, but specifying that they are `__constant` (in OpenCL terminology)?

**Comment by tqchen** [comment]
I am planning to add warp level memory soon, will update the issue when it is ready

**Comment by adityaatluri** [comment]
If the compiler know the variable `__constant` is for a wavefront, it'll keep them in sgprs. The MIOpen kernels are implemented differently than rocBLAS kernels.

**Comment by eqy** [comment]
One question is that even if the `__constant` specifier isn't explicit, can the compiler still derive the answer? I'm testing this hypothesis with some schedule templates.

**Comment by adityaatluri** [comment]
No. You can try it out with `OpenCL` backend of tvm and compile the generated ocl code to isa and see how it look.

**Comment by eqy** [comment]
@adityaatluri can `__constant` also be specified in the rocm backend? Look at the [llvm guide](https://llvm.org/docs/AMDGPUUsage.html#address-spaces) it seems possible:
`Constant | constant | same as global | 64 | 0x0000000000000000 -- | -- | -- | -- | --`

**Comment by adityaatluri** [comment]
Unfortunately, no. @gstoner how should we solve this?

**Comment by tqchen** [comment]
move general discussion to https://discuss.tvmlang.org/

**Comment by adityaatluri** [comment]
@eqy can you create a thread at https://discuss.tvmlang.org/

**Comment by ghostplant** [comment]
Is this feature supported?
