### ISSUE TITLE
How does tvm decide the number of threads and blocks to launch the cuda kernels?

### ISSUE THREAD

**Issue by zhangxinqian** [dmlc/tvm#1028]
Hi, can someone tell me how tvm choose the proper number of threads and blocks when launching the cuda kernels?  If possible, please show me the related codes. Thanks.

**Comment by merrymercy** [comment]
same problem #1005

**Comment by zhangxinqian** [comment]
Thanks for the reference. @merrymercy
But I did not explicitly bind the axis. I just  compiled mxnet model into .so lib using nnvm, then loaded it and ran with tvm runtime. So I wonder how the tvm decides the threads and blocks number automatically.

**Comment by merrymercy** [comment]
The related code is [TOPI](https://github.com/merrymercy/tvm/tree/master/topi).
Take convolution for examples. Convolution layers in mxnet model will be converted to topi's operators, then tvm call their schedule functions in [topi/cuda](https://github.com/merrymercy/tvm/blob/master/topi/python/topi/cuda/conv2d_nchw.py). These schedule functions bind the thread explicitly. Currently the rules for binding is hard coded by topi writers.

**Comment by zhangxinqian** [comment]
Great. Thanks a lot. @merrymercy

**Comment by tqchen** [comment]
close and tahnks @merrymercy for the answers

**Comment by malixian** [comment]
> The related code is [TOPI](https://github.com/merrymercy/tvm/tree/master/topi). Take convolution for examples. Convolution layers in mxnet model will be converted to topi's operators, then tvm call their schedule functions in [topi/cuda](https://github.com/merrymercy/tvm/blob/master/topi/python/topi/cuda/conv2d_nchw.py). These schedule functions bind the thread explicitly. Currently the rules for binding is hard coded by topi writers.

The relevant link of TOPI is outdated, can you provide me with the latest code link about `.bind(bx, tvm.thread_axis("blockIdx.x"))`？Thanks.

**Comment by LukeLIN-web** [comment]
> > The related code is [TOPI](https://github.com/merrymercy/tvm/tree/master/topi). Take convolution for examples. Convolution layers in mxnet model will be converted to topi's operators, then tvm call their schedule functions in [topi/cuda](https://github.com/merrymercy/tvm/blob/master/topi/python/topi/cuda/conv2d_nchw.py). These schedule functions bind the thread explicitly. Currently the rules for binding is hard coded by topi writers.
> 
> The relevant link of TOPI is outdated, can you provide me with the latest code link about `.bind(bx, tvm.thread_axis("blockIdx.x"))`？Thanks.

I also have this question.
