### ISSUE TITLE
converting to ‘const std::unordered_set<std::basic_string<char> >’from initializer

### ISSUE THREAD

**Issue by jiacunjiang1215** [dmlc/tvm#1033]
Hi everyone.

I got such error when i build the lasted source code:
converting to ‘const std::unordered_set<std::basic_string<char> >’from initializer list would use explicit constructor ‘std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = std::basic_string<char>; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::basic_string<char> >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::basic_string<char> >]’

g++ version:
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 

I check the changes and find “include\tvm\build_module.h”
namespace target {
/*! \return A target for LLVM */
EXPORT Target llvm(const std::unordered_set<std::string>& options = {});
....
....

When I change it to 
namespace target {
/*! \return A target for LLVM */
EXPORT Target llvm(const std::unordered_set<std::string>& options = std::unordered_set<std::string>());

The error is fixed.

**Comment by tqchen** [comment]
Good catch, can you send a PR to fix this?

**Comment by jiacunjiang1215** [comment]
@tqchen 
Ok, let me to fix it.
