### ISSUE TITLE
There is no file "src/runtime/cuda/cuda_runtime.cc"

### ISSUE THREAD

**Issue by zhangxinqian** [dmlc/tvm#1036]
I find that there is no file named cuda__runtime.cc which is inclueded in https://github.com/dmlc/tvm/blob/master/apps/howto_deploy/tvm_runtime_pack.cc (line 59). Maybe it is a mistake, in which actually it is cuda_module.cc.

**Comment by tqchen** [comment]
@zhangxinqian nice catch, can you send a PR to fix this?

**Comment by zhangxinqian** [comment]
@tqchen ok. I'll do it.
