### ISSUE TITLE
missing include when building android_rpc apk?

### ISSUE THREAD

**Issue by eqy** [dmlc/tvm#1054]
While building the apk for android rpc I am getting errors that look like `/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:2233: undefined reference to `tvm::runtime::threading::ThreadGroup::~ThreadGroup()'` which suggests that I am missing an include/dependency somewhere. 

I've built `libtvm.so` and `libtvm_runtime.so` and `tvm4j`; it seems I have all of the environment variables set up according to [here](https://github.com/dmlc/tvm/tree/master/apps/android_rpc). Any ideas on what is missing?

**Comment by dayanandasiet** [comment]
@eqy 

please share complete error details.

**Comment by tqchen** [comment]
@eqy This is due to a recent update, need to add https://github.com/dmlc/tvm/blob/master/src/runtime/threading_backend.cc to the app pack.

**Comment by eqy** [comment]
Do you mean we also need to add `threading_backend.cc` in addition `ml_dmlc_tvm_native_c_api.cc` as to `LOCAL_SRC_FILES`?

**Comment by tqchen** [comment]
need to add that to https://github.com/dmlc/tvm/blob/master/apps/android_rpc/app/src/main/jni/tvm_runtime.h#L24

**Comment by eqy** [comment]
Ok, now I am getting
```
[arm64-v8a] Compile++      : tvm4j_runtime_packed <= ml_dmlc_tvm_native_c_api.cc                                                                                                                                 
In file included from tvm/apps/android_rpc/app/src/main/jni/ml_dmlc_tvm_native_c_api.cc:8:
In file included from tvm/apps/android_rpc/app/src/main/jni/tvm_runtime.h:24:
tvm/apps/android_rpc/app/src/main/jni/../../../../../../include/../src/runtime/threading_backend.cc:84:7: error: use of undeclared identifier 'pthread_setaffinity_np'; did you mean 'sched_setaffinity'?
```
I'm not sure if there needs to be more compile options enabled due to the use of pthreads, but just `-lpthreads` doesn't seem to work.

**Comment by tqchen** [comment]
Check out the implementation of that file, seems was due to __ANDROID__ macro path not present

**Comment by tqchen** [comment]
I mean the backend.cc

**Comment by eqy** [comment]
Right, looks like the macro is firing properly but there is no `__ANDROID__` version implemented.

Adding 
```
#if defined(__ANDROID__)
      sched_setaffinity(0,
        sizeof(cpu_set_t), &cpuset);
#else
```
seems to fix the build, but I have not tested the app yet.

**Comment by tqchen** [comment]
OK, seems due to problem introduced by latest PR, can you send a patch?
