### ISSUE TITLE
How to generate copy intrinsic for pattern with if stmt

### ISSUE THREAD

**Issue by xqdan** [dmlc/tvm#1074]
Hi, all,

Consider stmt as below, the move range for ax1 and ax2 should be 34, instead of 36. How can we get this and generate copy intrinsic?
```
for (ax0, 0, 6) {
  for (ax1, 0, 36) {
    for (ax2, 0, 36) {
      for (ax3, 0, 16) {
        if (likely(((ax1 - 2) < 32))) {
          if (likely(((ax2 - 2) < 32))) {
            A.local.L1[((((ax0*20736) + (ax1*576)) + (ax2*16)) + ax3)] = A[(((((ax0*16384) + (ax1*512)) + (ax2*16)) + ax3) - 1056)]
          }
        }
      }
    }
  }
}
```

**Comment by derisavi-huawei** [comment]
One alternative is to implement a pass that checks the if statements and merges their conditions into one of the loops when possible.

**Comment by tqchen** [comment]
let us https://discuss.tvmlang.org for general discussions
