### ISSUE TITLE
[TOPI] Shape Compatibility Check

### ISSUE THREAD

**Issue by zt706** [dmlc/tvm#1078]
```python
def add_bl_layer(bottom, num_filter, dropout, width, name=None):
        conv = bn_relu_conv(bottom, ks=1, nout=int(width*num_filter), stride=1, pad=0, dropout=dropout)
        conv = bn_relu_conv(conv, ks=3, nout=num_filter, stride=1, pad=1, dropout=dropout)
        concate = mx.sym.Concat(bottom, conv, dim=1, name=name)   # bottom:(1,448,57,57), conv:(1,64,57,57)
        return concate
 
def bn_relu_conv(bottom, ks, nout, stride, pad, dropout, name=None):
        bn = mx.symbol.BatchNorm(data=bottom)
        relu = mx.symbol.Activation(data=bn, act_type="relu")
        conv = mx.symbol.Convolution(data=relu, kernel=(ks,ks), pad=(pad,pad), cudnn_tune='limited_workspace', workspace=64,\
                  stride=(stride,stride), num_filter=nout, name=name)
        return conv


when :
    data = add_bl_layer()  # output_shape=(1,512,57,57)
    bn_relu_conv(data, ...)
```

the error:
Traceback (most recent call last):
  File "eval_api_classify_tvm.py", line 356, in <module>
    calc_presion(args)
  File "eval_api_classify_tvm.py", line 292, in calc_presion
    predictor = init_model(params_path, {'net':net, 'batch_size':batch_size, 'inner_size':224, 'test_device': gpu})
  File "eval_api_classify_tvm.py", line 167, in init_model
    compile_tvm_graph(base_net, arg_params, aux_params, (batch_size,3, input_size, input_size))
  File "eval_api_classify_tvm.py", line 98, in compile_tvm_graph
    graph, lib, params = nnvm.compiler.build(nnvm_sym, target, shape_dict, params=nnvm_params)
  File "/home/zhouji/external_libs/nnvm/python/nnvm/compiler/build_module.py", line 251, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/home/zhouji/external_libs/nnvm/python/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/home/zhouji/external_libs/nnvm/python/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: [18:07:59] tvm/topi/include/topi/detail/broadcast.h:47: Check failed: false Incompatible broadcast dims: (448 + 64) and 512 in: [1, (448 + 64), 57, 57] and [512, 1, 1]

I debug the nnvm, and  the concate + bn may be something wrong.

**Comment by tqchen** [comment]
move to https://github.com/dmlc/tvm/issues/1024

**Comment by tqchen** [comment]
move to https://github.com/dmlc/tvm/issues/1106
