### ISSUE TITLE
Why TOPI is implemented in both c++ and python

### ISSUE THREAD

**Issue by QiJune** [dmlc/tvm#1088]
Let's take relu as an example:
In C++:
https://github.com/dmlc/tvm/blob/20c06f2e5e1c7ca2fdd834087bba38c0dde0b5ca/topi/include/topi/nn.h#L44-L57

In Python:
https://github.com/dmlc/tvm/blob/20c06f2e5e1c7ca2fdd834087bba38c0dde0b5ca/topi/python/topi/nn/elemwise.py#L7-L21

It seems that these two parts have the same logic. What's the point of this design?
Thanks!

**Comment by tqchen** [comment]
please redirect general questions to dicsuss.tvmlang.org
