### ISSUE TITLE
[TOPI] Better Equality Checking

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#1106]
Currently TOPI relies on several functions to check equality constraint that are not in particularly general and produces problems in cases like concatenate #1078 #1024 

We need to solve this issue, there are two orthogonal ways

- [ ] Upgrade concatenate to simplify its output expression, so that it won't have composed sum
- [ ] Define a stronger version of topi::EqualCheck that first calls ir::Equal, if failed, do CanonicalSimplify(x - y) and check if result equals 0
- [ ] Add regression test cases to prevent that from happening

**Comment by tqchen** [comment]
@PariksheetPinjari909 Are you interested in help on this?

**Comment by tqchen** [comment]
@PariksheetPinjari909 can you verify if the case still exists, if so apply the listed fixes?

**Comment by PariksheetPinjari909** [comment]
Sorry, i missed your comment. Of course i will be interested in working on this. Yes the issue still exist and we need one of the solution provided by you above. What i feel is we can simplify the output expression there itself in concatenate operation. Could you throw more light on 3rd point of regression test. In the mean time i will prepare the PR for concatenate op upgrade.

**Comment by tqchen** [comment]
by regression test I mean build a testcase that fails in current master but can be fixed in the patch.

**Comment by PariksheetPinjari909** [comment]
Both the issues #1078 #1024 are caused in CPP code. When i tested it on python equivalent, it passed fine. But keeping consistency in mind, i suggest we should make changes in both cpp and python concatenate function to simplify expression. What are your views on this @tqchen ?

**Comment by tqchen** [comment]
sound sgood, we should also add a stronger version of EqualCheck in C++
