### ISSUE TITLE
tvm ndk arm64 compiler

### ISSUE THREAD

**Issue by ehsanmok** [dmlc/tvm#1116]
Hi

I'm on Ubuntu 16.04 server, LLVM 6.0, android-ndk-r16b-linux-x86_64. As a test, I'm using nnvm to compile a simple convnet for `target = 'llvm -target=arm64-linux-android'` with `target_host=None` (on cpu now. Is this correct?). I want to create the shared lib, graph and params **without RPC** (as described [here](http://www.tvmlang.org/2017/11/08/android-rpc-introduction.html)) locally and put it in an android app.

I have already created the arm64 toolchain through `./make_standalone_toolchain.py` though I cannot find out what to export as `TVM_NDK_CC`? and then what to use as outputs and objects in `tvm.contrib.ndk` when `lib.export_library(path, ndk.create_shared(output=?, objects=?))`?

Also I noticed the toolchain clang version is 5.0 not 6.0 in my server. Could this cause some problems later?

I'd appreciate any help on these issues
Thanks

**Comment by tqchen** [comment]
please move general support question to https://discuss.tvmlang.org/ :)
