### ISSUE TITLE
No libtvm.dll is generated in Windows

### ISSUE THREAD

**Issue by ljppro** [dmlc/tvm#1119]
Hi,
I'm building tvm with CUDA and LLVM in Windows 10 with Visual Studio 2017. LLVM is built and installed successfully. After that I changed the CMakeLists.txt to USE_CUDA and USE_LLVM and cmake it as following:
C:\Users\xxx\Desktop\TVM\tvm\build>cmake -G "Visual Studio 15 2017 Win64" -DLLVM_DIR=C:\Program\lib\cmake\llvm -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES="Release" ..
-- Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.14393.
-- The C compiler identification is MSVC 19.13.26129.0
-- The CXX compiler identification is MSVC 19.13.26129.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0 (found version "8.0")
-- Build with CUDA support
-- Build with RPC support...
-- Build with Graph runtime support...
-- Build with LLVM 6.0.0
-- Set TVM_LLVM_VERSION=60
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/xxx/Desktop/TVM/tvm/build

And The VS studio builds the tvm projects also:
========== Build: 5 succeeded, 0 failed, 0 up-to-date, 2 skipped ==========

There are just 3 dll files in Release directory: tvm.dll, tvm_runtime.dll and tvm_topi.dll.

After install the tvm packages into python, I run the get_started.py. And then:
>>> import tvm
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import tvm
  File "C:\Users\liuj81\Desktop\TVM\tvm\python\tvm\__init__.py", line 5, in <module>
    from . import tensor
  File "C:\Users\liuj81\Desktop\TVM\tvm\python\tvm\tensor.py", line 4, in <module>
    from ._ffi.node import NodeBase, NodeGeneric, register_node, convert_to_node
  File "C:\Users\liuj81\Desktop\TVM\tvm\python\tvm\_ffi\node.py", line 8, in <module>
    from .node_generic import NodeGeneric, convert_to_node, const
  File "C:\Users\liuj81\Desktop\TVM\tvm\python\tvm\_ffi\node_generic.py", line 7, in <module>
    from .base import string_types
  File "C:\Users\liuj81\Desktop\TVM\tvm\python\tvm\_ffi\base.py", line 43, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "C:\Users\liuj81\Desktop\TVM\tvm\python\tvm\_ffi\base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "C:\Users\liuj81\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

Could you help me on this issue?

Thanks in advance!

**Comment by ehsanmok** [comment]
Did you `python setup.py install` after the build?

**Comment by ljppro** [comment]
@ehsanmok Yes. And I can find all three dll files copied into site-packages. By the way, I just install CUDA 8.0 into my system without a real GPU presented. Does it matter?
Thanks!

**Comment by ehsanmok** [comment]
I don't know! perhaps @tqchen can help?

**Comment by tqchen** [comment]
You can try build TVM without CUDA, you can do that by switch the USE_CUDA option to be OFF in the cmake file.

**Comment by tqchen** [comment]
tvm.dll is enough to use TVM for tvm to run on windows. Please see if the solution works, if not, we can followup in https://discuss.tvmlang.org/
