### ISSUE TITLE
Getting intermediate outputs for yolov3

### ISSUE THREAD

**Issue by PariksheetPinjari909** [dmlc/tvm#1120]
I am trying to implement yolov3 support now. But i am facing a problem right now because Yolov3 needs intermediate layer outputs for computing the region boxes.
Is there any way to get the intermediate layer outputs as tvm_getoutput can fetch only last layer outputs.

**Comment by tqchen** [comment]
please use https://discuss.tvmlang.org/ for this kind of question. What we need is to get the intermediate layer as output and group them as output symbol, just as multiple output in mxnet
