### ISSUE TITLE
Android API > 23 and OpenCL/GLES_mali permission

### ISSUE THREAD

**Issue by ehsanmok** [dmlc/tvm#1121]
Hi

I'm not an android dev. Just following the app/android_deply, would like to ask whether there'll be some solutions within TVM to use OpenCL with API 24 and above (as there's restrictions to access system libs) other than bundling the OpenCL.so and all of its dependencies with the app? (continuation of [#973](https://github.com/dmlc/tvm/issues/973) would be great though)

For example, is there going to RenderScript support in TVM?

**Comment by ehsanmok** [comment]
I think I found what I need but not sure how to use it [tvm.module.system_lib](http://docs.tvmlang.org/api/python/module.html#tvm.module.system_lib) ?

**Comment by tqchen** [comment]
Yes, using systemlib option, we can bundle everything together, but we do need libOpenCL dependency

**Comment by tqchen** [comment]
We don't have plan to support renderscript, but vulkan support is ready, which should be supported in most system.

**Comment by tqchen** [comment]
This topic is better be moved to https://discuss.tvmlang.org/
