### ISSUE TITLE
ThreadPool Thread-Safety

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#1142]
Cross ref [this issue](https://discuss.tvmlang.org/t/why-concurrent-graph-excutor-core-dump/140)
Currently the thread pool assumes single producer and always launching(for barrier to work). The thread-pool itself is global, this will becomes a problem if we call the cpu function from different threads. 

- To keep things simple and safe, we need to change the thread-pool to be threadlocal, so more threads will get allocated if invoked from multiple threads

cc @yidawang @nhynes

**Comment by lyqscmy** [comment]
How ThreadPool work with the graph runtime? Associated with the compiled operator? I'm wondering if we can implement graph runtime in Rust?

**Comment by nhynes** [comment]
> wondering if we can implement graph runtime in Rust?

This is a most excellent idea! Not only would Rust solve the data race problem, it would also improve integration with SGX via [rust-sgx-sdk](https://github.com/baidu/rust-sgx-sdk). I've also noticed that it's very easy to break the system allocator in very subtle ways by incorrectly memsetting the structs used by the runtime.

I anticipate several challenges, though. A primary concern is C++/Rust interoperability (particularly w.r.t. dmlc-core). The officially-supported [`bindgen`](https://rust-lang-nursery.github.io/rust-bindgen/cpp.html) utility doesn't handle C++ very well so everything would have to go through the C API, which might be unergonomic.

**Comment by yidawang** [comment]
#1152

**Comment by nhynes** [comment]
@lyqscmy, I have a need to implement the TVM runtime in Rust. Would you be interested in helping build this? I can try to have a first version ready for further development early next week.

**Comment by lyqscmy** [comment]
@nhynes, thanks for your appreciation. I really would love to do this job with you, but I'm afraid my ability is not enough, because I just learn Rust a few weeks.

**Comment by nhynes** [comment]
well, if you ever feel like testing your new skills, you're always welcome to [submit a PR](https://github.com/nhynes/tvm-rs) :)
