### ISSUE TITLE
CPU fails but GPU works on Android

### ISSUE THREAD

**Issue by ehsanmok** [dmlc/tvm#1153]
Hi

I'm on Ubuntu 16.04, LLVM 6.0, MXNet 1.2 (built from source) and I've built TVM after [#1132](https://github.com/dmlc/tvm/pull/1132) merged and NNVM after [#448](https://github.com/dmlc/nnvm/pull/448) merged. I've a small model in MXNet Symbol and the very strange thing is that compiling with OpenCL is running the model on Android works but for CPU crashes on Android with

```
/tvm/include/../src/runtime/dso_module.cc:93: Check failed: lib_handle_ != nullptr Failed to load dynamic shared library /data/user/0/com.huawei.aiiot.fqsdk.cpu64/cache/fqsdk_1469882095/cpu64_lib.so dlopen failed: cannot locate symbol "expf" referenced by "/data/data/com.huawei.aiiot.fqsdk.cpu64/cache/fqsdk_1469882095/cpu64_lib.so"...
```

Any idea about this error?

**Comment by tqchen** [comment]
Let use  https://discuss.tvmlang.org/ to discuss this. As indicated by the error message, it means somehow the device library cannot find expf
