### ISSUE TITLE
error "Cannot insert syncs inside condition" when using tvm.var

### ISSUE THREAD

**Issue by feiyuvl** [dmlc/tvm#1156]
![default](https://user-images.githubusercontent.com/13388702/39911320-9e531c80-552d-11e8-9e4a-f7112c13a45f.PNG)

This error occurs when I change the code 
`https://github.com/dmlc/tvm/blob/master/tutorials/optimize/opt_conv_cuda.py:28`
to 
`batch = tvm.var('batch')`

It seems tvm doesn't support variable input size in some condition when generating cuda kernels. Is there any way to solve that? @tqchen

**Comment by tqchen** [comment]
please raise general discussion at https://discuss.tvmlang.org/ This is indeed an limitation of current code generator and we normally encourage optimization for constant shape.
