### ISSUE TITLE
link error with tvm_topi.dll by vs2017

### ISSUE THREAD

**Issue by webbery** [dmlc/tvm#1159]
Hi, I'm new with tvm.  
I used cmake to generate a .sln file and tvm.dll was created. But I encountered following error with tvm_topi.dll:  
```
topi.obj : error LNK2019: unresolved symbol "public: virtual class tvm::Array<class tvm::Tensor,void> __cdecl tvm::ComputeOpNode::InputTensors(void)const " (?InputTensors@ComputeOpNode@tvm@@UEBA?AV?$Array@VTensor@tvm@@X@2@XZ)，in function "public: class tvm::Tensor __cdecl <lambda_62e9b9aef72fde4a6206bca07dd5fbfa>::operator()(class tvm::Operation const &)const " (??R<lambda_62e9b9aef72fde4a6206bca07dd5fbfa>@@QEBA?AVTensor@tvm@@AEBVOperation@2@@Z) 
```
I tried to add tvm_runtime.lib to tvm_topi project manually, but the error was still here. Have any idea to solve it?

**Comment by GryffindorZz** [comment]
I met the same error with you, did you solve it?

**Comment by webbery** [comment]
Well, I open tvm.lib by vim and find none of words 'InputTensors'. So it seems not export in windows. Then I add `TVM_DLL` to `class ComputeOpNode` thus it works.

**Comment by tqchen** [comment]
@webbery can you open send a patch to fix this?

**Comment by alirezag** [comment]
Same error here. Any resolution yet?

**Comment by tqchen** [comment]
fixed thanks to @webbery
