### ISSUE TITLE
Feature request improve usability with inspection

### ISSUE THREAD

**Issue by dtmoodie** [dmlc/tvm#1166]
As far as I can tell there is no way of inspection which functions are exposed by a module once loaded. And thus the only way for me to know how to interact with a loaded module is by looking at examples to see what other people see doing.
I'd like a feature to query a loaded module for at least a list of the names of functions that I can access.

**Comment by srkreddy1238** [comment]
@dtmoodie Are u talking about the compiled module loaded on tvm runtime ?

The fused operators are available in json file in each node.
Not sure if you are looking for it.

I think we could discuss on https://discuss.tvmlang.org/ until it yields some work.

**Comment by dtmoodie** [comment]
@srkreddy1238 

I don't mean the operators of my graph but the exposed functions of the compiled module.  IE when I call mod.GetFunction("load_params");  Where is a list of all possible functions that can be accessed?  I found while digging through mxnet's nnvm backend that there is a "set_stream" function, but I have no idea how I would have found that other than through digging through code.

**Comment by dtmoodie** [comment]
Hello,
Sorry for the confusion, in mxnet there appears to be a [set_stream ](https://github.com/apache/incubator-mxnet/blob/3545697210edebe02ef68bad7465c3054d34313d/src/nnvm/tvm_bridge.cc)function that is imported when using tvm modules.

**Comment by tqchen** [comment]
this top is better suited at https://discuss.tvm.ai/ forum.

It is possible to support adding list of function names, specifically, we could ask each module to optionally register a function ```___dir___```, which when called, return list of names. We cannot force all the modules to support this though, since we want to keep things minimum.
