### ISSUE TITLE
ir_builder for gpu backend

### ISSUE THREAD

**Issue by liangfu** [dmlc/tvm#1180]
As some of the `topi` operators are implemented with `ir_builder` (e.g. `nms`), and they are currently only available for `llvm` backend. I'm wondering how to create a port for these operators to be available for other backends, such as `opencl` and `cuda`.

I think the major problem is with the `ExternOp`, which doesn't have an `axis` to be bind with GPU threads. Most other operators are portable to GPUs mostly because they are base on `ComputeOp`, which does have an `axis` attribute.

**Comment by tqchen** [comment]
this discussion is better suitable for the forum https://discuss.tvmlang.org/ It is possible to use GPUs in extern ops. We cannot do explicit schedule, but we can directly create a thread_extent scope that represents the GPU threads, take a look at IR generated by a common GPU schedule and modify the builder to construct these IRs will serve the purpose

**Comment by liangfu** [comment]
Thanks for your answer, and I would put future discussions to the forum.
As a further notice, I've tested with IR generated by a common GPU schedule.
I observe that before binding to gridIdx and threadIdx, the IR looks like this

```
// attr [compute(C, 0x1aec650)] realize_scope = ""
realize C([0, n]) {
  produce C {
    for (i, 0, n) {
      C(i) =(A(i) + B(i))
    }
  }
}
```

And after binding to gridIdx and threadIdx, the IR looks like this:

```
// attr [compute(C, 0x1b8f270)] realize_scope = ""
realize C([0, n]) {
  produce C {
    // attr [iter_var(blockIdx.x, , blockIdx.x)] thread_extent = ((n + 255)/256)
    // attr [iter_var(threadIdx.x, , threadIdx.x)] thread_extent = 256
    if (likely(((threadIdx.x + (blockIdx.x*256)) < n))) {
      if (likely(((threadIdx.x + (blockIdx.x*256)) < n))) {
        C((threadIdx.x + (blockIdx.x*256))) =(A((threadIdx.x + (blockIdx.x*256))) + B((threadIdx.x + (blockIdx.x*256))))
      }
    }
  }
}
```

The above IR are generated by following statement,
``` python
s = s.normalize()                         
bounds = tvm.schedule.InferBound(s)       
stmt = tvm.schedule.ScheduleOps(s, bounds)
```
