### ISSUE TITLE
C++ Compiler API

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#1184]
Given that there is enough attention to the c++ compiler. I am creating this issue by elaborating the technical issues around this. 

## Benefit and Feasibility
Once we move everything to C++, we can expose the compiler API via PackedFunc to any front-end language we like. So everything still only depends on TVM's core C API but takes benefit of getting compiler support

This is definitely feasible, as the tvm and nnvm core are built up in C++. The python API themselves are C++ functions exposed to python.

This being said, we do take benefit of using python as a quick hook to access things like python callbacks and quick prototyping up things. So python API will continue to exist. 

The general idea of migration is that we will move stable more part to C++, and expose them via PackedFunc. Contributions are welcomed. So far @alex-weaver has been championing this, and we would definitely interested in getting contributions.

## Necessary Steps
- [x] Move basic version of tvm compiler API to c++ https://github.com/dmlc/tvm/pull/667
- [x] Move basic ops of topi to C++ https://github.com/dmlc/tvm/pull/763
- [ ] Move nnvm registration of the basic topi operators to c++
     - This is easy as long as topi functions are in C++
     - They actually originally belong to C++ and we moved them to python for flexibility
- [ ] Basic version of environment target system(like tvm.target), hopefully, compatible with python. this is needed for target-dependent dispatching when necessary.
- [ ] NNVM build function.

These steps will get us a functional compiler. Note that we do not yet plan to move the convolution schedules officially to C++ as they are still in flux, but it is possible to port these directly.

**Comment by adityaatluri** [comment]
I am interested in this too. I have a pet project trying to do the same but a little less verbose.

**Comment by srkreddy1238** [comment]
+1 

As I remember the last discussion on this was about target specific schedule selection from cpp.

We could start by revisiting the NNVM tracker.

**Comment by tqchen** [comment]
close due to inactive status, there are newer threads on related issues

**Comment by tqchen** [comment]
#3082
