### ISSUE TITLE
[SGX] Build Migration Updates

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#1194]
- [ ] CMake migration
- [ ] NNVM example migration

cc @nhynes now that nnvm is merged into tvm, we need to merge nnvm/examples/sgx to apps/sgx as a single example

**Comment by tqchen** [comment]
@nhynes can you act on this issue?

**Comment by nhynes** [comment]
hrm.. the current best way to use TVM in SGX is via Rust. The C++ is still segfaulting for unknown reasons. I could _try_ to update the C++ version, but it's not the preferred interface imho. How would you like to proceed?

**Comment by tqchen** [comment]
Let us update the c++ interface to make sure it is complete

**Comment by tqchen** [comment]
closed by https://github.com/dmlc/tvm/pull/1763
