### ISSUE TITLE
Getting a crash on a MacBook Pro 13' with Intel GPU

### ISSUE THREAD

**Issue by acostin1** [dmlc/tvm#1204]
I am trying tvmlang on my Mac OS 13.3, MacBook pro 13 with just a mere Intel GPU 550. I am unable to compile any model - I get this error

I compiled with support for metal, cuda, opencl, opengl (I manually installed glfw3 and modified config.mk to add the following flags)
# the additional link flags you want to add
ADD_LDFLAGS = -lglfw3

# the additional compile flags you want to add
ADD_CFLAGS = -framework Cocoa -framework OpenGL -framework IOKit -framework CoreVideo

No matther what sample I try to run, I get this error. Is metal supported with Intel GPUs?

Alexandru

acostin-macOS:nnvm acostin$ python from_onnx.py 
Downloading from url https://gist.github.com/zhreshold/bcda4716699ac97ea44f791c24310193/raw/93672b029103648953c4e5ad3ac3aadf346a4cdc/super_resolution_0.2.onnx to super_resolution.onnx
File cat.png existed, skip.
[20:18:34] src/runtime/metal/metal_device_api.mm:118: Intializing Metal device 0, name=Intel(R) Iris(TM) Graphics 550
Traceback (most recent call last):
  File "from_onnx.py", line 81, in <module>
    m = graph_runtime.create(graph, lib, ctx)
  File "/Users/acostin/.local/lib/python2.7/site-packages/tvm-0.4.0-py2.7-macosx-10.6-x86_64.egg/tvm/contrib/graph_runtime.py", line 44, in create
    return GraphModule(fcreate(graph_json_str, libmod, device_type, device_id), ctx)
  File "/Users/acostin/.local/lib/python2.7/site-packages/tvm-0.4.0-py2.7-macosx-10.6-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/Users/acostin/.local/lib/python2.7/site-packages/tvm-0.4.0-py2.7-macosx-10.6-x86_64.egg/tvm/_ffi/base.py", line 66, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [20:18:34] src/runtime/graph/graph_runtime.cc:503: Check failed: ret == 0 (-1 vs. 0) [20:18:34] src/runtime/c_runtime_api.cc:88: Check failed: allow_missing Device API gpu is not enabled.

**Comment by tqchen** [comment]
please ask general questions at https://discuss.tvm.ai/ in your case, we will need to change the target context to metal(0) instead of gpu(0)(which means cuda)

**Comment by acostin1** [comment]
Hi Tianqi.

Thanks for the note. I'll try now. BTW - installation instructions improved dramatically in the last week. I like your project and I am curious to see how it will improve the performance of models on desktop in particular.

As a funny note though - as TVM is trying to make neural networks fast everywhere, on all GPUs and CPUs, is there a way to refactor the API reflect that? (like tvm.gpu(0) should be my GPU not my Cuda endpoint). Or maybe improve the sample app to be more portable...

A

**Comment by rumusan** [comment]
hi @acostin1 
can u give some tips how to install tvm in macbook?
thanks.
