### ISSUE TITLE
Why TVMArgValue does not support float

### ISSUE THREAD

**Issue by PariksheetPinjari909** [dmlc/tvm#1211]
While analyzing some other issue, i just fumbled upon below error
 **## error: conversion from ‘tvm::runtime::TVMArgValue’ to ‘float’ is ambiguous**

I resolved it by changing the parameter type to double.

But just curious to know why Float is not supported if double is supported.

**Comment by tqchen** [comment]
This discussion is better suited at discuss forum. We didn't support float to make the FFI interface simple, as double is enough to pass arguments around. It also reflects the fact that python only have int and float types and do not distinguish between float and double
