### ISSUE TITLE
running time of the generated cuda code

### ISSUE THREAD

**Issue by lewisgit** [dmlc/tvm#1224]
I use "get_source()" api to get the source code of the generated cuda code, and compile it using nvcc.
It shows that the kernel's running time is 640ms. But the time_evaluator tells me, the running time is 20ms.
I wonder why this happens.
I use -O3 as my compile option, am I missing some critical compile options?

**Comment by tqchen** [comment]
please use https://discuss.tvm.ai/ for general questions

**Comment by lewisgit** [comment]
@tqchen hi, i created my account on the forum, and my account was on hold. I havent created a topic yet. So can you check my account, and see what's the problem. Sorry for posting the question here.
