### ISSUE TITLE
I got "C:\Users\Phenix\AppData\Local\Temp\tmp2s9ib2fk\dllmain.obj : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'" error when run get_started.py in win10 with vs2015

### ISSUE THREAD

**Issue by PhenixI** [dmlc/tvm#1229]
Hi, 
When I run get_started.py in win10, I got the following errors:
C:\Program Files (x86)\Microsoft Visual Studio 14.0>python E:\dl_projects\tvm\get_started.py
<class 'tvm.tensor.Tensor'>
-----GPU code-----
extern "C" __global__ void myadd__kernel0( float* __restrict__ C,  float* __restrict__ A,  float* __restrict__ B, int n) {
  if (((int)blockIdx.x) < (n / 64)) {
    C[((((int)blockIdx.x) * 64) + ((int)threadIdx.x))] = (A[((((int)blockIdx.x) * 64) + ((int)threadIdx.x))] + B[((((int)blockIdx.x) * 64) + ((int)threadIdx.x))]);
  } else {
    if ((((int)blockIdx.x) * 64) < (n - ((int)threadIdx.x))) {
      C[((((int)blockIdx.x) * 64) + ((int)threadIdx.x))] = (A[((((int)blockIdx.x) * 64) + ((int)threadIdx.x))] + B[((((int)blockIdx.x) * 64) + ((int)threadIdx.x))]);
    }
  }
}

Traceback (most recent call last):
  File "E:\dl_projects\tvm\get_started.py", line 196, in <module>
    cc.create_shared(temp.relpath("myadd.so"), [temp.relpath("myadd.o")])
  File "C:\Users\Phenix\AppData\Roaming\Python\Python36\site-packages\tvm-0.4.0-py3.6-win-amd64.egg\tvm\contrib\cc.py", line 35, in create_shared
    _windows_shared(output, objects, options)
  File "C:\Users\Phenix\AppData\Roaming\Python\Python36\site-packages\tvm-0.4.0-py3.6-win-amd64.egg\tvm\contrib\cc.py", line 120, in _windows_shared
    raise RuntimeError(msg)
RuntimeError: Compilation error:
Microsoft (R) Incremental Linker Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.

C:\Users\Phenix\AppData\Local\Temp\tmp2s9ib2fk\dllmain.obj : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'

Can any help me?

**Comment by tqchen** [comment]
please ask general questions at https://discuss.tvm.ai/
