### ISSUE TITLE
[ONNX] Fix Filed t is not supported in nnvm

### ISSUE THREAD

**Issue by pallabdatta** [dmlc/tvm#1236]
Hi 
I have a ONNX file exported via pytorch4. Now I import the ONNX file via NNVM as:
onnx_graph = onnx.load('network.onnx')
Then when I do:

sym, params = nnvm.frontend.from_onnx(onnx_graph)
I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pallabdatta/nnvm_tvm_npcompiler/np-compiler/tvm/nnvm/python/nnvm/frontend/onnx.py", line 709, in from_onnx
    sym, params = g.from_onnx(graph, opset)
  File "/Users/pallabdatta/nnvm_tvm_npcompiler/np-compiler/tvm/nnvm/python/nnvm/frontend/onnx.py", line 572, in from_onnx
    attr = self._parse_attr(node.attribute)
  File "/Users/pallabdatta/nnvm_tvm_npcompiler/np-compiler/tvm/nnvm/python/nnvm/frontend/onnx.py", line 621, in _parse_attr
    "Filed {} is not supported in nnvm.".format(f))
NotImplementedError: Filed t is not supported in nnvm.

Can you please help me how to fix this error in tvm/nnvm/python/nnvm/frontend/onnx.py and associated backend?!
thanks a lot,
Pallab

**Comment by pallabdatta** [comment]
HI @tqchen 

this issue is also related to: https://github.com/dmlc/nnvm/issues/433

Can you please suggest me how to fix this issue so that I can import the ONNX model via NNVM FrontEnd.

**Comment by tqchen** [comment]
@fumihwh can you suggest possible fix to this issue?

**Comment by fumihwh** [comment]
@tqchen @pallabdatta 
Field `t` means current node has one attribute which type is tensor. BTW, `g` for `graph` is also not supported.
I think `tensor` is quite easier to parse than `graph`.
By using `onnx.mapping.STORAGE_TENSOR_TYPE_TO_FIELD`, we can get value of tensor.
Try:
```
proto = a.t
field = mapping.STORAGE_TENSOR_TYPE_TO_FIELD[
              mapping.TENSOR_TYPE_TO_STORAGE_TENSOR_TYPE[proto.data_type]]
vals = getattr(proto, field)
attrs[a.name] = vals
```

**Comment by tqchen** [comment]
@fumihwh since you know how to do so, it would be really nice if you could help send a PR to fix onnx frontend for this case. Thanks!

**Comment by fumihwh** [comment]
@pallabdatta Could you give me an ONNX pb to test?

**Comment by pallabdatta** [comment]
Hi Wenhao

Attached is a network with a Constant node.

**Comment by pallabdatta** [comment]
Attached it as a .log file.

[network.log](https://github.com/dmlc/tvm/files/2107102/network.log)

**Comment by fumihwh** [comment]
@pallabdatta 
Plz send your network again...
The above comment does not contain any info about that..

**Comment by pallabdatta** [comment]
Can you access the network from here:

https://drive.google.com/drive/folders/16Fe-9iR6Z-181u_WmpG0j7YsozbXV-u1

**Comment by fumihwh** [comment]
@pallabdatta Plz grant permission..

**Comment by pallabdatta** [comment]
Done..

**Comment by fumihwh** [comment]
@pallabdatta not yet...I can't access that......

**Comment by pallabdatta** [comment]
Can you please try now..

**Comment by fumihwh** [comment]
@pallabdatta Could you try #1300 ?

**Comment by pallabdatta** [comment]
Thank you @fumihwh it works now..!!
