### ISSUE TITLE
[BUILD][RFC] Switch to Use CMake only for library build

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#1250]
So far we have maintained two build systems, but as the project grows we see a lot of burdens continuously doing so. 

The only reason we kept Makefile is that for small devices like raspberry pi the CMake version may not be up to date having a Makefile build is convenient for runtime only build with minimum dependency. CMake itself is not very hard to install though, so one way would be simply required CMake and add clear instruction on how to install it.

Here are steps toward migration.

- [x] Migrate the CI to use CMake by default
- [x] Redirect the current Makefile to CMake
   - The existing options like lint will be still in Makefile

**Comment by tqchen** [comment]
This might have implications on jvm and other build. cc @nhynes @yzhliu @tmoreau89

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/1254

**Comment by tqchen** [comment]
@nhynes I have migrated most of the changes, but don't know how to migrate the build rule for SGX, so now the CMake rules for SGX runtime is missing. Can you help with subsequent PR to fix SGX runtime build?

**Comment by nhynes** [comment]
Will do! I've actually been working on updating the NNVM example, too, but I'm encountering some memory allocator issues (which prompted me to start the Rust runtime in the first place).
