### ISSUE TITLE
use multicore CPU

### ISSUE THREAD

**Issue by kaishijeng** [dmlc/tvm#1258]
@tqchen 

I noticed that from_mxnet.py and from_tensorflow.py uses only 1 core during running. My platform is RK3399 which has 6 cores (2xA72+4xA53). Is there a way to use all 6 cores to speed up?

Another issue is from_mxnet.py and from_tensorflow.py using little processor (A53) even I use taskset to constrain them on A72. Any idea why?

Thanks,

**Comment by tqchen** [comment]
Thanks for bringing the questions up, please use https://discuss.tvm.ai/ for general discussions.
