### ISSUE TITLE
[OP] SSD gluon-cv  model support

### ISSUE THREAD

**Issue by kevinthesun** [dmlc/tvm#1269]
This PR https://github.com/dmlc/tvm/pull/1214#issuecomment-396759006 adds support for SSD model. It would provide a more convenient way to import and compile SSD model if we can also support gluon-cv SSD model. The major work is to add several operators:
- [x] L2Normalization
- [ ]  _contrib_box_nms
Currently we have nms operator implemented in tvm, but the interface can be a slightly different.
I'll make another PR to deal with these changes. Rewrite mms with hybrid frontend: https://github.com/dmlc/tvm/issues/1322
- [x] slice_like
- [x] where

**Comment by kevinthesun** [comment]
This PR https://github.com/dmlc/tvm/pull/1157 implements L2Normalization.

**Comment by tqchen** [comment]
@kevinthesun can you revisit and update the status of this issue?

**Comment by tqchen** [comment]
close due to inactive status, please reopen with new items

**Comment by shesung** [comment]
slice_axis seems not supported in nnvm

**Comment by p517332051** [comment]
slice_axis seems not supported in nnvm

**Comment by p517332051** [comment]
NotImplementedError: Operator: slice is not supported in nnvm.

**Comment by p517332051** [comment]
axis : tuple of <int>, optional, default=[]
    List of axes on which input data will be sliced according to the corresponding size of the second input. By default will slice on all axes. Negative axes are supported.
, in operator slice_like(name="", axes="(2, 3)")
