### ISSUE TITLE
[BUILD] Enable optional standalone spirv-tools

### ISSUE THREAD

**Issue by doctaweeks** [dmlc/tvm#1275]
libspirv.h is packaged with spirv-tools: spirv-tools/libspirv.h

**Comment by tqchen** [comment]
hmm, does this change happens in the recent VulkanSDK? Normally files will be copied if you do build tools after you install vulkan sdk

**Comment by tqchen** [comment]
The default build assumes the installation of vulkan sdk https://vulkan.lunarg.com/sdk/home, which comes with spirv-tools, and if you run ./build_tools.sh under the sdk root, you should be able to get spirv-tools in the corresponding folder. If you use a standalone spirv-tools, maybe we need to update the CMake search rule to do so

**Comment by doctaweeks** [comment]
I have a standalone spirv-tools. I think updating the search rule would be useful for any distro that packages the vulkan components separately.

**Comment by tqchen** [comment]
This likely involves modification of the following two files
- https://github.com/dmlc/tvm/blob/master/cmake/modules/Vulkan.cmake
- https://github.com/dmlc/tvm/blob/master/cmake/util/FindVulkan.cmake
 
We can introduce an optional option USE_SPRIV and use that info when this is set

**Comment by doctaweeks** [comment]
Rather than an option I think it's fine to check for one, then the other, and just use the one that's found. I suspect it's unlikely for someone to have it installed both ways.

**Comment by tqchen** [comment]
@doctaweeks any updates on this? would you like to send a patch?

**Comment by doctaweeks** [comment]
I haven't had a chance to revisit this in depth yet.

I can add that a complete fix for this will be a little more complicated. There is a separate pkgconfig file for spirv-tools that should probably be used (currently "find_package(Vulkan").

I'll try to get to it this week.

**Comment by tqchen** [comment]
close by #1298
