### ISSUE TITLE
nnvm can't be built in MXNet after commit b877687.

### ISSUE THREAD

**Issue by zheng-da** [dmlc/tvm#1285]
After this commit https://github.com/dmlc/tvm/commit/b877687fbeb8a6c12b62aac9869f7e54091395f4
nnvm can't be built in MXNet.

**Comment by tqchen** [comment]
A better way would be moving forward to modify . https://github.com/apache/incubator-mxnet/blob/master/CMakeLists.txt#L583 to remove the link to nnvm, and instead, add ${NNVMSOURCE} to the compiled source

**Comment by tqchen** [comment]
https://github.com/apache/incubator-mxnet/pull/11300
