### ISSUE TITLE
[DOC][Tutorial] How to write a pass in python

### ISSUE THREAD

**Issue by ehsanmok** [dmlc/tvm#1308]
@tqchen As part of roadmap v0.4, I'd like to write a tutorial on how to write a pass in python, but I'll need to know more details. Could you point me where to look for and what the goals are more specifically?

**Comment by tqchen** [comment]
@were @ZihengJiang may have more suggestions to provide. The goal is to understand how to do low level IR transformations, and related python function to do so.

Doing so a simple example task, like(mark a serial loop as parallel), or replace a pattern with intrinsic, would be a useful thing

**Comment by tqchen** [comment]
also cc @xqdan @libing4752

**Comment by tqchen** [comment]
@were would you be interested in this?

**Comment by tqchen** [comment]
pass means transformations between IRs, so these are approperiate @were

**Comment by were** [comment]
OK. Then essentially, what we want on the tutorial becomes how to gather information via IR and how to transform the IR.

**Comment by were** [comment]
I have written one #1671, but it is still crashing when building docs. Anyone can help?

**Comment by were** [comment]
Since #1671 is merged, should we close this issue?

**Comment by tqchen** [comment]
Thanks to @were , this is closed by #1671
