### ISSUE TITLE
Unexpected result when I use compute_at

### ISSUE THREAD

**Issue by kun-zh** [dmlc/tvm#1316]
The case is shown as below:

import tvm

A = tvm.placeholder((15,), name='A')
B = tvm.compute((15,), lambda i: A[i]+1, name='B')
C = tvm.compute((5,3), lambda i, j: B[i+j*5]*2, name='C')
s = tvm.create_schedule(C.op)
s[B].compute_at(s[C],s[C].op.axis[0])
print(tvm.lower(s, [A, B, C], simple_mode=True))

And I get the result as below:
produce C {
  for (i, 0, 5) {
    produce B {
      for (i, 0, 11) {
        B[(i + i)] = (A[(i + i)] + 1.000000f)
      }
    }
    for (j, 0, 3) {
      C[((i*3) + j)] = (B[(i + (j*5))]*2.000000f)
    }
  }
}

Seems this is an error? @tqchen

**Comment by merrymercy** [comment]
It is right. Although there are two axes with the same name `i`, tvm does not distinguish axes by name.
To avoid the name conflict, you can replace `i` with `k` in `B = tvm.compute((15,), lambda i: A[i]+1, name='B')`

**Comment by tqchen** [comment]
Please raise this discussion question at https://discuss.tvm.ai/ @merrymercy seems to provide a reasonable answer,

**Comment by xqdan** [comment]
that's not Kun talking about, the result is 
```
produce C {
  for (i, 0, 5) {
    produce B {
      for (i, 0, 11) {
        B[(i + i)] = (A[(i + i)] + 1.000000f)
      }
    }
    for (j, 0, 3) {
      C[((i*3) + j)] = (B[(i + (j*5))]*2.000000f)
    }
  }
}
```
however we are expecting
```
produce C {
  for (i, 0, 5) {
    produce B {
      for (i, 0, 3) {
        B[(i + i)] = (A[(i + i)] + 1.000000f)
      }
    }
    for (j, 0, 3) {
      C[((i*3) + j)] = (B[(i + (j*5))]*2.000000f)
    }
  }
}
```

**Comment by merrymercy** [comment]
Because the range inference of `compute_at` only supports continuous layout.
To compute C, if we only support fetch a continuous range of B, then 11 = (3-1) * 5 + 1 is the minimum. So I say it is correct..

**Comment by xqdan** [comment]
I see, is it possible to support fetching with stride?
