### ISSUE TITLE
[TOPI] Migrate Vision Kernel from IRBuilder to Hybrid Script

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#1322]
Now that hybrid script is merged in, we should start migrating the ir_builder code into the hybrid script.

- see [lanugage ref to hybrid script](https://docs.tvm.ai/langref/hybrid_script.html)

## Action Items
- [ ] Migrate vision code to use the hybrid script
- [ ] List possible problems on using the hybrid script and report back to the issue, when possible, fix it.

**Comment by tqchen** [comment]
cc @kevinthesun

**Comment by were** [comment]
If there are any problems with this frontend, please feel free to ping me. I will fix it asap.

**Comment by kevinthesun** [comment]
Will try this out.

**Comment by tqchen** [comment]
Please update status on this

**Comment by kevinthesun** [comment]
@were is working on some fixes for hybrid script.

**Comment by kevinthesun** [comment]
Yes. I'll start on this.
