### ISSUE TITLE
RPC Proxy upload failing to Android phone target

### ISSUE THREAD

**Issue by dayanandasiet** [dmlc/tvm#1334]
RPC proxy upload failing on latest master, this is recent induced with Tracker design changes? any solution?
`user@user-VirtualBox:~/shared-windows7/work_nnvm/work_tvm/apps/android_rpc$ python tests/android_rpc_test.py 
Run CPU test ...
Traceback (most recent call last):
  File "tests/android_rpc_test.py", line 74, in <module>
    test_rpc_module()
  File "tests/android_rpc_test.py", line 63, in test_rpc_module
    remote.upload(path_dso2)
  File "/home/user/.local/lib/python3.6/site-packages/tvm-0.4.0-py3.6-linux-x86_64.egg/tvm/contrib/rpc/client.py", line 85, in upload
    "tvm.contrib.rpc.server.upload")
  File "/home/user/.local/lib/python3.6/site-packages/tvm-0.4.0-py3.6-linux-x86_64.egg/tvm/contrib/rpc/client.py", line 41, in get_function
    return self._sess.get_function(name)
  File "/home/user/.local/lib/python3.6/site-packages/tvm-0.4.0-py3.6-linux-x86_64.egg/tvm/_ffi/function.py", line 103, in get_function
    ctypes.byref(ret_handle)))
  File "/home/user/.local/lib/python3.6/site-packages/tvm-0.4.0-py3.6-linux-x86_64.egg/tvm/_ffi/base.py", line 66, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [15:34:18] /home/user/shared-windows7/work_nnvm/work_tvm/src/runtime/rpc/rpc_session.cc:808: Check failed: code == RPCCode::kReturn code=4

Stack trace returned 10 entries:
[bt] (0) /home/user/.local/lib/python3.6/site-packages/tvm-0.4.0-py3.6-linux-x86_64.egg/tvm/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x53) [0x7fb3b94a9f23]
[bt] (1) /home/user/.local/lib/python3.6/site-packages/tvm-0.4.0-py3.6-linux-x86_64.egg/tvm/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x39) [0x7fb3b94aa799]
[bt] (2) /home/user/.local/lib/python3.6/site-packages/tvm-0.4.0-py3.6-linux-x86_64.egg/tvm/libtvm.so(+0x5cd2e9) [0x7fb3b98b52e9]
[bt] (3) /home/user/.local/lib/python3.6/site-packages/tvm-0.4.0-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::runtime::RPCModuleNode::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<tvm::runtime::ModuleNode> const&)+0x74d) [0x7fb3b98b058d]
[bt] (4) /home/user/.local/lib/python3.6/site-packages/tvm-0.4.0-py3.6-linux-x86_64.egg/tvm/libtvm.so(TVMModGetFunction+0x7d) [0x7fb3b987309d]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fb3beecedae]
[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7fb3beece71f]
[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x4cd) [0x7fb3bf0e2a4d]
[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x87b7) [0x7fb3bf0d97b7]
[bt] (9) python3(_PyObject_FastCallDict+0xa3) [0x45a0e3]
`

**Comment by eqy** [comment]
Are you using the tracker in this case? A tracker restart is required if the RPC proxy server was updated.

Otherwise can you link an example? (seems to work with and without tracker in my case)

**Comment by tqchen** [comment]
please move the general discussion to https://discuss.tvm.ai/
