### ISSUE TITLE
The elapsed time of   set_input(data',....)

### ISSUE THREAD

**Issue by nj0904107027** [dmlc/tvm#1353]
I  test  yoloV2   on   RK3399    platform  using    mali   gpu  ,but The elapsed time  of   set_input(‘data’,...) 
is about 5 second   when  I set new image .  I  wonder why  it  is so  slow 。

**Comment by PariksheetPinjari909** [comment]
Are you using darknet api to load the image? Please check, as the darknet api resizes the image. Can you provide a code snippet? That will help us to understand the issue.

**Comment by tqchen** [comment]
please use https://discuss.tvm.ai  for general discussions. Thanks!
