### ISSUE TITLE
REMOVE_ITEM error with LLVM

### ISSUE THREAD

**Issue by pvn25** [dmlc/tvm#1359]
I'm trying to build TVM and related libraries on Windows Machine and I get this error:

-- Build with RPC support...
-- Build with Graph runtime support...
CMake Error at cmake/util/FindLLVM.cmake:21 (list):
  list sub-command REMOVE_ITEM requires list to be present.
Call Stack (most recent call first):
  cmake/modules/LLVM.cmake:5 (find_llvm)
  CMakeLists.txt:171 (include)

-- Build with LLVM
-- Set TVM_LLVM_VERSION=00
-- Configuring incomplete, errors occurred!

I've directly set: set(USE_LLVM ON)

**Comment by tqchen** [comment]
please move discussion on installation to discuss.tvm.ai. 

Your case could mean llvm is not available in your system, or something is wrong in the cmake build, it would be preferably if you can debug it a bit. E.g. add message(STATUS "LLVM_LIBS" ${LLVM_LIBS}) in https://github.com/dmlc/tvm/blob/master/cmake/util/FindLLVM.cmake#L21 to see what are the library.

It could be possible you didn't have a llvm built from source in windows
