### ISSUE TITLE
Does TVM support multiple GPUs or multiple streams?

### ISSUE THREAD

**Issue by ljppro** [dmlc/tvm#1360]
Hi,

Just as title. In some cases, some compute nodes in a graph are not dependent on other nodes, so we can put two set of nodes into two CUDA streams and let them run in GPU independently.  Can TVM calculate how many independent computation set there are in the graph and put each set into different streams?

Thanks!

**Comment by srkreddy1238** [comment]
We don't support now.

We could move this topic to discuss.tvm.ai
