### ISSUE TITLE
Tutorial Compile the model on NNVM can't run

### ISSUE THREAD

**Issue by ljppro** [dmlc/tvm#1361]
Hi,
As title.

When I run this tutorial to:
# convert the keras model(NHWC layout) to NNVM format(NCHW layout).
sym, params = nnvm.frontend.from_keras(keras_resnet50)
# compile the model
target = 'cuda'
shape_dict = {'input_1': data.shape}
with nnvm.compiler.build_config(opt_level=2):
    graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, params=params)
An error reported as:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-30d013120b4c> in <module>()
      1 # convert the keras model(NHWC layout) to NNVM format(NCHW layout).
----> 2 sym, params = nnvm.frontend.from_keras(keras_resnet50)
      3 # compile the model
      4 target = 'cuda'
      5 shape_dict = {'input_1': data.shape}

~/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/frontend/keras.py in from_keras(model)
    524                 keras_op_to_nnvm(insym, keras_layer, keras_layer.name + ':' + str(my_idx), symtab)
    525 
--> 526     outsym = symtab.get_var(model._output_layers[0].name + ':0')
    527     tvmparams = {k:tvm.nd.array(np.array(v, dtype=np.float32)) for k, v in symtab.params.items()}
    528     return outsym, tvmparams

AttributeError: 'Model' object has no attribute '_output_layers'

Can you  help me? Many thanks!

**Comment by tqchen** [comment]
please move discussions to https://discuss.tvm.ai. This is due to keras compatibility issues, please upgrade the keras  to lastest
