### ISSUE TITLE
Tutorial Compile Tensorflow Models can't be run on GPU

### ISSUE THREAD

**Issue by ljppro** [dmlc/tvm#1362]
Hi,

When I run this tutorial on target LLVM, it's OK. But if I set the target to cuda, it will report error. Does TVM 0.4 not support Tensorflow on GPU yet?

Thanks!

**Comment by srkreddy1238** [comment]
Can you share the error log ?

**Comment by ljppro** [comment]
When run to this:
import nnvm.compiler
target = 'cuda'
shape_dict = {'DecodeJpeg/contents': x.shape}
dtype_dict = {'DecodeJpeg/contents': 'uint8'}
graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, dtype=dtype_dict, params=params)

it reports:
---------------------------------------------------------------------------
NNVMError                                 Traceback (most recent call last)
<ipython-input-20-752908cf5647> in <module>()
      3 shape_dict = {'DecodeJpeg/contents': x.shape}
      4 dtype_dict = {'DecodeJpeg/contents': 'uint8'}
----> 5 graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, dtype=dtype_dict, params=params)

~/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/compiler/build_module.py in build(graph, target, shape, dtype, params, target_host, layout)
    292     graph = graph.apply("InferShape").apply("InferType")
    293     with target:
--> 294         graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
    295     libmod = graph_attr._move_out_module(graph, "module")
    296     # Write variable initial values into params

~/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/graph.py in apply(self, passes)
    232         ghandle = GraphHandle()
    233         npass = nn_uint(len(passes))
--> 234         check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
    235         return Graph(ghandle)
    236 

~/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/_base.py in check_call(ret)
     73     """
     74     if ret != 0:
---> 75         raise NNVMError(py_str(_LIB.NNGetLastError()))
     76 
     77 def c_str(string):

NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/home/***/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/root/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/top/nn.py", line 106, in compute_conv2d
    inputs[0], kernel, strides, padding, layout, out_dtype=out_dtype)
  File "<decorator-gen-159>", line 2, in conv2d
  File "/home/***/tvm/python/tvm/target.py", line 345, in dispatch_func
    return dispatch_dict[k](*args, **kwargs)
  File "/home/***/tvm/topi/python/topi/cuda/conv2d.py", line 83, in conv2d_cuda
    raise ValueError("not support this layout {} yet".format(layout))
ValueError: not support this layout NHWC yet


Thanks!

**Comment by masahi** [comment]
NHWC layout is only supported on x86 backend.

**Comment by ljppro** [comment]
Hi masahi, (@masahi )
I was using "cuda" as target and set the GPU as following, instead of using x86 backend:
# Import the graph to NNVM
sym, params = nnvm.frontend.from_tensorflow(graph_def)

# compile the graph through NNVM
import nnvm.compiler
target = 'cuda'
shape_dict = {'DecodeJpeg/contents': x.shape}
dtype_dict = {'DecodeJpeg/contents': 'uint8'}
graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, dtype=dtype_dict, params=params)


# Execute the portable graph on TVM
time.sleep(5)

from tvm.contrib import graph_runtime
ctx = tvm.gpu(1)
dtype = 'uint8'
m = graph_runtime.create(graph, lib, ctx)
# set inputs
m.set_input('DecodeJpeg/contents', tvm.nd.array(x.astype(dtype)))
m.set_input(**params)
# execute
m.run()
# get outputs
tvm_output = m.get_output(0, tvm.nd.empty(((1, 1008)), 'float32'))

And the error reported as:
Traceback (most recent call last):
  File "test.py", line 73, in <module>
    graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, dtype=dtype_dict, params=params)
  File "/root/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/compiler/build_module.py", line 294, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/root/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/root/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/_base.py", line 75, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/home/liujp/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/root/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/top/nn.py", line 106, in compute_conv2d
    inputs[0], kernel, strides, padding, layout, out_dtype=out_dtype)
  File "<decorator-gen-35>", line 2, in conv2d
  File "/home/liujp/tvm/python/tvm/target.py", line 345, in dispatch_func
    return dispatch_dict[k](*args, **kwargs)
  File "/home/liujp/tvm/topi/python/topi/cuda/conv2d.py", line 83, in conv2d_cuda
    raise ValueError("not support this layout {} yet".format(layout))
ValueError: not support this layout NHWC yet

Many thanks!

**Comment by masahi** [comment]
See the last error message. Your model is in NHWC format, which is not supported in cuda backend.

**Comment by srkreddy1238** [comment]
NHWC is not suitable for CUDA. Tensorflow could support CUDA as long as the layout is NCHW.

**Comment by tqchen** [comment]
close this for now, as the original question is answered, please move followups to https://discuss.tvm.ai/ Thanks all the people who are involved in the discussion!
