### ISSUE TITLE
Tutorial Compile Keras Models error

### ISSUE THREAD

**Issue by ljppro** [dmlc/tvm#1364]
Hi,

I want to raise this issue in discuss to https://discuss.tvm.ai, but it seems that after I open this page, it's only a blank page. So I still raise here.

I raise an issue (#1361) before. But after I update my keras, another error reported as:
keras_resnet50 = keras.applications.resnet50.ResNet50(include_top=True, weights=None,
    input_shape=(224,224,3), classes=1000)
keras_resnet50.load_weights('resnet50_weights.h5')

File resnet50_weights.h5 exists, skip.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-8b18ccd81d7a> in <module>()
      4 download(weights_url, weights_file)
      5 keras_resnet50 = keras.applications.resnet50.ResNet50(include_top=True, weights=None,
----> 6     input_shape=(224,224,3), classes=1000)
      7 keras_resnet50.load_weights('resnet50_weights.h5')

/usr/local/lib/python3.5/dist-packages/keras_applications/resnet50.py in ResNet50(include_top, weights, input_tensor, input_shape, pooling, classes)
    242         x = layers.AveragePooling2D((7, 7), name='avg_pool')(x)
    243         x = layers.Flatten()(x)
--> 244         x = layers.Dense(classes, activation='softmax', name='fc1000')(x)
    245     else:
    246         if pooling == 'avg':

/usr/local/lib/python3.5/dist-packages/keras/engine/base_layer.py in __call__(self, inputs, **kwargs)
    458             # Actually call the layer,
    459             # collecting output(s), mask(s), and shape(s).
--> 460             output = self.call(inputs, **kwargs)
    461             output_mask = self.compute_mask(inputs, previous_mask)
    462 

/usr/local/lib/python3.5/dist-packages/keras/layers/core.py in call(self, inputs)
    887             output = K.bias_add(output, self.bias)
    888         if self.activation is not None:
--> 889             output = self.activation(output)
    890         return output
    891 

/usr/local/lib/python3.5/dist-packages/keras/activations.py in softmax(x, axis)
     27     ndim = K.ndim(x)
     28     if ndim == 2:
---> 29         return K.softmax(x)
     30     elif ndim > 2:
     31         e = K.exp(x - K.max(x, axis=axis, keepdims=True))

/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py in softmax(x, axis)
   3147         A tensor.
   3148     """
-> 3149     return tf.nn.softmax(x, axis=axis)
   3150 
   3151 

TypeError: softmax() got an unexpected keyword argument 'axis'

Thanks!

**Comment by tqchen** [comment]
The error you were facing seems comes from keras and tensorflow, so not necessarily related to tvm itself. Maybe you want to upgrade your tensorflow building.

https://discuss.tvm.ai/ seems to be fine from my side, maybe you want to check your network settings and use that for future support problems
