### ISSUE TITLE
undefined symbol in libtvm from NNPACK 

### ISSUE THREAD

**Issue by aswinjohn** [dmlc/tvm#1366]
https://github.com/dmlc/tvm/blob/2693dad5aba64a181be87fdcee53df8b39e45311/cmake/modules/contrib/NNPack.cmake#L10

NNPACK_CONTRB_LIB must be NNPACK_CONTRIB_LIB

Else the error is :  
  File "/home/XXX/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/XXX/tvm/build/libtvm.so: undefined symbol: nnp_convolution_output

**Comment by tqchen** [comment]
nice catch @aswinjohn can you send a patch to fix this problem?

**Comment by tqchen** [comment]
thanks @aswinjohn for the patch closed by #1368
