### ISSUE TITLE
[FRONTEND] [HYBRID] Support schedule interfaces on hybrid script

### ISSUE THREAD

**Issue by were** [dmlc/tvm#1384]
I have an ongoing PR(#1382), which has a hacky support on manipulating IR through some IR transform passes.

@tqchen suggested that I should refine it to make it able to reuse `compute.op`-like data structures. Then my solution comes to build some kind of op node between `compute.op` and `extern.op`, which supports: `split`, `loop_type`, `pragma`, `reorder`, and `bind` schedules.
````Python
import tvm
@tvm.hybrid.script
def outer_product(a, b, c):
    for j in range(128):
        for i in range(128):
            c[i,j] = a[i] * b[j]

a = tvm.placeholder((128, ), 'float32', 'a')
b = tvm.placeholder((128, ), 'float32', 'b')
c = tvm.placeholder((128, ), 'float32', 'c')
op = outer_product(a, b, c) #Currently it returns a HalideIR root, but I want to refactor it to a HybridOpNode
sch = tvm.create_schedule(op)
jo, ji = sch[op].split(j, 16)
io, ii = sch[op].split(i, 16)
sch[op].reorder(io, ii, jo, ji)
sch[op].vectorize(ji)
````

Points to be discussed:
1. Do I really need a `HybridOpNode`?
- I can either extend `ExternOpNode` to be able to schedule or create a new Op type, but it requires aggressive refactor to fulfill my assumptions:
    - Unlike conventional op, which takes several input operands and produces one output, hybrid op takes several arguments, and side-effect may happen: a tensor argument can both be an input and an output, because users may want some in-place tensor algorithms. However, in ExternOp, there are only inputs and outputs, and only outputs allow modification on the tensor buffer.
    - It requires some compilation pass to detect some loop levels that can be manipulated by the schedule interfaces, so it requires some extra attributes to record this information. However, this information is redundant to a general ExternOpNode.
- However, yet, I have not had a clear plan for the `HybridOpNode`, like attributes and analysis
2. `sch[op]`'s `op` seems to be redundant:
- As far as I know, all the schedule properties like `split`, `vectorize`, and `bind` are members of `Stage`
- However, in hybrid script there is only one stage inside, which makes `op`, the stage specifier, looks redundant

**Comment by tqchen** [comment]
@were Can you post a complete code example so we can start discussing the API?

**Comment by were** [comment]
@kevinthesun

**Comment by xqdan** [comment]
IMO, schedule for hybrid should be some passes, in which they can do optimize for IR stream automatically,
hybrid is input for tvm, just like c/c++ is input for llvm/gcc, just see how llvm/gcc to do schedule? a lots of passes! compute is your program logic, and you don't need to do too much schedule, of course you can, compiler will do most optimizations for you. 

So the schedule api for users should be some pragmas for making hints, and in tvm, passes will optimize according to these hints.

**Comment by were** [comment]
@xqdan Several reasons for scheduling interfaces:
1. We can explore the solution space of tuning independent with the hybrid function
2. We can use some compilation techniques to detect those loop levels can be manipulated
3. We can create Operation node for this function body to make it easier to glue to an ML flow

**Comment by kevinthesun** [comment]
@were If side effect is the major issue to support schedule interfaces, can we initially just disable in-place operation for parsing? We can then reuse ExternOpNode for now and adding support for side effect later. This should be sufficient for gluoncv models.

**Comment by xqdan** [comment]
@were if you take a look at the passes of gcc, you will find lots of loop transformations. compute and schedule are also separated in compiler, the only difference here is schedule in tvm is done manually, and compiler can optimize in a automatically way or based on hints/flags from users. also gcc has very aggressive transformation like software pipelining for loops. 
https://github.com/gcc-mirror/gcc/blob/229c0ef777161ec5adfb71ef1611af502541ccda/gcc/passes.def
         ```
         NEXT_PASS (pass_tree_loop_init);
	  NEXT_PASS (pass_tree_unswitch);
	  NEXT_PASS (pass_scev_cprop);
	  NEXT_PASS (pass_loop_split);
	  NEXT_PASS (pass_loop_jam);
	  /* All unswitching, final value replacement and splitting can expose
	     empty loops.  Remove them now.  */
	  NEXT_PASS (pass_cd_dce);
	  NEXT_PASS (pass_iv_canon);
	  NEXT_PASS (pass_loop_distribution);
	  NEXT_PASS (pass_linterchange);
	  NEXT_PASS (pass_copy_prop);
	  NEXT_PASS (pass_graphite);
	  PUSH_INSERT_PASSES_WITHIN (pass_graphite)
	      NEXT_PASS (pass_graphite_transforms);
	      NEXT_PASS (pass_lim);
	      NEXT_PASS (pass_copy_prop);
	      NEXT_PASS (pass_dce);
```

making split reorder such things as tvm passes are not violating the tvm philosophy. Also I don't see any differences between pragma + passes with tvm schedule api for tuning, pragma and passes's flag also can be tuned, lots of research is about how to tune the options of compiler flags for better performance.  

For aggressive or not, and automatically or not, if controlled by users(with schedule api/pragmas/flag options), schedule or transformations are not automatic but can be aggressive. if doing by tvm itself, not aggressive but automatic, both can be options for users.

IMO, the similar story is repeating in another place, you can see operators fusion just looks like inter procedure optimizations(eg inline), and passes in tvm is intro procedure, for example, double buffer is just a subset of software pipeline, BTW, you can control double buffer in schedule api, but actually it's a real pass.

For this issue, we don't need to care about the separation thing for hybrid, that's fine, and I suggest we implement split/reorder/.. in c++ passes, and provide api for users controlling for now, and the next would be we can analyze ir stream in tvm and decide to optimize or not.

**Comment by tqchen** [comment]
It is always good to implement user control first, then start to automate them with passes

**Comment by tqchen** [comment]
@were can you start with an implementation? Currently seems things are still a bit blocked by not being able to run extern block on that, we should start with that

**Comment by were** [comment]
@tqchen Thay may require moderate modification to the structure of OpNode.
Thus, I need to be careful.

**Comment by tqchen** [comment]
You can try to modify ExternOpNode, or create a HybridOpNode to support this, and open a PR when it is ready for review

**Comment by kevinthesun** [comment]
One question is whether passing a constant argument is supported now. If not, can we pass expr, like FloatImm?
