### ISSUE TITLE
devc.cc:13549:1: error: narrowing conversion of ‘150’ from ‘int’ to ‘char’ inside { } 

### ISSUE THREAD

**Issue by shamanqing** [dmlc/tvm#1386]
I build tvm refer to  https://docs.tvm.ai/install/index.html#build-the-shared-library using ubuntu 18.04, llvm-5.0, cuda 9.2, and run the tutorial https://docs.tvm.ai/tutorials/nnvm_quick_start.html#, when in step "Save Compiled Module" get this error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-cc19166af13b> in <module>()
      9 temp = util.tempdir()
     10 path_lib = temp.relpath("deploy_lib.so")
---> 11 lib.export_library(path_lib)
     12 with open(temp.relpath("deploy_graph.json"), "w") as fo:
     13     fo.write(graph.json())

~/.local/lib/python3.6/site-packages/tvm-0.4.0-py3.6-linux-x86_64.egg/tvm/module.py in export_library(self, file_name, fcompile, **kwargs)
    116             else:
    117                 fcompile = _cc.create_shared
--> 118         fcompile(file_name, files, **kwargs)
    119 
    120     def time_evaluator(self, func_name, ctx, number, repeat=1):

~/.local/lib/python3.6/site-packages/tvm-0.4.0-py3.6-linux-x86_64.egg/tvm/contrib/cc.py in create_shared(output, objects, options, cc)
     31     """
     32     if sys.platform == "darwin" or sys.platform.startswith('linux'):
---> 33         _linux_shared(output, objects, options, cc)
     34     elif sys.platform == "win32":
     35         _windows_shared(output, objects, options)

~/.local/lib/python3.6/site-packages/tvm-0.4.0-py3.6-linux-x86_64.egg/tvm/contrib/cc.py in _linux_shared(output, objects, options, cc)
     56         msg = "Compilation error:\n"
     57         msg += py_str(out)
---> 58         raise RuntimeError(msg)
     59 
     60 

RuntimeError: Compilation error:
/tmp/tmplkrsu83a/devc.cc:13549:1: error: narrowing conversion of ‘150’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
 };
 ^
/tmp/tmplkrsu83a/devc.cc:13549:1: error: narrowing conversion of ‘190’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/tmp/tmplkrsu83a/devc.cc:13549:1: error: narrowing conversion of ‘251’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]

Some thing wrong?

**Comment by tqchen** [comment]
This have something to do with your C compiler library. Please try to print the dev.cc in here https://github.com/dmlc/tvm/blob/master/python/tvm/module.py#L110

and see if the resulting code can be compiled with your default g++. In the future, please raise these discussions in https://discuss.tvm.ai
