### ISSUE TITLE
AttributeError: ‘Model’ object has no attribute ‘output_layers’ in nnvm/frontend/keras.py

### ISSUE THREAD

**Issue by aswinjohn** [dmlc/tvm#1391]
https://github.com/dmlc/tvm/blob/941f684614bb643258986fff256f1310587471b3/nnvm/python/nnvm/frontend/keras.py#L526

Google cached solution: https://webcache.googleusercontent.com/search?q=cache:E4rBauh661UJ:https://discuss.tvm.ai/t/compile-keras-model-issue-report-and-solution-included/256+&cd=1&hl=en&ct=clnk&gl=us

outsym = symtab.get_var(model._output_layers[0].name + ':0')
must be 
outsym = symtab.get_var(model.layers[-1].name + ':0')

**Comment by kazum** [comment]
Which backend are you using for Keres?  As I wrote in the link, TVM supports Keres with the tensorflow backend only for now.  See also #1392.

Anyway, I think further discussion should be moved to https://discuss.tvm.ai/ .

**Comment by tqchen** [comment]
This is mainly due to keras versions, if you update to latest keras version it should be fine

**Comment by aswinjohn** [comment]
Using TensorFlow backend and keras-2.2.0

**Comment by schliffen** [comment]
I've got similar error:
AttributeError: 'Model' object has no attribute '_network_nodes'
which was due to Keras version conflict, choosing version 2.3 resolved the issue.
