### ISSUE TITLE
when run tvm deploy app on android, exception  at jni_helper_func.h:182

### ISSUE THREAD

**Issue by ANSHUMAN87** [dmlc/tvm#1399]
I am trying to load tvm on android, by generating tvm android deploy app.
But when i load the  module (deploy.so), i get exception  at jni_helper_func.h:182.

Please help me resolve the issue , Thanks.

**Comment by srkreddy1238** [comment]
Could move this to general discussion.

Also please share more details of the exception.

**Comment by tqchen** [comment]
move to https://discuss.tvm.ai/
