### ISSUE TITLE
[TUTORIAL] Tutorial for Vision Operators

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#1411]
now that #1095 and #1397 is added, we have a comprehensive set of vision operators in topi. It would be great if we can write a tutorial for these operators

**Comment by tqchen** [comment]
cc @zhreshold @Laurawly @kevinthesun

**Comment by Laurawly** [comment]
@tqchen Since @kevinthesun has a tutorial here: https://docs.tvm.ai/tutorials/nnvm/deploy_ssd.html#sphx-glr-tutorials-nnvm-deploy-ssd-py
Should I update this one for the GPU SSD or write a new one?

**Comment by tqchen** [comment]
We just have to update https://docs.tvm.ai/tutorials/nnvm/deploy_ssd.html#sphx-glr-tutorials-nnvm-deploy-ssd-py to introduce GPU SSD.

What I mean, however, is the topi library calls, like https://docs.tvm.ai/tutorials/topi/intro_topi.html#sphx-glr-tutorials-topi-intro-topi-py, instead of the nnvm ops.

**Comment by kevinthesun** [comment]
@tqchen You mean adding a section named "vision operators" into that tutorial?

**Comment by tqchen** [comment]
close for now due to inactive status
