### ISSUE TITLE
[Optimization] Apply multi times apply passes will result in check shape error

### ISSUE THREAD

**Issue by FrozenGene** [dmlc/tvm#1414]
This is the reduced case from real model leveraging test_fold_scale_axis.py

```python
import nnvm
import nnvm.testing.resnet
import numpy as np
from nnvm import symbol as sym
from nnvm.compiler import graph_util, graph_attr

def test_fold_axis_conv():
    def before(x, conv_weight, conv_bias, in_scale, out_scale, channels):
        x = x * sym.expand_dims(in_scale, axis=1, num_newaxis=2)
        y = sym.conv2d(x, conv_weight, conv_bias,
                       channels=channels,
                       kernel_size=(3, 3),
                       padding=(1, 1),
                       groups=54,
                       name="conv")
        y = sym.relu(y)
        y = y * sym.expand_dims(out_scale, axis=1, num_newaxis=2)
        return y

    def expected(x, conv_weight, conv_bias, in_scale, out_scale, channels):
        conv_weight = conv_weight * sym.expand_dims(out_scale, axis=1, num_newaxis=3)
        conv_weight = conv_weight * sym.expand_dims(in_scale, axis=1, num_newaxis=2)
        conv_bias = conv_bias * out_scale
        y = sym.conv2d(x,
                       conv_weight,
                       conv_bias,
                       channels=channels,
                       kernel_size=(3, 3),
                       padding=(1, 1),
                       groups=54,
                       name="conv")
        y = sym.relu(y)
        return y

    # Before simplify
    def check(shape, channels):
        x = sym.Variable("x") + 1
        weight = sym.Variable("weight", shape=(54, 1, 3, 3))
        bias = sym.Variable("bias", shape=(54,))
        in_scale = sym.Variable("in_scale")
        out_scale = sym.Variable("out_scale")
        y1 = before(x, weight, bias, in_scale, out_scale, channels)
        y2 = expected(x, weight, bias, in_scale, out_scale, channels)
        ishape = {"x": shape, "out_scale": (channels,), "in_scale": (shape[1],)}
        g1 = nnvm.graph.create(y1)
        g2 = nnvm.graph.create(y2)
        graph_attr.set_shape_inputs(g1, ishape)
        g1 = g1.apply("InferShape").apply("FoldScaleAxis")
        # The second time
        graph_attr.set_shape_inputs(g1, ishape)
        g1 = g1.apply("InferShape").apply("FoldScaleAxis")

    check((1, 54, 63, 27), 54)
test_fold_axis_conv()
```
The problem is the second time. Will result in:

Traceback (most recent call last):
  File "/Users/blue/Documents/dev/tmp/tvm/nnvm/python/nnvm/_base.py", line 75, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: [19:28:33] /Users/blue/Documents/dev/tmp/tvm/nnvm/src/top/nn/convolution.cc:91: Operator conv2d(padding=(1, 1), kernel_size=(3, 3), channels=54, name=conv) expects weight's shape to be [54,54,3,3], but got [54,1,3,3].

The second time to apply optimization is the same as apply it into g2.

**Comment by FrozenGene** [comment]
I find here:

conv_weight = conv_weight * sym.expand_dims(in_scale, axis=1, num_newaxis=2) ===> 2 becomes 3 can pass. My real situation occurred in the fold_scale_axis's optimization, which also can 'expand_dims' and has the same problem.

**Comment by FrozenGene** [comment]
The reason is FoldScaleAxis doesn't support convolution with groups (including depthwise conv2d) currently. The fix can be done modify ScaleAxisForward for conv2d. Close it.

**Comment by merrymercy** [comment]
@FrozenGene  Can you send the patch?

**Comment by FrozenGene** [comment]
@merrymercy Currently，I only fix depthwise conv2d. i.e. input channel equals to groups. 

For the input channel not equals to groups, currently, I just return false and not apply this optimization. Because I find it is not easy for fixing input channel not equals to groups, which will need to extend our struct FoldChainInfo to contain more information. And conv2d / depthwise conv2d is enough for us now, so I only fix depthwise conv2d.

Do you want to this kind of patch?

**Comment by merrymercy** [comment]
Thanks, I think it is okay for now. I also met this bug.

**Comment by merrymercy** [comment]
@FrozenGene Any update on this?

**Comment by FrozenGene** [comment]
@merrymercy I am applying the process of open source in my company, could you wait for a while? Sorry for this inconvenience.
