### ISSUE TITLE
Unable to compile VGG16 from keras.applications

### ISSUE THREAD

**Issue by avlechen** [dmlc/tvm#1425]
I have ran example from keras tutorial with resnet50 and it worked great. But after that I decided to try different model from keras and it failed. The minimal snippet to reproduce the error:

```
import keras
import nnvm
import tvm
model = keras.applications.vgg16.VGG16(include_top=True, weights='imagenet', input_tensor=None, input_shape=None, pooling=None, classes=1000)
sym, params = nnvm.frontend.from_keras(model)
target = 'metal'
shape_dict = {'input_7': (1, 3, 224, 224)}

with nnvm.compiler.build_config(opt_level=0):
    graph, lib, params = nnvm.compiler.build(sym, target, params=params)
```

The error I get: 

> NNVMError                                 Traceback (most recent call last)
> <ipython-input-5-2906185aed03> in <module>()
>       8 
>       9 with nnvm.compiler.build_config(opt_level=0):
> ---> 10     graph, lib, params = nnvm.compiler.build(sym, target, params=params)
> 
> ~/.local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/compiler/build_module.py in build(graph, target, shape, dtype, params, target_host, layout)
>     292     graph = graph.apply("InferShape").apply("InferType")
>     293     with target:
> --> 294         graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
>     295     libmod = graph_attr._move_out_module(graph, "module")
>     296     # Write variable initial values into params
> 
> ~/.local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/graph.py in apply(self, passes)
>     232         ghandle = GraphHandle()
>     233         npass = nn_uint(len(passes))
> --> 234         check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
>     235         return Graph(ghandle)
>     236 
> 
> ~/.local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/_base.py in check_call(ret)
>      73     """
>      74     if ret != 0:
> ---> 75         raise NNVMError(py_str(_LIB.NNGetLastError()))
>      76 
>      77 def c_str(string):
> 
> NNVMError: [16:40:19] /Users/lechenko/Development/tvm/nnvm/src/top/nn/nn.cc:612: Check failed: pad_width.ndim() == inputs[0]->shape.size() && pad_width[0].ndim() == 2 Illegal pad_width
> 
> Stack trace returned 10 entries:
> [bt] (0) 0   libnnvm_compiler.dylib              0x000000011af05470 dmlc::StackTrace() + 288
> [bt] (1) 1   libnnvm_compiler.dylib              0x000000011af0520f dmlc::LogMessageFatal::~LogMessageFatal() + 47
> [bt] (2) 2   libnnvm_compiler.dylib              0x000000011b02f76d std::__1::__function::__func<nnvm::top::$_18, std::__1::allocator<nnvm::top::$_18>, tvm::Array<tvm::Tensor, void> (nnvm::NodeAttrs const&, tvm::Array<tvm::Tensor, void> const&, tvm::Array<tvm::Tensor, void> const&)>::operator()(nnvm::NodeAttrs const&, tvm::Array<tvm::Tensor, void> const&, tvm::Array<tvm::Tensor, void> const&) + 525
> [bt] (3) 3   libnnvm_compiler.dylib              0x000000011af8657e nnvm::compiler::CompileEngine::GetScheduleArgs(nnvm::Graph, tvm::Array<tvm::Tensor, void> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, tvm::Array<tvm::Tensor, void>*) + 6190
> [bt] (4) 4   libnnvm_compiler.dylib              0x000000011af840f4 nnvm::compiler::CompileEngine::DoLower(nnvm::Graph, tvm::Array<tvm::Tensor, void> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) + 644
> [bt] (5) 5   libnnvm_compiler.dylib              0x000000011af83573 nnvm::compiler::CompileEngine::Lower(nnvm::Graph, tvm::Array<tvm::Tensor, void> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) + 627
> [bt] (6) 6   libnnvm_compiler.dylib              0x000000011af8324d nnvm::compiler::GraphLower(nnvm::Graph, tvm::Array<tvm::Tensor, void> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) + 333
> [bt] (7) 7   libnnvm_compiler.dylib              0x000000011afa64d3 nnvm::compiler::GraphFuseCompile(nnvm::Graph) + 8835
> [bt] (8) 8   libnnvm_compiler.dylib              0x000000011af39921 nnvm::Graph std::__1::__invoke_void_return_wrapper<nnvm::Graph>::__call<nnvm::Graph (*&)(nnvm::Graph), nnvm::Graph>(nnvm::Graph (*&&&)(nnvm::Graph), nnvm::Graph&&) + 209
> [bt] (9) 9   libnnvm_compiler.dylib              0x000000011af39812 std::__1::__function::__func<nnvm::Graph (*)(nnvm::Graph), std::__1::allocator<nnvm::Graph (*)(nnvm::Graph)>, nnvm::Graph (nnvm::Graph)>::operator()(nnvm::Graph&&) + 18

I use keras=2.2.0 and conda=4.5.5 on MacOS 10.13.5

**Comment by Huyuwei** [comment]
@avlechen I tried VGG16, it works fine with cuda target. Can you update tvm to the latest?

General questions can be moved to https://discuss.tvm.ai/

**Comment by Huyuwei** [comment]
> shape_dict = {'input_7': (1, 3, 224, 224)}

@avlechen It should be input_1. Maybe this is the reason.

**Comment by tqchen** [comment]
Thanks @Huyuwei for answering the question, please move further discussion to https://discuss.tvm.ai/
