### ISSUE TITLE
[RFC] Android RPC service performance issues

### ISSUE THREAD

**Issue by alex-weaver** [dmlc/tvm#1433]
Using a service process for RPC in Android is causing significant performance regressions (approximately by a factor of 3 on my test device).

@merrymercy identified the watchdog process commit as the cause in #1426
The service/watchdog process was added in #1387 

I've confirmed that on my device performance returns to its previous level if I roll back `MainActivity.java` to before the service/watchdog was introduced.

It is unclear precisely why this is occurring, but I've done some debugging on this and found the following:
- The issue persists if the RPCProcessor is launched in a service but the watchdog is removed. This demonstrates the performance issue is not due to the interaction with the watchdog, but simply due to running in the service process.
- Adding a timer in C++ around GraphRuntime::Run confirms that almost all of the processing time is taken by this function, and not by java code.
- I have tried setting the service as a foreground service (how to do this correctly is somewhat poorly documented), since by default service processes in Android are given lower priority than app processes[1]. This did not make any difference :(

Any ideas as to why this might be occurring would be appreciated

[1] https://medium.com/google-developers/who-lives-and-who-dies-process-priorities-on-android-cb151f39044f

@tqchen 
@eqy

**Comment by alex-weaver** [comment]
That sounds great :)

Bringing the RPCProcessor back into the activity will definitely resolve the issue, I've just been digging into this because it's somehow unsatisfying without knowing why it was broken in the first place!

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/1457

**Comment by tqchen** [comment]
close this for now as @merrymercy confirmed that the performance regression is fixed by #1457 @alex-weaver it would be great if you can also verify independently
