### ISSUE TITLE
[tensorize] tensorize after reorder will be wrong

### ISSUE THREAD

**Issue by Youjk** [dmlc/tvm#1438]
xal1, xbl1, xcl1 = s[CL].op.axis
s[CL].reorder(xbl1, xcl1, xal1)
s[CL].tensorize(xal1, concat_intrin)

S[CL] is 3-dim,intrin input tensor is 1-dim

when run the code ,it will check failed:
    for (size_t i = 0; i < e.start; ++i) {
        CHECK(is_one(e.region[i]->extent))
            << "Tensorize " << intrin->name << ":"
            << " Input dimension mismatch with tensor intrin "
            << " expected shape=" << e.tensor->shape
            << ", given region=" << e.region;
      }

It seems that once I reorder the axis of a stage,and  tensorize the last axis will check failed.

**Comment by tqchen** [comment]
please give more details and move this discussion to the forum http://discuss.tvm.ai/
