### ISSUE TITLE
Timing violation for vta hardware implementation!

### ISSUE THREAD

**Issue by liyb13** [dmlc/tvm#1475]
Hello there, I clone this repository and compile the hardware design "/tvm/vta/hardware/xilinx/". It successfully generate the bitstream but the timing closure is not satisfied. It reports WNS and TNS are -1.601,  -1198.534 respectively. My synthesis and implementation keep the default settings unchanged.

**Comment by tqchen** [comment]
please open a new thread at http://discuss.tvm.ai/ :) and i think the community will be more than happy to answer the question
