### ISSUE TITLE
Does TVM support training?

### ISSUE THREAD

**Issue by ljppro** [dmlc/tvm#1493]
Hi,
All the tutorials I can find are all about inference. Does TVM support training? If yes, where can I find a tutorial? If no, do you have a schedule to support it? Thanks!

**Comment by tqchen** [comment]
Thanks for asking the question, this is a great discussion topic that can be discussed at https://discuss.tvm.ai/

**Comment by yzhliu** [comment]
pls refer to https://discuss.tvm.ai/t/dose-tvm-support-training-models/225
