### ISSUE TITLE
[x86][Schedule]Vectorization for pooling schedule for 4D data layout

### ISSUE THREAD

**Issue by kevinthesun** [dmlc/tvm#1516]
This PR https://github.com/dmlc/tvm/pull/1506 adds vectorization for pooling on x86. Currently this works when data layout is larger than 4 dimension. For 4D data, inline padding has conflict with vectorization introduced by that PR and will cause LLVM error. I'll investigate this issue later.

Reproduce: apply vectorization function to 4D case and create a nnvm graph with a pooling operator with non-zero padding.

Track this problem in this issue.

**Comment by yzhliu** [comment]
I think it is because vectorize cannot have if...else... inside. Since new changes in #1506 can now avoid such situation, shall we close it?
