### ISSUE TITLE
Can't Import NNVM after MXNet imported.

### ISSUE THREAD

**Issue by Faldict** [dmlc/tvm#1525]
I have installed MXNet 1.3.0 and TVM 0.4.0 on my Jetson TX2. I could import MXNet or NNVM alone, but I couldn't import both MXNet and NNVM together. Here's my code:

```
import mxnet as mx
import nnvm
```

And the logs:

```
terminate called after throwing an instance of 'dmlc::Error'
  what():  [02:25:29] /home/nvidia/tvm/dmlc-core/include/dmlc/././json.h:536: Check failed: type_name_.at(tp) == type_name Type has already been registered as another typename list_shape
Aborted (core dumped)
```

So how to fix it?

**Comment by tqchen** [comment]
Thanks for raising this question, please use https://discuss.tvm.ai/ for general discussion. This might have something specific to the TX2 board env (related to the implementation of RTLD.local, in theory, nnvm should resolve to its internal version of the json), as such a problem does not occur in normal desktops. I also recall @kazum have some related fix on such symbolic resolve issues 

As a temporary workaround, you could try to use tvm from a desktop and use cross compilation and ship through RPC.
