### ISSUE TITLE
when running a tvm case, a run time error happens.

### ISSUE THREAD

**Issue by Youjk** [dmlc/tvm#1537]
IR.cpp:32:11:run time error : left shift of negative value -1

IR.cpp source code:

Expr IntImm::make(Type t, int64_t value) {
    internal_assert(t.is_int() && t.is_scalar())
        << "IntImm must be a scalar Int\n";
    internal_assert(t.bits() == 8 || t.bits() == 16 || t.bits() == 32 || t.bits() == 64)
        << "IntImm must be 8, 16, 32, or 64-bit\n";

    // Normalize the value by dropping the high bits
    value <<= (64 - t.bits());
    // Then sign-extending to get them back
    value >>= (64 - t.bits());

    std::shared_ptr<IntImm> node = std::make_shared<IntImm>();
    node->type = t;
    node->value = value;
    return Expr(node);
}

In value <<= (64 - t.bits()),when value is negative will produce the rutime error.we can change the code like this value = (uint64_t)value << (64 - t.bits()), it does not change the value.

**Comment by tqchen** [comment]
please open a discussion thread at https://discuss.tvm.ai/, it would also be very helpful to provide a specific producible test code
