### ISSUE TITLE
[ONNX] Implement ConstantFill operator.

### ISSUE THREAD

**Issue by iwasaki-kenta** [dmlc/tvm#1539]
The `ConstantFill` operator is required for many seq2seq models.

Happy to integrate and make a PR for it, though want to ask if there's any documentation available on the NNVM Symbol/Variable API (instantiating new Variables to provide defaults for parameters, etc). Tried looking through other operators and noticed that the majority of them simply are pass-throughs/wrappers for already-existing operators.

From what I see, `ConstantFill` can be replaced by `Symbol.full_like(input, fill_value=...)` (fill_value has a default of 0).

**Comment by srkreddy1238** [comment]
@iwasaki-kenta welcome to contribute PR for ```ConstantFill```.

As of now I think we don't have a tutorial about how to develop a new operator across TVM & NNVM.
[TOPI Intro](https://github.com/dmlc/tvm/blob/cca57ae6d5815699206da6dfe44b31110edf5ceb/tutorials/topi/intro_topi.py) is a tutorial we have about how to use tvm topi. Community is always there to help with areas which are not documented till now.

The practice till now is for a new frontend operator is to for existing operators from NNVM and wrap it (if there is one).
Or 
Implement a new operator which fits for most of the other frameworks and then wrap it in frontend.

For ```ConstantFill``` it can be wrapped around ```full``` and ```full_like```.

One limitation I would see for ```ConstantFill``` is with ```input_as_shape=true``` and input tensor not being a param. You could asset this case and leave it as a limitation for now.

**Comment by tqchen** [comment]
closed by https://github.com/dmlc/tvm/pull/1764
