### ISSUE TITLE
[RUNTIME]Add the flexibility of CPU affinity 

### ISSUE THREAD

**Issue by sanallen** [dmlc/tvm#1541]
After I used config_threadpool function which is added by #1403, I think can add a offset parameter

```c++
TVM_REGISTER_GLOBAL("runtime.config_threadpool")
.set_body([](TVMArgs args, TVMRetValue* rv) {
    threading::ThreadGroup::AffinityMode mode =\
    static_cast<threading::ThreadGroup::AffinityMode>(\
    static_cast<int>(args[0]));
    int offset = args[1];
    int nthreads = args[2];
    ThreadPool::ThreadLocal()->UpdateWorkerConfiguration(mode, offset, nthreads);
});
```
Example:
System has 4x Cortex A-53 (LITTLE) + 2x Cortex A-72 (big).
cpuid 0: LITTLE
cpuid 1: LITTLE
cpuid 2: LITTLE
cpuid 3: LITTLE
cpuid 4: big
cpuid 5: big

config_threadpool("big", 1, 1) -> changes affinity order to [5,1,2,3,4], will use CPU 5
config_threadpool("little", 1, 3) ->leaves affinity order as [1,2,3,4,5,0], will use CPUs 1,2,3

What do You think about this idea? @tqchen @eqy

**Comment by sanallen** [comment]
Thanks, I will create a PR that add this feature.

**Comment by tqchen** [comment]
My major question is that whether we need such flexibility, on one note is that we do want to be backward compatible and also support the case with a single number @eqy maybe have more thoughts on this

**Comment by tqchen** [comment]
cc @yidawang @yzhliu

**Comment by sanallen** [comment]
@tqchen I understand your question, hope @eqy can give me some suggest

**Comment by eqy** [comment]
@sanallen What is the use case that requires support via an offset parameter?

**Comment by tqchen** [comment]
I feel that at the moment we do not yet have a clear use case for this API, so in the spirit of keeping things minimum, we do not have to support this for now. Let us revisit this when we have a concrete use case. Thanks @sanallen for the proposal
