### ISSUE TITLE
[Windows]: link error with current master 

### ISSUE THREAD

**Issue by rajh619** [dmlc/tvm#1547]
In  Windows 10 environment (VS2015) build fails  with linking error  in current master revision(8056165eea6b55aa27b6bbed741f58dc3a6e639b) as shown below : 

```
5>     Creating library C:/tvm/build/Release/nnvm_compiler.lib and object C:/tvm/build/Release/nnvm_compiler.exp
5>graph_runtime.obj : error LNK2019: unresolved external symbol "public: static class dmlc::Registry<struct tvm::NodeFactoryReg> * __cdecl dmlc::Registry<struct tvm::NodeFactoryReg>::Get(void)" (?Get@?$Registry@UNodeFactoryReg@tvm@@@dmlc@@SAPEAV12@XZ) referenced in function "void __cdecl nnvm::compiler::`dynamic initializer for '__make_Node_NDArrayWrapperNode__''(void)" (??__E__make_Node_NDArrayWrapperNode__@compiler@nnvm@@YAXXZ)
5>C:\tvm\build\Release\nnvm_compiler.dll : fatal error LNK1120: 1 unresolved externals
```
 
The issue happens in this line : 
https://github.com/dmlc/tvm/blob/8056165eea6b55aa27b6bbed741f58dc3a6e639b/nnvm/src/compiler/graph_runtime.cc#L103

**Comment by srkreddy1238** [comment]
Submodule update ??

**Comment by rajh619** [comment]
@srkreddy1238  "git submodule " init  &  "git submodule update" is done after cloning tvm .

**Comment by souptc** [comment]
the root cause is because we static link dmlc-core to tvm shared lib, but on windows, by default the shared library won't expose the symbols (Need annotation like TVM_EXPORTS ). dmlc::Registry::Get is not exposed in this case.

I am currently fix it by re-enable the registry in nnvmcompiler shared lib, but a better fix may be from dmlc-core side to expose this symbol. Any suggestion from tvm team?

**Comment by rajh619** [comment]
@souptc  thanks for the info , i saw your commit in #1550 , shall i use it for windows ?
I understand the change  conflicts with other platform .But as of now i hope i can use it as temporary fix for windows .

**Comment by souptc** [comment]
@rajh619 ，that commit could pass the build, but I didn't run all the tvm test cases, not sure is there any protential issue.

**Comment by tqchen** [comment]
fixed thanks to @souptc
