### ISSUE TITLE
AttributeError: 'module' object has no attribute 'tophub'

### ISSUE THREAD

**Issue by pribadihcr** [dmlc/tvm#1555]
Hi,

I run tvm/vta/tests/python/integration/test_benchmark_topi_conv2d.py, got the following error:
autotvm.tophub.check_package('vta')
AttributeError: 'module' object has no attribute 'tophub'

**Comment by tqchen** [comment]
Thanks for reporting the issue, please use https://discuss.tvm.ai/ for general questions
