### ISSUE TITLE
Can't Run ssd example

### ISSUE THREAD

**Issue by chenjunweii** [dmlc/tvm#1561]
I got this error when i run the ssd example, any idea ?

/home/xxx/src/tvm/src/runtime/module.cc:92: Check failed: f != nullptr Cannot find function tvm.contrib.sort.argsort in the imported modules or global registry

**verbose output**

Traceback (most recent call last):
  File "ssd.py", line 69, in <module>
    m.run()
  File "/home/xxx/src/tvm/python/tvm/contrib/graph_runtime.py", line 113, in run
    self._run()
  File "/home/xxx/src/tvm/python/tvm/_ffi/_ctypes/function.py", line 184, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/xxx/src/tvm/python/tvm/_ffi/base.py", line 66, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [14:52:57] /home/xxx/src/tvm/src/runtime/module_util.cc:52: Check failed: ret == 0 (-1 vs. 0) [14:52:57] /home/xxx/src/tvm/src/runtime/module.cc:92: Check failed: f != nullptr Cannot find function tvm.contrib.sort.argsort in the imported modules or global registry

Stack trace retxxxned 10 entries:
[bt] (0) /home/xxx/src/tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x53) [0x7fc21e4671d3]
[bt] (1) /home/xxx/src/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x39) [0x7fc21e467a39]
[bt] (2) /home/xxx/src/tvm/build/libtvm.so(tvm::runtime::ModuleNode::GetFuncFromEnv(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x2d7) [0x7fc21e8662b7]                                           
[bt] (3) /home/xxx/src/tvm/build/libtvm.so(TVMBackendGetFuncFromEnv+0x61) [0x7fc21e84e641]
[bt] (4) [0x7fc18a9190e2]
[bt] (5) [0x7fc18a918c26]
[bt] (6) /home/xxx/src/tvm/build/libtvm.so(+0x5d8a41) [0x7fc21e868a41]
[bt] (7) /home/xxx/src/tvm/build/libtvm.so(+0x619cd7) [0x7fc21e8a9cd7]
[bt] (8) /home/xxx/src/tvm/build/libtvm.so(+0x618bc7) [0x7fc21e8a8bc7]
[bt] (9) /home/xxx/src/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7fc21e85081e]

Stack trace retxxxned 10 entries:
[bt] (0) /home/xxx/src/tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x53) [0x7fc21e4671d3]
[bt] (1) /home/xxx/src/tvm/build/libtvm.so(+0x5d917d) [0x7fc21e86917d]
[bt] (2) /home/xxx/src/tvm/build/libtvm.so(+0x619cd7) [0x7fc21e8a9cd7]
[bt] (3) /home/xxx/src/tvm/build/libtvm.so(+0x618bc7) [0x7fc21e8a8bc7]
[bt] (4) /home/xxx/src/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7fc21e85081e]
[bt] (5) /usr/lib/libffi.so.6(ffi_call_unix64+0x4c) [0x7fc22aa2b1c8]
[bt] (6) /usr/lib/libffi.so.6(ffi_call+0x32a) [0x7fc22aa2ac2a]
[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2a5) [0x7fc22ac3fcd5]
[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12631) [0x7fc22ac40631]
[bt] (9) /usr/lib/libpython3.6m.so.1.0(_PyObject_FastCallDict+0x8c) [0x7fc22d28f64c]

terminate called after throwing an instance of 'dmlc::Error'
  what():  [14:52:57] /home/xxx/src/tvm/src/runtime/workspace_pool.cc:96: Check failed: allocated_.size() == 1 (3 vs. 1)

Stack trace retxxxned 8 entries:
[bt] (0) /home/xxx/src/tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x53) [0x7fc21e4671d3]
[bt] (1) /home/xxx/src/tvm/build/libtvm.so(tvm::runtime::WorkspacePool::Pool::Release(DLContext, tvm::runtime::DeviceAPI*)+0x7d0) [0x7fc21e882fa0]
[bt] (2) /home/xxx/src/tvm/build/libtvm.so(tvm::runtime::WorkspacePool::~WorkspacePool()+0x37) [0x7fc21e881367]
[bt] (3) /usr/lib/libc.so.6(__call_tls_dtors+0x3f) [0x7fc22d6a96cf]
[bt] (4) /usr/lib/libc.so.6(+0x39037) [0x7fc22d6a9037]
[bt] (5) /usr/lib/libc.so.6(+0x3905a) [0x7fc22d6a905a]
[bt] (6) /usr/lib/libc.so.6(__libc_start_main+0xf2) [0x7fc22d693072]
[bt] (7) python(_start+0x2a) [0x5614d0873cda]

[1]    19781 abort (core dumped)  python ssd.py

**Comment by kuonangzhe** [comment]
Just got the exact same error via the master branch. @chenjunweii how did you solve the problem?
