### ISSUE TITLE
[x86][intrinsic]Is test_llvm_lookup_intrin test LLVM version dependent?

### ISSUE THREAD

**Issue by zhiics** [dmlc/tvm#1565]
https://github.com/dmlc/tvm/blob/0241fdc5d23a410cff63a0ffeab7c548fadfaa98/tests/python/unittest/test_codegen_llvm.py#L62

I was trying to run tests using LLVM 7.0. It seemed that this test failed because it triggered an LLVM error during codegen.
Assertion failed: ((i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"), function init, file /Users/chzhi/tools/llvm/llvm/lib/IR/Instructions.cpp, line 299.
Abort trap: 6

@cowanmeg Could you please double check if it is a llvm version problem? If so, we might need llvm version check first.

In addition, it looks that the variable m is defined but not used and there is no assertion for the test.

**Comment by cowanmeg** [comment]
Hmm..I just downloaded the current llvm-7 development branch and the test passed for me. 
Can you see if updating fixes the issue?

Also thanks for catching that unused variable!

**Comment by zhiics** [comment]
I see, Thanks. I think mine was probably the trunk version.

**Comment by tqchen** [comment]
Let us move this discussion to https://discuss.tvm.ai/ as there is no actionable items. Please feel free to send a patch to remove unused variable
