### ISSUE TITLE
TVM4J  cannot compile

### ISSUE THREAD

**Issue by 13301338176** [dmlc/tvm#1568]
/tvm/build$ ls -l
总用量 70620
-rw-rw-r--  1 haijunz haijunz    43667  8月  6 13:49 CMakeCache.txt
drwxrwxr-x 22 haijunz haijunz     4096  8月  7 21:12 CMakeFiles
-rw-rw-r--  1 haijunz haijunz     5412  8月  6 13:49 cmake_install.cmake
-rw-rw-r--  1 haijunz haijunz     2952  8月  7 20:51 config.cmake
-rwxrwxr-x  1 haijunz haijunz  4045971  8月  6 13:52 libnnvm_compiler.so
-rwxrwxr-x  1 haijunz haijunz   965582  8月  6 13:49 libtvm_runtime.so
-rwxrwxr-x  1 haijunz haijunz 63466032  8月  6 13:51 libtvm.so
-rwxrwxr-x  1 haijunz haijunz  1335150  8月  6 13:51 libtvm_topi.so
-rwxrwxr-x  1 haijunz haijunz   193489  8月  6 13:49 libvta.so
-rw-rw-r--  1 haijunz haijunz   239819  8月  7 21:11 Makefile
-rwxrwxr-x  1 haijunz haijunz  1007507  8月  7 21:12 packed_func_test
-rwxrwxr-x  1 haijunz haijunz   989151  8月  7 21:11 tensor_test

Follow up procedure on at: https://github.com/dmlc/tvm/blob/master/jvm/README.md

haijunz@haijunz-HP-Z230-SFF-Workstation:/media/haijunz/400G/tvm/build$ make jvmpkg
make: *** 没有规则可以创建目标“jvmpkg”。 停止。
haijunz@haijunz-HP-Z230-SFF-Workstation:/media/haijunz/400G/tvm/build$ make jvminstall
make: *** 没有规则可以创建目标“jvminstall”。 停止。
haijunz@haijunz-HP-Z230-SFF-Workstation:/media/haijunz/400G/tvm/build$ make 
all                       depend                    ir_mutator_test/          packed_func_test          topi/
build_module_test         edit_cache                ir_simplify_test          packed_func_test/         topi_ewise_test
build_module_test/        edit_cache/               ir_simplify_test/         preinstall                topi_ewise_test/
clean                     expr_test                 ir_ssa_test               preinstall/               tvm
clean/                    expr_test/                ir_ssa_test/              rebuild_cache             tvm/
cmake_check_build_system  HalideIR/                 ir_visitor_test           rebuild_cache/            tvm_runtime
cmake_force               help                      ir_visitor_test/          runtime                   tvm_runtime/
container_test            install                   list_install_components   runtime/                  tvm_topi
container_test/           install/                  list_install_components/  src/                      tvm_topi/
cpptest                   ir_functor_test           nnvm/                     tensor_test               vta
cpptest/                  ir_functor_test/          nnvm_compiler             tensor_test/              vta/
default_target            ir_mutator_test           nnvm_compiler/            tests/

**Comment by 13301338176** [comment]
cd root directory(,/tvm) :    make jvmpkg   make jvminstall  will work  . close it

**Comment by tqchen** [comment]
Glad that you resolved the problem, please use https://discuss.tvm.ai/ for future related questions
