### ISSUE TITLE
[AUTOTVM] Building SSD error

### ISSUE THREAD

**Issue by feng98** [dmlc/tvm#1575]
# python tune_nnvm_arm.py 
Traceback (most recent call last): 
...
TVMError: [16:12:36] /tvm/src/schedule/message_passing.cc:36: Check failed: match iter_var(threadIdx.x, Range(min=0, extent=5), threadIdx.x) domain already inferred, cannot prove their extents are the same 4 vs 5

Stack trace returned 10 entries:
[bt] (0) /tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x5b) [0x7f9cc54b20cb]
[bt] (1) /tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x28) [0x7f9cc54b2918]
[bt] (2) /tvm/build/libtvm.so(tvm::schedule::Update(std::unordered_map<tvm::IterVar, tvm::Range, std::hash<tvm::IterVar>, std::equal_to<tvm::IterVar>, std::allocator<std::pair<tvm::IterVar const, tvm::Range> > >*, tvm::IterVar const&, tvm::Range)+0x330) [0x7f9cc56e3da0]
[bt] (3) /tvm/build/libtvm.so(tvm::schedule::PassDownDomain(tvm::Stage const&, std::unordered_map<tvm::IterVar, tvm::Range, std::hash<tvm::IterVar>, std::equal_to<tvm::IterVar>, std::allocator<std::pair<tvm::IterVar const, tvm::Range> > >*, bool)+0x47a) [0x7f9cc56e430a]
[bt] (4) /tvm/build/libtvm.so(tvm::schedule::InferBound(tvm::Schedule const&)+0xed8) [0x7f9cc5707968]
[bt] (5) /tvm/build/libtvm.so(+0x220038) [0x7f9cc54df038]
[bt] (6) /tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7f9cc58b908e]
[bt] (7) /tvm/python/tvm/_ffi/_cy2/core.so(+0x17a1b) [0x7f9cc4a42a1b]
[bt] (8) python(PyObject_Call+0x3e) [0x4a577e]
[bt] (9) python(PyEval_EvalFrameEx+0x2f0d) [0x4bed3d]

Error during compile graph
--------------------------
Graph(%input0,
      %input1,
      %input2,
      %input3,
      %input4) {
  %input0, shape=[1,128,10,10]
  %input1, shape=[128,128,1,1]
  %input2, shape=[128]
  %input3, shape=[128]
  %input4, shape=[128]
  %2 = conv2d(%input0, %input1, kernel_size='[1L, 1L]', use_bias='False', dilation='(1, 1)', channels='128', kernel_layout='OIHW', groups='1', padding='(0, 0)', layout='NCHW', strides='(1, 1)'), shape=[1,128,10,10]
  %4 = expand_dims(%input2, num_newaxis='2', axis='1'), shape=[128,1,1]
  %5 = broadcast_mul(%2, %4), shape=[1,128,10,10]
  %7 = negative(%input3), shape=[128]
  %8 = elemwise_mul(%7, %input2), shape=[128]
  %10 = elemwise_add(%8, %input4), shape=[128]
  %11 = expand_dims(%10, num_newaxis='2', axis='1'), shape=[128,1,1]
  %12 = broadcast_add(%5, %11), shape=[1,128,10,10]
  %13 = relu(%12), shape=[1,128,10,10]
  ret %13
}
graph_attr_keys = [shape, shape_num_unknown_nodes, dtype, dtype_num_unknown_nodes]

This issues alike #660. Could anyone help fix this please?@Laurawly

**Comment by tqchen** [comment]
please raise general questions at https://discuss.tvm.ai/
