### ISSUE TITLE
[Pass] Missing CHECK in storage rewrite

### ISSUE THREAD

**Issue by xqdan** [dmlc/tvm#1592]
We have a complicated case triggering this bug.

after L586,  we should have the same check as L559
https://github.com/dmlc/tvm/blob/master/src/pass/storage_rewrite.cc#L559

**Comment by tqchen** [comment]
also, please clarify if this is a bug, or a guard that need to be added to the case

**Comment by xqdan** [comment]
Sure, short cut case may take some time

**Comment by xqdan** [comment]
fixed by #1616
