### ISSUE TITLE
Tensorize in multithreaded environment

### ISSUE THREAD

**Issue by taknevski** [dmlc/tvm#1611]
[test.tar.gz](https://github.com/dmlc/tvm/files/2295210/test.tar.gz)
Hi,
I have a small test case where I do a 2-d matrix addition.
A = tvm.placeholder((4,16), name='input1')
B = tvm.placeholder((4,16), name='input2')
C = tvm.compute((4,16),
          lambda m,n: A[m,n] + B[m,n],
          name='output')

I tile on the leading dimension by 2 and parallelize as follows:

  m,n = s[C].op.axis

  m_outer,m_inner = s[C].split(m,factor=2)
  s[C].reorder(m_outer,m_inner,n)

I then match the inner matrix add with a tensorize routine:
And I add my own c function that does the matrix add as a packed func.
I print the address of the pointer passed into the routine. When there is a single thread(TVM_NUM_THREADS=1) the pointers are updated correctly prior to being passed to the function
But when there are 2 threads are more, the input pointer is not offset for threads other than the first one. 

I have attached a test case with a readme.

**Comment by taknevski** [comment]
I parallelize like this:

  s[C].parallel(m_outer)

**Comment by tqchen** [comment]
Thanks for bringing up the discussion, can you open a new thread at https://discuss.tvm.ai/ instead?

**Comment by taknevski** [comment]
I created a thread on the discuss forum, but was unable to upload the test case..
