### ISSUE TITLE
[runtime] TypedPackedFunc causes build failure on mac with clang compiler

### ISSUE THREAD

**Issue by zhiics** [dmlc/tvm#1650]
@tqchen 

I just pulled the latest code from the master branch to compile it on my mac with clang-7.0. I got a compiler error that complains about https://github.com/tqchen/tvm/blob/77422e349e03a75ce60991c205f2731e3febf80c/include/tvm/runtime/packed_func.h#L184

We can compile it on ubuntu with g++. I think the reason is probably because g++ will use the implicit conversion in the TypePackedFunc, but clang matches the implicit conversion in PackedFunc (https://github.com/tqchen/tvm/blob/77422e349e03a75ce60991c205f2731e3febf80c/include/tvm/runtime/packed_func.h#L98). I think one easy way is to change it to: `packed_ = packed` so that it will use the copy assignment.

**Comment by tqchen** [comment]
should be fixed by https://github.com/dmlc/tvm/pull/1649
