### ISSUE TITLE
Variable node names changed in the pass PrecomputePrune while param names not updated accordingly

### ISSUE THREAD

**Issue by reminisce** [dmlc/tvm#1676]
I have a graph with nothing to prune, but its variable node names are changed in the pass PrecomputePrune. I traced the code to the following place, where line 72 is reached for the variable nodes. Their names are changed by appending entry version numbers in `replace_pruned_entry`, and this results in mismatch between `params`'s names and the graph's `list_input_names()`. Should we add a check at line 71 to skip variable nodes, or is it intended to replace the entry of a variable node?
@tqchen @ZihengJiang 
![image](https://user-images.githubusercontent.com/4978794/44819521-f9925000-aba1-11e8-9571-de7ce988c49d.png)

**Comment by srkreddy1238** [comment]
Renaming is intended while pruning any compute node and we shouldn't retain the original param name here.

New name is necessary as if  ```there is two compute nodes get's pruned out of same param``` the final param nodes should go with different names than initial param name.

**Comment by reminisce** [comment]
@srkreddy1238 Thanks for the reply. I understand in some cases the names have to be changed. In my case, there is nothing to prune, and pruning pass just replaces a param node with a newly created param node of a new name, but does not generate a precompute graph since `non_var_edge` is 0. So the loaded param map cannot be updated because there is no precompute graph to generate output names. This results in name mismatch between the loaded param map and and the graph input names. This looks more like a bug to me. Please correct me if my understanding is wrong. Thanks.

**Comment by srkreddy1238** [comment]
Can you share the front end model if not private ?

**Comment by reminisce** [comment]
Yes, here is my [dev branch](https://github.com/reminisce/tvm/tree/subgraph_integration) for running the following script. I introduced a subgraph operator here that contains a subgraph of the whole graph. The subgraph operator is not optimized by the compiler and is backed up by an external accelerator at runtime.

I added a check at this line to skip replacing var entries and the following script can print the same input names of params and graph.
https://github.com/reminisce/tvm/blob/subgraph_integration/nnvm/src/compiler/precompute_prune.cc#L71


```python
import numpy as np
import tvm
import nnvm
from tvm.contrib import graph_runtime
from nnvm.testing.utils import create_workload


def test_tvm_compile():
    batch_size = 1
    image_shape = (1, 4, 4)
    data_shape = (batch_size,) + image_shape
    data = nnvm.symbol.Variable('data')
    data = nnvm.symbol.batch_norm(data=data, epsilon=2e-5, scale=False, name='bn_data')
    sym = nnvm.symbol.exp(data)

    with open('./original_simple_graph.json', 'w') as fo:
        fo.write(nnvm.graph.create(sym).json())

    opt_level = 3
    op_names = ['batch_norm']
    sym = nnvm.symbol.partition_by_names(sym, 'tensorrt', op_names)
    with open('./partitioned_simple_graph.json', 'w') as fo:
        fo.write(nnvm.graph.create(sym).json())

    target = tvm.target.create('llvm')
    _, params = create_workload(sym, batch_size, image_shape)
    print(sym.list_input_names())
    with nnvm.compiler.build_config(opt_level=opt_level):
        graph, lib, params = nnvm.compiler.build(sym, target, shape={'data': data_shape}, params=params)
    print(graph.symbol().list_input_names())
    print(params.keys())
    with open('./partitioned_optimized_simple_graph.json', "w") as fo:
        fo.write(graph.json())
```

**Comment by reminisce** [comment]
After testing with more cases, I find that the correct way of fixing this problem is deleting these lines to prevent early return.
https://github.com/dmlc/tvm/blob/master/nnvm/src/compiler/precompute_prune.cc#L78-L81

**Comment by srkreddy1238** [comment]
@reminisce 

I tried to have a look on your branch but it look like broken.

```TVM: Initializing cython mode...
[12:42:50] /home/srk/work/NN/TF-DMLC/test/tvm/dmlc-core/include/dmlc/logging.h:308: [12:42:50] src/runtime/registry.cc:57: Check failed: override Global PackedFunc arith.intset_single_point is already registered

Stack trace returned 10 entries:
[bt] (0) /home/srk/.local/lib/python3.6/site-packages/tvm-0.1.0-py3.6-linux-x86_64.egg/tvm/libtvm.so(_ZN3tvm7runtime8Registry8RegisterERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb+0x437) [0x7f576b7d9b67]
[bt] (1) /home/srk/work/NN/TF-DMLC/test/tvm/build/libtvm.so(+0x1b6f0c) [0x7f5769b53f0c]
[bt] (2) /lib64/ld-linux-x86-64.so.2(+0x10ada) [0x7f5774f42ada]
[bt] (3) /lib64/ld-linux-x86-64.so.2(+0x10beb) [0x7f5774f42beb]
[bt] (4) /lib64/ld-linux-x86-64.so.2(+0x15bf6) [0x7f5774f47bf6]
[bt] (5) /lib/x86_64-linux-gnu/libc.so.6(_dl_catch_error+0x84) [0x7f5773ee5db4]
[bt] (6) /lib64/ld-linux-x86-64.so.2(+0x15149) [0x7f5774f47149]
[bt] (7) /lib/x86_64-linux-gnu/libdl.so.2(+0xff6) [0x7f5774b0fff6]
[bt] (8) /lib/x86_64-linux-gnu/libc.so.6(_dl_catch_error+0x84) [0x7f5773ee5db4]
[bt] (9) /lib/x86_64-linux-gnu/libdl.so.2(+0x1759) [0x7f5774b10759]

terminate called after throwing an instance of 'dmlc::Error'
  what():  [12:42:50] src/runtime/registry.cc:57: Check failed: override Global PackedFunc arith.intset_single_point is already registered

Stack trace returned 10 entries:
[bt] (0) /home/srk/.local/lib/python3.6/site-packages/tvm-0.1.0-py3.6-linux-x86_64.egg/tvm/libtvm.so(_ZN3tvm7runtime8Registry8RegisterERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb+0x437) [0x7f576b7d9b67]
[bt] (1) /home/srk/work/NN/TF-DMLC/test/tvm/build/libtvm.so(+0x1b6f0c) [0x7f5769b53f0c]
[bt] (2) /lib64/ld-linux-x86-64.so.2(+0x10ada) [0x7f5774f42ada]
[bt] (3) /lib64/ld-linux-x86-64.so.2(+0x10beb) [0x7f5774f42beb]
[bt] (4) /lib64/ld-linux-x86-64.so.2(+0x15bf6) [0x7f5774f47bf6]
[bt] (5) /lib/x86_64-linux-gnu/libc.so.6(_dl_catch_error+0x84) [0x7f5773ee5db4]
[bt] (6) /lib64/ld-linux-x86-64.so.2(+0x15149) [0x7f5774f47149]
[bt] (7) /lib/x86_64-linux-gnu/libdl.so.2(+0xff6) [0x7f5774b0fff6]
[bt] (8) /lib/x86_64-linux-gnu/libc.so.6(_dl_catch_error+0x84) [0x7f5773ee5db4]
[bt] (9) /lib/x86_64-linux-gnu/libdl.so.2(+0x1759) [0x7f5774b10759]

Aborted (core dumped)
```

**Comment by reminisce** [comment]
@srkreddy1238 That's odd. I can run the script with the that branch. The error message indicates something I didn't touch in the codebase.

**Comment by srkreddy1238** [comment]
Have seen similar issue with below sub graph where entire graph can be pruned to a param.

```
Graph(%InceptionV4/Logits/PreLogitsFlatten/flatten/Shape, %InceptionV4/Logits/PreLogitsFlatten/flatten/Reshape/shape/1) {
  %1 = strided_slice(%InceptionV4/Logits/PreLogitsFlatten/flatten/Shape, stride='[1]', begin='[0]', end='[1]')
  %2 = reshape(%1, shape='(1,)')
  %3 = expand_dims(%2, num_newaxis='1', axis='0')
  %5 = expand_dims(%InceptionV4/Logits/PreLogitsFlatten/flatten/Reshape/shape/1, num_newaxis='1', axis='0')
  %6 = concatenate(%3, %5, axis='0')
  ret %6
}

```
and #2004  works for it.

**Comment by tqchen** [comment]
close for now due to inactive status
