### ISSUE TITLE
 Check failed: !use_count_.count(v) variable n has been used before definition!

### ISSUE THREAD

**Issue by lxwithgod** [dmlc/tvm#1679]
from __future__ import absolute_import, print_function
import tvm

n = tvm.var('n', dtype=tvm.int32)
Input = tvm.placeholder((n, n), name='Input')
Filter = tvm.placeholder((3, 3), name='Filter')
di = tvm.reduce_axis((0, 3), name='di')
dj = tvm.reduce_axis((0, 3), name='dj')
Output = tvm.compute(
    (n - 2, n - 2),
    lambda i, j: tvm.sum(Input[i + di, j + dj] * Filter[di, dj], axis=[di, dj]),
    name='Output')
s = tvm.create_schedule(Output.op)
#
oi, oj = s[Output].split(s[Output].op.axis[0], 32)
#
s[Output].bind(oi, tvm.thread_axis("blockIdx.x"))
s[Output].bind(oj, tvm.thread_axis("threadIdx.x"))
#
# # print(tvm.lower(s, [Input, Filter, Output,n], simple_mode=True))
#
fcuda = tvm.build(s, [Output, Input, Filter, n], "cuda", name="conv")

print(fcuda.imported_modules[0].get_source())

**Comment by tqchen** [comment]
please open a thread at https://discuss.tvm.ai/

**Comment by lxwithgod** [comment]
thanks
