### ISSUE TITLE
[CI] The link in darknet tutorial is broken

### ISSUE THREAD

**Issue by merrymercy** [dmlc/tvm#1681]
The link in darknet tutorial is broken. This blocks the CI test for all pull requests.

http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-1671/10/pipeline

@siju-samuel  Can you take a look?

**Comment by siju-samuel** [comment]
@merrymercy 
The recent changes in tutorial is with PR  #1501 broken the link for downloading the weights file, leading to this CI failure.

@yzhliu please merge #1682
