### ISSUE TITLE
[AutoTVM] x86 fp32 and int8 support

### ISSUE THREAD

**Issue by kevinthesun** [dmlc/tvm#1690]
This is to track the progress to support x86 AutoTVM support.

- [x] x86 fp32 AutoTVM support: https://github.com/dmlc/tvm/pull/1586

- [ ] x86 int8 AutoTVM support: https://github.com/dmlc/tvm/pull/1680

**Comment by kevinthesun** [comment]
Yes. I'll do this first.

**Comment by tqchen** [comment]
now that #1680 is merged, @anijain2305 can you please followup with autotvm support?

**Comment by merrymercy** [comment]
done by #1993
