### ISSUE TITLE
Bilinear mode in topi::nn::upsampling not working

### ISSUE THREAD

**Issue by KeDengMS** [dmlc/tvm#1692]
To repro, use following changes in test_topi_upsampling.py:
```
--- a/topi/tests/python/test_topi_upsampling.py
+++ b/topi/tests/python/test_topi_upsampling.py
@@ -22,7 +22,7 @@ def verify_upsampling(batch, in_channel, in_height, in_width, scale, layout='NCH
         raise NotImplementedError(
             'Layout not supported {} '.format(layout))

-    B = topi.nn.upsampling(A, scale, layout=layout)
+    B = topi.nn.upsampling(A, scale, layout=layout, method='BILINEAR')

     b_np = topi.testing.upsampling_python(a_np, scale, layout)
```

**Comment by masahi** [comment]
cc @srkreddy1238

**Comment by srkreddy1238** [comment]
@KeDengMS 

`NCH` layout ???
Can you conform the error log ?

**Comment by KeDengMS** [comment]
Yes NCHW layout, but I believe it exists in NHWC as well. The error is from a crash in dereferencing nullptr in [here](https://github.com/dmlc/tvm/blob/master/topi/include/topi/image/resize.h#L227-L228). The problem is that shape is a Mul node with two ImmInt as input, and [as_const_int](https://github.com/dmlc/HalideIR/blob/6f64f7866747a2a81bec84aea9bde0479c5b72c1/src/ir/IROperator.cpp#L68-L82) returns nullptr for non-const node.
It seems const folding should be applied, and moreover the bilinear interpolation code path needs to be tested.

**Comment by srkreddy1238** [comment]
@KeDengMS  a bit confused.

Is the issue about "Layout Not Supported" or "Crash " ?

Can you share complete log or the sample code?

**Comment by KeDengMS** [comment]
I think it's nothing about Layout, but more for BILINEAR mode. The repro is to change the python test to use BILINEAR mode: `B = topi.nn.upsampling(A, scale, layout=layout, method='BILINEAR')`, then you'll find the crash.

**Comment by masahi** [comment]
But the log says NotImplementedError('Layout not supported {} '.format(layout)). What is the "layout" parameter you passed in? It should be "NCHW" or "NHWC".

**Comment by KeDengMS** [comment]
The repro I show above is from git diff, not the log. The testcase tests both NCHW and NHWC

**Comment by masahi** [comment]
@KeDengMS I can repro your crash. The fix is to add util.simplify to https://github.com/dmlc/tvm/blob/master/topi/python/topi/nn/upsampling.py#L34

**Comment by masahi** [comment]
@srkreddy1238 I made a branch to fix this issue [here](https://github.com/masahi/tvm/tree/fix-bilinear). But some bilinear upsampling tests are failing. Can you have a look?

**Comment by srkreddy1238** [comment]
Thanks @KeDengMS  for bringing up the issue and thanks @masahi for finding the root cause and fix.
I have added the final piece (```atol=1e-5``` allowance) at #1708 for your review comment.

**Comment by KeDengMS** [comment]
Thanks for the fix!
