### ISSUE TITLE
how to add split condition inside tensorize scope

### ISSUE THREAD

**Issue by LaughingGor1949** [dmlc/tvm#1698]
# Hi all,
I need to split a axis which size is big prime number，then I tensorize at the xi iter. However I got something wrong, and I have no idea about that:
**Traceback (most recent call last):
  File "abs.py", line 38, in <module>
    tf_abs((131,), "float16")
  File "abs.py", line 34, in tf_abs
    print(tvm.lower(sch, [in_data, res], simple_mode=True))
  File "/home/laughing/soft/tvm/python/tvm/build_module.py", line 341, in lower
    stmt = schedule.ScheduleOps(sch, bounds)
  File "/home/laughing/soft/tvm/python/tvm/_ffi/function.py", line 280, in my_api_func
    return flocal(*args)
  File "/home/laughing/soft/tvm/python/tvm/_ffi/_ctypes/function.py", line 184, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/laughing/soft/tvm/python/tvm/_ffi/base.py", line 66, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [10:45:36] /home/laughing/soft/tvm/src/op/tensorize.cc:127: Tensorize failed, split condition likely(((i0.inner + (i0.outer*128)) < 131)) relies on var defined inside tensorize scope**
Thanks,

```
import tvm

def intrin_abs(n, dtype):
    x = tvm.placeholder((n,), dtype=dtype, name="x")
    y = tvm.compute((n,), lambda *indices: tvm.select(x(*indices) < 0, -x(*indices), x(*indices)))
    def intrin_func(ins, outs):
        xx = ins[0]
        yy = outs[0]
        return tvm.call_packed("vabs", xx, yy)
    with tvm.build_config(offset_factor=128):
        return tvm.decl_tensor_intrin(y.op, intrin_func)

def tf_abs(shape, dtype):
    in_data = tvm.placeholder(shape, dtype=dtype, name="in_data")
    res = tvm.compute(shape, lambda *indices: tvm.select(in_data(*indices) < 0, -in_data(*indices), in_data(*indices)))
    sch = tvm.create_schedule(res.op)
    xo, xi = sch[res].split(sch[res].op.axis[0], factor=128)
    sch[res].tensorize(xi, intrin_abs(128, in_data.dtype))
    print(tvm.lower(sch, [in_data, res], simple_mode=True))

if __name__ == "__main__":
    tf_abs((131,), "float16")
```

**Comment by tqchen** [comment]
Please open a thread at https://discuss.tvm.ai/
