### ISSUE TITLE
[TEST] Flaky test_topi_sparse

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#1704]
http://ci.tvm.ai:8080/blue/rest/organizations/jenkins/pipelines/tvm/branches/PR-1700/runs/2/nodes/231/log/?start=0

cc @liangfu

**Comment by liangfu** [comment]
Not equal to tolerance rtol=1e-05, atol=0

(mismatch 16.66666666666667%)
 x: array([[ -0.081917, -18.463932],
       [-12.556804, -23.299555],
       [  7.793209, -10.46417 ]], dtype=float32)
 y: array([[ -0.081915, -18.463932],
       [-12.556804, -23.299555],
       [  7.79321 , -10.464172]], dtype=float32)

looks like the rtol is too small in this case.

**Comment by tqchen** [comment]
@liangfu can you send a proposed fix?
