### ISSUE TITLE
[ARITH] Improve Canonical Simplification to Handle Fused Pattern 

### ISSUE THREAD

**Issue by KeDengMS** [dmlc/tvm#1711]
I have following C++ code when testing TVM in CUDA:
```
    tvm::Array<tvm::Expr> a_shape1 = {5, 6};
    // tvm::Array<tvm::Expr> a_shape1 = {5, 2, 3};
    tvm::Tensor tvm_X = tvm::placeholder(a_shape1, tvm::Float(32), "A");
    tvm::Tensor tvm_Y = ::topi::where(less(0, tvm_X), 1 / (1 + exp(negative(tvm_X))), 1 - 1 / (1 + exp(tvm_X)));
    auto target1 = tvm::target::cuda();
    auto S1 = topi::cuda::schedule_injective(target1, {tvm_Y});

    auto args1 = tvm::Array<tvm::Tensor>({tvm_X, tvm_Y});
    std::unordered_map<tvm::Tensor, tvm::Buffer> binds1;
    auto config1 = tvm::build_config();
    config1->restricted_func = true;
    auto lowered1 = tvm::lower(S1, args1, "Sigmoid", binds1, config1);

    std::cout << lowered1[0]->body << std::endl;
```

When the input shape is 2D (5,6), the lowered function looks close to handwritten kernel:
```
  if ((threadIdx.x < 30)) {
    tensor[threadIdx.x] = tvm_if_then_else(((0.000000f < A[threadIdx.x]) == (uint1)0), (1.000000f - (1.000000f/(exp(A[threadIdx.x]) + 1.000000f))), (1.000000f/(exp((0.000000f - A[threadIdx.x])) + 1.000000f)))
  }
```

However for 3D input shape (5, 2, 3), the lowered function looks different:
```
  if ((threadIdx.x < 30)) {
    tensor[(((threadIdx.x/6)*6) + ((((threadIdx.x/3) % 2)*3) + (threadIdx.x % 3)))] = tvm_if_then_else(((0.000000f < A[(((threadIdx.x/6)*6) + ((((threadIdx.x/3) % 2)*3) + (threadIdx.x % 3)))]) == (uint1)0), (1.000000f - (1.000000f/(exp(A[(((threadIdx.x/6)*6) + ((((threadIdx.x/3) % 2)*3) + (threadIdx.x % 3)))]) + 1.000000f))), (1.000000f/(exp((0.000000f - A[(((threadIdx.x/6)*6) + ((((threadIdx.x/3) % 2)*3) + (threadIdx.x % 3)))])) + 1.000000f)))
  }
```

From my reading of injective schedule, it seems all input axes are fused before split, so the two cases above should have identical code gen. Is my understanding correct?

**Comment by merrymercy** [comment]
Ideally `(((threadIdx.x/6)*6) + ((((threadIdx.x/3) % 2)*3) + (threadIdx.x % 3)))` should be simplified to `threadIdx.x` since they are equivalent. But it the simplifier in tvm cannot handle this case. (cc @tqchen )

Although it introduces some extra arithmetic operations, in practice we don't observe performance regression. So it is still okay.

**Comment by tqchen** [comment]
as far as I recall, there is some ability in the buffer index fetch to simplify such expressions, by @sxjscience  maybe someone can followup on this

**Comment by sxjscience** [comment]
Yes, I've met with this problem and have written the following code https://github.com/dmlc/tvm/blob/master/src/lang/buffer.cc#L152-L220 to optimize  some  predefined patterns.

**Comment by sxjscience** [comment]
The current implementation haven’t considered the case that involves “<“ . Like “... < 32”. Also, what’s the simplified version of this pattern?(looks complicated)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by merrymercy** [comment]
I found a related Halide PR (https://github.com/halide/Halide/pull/2845) which may be interesting.
They introduce meta rewrite rules like 

```
rewrite((x + y) + w < x + z, y + w < z)
rewrite(select(x, y, z) + select(x, w, u), select(x, y + w, z + u))
```

**Comment by xqdan** [comment]
@sxjscience it's im2col convolution

**Comment by tqchen** [comment]
Most of the simplification we talked about here involves bound checking as well as the arithmetic template, which is harder than the simple rewrites. I wanted to do it for quite a while ago, maybe it is a good time to rethink our arithmetic simplifier to handle these cases

**Comment by tqchen** [comment]
Consolidate this issue to #2588
