### ISSUE TITLE
TF op conversion tests fail on fresh checkout/build of master

### ISSUE THREAD

**Issue by stilistik** [dmlc/tvm#1719]
When creating a fresh clone of the project, building it with options CUDA=ON and LLVM=ON, then running the test_forward.py for the tensorflow python frontend, the tests fail for me with the following error: 
![screenshot from 2018-09-14 14-36-59](https://user-images.githubusercontent.com/17801065/45550619-a966ef00-b82b-11e8-8613-0cc96d43d362.png)
Reverting to commit 7d6ca1b3a7882189839bd2cb80bc8a74fa70d617 from Monday Sep. 10 and building resolves this issue for me.

**Comment by masahi** [comment]
Maybe git submodule update will solve your issue. The error is happening when importing tvm, so it has nothing to do with tensorflow test.

**Comment by stilistik** [comment]
> Maybe git submodule update will solve your issue. The error is happening when importing tvm, so it has nothing to do with tensorflow test.

the issue persists after git submodule update, actually it arises after a fresh build of the project.

**Comment by wweic** [comment]
As @masahi said, you are probably having issues with the shared library you built(`libtvm.so`), the error is missing symbol:
````bash
➜  c++filt _ZTIN3tvm4NodeE
typeinfo for tvm::Node
```` 
Typical cause of this error is missing implementation for virtual functions. Actually in the old nnvm repo, someone had the [exact same issue](https://webcache.googleusercontent.com/search?q=cache:qih-a3vlSzAJ:https://github.com/dmlc/nnvm/issues/332+&cd=1&hl=en&ct=clnk&gl=us&client=ubuntu) with dynamic library.

It would help if you can share how you build tvm step by step. And given your stack trace, i guess the following code snippet is sufficient to reproduce your error:
````bash
# cd to tvm repo root
PROJ=`pwd`
export PYTHONPATH=$PROJ/python:$PROJ/nnvm/pythonL$PROJ/topi/python
python3
# then inside the repl, try to import tvm
import tvm
````

**Comment by tqchen** [comment]
Thanks for everyone on discussing the issue, let us move further discussion to https://discuss.tvm.ai/
