### ISSUE TITLE
Some warning message for running on CUDA.

### ISSUE THREAD

**Issue by JudyZhan** [dmlc/tvm#1730]
Hi, 

I configured the TVM framework with CUDA-9.0, and run the "from_darknet.py" with the correct result, but has some warning messages during the running process, I don't know why this happened?

Compiling the model...
WARNING:autotvm:Cannot find config for target=cuda, workload=('conv2d', (1, 3, 416, 416, 'float32'), (32, 3, 3, 3, 'float32'), (1, 1), (1, 1), 'NCHW', 'float32'). A fallback configuration is used, which may bring great performance regression.
WARNING:autotvm:Cannot find config for target=cuda, workload=('conv2d', (1, 32, 416, 416, 'float32'), (64, 32, 3, 3, 'float32'), (2, 2), (1, 1), 'NCHW', 'float32'). A fallback configuration is used, which may bring great performance regression.

Loading the test image...
Running the test image...

Please give me  some advices.
Thanks so much.

**Comment by masahi** [comment]
cc @merrymercy

**Comment by tqchen** [comment]
please open a thread at https://discuss.tvm.ai/
