### ISSUE TITLE
[RFC] Add canonical and standard clang-format rules.

### ISSUE THREAD

**Issue by jroesch** [dmlc/tvm#1732]
I have noticed inconsistencies between TVM's style as written today the Google C++ style as formatted by tools such as `clang-format`. 

This proposal is simply a request for us to create a standard `clang-format` configuration file and apply it uniformly to all code and PRs. We could even set up git-hooks to do this automatically for TVM developers.

Thoughts? 

cc @zhiics

**Comment by junrushao1994** [comment]
Facebook's glow (https://github.com/pytorch/glow) has a clang-format, as well as clang-tidy, maybe we could learn something from them.

**Comment by tqchen** [comment]
Let us act on this, any volunteers?

**Comment by zhiics** [comment]
I think the easiest thing is to add a .clang-format in the project root dir as most of other projects do.

**Comment by tqchen** [comment]
that sounds good, @zhiics can you open a PR, we only need to modify a bit in terms of max chars per line(we use 100 chars).

**Comment by zhiics** [comment]
@tqchen NP. Let me do that.

**Comment by tqchen** [comment]
close by #2395
