### ISSUE TITLE
Softplus implementation is not numerically stable

### ISSUE THREAD

**Issue by KeDengMS** [dmlc/tvm#1768]
From the [implementation](https://github.com/dmlc/tvm/blob/d1e048b79600cdcde47396648df7e065f0bd0607/nnvm/python/nnvm/frontend/onnx.py#L294-L298)

```
_sym.log(_sym.exp(inputs[0]) + 1)
```

When input is 100, the output is Inf, while a stable value would be 100. Similar bugs are found in multiple places.

A numerical stable version could be `log(1 + exp(0 - abs(x))) + relu(x)`

**Comment by KeDengMS** [comment]
@ZihengJiang this would require changes in several places and adding test cases. I may find time to do so once I am more familiar with the code base.

**Comment by tqchen** [comment]
This is fixed by relay module, https://github.com/dmlc/tvm/blob/master/python/tvm/relay/frontend/mxnet.py#L59
