### ISSUE TITLE
[RFC] Relay IR Text Format

### ISSUE THREAD

**Issue by joshpoll** [dmlc/tvm#1782]
# Keyword Proposal

### The final keywords are:

- `def` for global function definitions
- `fn` for local function definitions/anonymous functions
- `if` and `else` for if-else expressions
- `let` for let bindings
- `True` and `False` for booleans
- data types are tvm-style. e.g. `float32x4`

### Loose Ends

There are some elements of the text format that didn't make it into this PR. See #1935 for details.

--------------------------------

Please comment on syntax design choices for #1781 here!

# Notable Syntax Examples

### Named, Typed
```
def @foo(%x: int64, %y: int64) -> int64 {
    %x + %y
}
```

### Named, Inferred
```
def @foo(%x, %y) {
    %x + %y
}
```

### Anonymous, Typed
```
fn (%x: int64, %y: int64) -> int64 {
    %x + %y
}
```

### Anonymous, Inferred
```
fn (%x, %y) {
    %x + %y
}
```

### Immutable
```
let %x = 2;
let %x = 3;
let %y = 4;
%x + %y
```

### Side Effects Only
The following are equivalent
```
print("hello");
1
```

```
let %_ = print("hello");
1
```

## Tuples

```
()
(0,)
(0, 1)
```

### Base Types
Designed to look like NumPy types.
```
int32
uint32
float32
bool
int32x4
...
```

### Shape Types
**unimplemented**
```
s
(n + 1, 2 * n, 4)
```

### Tensor Annotations
**generics unimplemented**
```
def @add(t1: Tensor[s, bt], t2: Tensor[s, bt]) -> Tensor[s,  bt] {
    ...
}
```

### Function Types
```
fn (int32, int32) -> int32
```

**Comment by tqchen** [comment]
Can we move most of the discussion to this issue instead? and post RFC here

**Comment by tqchen** [comment]
cc @dmlc/tvm-team

**Comment by tqchen** [comment]
cross posting.
We will need a spec on how nested expressions can be printed, 

specifically, instead of 
```
add(%x, add(%y, %z))
```

We prefer
```
%1 = add(%y, %z)
%2 = add(%x, %1)
```

Note that add will become neural network layers such as conv2d etc.

**Comment by joshpoll** [comment]
I don't think this concern is within the scope of this issue/PR. IMO the pretty printer should print the AST exactly as it's presented. I think it's too restrictive to force function arguments to be values at parse time, and thus we must allow for nested expressions. We could possibly have a compiler option that forces certain compiler passes like ANF and CSE before printing or even use the pretty printer to reformat code into "graph" style.

**Comment by tqchen** [comment]
This is an issue because this is how user usually constructs a program via DSL, and we need to make sure when we print, they are print out in a well-defined compact fashion which is readable by the parser(without running any transformation pass)

**Comment by joshpoll** [comment]
Here's a proposal for block syntax per @yuruofeifei's suggestion. It will have the same semantics as  [ReasonML's for local scope](https://reasonml.github.io/docs/en/comparison-to-ocaml#local-scope), which is

```
{
  let %x = 1;
  %x
};
...
```

desugars to

```
let _ =
  let %x = 1;
  %x;
...
```

**Comment by tqchen** [comment]
cc @junrushao1994 @dmlc/tvm-team @jroesch @MarisaKirisame @yuruofeifei @grwlf please comment on the choices of keywords in the text format.

**Comment by tqchen** [comment]
I think one general question we want to ask when deciding keyword is consistency, and whether we want to enforce some of these

-  Consistency with python style
  -  e.g. ```true/false```  vs ```True/False````
- Consistency with numpy base type convention(and the printing output of tvm types)
   - e,g. float32, bool vs Float32, Bool
- Consistent with common choices of existing languages
   - e.g. use of ```->``` vs ```=>```
      - Rust: fn(args) -> return_type 
      - Swift func(args)-> return_type

**Comment by junrushao1994** [comment]
Neat.

BTW, it is necessary to use `Int`, `UInt`, `Float`?

**Comment by nhynes** [comment]
> How to express common constant with type information
Rust has
```rust
let float1 = 1f32;
let double = 1.0;
let also_double = 1f64;
// same for {u32, u64, u128, ...}
```

> necessary to use `Int`, `UInt`, `Float`

It will definitely be confusing unless there's a well defined spec for how the compiler chooses to use these annotations. I can see some value of this when compiling one model to different architectures with varied word sizes (e.g., native vs wasm).

> tuple

This is already a major point of confusion for novice python devs. Following the convention of tuple = comma will at least keep the confusion consistent.

> print Array as `axis=(1,2)`

Semantically, it's the same thing since the type is fixed at this point. If anything, square brackets _might_ improve readability (e.g., `x(y(z, axis=(1, 2)), axis=(3,))` vs `x(y(z, axis=[1, 2]), axis=[3])`)

**Comment by joshpoll** [comment]
The idea was to have all terms (e.g. variables, functions, literals) use lowercase (this is currently not enforced) and all types use uppercase (this is currently enforced by the parser). This is similar to Python type annotations and makes it clear whether something is a term or a type.

This may become especially important when we have generic shapes like `(n, 1, m)`, because it should hopefully discourage users from writing things like `(float32, 1, m)`.

Moreover, in Python type annotations are lowercase for builtins like `int` and `str`, but (by convention) uppercase for classes. I think this is a meaningless distinction for Relay and leads to more problems than it solves. It also can falsely equate functions and types. E.g. `str` in python is both a type and a function that returns a `str`.

**Comment by joshpoll** [comment]
@tqchen @nhynes Since we don't support tensor or list literals, it might make sense to allow both `()` and `[]` in many places. On a related note, currently type constructors use `[]` instead of `()` like function calls. This was to be consistent with Python conventions and also because things like `Tensor[(1, 1, 1), float32]` are easier to read than `Tensor((1, 1, 1), float32)`.

**Comment by joshpoll** [comment]
The use of `(1,)` instead of `(1)` is mostly a technical one that could be relaxed in the future. The problem is that `(1)` can be parsed both as 1 with parentheses and as a tuple with a single element.

**Comment by joshpoll** [comment]
For functions:

I think using `fn` for function types is a good idea and an easy change to make.

The reason for using `->` over `=>` is both for consistency with Python annotations and also because lines like `let %_: () -> Int64 = fn () -> Int64 { 0 }; ()` are easier to read than `let %_: () => Int64 = fn () => Int64 { 0 }; ()` since `=>` visually interferes with `=`.

**Comment by joshpoll** [comment]
I support @nhynes's constant literal annotation suggestion.

**Comment by jroesch** [comment]
@tqchen it feels like we should be able to avoid embedding type information in the attributes and instead use the type system.

**Comment by tqchen** [comment]
@jroesch I agree that in the longer term maybe explicitly annotate the output type is a good alternative. However, given that explicit ouput-type annotation is not supported for now and keep the type information in the attributes provides the numpy compatible API, it could be a good way to go for now.

**Comment by tqchen** [comment]
To follow up with consistency issues, the constant proposal also needs some thoughts.

`1.0f32` makes a lot of sense for rust because rust already uses ```f32``` for ```float32```. It may make less sense given the way we choose name types. An alternative could be ```float32(1.0)```

Notably, we only need to print out common types in a friendly text format, that means we likely only have to deal with int32, float/double, bool and rest can be dealt with explicit cast

**Comment by MarisaKirisame** [comment]
This idea just come out of my head:
can we pin a version number to every relay source/serialized code? It help to switch from one version to another version.

**Comment by joshpoll** [comment]
@tqchen I think type abbreviations like `f32` make sense in Relay as well. C, C++, Java, and Python all have type suffixes for numeric literals. We could also consider forcing all literals to be type-annotated. If we decide to do that I think forcing people to write suffixes makes more sense than forcing people to write wrapping functions.

**Comment by joshpoll** [comment]
I think using Python conventions for booleans and dtypes is probably the way to go.

**Comment by joshpoll** [comment]
I'm closing this issue since the text format PR has been merged. #1935 contains the missing pieces that didn't make it into #1781 and further discussion about the text format should be moved there.
