### ISSUE TITLE
[TEST] test_matmul topi flaky

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#1784]
http://ci.tvm.ai:8080/blue/rest/organizations/jenkins/pipelines/tvm/branches/PR-1778/runs/3/nodes/231/log/?start=0

@grwlf can you take a look?

**Comment by grwlf** [comment]
That's unfortunate. Sure, I'll investigate.

**Comment by tqchen** [comment]
good point, @junrushao1994 can you send a patch?

**Comment by junrushao1994** [comment]
@tqchen Should I send a quick fix only for `test_matmul`, or change all the `assert_allclose` with something like `atol=1e-5`?

**Comment by tqchen** [comment]
most cases do comes with rtol i guess, and i think we are fine as long as they are not flaky

**Comment by junrushao1994** [comment]
@tqchen #1791

**Comment by junrushao1994** [comment]
Ideally it would be great to have some tools helping run a test for 1000 times before it is merged, so that the choice of thresholds won't bother further commits.

**Comment by grwlf** [comment]
@junrushao1994 thank you. I was able to reproduce the error. On my machine, typical error numeric error is `1e-7` or less, which is a bit higher than the default value of `atol` (1e-8). Most of the time, relative tolerance prevents assert from triggering but in rare cases RNG happens to generate operands close to zero. In such cases relative tolerance become `1e-9` or smaller, so the error condition hits. Increasing `atol` seems to be a correct fix. I am approving the PR.

As @junrushao1994 also points out, we use `assert_allclose` extensively. In the same time, `atol` are only set in rare cases, which is probably wrong as we may see now.

```
tvm $ git grep assert_allclose | grep -v atol | wc -l
258
```

**Comment by tqchen** [comment]
Close this, for now, @grwlf you are more than welcomed to send another pr to add atol to most other settings

**Comment by grwlf** [comment]
@tqchen OK. I'll be ready to do this after I finish a current investigation regarding the performance on a complex model.

**Comment by grwlf** [comment]
Funny, it is `np.isclose` which has the default value of `atol=1e-08`. In contrast, `np.testing.assert_allclose` uses default `atol=0`
