### ISSUE TITLE
reducing ci testing time?

### ISSUE THREAD

**Issue by MarisaKirisame** [dmlc/tvm#1878]
Right now we has 8 ci task running/in queue. During the relay operator sprint we also has such an insane amount.
given that each task take ~30 min of all computing power, this mean our feedback time become 4 hour!
However, most of the time is on testing, and most of the test are unrelated to what we changed.
Can we, when given test, only run them, if the relevant code is changed?
This is hard to do in general, but we can do something very coarse grained: if only a subproejct code get changed, only those test get run. So for example a pure vta change should only trigger vta test, relay change trigger relay test, etc.
I am not a jenkin master, so is this doable?

**Comment by tqchen** [comment]
Some of them are certainly doable, we have already tried to speed up things by using code cache. 

I would say in the short term, it would be still better to wait for the CI to complete while trying to make sure things pass in the first place. It is much easier to waste a bit of time here to just make sure everything is correct. We could just be mindful and do code polishment before things are sent to CI

**Comment by tqchen** [comment]
So in short, I think we will not do anything for now, please make sure you can run the relevant tests(lint, unittests) in your local env and use CI as a means to just safe check the last stage of the code
