### ISSUE TITLE
Support double buffer to use in ir builder DSL 

### ISSUE THREAD

**Issue by gaoxiong1** [dmlc/tvm#1897]
Currently, the node of double buffer AttrStmt use Operation type first, and  convert to Variable type by storage_flatten pass.  If we use  double buffer directly in ir builder DSL, which can only provide Variable as the AttrStmt's node, the storage_flatten will get error. So we can add some type check in storage_flatten to support this scene.

**Comment by tqchen** [comment]
closed by #1898 , thanks @gaoxiong1
