### ISSUE TITLE
nnvm/from_darknet   llvm::BranchInst::AssertOK() problem 

### ISSUE THREAD

**Issue by botaichang** [dmlc/tvm#1902]
when I run nnvm/from_darknet.py , I use target = 'llvm', but error as follows:

> lib/IR/Instructions.cpp:1130: void llvm::BranchInst::AssertOK(): Assertion `getCondition()->getType()->isIntegerTy(1) && "May only branch on boolean predicates!"' failed.
> Aborted (core dumped)
> 

do i need to replace llvm version ， i use llvm 6.0.1.

**Comment by wweic** [comment]
Hi, according the [community issue convention](https://github.com/dmlc/tvm/blob/f721a645cd77661a8284559d676ef20f91eaa771/.github/ISSUE_TEMPLATE.md), it's recommended to post to https://discuss.tvm.ai first. The community will help investigate and convert it into an actionable item laster as a github issue. And it's also very helpful to provide the exact command you use that cause the error and provide as much error log as possible.

**Comment by botaichang** [comment]
> Hi, according the [community issue convention](https://github.com/dmlc/tvm/blob/f721a645cd77661a8284559d676ef20f91eaa771/.github/ISSUE_TEMPLATE.md), it's recommended to post to https://discuss.tvm.ai first. The community will help investigate and convert it into an actionable item laster as a github issue. And it's also very helpful to provide the exact command you use that cause the error and provide as much error log as possible.

OK,thanks.
