### ISSUE TITLE
How to test a inference on ARM target

### ISSUE THREAD

**Issue by daeinki** [dmlc/tvm#1914]
Hi,

I am trying to test a inference on ARM target.
For this, I have created json, params and so library for ARM using python export_library function.
Ps. to create arm library, I should had modified python/tvm/contrib/cc.py code which allows cross compiler to be used instead of using fixed g++.

These file names have mxnet_resnet18_v1.json, mxnet_resnet18_v1.params and mxnet_resnet18_v1.so.
And than, I placed tvm runtime library for ARM and three files above to the target rootfs.

I'd like to test a inference on ARM target using a test application written with c or c++ language.

For the test application, I think I need to implement below functions,
- load so library.
- create graph runtime.
- load params file.
- convert input image to tensor.
- define output share

and lastly, run the module.

Is there any c or c++ based reference code for it? or anything I can refer to?

Thanks,
Inki Dae

**Comment by tqchen** [comment]
Thanks for asking the questions, please open a thread in https://discuss.tvm.ai/ . https://docs.tvm.ai/deploy/index.html might be helpful
