### ISSUE TITLE
nnvm.frontend.onnx Python API can't load current graph inputs

### ISSUE THREAD

**Issue by izgzhen** [dmlc/tvm#1931]
Possible root cause :https://github.com/dmlc/tvm/blob/f1a4b94be9488db9bbda7b5954cd58d814163ed5/nnvm/python/nnvm/frontend/onnx.py#L821

The `self._renames` above is never updated. So `inputs` is wrong.

Example application:

- https://gist.github.com/izgzhen/57f70c028cc561d079837ab16aead9b3
- https://gist.github.com/izgzhen/17d6236f8be3f34640ff0e7f5b40174f

(basically a RNN for NLP task exported by PyTorch and loaded in TVM, sorry that I didn't have sufficient time to construct a very good small test. But I think the bug is obvious from code).

**Comment by tqchen** [comment]
Thanks @izgzhen for reporting this? Can you send a patch to fixe the problem?
