### ISSUE TITLE
[Relay] IR Text Format Improvements

### ISSUE THREAD

**Issue by joshpoll** [dmlc/tvm#1935]
- [ ] Sophisticated tensor and function type annotations including type relations and generics

- [ ] Easy parser installation. Currently running make will build the parser provided you have ANTLR installed; however, we'd like to make it easy for others to use the text format parser even if they don't have ANTLR installed. One way we could accomplish this is to maintain a version of the parser somewhere and have users wget it.

- [ ] Support temp vars like `%0`, `%1`, etc. We need to agree on how to properly handle these.

- [ ] Graph construction support.

- [ ] Consistency between text format and text printer. We'd like `pretty_print(parse(<prog>)) = <prog>`.

- [ ] Better error messages.

- [ ] Attributes.

- [ ] Type suffixes.

**Comment by tqchen** [comment]
I am not sure if this is staled already, close this for now because this issue is rather inactive. Let us open new thread with smaller actionable items
