### ISSUE TITLE
c++ float16 calculatiion on Mali-T860

### ISSUE THREAD

**Issue by Howave** [dmlc/tvm#1942]
I convert the model and params to float16 format,

and set some parameters for float16 calculatiion.
    int dtype_code = kDLFloat;
    int dtype_bits = 16;
    int dtype_lanes = 1;
    int device_type = kDLOpenCL;
    int device_id = 0;

then uses float2half and half2float for data conversion.

but the results are wrong.

Could you have some guides？Thanks!

**Comment by tqchen** [comment]
Thanks for asking the question, please open a thread in https://discuss.tvm.ai/
