### ISSUE TITLE
HalideIR source code throw a runtime error:left shift of negative value -1

### ISSUE THREAD

**Issue by Youjk** [dmlc/tvm#1953]
In HalideIR source code , the 32 rows in file IR.cpp :

```
Expr IntImm::make(Type t, int64_t value) {
internal_assert(t.is_int() && t.is_scalar())
<< "IntImm must be a scalar Int\n";
internal_assert(t.bits() == 8 || t.bits() == 16 || t.bits() == 32 || t.bits() == 64)
<< "IntImm must be 8, 16, 32, or 64-bit\n";

// Normalize the value by dropping the high bits
value <<= (64 - t.bits());
// Then sign-extending to get them back
value >>= (64 - t.bits());

std::shared_ptr<IntImm> node = std::make_shared<IntImm>();
node->type = t;
node->value = value;
return Expr(node);
}
```

if value is negative, value <<= (64 - t.bits()) will cause a runtime error.
![image](https://user-images.githubusercontent.com/8721085/47291129-1ba1cf00-d635-11e8-85ae-0f96020e4b93.png)

can I modify the code in the 32 rows like this:
value =(uint64_t) value << (64 - t.bits());

**Comment by tqchen** [comment]
The code itself is correct and left shift of integer value is well defined. Can you try to update it as 

```c++
value <<= static_cast<int64_t>(64 - t.bits());
```

**Comment by Youjk** [comment]
I try to update the code as you say,it still causes the runtime error while the  value is negative,because the type of value is int64_t, so the high bit represents sign, and the left shitf may change the sign of the number. so  I modify the code like this to cast the value to uint64_t :
`value =(uint64_t) value << (64 - t.bits());`

**Comment by tqchen** [comment]
let us move further discussion to https://discuss.tvm.ai/
