### ISSUE TITLE
Reshape inputs size should be compatible

### ISSUE THREAD

**Issue by wincle** [dmlc/tvm#1972]
Hi , I have facing one problem , I'm running the "Compile Tensorflow Models" tutorial demo code, it's okay with the given model which is InceptionV1 from "https://github.com/dmlc/web-data/tree/master/tensorflow/models/InceptionV1" , But when I test my model which is InceptionV4, it  brings Error as follow:
`nnvm._base.NNVMError: Error in operator prefix/InceptionV4/Logits/PreLogitsFlatten/flatten/Reshape: [09:00:52] /tvm/nnvm/src/top/tensor/transform.cc:649: Check failed: in_attrs->at(0).Size() == in_attrs->at(1).Size() (1536 vs. 2) Reshape inputs size should be compatible`
The inputs of reshape op with shapes (1,1,1,1536) and 2
output shape is (?,?)
Could you please tell why did the error happened?

**Comment by tqchen** [comment]
Thanks for bringing up this problem, please open a thread at the community disucss forum https://discuss.tvm.ai

**Comment by srkreddy1238** [comment]
@wincle https://github.com/dmlc/tvm/pull/1923 should fix this issue.

**Comment by srkreddy1238** [comment]
@wincle you may follow the below discussion 
https://discuss.tvm.ai/t/tvm-tf-converter-bug-with-inception-v4-network/894/2

**Comment by wincle** [comment]
@tqchen Thx! I have post my question up there, it seems need time to show up for me.

**Comment by wincle** [comment]
Hi, @srkreddy1238 , Thanks for your reply , I have checked the links which you posted, your work is indeed valuable, but it still confused me because I didn't find the same problems as I met which happened in `nnvm.frontend.from_tensorflow` at the Reshape Op. 
Could you please explain clearly why did this error happened? Thx!
