### ISSUE TITLE
unable to find the interface function defined in TVM，when import tvm.dll to python.

### ISSUE THREAD

**Issue by Foundea** [dmlc/tvm#2003]
using VS2017 compiled TVM source to generated tvm.dll library ,but when we import this library to python， python unable to find the interface function defined in TVM。We found that the function name has changed in tvm.dll。
How to solve this problem？

D:\software\python2_64\libs>python
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import *
>>> dll= CDLL("tvm.dll")
>>> dll.const()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\software\python2_64\lib\ctypes\__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "D:\software\python2_64\lib\ctypes\__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError**: **function 'const' not found****
>>> dll.TVMSetStream()
0
>>>

Microsoft (R) COFF/PE Dumper Version 14.10.25017.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file D:\WORK\vstest\test_import\tvm.dll

File Type: DLL

  Section contains the following exports for tvm.dll

    00000000 characteristics
    5BC7F28F time date stamp Thu Oct 18 10:40:15 2018
        0.00 version
           1 ordinal base
         794 number of functions
         794 number of names

    ordinal hint RVA      name

          1    0 020DC9C4 ?$TSS0@?1??Mutate@IRMutator@ir@tvm@@UEAA?AUExpr@HalideIR@@U56@@Z@4HA = ?$TSS0@?1??Mutate@IRMutator@ir@tvm@@UEAA?AUExpr@HalideIR@@U56@@Z@4HA (int `public: virtual struct HalideIR::Expr __cdecl tvm::ir::IRMutator::Mutate(struct HalideIR::Expr)'::`2'::$TSS0)
          2    1 020DC9D4 ?$TSS0@?1??Mutate@IRMutator@ir@tvm@@UEAA?AUStmt@Internal@HalideIR@@U567@@Z@4HA = ?$TSS0@?1??Mutate@IRMutator@ir@tvm@@UEAA?AUStmt@Internal@HalideIR@@U567@@Z@4HA (int `public: virtual struct HalideIR::Internal::Stmt __cdecl tvm::ir::IRMutator::Mutate(struct HalideIR::Internal::Stmt)'::`2'::$TSS0)
          3    2 020DC9B4 ?$TSS0@?1??Visit@IRVisitor@ir@tvm@@UEAAXAEBVNodeRef@4@@Z@4HA = ?$TSS0@?1??Visit@IRVisitor@ir@tvm@@UEAAXAEBVNodeRef@4@@Z@4HA (int `public: virtual void __cdecl tvm::ir::IRVisitor::Visit(class tvm::NodeRef const &)'::`2'::$TSS0)
          4    3 020DC730 ?$TSS0@?1??_DerivedFrom@ComputeOpNode@tvm@@UEBA?B_NI@Z@4HA = ?$TSS0@?1??_DerivedFrom@ComputeOpNode@tvm@@UEBA?B_NI@Z@4HA (int `public: virtual bool const __cdecl tvm::ComputeOpNode::_DerivedFrom(unsigned int)const '::`2'::$TSS0)
          5    4 020DC728 ?$TSS0@?1??type_index@ComputeOpNode@tvm@@UEBA?BIXZ@4HA = ?$TSS0@?1??type_index@ComputeOpNode@tvm@@UEBA?BIXZ@4HA (TSS0<`template-parameter-2',tvm::ComputeOpNode::ype_index,void,int, ?? &>)
          6    5 0001E0D8 ??0AttrVisitor@tvm@@QEAA@$$QEAV01@@Z = @ILT+118995(??0AttrVisitor@tvm@@QEAA@$$QEAV01@@Z)
          7    6 0003779F ??0AttrVisitor@tvm@@QEAA@AEBV01@@Z = @ILT+223130(??0AttrVisitor@tvm@@QEAA@AEBV01@@Z)
          8    7 0005A2E5 ??0AttrVisitor@tvm@@QEAA@XZ = @ILT+365280(??0AttrVisitor@tvm@@QEAA@XZ)
          9    8 00022070 ??0CompileError@HalideIR@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z = @ILT+135275(??0CompileError@HalideIR@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
         10    9 0002826D ??0ComputeOpNode@tvm@@QEAA@$$QEAV01@@Z = @ILT+160360(??0ComputeOpNode@tvm@@QEAA@$$QEAV01@@Z)
         11    A 0006642D ??0ComputeOpNode@tvm@@QEAA@AEBV01@@Z = @ILT+414760(??0ComputeOpNode@tvm@@QEAA@AEBV01@@Z)
         12    B 00001AAA ??0ComputeOpNode@tvm@@QEAA@XZ = @ILT+2725(??0ComputeOpNode@tvm@@QEAA@XZ)
         13    C 00032A83 ??0Error@HalideIR@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z = @ILT+203390(??0Error@HalideIR@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
         14    D 00061437 ??0ErrorReport@Internal@HalideIR@@QEAA@PEBDH0H@Z = @ILT+394290(??0ErrorReport@Internal@HalideIR@@QEAA@PEBDH0H@Z)
         15    E 0006BF27 ??0Expr@HalideIR@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z = @ILT+438050(??0Expr@HalideIR@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
         16    F 00025E96 ??0Expr@HalideIR@@QEAA@C@Z = @ILT+151185(??0Expr@HalideIR@@QEAA@C@Z)
     )
         65   40 0002343E ??7tvm@@YA?AUExpr@HalideIR@@U12@@Z = @ILT+140345(??7tvm@@YA?AUExpr@HalideIR@@U12@@Z)
         66   41 0006B56D ??8float16_t@HalideIR@@QEBA_NU01@@Z = @ILT+435560(??8float16_t@HalideIR@@QEBA_NU01@@Z)
         67   42 00022683 ??8tvm@@YA?AUExpr@HalideIR@@U12@0@Z = @ILT+136830(??8tvm@@YA?AUExpr@HalideIR@@U12@0@Z)
         68   43 0006AA00 ??9float16_t@HalideIR@@QEBA_NU01@@Z = @ILT+432635(??9float16_t@HalideIR@@QEBA_NU01@@Z)
         69   44 0000F95C ??9tvm@@YA?AUExpr@HalideIR@@U12@0@Z = @ILT+59735(??9tvm@@YA?AUExpr@HalideIR@@U12@0@Z)
         70   45 00070063 ??ASchedule@tvm@@QEAA?AVStage@1@AEBVOperation@1@@Z = @ILT+454750(??ASchedule@tvm@@QEAA?AVStage@1@AEBVOperation@1@@Z)

        778  309 00003D14 TVMFuncListGlobalNames = @ILT+11535(TVMFuncListGlobalNames)
        779  30A 00022179 TVMFuncRegisterGlobal = @ILT+135540(TVMFuncRegisterGlobal)
        780  30B 000593A9 TVMGetLastError = @ILT+361380(TVMGetLastError)
        781  30C 000576BC TVMModFree = @ILT+353975(TVMModFree)
        782  30D 000387B7 TVMModGetFunction = @ILT+227250(TVMModGetFunction)
        783  30E 0003ADCD TVMModImport = @ILT+237000(TVMModImport)
        784  30F 0006A5CD TVMModLoadFromFile = @ILT+431560(TVMModLoadFromFile)
        785  310 00043A86 TVMNodeFree = @ILT+273025(TVMNodeFree)
        786  311 0005F731 TVMNodeGetAttr = @ILT+386860(TVMNodeGetAttr)
        787  312 00073605 TVMNodeGetTypeIndex = @ILT+468480(TVMNodeGetTypeIndex)
        788  313 00011315 TVMNodeListAttrNames = @ILT+66320(TVMNodeListAttrNames)
        789  314 00006D07 TVMNodeTypeKey2Index = @ILT+23810(TVMNodeTypeKey2Index)
        790  315 00050763 TVMSetStream = @ILT+325470(TVMSetStream)
        791  316 0003DD11 TVMStreamCreate = @ILT+249100(TVMStreamCreate)
        792  317 00011C20 TVMStreamFree = @ILT+68635(TVMStreamFree)
        793  318 00037105 TVMStreamStreamSynchronize = @ILT+221440(TVMStreamStreamSynchronize)
        794  319 000113B5 TVMSynchronize = @ILT+66480(TVMSynchronize)

**Comment by tqchen** [comment]
Thanks for bringing this up, please open a new thread at https://discuss.tvm.ai/

**Comment by Foundea** [comment]
Hi，open this topic at:
https://discuss.tvm.ai/t/using-vs2017-compiled-tvm-source-to-generated-tvm-dll-library-but-this-library-unable-to-import-python/1044
