### ISSUE TITLE
[RFC] Community Guideline Improvements

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#2017]
Thanks for everyone who actively participates in the contribution and governing for the community. Since we started with the current [govenance model](https://docs.tvm.ai/contribute/community.html) our community has grown considerably. It is glad to see that some success participation including 1) Emphasize on code reviews and high review coverage which helps to improve the code quality. 2) Emphasize of test-cases. 3)Active proposals of RFCs and encourages everyone to participates in the decision; most importantly, our diverse set of contributors and their willingness to spend personal time to help each other.

As the project moves forward, it is a good time to summarize the lessons we learned and discuss how can we improve the community guidelines to make the project great for everyone. I draft this RFC based on discussions with current committers and invite everyone in the community to discuss.

## Committers and CodeOwners

The first proposal is to merge CodeOwners with committers. The reasoning behind this proposal is that CodeOwners already own a module and they should really have the write permission to do so. Of course, since the write permission granted to committers are global, we would trust our code owners to only merge the code that they see fit, and I think they will.  

In the same time, we would also like to have a broader set of PMCs. The current set of committers are already standing up roles as PMCs. So the proposal would be to invite the current CodeOwners as committers, and current committers as PMC.

I would also like us to discuss what traits should we look for in potential committers, is there anything we should add or emphasize besides the current guideline.

## Consensus Building

The fascinating part of open source is the number of contributions that is happening. Admittedly, as the community grows we need to think about how can we reach consensus among the community when there are disagreements. 

One way is to always encourage a broader set of discussions between in the entire community, hopefully, to get everyone's agreement. The PMCs who have the expertise on the specific topic would moderate the discussions and possibly make suggestions.

## Collaboration

High stake open source projects usually involve corporation interests, and it is good to have so as the push by major companies would really help the project growth. Inevitably, we usually talk to folks who sit close to us, and that can unintentionally create circles. It is important for us as a community to think how can constructively collaborate with others, especially with those outside our organizations. Specifically, here are something that might help: try to review code from newcomers who do not sit next to ourselves; recognize their contributions and help solve the problem together; encourage code reviews from people other than our colleagues; PMCs should strive to nominate committers from other organizations

We do not have a definitive answer to this question. But we do want to make the community welcoming as a whole so that everyone can contribute and get recognized as part of our community. We might want to incorporate some of that when evaluating new reviewers, committers and PMC members.

These are just a few thoughts that I summarized. As per our common practice, everyone in the community is encouraged to participate in RFC, and please share your thoughts.

**Comment by tqchen** [comment]
cc @dmlc/tvm-team

**Comment by ZihengJiang** [comment]
SGTM. 
IMHO, encouraging the collabration between members from different orgranizations would definitely help the development of community.

**Comment by srkreddy1238** [comment]
Yes, current cooperation is within close circles.

+1 for collaboration across organizations.

Some options I see are irc chats, summary reports by calls or news letter ( may be monthly).

**Comment by FrozenGene** [comment]
One suggestion: we can set up one `slack` channel.

**Comment by masahi** [comment]
just FYI, we already have slack at https://tvmai.slack.com

**Comment by tqchen** [comment]
We have a slack channel which @masahi mentioned and it is kind of abandoned in favor of the public discuss forum. We could revive it in somehow, but on second thought maybe it is good to keep most discussion public in async fashion, thus the github issue/discuss would be better place to do so

**Comment by nhynes** [comment]
> slack

I kind of like when there are public semi-synchronous discussion groups for when I have a one-off question that's blocking my progress. I also like responding to messages when I'm slacking (in the literal sense).

For comparison, the PyTorch slack is a really happenin' place where much debugging and knowledge transfer happens.

**Comment by tmoreau89** [comment]
I do have a preference for using the discuss forums, but @nhynes brings up a good point w.r.t. getting quick answers in Slack. 

However, one of the benefits of the forums is being able to search through history, and the latter being indexable by search engines. Would Slack give us the same benefits? Right now we have a free slack organization, and we'd certainly have to upgrade to a paid one to at least be able to preserve chat history.

**Comment by yzhliu** [comment]
I like the idea of nominating committers and reviewers more from other organizations, it helps build diversity and improves collaboration within the community.

**Comment by slyubomirsky** [comment]
I agree with @tmoreau89 on the benefit of forums being conveniently searchable. It is much easier and more natural to resurrect an old forum thread if the topic has become relevant again than it is to keep a discussion going in a Slack channel

**Comment by jroesch** [comment]
Yeah I think @nhynes brings up a good point about slack being a good place for people to do quick knowledge exchanges while developing/hacking on TVM.

**Comment by tqchen** [comment]
Thanks for everyone who participates in the discussion, I have opened #2077 as a proposed new community guideline

**Comment by tqchen** [comment]
#2077 is now merged, I will send out emails to the current code owners shortly about the new committership rules. Thanks to everyone's participation to make the community better!
