### ISSUE TITLE
tvm is not compatible with llvm 7.0.0

### ISSUE THREAD

**Issue by KingOnTheStar** [dmlc/tvm#2053]
This is a bug report.
I followed the install tutorials of tvm and install llvm 7.0.0, then run tutorials/autotvm/tune_simple_template.py. Then I got this error:

RuntimeError: Compilation error:\n/usr/bin/ld: /tmp/tmpdv8hmu/lib.o: relocation R_X86_64_32S against `.rodata.cst16\' can not be used when making a shared object

After changing llvm 7.0.0 to llvm 4.0.0, everything work well.
I use Unbuntu16.04, cuda10

**Comment by yzhliu** [comment]
Looks like it is something wrong with autotvm or rpc library loading. I encountered same problem running https://docs.tvm.ai/tutorials/autotvm/tune_nnvm_x86.html. llvm 6 is good. @merrymercy any idea?

**Comment by yzhliu** [comment]
Local compiling & runtime is good with llvm 7, as far as I see.

**Comment by tqchen** [comment]
seems to be duplicate with https://github.com/dmlc/tvm/issues/2005, let us move all discussion to there

**Comment by carlushuang** [comment]
https://discuss.tvm.ai/t/runtime-llvm-cc-create-shared-error-while-run-tune-simple-template/1037

same issue with above link
