### ISSUE TITLE
android deploy crash!! when exe_gpu=true

### ISSUE THREAD

**Issue by wayen820** [dmlc/tvm#2058]
I use Release v0.4 version,when I set exe_gpu=false in mainactivity,everything is ok,but when I set exe_gpu=true,app is crash! the log is:
`11-03 11:01:39.495 26668-27014/ml.dmlc.tvm.android.demo E/libc++abi: terminating with uncaught exception of type dmlc::Error: [11:01:39] /home/wayen/program/tvm-work/tvm0.4/tvm/apps/android_deploy/app/src/main/jni/jni_helper_func.h:194: Do NOT know how to handle return type code 127`
I pull the master branch code and try again,it do not make any different.

**Comment by tqchen** [comment]
Thanks for reporting the error, please open a new thread at https://discuss.tvm.ai/, when possible, provide more details of your setup
