### ISSUE TITLE
Error : python setup.py install 

### ISSUE THREAD

**Issue by chenjunweii** [dmlc/tvm#2072]
I just Re-Compile TVM after the system upgrade, I got the following error when using command " python setup.py install " to install python package on python3, nnvm and topi package are free from the error, I've also tried to install tvm on python2, and it works, only python3 version of tvm got those error

g++, gcc : 6.4.1
python3 version : 3.7.1
OS : Arch Linux

/usr/lib/python3.7/site-packages/setuptools/dist.py:398: UserWarning: Normalizing '0.5.dev' to '0.5.dev0'
  normalized_version,
running install
running bdist_egg
running egg_info
writing tvm.egg-info/PKG-INFO
writing dependency_links to tvm.egg-info/dependency_links.txt
writing requirements to tvm.egg-info/requires.txt
writing top-level names to tvm.egg-info/top_level.txt
reading manifest file 'tvm.egg-info/SOURCES.txt'
writing manifest file 'tvm.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'tvm._ffi._cy3.core' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -flto=4 -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I../include/ -I../3rdparty/dmlc-core/include -I../3rdparty/dlpack/include -I/usr/include/python3.7m -c tvm/_ffi/_cython/core.cpp -o build/temp.linux-x86_64-3.7/tvm/_ffi/_cython/core.o
g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=4 -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-x86_64-3.7/tvm/_ffi/_cython/core.o -L/usr/lib -lpython3.7m -o build/lib.linux-x86_64-3.7/tvm/_ffi/_cy3/core.cpython-37m-x86_64-linux-gnu.so
g++: error trying to exec 'lto1': execvp: No such file or directory
lto-wrapper: fatal error: g++ returned 1 exit status
compilation terminated.
ld: error: lto-wrapper failed
error: command 'g++' failed with exit status 1

Any Solution ?

**Comment by tqchen** [comment]
Thanks for bringing this up, please open a thread at https://discuss.tvm.ai/
