### ISSUE TITLE
Web Run Time Not Built After ReadMe Instructions

### ISSUE THREAD

**Issue by nrothGIT** [dmlc/tvm#2086]
Hi! 

I have followed the build instruction at https://github.com/dmlc/tvm/tree/master/web. I am running [Ubuntu-16.04.](url
[config.cmake.txt](https://github.com/dmlc/tvm/files/2568667/config.cmake.txt)
) I was successfully able to compile with the -web flag and there were no errors. However, when I try to run the basic test, I get the following Errors:

"Ä11:10:28Ü /home/nat/testgl/tvm/src/codegen/llvm/codegen_llvm.cc:75: Set native vector bits to be 128 for asmjs
Traceback (most recent call last):
 File "prepare_test_libs.py", line 21, in <module>
   prepare_test_libs(os.path.join(curr_path, "./"))
 File "prepare_test_libs.py", line 17, in prepare_test_libs
   emscripten.create_js(os.path.join(base_path, "test_module.js"), obj_path)
 File "/usr/local/lib/python2.7/dist-packages/tvm-0.5.dev0-py2.7-linux-x86_64.egg/tvm/contrib/emscripten.py", line 48, in create_js
   objects += Äfind_lib_path("libtvm_web_runtime.bc")Ä0ÜÜ
 File "/usr/local/lib/python2.7/dist-packages/tvm-0.5.dev0-py2.7-linux-x86_64.egg/tvm/_ffi/libinfo.py", line 93, in find_lib_path
   raise RuntimeError(message)
RuntimeError: Cannot find the files.
List of candidates:
/usr/local/cuda-9.0/lib64/libtvm_web_runtime.bc
/home/nat/testgl/tvm/tests/web/libtvm_web_runtime.bc
/usr/local/lib/python2.7/dist-packages/tvm-0.5.dev0-py2.7-linux-x86_64.egg/tvm/libtvm_web_runtime.bc
/usr/local/lib/python2.7/dist-packages/build/libtvm_web_runtime.bc
/usr/local/lib/python2.7/dist-packages/build/Release/libtvm_web_runtime.bc
/usr/local/lib/python2.7/dist-packages/lib/libtvm_web_runtime.bc
/usr/local/lib/python2.7/libtvm_web_runtime.bc"

Where should the libtvm_web_runtime.bc live after the run of make -web? I have attached my config file as well. Am I missing something? It just appears that the build does not generate a libtvm_web_runtime.bc.

To build, I am copying over the config.cmake to a build folder. The I run cmake .. and then make -web. If I examine the Makefile, it is different than the one checked into master and it appears none of the web_runtime scripting is in there.

**Comment by tqchen** [comment]
Thanks for bringing up the issue, can you please open a new thread at https://discuss.tvm.ai/? Here is the particular rule, you need to type make web in the root folder(as it is not part of CMake rules)

**Comment by tqchen** [comment]
see https://github.com/dmlc/tvm/blob/master/Makefile#L41

**Comment by nrothGIT** [comment]
Thanks for the response, I've moved it to here https://discuss.tvm.ai/t/undefined-symbols-in-web-runtime-following-tutorial-steps/1121

**Comment by DavidGOrtega** [comment]
Ubuntu 16.04

I can't build it either!

I follow the instructions compiling the libraries but I'm not able to build the runtime. I have a weird error. Can't find execinfo.h 

```
root@dgo-ubuntu:~/tvm/build# ls
CMakeCache.txt  cmake_install.cmake    config.cmake         libtvm_runtime.so  libtvm_topi.so  Makefile
CMakeFiles      compile_commands.json  libnnvm_compiler.so  libtvm.so          libvta.so       web
root@dgo-ubuntu:~/tvm/build# make sss
make: *** No rule to make target 'sss'.  Stop.
root@dgo-ubuntu:~/tvm/build# make web
root@dgo-ubuntu:~/tvm/build# make ss
make: *** No rule to make target 'ss'.  Stop.
root@dgo-ubuntu:~/tvm/build# make web
root@dgo-ubuntu:~/tvm/build# cd web/
root@dgo-ubuntu:~/tvm/build/web# ls
web_runtime.d
root@dgo-ubuntu:~/tvm/build/web# cd ..
root@dgo-ubuntu:~/tvm/build# cd ..
root@dgo-ubuntu:~/tvm# make web
emcc -std=c++11 -DDMLC_LOG_STACK_TRACE=0 -Oz -s RESERVED_FUNCTION_POINTERS=2 -s MAIN_MODULE=1 -s NO_EXIT_RUNTIME=1 -s TOTAL_MEMORY=1073741824 -s EXTRA_EXPORTED_RUNTIME_METHODS="['cwrap','getValue','setValue','addFunction']" -s USE_GLFW=3 -s USE_WEBGL2=1 -lglfw -Iinclude -I/root/tvm/3rdparty/dlpack/include -I/root/tvm/3rdparty/dmlc-core/include -MM -MT build/libtvm_web_runtime.bc web/web_runtime.cc >build/web/web_runtime.d
In file included from web/web_runtime.cc:8:
In file included from web/../src/runtime/c_runtime_api.cc:6:
In file included from /root/tvm/3rdparty/dmlc-core/include/dmlc/thread_local.h:12:
In file included from /root/tvm/3rdparty/dmlc-core/include/dmlc/./base.h:271:
/root/tvm/3rdparty/dmlc-core/include/dmlc/build_config.h:25:11: warning: 'DMLC_LOG_STACK_TRACE' macro redefined [-Wmacro-redefined]
  #define DMLC_LOG_STACK_TRACE 1
          ^
<command line>:5:9: note: previous definition is here
#define DMLC_LOG_STACK_TRACE 0
        ^
In file included from web/web_runtime.cc:8:
In file included from web/../src/runtime/c_runtime_api.cc:9:
In file included from include/tvm/runtime/packed_func.h:9:
/root/tvm/3rdparty/dmlc-core/include/dmlc/logging.h:20:10: fatal error: 'execinfo.h' file not found
#include DMLC_EXECINFO_H
         ^
/root/tvm/3rdparty/dmlc-core/include/dmlc/build_config.h:27:27: note: expanded from macro 'DMLC_EXECINFO_H'
  #define DMLC_EXECINFO_H <execinfo.h>
                          ^~~~~~~~~~~~
1 warning and 1 error generated.
Makefile:42: recipe for target 'build/libtvm_web_runtime.bc' failed
make: *** [build/libtvm_web_runtime.bc] Error 1
```

If I comment the line 27 n build_config.h I have others errors:

```
root@dgo-ubuntu:~/tvm# make web
emcc -std=c++11 -DDMLC_LOG_STACK_TRACE=0 -Oz -s RESERVED_FUNCTION_POINTERS=2 -s MAIN_MODULE=1 -s NO_EXIT_RUNTIME=1 -s TOTAL_MEMORY=1073741824 -s EXTRA_EXPORTED_RUNTIME_METHODS="['cwrap','getValue','setValue','addFunction']" -s USE_GLFW=3 -s USE_WEBGL2=1 -lglfw -Iinclude -I/root/tvm/3rdparty/dlpack/include -I/root/tvm/3rdparty/dmlc-core/include -MM -MT build/libtvm_web_runtime.bc web/web_runtime.cc >build/web/web_runtime.d
In file included from web/web_runtime.cc:8:
In file included from web/../src/runtime/c_runtime_api.cc:6:
In file included from /root/tvm/3rdparty/dmlc-core/include/dmlc/thread_local.h:12:
In file included from /root/tvm/3rdparty/dmlc-core/include/dmlc/./base.h:271:
/root/tvm/3rdparty/dmlc-core/include/dmlc/build_config.h:25:11: warning: 'DMLC_LOG_STACK_TRACE' macro redefined [-Wmacro-redefined]
  #define DMLC_LOG_STACK_TRACE 1
          ^
<command line>:5:9: note: previous definition is here
#define DMLC_LOG_STACK_TRACE 0
        ^
In file included from web/web_runtime.cc:8:
In file included from web/../src/runtime/c_runtime_api.cc:9:
In file included from include/tvm/runtime/packed_func.h:9:
/root/tvm/3rdparty/dmlc-core/include/dmlc/logging.h:20:10: error: expected "FILENAME" or <FILENAME>
#include DMLC_EXECINFO_H
         ^
In file included from web/web_runtime.cc:8:
In file included from web/../src/runtime/c_runtime_api.cc:9:
In file included from include/tvm/runtime/packed_func.h:18:
In file included from include/tvm/runtime/module.h:11:
In file included from /root/tvm/3rdparty/dmlc-core/include/dmlc/./io.h:445:
In file included from /root/tvm/3rdparty/dmlc-core/include/dmlc/./serializer.h:22:
/root/tvm/3rdparty/dmlc-core/include/dmlc/./endian.h:24:6: error: "Unable to determine endianness of your machine; use CMake to compile"
    #error "Unable to determine endianness of your machine; use CMake to compile"
     ^
1 warning and 2 errors generated.
Makefile:42: recipe for target 'build/libtvm_web_runtime.bc' failed
make: *** [build/libtvm_web_runtime.bc] Error 1
```

**Comment by tqchen** [comment]
should be fixed by https://github.com/dmlc/tvm/pull/2379

**Comment by DavidGOrtega** [comment]
There is a minor issue in the docs

```
This will create lib/libtvm_web_runtime.bc and lib/libtvm_web_runtime.js.
```

However the files are created inside bin folder:

```
root@dgo-ubuntu:~/tvm/build# ls
CMakeCache.txt  cmake_install.cmake    config.cmake         libtvm_runtime.so  libtvm_topi.so             libtvm_web_runtime.bc  libtvm_web_runtime.wasm  Makefile
CMakeFiles      compile_commands.json  libnnvm_compiler.so  libtvm.so          libtvm_web_runtime.asm.js  libtvm_web_runtime.js  libvta.so                web

```
