### ISSUE TITLE
[Compile Error on Windows]

### ISSUE THREAD

**Issue by FreshHillyer** [dmlc/tvm#2087]
When i follow the installation, i compile the tvm while meeting some errors. And these erros cause the Release/tvm.lib cant generate. How can I fix this？

> 1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(932): error C2065: “uint”: 未声明的标识符
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(932): error C2146: 语法错误: 缺少“;”(在标识符“i”的前面)
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(932): error C2143: 语法错误: 缺少“;”(在“=”的前面)
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(932): error C2143: 语法错误: 缺少“)”(在“=”的前面)
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(932): error C2059: 语法错误:“=”
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(932): error C2065: “i”: 未声明的标识符
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(932): error C2059: 语法错误:“)”
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(933): error C2059: 语法错误:“if”
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(936): error C2065: “i”: 未声明的标识符
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(937): error C2065: “i”: 未声明的标识符
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(941): error C2065: “begin”: 未声明的标识符
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(944): error C2065: “begin”: 未声明的标识符
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(946): error C2065: “fields”: 未声明的标识符
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(947): error C2065: “fields”: 未声明的标识符
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(947): error C2660: “tvm::relay::TypeReporterNode::Assign”: 函数不接受 1 个参数
1>c:\users\usr\documents\github\tvm\include\tvm\relay\type.h(280): note: 参见“tvm::relay::TypeReporterNode::Assign”的声明
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(949): error C2059: 语法错误:“return”
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(955): error C2065: “SplitAttrs”: 未声明的标识符
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(955): error C2672: “tvm::make_node”: 未找到匹配的重载函数
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(955): error C2974: 'tvm::make_node' : 模板 对于 'T'是无效参数，应为类型
1>c:\users\usr\documents\github\tvm\3rdparty\halideir\src\tvm\node\node_base.h(86): note: 参见“tvm::make_node”的声明
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(956): error C3536: “attrs”: 初始化之前无法使用
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(958): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(958): error C2143: 语法错误: 缺少“;”(在“&”的前面)
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(958): error C2065: “op”: 未声明的标识符
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(958): error C2825: 'Op': 当后面跟“::”时必须为类或命名空间
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(958): error C2510: “Op”:“::”的左边必须是类/结构/联合
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(958): error C3861: “Get”: 找不到标识符
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(959): error C2653: “CallNode”: 不是类或命名空间名称
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(959): error C2065: “op”: 未声明的标识符
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(959): error C2440: “<function-style-cast>”: 无法从“int”转换为“tvm::Attrs”
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(959): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(959): error C3861: “make”: 找不到标识符
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(986): error C2065: “SplitRel”: 未声明的标识符
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(971): error C2530: “tvm::__make_RelayOp31”: 必须初始化引用
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(989): error C2059: 语法错误:“}”
1>c:\users\usr\documents\github\tvm\src\relay\op\tensor\transform.cc(989): error C2143: 语法错误: 缺少“;”(在“}”的前面)
1>已完成生成项目“tvm.vcxproj”的操作 - 失败。
3>------ 已启动生成: 项目: nnvm_compiler, 配置: Release x64 ------
4>------ 已启动生成: 项目: tvm_topi, 配置: Release x64 ------
3>LINK : fatal error LNK1181: 无法打开输入文件“Release\tvm.lib”
3>已完成生成项目“nnvm_compiler.vcxproj”的操作 - 失败。
4>LINK : fatal error LNK1181: 无法打开输入文件“Release\tvm.lib”
4>已完成生成项目“tvm_topi.vcxproj”的操作 - 失败。

**Comment by tqchen** [comment]
Please open a new thread at https://discuss.tvm.ai/

**Comment by smartwell** [comment]
> Please open a new thread at https://discuss.tvm.ai/

same problem,  i install LLVM successfully,but when i build tvm.sln with LLVM and cuda is ‘ON’，what can i do ?
