### ISSUE TITLE
Typo in web tutorial

### ISSUE THREAD

**Issue by almson** [dmlc/tvm#2108]
In https://docs.tvm.ai/tutorials/nnvm_quick_start.html line

    net, params = nnvm.testing.resnet.get_workload(
    layers=18, batch_size=batch_size, image_shape=image_shape)

`layers=18' should be 'num_layers=18'

**Comment by tqchen** [comment]
good catch, can you send a patch to fix https://github.com/dmlc/tvm/blob/master/tutorials/nnvm_quick_start.py#L53?
Thanks!
