### ISSUE TITLE
[CONTRIB] NNPack Test Flaky

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#2109]
http://ci.tvm.ai:8080/job/tvm/job/PR-2103/1/consoleText

cc @ajtulloch can you take a look?

**Comment by ajtulloch** [comment]
The error is nnp_status_unsupported_hardware, I’ll send a diff which exposes nnp_initialize() to TVM and add a check that nnp_initialize succeeds before invoking the rest of the year. Does that sound good?

**Comment by tqchen** [comment]
that sounds good

**Comment by ajtulloch** [comment]
Fix in https://github.com/dmlc/tvm/pull/2119/
