### ISSUE TITLE
Tensorflow nnvm shape error

### ISSUE THREAD

**Issue by daweili1226** [dmlc/tvm#2162]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by daweili1226** [comment]
Traceback (most recent call last):
  File "x.py", line 142, in <module>
    graph, lib, params = nnvm.compiler.build(sym, shape=shape_dict, target=target, target_host=target_host, dtype=dtype_dict, params=params)
  File "/homed/lidw/tvm/nnvm/python/nnvm/compiler/build_module.py", line 270, in build
    ishape, _ = graph_util.infer_shape(graph, **shape)
  File "/homed/lidw/tvm/nnvm/python/nnvm/compiler/graph_util.py", line 31, in infer_shape
    graph = graph.apply("InferShape")
  File "/homed/lidw/tvm/nnvm/python/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/homed/lidw/tvm/nnvm/python/nnvm/_base.py", line 75, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: Error in operator model_with_buckets/embedding_attention_decoder_6/attention_decoder/attention_decoder/MatMul: [21:57:07] /homed/lidw/tvm-zx/nnvm/src/top/nn/nn.cc:58: Operator dense(use_bias=False, units=128, name=model_with_buckets/embedding_attention_decoder_6/attention_decoder/attention_decoder/MatMul) expects weight's shape to be [128,128], but got [128,384].

**Comment by daweili1226** [comment]
I ran an OCR model and the above error occurred, can someone help me figure it out? Appreciated.

**Comment by eqy** [comment]
Can you please move this topic to the discuss board?
