### ISSUE TITLE
[ARITH] Simplifier Improvement

### ISSUE THREAD

**Issue by sgrechanik-h** [dmlc/tvm#2173]
* The simplifier does not simplify `(y - x) - y`. Interestingly, `(y - x) - y < 0` is simplified, but `(y - x) - y > 0` is not:
  ```
  x = tvm.var('x')
  y = tvm.var('y')
  print(tvm.ir_pass.Simplify((y - x) - y))
  print(tvm.ir_pass.Simplify((y - x) - y > 0))
  print(tvm.ir_pass.Simplify((y - x) - y < 0))

  Output:
  ((y - x) - y)
  (0 < ((y - x) - y))
  (0 < x)
  ```
  `CanonicalSimplify` works well on this example though.
* The simplifier rewrites `(3*x + y)/3` into `x + (y/3)`. Since tvm uses C/C++ truncated division instead of flooring or euclidean division, this is wrong (e.g. `x = 1, y = -1`). Recently there was a related issue [here](https://discuss.tvm.ai/t/fixed-dangerous-optimization-in-simplify/913). However, instead of disabling another simplification rule I would suggest discussing another option: using Euclidean division in TVM, since the Euclidean definition has some advantages regarding program transformations, and it was originally used in Halide.

**Comment by tqchen** [comment]
Some of these are not as problematic, because they can be caught by CanonicalSimplify. 
Eventually, we will need a new simplifier that takes all of these into consideration, and do reasonable integer set analysis hopefully in the next release cycle

**Comment by tqchen** [comment]
To follow-up on Euclidean divisions, I agree that euclidean div is nice for analysis. The main problem of Euclidean div generation is it is relatively hard to generate efficient low-level code for it. Unless we have a strict analysis of positiveness of the index, in which case the definition of division won't matter. So the case now is we would just stick for floor div as it is close to machine code, improve the integer set analysis to cover the range of the variable and then revisit the issue later

**Comment by sgrechanik-h** [comment]
By the way, turned out the HalideIR submodule hasn't been updated for a while, so the fix of @xqdan is not  in TVM yet. (Unfortunately it doesn't solve my case of incorrect simplification anyway).

I would still vote for Euclidean division, and concerning its problems, I would suggest the following plan:
- Rename Div and Mod in IR to EuclideanDiv and EuclideanMod
- Add explicit functions like euclidean_div, truncated_div, etc into the python interface. The ordinary `/` and `%` operators should be translated into expressions checking that their arguments are non-negative and throwing an exception or something like that when they are negative.
- Add a pass rewriting EuclideanDiv in terms of truncated div. As a result, select expressions will appear, but I think they can be effectively eliminated in most cases even with the existing integer set analysis and simplification. Of course, we have to think about some kind of performance regression testing before doing this.

If we choose truncated division, then we should do something with the HalideIR simplifier, because it is used everywhere and is heavily relied upon, and we cannot just replace it with CanonicalSimplify yet.

**Comment by tqchen** [comment]
Given that truncate div is the current way and the limited simplification works fine for now, I propose us to do the following thing, from pragmatic point of view:

- Upgrade the integer set analysis to cover most cases on positiveness testing
- Keep Div/Mod as truncated version as developers in c++/LLVM are more familar with this semantics(no surprise principle).
   - If necessary, I wont mind disabling some of the rules temporary, given that the div rules in the index simplification do not play an important role for perf.
- Add CeilDiv or EuclideanDiv to the IR.
- Do the truncated rewriting pass as @sgrechanik-h suggested.

Since this would be a major change to the analysis pipeline, we might want to do it in the next release cycle.

**Comment by tqchen** [comment]
move to #2588
