### ISSUE TITLE
[COMMUNITY][RFC] Developer Slack Channel

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#2174]
As a followup of https://github.com/dmlc/tvm/issues/2017, @nhynes suggested that we should still make use of slack, to some extent for semi-sync communications. So we have revived the https://tvmai.slack.com channel. This RFC is used to discuss among the community on the purpose of the slack channel vs other communication channels (discuss, issues). All the current committers should have admin access, please ask one of them to add you if you would like to join.

So far we have a clear model to use github issues/PRs for development items that are actionable and discuss forum for general discussions. As discussed in #2017, the advantage of these channels is that they are publically archived and searchable. Hopefully, the reintroduction of slack complements discuss and github issues.

I would like to use this RFC to discuss the guidelines for using the slack channel

Ideally, we should use slack by assuming that it is not necessarily publically archived(this is especially true for p2p chats). The purpose of the slack is to provide a semi-synchronized way for our developers to quickly chat and collaborate.  In another word, any member in the community should be able to join the development anytime by only look at the github and the discuss forum.

- General usage questions should be redirected to discuss forums.
- Development decisions should be sent in in forms of RFCs.
- When chat happens and technical development issues become long and there are valuable  things, consider moving the discussion to the discuss forum, or summarize the result of the discussion.

Please share your thoughts

cc @dmlc/tvm-team

**Comment by masahi** [comment]
Communication on slack worked quite well during rocm backend development. You can see the amount of chat we had on rocm channel. So yes, I think slack is great for certain purpose, and we already have a success story for that.

**Comment by were** [comment]
I cannot enter this channel because I have no CMU/UCB/UW edu email address.

**Comment by tqchen** [comment]
@were I just send an invitation to you

**Comment by srkreddy1238** [comment]
Can someone send an invitation to me ?

**Comment by tqchen** [comment]
@srkreddy1238 invitation sent, sorry about that

**Comment by grwlf** [comment]
May I join this channel too?

**Comment by ehsanmok** [comment]
@tqchen could you please send the invitation to me as well?

**Comment by sgrechanik-h** [comment]
Could you please invite me too?

**Comment by zhiics** [comment]
Could you please sent me an invitation as well? Thanks.

**Comment by tqchen** [comment]
Thanks for everyone's participation. Please reach out to any of the current committers to add yourself to the slack. As a guideline, we still encourage discussions in public searchable places such as forum and issues when possible.

**Comment by mjs-arm** [comment]
Can someone send me an invitation to the slack channel please?

**Comment by tqchen** [comment]
Invitation sent, for follow up requests please open a thread with the "development" category in https://discuss.tvm.ai/.

Again, the slack channel is used for quick communication between developers, and we do not intend to use for long discussions and technical decisions. We welcome topics in the discuss forum, which is publically archived so everyone in the community can see and participate
