### ISSUE TITLE
[RELAY][PASS] Check Positiveness in FoldScaleAxis

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#2182]
This issue is bought up by @merrymercy . So far FoldScaleAxis is able to pass through functions like relu. However, this is only true if the scaling factor is all positive number -- we didn't encounter this problem so far because most networks only have scaling coming from BN and the result is positive constant. 

We should update the pass by running the following thing:
- Do constant folding before running FoldScaleAxis
- Check positiveness of the scale(since scale is constant it is not hard to do so)
- Only allow passing relu through if the scale is positive.

**Comment by tqchen** [comment]
@eqy @vinx13 please let us know if you are interested in working on it

**Comment by vinx13** [comment]
I will work on this

**Comment by vinx13** [comment]
@tqchen Since the element type of `tvm::runtime::NDArray` is only available at runtime, is there a better way to access elements than using a switch over different types?

**Comment by tqchen** [comment]
For now, seems switching over different types is the best way. We don't need to check for strange types and it is fine to only support types we know. We can build a few helper functions on this
