### ISSUE TITLE
[IMPROVEMENT] Support pathlib Path

### ISSUE THREAD

**Issue by obust** [dmlc/tvm#2222]
# Feature Request

All functions and methods taking a path as argument should support the `pathlib Path` type.
`pathlib` is the preferred API to handle paths in python 2.7+ (although there is no official PEP8 recommendation). It would be good to at support it and maybe even advertise it in the tutorials to display modern python usage.

The following functions fail when given a `Path` argument:
- `autotvm.callback.log_to_file(filepath)`
- `autotvm.apply_history_best(filepath)`
- `lib.export_library(filepath)`
- more ?

**Comment by tqchen** [comment]
Thanks, @obust for the suggestion. Given that pathlib is not available in 2.7, we might need to be a bit mindful on backward compatibility, other than that, I to tag this as help wanted and anyone is welcomed to bring in this feature

**Comment by obust** [comment]
Oh, you are right, it is not in the 2.7 standard library but is available through PyPI.
I guess there are two ways to go about it:
- cast path arguments to string in case they are `Path`
- use `pathlib2` internally and cast path arguments to `Path` in case they are `string` https://www.scivision.co/python-idiomatic-pathlib-use/

**Comment by tqchen** [comment]
I think cast arguments to string is going to be easier for now

**Comment by tqchen** [comment]
@obust would you like to act on this?

**Comment by obust** [comment]
I don't have authorization to contribute PRs yet. Feel free to pick it up for now :)

**Comment by cchung100m** [comment]
Hi @tqchen 

Do we still need to cast the variable `filepath` to string type in following three class?

- `autotvm.callback.log_to_file(filepath)`
- `autotvm.apply_history_best(filepath)`
- `lib.export_library(filepath)`

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/3968
