### ISSUE TITLE
Tutorials nnvm compile tensorflow model failed

### ISSUE THREAD

**Issue by jon-soc** [dmlc/tvm#2229]
python from_tensorflow.py 

Downloading elephant-299.jpg from https://github.com/dmlc/web-data/raw/master/tensorflow/models/InceptionV1/elephant-299.jpg...
Downloading classify_image_graph_def-with_shapes.pb from https://github.com/dmlc/web-data/raw/master/tensorflow/models/InceptionV1/classify_image_graph_def-with_shapes.pb...
Downloading imagenet_2012_challenge_label_map_proto.pbtxt from https://github.com/dmlc/web-data/raw/master/tensorflow/models/InceptionV1/imagenet_2012_challenge_label_map_proto.pbtxt...
Downloading imagenet_synset_to_human_label_map.txt from https://github.com/dmlc/web-data/raw/master/tensorflow/models/InceptionV1/imagenet_synset_to_human_label_map.txt...

WARNING:tensorflow:From from_tensorflow.py:85: __init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
2018-12-04 16:22:27.337638: W tensorflow/core/framework/op_def_util.cc:355] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
DecodeJpeg: It's a pass through, please handle preprocessing before input
Traceback (most recent call last):
  File "from_tensorflow.py", line 118, in <module>
    sym, params = nnvm.frontend.from_tensorflow(graph_def, layout=layout)
  File "/AI/tvm/nnvm/python/nnvm/frontend/tensorflow.py", line 1410, in from_tensorflow
    sym, params = g.from_tensorflow(graph, layout, shape, outputs)
  File "AI/tvm/nnvm/python/nnvm/frontend/tensorflow.py", line 1182, in from_tensorflow
    shape_dict.update(shape)
TypeError: 'TensorShapeProto' object is not iterable

**Comment by jon-soc** [comment]
TypeError: 'TensorShapeProto' object is not iterable

**Comment by srkreddy1238** [comment]
Can you share python and tensorflow versions ?

**Comment by jon-soc** [comment]
python 2.7
tensorflow 1.12.0

**Comment by jon-soc** [comment]
not,

**Comment by tqchen** [comment]
Thanks for bringing this up, let us move this thread to https://discuss.tvm.ai/

**Comment by srkreddy1238** [comment]
@jon-soc  Can you to check below patch for this issue ?
https://github.com/srkreddy1238/tvm/commit/6e6ac97924c238e367617a0036b71b0befb8a5a4
