### ISSUE TITLE
[RFC] [Relay]A Normal Form Conversion

### ISSUE THREAD

**Issue by MarisaKirisame** [dmlc/tvm#2253]
https://github.com/dmlc/tvm/pull/2251 implement a pass which converts expression with sharing (different occurrence of Expr might be the same ptr) into expression without sharing, by inserting let all over the place.

It is useful because it allows subsequent passes to ignore sharing and only deal with let (which might also reside in the original program anyway).

However, to do so, we must define precisely what is the scope of a node.
It is determined by the Expr that immediately depends on it.
For example in the Graph `a + b`, `a + b` immediate depends on both `a` and `b`.
We will call 'immediately depends on' 'point to' from now on.

Let's start from the degenerate case that there is only one graph a that points to b.
In that case, `GetScope(a, b) = scope(a) if (b is not in curly brace position of a) else new_subscope(scope(a))`

Now the other case.
If nothing points to node b:
b is the outmost scope

If there are multiple pointer pointing to b:
b's scope is the least common ancestor of all GetScope.

**Comment by tqchen** [comment]
How about we define the scope of an expression to be the least common ancestor of all the scopes that directly refers the expression?

**Comment by MarisaKirisame** [comment]
@tqchen we cant, it will lift outside of if else.
Beside special casing for singly scoped object it is what we do.

**Comment by tqchen** [comment]
Can you give an example on why we cannot use the LCA scope as the scope ?

**Comment by MarisaKirisame** [comment]
@tqchen suppose we have
sum(x) = if (x == 0) {0} else {x + sum(x - 1)}
if we try to use the LCA scope, we will lift the 'x + sum(x - 1)' out of the if else, and in the same scope as the parent if, which is incorrect and make the whole thing an infinite loop. It is one reason the definition is complex.

**Comment by tqchen** [comment]
@MarisaKirisame  in your particular case

```
 if (x == 0) {
    0
 } else {
   %1 = x + sum(x - 1)
   %1
}
```
Because %1 is only used in the scope of else, all its usage is only in the scope of else. So the LCA of %1 is the else scope. However, if the code is:

```
%1 = %x -1
 if (%1 == 0) {
    0
 } else {
   %2 = x + sum(%1)
   %1
}
```
Then because ``%1`` get used in both the condition of if, and else scope of if, its LCA is outside the if scope.

**Comment by MarisaKirisame** [comment]
@tqchen this is exactly our algorithm - we cant always take the parent scope, if it is in special location (inside any branch of if/else, inside function definition, inside pattern matching), new scope have to be created.

**Comment by MarisaKirisame** [comment]
> In particular, we also specify the order of evaluation.

@tqchen I am against this. Either the order does not matter, or, if the order matter in a *graph*, something is wrong. This behavior should be implementation-defined, simply because no code should depend on how it is order - something is wrong in the semantic level.

**Comment by tqchen** [comment]
It is true that order does not matter in a graph. We essentially need to impose additional semantics when converting from graph to ANF to make sure such conversion is deterministic. 

Having such deterministic conversion makes developers easy to reason about the consequences of the operation. Post-DFS order is a frequently used lowering rule already for graph code, so I propose that we adopt this semantics in the ToANF pass

**Comment by MarisaKirisame** [comment]
@tqchen i just checked and it is post order. I will update the comment.

**Comment by junrushao1994** [comment]
@tqchen in your example, `%1 = %x -1` should be `%1 = %x`, which is a typo

**Comment by junrushao1994** [comment]
Just curious, have you guys decided to do opt based on anf or cps? What doves the time complexity looks like when it comes to crazy neural nets as deep as ~10k layers?

**Comment by MarisaKirisame** [comment]
@junrushao1994 
0: we decided to used anf instead of cps because the latter is more complex (not just the transformation, but subsequent optimization is harder to write in cps style). also we do not need continuation.
1: the complexity is somewhere around n log n, so it would not be an issue. also other passes will have a higher complexity, so this is not a bottleneck afaik. also even if the nn is 10k layers we might simply represent  it as a compact program.

**Comment by junrushao1994** [comment]
@MarisaKirisame looks good with this complexity as long as you implement lca and dominator analysis efficiently. Sure, people build nn in a modular way, so we need to convince ourselves that our interprocedural analysis works.

**Comment by tqchen** [comment]
close by https://github.com/dmlc/tvm/pull/2251
