### ISSUE TITLE
[Potential bug] `blockIdx.x` mistakenly bound to irrelevant axis

### ISSUE THREAD

**Issue by junrushao1994** [dmlc/tvm#2260]
While working on the recurrent nets, I ran into an issue that `blockIdx.x` is mistakenly bound to some irrelevant axis.

For example, when I bind `ax1.outer` in Line 81 in [this gist](https://gist.github.com/junrushao1994/617da2110fc787f8a626b4bb16d4bc6a#file-before-txt-L81) to `blockIdx.x`, it affected the beginning of the lowered code with apparently wrong boundary checking, Line 27 in [this gist](https://gist.github.com/junrushao1994/f48d57bdaa2205055eda68729b1e49e5#file-after-txt-L27), but what I did is only to bind `blockIdx.x` to Line 81...My code is provided [here](https://github.com/junrushao1994/tvm/blob/675bd115956c80333e5a8bbe3a56359b93ade812/topi/recipe/rnn/rnns.py#L115), in which Line 115 does the binding.

I suspect that rebinding `blockIdx.x` may cause some weird issues. 

@wetliu @tqchen @ZihengJiang Thanks in advance!

**Comment by tqchen** [comment]
@junrushao1994 can you take some time to look into this?
