### ISSUE TITLE
[RFC][Hybrid Script] Syntax sugars for Hybrid Script

### ISSUE THREAD

**Issue by were** [dmlc/tvm#2262]
Hybrid Script is still under a very preliminary stage of development.
Comparing with its counterpart in FaceBook, TorchScript, a lot of syntax sugars are not supported yet.
1. ~Global function call~ *Done*
````Python
@script
def foo(a):
    # balah
    return b

@script
def goo(a):
    b = foo(a)
    return b
````
`foo` can be found in `__global__` dict, so it is not hard to do this I believe.

2. Tensor level operations
````Python
# RFC
# actually, all these tensor operation rules will be hardcoded in the compiler
# i do not want to make it super complicate...
````
3. ~Triple inequity~ *Done*
````Python
if 0 <= a < n:
    # balah
````
4. In-place Operator
````Python
#RFC: Is this one good enough? Users are required to explicitly return the tensor with side effect.
@script
def goo(a):
    for i in range(a.shape[0]):
        a[i] += 1
    return a
````
@kevinthesun Any more suggestions?

**Comment by kevinthesun** [comment]
```python
continue
```
is not supported.

**Comment by were** [comment]
@kevinthesun 
I am not very sure how `continue`, `break` and in-loop `return` can be supported, because so far HalideIR does not support it yet.

@tqchen 
Do you mind if I add `break/continue` and `while` loop in Halide IR?

**Comment by were** [comment]
@tqchen Exactly, I know the current analysis is specific to loops without `break/continue`. That's why I am also reluctant to add it either.

**Comment by kevinthesun** [comment]
Chain of logical expr is not supported.
```python
if a < b and c < d and e < f: 
```

**Comment by were** [comment]
@kevinthesun Can you be more specific that I can replicate it?

**Comment by kevinthesun** [comment]
```python
@hybrid.script
def test(data, bool_var):
    # This won't work
    if data[0] > 1 and data[1] < 2 and data[2] > 3:
        ...
    # This won't work either.
    if data[0] > 1 and bool_var:
        ...
```

**Comment by were** [comment]
@kevinthesun 
Follow up your request on `tvm.container.Array`:
Unfortunately, `tvm.container.Array` cannot be directly accessed by HalideIR.
````
i = tvm.var('i')
a = tvm.convert([1, 2, 3])
expr = a[i] # This is illegal
````

**Comment by kevinthesun** [comment]
@were Would you think supporting array argument requires much more work than expected? If this is case, I can roll back multibox operators to use ir_build for now in https://github.com/dmlc/tvm/pull/2353.

**Comment by tqchen** [comment]
Close this RFC for now as most discussed items has been implemented, please open new threads for new feature discussion
