### ISSUE TITLE
Running docker environment get "sudo: unable to resolve host linuxkit-025000000001" and the notebook can not be accessed from the host browser

### ISSUE THREAD

**Issue by wonderxboy** [dmlc/tvm#2270]
When running docker script (/path/to/tvm/docker/bash.sh tvmai/demo-cpu), shell shows 
> sudo: unable to resolve host linuxkit-025000000001

Then after running jupyter notebook from container, the notebook can not be opened from host browser.

It doesn't seem that the container 8888 port is properly expose to the host. My environment:

- MacOS 10.14 Beta (18A384a)
- Docker version 18.06.1-ce, build e68fc7a

**Comment by tqchen** [comment]
Thanks for bringing it up, please move the general usage discussion to https://discuss.tvm.ai/

In your particular case, it seems due to a docker problem on your side, we are using ```--net=host``` option to expose the port. See https://github.com/dmlc/tvm/blob/master/docker/bash.sh#L20

**Comment by ChrisHunting** [comment]
I run into the same error using MBP. Did you solve the problem? thx

**Comment by tqchen** [comment]
Because this is a restriction on MAC or Windows, likely you can get around it by not using --net=host, and lookup the VM address of the docker host, open browser to connect to that part, alternatively, you can try directly map the port used by the notebook

**Comment by viirya** [comment]
For Mac users, you can modify `docker/bash.sh` to export port of the container to the host. 

```
diff --git a/docker/bash.sh b/docker/bash.sh
index 23b2e209..2ad7fc53 100755
--- a/docker/bash.sh
+++ b/docker/bash.sh
@@ -35,7 +35,7 @@ DOCKER_IMAGE_NAME=("$1")

 if [ "$#" -eq 1 ]; then
     COMMAND="bash"
-    CI_DOCKER_EXTRA_PARAMS=("-it --net=host")
+    CI_DOCKER_EXTRA_PARAMS=("-it -p 8888:8888")
 else
     shift 1
     COMMAND=("$@")
```

**Comment by tqchen** [comment]
@viirya do you mind open a PR to fix this? We can certainly change the setting depends on the os we detect

**Comment by viirya** [comment]
@tqchen Ok. I will do it.
