### ISSUE TITLE
[COMMUNITY] High-res TVM logo

### ISSUE THREAD

**Issue by nhynes** [dmlc/tvm#2282]
Much unlike the lowered computations, the TVM logo isn't vectorized (to my best knowledge). Is there a svg/eps version somewhere? Perhaps it would be helpful to have a "iconography guidelines" page with links to assets and usage requirements.

If there is no existing vector logo, if someone could say what the "tvm" font is, I'm sure one of us with Illustrator could whip something up.

**Comment by tqchen** [comment]
Here it is https://tvm.ai/images/logo/tvm-logo.eps
