### ISSUE TITLE
[RFC] [Hybrid Script] IR Dump

### ISSUE THREAD

**Issue by were** [dmlc/tvm#2288]
Because HalideIR now can be fully mapped to Hybrid Script and vice versa, I want to support IR dump to Hybrid Script so that users can play with IR body directly.

Which one do you guys prefer?
1. `mode=tvm.build(sch, args, target='hybrid'); mode.save('a.py')`
2. `tvm.hybrid.emit(stmt, file_name)`

I personally like the 2nd one better. I do not want touch too much build module thing. I want to make it as standalone as possible.

@tqchen @eqy @yzhliu @kevinthesun @yidawang

**Comment by xqdan** [comment]
What's purpose of IR dump for, debugging or some transformation?

**Comment by were** [comment]
@xqdan You can dump HalideIR to this script format and play with the IR directly.
Isn't it useful, when there are some bugs (and you just need a quick fix) or some schedule not supported yet?

**Comment by junrushao1994** [comment]
Slightly off the topic, I would say it could be better if we explicitly claim which syntactic sugar of Python is supported, which is not. You might be interested in writing it in accordance with Python's official AST document, [Green Tree Snake](https://greentreesnakes.readthedocs.io/en).

**Comment by kevinthesun** [comment]
Personally I prefer the second method, to keep this under hybrid script. @junrushao1994 It's helpful to have such a doc for developer to check whether their code syntax is supported. We can start with adding something we don't think will support in the long term, such as break/continue.

**Comment by xqdan** [comment]
@were yes, looks cool, can we do this for each pass?

**Comment by junrushao1994** [comment]
@kevinthesun complicated jumps like break/continue is not possible in Halide, because it break all analysis conducted. Hence, it is not quite meaningful to add it to the hybrid script. Do you have specific use cases for break/continue?

**Comment by kevinthesun** [comment]
@junrushao1994 I don't think we need to support those.

**Comment by were** [comment]
@xqdan I do not want to aggressively modify the codegen backend.
I believe dumping each pass requires this.
I just want to dump the normalized schedule, the highest level.

**Comment by xqdan** [comment]
@were I see. 2nd is better for me.

**Comment by xqdan** [comment]
@kevinthesun totally agree with @were and @junrushao1994, to support continue and break, the whole TVM stack would need lots of stuff in traditional compilers, which will make things complicated. if any operators don't fit into abstraction of TVM, maybe it's better to support it with low level languages, such as CUDA c.
