### ISSUE TITLE
I cannot create shared object.

### ISSUE THREAD

**Issue by were** [dmlc/tvm#2300]
When I am working on #2287 , I got a CPU check failure.
I want to replicate the problem locally so that I can fix it.
```
python3 tvm/tests/python/unittest/test_module_load.py
```
What I got is:
```
Traceback (most recent call last):
  File "test_module_load.py", line 198, in <module>
    test_combine_module_llvm()
  File "test_module_load.py", line 192, in test_combine_module_llvm
    check_system_lib()
  File "test_module_load.py", line 179, in check_system_lib
    cc.create_shared(path_dso, [path1, path2])
  File "~/tvm/python/tvm/contrib/cc.py", line 33, in create_shared
    _linux_shared(output, objects, options, cc)
  File "~/tvm/python/tvm/contrib/cc.py", line 59, in _linux_shared
    raise RuntimeError(msg)
RuntimeError: Compilation error:
/usr/bin/ld: /tmp/tmpcOcGRh/myadd1.o: relocation R_X86_64_32S against `.rodata.cst4' can not be used when making a shared object; recompile with -fPIC
/tmp/tmpcOcGRh/myadd1.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```
and I followed this stackoverflow to see if `.o`s are compiled with `-fPIC`.
https://stackoverflow.com/questions/19768267/relocation-r-x86-64-32s-against-linking-error
which shows that `.o`s are compiled properly with `-fPIC`.

**Comment by merrymercy** [comment]
It is probably due to the llvm/gcc compatibility and not related to your change.
Solution and discussion:
https://discuss.tvm.ai/t/runtime-llvm-cc-create-shared-error-while-run-tune-simple-template/1037/5
