### ISSUE TITLE
[RUST][FRONTEND] macro for constructing the builder

### ISSUE THREAD

**Issue by ehsanmok** [dmlc/tvm#2305]
The proposed `tvm_call!` doesn't not accept `set_output`. Expand the macro with perhaps some related syntax extension. TODO [#2292](https://github.com/dmlc/tvm/pull/2292)

**Comment by tqchen** [comment]
to avoid creating too many issues, please merge most of them into a single rust FRONTEND working item issue and only open new issue when we think we can act in it soon(say can be closed in two weeks)

**Comment by ehsanmok** [comment]
Noted! Given the upcoming holidays, might be qualified in the timeline.

**Comment by ehsanmok** [comment]
@tqchen @nhynes I decided to keep the ball rolling before the holidays. Regarding the macro, currently `tvm_call!` is good enough. My suggestion is that we can generalize it to something like

```
tvm_call!(func: [func_identifier], arg: [stack of args], out: [at most one output])
```
and to ensure the output to have at most one value, we can use `!#[feature(macro_at_most_one_rep)]`(https://doc.rust-lang.org/unstable-book/language-features/macro-at-most-once-rep.html#macro_at_most_once_rep) through `?`, which we won't need in 2018 edition actually.

In my opinion this is rather an icing-on-the-cake macro. What do you think?

**Comment by nhynes** [comment]
what you're describing seems almost exactly what [`runtime::{PackedFunc, call_packed}`](https://github.com/dmlc/tvm/blob/master/rust/src/runtime/packed_func.rs#L11-L26) do. Is there something that `tvm_call` must do that `call_packed` does not?

**Comment by nhynes** [comment]
Actually, on second reading. I'm really unconvinced that all of this `Builder` stuff is necessary since you can always just cast the TVM function to an actual `Box<Fn>` and call it directly.

**Comment by ehsanmok** [comment]
@nhynes Honestly, I don't see any added complexity.

1. Builder pattern in Rust is more common in Rust than in any other languages. I like to think that making the components clear and out of magic is the proper way in general and in particular for our case. For example, during dev, I wanted to investigate the args passed in the builder for debugging purposes. Debugging macros in Rust is not graceful even with [log_syntax or trace_macros](https://github.com/rust-lang/rust/issues/29598). 

2. I developed the frontend with compatibility of other runtime frontends (such as java) to make things more coherent than runtime when added recently. Builder was also used there.

3. Builder also covers your `syslib.get_function("default_function")` when interacting with already built modules as well as invoking the functions.

4. `tvm_call` is pretty similar to `call_packed` and I'm for the name change as I suggested in the PR comments before, but right now, `tvm_call` doesn't use `set_output` as in

```
function::Builder::from(&mut fadd)
            .arg(&arr)
            .arg(&arr)
            .set_output(&mut ret)
            .invoke()
            .unwrap();
```
which I thought this issue is about and making it general can make things more clearer by something like

```
tvm_call!(fadd; args: &arr, &arr; out: &mut ret)?;
```

5. I think packed function  `fn(&[TVMArgValue]) -> Result<TVMRetValue>` is more Rusty than `Box<Fn(&[TVMArgValue]) -> TVMRetValue + Send + Sync>`. In fact, [fn function ptr is Fn + Send + Sync + Pointer etc.](https://doc.rust-lang.org/std/primitive.fn.html)

Finally, frontend needs to be able to register global functions and the whole mechanism fits things together in `register_global_func!`

**Comment by nhynes** [comment]
Okay, then let's modify `PackedFunc` to `Result<TvmRetValue>`; I didn't have need for it originally so I didn't add it. Having two ways to construct and call `PackedFunc` isn't bad so how about we do both macro _and_ builder but simplify the interior of builder to use `PackedFunc` instead of manual.

**Comment by ehsanmok** [comment]
Sure! since this issue is addressing your first proposition, shall we move on and make a succinct plan after frontend is merged?

**Comment by nhynes** [comment]
Sure Builder can be improved once we merge everything in. We're going to need to update `TVMRetValue` now, though, since that's going to become a common dependency pre-merge.
