### ISSUE TITLE
[RUST] RFC and 0.5 Release Plans

### ISSUE THREAD

**Issue by ehsanmok** [dmlc/tvm#2306]
The following are the current plans for [TVM Rust](https://github.com/dmlc/tvm/issues/1601) including both "runtime" and "frontend" as part of roadmap v0.5.

- [ ] Create `common` crate for runtime and frontend
- [ ] [Merge frontend](https://github.com/dmlc/tvm/pull/2292)
- [ ] Comply with Rust [2018-edition](https://rust-lang-nursery.github.io/edition-guide/rust-2018/index.html).
- [ ] Add function builder to runtime and make runtime `PackedFunc` compatible with frontend
- [ ] Make `call_packed!` macro more general and compatible across both runtime and frontend sides as [discussed](https://github.com/dmlc/tvm/issues/2305).

**Comment by ehsanmok** [comment]
Here're my thoughts about a `common` crate:

The main difference (besides some conversions and using a fat point) between frontend and runtime `TVMArgValue` and `TVMRetValue` is how they're wrapping/using `TVMValue`. The runtime `TVMValue`  is raw, however, frontend needs `Debug + Display` and some idiomatic conversions. Therefore, `common`'s `TVMValue` has to be wrapped *at least*. 

Because bindgen doesn't work for runtime, so either we should 
* include the generated raw c api in `common` entirely (same as runtime) 
or 
* include what needed such as raw `TVMValue` and `TVMTypeCode` and then, wrap and impl required conversions for *both* runtime and frontend (because of Orphan rule so that we won't need more wrapper boilerplates in either crates).

@nhynes please let me know what you think.

**Comment by nhynes** [comment]
an interesting point. what happens if the `common` crate has the headers behind one of two mutually exclusive feature flags: `runtime` and `frontend`? The former would pull in the definitions from `c_runtime_api.rs` and the latter would expose `tvm-sys`.

> removing the debugging 
I'm not sure I follow. Is it not as easy as `#[derive(Debug)]` or even `impl Debug for Struct`

**Comment by ehsanmok** [comment]
@nhynes the major issue I'm dealing with now is to be able to clone `TVMRetValue`. 

First of all, I think, it is incorrect to [cast handle types as `u64`](https://github.com/dmlc/tvm/blob/master/rust/src/runtime/packed_func.rs#L189) as `from_tvm_value` and `into_tvm_value` won't be inverse of each other, so I had to modify `from_tvm_value` to box the handles like `v_handle: Box::into_raw(self.box_value) as *mut c_void` then I could impl `TryFrom` with downcast for my `Module` for example, correctly. (Previously, it was segfault).

However now, imlp `Clone` for `TVMRetValue` for the *handle cases* is problematic for two main reasons that [all the `Box` methods](https://doc.rust-lang.org/std/boxed/struct.Box.html#methods) wants ownership and `Any` is not clonable.

So my conclusion up to now is that the current `TVMRetValue` representation is insufficient and I'm thinking of a better representation or some safe workaround.
