### ISSUE TITLE
[ARITH] Enhance CanonicalSimplify((241+48x)/16)

### ISSUE THREAD

**Issue by derisavi** [dmlc/tvm#2308]
```python
import tvm
x = tvm.var("x")
print(tvm.ir_pass.CanonicalSimplify((240+48*x)/ 16)
print(tvm.ir_pass.CanonicalSimplify((241+48*x)/ 16)
```
produces
```
(15 + (x*3))
((241 + (x*48))/16)
```
where expected result is:
```
(15 + (x*3))
(15 + (x*3))
```

**Comment by sgrechanik-h** [comment]
Since tvm uses truncated division (in contrast to Halide which uses Euclidean division), this is wrong for some negative values, e.g. for x = -10, `(241 + 48*(-10))/16 = (-239)/16 = -14` and `15 + 3*(-10) = -15`.

**Comment by derisavi** [comment]
> Since tvm uses truncated division (in contrast to Halide which uses Euclidean division), this is wrong for some negative values, e.g. for x = -10, `(241 + 48*(-10))/16 = (-239)/16 = -14` and `15 + 3*(-10) = -15`.

Thanks for bringing up this important distinction. Does this mean that the existing rules (before my patch) also needs fixing because 
```python
import tvm
x = tvm.var('x')
print(tvm.ir_pass.CanonicalSimplify((10*x+5)/10))
```
produces `x` (without my patch) which is wrong if x is negative. We get the incorrect result above if we replace 5 by any positive number less than 10.

**Comment by derisavi** [comment]
> Since tvm uses truncated division (in contrast to Halide which uses Euclidean division), this is wrong for some negative values, e.g. for x = -10, `(241 + 48*(-10))/16 = (-239)/16 = -14` and `15 + 3*(-10) = -15`.

What is the definition of TVM's mod operator? is it `a mod b = a - (a/b)*b` (where / is truncated division)?

**Comment by sgrechanik-h** [comment]
Oh, I didn't know that CanonicalSimplify sometimes perform incorrect transformations too. Yes, I think it needs to be fixed.

**Comment by derisavi** [comment]
Given @sgrechanik-h's point, the testcase at the top is not a proper testcase and it has to be replaced by the following:
```python
import tvm
x = tvm.var("x")
print(tvm.ir_pass.CanonicalSimplify((240+48*x)/ 16) # produces wrong result given that we don't know anything about x
print(tvm.ir_pass.CanonicalSimplify((241+48*x)/ 16) 
print(tvm.ir_pass.CanonicalSimplify((240+48*x)/ 16, {x: tvm.Range(-5,10)})
print(tvm.ir_pass.CanonicalSimplify((241+48*x)/ 16, {x: tvm.Range(-5,10)})
```
produces
```
(15 + (x*3))
((241 + (x*48))/16)
(15 + (x*3))
((241 + (x*48))/16)
```
where expected result is:
```
((240 + (x*48))/16)
((241 + (x*48))/16)
(15 + (x*3))
(15 + (x*3))
```

**Comment by sgrechanik-h** [comment]
> print(tvm.ir_pass.CanonicalSimplify((240+48*x)/ 16) # produces wrong result given that we don't know anything about x

This one, i.e. `(240+48*x)/ 16  ->  15 + (x*3)` seems to be correct for all `x` since both 240 and 48 are divisible by 16.

**Comment by derisavi** [comment]
> > print(tvm.ir_pass.CanonicalSimplify((240+48*x)/ 16) # produces wrong result given that we don't know anything about x
> 
> This one, i.e. `(240+48*x)/ 16 -> 15 + (x*3)` seems to be correct for all `x` since both 240 and 48 are divisible by 16.
You're right. I will fix/edit the example above. The  patch (https://github.com/dmlc/tvm/pull/2310) does the right thing.
