### ISSUE TITLE
[DISCUSS][ARM] Arm data prefetch instruction

### ISSUE THREAD

**Issue by tianylijun** [dmlc/tvm#2343]
Platform: ARM64

Arm data prefetch instruction, e.g. prfm [arm64], pld[arm32]

It seems TVM not support this feature, as I can not find these instructions in the .o generate by TVM. (I disassemble mobilnet.o to get the assemble file ). Is that right? or is there any compile cfg can do this?

**Comment by tqchen** [comment]
cc @were @ajtulloch  there is already prefetch support as schedule primitive, however, we did not find it bring performance benefit yet. Maybe there are some gaps in the generated code

**Comment by tqchen** [comment]
Given that this is a discussion and we do not yet have actionable items, this issue is closed for now, let us move further discussion to https://discuss.tvm.ai/
