### ISSUE TITLE
[TOPI] [HYBRID] Migrate TOPI ir_builder to Hybrid Script

### ISSUE THREAD

**Issue by were** [dmlc/tvm#2348]
Currently, many operators in TOPI are written in IRBuilder.
To make these operators easy to maintain, migrating them to Hybrid Script is proposed.
Here are the usages:
1. x86/arm: I think just keep it for now, because LLVM intrin call is not supported yet. Also, it is not easy to do sw emu.
2. sparse: I think these can be migrated. @liangfu Can you take a look?
3. vision: @kevinthesun Let me support const tuples, i.e. array container, so that you can make all these done.
4. cuda: @kevinthesun Are you also in charge of cuda ones or only CPU ones?

**Comment by were** [comment]
@tqchen I apologize that I did not push the migration which made that issue stale.
Can you close the old one and we discuss here?

**Comment by liangfu** [comment]
okay, I will look into this.

**Comment by kevinthesun** [comment]
@Laurawly do you have circle to deal with cuda vision ops? If not, I can take over these.

**Comment by tqchen** [comment]
As far as I see the migration to ir builder is ongoing. I will close this thread due to inactive status. @kevinthesun @Laurawly @liangfu please feel free to open new threads
