### ISSUE TITLE
[RFC][Runtime] Graph signature metadata

### ISSUE THREAD

**Issue by srkreddy1238** [dmlc/tvm#2357]
In the context of integrating TVM runtime with model hosting services

Model serving solution isolate model specific information and expose unified interface to users (example via REST API). Integration with such solutions need model metadata to be exposed to users (like inputs/outputs shape, name and dtype ...etc.).

ref. https://github.com/dmlc/tvm/pull/1659 solves to an extent of querying information of outputs.
We still need some way of getting inputs information.

Some challenges in current runtime implementation
- TVM runtime doesn't differentiates params from inputs and allows to setting params by set_input API.
- There is no API to get node name from index.

### Option:
- After load_params we could maintain graph_inputs list (inputs - params) and support ```get_input``` and ```num_inputs```.
- Additional API to query name_hint to get the node name. ```name_hint(input or output, index)```

**Comment by srkreddy1238** [comment]
@tqchen @yzhliu @grwlf welcome to comment.

**Comment by tqchen** [comment]
There are certainly tradeoffs we can make here. Supporting more meta-data query will make the module more informative, but never-the-less creates additional APIs that need to maintain and part of the code that need to be included in the runtime(which somewhat goes against minimalist principle).

This additional information can also be provided as a wrapper on the current API, for example, storing additional meta-data in json, in the case of REST. For other applications, we already have a convention on name/index of input, as well as the shape info, so such may not be necessary.

**Comment by srkreddy1238** [comment]
storing the input info in graph json should be ok.

**Comment by tqchen** [comment]
close this for now as it is temporary, not actionable. If we have an additional info field in the json, we can sent an update to allow parser to skip the field correctly while let the high level framework to get the info
