### ISSUE TITLE
[ONNX] How do I know if need broadcast in elemwise op

### ISSUE THREAD

**Issue by BobLiu20** [dmlc/tvm#2359]
Because onnx had been remove broadcast attribute in Mul op from version 6. See [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Mul). So, We can't checkout broadcast attr anymore.  Code below:
https://github.com/dmlc/tvm/blob/b11884858fa052503d1e2e8318380111910faa2e/nnvm/python/nnvm/frontend/onnx.py#L49-L51   

My question:   
Does any idea to check if we should use elemwise_xx or broadcast_xx in tvm ?

**Comment by BobLiu20** [comment]
I have a bad idea: remove condition and let all onnx Mul op convert to tvm broadcast_mul. It will be working well. But I don't know how it will effect performance. Any idea?

**Comment by tqchen** [comment]
We can always use the broadcast version of multiplication. The NNVMv2 relay support broadcast by default
