### ISSUE TITLE
Why set LRN Op Pattern to OPAQUE 

### ISSUE THREAD

**Issue by heguixiang** [dmlc/tvm#2378]
Thanks for your TVM project. 

    I have benefited a lot after reading your excellent project.  But I have a puzzle, why you setting LRN operator pattern as OPAQUE, just like "reg.register_pattern("lrn", OpPattern.OPAQUE)", why it can not merge with ops even with elemwise pattern attribute, I am looking forward your reply, thank you very much.

**Comment by tqchen** [comment]
Please open a new thread in https://discuss.tvm.ai/
