### ISSUE TITLE
CI numerical issue

### ISSUE THREAD

**Issue by liwchang** [dmlc/tvm#2388]
CI seems too numerically sensitive.
Also, tvm using random numbers in unit tests made it even worse.
That caused too many false alarms during CI.

Maybe fixing seed or inputs can resolve this issue.

-L

**Comment by tqchen** [comment]
So far there is not too many flaky cases, if there are, we should fix the test-case to relax the bound, and nail down the flay testcases

**Comment by liwchang** [comment]
Thanks.

I encountered one in logSoftMax today.

Let's keep this thread for a few while. 
I think others might wanna report it.

**Comment by tqchen** [comment]
As per current guideline, https://github.com/dmlc/tvm/blob/master/.github/ISSUE_TEMPLATE.md we try to close issues aggressively and make sure each issue are actionable.  This approach avoids a huge pile of issues that nobody gets attend to. So I would recommend close this one, open a thread in https://discuss.tvm.ai/  and open separate actionable items as issues, for example:

- https://github.com/dmlc/tvm/issues/2109
- https://github.com/dmlc/tvm/issues/1784

**Comment by tqchen** [comment]
The random number is useful for test-cases and I believe in most cases, as long as we make sure the ranges are right(correct interval of the distribution for certain functions) or have the right tol value, most cases are not flaky.  Using random number can sometimes help us find problems.

**Comment by tqchen** [comment]
centralized thread created per your suggestion https://discuss.tvm.ai/t/flaky-test-cases-thread/1437
