### ISSUE TITLE
Is autoTVM an option?

### ISSUE THREAD

**Issue by LJenny** [dmlc/tvm#2390]
Hi, I would like to ask a simple question.
In the tutorial, there is optimize / opt_gemm.py.
In this sample, I can not find an automated schedule optimizer (autoTVM).
Is not the sample optimized for the schedule?
For example, do I need to add an autotvm module to optimize this sample?
Thank you in advance.

**Comment by tqchen** [comment]
Thanks for raising the question, please open a new thread in https://discuss.tvm.ai/
