### ISSUE TITLE
[TEST][ONNX] ONNX test flaky (Div in test_binary_ops) 

### ISSUE THREAD

**Issue by yangchen-MS** [dmlc/tvm#2396]
With commit be07fac, the following test input produced failure for Div op:

    x = np.asarray([[[[ 0.71703678, 0.56416506, 0.08745602],
                      [ 0.87705201, 0.50444186, 0.70680761],
                      [ 0.20275222, 0.00688661, 0.88937372]],
                     [[ 0.70284462, 0.31927493, 0.33494693],
                      [ 0.77690017, 0.7294656,  0.33145803],
                      [ 0.09090571, 0.81665891, 0.83966464]]]], dtype='float32')

    y = np.asarray([[[[ 0.03319569, 0.65654027, 0.84947187],
                      [ 0.87152171, 0.00495975, 0.91269046],
                      [ 0.27567229, 0.74589926, 0.02653436]],
                     [[ 0.49205354, 0.6990847,  0.32115516],
                      [ 0.39994141, 0.36066473, 0.03974146],
                      [ 0.4188557,  0.39287621, 0.68752563]]]], dtype='float32')

On my machine, I got:

    out_np:
    [[[[  2.16002979e+01   8.59300017e-01   1.02953404e-01]
       [  1.00634551e+00   1.01707115e+02   7.74422050e-01]
       [  7.35482752e-01   9.23262723e-03   3.35178146e+01]]

      [[  1.42839050e+00   4.56704229e-01   1.04294431e+00]
       [  1.94253492e+00   2.02255869e+00   8.34035873e+00]
       [  2.17033491e-01   2.07866716e+00   1.22128487e+00]]]]
    tvm_out:
    [[[[  2.16002979e+01   8.59299958e-01   1.02953397e-01]
       [  1.00634563e+00   1.01707123e+02   7.74422050e-01]
       [  7.35482752e-01   9.23262723e-03   3.35178108e+01]]

      [[  1.42839050e+00   4.56704229e-01   1.04294419e+00]
       [  1.94253492e+00   2.02255869e+00   8.34035873e+00]
       [  2.17033491e-01   2.07866716e+00   1.22128487e+00]]]]

**Comment by yangchen-MS** [comment]
BTW, the failure happened when testing nnvm/tests/python/frontend/onnx for CPU target. My TVM built with LLVM 6.0.1.

**Comment by tqchen** [comment]
move to https://github.com/dmlc/tvm/issues/2398
