### ISSUE TITLE
[TEST][ONNX] ONNX test flaky sqrt, div, logsoftmax

### ISSUE THREAD

**Issue by yangchen-MS** [dmlc/tvm#2397]
With commit be07fac, the following test input produced failure for Sqrt op:

    indata = np.asarray([[0.69074488, 0.29226714,-0.56205946, 0.01265035]], dtype='float32')

With the input above, I got:

    outdata:
    [[-0.90204036 -1.30051804 -2.15484476 -1.58013487]]
    tvm_out:
    [[-0.90204048 -1.30051827 -2.15484476 -1.58013499]]

**Comment by yangchen-MS** [comment]
I should have been more careful when reporting the issue. The failure happened when running nnvm/tests/python/frontend/onnx for CPU target. My TVM built with LLVM 6.0.1. To reproduce the failure (hopefully you could reproduce it because it might be arch-related), you can replace:

    x = np.random.uniform(size=in_shape).astype(dtype)

with

        x = np.asarray([[[[ 0.94189703, 0.24268626, 0.25545985],
                      [ 0.95224684, 0.57228124, 0.63862652],
                      [ 0.93324018, 0.87410188, 0.62078589]],
                     [[ 0.21460213, 0.86773658, 0.62907255],
                      [ 0.18104482, 0.82294154, 0.26680526],
                      [ 0.411677,   0.03111285, 0.11248256]]]], dtype='float32')

in function test_single_ops in nnvm/tests/python/frontend/onnx/test_forward.py, and run a similar command like below:

    python -m nose -v ../nnvm/tests/python/frontend/onnx/test_forward.py

**Comment by yangchen-MS** [comment]
I think we may want to adjust '```rtol``` for these failing tests. The reason is that different FP-related algorithms (e.g. vectorization algorithm used by LLVM, or CUDA library) could produce results with different accuracy. For example, we might want to check only 3 or 4 most significant digits after dot.

**Comment by tqchen** [comment]
@yangchen-MS can you send in a PR to adjust the rtols and atol(of the recently reported flaky case). We can use tvm.testing.assert_allclose which sets the atol correctly. 

In some cases, we might need to fix the way random numbers are generated(e.g. Div, (x/y) we will need to make sure y is not too small)

**Comment by yangchen-MS** [comment]
Yes, I will do that. Thanks.
