### ISSUE TITLE
[TEST][ONNX] ONNX test flaky (test_LogSoftmax)

### ISSUE THREAD

**Issue by yangchen-MS** [dmlc/tvm#2398]
With commit be07fac, the following test input produced failure to test_LogSoftmax:

    indata = np.asarray([[0.69074488, 0.29226714,-0.56205946, 0.01265035]], dtype='float32')

With this input data, I got:

    outdata:
    [[-0.90204036 -1.30051804 -2.15484476 -1.58013487]]
    tvm_out:
    [[-0.90204048 -1.30051827 -2.15484476 -1.58013499]]

**Comment by yangchen-MS** [comment]
To reproduce the issue, you may try the following patch:

    diff --git a/nnvm/tests/python/frontend/onnx/test_forward.py b/nnvm/tests/python/frontend/onnx/test_forward.py
    index 82b5d319..d20b0521 100644
    --- a/nnvm/tests/python/frontend/onnx/test_forward.py
    +++ b/nnvm/tests/python/frontend/onnx/test_forward.py
    @@ -273,7 +273,7 @@ def test_slice():
         _test_slice_iteration(x, x[:, 0:-1], (0), (-1), (1))

     def _test_onnx_op_elementwise(inshape, outfunc, npargs, dtype, opname, kwargs):
    -    indata = np.random.uniform(-1, 1, size=inshape).astype(dtype)
    +    indata = np.asarray([[0.69074488, 0.29226714,-0.56205946, 0.01265035]], dtype='float32')
         outdata = outfunc(indata, **npargs)

         y = helper.make_node(opname, ['in'], ['out'], **kwargs)

And run a command similar to this one:

    python -m nose -v ../nnvm/tests/python/frontend/onnx/test_forward.py

Note that make sure to setup PYTHONPATH correctly before running the command.

**Comment by tqchen** [comment]
move to https://github.com/dmlc/tvm/issues/2398
