### ISSUE TITLE
[RFC][DISCUSS] TVM Apache Incubation

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#2401]
Dear community, happy new year! As the TVM community grows larger, we have heard voices on the possibility of joining a software foundation. As per our community tradition, I open this thread for discussing the possible futures of the community. In particular, we would like to discuss the possibility to propose TVM to Apache Incubator.

Please share your thoughts, concerns, ideas.

##  Why 

The TVM currently runs like an Apache project already, with merit-based governance model and a strong emphasis of community. So it is natural to do such a transition. Markus, our potential Apache mentor kindly gave a talk during TVM conference. You can find his slides [here](https://sampl.cs.washington.edu/tvmconf/slides/Markus-Weimer-TVM-Apache.pdf) 

##  Why Not

Apache does not magically make things happen. I have seen good and bad things happen in Apache communities. Sometimes it is simply due to the conflict of interest happened in bad ways, and not necessarily has a direct connection to incubation itself.  As a diverse community, we believe we have already experienced ways to work together in a positive and collaborative way, so I hope such risk is minimized.
 
Another potential risk could be changing ways of development. Historically, Apache projects favor a single way of development:
- Use gitbox(which get mirrored to github) 
- Use JIRA instead of github issues. 
- Mail-list centric culture
   - use dev@ for development
   - many projects uses user@ mail-list for general support discussion.

These restrictions are being lifted recently and Apache encourages each project to follow their way of development(e.g. use github issues). One of the main philosophy behind these choices is to make sure that the development is not dominated by a single party. For example, face to face or one to one hangout call makes it hard for other parties to participate. So we need to ask developers to summarize their discussions and provide RFC to the community via public archive(e.g. github issues). By making all the development and discussion history public, we enable community members who maybe not have time to participate face to face meetings to join the development smoothly as well. Our community adopts the same philosophy(develop in a publically archivable place), with slight variants:

- We use github primary for development.
- We use github issues for design discussions and RFCs
- We use a discourse forum https://discuss.tvm.ai for general support discussions

My understanding is that the Apache is flexible enough as long as we follow the general principle. Likely we will need to subscribe github issues to dev@, but can keep the discourse forum and use github for development

## How it could affect us

We shall continue to grow the community and make TVM awesome for everyone. Because the TVM already follows the Apache-style governance model, the transition should be smooth. There will be a disruptive period when we transition the codebase

The following things will happen, based on my previous experience with Apache projects,
 if we decide to incubate

 - We will send out a proposal to Apache incubator to see if they would like to sponsor the project
 - We will migrate the project repo to apache/incubator-tvm
 - Apache generally encourages each community to use their ways of development, as long as we follow the apache-way, we can keep our current style of development
   - Likely we can keep the current way of development, with GitHub and RFCs
   - A dev@ mail-list will be created, which mirrors GitHub issues, and RFCs can also be discussed there. dev@ mail-list is important in Apache culture, many projects do design discussion there. So far, we use github issues like the similar way people use dev@, so mirroring GH issues to dev@ would likely give us the most smooth transition.

The current committers will be invited as to Apache committers. The current PMC already follows the Apache style of voting in committers, and we only need to migrate the PMC mail-list.  While reviewer is not an official role in Apache projects, we can still propose to maintaining our reviewer list and use this mechanism to help us find potential committers.

## Share your thoughts
As per community tradition, all major proposals will be discussed as RFC by members of the community.  We will open this thread for a week for discussions on whether should we join the process. I have invited our potential mentors(@markusweimer, @sscdotopen, @bgchun) to join the discussion as well. 

I will send out the incubating proposal for public RFC as well if we agree that that is a good idea. cc @dmlc/tvm-comitter 

Please share your thoughts, examples:

- Let us do apache incubation
- I  do not care
- No-op, the current way is OK, let us just keep the project as it is
- I have a question on ...

**Comment by ZihengJiang** [comment]
+1

**Comment by were** [comment]
+0

**Comment by masahi** [comment]
+1

**Comment by icemelon9** [comment]
+1

**Comment by tqchen** [comment]
Thanks for everyone who responded so far, I have updated the thread to also discuss the cons. If you have some specific questions, or thoughts, please feel free to share them

**Comment by srkreddy1238** [comment]
+1

**Comment by ZihengJiang** [comment]
The transition sounds good to me. One thing is, will Apache require us to transition the website/CI hosting?

**Comment by tqchen** [comment]
re. CI/website, as far as I understand, the main website(tvm.ai) will need to be migrated to tvm.incubator.apache.org.  Likely we can keep our own CIs due to the special requirement to setup the pipelines and https://discuss.tvm.ai/, but we can also confirm this in our proposal. 

Regardless of where things goes, the general principle is that the resources are owned and shared by the community

**Comment by Ravenwater** [comment]
what are the success statistics for Apache projects that have University-paid versus Company-paid principals? I am worried that a project with this level of complexity needs a continuously engaged engineering team of significant cost and skill level to keep the core healthy.

**Comment by tqchen** [comment]
I think it does not matter in terms of contributors from university v.s. company,  it is dangerous to impose bias toward either one. Note that a contributors' background does not necessarily imply their skill level.  I have personally seen proliferate open source contributors from both backgrounds.

The merit-based principle means that whoever made sustained high-quality contributions will get added to the committer and have more weight in the decision. 

The quality of the codebase really boils down to whether or not can we have a healthy community that upholds a high standard and works together toward that goal. I think we are working hard toward that goal :)

**Comment by nhynes** [comment]
> a project with this level of complexity needs a continuously engaged engineering team

I think that's already what we have! Even without incubation and a community-based dev team, TVM is already a significant way towards not only fast ML on the usual devices, but also heretofore unexplored ones with VTA. Indeed, TVM's development closely parallels that of MXNet, which continues to thrive, and actually drops some of the procedural/tooling baggage that can hinder contribution.

Furthermore, although there are certainly success stories of paid core devs (e.g., Neovim), keeping the project maintained exclusively by the community aligns its goals with both the ASF and those same people who use it.

Of course, one unique aspect of TVM is that its stakeholders come from both industry _and_ academia. Very often, too, contributors represent both interests (e.g., those at industry research labs). (And, personally, I'd be _more_ reassured by an army of capable grad students spending their 25 hour days hacking on TVM :). Overall, I think that there's no worry that the TVM codebase would grow anything but more cohesive.

**Comment by sscdotopen** [comment]
Sebastian here from the ASF. I would like to note that many successful 
Apache projects such as Flink or Spark managed to attract a mix of 
(paid) academic and industry contributors.

A goal of the incubation process in Apache is to broaden the set of 
stakeholders in a project so that it does not exclusively rely on the 
benevolence of a single contributing entity.

Best,
Sebastian

**Comment by tmoreau89** [comment]
I'm all for this proposed transition. And regarding academic-based vs. industry-based engineering team, I think we have the right mix to keep the project healthy and growing!

**Comment by xqdan** [comment]
Let us do apache incubation

**Comment by jroesch** [comment]
I am in favor as well. My only concerns are about development workflow/methodology, i.e staying on Github, and avoiding JIRA.

**Comment by markusweimer** [comment]
Markus here, like @sscdotopen from the ASF. Allow me to address a couple of the questions raised so far. I realize that some of what I say is repetitive with the comments made by others, but maybe the different formulation from a different perspective is useful.

@jroesch said:
> My only concerns are about development workflow/methodology, i.e staying on Github, and avoiding JIRA.

The vast majority of the workflow of TVM seems unaffected by a move to the ASF. The biggest challenge usually is to move to a everything-documented workflow where ideas are discussed and decisions are made in a public, archived form. TVM already does this on GitHub and its mailing list.

There is a minor adjustment I see coming, though: Discussions will move to an ASF mailing list, and discussions on GitHub will have to be mirrored there. This "everything (also) happens on the ASF list" requirement allows the foundation to provide its various legal and other shields for projects.

@Ravenwater said:
> what are the success statistics for Apache projects that have University-paid versus Company-paid principals? I am worried that a project with this level of complexity needs a continuously engaged engineering team of significant cost and skill level to keep the core healthy.

Not sure whether such stats are kept :-(. However, a couple of high-profile projects were started at universities, and the move to the ASF was at least not a hindrance to their success. In fact, I believe that the move to the ASF massively contributed to their success, as contributions from industry became substantially easier, and less lawyer-heavy. Apache Spark and Apache Flink are good examples in this category.

But your question raises another important concern the ASF actually cares a great deal about: Is the project dependent upon the benevolence of a single entity or not? For a project to be stable in the long term, it has to be as diverse in its support as possible. That is why one major goal during incubation and on the way to graduation to become a top level project is to broaden this support. And having a mixture of members from both industry and academia is beneficial for the stability here.

@ZihengJiang said:
> One thing is, will Apache require us to transition the website/CI hosting?

Yes and no :). The ASF will own the trademarks to the project name, e.g. "Apache TVM". As such, the domain registration(s) of the project, the twitter handle, … and other uses of this trademark need to be under ASF control. This is usually done by sharing custody of those within the PMC.

The ASF does provide CI, but I found it often inferior to what other companies offer to OSS projects for free (Shameless plug: Azure DevOps Pipelines :-) ). There is no requirement to use the ASF infrastructure. Just like with domain names and hosting, the important thing is that access and ownership lies with the project. For instance, a private build server at UW being a critical part of the workflow would be problematic (but not a blocker, Spark has done this in the past).

**Comment by tqchen** [comment]
To follow up a bit on comments on development workflow. One thing that Apache is quite strict about is the dev@ mail-list. There is a that everything (also) happens on the ASF list, this helps to provide a legal shield to the discussion. Given that our current way of development requires major design decisions and discussions being made in Github issues, we will likely resolve the issue by mirroring Github issues into dev@.

I think one possible grey part of the field is the discourse forum https://discuss.tvm.ai/. While Apache projects are mail-list heavy, many users of the projects and developers find it easy to make use of discourse forums. And this approach has been adopted by communities like Rust, Pytorch, Julia. The discuss forum has become a crucial part to enable vibrate community discussions. Given that discourse is used for technical discussions and general support, I feel that there might be less barrier in keeping it, but maybe @markusweimer @sscdotopen  can confirm this as well. Note that major design decisions, which will appear as RFCs(issues), get mirrored into dev@.

**Comment by sscdotopen** [comment]
Hi Tianqi,

I asked on the incubator mailing list whether the ASF has an official 
stance on discussion boards, I will keep you (and the TVM community) 
updated on what they answer. I also feel that it would make sense to 
keep it.

Best,
Sebastian

**Comment by tqchen** [comment]
To follow up a bit on the discourse, one way to make it work with the current ASF infra is to archive every post into a mail-list. I have done some experiments on this and found it is possible via [mail-list mode](https://meta.discourse.org/t/what-is-mailing-list-mode/46008) 

In particular, I created an account archiver, with its own gmail account and enabled mail-list mode. I can confirm the email received all the posts as emails. Then the only thing we need to do is to set up forwarding rules to forward the email to the target mail-list. cc @sscdotopen

**Comment by sscdotopen** [comment]
Hi Tianqi,

Thank you for trying this, if we archive to an ASF controlled email list 
(which we can get from Apache Infra), than everything should be fine :)

Best,
Sebastian

**Comment by kevinthesun** [comment]
+1 apache is a good way to go.

**Comment by tqchen** [comment]
Thanks, everyone for helpful discussions. To summarize, we agree that it is a good idea to move to Apache. The community will need to strive to address the issues being raised and makes the project better for everyone.

We would like to invite everyone to review the formal incubation proposal draft in https://github.com/dmlc/tvm/issues/2466  and move further discussions there.

**Comment by luorixiangyang** [comment]
+1 apache is a good way to go.
