### ISSUE TITLE
Does tvm support model convert from pytorch or onnx?

### ISSUE THREAD

**Issue by jinfagang** [dmlc/tvm#2410]
Does tvm support model ocnvertion from pytorch or onnx? It seems it define models it self and compile to lib,

**Comment by tqchen** [comment]
Yes, see https://docs.tvm.ai/tutorials/index.html#compile-deep-learning-models. For general questions as such, please open new threads in https://discuss.tvm.ai/

**Comment by ajaysg** [comment]
My pytorch onnx graph has Aten operator which was not supported by tensorrt and onnxrt. So i am planning to compile via TVM. will i face any problem because of the Aten operator
