### ISSUE TITLE
[RELAY][COMMON] Common api across nnvm relay

### ISSUE THREAD

**Issue by srkreddy1238** [dmlc/tvm#2413]
This issue is to track the common API movement from nnvm to relay.
This movement is based on the fact that nnvm will depends on relay.

- [ ] nnvm.compiler.save_param_dict

- [ ] nnvm.compiler.load_param_dict

please feel free to add if anybody come across such API require a movement.

**Comment by jroesch** [comment]
I will try and open a PR today after I get a few other things done.

**Comment by jroesch** [comment]
@weberlo I think this would actually be a good way to get back into the code base, could you try and do this? I'm happy to mentor/explain.

**Comment by weberlo** [comment]
Yeah.  Sure thing.  I'm free to talk about it any time.

**Comment by FrozenGene** [comment]
@srkreddy1238 This help we call Relay pass in NNVM or other purpose?

**Comment by srkreddy1238** [comment]
@FrozenGene no special purpose.

A simple model frontend, compilation and execution is now possible without importing NNVMv1 (nnvm).
I came across these API which are still under NNVMv1 but needed to save compilation output of relay.
This issue is just to track such things.

**Comment by FrozenGene** [comment]
@srkreddy1238 Thank you for the explanation.

**Comment by weberlo** [comment]
Sorry for letting this slip under my radar.  I'll be opening a PR addressing this issue shortly.

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/2620
