### ISSUE TITLE
Error when running "Compile ONNX Models" tutorial

### ISSUE THREAD

**Issue by qigtang** [dmlc/tvm#2415]
I am trying to run the tutorial in https://docs.tvm.ai/tutorials/nnvm/from_onnx.html#sphx-glr-download-tutorials-nnvm-from-onnx-py

- use tvmai/demo-cpu:latest docker image
- inside docker, type "pip3 install onnx" to install onnx 
- Then download jupyter notebook https://docs.tvm.ai/_downloads/0f32a5e1990d5f813b94ba5abdc4600e/from_onnx.ipynb
- in the script, convert target from 'gpu' to 'cpu'
- run the jupyter notebook. It prints out error message

---------------------------------------------------------------------------
NNVMError                                 Traceback (most recent call last)
<ipython-input-7-2cf544afd1d7> in <module>()
      6 shape_dict = {input_name: x.shape}
      7 with nnvm.compiler.build_config(opt_level=3):
----> 8     graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, params=params)

/usr/tvm/nnvm/python/nnvm/compiler/build_module.py in build(graph, target, shape, dtype, params, target_host, layout)
    292     graph = graph.apply("InferShape").apply("InferType")
    293     with target:
--> 294         graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
    295     libmod = graph_attr._move_out_module(graph, "module")
    296     # Write variable initial values into params

/usr/tvm/nnvm/python/nnvm/graph.py in apply(self, passes)
    232         ghandle = GraphHandle()
    233         npass = nn_uint(len(passes))
--> 234         check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
    235         return Graph(ghandle)
    236 

/usr/tvm/nnvm/python/nnvm/_base.py in check_call(ret)
     73     """
     74     if ret != 0:
---> 75         raise NNVMError(py_str(_LIB.NNGetLastError()))
     76 
     77 def c_str(string):

NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/usr/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/usr/tvm/nnvm/python/nnvm/top/nn.py", line 138, in schedule_conv2d
    return topi.generic.schedule_conv2d_nchw(outs)
  File "<decorator-gen-181>", line 2, in schedule_conv2d_nchw
  File "/usr/tvm/python/tvm/target.py", line 346, in dispatch_func
    return func(*args, **kwargs)
  File "/usr/tvm/topi/python/topi/generic/nn.py", line 36, in schedule_conv2d_nchw
    return _default_schedule(outs, False)
  File "/usr/tvm/topi/python/topi/generic/nn.py", line 12, in _default_schedule
    raise RuntimeError("schedule not registered for '%s'" % target)
RuntimeError: schedule not registered for 'stackvm'

The jupyter notebook cell 

```python
import nnvm.compiler
#target = 'cuda'
target = 'cpu'
# assume first input name is data
input_name = sym.list_input_names()[0]
shape_dict = {input_name: x.shape}
with nnvm.compiler.build_config(opt_level=3):
    graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, params=params)
```

**Comment by tqchen** [comment]
Thanks for reporting the problem, please open a new thread at https://discuss.tvm.ai/. In your case, it is likely due to not compiling with LLVM

**Comment by qigtang** [comment]
Thanks! 
Will try build the tool from source with llvm later.
