### ISSUE TITLE
FullyConnected with PRelu Error

### ISSUE THREAD

**Issue by JeffSoong** [dmlc/tvm#2428]
Check failed: dshape.ndim() == 4 (2 vs. 4) Input data should be 4D, but got 2

**Comment by FrozenGene** [comment]
@JeffSoong could you list more detail information? For example, what frontend you use? what model you test? If the model is your internal, could you construct simple unit test case? These information could help we reconstruct your issue and help to find out the reason.

**Comment by tqchen** [comment]
Thanks for reporting this problem, as the item is not currently directly actionable, please open a new thread in https://discuss.tvm.ai/

**Comment by XiaolongMeng** [comment]
I simple del CHECK_EQ... It works find...

**Comment by FrozenGene** [comment]
@XiaolongMeng I think you could make a PR. That CHECK_EQ shouldn't be there.
