### ISSUE TITLE
[Relay] Flaky Compilation for Gluoncv SSD model

### ISSUE THREAD

**Issue by kevinthesun** [dmlc/tvm#2431]
I'm adding relay support for gluoncv ssd models. The end to end compilation randomly fails:https://github.com/kevinthesun/tvm/blob/RefactorSSDOperator/tutorials/nnvm/deploy_ssd.py

First build RefactorSSDOperator branch under my folk tvm with USE_SORT ON
Then run the test several times:
```python
python deploy_ssd.py -f relay
```
Sometimes it succeeds but sometimes fails.
The segfault happens inside op fuse pass: https://github.com/kevinthesun/tvm/blob/RefactorSSDOperator/src/relay/pass/fuse_ops.cc#L741

@jroesch

**Comment by masahi** [comment]
Ok, that line was added by me. I'll take a look.

**Comment by masahi** [comment]
on Windows, it always segfaults. Disabling fusion support for tuple node will remove the segfault, but then there is another error:

```
File "test_ssd.py", line 89, in <module>
graph, lib, params = relay.build(net, target, params=params)
File "D:\projects\dev\tvm\python\tvm\relay\build_module.py", line 274, in build
graph_json, lowered_funcs, params = graph_gen.codegen(func)
File "D:\projects\dev\tvm\python\tvm\relay\backend\graph_runtime_codegen.py", line 386, in codegen
self.storage_device_map = _backend.GraphPlanMemory(func)
File "D:\projects\dev\tvm\python\tvm\_ffi\_ctypes\function.py", line 185, in __call__
ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "D:\projects\dev\tvm\python\tvm\_ffi\base.py", line 72, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [14:07:37] d:\projects\dev\tvm\src\relay\backend\graph_plan_memory.cc:102: Check failed: it != token_map_.end()
```

**Comment by masahi** [comment]
@kevinthesun I found the bug! deploy_ssd.py works with relay.

please change [this line](https://github.com/dmlc/tvm/blob/master/src/relay/pass/fuse_ops.cc#L744) to

```
for (size_t i = 0; i < new_fields.size() && isolated; ++i) {
```

I'll send a PR soon.

**Comment by kevinthesun** [comment]
Thank you for quick response！

**Comment by jroesch** [comment]
Thanks for showing up with the fix @masahi !! Will you cc me on the PR?
