### ISSUE TITLE
[RFC] Streamline the relay build and optimize interface

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#2449]
As per #2361 , the build now takes an additional parameter(fallback_device). This is an RFC to discuss the interface of the build.

In particular, there is a dangerous trend in adding compilation related options to the interface itself, we can imagine that additional parameters will get added when we want more options, making build and optimize harder to maintain, this happened in the past in XGBoost project, whose train interface have an explosive growth of options that we lose track of.

I want to propose a discussion on the build interface, in particular, if we can keep additional pass options in build config, and keep a clean, consistent build interface with target, target_host and params.

cc @zhiics @jroesch @yzhliu

**Comment by zhiics** [comment]
Yes, I am actually also aware of this. Another case may need again to extend the API is when we have different annotation schemes. Adding options looks a better way to me.

**Comment by tqchen** [comment]
@zhiics can you send a refactor patch then?

**Comment by zhiics** [comment]
Sure. I will.
