### ISSUE TITLE
[RFC] Make use of Shuffle Expr

### ISSUE THREAD

**Issue by liwchang** [dmlc/tvm#2452]
It might be considered as a general version to replace tvm_warp_shuffle.
For llvm, it can simply generate llvm vector instruction, like extractelement or shufflevector.

-L

**Comment by tqchen** [comment]
The warp_shuffle is different from shuffle because it involves multiple threads. But indeed shuffle can be useful in certain cases. This is something I have been debating about recently. 

On one hand, shuffle will enrich the semantics of the low-level IR and makes it easy to generate complicated vector instructions.  On the other hand, such additional complexity and expressiveness introduced, while being good for LLVM, may create additional burdens for other backends, especially the accelerator part. My current take is that given that the shuffle is not the bottleneck of our current workload so far, we might not have to bring this additional complexity yet, but I am also open to the other option.

**Comment by tqchen** [comment]
BTW, for general RFC style proposals, please use RFC prefix :) We also welcome general discussion threads in https://discuss.tvm.ai/

**Comment by liwchang** [comment]
Sure.
It is not difficult to work around anyway, just look ugly to me.

BTW, warp_shuffle should be exactly like vector shuffle. 
Warp is just terminology of vector in CUDA.

To me, shuffle is a sugar expression for access pattern.
The same shuffle be also lowered to storing local array, and loading back, like scratchpad in GPU.
It can further unify transformation across architecture.

But you might be right. 
It seems not the bottleneck.

-L

**Comment by tqchen** [comment]
I can get the analogy between warp_shuffle and shuffle, it is just that the programming model of CUDA and OpenCL did not treat the warp as a vector lane but allows you to program them separately. So it looks more like an all-to-all communicator. If we have a good idea on how to represent them in a unified way in low level IR, it would be interesting to see what that would look like

**Comment by liwchang** [comment]
I think you got the key point, since you mention communicator.
I think I also realized some confusion since I mentioned HalideIR's Shuffle.
HalideIR's Shuffle seems only working on vector type, so that is why you kept mentioning vector.


The best design in my mind should be Shuffle that works on axis.
It can apply in scheduling by giving strong hint for communication/access pattern.
If that axis got vectorized, then goes current Halide's.
If that axis got bind to CUDA/CL thread within a warp, do something like warp_shuffle.
If that axis got serialized, just generate loop for access.
If that axis got bind to CUDA/CL block, we can give do basic thread communication through scratchpad.
If that axis got bind to outer axis of CUDA/CL blocks, we can do some block communication trick, or just through an exception for no support (we already throw a ton of exception anyway. :) ).  
If that axis got bind to distribute node, we can give call some MPI communication subroutine.
For axis in some asic or FPGA, you can think about module duplication, and communication routing or message instruction around them.

Semantic-wise, Shuffle implies that the data communication has the same results as it happen in a lock-step.
(Let's call it a semantic lock-step.)
Whether it really happen in a lock-step like CUDA-warp or not. We actually don't care. 
I don't think CL really guarantee a real lock-step in HW level.

By unifying it, API and codegen should be simpler.
Even autotuning can be simpler.

-L

**Comment by tqchen** [comment]
This seems to head in the right direction, but we will need a more detailed proposal. How about we close this RFC first, as it is not currently directly actionable. If you can think a bit more and sent in another RFC as a proposal, we can do a more in-depth discussion.

**Comment by liwchang** [comment]
Sure.
