### ISSUE TITLE
[BUG] Integer overflow during interval analysis and simplification

### ISSUE THREAD

**Issue by sgrechanik-h** [dmlc/tvm#2455]
Consider the following code:
```python
import tvm

dtype = 'int32'
cnst = lambda c: tvm.const(c, dtype)
vs = [tvm.var("x" + str(i), dtype) for i in range(4)]
[x0, x1,x2, x3] = vs
vranges = {v: tvm.Range(tvm.const(-256*256*2560, dtype), tvm.const(256*256*256*20, dtype))
               for v in vs}

expr = x0*cnst(2) + x1*cnst(2) + x2*cnst(2) + cnst(-1) < x3*cnst(-1)

res = tvm.ir_pass.CanonicalSimplify(expr, vranges)

print(vranges)
print(expr)
print(res)
```

(Note that all the specified ranges are within the limits for int32).
CanonicalSimplify simplifies the expression to 1 which is wrong. The reason is that during interval analysis (EvalSet) an integer overflow happens. Note that although internally values are represented as int64, which should be enough, the function `IntImm::make` from HalideIR intentionally performs truncation of higher bits.
I don't know what to do with this problem, the truncation seems important if we want to preserve the exact behavior of integer operations, but I think it should be disabled for interval analysis somehow.

**Comment by tqchen** [comment]
given that the real code overflows, it is hard to argue this as a bug for now. Ideally, we will want to move most of the integer analysis to int64 and do a bound analysis to narrow down necessary ones to int32. This will likely mean a refactor of the current integer analysis. I would suggest we put this in our list to be noticed, and come back to it when we refactor integer analysis. I hope that can happen in the 0.6 release cycle.

**Comment by tqchen** [comment]
Consolidate this issue to #2588
