### ISSUE TITLE
[TOPI] topi.nn.batch_norm_inference is broken

### ISSUE THREAD

**Issue by headupinclouds** [dmlc/tvm#2470]
The `topi.nn.batch_norm_inference` python implementation appears to be broken.

```
  File "/dl/mxnet/3rdparty/tvm/topi/python/topi/nn/batch_norm.py", line 54, in batch_norm_inference
    mean = tvm.compute((C, ), lambda c: moving_mean[c])
NameError: name 'C' is not defined
```

https://github.com/dmlc/tvm/blob/e4b9f986dab8c48ba109a52106565fc4be6b67c4/topi/python/topi/nn/batch_norm.py#L54-L56

Should the offending lines (`mean` and `var` return variables) just be removed here?

C++ prototype:

https://github.com/dmlc/tvm/blob/e4b9f986dab8c48ba109a52106565fc4be6b67c4/topi/include/topi/nn/batch_norm.h#L33-L41

For what it's worth, `topi.nn.batch_norm_inference` doesn't currently have a unit test, and I don't see any other references to it in the repository:

```
find /dl/mxnet/3rdparty/tvm/ -name "*.py" | xargs grep batch_norm_inference
```

```
/dl/mxnet/3rdparty/tvm/topi/python/topi/nn/batch_norm.py:def batch_norm_inference(data, gamma, beta, moving_mean, moving_var, eps, fix_gamma):
```

**Comment by yzhliu** [comment]
I feel `batch_norm_inference` is no longer used as `batch_norm` gets decomposed into several scalar operations in `simplify_inference` pass.

**Comment by headupinclouds** [comment]
> I feel batch_norm_inference is no longer used as batch_norm gets decomposed into several scalar operations in simplify_inference pass

I see.  Are you suggesting it should just be removed?

**Comment by yzhliu** [comment]
Yes, let's do it. would you mind shoot a PR to remove?

**Comment by headupinclouds** [comment]
pushed https://github.com/dmlc/tvm/pull/2626
