### ISSUE TITLE
[RUST][RUNTIME] nnvm test fails

### ISSUE THREAD

**Issue by ehsanmok** [dmlc/tvm#2480]
During my local dev for Rust frontend, the current runtime `tests/test_nnvm` fails with that is also a problem with other current PRs such as [this](http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-2479/1/pipeline) in [here](https://github.com/dmlc/tvm/pull/2479).

```
error: failed to run custom build command for `test-nnvm v0.0.0 (/workspace/rust/tests/test_nnvm)`

process didn't exit successfully: `/workspace/rust/tests/test_nnvm/target/debug/build/test-nnvm-7757aa29dfd2f3a3/build-script-build` (exit code: 101)

--- stderr

thread 'main' panicked at 'Cannot find config for target=llvm --system-lib, workload=('dense', (4, 8, 'float32'), (16, 8, 'float32'), (16, 'float32')). A fallback configuration is used, which may bring great performance regression.

', build.rs:18:5

note: Run with `RUST_BACKTRACE=1` for a backtrace.

````
Previously, my local test was failing at [this check_sum](https://github.com/dmlc/tvm/blob/master/rust/tests/test_nnvm/src/main.rs#L71). This is rather strange. I'm on **Rust-nightly 1.32**.

@tqchen @nhynes

**Comment by nhynes** [comment]
I ran the tests in a local docker container according to the CI flow on 0806b69e3fb136226fa1dafad00bd2c606cc998d but could not reproduce the bug. I'd suggest rebasing the failing PRs onto `master`, at the very least.

**Comment by eqy** [comment]
Interesting, the three most recently opened PRs all fail with this error.

**Comment by nhynes** [comment]
Well, I [found the bug](https://github.com/dmlc/tvm/blob/master/rust/tests/test_nnvm/build.rs#L17). Why I couldn't reproduce is a separate issue, but I'll post a fix now :)
