### ISSUE TITLE
[RFC] Pytorch Support for TVM

### ISSUE THREAD

**Issue by JennyChou5** [dmlc/tvm#2494]
### Problem Statement
PyTorch is a relatively new deep learning framework that is fast becoming popular among researchers and data scientists. It shows the capability to build deep learning applications on top of dynamic graphs which can be played with on runtime. Having Pytorch support in TVM can drive faster adoption, particularly among product builders who would like to ship PyTorch models into edge devices. Although current TVM supports ONNX input format and Pytorch package can export pretrained models in torchvision into ONNX, there is still gap with direct pytorch support for TVM due to ONNX limitation.

### Current TVM Framework Support StatusCurrently 
TVM rely on user exporting pytorch model to ONNX format and feed single .onnx file into it. However, ONNX exporter is a trace-based exporter. It operates by executing the model once, and exporting the operators which were actually run during this run. Therefore, if the model is dynamic which may change behavior depending on input data, the export would not be accurate.

### Proposed Pytorch Support for connecting NNVM and Relay
With the NNVM IR	 allowing user to register operators and their attributes, we would like to first load a model in PyTorch and save it as .json (symbol graph) and .npz (weights) and later convert the symbol graph to NNVM graph. We plan to leverage the ONNX parser as much as possible for models but provide the operators mapping directly to NNVM if there exists error when applying torch.onnx. 
With Relay, the second generation of NNVM, which mainly support data flow-style programming, functional-style scoping, let-binding, etc, more investigation is needed, including how to export dynamic graphs written in Pytorch.

**Comment by tqchen** [comment]
Maybe someone from Pytorch team can also chime in and see if it is a recommended way? Is there an official IR in Pytorch that we should connect to. 

Might also be helpful to get feedbacks from pytorch folks: cc @hlu1 @ajtulloch @ezyang @soumith

**Comment by tqchen** [comment]
closed for now, likely we can get related support in https://github.com/pytorch/tvm thanks to @bwasti
