### ISSUE TITLE
can not found cl.exe,please run this in Vistual Studio Command Prompt

### ISSUE THREAD

**Issue by mukul74** [dmlc/tvm#2497]
![image](https://user-images.githubusercontent.com/5962451/51603601-3e8f9800-1f30-11e9-8452-981681ef48c8.png)

https://docs.tvm.ai/tutorials/get_started.html#sphx-glr-tutorials-get-started-py
* I have added the cl.exe path in the environment path but still this issue is appearing .
* Any suggestions?

**Comment by tqchen** [comment]
Please open a new thread in https://discuss.tvm.ai/
