### ISSUE TITLE
can't find the header file 

### ISSUE THREAD

**Issue by yvn96** [dmlc/tvm#2499]
When we are saving the shared library then .o files are being passed to form a .so file. There should be a .h file also for linking. Where can I get that .h file?

**Comment by eqy** [comment]
[This](https://github.com/dmlc/tvm/blob/master/apps/howto_deploy/cpp_deploy.cc) is an example of using C++ to deploy a TVM module. In the future, please use the [discuss board](discuss.tvm.ai) for support questions; thanks!
