### ISSUE TITLE
[Relay][Parser] Parser Roundtrip

### ISSUE THREAD

**Issue by joshpoll** [dmlc/tvm#2501]
The Relay parser should be able to roundtrip with the pretty printer, i.e., for any Relay AST `ast`, `relay.fromtext(ast.astext()) == ast`. We probably want a similar guarantee for pretty printing and parsing modules. This will ensure that the parser and printer agree on a single canonical text format.

One simple way of doing this is to write a bunch of tests by hand; however, it should be possible to write a generator/fuzzer that creates valid Relay ASTs, which we can then use to test the equality above. It will also help us achieve good test case coverage and hopefully find subtle bugs.

It is also possible to go the other way, i.e., for any Relay text format program `prog`, `relay.fromtext(prog).astext() == prog`. This direction is more difficult since it requires preserving more information about a source program during parsing like whitespace and syntactic sugar usage (e.g. writing `+` vs. `relay.add`). Although it's more work, it would also allow us to display error messages more appropriately since we would be able to pretty print ASTs as they appear in the original text format program.

For more information on roundtripping, check out these links:
- https://teh.id.au/posts/2017/06/07/round-trip-property
- https://dev.eiffel.com/Design_of_Roundtrip_Parser

cc: @wweic @jroesch

**Comment by tqchen** [comment]
close due to inactive status
