### ISSUE TITLE
[Relay] Negative test cases for type inference

### ISSUE THREAD

**Issue by slyubomirsky** [dmlc/tvm#2502]
Type inference is a critical feature for Relay, as the number of explicit type annotations that would be needed for the type system to be workable would be overwhelming otherwise. However, our test suite for it is pretty sparse considering how important a feature it is.

A simple area of improvement would be adding more negative test cases, which the current tests do not include at all. These cases would be particularly important for preventing regression.

(I am perfectly happy to be assigned to this, I just wanted to document this issue so that it does not get lost amid the other major Relay features being added.)

**Comment by tqchen** [comment]
Close for now mainly because this issue is a bit too generic to be actionable, let us open new threads with concrete actionable items so we can work to close them
