### ISSUE TITLE
Compilation error Golang 1.11 (go1.11.4 darwin)

### ISSUE THREAD

**Issue by patrikhermansson** [dmlc/tvm#2517]
Hi,
I'm getting the following error when building the Golang module. Latest checkout of the tvm repository.

go version go1.11.4 darwin/amd64

`$ make
function_test.go:207:30: error strings should not be capitalized or end with punctuation or a newline
ndarray.go:104:30: error strings should not be capitalized or end with punctuation or a newline
ndarray.go:198:30: error strings should not be capitalized or end with punctuation or a newline
ndarray.go:282:26: error strings should not be capitalized or end with punctuation or a newline
ndarray.go:293:34: error strings should not be capitalized or end with punctuation or a newline
value.go:310:34: error strings should not be capitalized or end with punctuation or a newline
value.go:323:30: error strings should not be capitalized or end with punctuation or a newline

gotvm

./ndarray.go:251: cannot use (*_Ctype_long)(&shape[0]) (type *_Ctype_long) as type *_Ctype_longlong in argument to func literal
make: *** [all] Error `

**Comment by srkreddy1238** [comment]
@patrikhermansson  thanks for reporting, let me check.

**Comment by srkreddy1238** [comment]
@patrikhermansson  can you try below patch ?

```
diff --git a/golang/Makefile b/golang/Makefile
index 54019740..d62133b7 100644
--- a/golang/Makefile
+++ b/golang/Makefile
@@ -7,8 +7,8 @@ NATIVE_SRC = tvm_runtime_pack.cc
 
 GOPATH=$(CURDIR)/gopath
 GOPATHDIR=${GOPATH}/src/${TARGET}/
-CGO_CPPFLAGS="-I. -I${TVM_BASE}/ -I${TVM_BASE}/3rdparty/dmlc-core/include -I${TVM_BASE}/include -I${TVM_BASE}/3rdparty/dlpack/include/"
-CGO_CXXFLAGS="-std=c++11"
+CGO_CPPFLAGS="-I. -I${TVM_BASE}/ -I${TVM_BASE}/3rdparty/dmlc-core/include -I${TVM_BASE}/include -I${TVM_BASE}/3rdparty/dlpack/include/ -m64"
+CGO_CXXFLAGS="-std=c++11 -m64"
 CGO_CFLAGS="-I${TVM_BASE}"
 CGO_LDFLAGS="-ldl -lm"
```
