### ISSUE TITLE
[FRONTEND] Tensorflow Op: FIFOQueueV2 and QueueDequeueManyV2 are not supported

### ISSUE THREAD

**Issue by yongwww** [dmlc/tvm#2518]
Got the following error message when tried to parse [TensorFlow Lite official model](https://www.tensorflow.org/lite/models) ResNet_V2_101, the frozen pb file is resnet_v2_101_299_frozen.pb.

`NotImplementedError: The following operators are not implemented: {'FIFOQueueV2', 'QueueDequeueManyV2'}`

**Comment by yongwww** [comment]
Potential fix: Skip the two ops by simply mapping to _undef, they are not related inference in this graphdef, any suggestion or comments? @srkreddy1238 @zhiics

**Comment by tqchen** [comment]
Thanks for brings this up. For normal questions and requests please open a new thread in https://discuss.tvm.ai/

**Comment by alex96295** [comment]
@yongwww  @zhiics sorry how do you 'map ops to _undef'? I have the very same issue

**Comment by srkreddy1238** [comment]
One option would be mapping them to Identity in frontend.

**Comment by alex96295** [comment]
@srkreddy1238 thank you for your answer
I am pretty a beginner here, especially with TensorFlow, could you please tell me a possible - practical - way of doing what you said? In terms of code, where and how modify it
