### ISSUE TITLE
"Disable copy and assign from another value, but allow move"

### ISSUE THREAD

**Issue by alexeyr** [dmlc/tvm#2521]
This is the comment at https://github.com/dmlc/tvm/blob/1120655b7bc43c8881f982424a986974eeaf75e6/include/tvm/runtime/packed_func.h#L609-L612, but instead of being disabled the copy constructor is declared on the next line (and the assignment operator on https://github.com/dmlc/tvm/blob/1120655b7bc43c8881f982424a986974eeaf75e6/include/tvm/runtime/packed_func.h#L718-L720). 

One of them should be removed, but I don't know which (deleting copy constructor explicitly makes compilation fail).

**Comment by tqchen** [comment]
Thanks for pointing it out. The comment should be removed

**Comment by tqchen** [comment]
close by #2527  thanks to @alexeyr
