### ISSUE TITLE
[Installation]rang.hpp: No such file or directory

### ISSUE THREAD

**Issue by TonyZhouCH** [dmlc/tvm#2522]
Hi!
I pull the latest code. And I compile the tvm from source code.
+  When I compile, an error occurs which is "/tvm/src/relay/ir/error.cc:12:20: fatal error: **rang.hpp**: No such file or directory"
+ I checked the git log, the 'error.cc' was created 4 days ago. And I didn't find the 'rang.hpp' in the repo.
 
Thanks!!!

**Comment by leeexyz** [comment]
Hi, it is a sub-repository under`tvm/3rdparty/rang`. you should clone it. please check [rang](https://github.com/agauniyal/rang/)

**Comment by TonyZhouCH** [comment]
It solves! Thank you!!
