### ISSUE TITLE
[TFLite] Tutorial Compile TFLite Models occur AttributeError: 'SubGraph' object has no attribute 'InputsAsNumpy'

### ISSUE THREAD

**Issue by rivergold** [dmlc/tvm#2528]
I follow the Tutorial: [Compile TFLite Models](https://docs.tvm.ai/tutorials/frontend/from_tflite.html#sphx-glr-tutorials-frontend-from-tflite-py), and when I run the followings
```python
from tvm import relay
func, params = relay.frontend.from_tflite(tflite_model,
                                          shape_dict={input_tensor: input_shape},
                                          dtype_dict={input_tensor: input_dtype})
```
meet the  error
```
File "xxxx/tvm/tvm/python/tvm/relay/frontend/tflite.py", line 609, in from_tflite
    model_inputs = subgraph.InputsAsNumpy()
AttributeError: 'SubGraph' object has no attribute 'InputsAsNumpy'
```
Is there any solutions or what have I missed?

**Comment by FrozenGene** [comment]
Which python version do you use? Have you install TFLite package correctly? Subgraph should have this method of InputsAsNumpy(). See here: https://github.com/FrozenGene/tflite/blob/master/tflite/SubGraph.py#L50

**Comment by tqchen** [comment]
please open a new thread in discuss.tvm.ai
