### ISSUE TITLE
Debug VTA in Simulation

### ISSUE THREAD

**Issue by sameer120** [dmlc/tvm#2530]
Hello,

I am modifying the VTA Core to add some extra SRAM and hold the data locally instead of sending it to DRAM, I want to debug my logic, can I know the tool chain and enviornment i should use to debug this issue. Just want clarify i want to do it in Host Software(Simulation) not on FPGA.

Thanks & Regards
Sameer

**Comment by Ravenwater** [comment]
@sameer120 looking at the code, the sim is a pure functional emulator of state ( https://github.com/dmlc/tvm/blob/master/vta/src/sim/sim_driver.cc ) and thus a simple C++ compiler and debugger would be sufficient to validate your mods.

I heard from @tmoreau89 that there is a WIP branch for another FPGA board, but I cannot find a proper fsim/asim/psim/rtl progression that is more common in processor design exploration. 

Looking at your requirements, the SRAM mod you are looking at is a simple configuration value, and the local memory vs remote memory is an additional API and resource definition plus the semantics that you need to be able to marshal data from your local memory to remove memory. So fundamentally you would learn very little from modifying the simulator as functionality is not why you would create a local memory, you would do that for performance, and thus you would need to model the temporal dimension of managing the local memory resource. 

However, this request does demonstrate that the simulation back-end of VTA needs a lot of TLC before it becomes usable as a design exploration tool.

**Comment by tqchen** [comment]
Thanks for the helpful discussion, given its nature, please open a new thread in https://discuss.tvm.ai/
