### ISSUE TITLE
Repeated check for `if (c.mem.opcode == VTA_OPCODE_LOAD || c.mem.opcode == VTA_OPCODE_STORE)`

### ISSUE THREAD

**Issue by alexeyr** [dmlc/tvm#2538]
Nested under https://github.com/dmlc/tvm/blob/75f91c45d7135f366ce653cb2b2d26de2cf25df0/vta/src/runtime.cc#L626 we have the same check in https://github.com/dmlc/tvm/blob/75f91c45d7135f366ce653cb2b2d26de2cf25df0/vta/src/runtime.cc#L641
which even has an `else`.

Probably the second `if` should either be removed or have its condition changed.

**Comment by tqchen** [comment]
#2557
