### ISSUE TITLE
Trivially true CHECK(to != kLoadStage || to != kComputeStage);

### ISSUE THREAD

**Issue by alexeyr** [dmlc/tvm#2539]
The condition in https://github.com/dmlc/tvm/blob/75f91c45d7135f366ce653cb2b2d26de2cf25df0/vta/src/runtime.cc#L498
is always true whatever `to` is. Should it be `&&` instead of `||`, or should one of the sides have `from` as in the previous line?

**Comment by alexeyr** [comment]
That's my understanding of the CHECK in the previous line, but this one can't guard against anything, can it? 

Unless `kLoadStage` and `kComputeStage` are accidentally changed to be equal, which would be a rather bigger problem, but probably not the intention :)

**Comment by tqchen** [comment]
Ah,  you are right, thanks for pointing it out, a fix is welcomed :)

**Comment by alexeyr** [comment]
The problem is that I don't know what the fixed check should be, I only have guesses which I mentioned in the original post.

**Comment by tqchen** [comment]
It should be  CHECK(from != kLoadStage || to != kComputeStage);
