### ISSUE TITLE
An uint32_t compared with 0

### ISSUE THREAD

**Issue by alexeyr** [dmlc/tvm#2540]
Either the comparison in https://github.com/dmlc/tvm/blob/426e3bb0a8e86bb48a25b950fd8ef965ca5d370b/src/relay/op/layout.h#L115 should be changed to `!= -1` or `int32_t` used for `superdim_pos` and the other two vectors. The second looks better to me since `-1` is used as the sentinel value.

**Comment by tqchen** [comment]
#2557
