### ISSUE TITLE
Duplicate functions entry_id and GetEntryId

### ISSUE THREAD

**Issue by alexeyr** [dmlc/tvm#2541]
Functions in https://github.com/dmlc/tvm/blob/f359e06590fef2275c8f5eae91c8f0beced0f857/src/runtime/graph/graph_runtime.h#L364-L366 and https://github.com/dmlc/tvm/blob/f359e06590fef2275c8f5eae91c8f0beced0f857/src/runtime/graph/graph_runtime.h#L149-L151 are identical. Should one of them be removed or call another?

Ok, this should be the last minor issue for now :)

**Comment by tqchen** [comment]
I think we should only support entry_id

**Comment by tqchen** [comment]
#2557
