### ISSUE TITLE
[VOTE] Apache Incubation 

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#2543]
In #2401 , the community agrees that it is a good idea to move toward Apache. In #2466 , the TVM community collectively drafted the proposal.

This is the formal voting thread for the [TVM Apache Incubation Proposal](https://docs.google.com/document/d/11xjGiRKXnAfc6RhznmL6-CT5f1vw-0ajBdlBYkbZXk0/edit?usp=sharing
)
The vote will last for a week and end on Feb 9th. Everyone in the community is welcomed to participate, please vote (by replying to the thread, emoji is also fine but a reply is better):

- +1  if you agree
- +0 if you do not care
- -1  because ...

cc @dmlc/tvm-committer  @markusweimer, @sscdotopen, @bgchun

**Comment by ZihengJiang** [comment]
+1

**Comment by icemelon9** [comment]
+1

**Comment by nhynes** [comment]
+1

**Comment by zhiics** [comment]
+1

**Comment by FrozenGene** [comment]
+1

**Comment by yongwww** [comment]
+1

**Comment by Ravenwater** [comment]
+1

**Comment by srkreddy1238** [comment]
+1

**Comment by derisavi** [comment]
+1

**Comment by alex-weaver** [comment]
+1

**Comment by ajtulloch** [comment]
+1

**Comment by tqchen** [comment]
Thanks to everyone who voted on this thread. The vote has passed. We will start the incubation proposal process. 

cc @dmlc/tvm-committer @markusweimer, @sscdotopen, @bgchun

**Comment by tqchen** [comment]
See https://github.com/dmlc/tvm/issues/2907 for transition note
