### ISSUE TITLE
Description of computing block data

### ISSUE THREAD

**Issue by ShawnZhuang** [dmlc/tvm#2545]
a tvm.compute support only point to point description (ignore the tensor-compute since it is incompatible with inferbound and split).   For new incomming hardwares , such as arm tpu or huawei Ascend,   the instructs usually operate on blocks of buffer. only the address and range of the buffer is concerned.  i want to develop a new compute to descript  a block buffer operation

**Comment by tqchen** [comment]
please open a new thread in discuss forum
