### ISSUE TITLE
[VOTE] TVM 0.5 Release

### ISSUE THREAD

**Issue by ZihengJiang** [dmlc/tvm#2547]
Dear TVM Community,

This is the vote to release TVM version v0.5 (commit: e0af5c200faa786967e5c76f37b71e12fb64d661). Voting will start today, Friday February 1st and will close on Wednesday Feb 6th.

Link to release notes candidate: https://github.com/dmlc/tvm/issues/2448 

Everyone in the community is welcomed to participate, please vote (by replying to the thread, emoji is also fine but a reply is better):

+1 if you agree
+0 if you do not care
-1 because ...

We partially adopt the [Apache Release Policy](http://www.apache.org/legal/release-policy.html#policy):

> For a release vote to pass, a minimum of three positive votes and more positive than negative votes MUST be cast. Releases may not be vetoed. Votes cast by PMC members are binding.

While again we encourage everyone to review, verify and vote, your feedback is invaluable to the community and is greatly appreciated.

cc @dmlc/tvm-committer

**Comment by masahi** [comment]
+1

**Comment by FrozenGene** [comment]
+1

**Comment by Laurawly** [comment]
+1

**Comment by kazum** [comment]
+1

**Comment by icemelon9** [comment]
+1

**Comment by srkreddy1238** [comment]
+1

**Comment by ZihengJiang** [comment]
Hi community, thanks to everyone who voted on this thread. However, we have several bug-fix PRs for the new feature, liker #2495 #2573 #2580 . Members like @tqchen , @yzhliu and me believe that It would be better to have them in the 0.5 release. According to the apache rule, we need to cancel this vote and have another round of vote for the new commit. I will move the vote forward with another Github issue.
