### ISSUE TITLE
[RFC] Data Layout Structure in TVM Node System

### ISSUE THREAD

**Issue by yzhliu** [dmlc/tvm#2554]
As we now more and more rely on data layout optimization to get decent performance, I'd like to introduce Layout structure into TVM Node system. It would make life easier because,

* Relay and NNVM both have `AlterOpLayout` pass to modify data layout between layers, for now they have their own Layout implementation.
* Later on @kevinthesun will introduce end-to-end auto-tuning. The basic idea is to take inter-layer layout transformation overhead into consideration. As a module in AutoTVM, it will be more nature to use LayoutNode in TVM (instead of that in Relay or NNVM)
* Layout operation can be exposed to Python/Java/Rust/Golang/... frontend directly. TOPI developers will benefit from it as performance is greatly related to data layouts.

It was initially proposed by @tqchen https://discuss.tvm.ai/t/datalayout-structure/80 . A modified implementation can be found [here](https://github.com/dmlc/tvm/pull/2509).

## Definition of a Single Layout
The layout is composed of upper cases, lower cases and numbers, where upper case indicates a primal axis and the corresponding lower case with factor size indicates the subordinate axis. For example, NCHW16c can describe a 5-D tensor of [batch_size, channel, height, width, channel_block=16]. `data_NCHW` and `data_NCHW16c` can be converted to each other by `data_NCHW[n, c, h, w] = data_NCHW16c[n, c/16, h, w, c%16]`

`LayoutNode` can be constructed by a valid layout string. It provides helper function to query the index of an axis, number of dimension, etc.

`LayoutNode` is not implemented to be bind with a fixed shape, that is to say, technically one can assign layout NCHW to a 3-dim tensor, while this is highly discouraged, developers need to keep it in mind.

## Bijective Layout and Layout Transform

Formally a data layout transformation is a bijective function mapping from the source index (i0, i1, …, im) to the target index (j0, j1, … jm). Given two `LayoutNode`, `BijectiveLayoutNode` build and store the mapping rule as following,

```cpp
// Describes how source axis can be mapped
// to the target axis, e.g., [i0 / 16, i1, i0 % 16] can describe NC -> NC16n
Array<Expr> forward_rule;
// and vice versa
Array<Expr> backward_rule;
```
If the given two layouts cannot be converted to each other (e.g., NCHW and OIHW), an undefined `Node` will be returned. So one can check `bilayout.defined()` to test whether two layouts are convertible.

The C++ code below shows the transform interface.

```cpp
class BijectiveLayout : public NodeRef {
 public:
  BijectiveLayout() = default;
  explicit BijectiveLayout(NodePtr<Node> n) : NodeRef(n) {}

  // Given the shape of the source layout, infer the target shape.
  TVM_DLL Array<Expr> ForwardShape(const Array<Expr>& shape) const;
  // Given the target shape, recover the source shape.
  TVM_DLL Array<Expr> BackwardShape(const Array<Expr>& shape) const;
  // Given the indices in the source layout, infer the target indices.
  TVM_DLL Array<Expr> ForwardIndex(const Array<Expr>& index) const;
  // Given the indices in the target layout, infer the source indices.
  TVM_DLL Array<Expr> BackwardIndex(const Array<Expr>& target_index) const;

  /*!
   * \brief access the internal node container
   * \return the pointer to the internal node container
   */
  inline const BijectiveLayoutNode* operator->() const;

  /*! \brief specify container node */
  using ContainerType = BijectiveLayoutNode;
};
```

For example, to convert shape,
```python
bilayout = tvm.bijective_layout("NCHW", "NCHW16c")
dst_shape = bilayout.forward_shape((1, 32, 7, 7))
assert get_const_tuple(dst_shape) == (1, 2, 7, 7, 16)

print(bilayout.forward_shape([tvm.var("n"), tvm.var("c"), tvm.var("h"), tvm.var("w")]))
# output [n, (c/16), h, w, 16]
```

to convert tensor access index,
```python
bilayout = tvm.bijective_layout("NCHW", "NCHW16c")
dst_index = bilayout.forward_index([0, 18, 6, 6])
assert get_const_tuple(dst_index) == (0, 1, 6, 6, 2)  # 1 * 16 + 2 = 18

print(bilayout.forward_index([tvm.var("n"), tvm.var("c"), tvm.var("h"), tvm.var("w")]))
# output [n, (c/16), h, w, (c%16)]
```

**Comment by tqchen** [comment]
closed by https://github.com/dmlc/tvm/pull/2509
