### ISSUE TITLE
Error C2487 when build on Windows

### ISSUE THREAD

**Issue by cloudhan** [dmlc/tvm#2555]
When build with latest master on Windows 10 with Visual Studio 2017, I get the following error:
```
...
D:\workspaces\tvm\include\tvm/runtime/device_api.h(176): error C2487: 'Get': member of dll interface class may not be declared with dll interface (compiling source file D:\workspaces\tvm\src\pass\lower_thread_allreduce.cc) [D:\workspaces\tvm\build\tvm.vcxproj]
...
```
Many  same error on line 176 of `device_api.h`. According to [MSDN](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2487?view=vs-2017) :

> You can declare a whole class, or certain members of a non-DLL interface class, with DLL interface. You cannot declare a class with DLL interface and then declare a member of that class with DLL interface.

That is, the TVM_DLL macro on class and class member are **mutually exclusive**.

**Comment by cloudhan** [comment]
After removing `TVM_DLL` from the static `Get` Method of `DeviceAPI`, now it compiles.

**Comment by tqchen** [comment]
A patch is welcomed!

**Comment by tqchen** [comment]
#2557
