### ISSUE TITLE
[autotvm] callback.log_to_file should clean-up the log file if `tuner.tune` is interrupted

### ISSUE THREAD

**Issue by sabhiram** [dmlc/tvm#2560]
Currently when running a large tuning job, there is no way to know if the results in the log were due to an interrupted task or if the tuning task fully completed. 

Any idea how I can track this? Happy to help if one of the maintainers can point me in the right direction.

**Comment by tqchen** [comment]
Given that this is a discussion item, can you open a new thread in https://discuss.tvm.ai/? We can follow up in issues once we have an actionable item. My guess is that we can add some callback hooks to make this happen
