### ISSUE TITLE
libprotobuf issue

### ISSUE THREAD

**Issue by zzzzzzch** [dmlc/tvm#2579]
Hi!
Sorry to bother you. I came accros a problem about protobuf, which cost me a lot of time to solve and failed.

+ Motivation
   import other DL models (using ONNX or TF) to tvm and sgx
+ Problem
   when using ONNX, it cames:
   >  [libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version **3.6.1** of the Protocol Buffer runtime library, but the installed version is **2.6.1**.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)

   + ONNX needs python-protobuf 3.6.1 version ( I tried installing python-version-2.6.1 to keep the python version consistent with .so version , but python-version-2.6.1 didn't work with python3 and error occurred )
   + I noticed *libnnvm_compiler.so*, *libtvm_runtime.so*, *libtvm.so*, *libtvm_topi.so* all need the **libprotobuf.so.9**, which is version 2.6.1
   + And I want to use sgx, which needs Intel's sgxsdk and Baidu's rust-sgxsdk.
        + *libsgx_urts.so* and *libsgx_uae_service.so* both need **libprotobuf.so.9**
        + Baidu's sdk also needs **libprotobuf.so.9**, according to this [link](https://github.com/baidu/rust-sgx-sdk/blob/master/documents/sgx_in_mesalock_linux.md)

+ Attempts
    + I uninstalled protobuf-2.6.1 on my machine and tried installing protobuf-3.6.1 from protobuf github repo, and same error occurred.
    + I tried the 2.6.1 and 3.6.1 version both existing on my machine, and made the `protoc` command version is 3.6.1, and same error occurred

I don't konw how to solve it. 
Thanks!!

**Comment by srkreddy1238** [comment]
Can you share the exact error log while import ?

**Comment by tqchen** [comment]
Let us always use discuss for this kind of topic https://discuss.tvm.ai/t/libprotobuf-issue/1635
