### ISSUE TITLE
[RFC][TVM] Define a common base class for ComputeOpNode and TensorComputeOpNode

### ISSUE THREAD

**Issue by derisavi** [dmlc/tvm#2583]
## Motivation
There is a significant amount of common code (and concepts) between `ComputeOpNode` and `TensorComputeOpNode`. In particular, methods `root_iter_vars()`, `output_shape()`, `GatherBound()`, `BuildRealize()`, `MakeLoopNest` (and `ComputeLoopNest::make()`, its counterpart for `ComputeOpNode`) have either exactly or almost the same code (around 130 LOC)

## Proposed Solution
We define a common base class (a new `ComputeOpNode`) and have two dervied classes: `ScalarComputeOpNode` (to replace the current `ComputeOpNode`) and `TensorComputeOpNode`. we also add a new method `ComputeOpNode::num_schedulable_dims()` that returns `axis->size()` for `ScalarComputeOpNode` and `scheduable_ndim` data member for `TensorComputeOpNode`.

## Other potential benefits
Currently, `ComputeOpNode` support tensorization but `TensorComputeOpNode` doesn't. It's possible that supporting tensorization in `TensorComputeOpNode` can reuse some of the existing tensorization code in `ComputeOpNode`

**Comment by tqchen** [comment]
I agree this is a good direction, although we might want to discuss a bit with detailed code, please tag folks who you think are relevant

**Comment by ZihengJiang** [comment]
Just out of curiosity, in what situation we need to use `tensorize` in `TensorComputeOp`?

**Comment by derisavi** [comment]
We have used `TensorComputeOp` to put some fine-grained tensor computation inside a black box (for example, a 4x4 matmul). However, our hardware also supports a coarse-grained version of the same tensor computation (for example, a 16x16 matmul), and that is expressible by a loopnest around the fine-grained version. What we would like to do is to `tensorize` to replace the loopnest of fine-grained version with a single invocation of the coarse-grained version.

The reason we use the fine-grained version in our tensor computation is that it gives us more flexibility. Does that answer your question?

**Comment by ZihengJiang** [comment]
@derisavi SGTM. Thanks

**Comment by derisavi** [comment]
Fixed in #2587 so closing.
