### ISSUE TITLE
Bug with relay var that have no shape

### ISSUE THREAD

**Issue by abergeron** [dmlc/tvm#2612]
If you create a variable and pass None as the shape (or just don't pass the shape argument),  the variable ends up being created with None as the type_annotation.

Later on when you try to call a graph that includes such a variable, you get a crash saying the variable has no type.

The code to get a function to compile is rather involved, so I'm not copying it here, but here is how I created the function:

```python
from tvm import relay

x = relay.var('x', dtype='int32')
fn = relay.Function([x], x)
```

The error you get when running this is:
```
tvm._ffi.base.TVMError: [01:49:08] /Users/anakha/miniconda/conda-bld/tvm-libs_1549669997371/work/src/relay/pass/type_infer.cc:492: Check failed: checked_type.as<IncompleteTypeNode>() == nullptr Cannot resolve type of Var(x) at (nullptr)
```

Analyzing the code at https://github.com/dmlc/tvm/blob/master/python/tvm/relay/expr.py#L491, it seems that we indeed only create a type_annotation if shape is not None or type_annotation is a string.

I'm not sure if this is intended behaviour or not, since the document is not super clear on that.  And if this is intended behaviour, I'm curious what use case does it support.

**Comment by tqchen** [comment]
Thanks for bringing this up, because we do not yet have a clear actionable item, do you mind open a thread in https://discuss.tvm.ai/? Would be more than happy to continue discussing there

**Comment by tqchen** [comment]
@abergeron do you mind following up in https://discuss.tvm.ai/? As far as I know, the shape can not be None in the type_annotation (we use empty list[] to indicate zero-dimensional tensor, aka scalar ).
