### ISSUE TITLE
[VOTE] TVM 0.5 Release

### ISSUE THREAD

**Issue by ZihengJiang** [dmlc/tvm#2614]
Dear TVM Community,

Because we have several bug-fix PRs for the new feature, liker #2495 #2573 #2580 . According to the apache rule, we need to cancel the previous vote and have another round of vote for the new commit. This is the new vote to release TVM version v0.5 (commit: [18c36a](https://github.com/dmlc/tvm/commit/18c36ab586f1ce72d7a420ac76d66a3f8b3e1dd6)). Voting will start today, Saturday February 16th and will close on Monday Feb 18th.

Link to release notes candidate: #2448 

Everyone in the community is welcomed to participate, please vote (by replying to the thread, emoji is also fine but a reply is better):

+1 if you agree
+0 if you do not care
-1 because ...

We partially adopt the [Apache Release Policy](http://www.apache.org/legal/release-policy.html#policy):

> For a release vote to pass, a minimum of three positive votes and more positive than negative votes MUST be cast. Releases may not be vetoed. Votes cast by PMC members are binding.

While again we encourage everyone to review, verify and vote, your feedback is invaluable to the community and is greatly appreciated.

cc @dmlc/tvm-committer

**Comment by tqchen** [comment]
+1

**Comment by Ravenwater** [comment]
+1

**Comment by siju-samuel** [comment]
+1

**Comment by kazum** [comment]
+1

**Comment by yzhliu** [comment]
+1

**Comment by vinx13** [comment]
+1

**Comment by Laurawly** [comment]
+1

**Comment by yidawang** [comment]
+1

**Comment by ehsanmok** [comment]
+1

**Comment by icemelon9** [comment]
+1

**Comment by ZihengJiang** [comment]
Thanks to everyone who voted on this thread. The vote has passed. We will start the release process. cc @dmlc/tvm-committer .
I will also keep updating this thread with more news.
