### ISSUE TITLE
Backend for Nvidia Tensor Cores

### ISSUE THREAD

**Issue by chughtapan** [dmlc/tvm#2625]
Hi,
I am interested in code generation using TVM for Nvidia Tensor Cores (eg the ones found in V100). I wanted to know if there is an existing backend for Tensor Cores? If not, how complicated is it to add a backend given support for Tensorization already exists in TVM?

Thanks,
Tapan

**Comment by merrymercy** [comment]
You can try to search on the forum. There are tworelated threads. https://discuss.tvm.ai/search?q=tensor%20core
