### ISSUE TITLE
why not add uninstall guide?

### ISSUE THREAD

**Issue by yongwww** [dmlc/tvm#2638]
TVM has installation tutorial, why not add uninstallation guide?

**Comment by yzhliu** [comment]
probably due to the fact that we don't want users to uninstall :)

would you mind add one into the tutorial?

**Comment by eqy** [comment]
@yongwww we welcome contributions :)

**Comment by yongwww** [comment]
@yzhliu @eqy OK, I will spend some time adding it no later than the next weekend.

**Comment by tqchen** [comment]
Close due to inactive status, and uninstall guide was not as important

**Comment by yongwww** [comment]
show up to say sorry for my delay since I had to work on other stuffs, it is in my todo list, will add it if nobody does
