### ISSUE TITLE
can't run get_start.py

### ISSUE THREAD

**Issue by zkh2018** [dmlc/tvm#2640]
tvm._ffi.base.TVMError: [11:08:39] ~/tvm/src/runtime/cuda/cuda_device_api.cc:93: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: CUDA driver version is insufficient for CUDA runtime version

**Comment by eqy** [comment]
Since this is a support issue, can you please open a thread on the [discuss board](https://discuss.tvm.ai)?
