### ISSUE TITLE
when I use bundle_deploy, occur error:demo: demo.cc:20: int main(int, char**): Assertion `bundle' failed. Makefile:16: recipe for target 'test' failed make: *** [test] 已放弃 (core dumped)

### ISSUE THREAD

**Issue by zaidao2023** [dmlc/tvm#2641]
how to fix it

**Comment by cbecker** [comment]
I saw something similar here. I fixed it by forcing the app to link against the `pthread` library, by adding `-Wl,--no-as-needed -lpthread` to the `demo` rule in the Makefile

**Comment by tqchen** [comment]
Thanks for bringing it up, please move the discussion to https://discuss.tvm.ai/
