### ISSUE TITLE
[DOC][RELAY API] duplicate submodule in the API

### ISSUE THREAD

**Issue by yongwww** [dmlc/tvm#2644]
Looks the API in the [relay api doc](https://docs.tvm.ai/api/python/relay/index.html) is incorrect, there are a lot of duplicate submodules introduced,  for example the `tvm.relay.op.nn.nn.batch_norm` should be `tvm.relay.nn.batch_norm` in the section [tvm.relay.nn](https://docs.tvm.ai/api/python/relay/nn.html). Same issues in other sections of relay api doc.

**Comment by tqchen** [comment]
For cases as such, please directly send in a pull request to fix the issue

**Comment by yongwww** [comment]
@tqchen sure thanks.
