### ISSUE TITLE
[RUST] ci_cpu docker image build failure.

### ISSUE THREAD

**Issue by mjs-arm** [dmlc/tvm#2657]
The ci_cpu docker image fails to build cleanly.  The Dockerfile runs ubuntu_install_rust.sh which in turn executes:
cargo +nightly install rustfmt-nightly --version 1.0.1 --force

Which results in the following build error:

ubuntu_install_rust.sh
^[[0m^[[91m   Compiling scoped-tls v0.1.2
^[[0m^[[91merror[E0277]: the trait bound `std::borrow::Cow<'_, str>: std::convert::From<core::str::EscapeDefault<'_>>` is not satisfied^[[0m^[[91m
^[[0m^[[91m   --> /opt/rust/registry/src/github.com-1ecc6299db9ec823/rustc-ap-graphviz-306.0.0/lib.rs:551:44^[[0m^[[91m
^[[0m^[[91m    |^[[0m^[[91m
^[[0m^[[91m551 |                     (&*s).escape_default().into()^[[0m^[[91m
^[[0m^[[91m    |                                            ^^^^ the trait `std::convert::From<core::str::EscapeDefault<'_>>` is not implemented for `std::borrow::Cow<'_, str>`^[[0m^[[91m
^[[0m^[[91m    |^[[0m^[[91m
^[[0m^[[91m    = help: the following implementations were found:^[[0m^[[91m
^[[0m^[[91m              <std::borrow::Cow<'a, [T]> as std::convert::From<&'a [T]>>^[[0m^[[91m
^[[0m^[[91m              <std::borrow::Cow<'a, [T]> as std::convert::From<&'a std::vec::Vec<T>>>^[[0m^[[91m
^[[0m^[[91m              <std::borrow::Cow<'a, [T]> as std::convert::From<std::vec::Vec<T>>>^[[0m^[[91m
^[[0m^[[91m              <std::borrow::Cow<'a, std::ffi::CStr> as std::convert::From<&'a std::ffi::CStr>>^[[0m^[[91m
^[[0m^[[91m            and 11 others^[[0m^[[91m
^[[0m^[[91m    = note: required because of the requirements on the impl of `std::convert::Into<std::borrow::Cow<'_, str>>` for `core::str::EscapeDefault<'_>`^[[0m^[[91m
^[[0m^[[91m
^[[0m^[[91merror: aborting due to previous error^[[0m^[[91m
^[[0m^[[91m
^[[0m^[[91mFor more information about this error, try `rustc --explain E0277`.^[[0m^[[91m
^[[0m^[[91merror: Could not compile `rustc-ap-graphviz`.
warning: build failed, waiting for other jobs to finish...
^[[0m^[[91merror: failed to compile `rustfmt-nightly v1.0.1`, intermediate artifacts can be found at `/tmp/cargo-installgw3Wp4`

**Comment by tqchen** [comment]
cc @nhynes can you help to take a look?

**Comment by nhynes** [comment]
Huh. I don't think anything changed in `rust/` lately? Maybe there was a missing lockfile somewhere. Isn't semver great? I'll take a look now.

**Comment by tqchen** [comment]
I can confirm there is an error locally, was due to a deleted version tag in /opt/rust/sgx , perhaps in upstream

**Comment by mjs-arm** [comment]
@tgchen can you elaborate a little more detail on the tag you mention above?

**Comment by nhynes** [comment]
I'm working on this literally right now. I'll post back shortly! Super sorry for the long delay.

**Comment by nhynes** [comment]
Ehh. This one was an unfortunate case of rust nightly being unstable (go figure). `rustfmt` 1.0.1 used APIs that changed since the nightly with which it was originally built. Fortunately, the [fix](https://github.com/dmlc/tvm/pull/2852) is simple. Thanks for reporting this!
