### ISSUE TITLE
[TOPI] Better x86 support for conv2d_transpose

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#2658]
see https://discuss.tvm.ai/t/possible-issue-with-conv-transpose-very-slow/1734

**Comment by yidawang** [comment]
We also noticed that. Will see if we can get some cycles to work on it. Will also add the MAC count for this op along with the optimization. @yzhliu @kevinthesun

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/3491
