### ISSUE TITLE
[RFC][COMMUNITY] Nomination Org Principle

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#2663]
Dear TVM community

TVM is a community project, we always put community collaboration at the top of our priority, this is especially true for collaborations with folks who we do not interact daily. I the meanwhile, I do have to admit that have the natural tendency to talk more to our colleagues. 

To further encourage such collaboration and more importantly recognition of community members who are not in our physical circle. We propose to adopt the principle that a PMC member will only nominate candidates from a different organization. This principle will not bar anyone with merit from being nominated(since folks will be nominated by PMC members who are not their colleague at work). It is a principle to encourage folks to interact more with people who are beyond our circles and work together with other folks in the Apache way. Of course, it is by no means a way to prevent all kind of conflict of interest, but it encourages our PMC members to look broadly in the community and bring a better community for everyone.

As you may have noticed in the past community nominations, the current PMC has already done a soft run of this principle in the past five months and it worked quite well. We want to formalize this principle and would like to hear the community’s thoughts on this matter.

Please share your thoughts.

cc @dmlc/tvm-committer

**Comment by ZihengJiang** [comment]
+1.
I like the idea that don't allow to nominate candidate from the same org. I believe that it would be helpful to achieve a diverse community.

**Comment by antinucleon** [comment]
+1 From oberservation of a very similar cross org DL project, every org has its own interest and trys to push project follow their best interest. This will bring deadly effect when interests are very different and there is POTENTIAL unreasonable PMC to screw up contributors from other org. This proposal is able to avoid potential painful situation we have seen in other project.

**Comment by antinucleon** [comment]
+1. From historical observation, this will make project healthier, bring more diversity and help make project fair to every org. Also it will be helpful in the merit evaluation process.

**Comment by tqchen** [comment]
Formal voting thread here https://github.com/dmlc/tvm/issues/2717
