### ISSUE TITLE
[DOCS] Relay Tutorials Completion 

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#2678]
As we transition to relay, we need to upgrade the original documents in nnvm to use relay instead, here are a list of pending items to be fixed

- [x] https://docs.tvm.ai/tutorials/nnvm_quick_start.html#sphx-glr-tutorials-nnvm-quick-start-py 
- [x] https://docs.tvm.ai/tutorials/nnvm/from_mxnet.html#sphx-glr-tutorials-nnvm-from-mxnet-py 
- [x] https://docs.tvm.ai/tutorials/nnvm/deploy_model_on_rasp.html
- [x] https://docs.tvm.ai/tutorials/nnvm/deploy_model_on_mali_gpu.html
- [x] https://docs.tvm.ai/tutorials/nnvm/using_external_lib.html
- [x] https://docs.tvm.ai/tutorials/nnvm/deploy_ssd.html
- [ ] https://docs.tvm.ai/tutorials/nnvm/from_mxnet_to_webgl.html

Please feel free to claim ones you want to contribute by replying to the thread. Please keep the original author's name while adding your own name if necessary.

**Comment by tqchen** [comment]
cc @merrymercy @jroesch @kazum @ZihengJiang @kevinthesun @phisiart @zhreshold

**Comment by kazum** [comment]
#2688 Relay tutorial for Compile MXNet Models

**Comment by makihiro** [comment]
#2693 PR for "Deploy the Pretrained Model on Raspberry Pi" to use Relay

**Comment by SiNZeRo** [comment]
#2694 
[DOC] Using External Libraries in Relay

**Comment by masahi** [comment]
do we want to keep the original nnvm based tutorials or remove them?

**Comment by tqchen** [comment]
I think both ways are fine(keep vs removing). Once everything is complete in relay. I prefer to start removing some of the nnvm content

**Comment by tqchen** [comment]
Thanks for everyone's effort, we still have two left :)

**Comment by kevinthesun** [comment]
Deploy gluoncv sad with relay: https://github.com/dmlc/tvm/pull/2353

**Comment by Laurawly** [comment]
I can help writing tutorials on other gluoncv models such as Yolo if needed.

**Comment by tqchen** [comment]
Close this PR since most old docs are updated and #2783  New documents are  more than welcomed
