### ISSUE TITLE
GPU for yolov3 issues

### ISSUE THREAD

**Issue by wangnet** [dmlc/tvm#2679]
IN [ Compile YOLO-V2 and YOLO-V3 in DarkNet Models ] Tutorials
When set 
ctx = tvm.cpu(0)  --> ctx = tvm.gpu(0)
will got issue bellow:

File dog.jpg exists, skip.
Running the test image...
Traceback (most recent call last):
  File "test_yolov3.py", line 89, in <module>
    m.run()
  File "/home/ai/big_disk/TVM/tvm/python/tvm/contrib/graph_runtime.py", line 151, in run
    self._run()
  File "/home/ai/big_disk/TVM/tvm/python/tvm/_ffi/_ctypes/function.py", line 185, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/ai/big_disk/TVM/tvm/python/tvm/_ffi/base.py", line 71, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [23:52:46] /home/ai/big_disk/TVM/tvm/src/runtime/module_util.cc:53: Check failed: ret == 0 (-1 vs. 0) Assert fail: (dev_type == 1), device_type need to be 1
PLZ Help to check it~

**Comment by wangnet** [comment]
as just has one GPU , set to 1 also not work

**Comment by wangnet** [comment]
fixed with set 
target = tvm.target.cuda()

**Comment by tqchen** [comment]
Thanks for bringing this up. For future questions, please open new threads in https://discuss.tvm.ai/

**Comment by Rainweic** [comment]
> fixed with set
> target = tvm.target.cuda()

Can you show me the code ?
哥 完整的代码能看看吗
