### ISSUE TITLE
[TVM][ARITH] integer set analysis does not handle Select

### ISSUE THREAD

**Issue by derisavi** [dmlc/tvm#2686]
When faced with `Select` operator, `IntSetEvaluator` will do the default thing which is to return `IntSet::everything()` which is too conservative. 
The right thing to do is to return the union of `IntSet`s of true and false expressions.

**Comment by tqchen** [comment]
This sounds like something we can directly send a patch to fix, we can also consolidate it to #2588 

I have already done so for some of the analysis in #2668

**Comment by derisavi** [comment]
I already have a fix (5 lines of code) for this small bug. I was going to send a PR but I'm open to suggestion on what do with it (or even not to do anything with it and wait for a PR for #2588)
