### ISSUE TITLE
[AUTOTVM] acceptance probability definition

### ISSUE THREAD

**Issue by eqy** [dmlc/tvm#2689]
While looking at the simulated annealing code for AutoTVM, I noticed that we do a minimum with 1 before exponentiating the scaled difference: https://github.com/dmlc/tvm/blob/30242d5c46059939e0327e48fd3a3c6377a637b6/python/tvm/autotvm/tuner/sa_model_optimizer.py#L90. My understanding is that this will cause a "probability" bound of (0, 2.71828] when the following call to `np.random.random` will only generate values in (0, 1). 
I think the minimum has no effect and can just be removed, as `np.random.random` will only generate values in (0, 1) anyway. Similarly, if we switch the order to be min(exp()), the additional operation will not do anything.

CC @merrymercy

**Comment by merrymercy** [comment]
It is used to prevent overflow in `np.exp`.
You can try
```python
np.exp(1/(1e-5))
```
Then you will see the warning.
