### ISSUE TITLE
End to end tutorial for deploying OpenCL to to remote

### ISSUE THREAD

**Issue by TheMartynBliss** [dmlc/tvm#2701]
I am trying to make use of TVM to generate object code that I can run on a target (remote) device. I have been able to do this with a CPU backend but I now want to use OpenCL.

It seems if you generate object files via the build_model.py the opencl kernels are not persisted anywhere, and then when you try and run on device it complains it cannot find the kernels (which seems fair).

How should the kernels be loaded in order to be accessible?

**Comment by tqchen** [comment]
Thanks for bringing this up, We usually use https://discuss.tvm.ai/ for related questions, please open a new thread there

**Comment by tqchen** [comment]
see https://discuss.tvm.ai/t/c-deploy-example-switch-to-opencl/1361/6
