### ISSUE TITLE
[VOTE][COMMUNITY] Nomination Org Principle

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#2717]
Thanks for everyone's participation in discussion of  https://github.com/dmlc/tvm/issues/2663

TVM is a community project, we always put community collaboration at the top of our priority, this is especially true for collaborations with folks who we do not interact daily. I the meanwhile, I do have to admit that have the natural tendency to talk more to our colleagues. 

To further encourage such collaboration and more importantly recognition of community members who are not in our physical circle. We propose to adopt the principle that a PMC member will only nominate candidates from a different organization. This principle will not bar anyone with merit from being nominated(since folks will be nominated by PMC members who are not their colleague at work). It is a principle to encourage folks to interact more with people who are beyond our circles and work together with other folks in the Apache way. Of course, it is by no means a way to prevent all kind of conflict of interest, but it encourages our PMC members to look broadly in the community and bring a better community for everyone.

As you may have noticed in the past community nominations, the current PMC has already done a soft run of this principle in the past five months and it worked quite well. We want to formalize this principle and would like to hear the community’s thoughts on this matter.

This is a voting thread to formally adopt the nomination org principle.

The vote will last for a week and end on Mar 9th. Everyone in the community is welcomed to participate, please vote (by replying to the thread, emoji is also fine but a reply is better):

- +1  if you agree
- +0 if you do not care
- -1  because ...

cc @dmlc/tvm-committer

**Comment by yidawang** [comment]
+1

**Comment by icemelon9** [comment]
+1

**Comment by liangdzou** [comment]
+1

**Comment by Laurawly** [comment]
+1

**Comment by srkreddy1238** [comment]
+1

**Comment by kazum** [comment]
+1

**Comment by vinx13** [comment]
+1

**Comment by Ravenwater** [comment]
+1

**Comment by yzhliu** [comment]
+1

**Comment by tmoreau89** [comment]
+1

**Comment by antinucleon** [comment]
+1

**Comment by makihiro** [comment]
+1

**Comment by ZihengJiang** [comment]
+1

**Comment by tqchen** [comment]
Thanks to everyone's participation, the vote has passed
