### ISSUE TITLE
[RELAY] Tuple causes extra data copy

### ISSUE THREAD

**Issue by lixiaoquan** [dmlc/tvm#2735]
I am implementing a customized relay op which is opaque, I found if a tuple is passed to an opaque op, it may cause extra data copy. Please check this code

```python
from tvm import relay

# Make concatenate opaque just to show the case in which tuple is passed to an opaque op
relay.op._tensor.register_pattern("concatenate", 8, level=15)

input0 = relay.var('input0', shape=(1, 3, 255, 255))
input1 = relay.var('input1', shape=(255, 255, 3, 1))
input1_transposed = relay.transpose(input1, (3, 2, 0, 1))
tensor  = relay.concatenate([input0, input1_transposed], axis=3)

func = relay.Function([input0, input1], tensor)

print(func)

graph, lib, params = relay.build(func, "cuda")

print(lib.imported_modules[0].get_source())
```

relay code is

```c
fn (%input0: Tensor[(1, 3, 255, 255), float32],
    %input1: Tensor[(255, 255, 3, 1), float32])
    -> Tensor[(1, 3, 255, 510), float32] {
  %0 = transpose(%input1, axes=[3, 2, 0, 1]) # ty=Tensor[(1, 3, 255, 255), float32]
  %1 = (%input0, %0)
  %2 = concatenate(%1, axis=3) # ty=Tensor[(1, 3, 255, 510), float32]
  %2
}
```

As you can see, there is *no* need to copy input0 in device side. But it generates 3 kernels and one of which is for copying input0 , I guess this is caused by '%1 = (%input0, %0)'

Could you please point out where should I check to optimize it and avoid this extra copy?

**Comment by vinx13** [comment]
The copy is added in #2537 because current storage planner doesn't support inplace operations. A possible solution is to avoid making the tuple inside subfunction in op fusion, but this prevents fusing concatenate with previous ops.

**Comment by tqchen** [comment]
Please move general discussions to https://discuss.tvm.ai/
