### ISSUE TITLE
how to get muti-output in tvm

### ISSUE THREAD

**Issue by Youjk** [dmlc/tvm#2740]
A Demo: E=A+B,F=E+A, there are two output E、F，and I want to return E、F。so I write a demo like this:
`

    shape = (10,1024)
    A = tvm.placeholder(shape, name="A", dtype="float16")
    B = tvm.placeholder(shape, name="B", dtype="float16")
    E = tvm.compute(A.shape, lambda *index:A(*index)+ B(*index), name = "E")
    F = tvm.compute(E.shape, lambda *index:E(*index)+ B(*index), name = "F")
    sch = tvm.create_schedule([F.op])

    AL = sch.cache_read(A, "local", [E])
    BL = sch.cache_read(B, "local", [E, F])
    EL = sch.cache_write(E, "local")
    FL = sch.cache_write(F, "local")
    with build_config:
        print(tvm.lower(sch, [A, B,E,F], simple_mode=True))
  

`

we will get this IR:
![image](https://user-images.githubusercontent.com/8721085/53926475-87ee0e00-40be-11e9-8cd7-cf8f2f200b4c.png)

we can get output E、F in global, but in produce F.local, it use global var E when compute, but this compute is is in local, if build, will be wrong.

if we add 
`sch[E].compute_inline()`
we will get such IR:
![image](https://user-images.githubusercontent.com/8721085/53926625-267a6f00-40bf-11e9-9107-33649c499e11.png)

this IR , the compute in produce F.local is right, it use all var is in local. but the output E is inline, so we only can get one out F. this is not what we want. 

So how to get the right IR and return muti-output?

**Comment by tqchen** [comment]
Please use https://discuss.tvm.ai/ for  questions

**Comment by merrymercy** [comment]
try 
```
import tvm
shape = (10,1024)
A = tvm.placeholder(shape, name="A", dtype="float16")
B = tvm.placeholder(shape, name="B", dtype="float16")
E = tvm.compute(A.shape, lambda *index:A(*index)+ B(*index), name = "E")
F = tvm.compute(E.shape, lambda *index:E(*index)+ B(*index), name = "F")
sch = tvm.create_schedule([F.op])

AL = sch.cache_read(A, "local", [E])
BL = sch.cache_read(B, "local", [E, F])
EL = sch.cache_write(E, "local")
FL = sch.cache_write(F, "local")

EL_tmp = sch.cache_read(E, 'local', [FL])

print(tvm.lower(sch, [A, B,E,F], simple_mode=True))
```

This can get the correct IR, but there maybe some redundant loads.
