### ISSUE TITLE
[TEST][FLAKY] test_dlpack

### ISSUE THREAD

**Issue by icemelon9** [dmlc/tvm#2750]
Both #2749 and #2353 encountered seg fault error at test_dlpack.
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-2749/2/pipeline
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-2353/48/pipeline

cc @eqy , could you help look at this?

**Comment by eqy** [comment]
I will see if I can repro, otherwise we can thinking about disabling this test for now as it is not a critical part of the infrastructure.

**Comment by eqy** [comment]
@icemelon9 I am not able to reproduce the exact segfault on my machine, but I do see some tolerance errors (maybe ever few hundred invocations). Bumping `rtol` down to `1e-5` seems to be enough on my end---should we submit a PR for that in the meantime?

**Comment by tqchen** [comment]
Should be fixed by https://github.com/dmlc/tvm/pull/2759
