### ISSUE TITLE
[CODEGEN] Enhance OpenCL Generator to Support Conditional Generation that Preserves Type

### ISSUE THREAD

**Issue by lixiaoquan** [dmlc/tvm#2787]
This code (simplified) can't be built with both NV OpenCL and llvm. Error is "error: call to 'max' is ambiguous"
```
   uchar i = 0, j = 0;
   uchar t = max((uchar)j, ((i > 0) ? (uchar)1 : (uchar)0));
```
It seems the type of the ternary operator is not unchar.

My current workaround is to always add a conversion for uint8 before tvm::if_then_else, if you think it's OK, I'll send a PR.

```
diff --git a/tvm/src/codegen/codegen_c.cc b/tvm/src/codegen/codegen_c.cc
index 9b73e4e..3a5357a 100644
--- a/tvm/src/codegen/codegen_c.cc
+++ b/tvm/src/codegen/codegen_c.cc
@@ -524,6 +524,13 @@ void CodeGenC::VisitExpr_(const Call *op, std::ostream& os) {  // NOLINT(*)
   } else if (op->is_intrinsic(Call::shift_right)) {
     PrintBinaryIntrinsitc(op, " >> ", os, this);
   } else if (op->is_intrinsic(intrinsic::tvm_if_then_else)) {
+    // Workaround OpenCL compiler issue
+    // type of ternary expression in NV OpenCL compiler isn't same as type of true/false value
+    if (op->args[2].type() == UInt(8)) {
+      os << "(";
+      PrintType(UInt(8), os);
+      os << ")";
+    }
     os << "(";
     PrintExpr(op->args[0], os);
     os << " ? ";

```

**Comment by tqchen** [comment]
Should we always convert then?

**Comment by lixiaoquan** [comment]
It is in codegen_c, and I haven't found an easy way to distinguish between CUDA and OpenCL.

When the ternary operator is printed, we can't know whether it's a parameter of max().

And this issue should also apply to other functions like min().

Maybe we can override the handling of tvm::if_then_else in CodeGenOpenCL.

Is there any suggestion for an ideal solution?

**Comment by tqchen** [comment]
yes an override is fine you can override codegen of call and then fallback to base
