### ISSUE TITLE
【Docker/SGX】fatal error: inc/stat.h: No such file or directory

### ISSUE THREAD

**Issue by wuzhiyu666** [dmlc/tvm#2790]
When I followed the instruction(https://github.com/dmlc/tvm/tree/master/apps/sgx) to run the SGX demo with docker, I successfully pulled the docker image and entered the container, but when I use the `make -j4` command, I got a fatal error：
`fatal error: inc/stat.h: No such file or directory`
This makes me very confused, what should I do? @tqchen  @nhynes 
Thank you!

**Comment by tqchen** [comment]
Please open a new thread at https://discuss.tvm.ai/

**Comment by nhynes** [comment]
(although discuss.tvm.ai is the correct place for such questions, I'll post the following just in case anyone else looks)

It seems like the [include path](https://github.com/dmlc/tvm/blob/master/apps/sgx/Makefile#L23) isn't being set. Are you sure you used the included `cmake` invocation _exactly_? It should Just Work™. You might have an old version of ci-cpu in your docker cache. Try [clearing it](https://forums.docker.com/t/how-to-delete-cache/5753) and then copy+pasting in the commands. If that doesn't work, please do post on the forums :)

**Comment by wuzhiyu666** [comment]
I have cleaned the cache, but It didn't work, it was still the same error. Moreover, I don't understand what you mean by " included cmake invocation exactly", I have posted my question on https://discuss.tvm.ai/
Thank you so much! @nhynes
