### ISSUE TITLE
[TEST][FLAKY] test_rfactor_argmax

### ISSUE THREAD

**Issue by icemelon9** [dmlc/tvm#2808]
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-2807/1/pipeline

I guess it's because two values are too close. Might be fixed by setting a random seed.

**Comment by tqchen** [comment]
cc @sxjscience can you take a look?

**Comment by sxjscience** [comment]
Yes, I'll take a look.

**Comment by tqchen** [comment]
This flaky was a bit inactive and could be fixed by https://github.com/dmlc/tvm/issues/2767, close for now
