### ISSUE TITLE
[DOCKER] ubuntu_install_tflite.sh flatbuffers build failure

### ISSUE THREAD

**Issue by mjs-arm** [dmlc/tvm#2823]
Since 14/3/2019 ubuntu_install_tflite.sh fails due to build failure in flatbuffers.

The ubuntu_install_tflite.sh script checkouts out the head of flatbuffers and tries to build it.  Upstream flatbuffers commit: 3b23ff18ea27c6cac33c8211d405d57d4595db1a  "Made ToStringVisitor backwards compatible with older behavior." triggers the following build error:

/flatbuffers/include/flatbuffers/minireflect.h:293:7: error: declaration of 'vector_delimited' shadows a member of 'flatbuffers::ToStringVisitor' [-Werror=shadow]

The build error itself is an issue with the upstream project but the important underlying issue for TVM is that the ubutnu_install_tflite.sh script is tracking the bleeding edge of flatbuffers rather than pulling and building a known fixed version of flatbuffers.  This means tvm rebuilds of the build infrastructure docker images are not repeatable / subject to arbitrary failure.

**Comment by mjs-arm** [comment]
https://github.com/google/flatbuffers/issues/5238

**Comment by kentkolze** [comment]
Ah. Is there a known fixed version commit I could checkout in order to get a build working?

**Comment by tqchen** [comment]
cc @FrozenGene let us change the build script to use a stable version.

**Comment by mjs-arm** [comment]
The last tagged release is tagged v1.10.0 it dates back to Oct 2018 (flat buffers appears to do a release tag about every 6 months).  I can prep a patch to pin to v1.10.0

**Comment by srkreddy1238** [comment]
@mjs-arm this issue look resolved. Can we close ?
