### ISSUE TITLE
[RFC] Meta RFC: Use Github PR to do RFC

### ISSUE THREAD

**Issue by jroesch** [dmlc/tvm#2837]
As we move closer to being an Apache project I think we should consider updating some of our workflows to help increase discoverability and access to RFCs.

In the past I have been an active contributor to the Rust project which has a great system for managing and displaying RFCs. Instead of merely posting RFCs as issues, they keep a separate repo where RFCs are numbered and stored, see https://github.com/rust-lang/rfcs.

They also provided a nicely rendered view: https://rust-lang.github.io/rfcs/.

In this approach accepted RFCs are committed to the repo and their history and evolution stored. 

For example this also allows us to use the Github PR tools, including suggestions and in-context discussion threads to improve the RFCs. We can also have a more formal notion of approval, for example when a vote has been called, or we reach informal consensus we can merge the PR. If we decide not to pursue a direction we can either reject or mark as postponed. 

Overall I think this is superior to using issues for RFCs and allows us to keep history about when/where they are merged and allow people to view the history of the project without having to go looking through issues.

**Comment by tqchen** [comment]
Overall there is a tradeoff between the agile development and how many steps we need create to introduce this process. This could be something that we eventually want, but I am not sure if it is something we want to do right now, would also love to see everyone's thoughts.

If we decide to adopt the new approach, I think the best time would be after a major release cycle. Apache's requirement is that everything should also be mirrored to dev@, which is doable as long as we mirror all the issues and discuss into the list.

**Comment by junrushao1994** [comment]
> Instead of merely posting RFCs as issues, they keep a separate repo where RFCs are numbered and stored, see https://github.com/rust-lang/rfcs.

I feel that we could do this automatically using some kind of bot. Just post everything in GitHub issues in some predefined format, and ask the bot to archive it, or post it to dev@.

**Comment by yzhliu** [comment]
my +0.6

@junrushao1994 I actually feel the most attractive feature is the ability to let people provide in-context suggestions.

While I also worry it might make process a little bit too heavy.

**Comment by jroesch** [comment]
I agree it does add more process, but my feeling is we should be using RFCs for large features that are more process heavy anyways. 

I have been writing 3-4 RFCs with different people the past few weeks and it is very hard to collaboratively iterate on RFCs right now. For example only people who are committer or above can directly edit other's issues and there are no tools for drafting or line specific suggestions or feedback. 

In the Rust world the RFCs are often iterated on by quite a few people and it generally improves the writing quality of the RFC, as well as incidentally providing documentation. Documentation is another motivation of mine, as often new features are shipped with relatively low text describing their design and implementation. More polished RFCs provide a path to generating more documentation for new features.

**Comment by ehsanmok** [comment]
+1 I've also suggested the same [here](https://github.com/dmlc/tvm/issues/2523#issuecomment-459825186) and current some RFCs are not really RFCs in a sense that they don't offer major features etc. I really think, the process should be defined more succinctly. Archiving them is really valuable for current and future contributors as well.

**Comment by tqchen** [comment]
To summarize the conclusion so far, folks agreed that this could be useful for formalism and the only question is when to adopt this. Given the inactive status of this RFC, we will close this for now, and revisit when we find the need
