### ISSUE TITLE
[TEST][FLAKY][NVPTX]  test_topi_conv2d_nchw.test_conv2d_nchw

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#2845]
- http://ci.tvm.ai:8080/blue/rest/organizations/jenkins/pipelines/tvm/branches/PR-2841/runs/1/nodes/235/log/?start=0
- http://ci.tvm.ai:8080/blue/rest/organizations/jenkins/pipelines/tvm/branches/PR-2844/runs/1/nodes/235/log/?start=0

This error also only happens when we introduced the new CI node with Titan X(pascal). Seems only happens in NVPTX, one possibility is too big workloads.

cc @masahi @Laurawly can you take a look?

**Comment by tqchen** [comment]
cc @icemelon9

**Comment by masahi** [comment]
ok

**Comment by masahi** [comment]
I can't reproduce this on GTX 1070 ti + LLVM 6.0. All tests pass on my box. 

We had a similar issue when AutoTVM for GPU was introduced (see [here](https://github.com/dmlc/tvm/pull/1638#issuecomment-418557935)). Some tests failed only on NVPTX, so they are [disabled](https://github.com/dmlc/tvm/blob/master/topi/tests/python/test_topi_conv2d_nchw.py#L109).
