### ISSUE TITLE
Parsing error, when I install tvmrpc-release.apk in my android phone.

### ISSUE THREAD

**Issue by WadeWuu** [dmlc/tvm#2871]
I have not modifyied the tvm4j dependency declare in app/build.gradle. I just use gradle to build directly. I built successfully.    
![image](https://user-images.githubusercontent.com/35893383/54754244-05b52c00-4c1e-11e9-943a-20056ed48673.png)

And then I dev_tools/gen_keystore.sh and dev_tools/sign_apk.sh to get the tvmrpc-release.apk.

However, when I install tvmrpc-release.apk in my android phone, it occurs the Parsing error：Problems in parsing software packages.

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/
