### ISSUE TITLE
[USE] errors when using tvm c++: fatal error: dmlc/io.h: No such file or directory

### ISSUE THREAD

**Issue by jinfagang** [dmlc/tvm#2876]
Obviously, this is a lacking of that package, but there is no where for users to no which this files comes from and install which package. Would it be better to add it as third party? 

```
/usr/local/include/tvm/runtime/module.h:11:21: fatal error: dmlc/io.h: No such file or directory
 #include <dmlc/io.h>
                     ^
```

**Comment by srkreddy1238** [comment]
@jinfagang  
Did you use ```--recursive``` while git clone ?

BTW, you may rise these general issues @ https://discuss.tvm.ai/

**Comment by canyilmaz90** [comment]
@jinfagang did you manage to solve this? I'm facing the same error, but when I check, there is 'module.h' in the included directory!

**Comment by temofy** [comment]
You can solve this problem by building the cmake projects 3rdparty/dmlc and then 3rdparty/dlpack and doing a make install for each, then these headers will be in the system paths

**Comment by jonnyjohnson1** [comment]
New to this issue...

To install, the command `make install`  doesn't seem to work. I see there is the CMakeLists.txt file, and it is the CMake I am new to...

Do I have to make install each by using some kind of CMake install (different than Makefile's `make install`)?

I see this example here: https://stackoverflow.com/questions/48428647/how-to-use-cmake-to-install.

What would I do to install the dmlc project specifically as an example?
