### ISSUE TITLE
[RUNTIME][OPENCL] Make OpenCL runtime Compatible with OpenCL2.0

### ISSUE THREAD

**Issue by mjs-arm** [dmlc/tvm#2897]
Build opencl fails with:

tvm/src/runtime/opencl/opencl_device_api.cc:278:9: error: ‘_cl_command_queue* clCreateCommandQueue(cl_context, cl_device_id, cl_command_queue_properties, cl_int*)’ is deprecated [-Werror=deprecated-declarations]

The clCreateCommandQueue API is deprecated in OpenCL2.0.

Possible solutions:

1) Switch to clCreateCommandQueueWithProperties

2) Define  either we need to:
#define CL_USE_DEPRECATED_OPENCL_1_2_APIS  prior to the inclusion of cl.h

**Comment by tqchen** [comment]
cc @kazum , likely we can detect the OpenCL version in macro and use the new API(it is not yet available in old version of the API).

**Comment by kazum** [comment]
I think we cannot detect the OpenCL version statically - we need to query it with the OpenCL APIs.  Maybe, it's possible to detect the version in cmake and define an appropriate macro.

Anyway, there are still many OpenCL platforms which doesn't support OpenCL 2.0.  Defining CL_USE_DEPRECATED_OPENCL_1_2_APIS looks good for now.

**Comment by tqchen** [comment]
By search around i have found ```__OPENCL_VERSION__ ```, not sure if it is part of standnard

**Comment by kazum** [comment]
Is `__OPENCL_VERSION__` only available in OpenCL kernel code?  https://www.khronos.org/registry/OpenCL/sdk/2.1/docs/man/xhtml/preprocessorDirectives.html

I searched the macro in the official OpenCL headers (https://github.com/KhronosGroup/OpenCL-Headers), but couldn't find it.  Even if it is defined there, the supported OpenCL version is up to the target device, IIUC.

**Comment by tqchen** [comment]
OK, perhaps we can define the backward compatible flag for now then

**Comment by mjs-arm** [comment]
Resolved by #2950
