### ISSUE TITLE
[Relay][OP] Add comparison operator overloading

### ISSUE THREAD

**Issue by haojin2** [dmlc/tvm#2910]
Environment: Ubuntu 18.04
Python Version: Python 3.6.7
Minimal Reproduction Script:
```Python
from tvm import relay
a = relay.Var("a")
b = relay.expr.const(1.0, dtype='float32')
c = a < b
```
Error:
```
TypeError: '<' not supported between instances of 'Var' and 'Constant'
```

**Comment by u99127** [comment]
Probably a dumb question, but is c = a < b the same as using of c = relay.less_equal (a, b); ?

**Comment by u99127** [comment]
Now merged, I suspect closed by the commit.
