### ISSUE TITLE
a bug about compute_inline

### ISSUE THREAD

**Issue by Youjk** [dmlc/tvm#2912]
case:
`    

    A = tvm.placeholder(shape, name="A", dtype=inp_dtype)
    B = tvm.placeholder(shape, name="B", dtype=inp_dtype)
    C = tvm.compute(A.shape, lambda *index:A(*index)+ B(*index), name = "C")
    def _compute(*index) :
        return C(*index) * B(*index), C(*index) + B(*index)
    F,E = tvm.compute(A.shape, _compute, name = "F")
    sch = tvm.create_schedule([F.op, E.op])
    AL = sch.cache_read(A, 'local', [C])
    BL = sch.cache_read(B, 'local', [C,E])
    CL = sch.cache_write(C, 'local')
    FL, EL = sch.cache_write([F, E], 'local')

    sch[C].compute_inline()

    tvm.build(sch, [A, B,E,F], "llvm", name="test")`

when compute in a group andcompute_inline。run this case will wrong：
`bound.cc:135: Check failed: it != rmap->end()`

review the source code in schedule_dataflow_rewrite.cc, the line 606 :s->op = op should be out of the for like this:
     
```
   if (!op.same_as(s->op)) {
      for (int idx = 0; idx < s->op->num_outputs(); ++idx) {
        repl[s->op.output(idx)] = op.output(idx);
      }
      s->op = op;
    }
```
then this case will be right. is this a bug about comput in a group and compute_inline

**Comment by merrymercy** [comment]
Could you send a patch?
