### ISSUE TITLE
issues with deploy_ssd_gluoncv.py

### ISSUE THREAD

**Issue by kaishijeng** [dmlc/tvm#2918]
2 issues with deploy_ssd_gluoncv.py: 

1) ssd_512_resnet18_v1_voc doesn't exist in the model zoo
2) Run time for ssd_512_mobilenet1.0_voc is very slow compared with mxnet framework for model on rk3399 platform:

tvm: 1.5sec
mxnet: 40ms

Any idea why there is such a big gap of inference time?

**Comment by tqchen** [comment]
Please open a new thread in discuss.tvm.ai
