### ISSUE TITLE
TVM on yocto

### ISSUE THREAD

**Issue by peter197321** [dmlc/tvm#2920]
is there a possiblity to have TVM on Yocto Linux? Does it make sense? or any plan for it?

**Comment by tqchen** [comment]
Please open a new thread in discuss.tvm.ai

**Comment by fzi-peccia** [comment]
I found [this](https://github.com/t-kuha/recipes-ml/blob/2022.2/python-tvm/python-tvm.bb) bitbake recipes which add the TVM runtime, I used it to add TVM to a Yocto Linux, and its working fine.
