### ISSUE TITLE
[Relay][RFC] FuseOps and Tuple

### ISSUE THREAD

**Issue by MarisaKirisame** [dmlc/tvm#2931]
After some consideration I think #2914 is not the best way to support tuple in fusion. 
0: it could handle tuple of tuple, it is the relay interpreter that is incorrect (it didnot recursively fset, but instead assume it is either tensor or tuple of tensor).
1: it should not care about reference at all!
as operator accept recursive tuple of tensor, if there is reference in the code, it will never become a tensor (except by function call, or refget). the correct place to catch for reference, is at refget/forigen function call, and not a tensor.

**Comment by MarisaKirisame** [comment]
@masahi @tqchen

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/issues/3039
