### ISSUE TITLE
Operator: _arange is not supported in nnvm   [gluoncv yolov3 into tvm]

### ISSUE THREAD

**Issue by wangshankun** [dmlc/tvm#2948]
Failed to convert gluoncv yolov3 into tvm

  File "/home/lhy/Documents/Lib/tvm/nnvm/python/nnvm/frontend/mxnet.py", line 527, in from_mxnet
    sym = _from_mxnet_impl(symbol, {})
  File "/home/lhy/Documents/Lib/tvm/nnvm/python/nnvm/frontend/mxnet.py", line 486, in _from_mxnet_impl
    node = _convert_symbol(op_name, [], attr)
  File "/home/lhy/Documents/Lib/tvm/nnvm/python/nnvm/frontend/mxnet.py", line 392, in _convert_symbol
    _raise_not_supported('Operator: ' + op_name)
  File "/home/lhy/Documents/Lib/tvm/nnvm/python/nnvm/frontend/mxnet.py", line 24, in _raise_not_supported
    raise NotImplementedError(err)
NotImplementedError: Operator: _arange is not supported in nnvm.

https://discuss.tvm.ai/t/failed-to-convert-gluoncv-yolov3-into-tvm/1475

**Comment by icemelon9** [comment]
`_arange` op is already supported in the Relay MxNet frontend converter.
At this time, we encourage you to use Relay to convert models as new operators will be first supported in Relay. We also welcome you and community to add support for `_arange` in NNVM.

**Comment by wangshankun** [comment]
> `_arange` op is already supported in the Relay MxNet frontend converter.
> At this time, we encourage you to use Relay to convert models as new operators will be first supported in Relay. We also welcome you and community to add support for `_arange` in NNVM.

**relay  is not good either**

alibaba@firefly:~/tvm_demo$ python dp_relay_yolov3.py
Shape of pre-processed image: (1, 3, 512, 683)
Traceback (most recent call last):
  File "dp_relay_yolov3.py", line 26, in <module>
    func, params = relay.frontend.from_mxnet(sym, shape_dict)
  File "/home/alibaba/tvm/python/tvm/relay/frontend/mxnet.py", line 602, in from_mxnet
    sym = _from_mxnet_impl(symbol, shape, dtype)
  File "/home/alibaba/tvm/python/tvm/relay/frontend/mxnet.py", line 521, in _from_mxnet_impl
    res = _convert_map[op_name](children, attrs)
  File "/home/alibaba/tvm/python/tvm/relay/frontend/mxnet.py", line 199, in _mx_slice_axis
    shape = ir_pass.infer_type(inputs[0]).checked_type.shape
  File "/home/alibaba/tvm/python/tvm/relay/ir_pass.py", line 45, in infer_type
    return _ir_pass.infer_type(expr, mod)
  File "/home/alibaba/tvm/python/tvm/_ffi/_ctypes/function.py", line 185, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/alibaba/tvm/python/tvm/_ffi/base.py", line 71, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [11:26:16] /home/alibaba/tvm/src/relay/pass/type_infer.cc:620: Check failed: checked_type.as<IncompleteTypeNode>() == nullptr Cannot resolve type of CallNode(Op(reshape), [CallNode(Op(transpose), [CallNode(Op(reshape), [CallNode(Op(nn.bias_add), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.leaky_relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.leaky_relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.leaky_relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.leaky_relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.leaky_relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.leaky_relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(nn.relu), [TupleGetItemNode(CallNode(Op(nn.batch_norm), [CallNode(Op(nn.conv2d), [CallNode(Op(transpose), [CallNode(Op(divide), [CallNode(Op(subtract), [Var(data, ty=TensorType([1, 3, 512, 683], float32)), Var(_defaultpreprocess0_init_mean)], (nullptr), []), Var(_defaultpreprocess0_init_scale)], (nullptr), [])], relay.attrs.TransposeAttrs(0x2d6012b0), []), Var(mobilenet0_conv0_weight)], relay.attrs.Conv2DAttrs(0x27508400), []), Var(mobilenet0_batchnorm0_gamma), Var(mobilenet0_batchnorm0_beta), Var(mobilenet0_batchnorm0_running_mean), Var(mobilenet0_batchnorm0_running_var)], relay.attrs.BatchNormAttrs(0x2d5fdfc0), []), 0)], (nullptr), []), Var(mobilenet0_conv1_weight)], relay.attrs.Conv2DAttrs(0x27424340), []), Var(mobilenet0_batchnorm1_gamma), Var(mobilenet0_batchnorm1_beta), Var(mobilenet0_batchnorm1_running_mean), Var(mobilenet0_batchnorm1_running_var)], relay.attrs.BatchNormAttrs(0x287bfc00), []), 0)], (nullptr), []), Var(mobilenet0_conv2_weight)], relay.attrs.Conv2DAttrs(0x265390b0), []), Var(mobilenet0_batchnorm2_gamma), Var(mobilenet0_batchnorm2_beta), Var(mobilenet0_batchnorm2_running_mean), Var(mobilenet0_batchnorm2_running_var)], relay.attrs.BatchNormAttrs(0x2d601fb0), []), 0)], (nullptr), []), Var(mobilenet0_conv3_weight)], relay.attrs.Conv2DAttrs(0x26524f90), []), Var(mobilenet0_batchnorm3_gamma), Var(mobilenet0_batchnorm3_beta), Var(mobilenet0_batchnorm3_running_mean), Var(mobilenet0_batchnorm3_running_var)], relay.attrs.BatchNormAttrs(0x2d602ba0), []), 0)], (nullptr), []), Var(mobilenet0_conv4_weight)], relay.attrs.Conv2DAttrs(0x26510320), []), Var(mobilenet0_batchnorm4_gamma), Var(mobilenet0_batchnorm4_beta), Var(mobilenet0_batchnorm4_running_mean), Var(mobilenet0_batchnorm4_running_var)], relay.attrs.BatchNormAttrs(0x2d6011e0), []), 0)], (nullptr), []), Var(mobilenet0_conv5_weight)], relay.attrs.Conv2DAttrs(0x26523900), []), Var(mobilenet0_batchnorm5_gamma), Var(mobilenet0_batchnorm5_beta), Var(mobilenet0_batchnorm5_running_mean), Var(mobilenet0_batchnorm5_running_var)], relay.attrs.BatchNormAttrs(0x283bbe90), []), 0)], (nullptr), []), Var(mobilenet0_conv6_weight)], relay.attrs.Conv2DAttrs(0x2650bad0), []), Var(mobilenet0_batchnorm6_gamma), Var(mobilenet0_batchnorm6_beta), Var(mobilenet0_batchnorm6_running_mean), Var(mobilenet0_batchnorm6_running_var)], relay.attrs.BatchNormAttrs(0x2d604bd0), []), 0)], (nullptr), []), Var(mobilenet0_conv7_weight)], relay.attrs.Conv2DAttrs(0x2d605230), []), Var(mobilenet0_batchnorm7_gamma), Var(mobilenet0_batchnorm7_beta), Var(mobilenet0_batchnorm7_running_mean), Var(mobilenet0_batchnorm7_running_var)], relay.attrs.BatchNormAttrs(0x2d605650), []), 0)], (nullptr), []), Var(mobilenet0_conv8_weight)], relay.attrs.Conv2DAttrs(0x2d605cb0), []), Var(mobilenet0_batchnorm8_gamma), Var(mobilenet0_batchnorm8_beta), Var(mobilenet0_batchnorm8_running_mean), Var(mobilenet0_batchnorm8_running_var)], relay.attrs.BatchNormAttrs(0x2d6060d0), []), 0)], (nullptr), []), Var(mobilenet0_conv9_weight)], relay.attrs.Conv2DAttrs(0x2d606730), []), Var(mobilenet0_batchnorm9_gamma), Var(mobilenet0_batchnorm9_beta), Var(mobilenet0_batchnorm9_running_mean), Var(mobilenet0_batchnorm9_running_var)], relay.attrs.BatchNormAttrs(0x2d606b50), []), 0)], (nullptr), []), Var(mobilenet0_conv10_weight)], relay.attrs.Conv2DAttrs(0x2d603a20), []), Var(mobilenet0_batchnorm10_gamma), Var(mobilenet0_batchnorm10_beta), Var(mobilenet0_batchnorm10_running_mean), Var(mobilenet0_batchnorm10_running_var)], relay.attrs.BatchNormAttrs(0x2d603e70), []), 0)], (nullptr), []), Var(mobilenet0_conv11_weight)], relay.attrs.Conv2DAttrs(0x2d6085f0), []), Var(mobilenet0_batchnorm11_gamma), Var(mobilenet0_batchnorm11_beta), Var(mobilenet0_batchnorm11_running_mean), Var(mobilenet0_batchnorm11_running_var)], relay.attrs.BatchNormAttrs(0x2d608a40), []), 0)], (nullptr), []), Var(mobilenet0_conv12_weight)], relay.attrs.Conv2DAttrs(0x2d6090a0), []), Var(mobilenet0_batchnorm12_gamma), Var(mobilenet0_batchnorm12_beta), Var(mobilenet0_batchnorm12_running_mean), Var(mobilenet0_batchnorm12_running_var)], relay.attrs.BatchNormAttrs(0x2d6094f0), []), 0)], (nullptr), []), Var(mobilenet0_conv13_weight)], relay.attrs.Conv2DAttrs(0x2d609b50), []), Var(mobilenet0_batchnorm13_gamma), Var(mobilenet0_batchnorm13_beta), Var(mobilenet0_batchnorm13_running_mean), Var(mobilenet0_batchnorm13_running_var)], relay.attrs.BatchNormAttrs(0x2d609fa0), []), 0)], (nullptr), []), Var(mobilenet0_conv14_weight)], relay.attrs.Conv2DAttrs(0x2d60a600), []), Var(mobilenet0_batchnorm14_gamma), Var(mobilenet0_batchnorm14_beta), Var(mobilenet0_batchnorm14_running_mean), Var(mobilenet0_batchnorm14_running_var)], relay.attrs.BatchNormAttrs(0x2d60aa50), []), 0)], (nullptr), []), Var(mobilenet0_conv15_weight)], relay.attrs.Conv2DAttrs(0x2d60b0b0), []), Var(mobilenet0_batchnorm15_gamma), Var(mobilenet0_batchnorm15_beta), Var(mobilenet0_batchnorm15_running_mean), Var(mobilenet0_batchnorm15_running_var)], relay.attrs.BatchNormAttrs(0x2d60b500), []), 0)], (nullptr), []), Var(mobilenet0_conv16_weight)], relay.attrs.Conv2DAttrs(0x2d60bb60), []), Var(mobilenet0_batchnorm16_gamma), Var(mobilenet0_batchnorm16_beta), Var(mobilenet0_batchnorm16_running_mean), Var(mobilenet0_batchnorm16_running_var)], relay.attrs.BatchNormAttrs(0x2d60bfb0), []), 0)], (nullptr), []), Var(mobilenet0_conv17_weight)], relay.attrs.Conv2DAttrs(0x2d60c610), []), Var(mobilenet0_batchnorm17_gamma), Var(mobilenet0_batchnorm17_beta), Var(mobilenet0_batchnorm17_running_mean), Var(mobilenet0_batchnorm17_running_var)], relay.attrs.BatchNormAttrs(0x2d60ca60), []), 0)], (nullptr), []), Var(mobilenet0_conv18_weight)], relay.attrs.Conv2DAttrs(0x2d60d0c0), []), Var(mobilenet0_batchnorm18_gamma), Var(mobilenet0_batchnorm18_beta), Var(mobilenet0_batchnorm18_running_mean), Var(mobilenet0_batchnorm18_running_var)], relay.attrs.BatchNormAttrs(0x2d60d510), []), 0)], (nullptr), []), Var(mobilenet0_conv19_weight)], relay.attrs.Conv2DAttrs(0x2d60db70), []), Var(mobilenet0_batchnorm19_gamma), Var(mobilenet0_batchnorm19_beta), Var(mobilenet0_batchnorm19_running_mean), Var(mobilenet0_batchnorm19_running_var)], relay.attrs.BatchNormAttrs(0x2d60dfc0), []), 0)], (nullptr), []), Var(mobilenet0_conv20_weight)], relay.attrs.Conv2DAttrs(0x2d60e700), []), Var(mobilenet0_batchnorm20_gamma), Var(mobilenet0_batchnorm20_beta), Var(mobilenet0_batchnorm20_running_mean), Var(mobilenet0_batchnorm20_running_var)], relay.attrs.BatchNormAttrs(0x2d610f80), []), 0)], (nullptr), []), Var(mobilenet0_conv21_weight)], relay.attrs.Conv2DAttrs(0x2d607400), []), Var(mobilenet0_batchnorm21_gamma), Var(mobilenet0_batchnorm21_beta), Var(mobilenet0_batchnorm21_running_mean), Var(mobilenet0_batchnorm21_running_var)], relay.attrs.BatchNormAttrs(0x2d607850), []), 0)], (nullptr), []), Var(mobilenet0_conv22_weight)], relay.attrs.Conv2DAttrs(0x2d611e40), []), Var(mobilenet0_batchnorm22_gamma), Var(mobilenet0_batchnorm22_beta), Var(mobilenet0_batchnorm22_running_mean), Var(mobilenet0_batchnorm22_running_var)], relay.attrs.BatchNormAttrs(0x2d612290), []), 0)], (nullptr), []), Var(mobilenet0_conv23_weight)], relay.attrs.Conv2DAttrs(0x2d612a90), []), Var(mobilenet0_batchnorm23_gamma), Var(mobilenet0_batchnorm23_beta), Var(mobilenet0_batchnorm23_running_mean), Var(mobilenet0_batchnorm23_running_var)], relay.attrs.BatchNormAttrs(0x2d612ee0), []), 0)], (nullptr), []), Var(mobilenet0_conv24_weight)], relay.attrs.Conv2DAttrs(0x2d613700), []), Var(mobilenet0_batchnorm24_gamma), Var(mobilenet0_batchnorm24_beta), Var(mobilenet0_batchnorm24_running_mean), Var(mobilenet0_batchnorm24_running_var)], relay.attrs.BatchNormAttrs(0x2d613b50), []), 0)], (nullptr), []), Var(mobilenet0_conv25_weight)], relay.attrs.Conv2DAttrs(0x2d614370), []), Var(mobilenet0_batchnorm25_gamma), Var(mobilenet0_batchnorm25_beta), Var(mobilenet0_batchnorm25_running_mean), Var(mobilenet0_batchnorm25_running_var)], relay.attrs.BatchNormAttrs(0x2d6147c0), []), 0)], (nullptr), []), Var(mobilenet0_conv26_weight)], relay.attrs.Conv2DAttrs(0x2d614fe0), []), Var(mobilenet0_batchnorm26_gamma), Var(mobilenet0_batchnorm26_beta), Var(mobilenet0_batchnorm26_running_mean), Var(mobilenet0_batchnorm26_running_var)], relay.attrs.BatchNormAttrs(0x2d615430), []), 0)], (nullptr), []), Var(yolov30_yolodetectionblockv30_conv0_weight)], relay.attrs.Conv2DAttrs(0x2d615c90), []), Var(yolov30_yolodetectionblockv30_batchnorm0_gamma), Var(yolov30_yolodetectionblockv30_batchnorm0_beta), Var(yolov30_yolodetectionblockv30_batchnorm0_running_mean), Var(yolov30_yolodetectionblockv30_batchnorm0_running_var)], relay.attrs.BatchNormAttrs(0x2d616120), []), 0)], relay.attrs.LeakyReluAttrs(0x2d6154f0), []), Var(yolov30_yolodetectionblockv30_conv1_weight)], relay.attrs.Conv2DAttrs(0x2d616b80), []), Var(yolov30_yolodetectionblockv30_batchnorm1_gamma), Var(yolov30_yolodetectionblockv30_batchnorm1_beta), Var(yolov30_yolodetectionblockv30_batchnorm1_running_mean), Var(yolov30_yolodetectionblockv30_batchnorm1_running_var)], relay.attrs.BatchNormAttrs(0x2d617010), []), 0)], relay.attrs.LeakyReluAttrs(0x2d6170d0), []), Var(yolov30_yolodetectionblockv30_conv2_weight)], relay.attrs.Conv2DAttrs(0x2d617870), []), Var(yolov30_yolodetectionblockv30_batchnorm2_gamma), Var(yolov30_yolodetectionblockv30_batchnorm2_beta), Var(yolov30_yolodetectionblockv30_batchnorm2_running_mean), Var(yolov30_yolodetectionblockv30_batchnorm2_running_var)], relay.attrs.BatchNormAttrs(0x2d617d00), []), 0)], relay.attrs.LeakyReluAttrs(0x2d617dc0), []), Var(yolov30_yolodetectionblockv30_conv3_weight)], relay.attrs.Conv2DAttrs(0x2d618790), []), Var(yolov30_yolodetectionblockv30_batchnorm3_gamma), Var(yolov30_yolodetectionblockv30_batchnorm3_beta), Var(yolov30_yolodetectionblockv30_batchnorm3_running_mean), Var(yolov30_yolodetectionblockv30_batchnorm3_running_var)], relay.attrs.BatchNormAttrs(0x2d618c20), []), 0)], relay.attrs.LeakyReluAttrs(0x2d618ce0), []), Var(yolov30_yolodetectionblockv30_conv4_weight)], relay.attrs.Conv2DAttrs(0x2d619480), []), Var(yolov30_yolodetectionblockv30_batchnorm4_gamma), Var(yolov30_yolodetectionblockv30_batchnorm4_beta), Var(yolov30_yolodetectionblockv30_batchnorm4_running_mean), Var(yolov30_yolodetectionblockv30_batchnorm4_running_var)], relay.attrs.BatchNormAttrs(0x2d619910), []), 0)], relay.attrs.LeakyReluAttrs(0x2d6199d0), []), Var(yolov30_yolodetectionblockv30_conv5_weight)], relay.attrs.Conv2DAttrs(0x2d61a170), []), Var(yolov30_yolodetectionblockv30_batchnorm5_gamma), Var(yolov30_yolodetectionblockv30_batchnorm5_beta), Var(yolov30_yolodetectionblockv30_batchnorm5_running_mean), Var(yolov30_yolodetectionblockv30_batchnorm5_running_var)], relay.attrs.BatchNormAttrs(0x2d61a600), []), 0)], relay.attrs.LeakyReluAttrs(0x2d61a6c0), []), Var(yolov30_yolooutputv30_conv0_weight)], relay.attrs.Conv2DAttrs(0x2d61af20), []), Var(yolov30_yolooutputv30_conv0_bias)], relay.attrs.BiasAddAttrs(0x2d61b9f0), [])], relay.attrs.ReshapeAttrs(0x2d61be10), [])], relay.attrs.TransposeAttrs(0x2d61c080), [])], relay.attrs.ReshapeAttrs(0x2d61c580), []) at (nullptr)

Stack trace returned 10 entries:
[bt] (0) /home/alibaba/tvm/build/libtvm.so(+0x128984) [0x7f8a989984]
[bt] (1) /home/alibaba/tvm/build/libtvm.so(+0x129190) [0x7f8a98a190]
[bt] (2) /home/alibaba/tvm/build/libtvm.so(+0x6129a0) [0x7f8ae739a0]
[bt] (3) /home/alibaba/tvm/build/libtvm.so(+0x612e48) [0x7f8ae73e48]
[bt] (4) /home/alibaba/tvm/build/libtvm.so(+0x46ed3c) [0x7f8accfd3c]
[bt] (5) /home/alibaba/tvm/build/libtvm.so(+0x4702a4) [0x7f8acd12a4]
[bt] (6) /home/alibaba/tvm/build/libtvm.so(+0x46ba7c) [0x7f8accca7c]
[bt] (7) /home/alibaba/tvm/build/libtvm.so(+0x46ac90) [0x7f8accbc90]
[bt] (8) /home/alibaba/tvm/build/libtvm.so(+0x613000) [0x7f8ae74000]
[bt] (9) /home/alibaba/tvm/build/libtvm.so(+0x6134b8) [0x7f8ae744b8]

**Comment by junrushao1994** [comment]
@icemelon9 I suppose we should open a new thread on https://discuss.tvm.ai/ ?
