### ISSUE TITLE
download_testdata Error in Tutorial Examples

### ISSUE THREAD

**Issue by mostafaelhoushi** [dmlc/tvm#2953]
When running many of the Frontend examples in the [Frontend section of the Tutorial](https://docs.tvm.ai/tutorials/frontend/), e.g.: 
https://docs.tvm.ai/tutorials/frontend/from_onnx.html

I get the following error:
```
$ python from_onnx.py
Traceback (most recent call last):
  File "from_onnx.py", line 23, in <module>
    from tvm.contrib.download import download_testdata
ImportError: cannot import name download_testdata
```

I am using Ubuntu 16.04, and built TVM using LLVM and CUDA set.

**Comment by icemelon9** [comment]
Could you checkout the latest tvm repo? `download_testdata` is added in recent commits (#2921 ).

**Comment by mostafaelhoushi** [comment]
Thanks! Now it seems to be working fine
