### ISSUE TITLE
[Relay][API] Rename RelayPrint to AsText

### ISSUE THREAD

**Issue by jroesch** [dmlc/tvm#2955]
We currently have different names for the C++ printing routine and the Python printing routine. We should rename them for consistency sake. 

See: https://discuss.tvm.ai/t/define-neural-network-in-c-and-print-its-ssa-ir/2078/3

**Comment by jroesch** [comment]
cc @joshpoll @tqchen

**Comment by tqchen** [comment]
+1

**Comment by yzhliu** [comment]
+1

**Comment by joshpoll** [comment]
+1

**Comment by tqchen** [comment]
BTW, for design discussions, please tag with RFC or DEV prefix, so it will be mirrored to dev@apache see https://github.com/dmlc/tvm/issues/2907
