### ISSUE TITLE
Does TVM support model convert from thinc ?

### ISSUE THREAD

**Issue by gitathrun** [dmlc/tvm#2963]
I know thinc is not the main stream DL framework, but its execution efficiency is fairly quick and numpy and chainer based, is it possible to the support from TVM later? or any possible solution/approach to get support from TVM?

**Comment by tqchen** [comment]
This is a topic that should be discussed in https://discuss.tvm.ai/

**Comment by junrushao1994** [comment]
SpaCy uses thinc, which makes it vital for preprocessing texts. Should be important when it comes to data pipeline but not model itself. Again, for general questions, let’s discuss on the forum
