### ISSUE TITLE
[VOTE] Apache Transition Plan

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#2973]
TVM has been transitioned to Apache, following our traditional as well as Apache’s, major decisions about community will result in a VOTE. Everyone in the community is welcomed to participate. This is the first voting thread after TVM get into Apache. See also background in [Apache Transition Plan](https://github.com/dmlc/tvm/issues/2907).

This is a formal vote about the following items.

- Continue to use github issues and discuss forums for community conversations
NOTE: all the conversation threads are mirrored to apache lists.
- Continue to use our [community guideline](https://docs.tvm.ai/contribute/community.html)
   - Nonimation org principle https://github.com/dmlc/tvm/issues/2717
   - Recognize reviewers to help grow the community

This thread is mirrored to dev@tvm.apache.org. See https://lists.apache.org/list.html?dev@tvm.apache.org You can participate the vote by replying to this thread, or reply via email in the dev@. The vote will be open for a week, until April 13th.

Please vote:
- +1 if you agree
- +0, if you don’t case
- -1, because.

**Comment by junrushao1994** [comment]
+1

Should we show the [link](https://lists.apache.org/list.html?dev@tvm.apache.org) to mailing list achieve somewhere.

**Comment by wweic** [comment]
+1

**Comment by kazum** [comment]
+1

**Comment by srkreddy1238** [comment]
+1

**Comment by tvm-archiver** [comment]
+1

**Comment by xqdan** [comment]
+1

**Comment by ehsanmok** [comment]
+1

**Comment by kevinthesun** [comment]
+1

**Comment by Ravenwater** [comment]
+1

**Comment by vinx13** [comment]
+1

**Comment by makihiro** [comment]
+1

**Comment by yidawang** [comment]
+1

**Comment by ajtulloch** [comment]
+1

**Comment by ZihengJiang** [comment]
+1

**Comment by icemelon9** [comment]
+1

**Comment by zhiics** [comment]
+1

**Comment by merrymercy** [comment]
+1

**Comment by jroesch** [comment]
+1

**Comment by tqchen** [comment]
Thanks to everyone who voted, this vote has passed. 18 +1 votes, (no 0 and -1 votes)
