### ISSUE TITLE
[Discussion] Export LookupLLVMIntrinsic for C++ users

### ISSUE THREAD

**Issue by baowenlei** [dmlc/tvm#2974]
Hi there,

Currently it seems that `LookupLLVMIntrinsic` or `lookupIntrinsicID` is not exposed to C++ users in tvm. But it is available from python side. Please correct me if I am wrong.

To utilize it in C++, I just put it in some header. 
Please let me know if this sounds a reasonable request and where should I put it to export. And then I could create a PR for that.

Thanks.

**Comment by tqchen** [comment]
Please open a new thread in https://discuss.tvm.ai/ with development tag :)

**Comment by tqchen** [comment]
To answer your specific question. We try to keep the public API minimum. LookupLLVMIntrinsic is a private API that we use inside the tvm project and maybe we should not expose it for now. Note that it is also part of LLVM API that you might be able to directly get by call into LLVM function.
