### ISSUE TITLE
[Vote] Deprecate Python2 Support

### ISSUE THREAD

**Issue by antinucleon** [dmlc/tvm#2994]
As we discussed in https://github.com/dmlc/tvm/issues/2715, most of us agree with switch to Python3 starts with 0.6 release. I want to start a vote to deprecate Python2 support & test in our current master branch. 

@dmlc/tvm-committer

**Comment by nhynes** [comment]
Ah finally! So much +1

**Comment by tmoreau89** [comment]
+1

**Comment by Ravenwater** [comment]
+1

**Comment by MarisaKirisame** [comment]
+1. We (The relay crew) often find not having py3 features(fstring, keword only argument, type annotation, nonlocal) inconvenient. Can we get it to 3.6? fstring(3.6 feature) is used heavily in the relay ahead of time compiler that will be opensourced soon.

**Comment by tqchen** [comment]
+1, I think we agreed on python3.5 support to be safe because many users' system still only have 3.5 installed.

**Comment by icemelon9** [comment]
+1

**Comment by zhiics** [comment]
+1

**Comment by Laurawly** [comment]
+1

**Comment by srkreddy1238** [comment]
+1

**Comment by jroesch** [comment]
👍

**Comment by kazum** [comment]
+1

**Comment by ehsanmok** [comment]
+1

**Comment by joshpoll** [comment]
+1

**Comment by antinucleon** [comment]
Python2 is deprecated in https://github.com/dmlc/tvm/pull/2986. We may also send a PR to https://python3statement.org/

**Comment by tqchen** [comment]
Let us keep the vote open for a week.
