### ISSUE TITLE
How to extract functions from tvm module.

### ISSUE THREAD

**Issue by myproject24** [dmlc/tvm#3007]
@tqchen I have tvm compiled module, I have to extract all function present inside the module what is the way to know the functions inside the module. Basically, I am trying to deploy the module in c++ and need to call those functions.

**Comment by srkreddy1238** [comment]
Can you check the graph JSON ?

**Comment by myproject24** [comment]
@srkreddy1238 Can you please show me the sample of function name looks like in JSON file?

**Comment by tqchen** [comment]
Please open a new thread on disuss.tvm.ai
