### ISSUE TITLE
from_caffe2

### ISSUE THREAD

**Issue by petit-ami** [dmlc/tvm#3055]
DecodeError                               Traceback (most recent call last)
<ipython-input-11-1cd24da8f231> in <module>()
      6         self.init_net, self.predict_net, self.value_info = mf.get_c2_model(model_name)
      7 
----> 8 resnet50 = Model('resnet50')

<ipython-input-11-1cd24da8f231> in __init__(self, model_name)
      4 class Model:
      5     def __init__(self, model_name):
----> 6         self.init_net, self.predict_net, self.value_info = mf.get_c2_model(model_name)
      7 
      8 resnet50 = Model('resnet50')

/export/userhome/liqiang/liqiang/Anaconda/ENTER/envs/tvm/lib/python2.7/site-packages/caffe2/python/models/download.pyc in get_c2_model(self, model_name)
    190         c2_init_net = caffe2_pb2.NetDef()
    191         with open(c2_init_pb, 'rb') as f:
--> 192             c2_init_net.ParseFromString(f.read())
    193         c2_init_net.name = model_name + '_init'
    194 

DecodeError: Error parsing message

could anybody know any solution to this?

**Comment by hlu1** [comment]
Are you using python2.7? TVM has officially dropped support of python2.7. Can you rerun it with python3 (at least python 3.5)? The error message looks like a caffe2 protobuf error. It failed to decode the input init_net.

If the problem still exists after upgrading to python3, please post a repro.

**Comment by tqchen** [comment]
It is also better to move the question first to discuss.tvm.ai

**Comment by petit-ami** [comment]
@after creating a new environment of python3.6, another message occurs:
DecodeError                               Traceback (most recent call last)
<ipython-input-2-1cd24da8f231> in <module>()
      6         self.init_net, self.predict_net, self.value_info = mf.get_c2_model(model_name)
      7 
----> 8 resnet50 = Model('resnet50')

<ipython-input-2-1cd24da8f231> in __init__(self, model_name)
      4 class Model:
      5     def __init__(self, model_name):
----> 6         self.init_net, self.predict_net, self.value_info = mf.get_c2_model(model_name)
      7 
      8 resnet50 = Model('resnet50')

~/liqiang/Anaconda/ENTER/envs/tvm36/lib/python3.6/site-packages/caffe2/python/models/download.py in get_c2_model(self, model_name)
    188         c2_init_net = caffe2_pb2.NetDef()
    189         with open(c2_init_pb, 'rb') as f:
--> 190             c2_init_net.ParseFromString(f.read())
    191         c2_init_net.name = model_name + '_init'
    192 

~/liqiang/Anaconda/ENTER/envs/tvm36/lib/python3.6/site-packages/google/protobuf/message.py in ParseFromString(self, serialized)
    183     """
    184     self.Clear()
--> 185     self.MergeFromString(serialized)
    186 
    187   def SerializeToString(self, **kwargs):

~/liqiang/Anaconda/ENTER/envs/tvm36/lib/python3.6/site-packages/google/protobuf/internal/python_message.py in MergeFromString(self, serialized)
   1067     length = len(serialized)
   1068     try:
-> 1069       if self._InternalParse(serialized, 0, length) != length:
   1070         # The only reason _InternalParse would return early is if it
   1071         # encountered an end-group tag.

~/liqiang/Anaconda/ENTER/envs/tvm36/lib/python3.6/site-packages/google/protobuf/internal/python_message.py in InternalParse(self, buffer, pos, end)
   1103         pos = new_pos
   1104       else:
-> 1105         pos = field_decoder(buffer, new_pos, end, self, field_dict)
   1106         if field_desc:
   1107           self._UpdateOneofState(field_desc)

~/liqiang/Anaconda/ENTER/envs/tvm36/lib/python3.6/site-packages/google/protobuf/internal/decoder.py in DecodeRepeatedField(buffer, pos, end, message, field_dict)
    608         new_pos = pos + size
    609         if new_pos > end:
--> 610           raise _DecodeError('Truncated message.')
    611         # Read sub-message.
    612         if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:

DecodeError: Truncated message.


how can I fix that?

**Comment by hlu1** [comment]
I'm pretty sure your problem is with protobuf and caffe2/pytorch. The error message doesn't seem to be related to tvm. Have you tried to run the unit tests in pytorch and see if all those pass?

**Comment by petit-ami** [comment]
DecodeError                               Traceback (most recent call last)
<ipython-input-2-1cd24da8f231> in <module>()
      6         self.init_net, self.predict_net, self.value_info = mf.get_c2_model(model_name)
      7 
----> 8 resnet50 = Model('resnet50')

<ipython-input-2-1cd24da8f231> in __init__(self, model_name)
      4 class Model:
      5     def __init__(self, model_name):
----> 6         self.init_net, self.predict_net, self.value_info = mf.get_c2_model(model_name)
      7 
      8 resnet50 = Model('resnet50')

~/liqiang/Anaconda/ENTER/envs/tvm36/lib/python3.6/site-packages/caffe2/python/models/download.py in get_c2_model(self, model_name)
    190         c2_init_net = caffe2_pb2.NetDef()
    191         with open(c2_init_pb, 'rb') as f:
--> 192             c2_init_net.ParseFromString(f.read())
    193         c2_init_net.name = model_name + '_init'
    194 

DecodeError: Error parsing message

@hlu1 
I install the pytoch as the tutorials tell: 
conda install pytorch-nightly cudatoolkit=9.0 -c pytorch
and I can successfully import torch and caffe2, using python=3.6
the error  above still come up，should I downgrade the version of prototbuf?

my env:
pytorch-nightly：1.10
protobuf：3.7.1
libprotobuf：3.7.1
