### ISSUE TITLE
UnboundLocalError: local variable 'tensor' referenced before assignment

### ISSUE THREAD

**Issue by OuHangKresnik** [dmlc/tvm#3067]
MacOS

### **Error:**
  File "/Users/ouhang/Work/Ninjia/workspace/tvm/python/tvm/_ffi/_ctypes/function.py", line 71, in cfun
    rv = local_pyfunc(*pyargs)
  File "/Users/ouhang/Work/Ninjia/workspace/tvm/topi/python/topi/opengl/pooling.py", line 124, in schedule_pool
    traverse(outs[0].op)
  File "/Users/ouhang/Work/Ninjia/workspace/tvm/topi/python/topi/opengl/pooling.py", line 110, in traverse
    for tensor in OP.input_tensors and tensor.op not in scheduled_ops:
UnboundLocalError: local variable 'tensor' referenced before assignment

**Code:**

    opt_level = 3
    target = tvm.target.opengl()
    with relay.build_config(opt_level=opt_level):
       graph, lib, params = relay.build_module.build(net, target, params=params)

**Fix:**
Change
topi/python/topi/opengl/pooling.py

    for tensor in OP.input_tensors and tensor.op not in scheduled_ops:
        if tensor.op.input_tensors:
            traverse(tensor.op)

To:

            for tensor in OP.input_tensors:
                if tensor.op not in scheduled_ops and tensor.op.input_tensors:
                    traverse(tensor.op)

Would fix...

**Comment by tqchen** [comment]
This fix lgtm, a PR is welcomed!
