### ISSUE TITLE
Does relay/nnvm support dynamic shape?

### ISSUE THREAD

**Issue by minminsun** [dmlc/tvm#3076]
I noticed that models defined under python/tvm/relay/testing/ all have fixed input shapes. But in real applications some dimensions, e.g. the batch dimension, could vary from one request to another.
In Tensorflow, the dynamic shape is supported by specifying None for some dimensions of a placeholder's shape. So I'm curious does relay or nnvm have such support too?

**Comment by wweic** [comment]
Hi @minminsun, There is RFC for dynamic shape in Relay(https://github.com/dmlc/tvm/issues/3042). For dynamic rank, algebraic data type can be used to support it to some degree. https://discuss.tvm.ai/ is the forum for general questions/discussions :-)

**Comment by minminsun** [comment]
@wweic many thanks!
