### ISSUE TITLE
[TENSORFLOW] Frontend update to 1.12 

### ISSUE THREAD

**Issue by srkreddy1238** [dmlc/tvm#3077]
w.r.t
https://discuss.tvm.ai/t/support-for-tensorflow-ops-for-newer-tf-version/2324

Standard Tensorflow models exported in TF 1.12 & later have newer ops which have not been implemented in TVM right now.

VariableV2: I guess TF has deprecated Variable and moved to variable2. I am not 100% sure though. Here is the link 1
TruncatedNormal
Assign
I havent encountered any other non supported op. Want to know whats the way forward ?

```
Traceback (most recent call last):
  File "tvm_basic_infra_testing.py", line 106, in <module>
    net, params = tvm.relay.frontend.from_tensorflow(graph_def, shape={'input':input_shape}, layout=layout)
  File "/tvm/python/tvm/relay/frontend/tensorflow.py", line 2182, in from_tensorflow
    sym, params = g.from_tensorflow(graph, layout, shape, outputs)
  File "/tvm/python/tvm/relay/frontend/tensorflow.py", line 1700, in from_tensorflow
    "The following operators are not implemented: {}".format(missing_operators))
NotImplementedError: The following operators are not implemented: {'TruncatedNormal', 'Assign', 'VariableV2'}
```

**Comment by masahi** [comment]
@srkreddy1238 what is the tensorflow version expected to work with TVM? I'm trying to fix tensorflow frontend tests for my PR.

**Comment by yongwww** [comment]
@masahi I think it is 1.13 for now. @srkreddy1238 pls confirm

**Comment by srkreddy1238** [comment]
I think we should go with 1.13 now.

**Comment by srkreddy1238** [comment]
#3184 provides limited support for PlaceholderWithDefault treating it as Placeholder.

```tf.graph_util.convert_variables_to_constants``` graph transform can be used before import to take care of Variable(V2), Assign.

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/3184
