### ISSUE TITLE
[Question] Does it necessary to define project based option command in cmake?

### ISSUE THREAD

**Issue by cloudhan** [dmlc/tvm#3078]
I notice in dmlc project,s there will always be <project_name>_option in `CMakeLists.txt` which is defined in https://github.com/dmlc/tvm/blob/3f835bd974536a3b19dc63d7f7e55ada01d752bd/cmake/util/Util.cmake#L28

I am curious, what is its purpose? Why not just use CMake's `option` command?

**Comment by merrymercy** [comment]
Please move general questions to https://tvm.ai
