### ISSUE TITLE
ResNet50 based one stage detector model conversion gets hung up

### ISSUE THREAD

**Issue by nttstar** [dmlc/tvm#3090]
Dear auchors, we're trying to convert a resnet50 based one stage detector to tvm, but gets hung up. Here is the download link from baidu cloud: 
https://pan.baidu.com/s/1C6nKq122gJxRhb37vK0_LQ

Introduction: https://github.com/deepinsight/insightface/tree/master/retinaface

Can anybody have a look on it?

By the way, a mobilenet based model is working well, the only difference between them is backbone.

**Comment by tqchen** [comment]
Thanks for reporting this, usually we prefer to ask this kind of questions in https://discuss.tvm.ai/ please open a new thread there
