### ISSUE TITLE
[Performance] x86 gluoncv ssd performance regression

### ISSUE THREAD

**Issue by kevinthesun** [dmlc/tvm#3097]
This is to track the status of https://discuss.tvm.ai/t/relay-x86-target-performance-regression/2266/5

Analyzer CanonicalSimplifier is casuing fused_strided_slice_greater_cast_concatenate_ones_like_multiply_where_strided_slice to be slower.

**Comment by kevinthesun** [comment]
@tqchen 
After investigating generated lower stmt, I found a important difference:
In old version which has expected performance, this fused func has such a patten:
```
tvm_if_then_else((24512 <= ((((ax0.ax1.fused*4) + ax2) + -4) % 24528)), placeholder[(((((ax0.ax1.fused*4) + ax2) + -4) % 24528) % 16)],  ...
```
After Analyzer CanonicalSimplifier commit, it becomes:
```
tvm_if_then_else((24512 <= ((((ax0.ax1.fused*4) + ax2) + -466036) % 24528)), placeholder[((((((ax0.ax1.fused*4) + ax2) + -466036) % 24528) + -24512) % 16)],  ...
```
Two expressions have the same semantic but the latter one is more complicated. A lot of similar pattens happen in this func and it might be the problem. 

Since lowered stmt is very long, I put the complete stmt in gist: [old](https://gist.github.com/kevinthesun/7dfa5148efaecafe4f4b8bbb41e89e8e) and [new](https://gist.github.com/kevinthesun/1f19f422890ecc61744f16eda723639a)

**Comment by yzhliu** [comment]
@kevinthesun Do we confirm CanonicalSimplifier is causing the regression?

**Comment by tqchen** [comment]
This could likely due to CanonicalSimplify for making a stronger assumption of simplifying the divisions and mod(having to make sure operands are positive). 

This is mainly because we make a different assumption about the division semantics. For this particular case, we could enhance the simplifier to deduce that the operand before mod is indeed positive, I will attempt a fix in the incoming weeks and see how it goes

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/3132 is an attempted improvement to alleviate this situation. In particular, the two cases examples can now be simplified

**Comment by kevinthesun** [comment]
@tqchen Now gluoncv ssd has expected performance after https://github.com/dmlc/tvm/pull/3132. Thanks for your fixing!
