### ISSUE TITLE
[TUTORIAL] Deploy GluonCV some ssd tutorial models fail

### ISSUE THREAD

**Issue by jnorwood** [dmlc/tvm#3103]
The ssd tutorial presents a list of possible models.  I tried substituting each of the ones in the list.
[https://docs.tvm.ai/tutorials/frontend/deploy_ssd_gluoncv.html](url)

These two failed due to not having pretrained  versions available.
model_name = "ssd_512_resnet18_v1_voc" #no pretrained
model_name = "ssd_512_resnet18_v1_coco" #no pretrained

**Comment by tqchen** [comment]
@kevinthesun can you check and take a look?

**Comment by tqchen** [comment]
As a side note, we always encourage posting on https://discuss.tvm.ai/ first :)

**Comment by jnorwood** [comment]
ok, thanks.  I wasn't aware of the discuss.tvm.ai group.  I signed up there and will use that next time.

**Comment by zhreshold** [comment]
@jnorwood Unfortunately SSD `resnet18_v1` models has no pretrained weights. There are a couple more power models to choose but if you are particularly interested in the less expensive models, we are open to contributions!

**Comment by jnorwood** [comment]
Yes, I determined that it had no pretrained weights, but this tutorial listed these two among the available models for that tutorial.  So, I guess the solution is to just remove the two entries from the tutorial supported_model list.

**Comment by kevinthesun** [comment]
Will be fixed in https://github.com/dmlc/tvm/pull/2784.
