### ISSUE TITLE
relay tutorial missing llvm example

### ISSUE THREAD

**Issue by jnorwood** [dmlc/tvm#3104]
I'm trying out the relay tutorial at

[https://docs.tvm.ai/tutorials/relay_quick_start.html#overview-for-supported-hardware-backend-of-tvm](url)

It has the statement:
`In this tutorial, we’ll choose cuda and llvm as target backends
`
but in fact the tutorial only presented for target cuda (which I don't have).

From poking around, I figured out how to modify it for llvm.
I tested for inception v3, mobilenet, resnet, squeezenet, vgg and densenet.  All except densenet seemed to work.  It gets all 0 results, which doesn't result in a failure, but I presume is wrong.

In general, it takes manual digging through the code to determine which parameters are accepted for the different models, and it takes getting in the debugger to figure out a list of possible models.  I'll add follow up posts on each of the ones I tested.

**Comment by jnorwood** [comment]
rather than making several comments, I'll just attach my modified files.  Note that densenet apparently fails with all 0 value returns. The others ... inception, mobilenet, resnet, squeezenet, vgg can have different versions or sizes in the parameter lists... I made comments in the code of the possible values.
In general, you have to use  ` target = 'llvm'`  and  `ctx = tvm.cpu()`

you need to specify a correct image shape for the model, such as:
`image_shape = (3, 299, 299)`  for inception

you have to modify the get_workload calls compatible with each model

```
# num_layers can be 18,34,50, 101, 152, 200
net, params = relay.testing.resnet.get_workload(
    num_layers=34, batch_size=batch_size, image_shape=image_shape)
```
I also commented out the print line, which can take a long time for the larger models
`#print(net.astext(show_meta_data=False))`

[relay_1.zip](https://github.com/dmlc/tvm/files/3120135/relay_1.zip)

**Comment by srkreddy1238** [comment]
Can you raise it on discuss forum  https://discuss.tvm.ai ?
Once a issue is concluded we can bring it back here.

Thanks

**Comment by tqchen** [comment]
Let us  discussion to https://discuss.tvm.ai:)

**Comment by jnorwood** [comment]
ok, I referenced this at
[https://discuss.tvm.ai/t/relay-tutorial-could-use-some-llvm-examples/2385](url)
