### ISSUE TITLE
[Relay][ONNX] KeyError: ‘W’ when compiling from onnx

### ISSUE THREAD

**Issue by mnboos** [dmlc/tvm#3134]
Dear tvm team

I'm aware that I'm not supposed to use this issue tracker as a first instance. However, in the community was no reaction and in the meantime the model I uploaded was deleted. So I added it here as an attachment, so it won't get lost anymore.
[yolo_failing.zip](https://github.com/dmlc/tvm/files/3140832/yolo_failing.zip)

The attached model leads to an exception during the compilation:

```python
 File "C:\src\xyz\src\tvm\compile_model.py", line 78, in compile_model
    relay_func, params = relay.frontend.from_onnx(onnx_model, shape=input_shape_dict)
  File "C:\Users\bmar\AppData\Roaming\Python\Python36\site-packages\tvm-0.6.dev0-py3.6-win-amd64.egg\tvm\relay\frontend\onnx.py", line 1139, in from_onnx
    sym, params = g.from_onnx(graph, opset)
  File "C:\Users\bmar\AppData\Roaming\Python\Python36\site-packages\tvm-0.6.dev0-py3.6-win-amd64.egg\tvm\relay\frontend\onnx.py", line 960, in from_onnx
    inputs = [self._nodes[self._renames.get(i, i)] for i in node.input]
  File "C:\Users\bmar\AppData\Roaming\Python\Python36\site-packages\tvm-0.6.dev0-py3.6-win-amd64.egg\tvm\relay\frontend\onnx.py", line 960, in <listcomp>
    inputs = [self._nodes[self._renames.get(i, i)] for i in node.input]
KeyError: 'W'
```

**Comment by tqchen** [comment]
cross ref https://discuss.tvm.ai/t/relay-onnx-keyerror-w-when-compiling-from-onnx/2102/3

Given that you have a good idea about what is happening, can you attempt a fix to the problem?

**Comment by mnboos** [comment]
I will clarify with my boss and come back to you.

**Comment by zhanggy358** [comment]
I have encountered similar issue:


Traceback (most recent call last):
  File "from_onnx.py", line 96, in <module>
    sym, params = relay.frontend.from_onnx(onnx_model, shape_dict, dtype='float32')
  File "/tvm/python/tvm/relay/frontend/onnx.py", line 1144, in from_onnx
    sym, params = g.from_onnx(graph, opset)
  File "/tvm/python/tvm/relay/frontend/onnx.py", line 965, in from_onnx
    inputs = [self._nodes[self._renames.get(i, i)] for i in node.input]
  File "//tvm/python/tvm/relay/frontend/onnx.py", line 965, in <listcomp>
    inputs = [self._nodes[self._renames.get(i, i)] for i in node.input]
KeyError: ' '

**Comment by jroesch** [comment]
Could you send the parameters to the `from_onnx` call? 

For example with:

```
import onnx
from tvm import relay

yolo = onnx.load("/Users/jroesch/Downloads/yolo_failing.onnx")
import pdb; pdb.set_trace()
# What shapes do we pass?
relay.frontend.from_onnx(yolo)
```

**Comment by jroesch** [comment]
cc @zhreshold could you look into this?

**Comment by zhreshold** [comment]
I actually digged into and found some bugs.
Here's the fix: https://github.com/dmlc/tvm/pull/3143

@mnboos 
However, the provided yolo_failing.zip is not a valid onnx model, the nodes are not in topological order which will cause failure when iterating throught the nodes in onnx.graph. 
Please let me know if you have a proper model and I can add it to the unittest.

**Comment by mnboos** [comment]
@zhreshold Thanks for your efforts. The model was created with the official keras2onnx converter, I'll file an issue there. On the other hand it would be nice if TVM could either first sort topologically if necessary or provide a useful error message.

**Comment by jroesch** [comment]
It is possible to just directly use the Keras importer in that case?

**Comment by mnboos** [comment]
Theoretically yes, but we're looking into TVM and TVM handles onnx as input, which lead to the error above. Using another library would just be avoiding a symptom, whereas I'm more a friend of solving problem at its root. Don't get me wrong, I don't want to make accusations, I'm just saying there is room for improvement in terms of robustness in TVM (when it comes to handling (invalid) onnx).

**Comment by tqchen** [comment]
Close by https://github.com/dmlc/tvm/pull/3143, we welcome contribution for a  topo correctness checker in onnx importer
