### ISSUE TITLE
[TEST][FLAKY] test_topi_vision.test_get_valid_counts

### ISSUE THREAD

**Issue by eqy** [dmlc/tvm#3142]
See http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3083/6/pipeline/ for an example failed run.

**Comment by eqy** [comment]
Closed by #3151, thanks @Laurawly

**Comment by tqchen** [comment]
the problem still occurs http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3156/32/pipeline

**Comment by tqchen** [comment]
cc @Laurawly

**Comment by Laurawly** [comment]
@tqchen I wonder if this change https://github.com/dmlc/tvm/blob/1f3a49417ec8f2712aa979b8e3d56a838734dcf1/src/codegen/build_module.cc#L86 will fix the problem.
