### ISSUE TITLE
[Bug][VTA][PATCH Attached] VTA Load Error After Change VTA Config "LOG_BLOCK_IN" and "LOG_BLOCK_OUT" Into >4 Number 

### ISSUE THREAD

**Issue by ahjiangz** [dmlc/tvm#3150]
Hi There,

I am doing some practice with VTA Tutorials "Simple Matrix Multiply" and experienced a error issue and it seems like be a bug of vta_conv2d.py.

Issue is after  changed   LOG_BLOCK_IN and LOG_BLOCK_OUT in vta_config.json into a >4 value like 5, the vta load would report error as following.  

Problem seems like caused by resnet18 that used by vta_conv2d.py and have in_filter minimum size which is 16. I attached a patch for such issue which would make "Simple Matrix Multiply" demo work with >4  LOG_BLOCK_IN and LOG_BLOCK_OUT value.

Regards
Hua

Issue:
VTA Load Error After Change VTA Config "LOG_BLOCK_IN" and "LOG_BLOCK_OUT" Into >4 Number.
tvm/vta/python/vta/top/vta_conv2d.py in find_schedules(layer, vt_only, best_only)
    151 
    152     if best_only:
--> 153         return [fil_sched[xfer_size.index(min(xfer_size))]]
    154     return fil_sched
    155 

ValueError: min() arg is an empty sequence

Patch: attached
[vtaconfig.txt](https://github.com/dmlc/tvm/files/3158792/vtaconfig.txt)

**Comment by tqchen** [comment]
please open a new thread in discuss.tvm.ai
