### ISSUE TITLE
[c++ deploy] How to manage resources for multiple tvm instances in single application?

### ISSUE THREAD

**Issue by ZephyrSails** [dmlc/tvm#3152]
Hi there,

I have a c++ application and it will run multiple tvm instances in parallel, and I wish each tvm instance can use 4 cpus to optimize the execution time. (e.g: on a machine with 20 cores, I will run 5 tvm instances and each instances will use and only use their assigned 4 cores).

If I don't need them to run in parallel, I can use environment variable e.g: `export TVM_NUM_THREADS=4` to set the cpu usage for entire application, but I don't know what would be the best practice to set such limitation for every instances (who may run in parallel) inside the application.

Any insights? Thanks in advance!

**Comment by Ravenwater** [comment]
I presume that the concurrency created by parallel execution is at the model level. In that case, you would want to create some model-level memory and processor allocations. You could do this at the process level, and manage TVM invokations, or you can leverage the whole container ecosystem. Although, container schedulers like k8s tend to want resource guarantees, so the container route will increase your overall resource requirements.

**Comment by tqchen** [comment]
Thanks for the great discussion, for this kind of topic, we generally encourage opening a thread in https://discuss.tvm.ai/, let us move the discussion there :)

**Comment by ZephyrSails** [comment]
Hi @Ravenwater, thanks for your reply, the concurrency I'm talking about is out side model, for example: our TVM model will handle entire user request. When we have multiple user requests happening concurrently, we will create multiple TVM model instance, and each instance handle each request. We wish each TVM model instance can get their designated resource (cpu) and do not interfere with each other.

**Comment by ZephyrSails** [comment]
@tqchen What would be the best practice to move this topic? Shall I just post the exact same question in https://discuss.tvm.ai/ and add a link to this thread?
