### ISSUE TITLE
CI build problem

### ISSUE THREAD

**Issue by derisavi** [dmlc/tvm#3171]
The last few CI builds have failed very early on. Could be a server problem or something.
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3169/1/pipeline
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3168/1/pipeline
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3166/2/pipeline

Can someone please take a look? I don't know who other than @tqchen can fix it. Please feel free to tag them here.

**Comment by tqchen** [comment]
Thanks for reporting this. Was due to a bad configuration in a worker. This has been fixed. Please push again to retrigger
