### ISSUE TITLE
Build error from dsl_api.cc

### ISSUE THREAD

**Issue by Wheest** [dmlc/tvm#3181]
Hello there.

I've been getting the following build error on all master commits since [dd55682](https://github.com/dmlc/tvm/commit/dd55682dcd6a6b17d11f228a64708532bb1ad111), including the [current head of master](https://github.com/dmlc/tvm/commit/5f5bf79742552194eeb5256026ae60e9cfe94426).  Build is successful on prior versions.

```
/home/wheest/tools/tvm/src/api/dsl_api.cc:95:55: error: only virtual member functions can be marked 'final'
  void Visit(const char* key, runtime::Object* value) final {
                                                      ^~~~~~
/home/wheest/tools/tvm/src/api/dsl_api.cc:136:55: error: only virtual member functions can be marked 'final'
  void Visit(const char* key, runtime::Object* value) final {
                                                      ^~~~~~
2 errors generated.
make[2]: *** [CMakeFiles/tvm.dir/build.make:167: CMakeFiles/tvm.dir/src/api/dsl_api.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:211: CMakeFiles/tvm.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

Only tested on Debian testing buster, x86_64 Linux 4.19.0-4-amd64, can provide further information if needed.

**Comment by jroesch** [comment]
You need to update your submodules, make sure to run `git submodule update` after pulling a revision in which the submodules have changed.
