### ISSUE TITLE
output shape is different from mxnet

### ISSUE THREAD

**Issue by ElegantGod** [dmlc/tvm#3183]
In my tvm inference, the ndim and shape of cpp and python are 5, [1,4,32,32,8], but the ndim and shape of mxnet inerence are 4,[1,32,32,32].

**Comment by vinx13** [comment]
In TVM, some conv2d will be transformed to NCHWc for better performance. https://github.com/dmlc/tvm/blob/6a4d71ff40915611bd42b62994992b879e6be610/topi/python/topi/x86/conv2d.py#L374
Please move discussion to https://discuss.tvm.ai if you met any error.
