### ISSUE TITLE
[TFLite] Support Operator MUL,RESIZE_BILLINEAR not implemented

### ISSUE THREAD

**Issue by aa12356jm** [dmlc/tvm#3189]
when I try a pretrained tflite model, get a error:
tvm.error.OpNotImplemented: The following operators are not supported in frontend TFLite: 'MUL','RESIZE_BILINEAR'

**Comment by apivovarov** [comment]
Added MUL https://github.com/dmlc/tvm/pull/3304

**Comment by apivovarov** [comment]
PR to support `RESIZE_BILLINEAR` https://github.com/dmlc/tvm/pull/3370
