### ISSUE TITLE
OpenCL grouped convolutions "did you forget to bind"

### ISSUE THREAD

**Issue by Wheest** [dmlc/tvm#3190]
It's possible that this is a usage question rather than a bug.

However, I have been trying to run grouped convolutions on OpenCL devices, using models imported from ONNX.

OpenCL models work when the number of `groups==1`, and when `groups==input_channels`, but get errors like `Direct host side access to device memory is detected in fused_nn_conv2d_9` for other values of groups.  

Interestingly, varying the optimisation level changes the error message slightly, but does not fix results.

[I have an MWE gist notebook that shows the problem here](https://gist.github.com/Wheest/abd48c08e7b0fef70f24c0a5b7c1c666).

Prior issues with grouped convolutions were dealt with in [#3070](https://github.com/dmlc/tvm/pull/3070).

Perhaps grouped convolutions in OpenCL require a specific data layout?  However I'm unsure how I would specify this for imported ONNX models.

**Comment by vinx13** [comment]
group conv2d is not fully supported, we don't have schedule on CUDA/OpenCL. Currently only int8 group conv2d on CUDA is supported.

**Comment by tqchen** [comment]
@vinx13 can we add a more specific exception for other cases for now?
