### ISSUE TITLE
[RELAY] Avoid eager creation of global target object

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#3197]
https://github.com/dmlc/tvm/blob/master/src/relay/backend/build_module.cc#L54

Not all target is enabled.
- See https://discuss.tvm.ai/t/unknown-target-name-vpi/2589/3
- Consider changing the map to a function, with switch case

It is usually not a good practice to eagerly create a global static object(which might have initialization order issue).

**Comment by tqchen** [comment]
cc @zhiics

**Comment by zhiics** [comment]
I will move them back to `std::string` and create when necessary.

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/3198

**Comment by zhiics** [comment]
@tqchen Thanks for the fix.
