### ISSUE TITLE
[TOPI] Operator overloading issue when dealing with zero-rank tensor

### ISSUE THREAD

**Issue by kevinthesun** [dmlc/tvm#3240]
This PR https://github.com/dmlc/tvm/pull/1029 overloads binary op for tensor to use topi broadcast op when importing topi. This will cause topi.compute to fail when zero-rank tensor appears in the fcompute body, since a topi broadcast op returns a tensor while comm_reducer requires an expr:
```python
import tvm
from tvm import relay

n = 10
A = tvm.placeholder((n, ), name='A')
scale = tvm.placeholder((), name='scale')
k = tvm.reduce_axis((0, n), name="k")
fcompute = lambda : tvm.sum(A[k] * scale, axis=k)
C = tvm.compute((), fcompute, name="C")
```
Error msg:
```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    C = tvm.compute((), fcompute, name="C")
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-macosx-10.11-x86_64.egg/tvm/api.py", line 309, in compute
    body = fcompute(*[v.var for v in dim_var])
  File "test.py", line 8, in <lambda>
    fcompute = lambda : tvm.sum(A[k] * scale, axis=k)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-macosx-10.11-x86_64.egg/tvm/api.py", line 819, in reducer
    return _make_reduce(expr, axis, where)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-macosx-10.11-x86_64.egg/tvm/api.py", line 795, in _make_reduce
    assert isinstance(expr, _expr.Expr)
AssertionError
```
@tqchen @jroesch @yzhliu

**Comment by tqchen** [comment]
@kevinthesun please followup to propose a fix for this.

**Comment by tqchen** [comment]
ping @kevinthesun

**Comment by kevinthesun** [comment]
Is it possible we force binary op to be the correct implementation inside tvm.compute?

**Comment by tqchen** [comment]
Because it is not context-dependent, it is harder to do force that. We could, however, avoid overloading of TensorSlice mul scalar to get an Tensor.

**Comment by MarisaKirisame** [comment]
@kevinthesun what is the status on this?

**Comment by kevinthesun** [comment]
@tqchen Did you mean force mul-scalar to always get Expr?

**Comment by tqchen** [comment]
it depends on the type. If it is TensorSlice that has 0-rank, we could always return Expr.

**Comment by tqchen** [comment]
After i think a bit more about it. I think the problem was that we do need to represent the 0-rank tensor as TensorSlice, so in the above case, we should instead write(note the call in the scale)

```python
import tvm
from tvm import relay

n = 10
A = tvm.placeholder((n, ), name='A')
scale = tvm.placeholder((), name='scale')
k = tvm.reduce_axis((0, n), name="k")
fcompute = lambda : tvm.sum(A[k] * scale(), axis=k)
C = tvm.compute((), fcompute, name="C")
```

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/3612 makes the test cases more conservative. So that the topi behavior can remains the same.
