### ISSUE TITLE
[potential bug?] SimulatedAnnealingOptimizer will find useless candidate?

### ISSUE THREAD

**Issue by deadlywing** [dmlc/tvm#3245]
When I read the code of  SimulatedAnnealingOptimize, I find the method `find_maximums` is implemented by heap, and insert some dummy elements first as following:
https://github.com/dmlc/tvm/blob/c0afc91884c1e664e19ab10f5f4898425975a756/python/tvm/autotvm/tuner/sa_model_optimizer.py#L78

But, in the code, there is no guarantee that the output list contains no dummy elements, so will it be a bug when we nearly run out the configs and can't find new points during the loop?

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/ for general discussions :)

**Comment by merrymercy** [comment]
Good catch. Are you interested in sending a patch?

**Comment by eqy** [comment]
@merrymercy this problem should be at least partially covered by this heuristic right
https://github.com/dmlc/tvm/blob/4767554c580f5aa0521727629e51f04f5315f025/python/tvm/autotvm/tuner/model_based_tuner.py#L238

**Comment by merrymercy** [comment]
But it is still a bug in `find_maximums`..
