### ISSUE TITLE
questions about submodular_pick

### ISSUE THREAD

**Issue by deadlywing** [dmlc/tvm#3246]
I am confused about  the following line of method `update` in class `ModelBasedTuner`:
https://github.com/dmlc/tvm/blob/c0afc91884c1e664e19ab10f5f4898425975a756/python/tvm/autotvm/tuner/model_based_tuner.py#L272

In my opinion, `submodular_pick` pick points according both scores(flops) and DiversityScore, but why use zero vector rather than the true score vector?
Thanks!

**Comment by tqchen** [comment]
Please open a new thread in https://discuss.tvm.ai/

**Comment by merrymercy** [comment]
This can be a custom weight, but we just use 0.0

**Comment by deadlywing** [comment]
I see, Thanks a lot!

**Comment by tqchen** [comment]
Thanks for great discussions, @deadlywing , for other followup discussions, you are more than welcomed to use  https://discuss.tvm.ai/
