### ISSUE TITLE
[RELAY] Conditions in quantize.optimize are broken due to issue with tvm.Array

### ISSUE THREAD

**Issue by vinx13** [dmlc/tvm#3273]
This bug is introduced in #3234.
This condition https://github.com/dmlc/tvm/blob/f6acf2e5f51f9ac48f8d13e095805b7fe3f74bcf/python/tvm/relay/quantize/quantize.py#L324 is always `False` because `cfg.required_pass` is `tvm.container.Array`

cc @zhiics

**Comment by zhiics** [comment]
Thanks for pointing out. I will fix this later by moving the whole function to the pass manager after #3251 is merged.

**Comment by tqchen** [comment]
ping @zhiics @vinx13 let us fix this asap

**Comment by zhiics** [comment]
Sorry, I am traveling today. I will fix it tomorrow.

**Comment by tqchen** [comment]
#3283

**Comment by vinx13** [comment]
solved by #3283
