### ISSUE TITLE
MatMul on NVIDIA GPU

### ISSUE THREAD

**Issue by minminsun** [dmlc/tvm#3285]
I can't find any tutorial on tuning MatMul on NVIDIA GPU, so I simply modify the tutorial on tuning MatMul on CPU to get started.
I just added some bind expressions in order to make the schedule work on NVIDIA GPU. 
```
import tvm

def matmul_v0(N, L, M, dtype):
    A = tvm.placeholder((N, L), name='A', dtype=dtype)
    B = tvm.placeholder((L, M), name='B', dtype=dtype)

    k = tvm.reduce_axis((0, L), name='k')
    C = tvm.compute((N, M), lambda i, j: tvm.sum(A[i, k] * B[k, j], axis=k), name='C')
    s = tvm.create_schedule(C.op)

    # schedule
    y, x = s[C].op.axis
    k = s[C].op.reduce_axis[0]

    yo, yi = s[C].split(y, 4)
    xo, xi = s[C].split(x, 4)

    s[C].bind(yo, tvm.thread_axis("blockIdx.y"))
    s[C].bind(xo, tvm.thread_axis("blockIdx.x"))
    s[C].bind(yi, tvm.thread_axis("threadIdx.y"))
    s[C].bind(xi, tvm.thread_axis("threadIdx.x"))
    s[C].reorder(yo, xo, k, yi, xi)

    return s, [A, B, C]

N, L, M = 32, 32, 32
s, a = matmul_v0(N, L, M, 'float32')
fmatmul = tvm.build(s, a, "cuda", target_host="llvm", name="matmul_v0")
```
But it doesn't work. The Error Message is as bellow:
"tvm/src/pass/make_api.cc", line 188 TVMError: Not all Vars are passed in api_args:  'i.inner.init'  'j.inner.init'  does not appeared in api_args

What's the problem with this schedule? And it would be so great if there will be a tutorial on tuning MatMul on NVIDIA GPU added in the future. Thanks!

**Comment by masahi** [comment]
An example of matmul on cuda is available here. https://github.com/dmlc/tvm/blob/master/topi/recipe/gemm/cuda_gemm_square.py

Please use the discussion forum for questions like this.
