### ISSUE TITLE
TVM4J: sun.misc.SharedSecrets was removed with Java >= 9

### ISSUE THREAD

**Issue by t-vi** [dmlc/tvm#3301]
Hi!

Thank you for TVM.

I'm following the instructions for building tvm4j, but compilation fails with
```
[ERROR] tvm/jvm/core/src/main/java/ml/dmlc/tvm/rpc/Server.java:[20,16] cannot find symbol
[ERROR]   symbol:   class SharedSecrets
[ERROR]   location: package sun.misc
```
as far as I can tell, this function was made even more internal with Java 9+.
One solution - keeping Java 8 compat - seems to be to do to use [reflection as in this example](http://hg.openjdk.java.net/openjfx/9-dev/rt/rev/f423d490ae1b).

On [stackoverflow](https://stackoverflow.com/questions/55512615/how-can-i-get-posix-file-descriptor-in-java-1) there is a hacky solution accessing private members of the `FileDescriptor`.

Neither seems particularly attractive, but if you had a favourite...

**Comment by tqchen** [comment]
cc @yzhliu @eqy

**Comment by yzhliu** [comment]
For short-term, we can go with accessing the private field. While I believe the right approach is to move server-loop to frontend bindings, i.e., 
```java
while (data = read(socket)) {
  call_packed_func("process_data", data);
}
```

btw, I got lost with the registry, where is `tvm.rpc.server.start` gets registered? @tqchen

**Comment by tqchen** [comment]
``` tvm.rpc.server.start``` is an optional callback, perhaps a better name should be  ```tvm.rpc.server.on_start```

**Comment by tqchen** [comment]
@yzhliu can you followup on this thread?

**Comment by tqchen** [comment]
ping @yzhliu

**Comment by yzhliu** [comment]
will look into it next week.

**Comment by tqchen** [comment]
@yzhliu what is the status of this issue?

**Comment by yzhliu** [comment]
@tqchen sorry for delay, I'm working on it.

**Comment by tqchen** [comment]
fixed by https://github.com/dmlc/tvm/pull/4147
