### ISSUE TITLE
[TOPI] Fast mode in take op

### ISSUE THREAD

**Issue by hlu1** [dmlc/tvm#3303]
Currently `topi.take` supports two modes, "clip" and "wrap", following the numpy take convention (https://docs.scipy.org/doc/numpy/reference/generated/numpy.take.html). However, the clipping operation makes the take op 30% slower when the input shape is sufficiently large, for example with input shape [20, 1500] and indices shape [750]. I would like to propose add a "fast" mode, similar to the numpy "raise" mode, with no clipping, wrapping, or raising error when the indices are out of range.  The user will be responsible to make sure the indices are in range.

cc @ajtulloch, @antinucleon

**Comment by antinucleon** [comment]
LGTM. @tqchen Is there an easy way to insert assert stmt for out of range check? If we have assert we can both keep speed and make it easy to debug.

**Comment by hlu1** [comment]
Does assert stmt slow it down though? I imagine the range check in the assert stmt is essentially the same as the clipping operation.

**Comment by hlu1** [comment]
cc @yinghai

**Comment by icemelon9** [comment]
I agree that adding assert stmt may also slow down the op. I think it's okay to add "fast" mode in take and add warning in the doc.

**Comment by antinucleon** [comment]
> I agree that adding assert stmt may also slow down the op. I think it's okay to add "fast" mode in take and add warning in the doc.

How about adding a compile time warning as well?

**Comment by hlu1** [comment]
LOG(WARNING) should do. Please review https://github.com/dmlc/tvm/pull/3325
