### ISSUE TITLE
  "inputNdArray.copyFrom(imgRgbTranValues)"  in android_deploy takes very long time

### ISSUE THREAD

**Issue by xinyan0206** [dmlc/tvm#3327]
my image inputSize is 256x256x3, according to android_deploy in TVM ,I transformed it to  float[256x256x3],then I use  NdArray.copyFrom() method transform it to Ndarray， NdArray.copyFrom()   takes more than 200ms，why this method take so long time？？

**Comment by xinyan0206** [comment]
Is there other method i can  use instead of NdArray.copyFrom()

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/

**Comment by xinyan0206** [comment]
> Please open a new thread on https://discuss.tvm.ai/

Thanks for your reply!Open a new thread does work, it only take 30ms.
