### ISSUE TITLE
TFLite Tutorial broken by recent commit.

### ISSUE THREAD

**Issue by mshawcroft** [dmlc/tvm#3332]
The TFLite tutorial is here: https://docs.tvm.ai/tutorials/frontend/from_tflite.html is broken by this recent commit:

https://github.com/dmlc/tvm/pull/3141

commit b63267b92d942b9c64f814b73567b2fe908e67fb
Author: Zhao Wu <wuzhaozju@gmail.com>
Date:   Wed May 22 10:44:47 2019 +0800

    [TFLite] Convert TFLite NCHW to NHWC (#3141)
    * Convert TFLite NCHW to NHWC 
    * Minor comment fix

Building the example in the tutorial results in this failure:
In `main`: 
v0.0.1
fn (%input: Tensor[(1, 3, 224, 224), float32]) {
  %0 = nn.pad(%input, pad_width=[[0, 0], [0, 1], [0, 1], [0, 0]])
  %1 = nn.conv2d(%0, meta[relay.Constant][0], strides=[2, 2], channels=32, kernel_size=[3, 3], data_layout="NHWC", kernel_layout="HWIO")an internal invariant was violated while typechecking your program [15:33:02] /workspace/src/relay/pass/type_solver.cc:119: Check failed: resolved.defined(): Unable to unify parent types: TensorType([3, 3, 224, 32], float32) and TensorType([3, 3, 3, 32], float32)
;

**Comment by apivovarov** [comment]
Are you sure you are using the latest TVM version?

**Comment by mshawcroft** [comment]
Just re-checked this on master (f731e0e666ff07ceba228e2ea0b1bcda837fa6e1) and the issue is still present.

**Comment by FrozenGene** [comment]
I think you don't update the tutorial file. Your input is `1 3 224 224`, which is NCHW input previously. However, current tutorial use `1 224 224 3` NHWC layout. Please checkout the latest TVM codebase of all files.

**Comment by mshawcroft** [comment]
Yep, my bad, the tutorial code I used was out of step.  Thank you for looking into this, much appreciated.
