### ISSUE TITLE
How to know what exactly happens by Relay-IR and llvm code ?

### ISSUE THREAD

**Issue by YPBlib** [dmlc/tvm#3333]
I'm using TVM 0.6 on CPU host. When I wrote a simple tensor computation and build it with TVM, I get a tvm schedule object. Then I can get its Realy IR representation and llvm source code.
My problem is the llvm code are too confusing to read (they can easily be over thousands of lines).
The relay IR is simple though, it seems unreal to me. For example, when I use vectorize method, sometimes I get 1024-bit instruction, which doesn't exit on any CPU arch.

Thus I want to know how to know what exactly happens when TVM models run on CPU?

**Comment by tqchen** [comment]
Please open a new thread in https://discuss.tvm.ai/
