### ISSUE TITLE
Too small time limit for frontend: GPU integration test

### ISSUE THREAD

**Issue by apivovarov** [dmlc/tvm#3334]
Currently "frontend: GPU" integration test time is limited to 1 hour.
Jenkins will kill the test if it runs longer.

I faced this issue several times already for PRs #3310 and #3313
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3313/2/pipeline/
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3313/3/pipeline/
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3310/2/pipeline/
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3310/3/pipeline/

I checked successful frontend: GPU builds and noticed that duration is very close to 1 hour
e.g. 48min 35 sec
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3304/1/pipeline/239

Can time limit for "frontend: GPU" integration test be increased to 1 hour and 30 min?

**Comment by apivovarov** [comment]
On the 5th retry I was able to get successful Jenkins build.
"frontend: GPU" took 59m 6s (just 54 seconds below the 1 hour limit)
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3310/5/pipeline/239

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/3337
