### ISSUE TITLE
[RFC][Frontend] Return module for Relay frontend converter

### ISSUE THREAD

**Issue by icemelon9** [dmlc/tvm#3346]
As we have pass manager in Relay optimization and mostly use module as optimization unit, I suggest we change the Relay frontend converter to return a module instead of a function. The change also makes easier add prelude and global var in the frontend converter in the future. Frontend converter will preset the main function in the module to the converted function as 
```
mod[mod.entry_func] = converted_func
```
Correspondingly we need to change the relay executor to be able to run the converted module. I use MxNet as an exmple to show the proposed change:
```
mod, _ = relay.frontend.from_mxnet(mx_sym, shapes, dtype)
for kind in ["graph", "debug"]:
    intrp = relay.create_executor(kind, mod=mod, ctx=ctx, target=target)
    op_res = intrp.evaluate()(*args)
```
When executor is given no input, it will execute the `mod.entry_func` by default.

cc @jroesch @tqchen @wweic @zhiics

**Comment by zhiics** [comment]
Yeah, this is exactly what I think as well.

**Comment by wweic** [comment]
+1

**Comment by yongwww** [comment]
+1

**Comment by zhiics** [comment]
@icemelon9 #3353 was the draft I haven't finished yet.

**Comment by tqchen** [comment]
+1

**Comment by tqchen** [comment]
#3353
