### ISSUE TITLE
test_vm.test_sum_loop Segmentation fault

### ISSUE THREAD

**Issue by apivovarov** [dmlc/tvm#3352]
At least two recent builds faced this issue
```
test_vm.test_sum_loop ... ./tests/scripts/task_python_integration.sh: line 41: 31836 Segmentation fault      (core dumped) TVM_FFI=ctypes python3 -m nose -v tests/python/relay
```
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3342/1/pipeline/

http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3350/1/pipeline

**Comment by zhiics** [comment]
#3299 Should fix it.

**Comment by apivovarov** [comment]
got another failed build
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3350/4/pipeline

**Comment by slyubomirsky** [comment]
Experienced the same with `test_count_loop()`, fyi

**Comment by apivovarov** [comment]
Most of the recent builds failed with `Segmentation fault`:
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3347/8/pipeline
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3344/2/pipeline
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3356/2/pipeline
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3342/2/pipeline
@tqchen We have serious problem in CI

**Comment by slyubomirsky** [comment]
#3229 seems to have fixed the segfaults, at least on my end

**Comment by zhiics** [comment]
yes. I think it should fix the problem.
