### ISSUE TITLE
[CI] Jenkins workers has old tflite package

### ISSUE THREAD

**Issue by apivovarov** [dmlc/tvm#3373]
1 day ago I updated `ubuntu_install_tflite.sh` to use tflite schema version 1.13
https://github.com/dmlc/tvm/blob/master/docker/install/ubuntu_install_tflite.sh#L38
PR was merged 1 day ago
https://github.com/dmlc/tvm/pull/3356

After that I started two build which uses new tflite classes from v1.13
Both builds failed because they can not find new tflite classes which means that Jenkins workers still use old tflite v1.12
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3370/2/pipeline/
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3370/1/pipeline/
Integration test - frontend GPU error:
```
Running relay TFLite frontend test...
  File "/workspace/python/tvm/relay/frontend/tflite.py", line 235, in _convert_resize
    from tflite.ResizeNearestNeighborOptions import ResizeNearestNeighborOptions
```
PR which uses new tflite classes https://github.com/dmlc/tvm/pull/3370
tflite schema v1.13 - https://raw.githubusercontent.com/tensorflow/tensorflow/r1.13/tensorflow/lite/schema/schema.fbs

**Comment by apivovarov** [comment]
@tqchen Can you help me to solve the issue with old tflite package on Jenkins workers?

**Comment by tqchen** [comment]
The CI image uses a cached image, and need to be staged manually. This is to ensure we have a stable build env. See note here: https://docs.tvm.ai/contribute/pull_request.html#ci-environment

However, do expect a bit delays as we want to update the images infrequently. A quick way to get around would make sure that the solution can be compatible with both versions (also helpful for users as well).

I will send an update note when the docker image get updated.

**Comment by apivovarov** [comment]
ok, I fixed my PR to support both tflite versions

**Comment by tqchen** [comment]
Now that https://github.com/dmlc/tvm/pull/3374 has been merged, the CI should have been updated to the latest state including the tflite change
