### ISSUE TITLE
RPC context is not identifying gpu device

### ISSUE THREAD

**Issue by andi4191** [dmlc/tvm#3383]
I am attempting to use aarch64-linux-gnu target with (CPU and Nvidia’s GPU). CPU is identified from RPC session but not the same for GPU.

>>> ctx = remote.gpu()
>>> print(ctx.exist)
>>> False
>>>
>>> ctx = remote.cpu()
>>> print(ctx.exist)
>>> True
>>>
>>> ctx = remote.gpu(1)
>>> print(ctx.exist)
>>> False
>>>
>>> ctx = remote.gpu(0)
>>> print(ctx.exist)
>>> False

Also, tried creating the remote context directly with cpu and gpu dev_type to verify. Same behavior

>>> ctx = remote.context(1, 0)
>>> print (ctx.exist)
True
>>> ctx = remote.context(1, 1)
>>> print (ctx.exist)
True
>>> ctx = remote.context(2, 0)
>>> print (ctx.exist)
False
>>> print (ctx.exist)
False

**Comment by eqy** [comment]
Since this is a support question, please open a thread at discuss.tvm.ai.

**Comment by andi4191** [comment]
@eqy: I already did that last week. No response so far.
