### ISSUE TITLE
Tutorials/Docs are break due to frontend API change

### ISSUE THREAD

**Issue by antinucleon** [dmlc/tvm#3399]
Att.. API is changed in https://github.com/dmlc/tvm/pull/3353/files
However doc and tutorials/docs such as AutoTVM are not updated. 

Also I suggest to add a warning of this change, as it breaks all old code.

**Comment by tqchen** [comment]
The RFC was https://github.com/dmlc/tvm/issues/3346 I agree it would be good to raise a bit more attention. @antinucleon can you point out which of the files that haven't been updated?

**Comment by zhiics** [comment]
#3401

@antinucleon Are you aware of any other places might miss the change?

**Comment by antinucleon** [comment]
Can we add a deprecated warning in frontend for 0.6 and remove in 0.7?

**Comment by tqchen** [comment]
Due to the fact that this is a return value, it is harder to deprecate the frontend API this time. Given that this is a major change that is necessary to enable more models(with loops recursion). I suggest we keep the change, but create another RFC notification thread in the forum.
