### ISSUE TITLE
[Frontend][TENSORFLOW] conv2d() got an unexpected keyword argument 'explicit_paddings'

### ISSUE THREAD

**Issue by gasgallo** [dmlc/tvm#3428]
When I run the `tutorial/frontend/from_tensorflow.py` script with my own custom model (ResNet style), I get the following error:
```
Traceback (most recent call last):
  File "/usr/tvm/tutorials/frontend/from_tensorflow.py", line 104, in <module>
    shape=shape_dict)
  File "/usr/tvm/python/tvm/relay/frontend/tensorflow.py", line 2349, in from_tensorflow
    mod, params = g.from_tensorflow(graph, layout, shape, outputs)
  File "/usr/tvm/python/tvm/relay/frontend/tensorflow.py", line 1994, in from_tensorflow
    op = self._convert_operator(node.op, inputs, attr, graph)
  File "/usr/tvm/python/tvm/relay/frontend/tensorflow.py", line 2312, in _convert_operator
    sym = convert_map[op_name](inputs, attrs, self._params)
  File "/usr/tvm/python/tvm/relay/frontend/tensorflow.py", line 469, in _impl
    custom_check=_dimension_constraint())([inputs[0], inputs[1]], attr)
  File "/usr/tvm/python/tvm/relay/frontend/tensorflow.py", line 155, in __call__
    return _get_relay_op(op_name)(*inputs, **new_attrs)
TypeError: conv2d() got an unexpected keyword argument 'explicit_paddings'
```
If I delete the `explicit_padding` attribute when processing my model in `python/tvm/relay/frontend/tensorflow.py` then I don't get any error and everything works fine.

**Comment by tqchen** [comment]
@srkreddy1238 @FrozenGene can you help to take a look?

**Comment by FrozenGene** [comment]
@gasgallo Could you share the model (or reduced model, for example, just one convolution having your problem)? I guess we don't support `explicit_padding `, According to the doc:
```
When explicit padding is used and data_format is "NHWC", this should be in the form [[0, 0], [pad_top, pad_bottom], [pad_left, pad_right], [0, 0]]. When explicit padding used and data_format is "NCHW", this should be in the form [[0, 0], [0, 0], [pad_top, pad_bottom], [pad_left, pad_right]].
```
We shouldn't ignore / delete this attribute. We should insert `pad` operator according to the value.

**Comment by arangrej** [comment]
@FrozenGene I am also facing the same issue on LeNet Mnist model. Please find attached zip containing a .pb file.

[mnist_lenet_bn_1.zip](https://github.com/dmlc/tvm/files/3401649/mnist_lenet_bn_1.zip)

**Comment by FrozenGene** [comment]
@arangrej, thanks for your sharing. I will take a look.

**Comment by FrozenGene** [comment]
> @FrozenGene I am also facing the same issue on LeNet Mnist model. Please find attached zip containing a .pb file.
> 
> [mnist_lenet_bn_1.zip](https://github.com/dmlc/tvm/files/3401649/mnist_lenet_bn_1.zip)

I can not download this zip. Could you upload this file again?

**Comment by FrozenGene** [comment]
> > @FrozenGene I am also facing the same issue on LeNet Mnist model. Please find attached zip containing a .pb file.
> > [mnist_lenet_bn_1.zip](https://github.com/dmlc/tvm/files/3401649/mnist_lenet_bn_1.zip)
> 
> I can not download this zip. Could you upload this file again?

My network issue. I could download it now.

**Comment by FrozenGene** [comment]
@arangrej I think you are using TF version >= 1.14, right? This parameter is introduced since 1.14. I will fix this. This parameter can not be ignored simply.

**Comment by FrozenGene** [comment]
@srkreddy1238 @tqchen Need information of our CI tensorflow. Which version of tensorflow in our CI? 1.13 , 1.14 or 2.0?

**Comment by arangrej** [comment]
@FrozenGene Right. I am using TF 1.14.0

**Comment by FrozenGene** [comment]
If our CI tensorflow is not 1.14, I think we should have one separate PR to upgrade to Tensorflow 1.14. As https://github.com/dmlc/tvm/pull/3427 described, TFLite's related things should be also changed. However, I am not familiar with docker, could someone help to handle this? CC: @apivovarov

**Comment by FrozenGene** [comment]
> @FrozenGene Right. I am using TF 1.14.0

One quick workaround for your model, using TF 1.13.1. Because your model's explict_padding is [] in fact.

**Comment by murdockhou** [comment]
> When I run the `tutorial/frontend/from_tensorflow.py` script with my own custom model (ResNet style), I get the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/tvm/tutorials/frontend/from_tensorflow.py", line 104, in <module>
>     shape=shape_dict)
>   File "/usr/tvm/python/tvm/relay/frontend/tensorflow.py", line 2349, in from_tensorflow
>     mod, params = g.from_tensorflow(graph, layout, shape, outputs)
>   File "/usr/tvm/python/tvm/relay/frontend/tensorflow.py", line 1994, in from_tensorflow
>     op = self._convert_operator(node.op, inputs, attr, graph)
>   File "/usr/tvm/python/tvm/relay/frontend/tensorflow.py", line 2312, in _convert_operator
>     sym = convert_map[op_name](inputs, attrs, self._params)
>   File "/usr/tvm/python/tvm/relay/frontend/tensorflow.py", line 469, in _impl
>     custom_check=_dimension_constraint())([inputs[0], inputs[1]], attr)
>   File "/usr/tvm/python/tvm/relay/frontend/tensorflow.py", line 155, in __call__
>     return _get_relay_op(op_name)(*inputs, **new_attrs)
> TypeError: conv2d() got an unexpected keyword argument 'explicit_paddings'
> ```
> 
> If I delete the `explicit_padding` attribute when processing my model in `python/tvm/relay/frontend/tensorflow.py` then I don't get any error and everything works fine.

hi，could you please tell me  how to delete attri 'explicit_paddings' in tensorflow.py?

**Comment by gasgallo** [comment]
@murdockhou Honestly I don't remember, in the end I converted my model to MXnet that doesn't have that incompatibility.

But quickly looking at the code of `tensorflow.py`, in `__call__` function, before iterating other `attrs` keys, check if `explicit_paddings` is a key and, if so, delete it or skip that key.
You can add this code at line 133:
```
if k == 'explicit_paddings':
    continue
```

**Comment by zhuochenKIDD** [comment]
@murdockhou @gasgallo 

adding ignores=['explicit_paddings'], to AttrCvt construction in 
https://github.com/dmlc/tvm/blob/master/python/tvm/relay/frontend/tensorflow.py#L311

**Comment by EddieBurning** [comment]
@zhuochenKIDD i encountered the same issue, and have tried your way, but the issue still exists, any idea? do you verify the way?

**Comment by OriAlpha** [comment]
you can just get the graph of the TensorFlow and then pop the arguments inside the graph and then you can feed the graph and to the TVM. this will work.  also, you can add the adding ignores=['explicit_paddings'] to the main function but it gives rise to other errors further...

**Comment by tqchen** [comment]
Thanks for all the great discussions, as the original problem is resolved. I am going to close this, future discussions are encouraged in https://discuss.tvm.ai/

**Comment by JFishLover** [comment]
> When I run the `tutorial/frontend/from_tensorflow.py` script with my own custom model (ResNet style), I get the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/tvm/tutorials/frontend/from_tensorflow.py", line 104, in <module>
>     shape=shape_dict)
>   File "/usr/tvm/python/tvm/relay/frontend/tensorflow.py", line 2349, in from_tensorflow
>     mod, params = g.from_tensorflow(graph, layout, shape, outputs)
>   File "/usr/tvm/python/tvm/relay/frontend/tensorflow.py", line 1994, in from_tensorflow
>     op = self._convert_operator(node.op, inputs, attr, graph)
>   File "/usr/tvm/python/tvm/relay/frontend/tensorflow.py", line 2312, in _convert_operator
>     sym = convert_map[op_name](inputs, attrs, self._params)
>   File "/usr/tvm/python/tvm/relay/frontend/tensorflow.py", line 469, in _impl
>     custom_check=_dimension_constraint())([inputs[0], inputs[1]], attr)
>   File "/usr/tvm/python/tvm/relay/frontend/tensorflow.py", line 155, in __call__
>     return _get_relay_op(op_name)(*inputs, **new_attrs)
> TypeError: conv2d() got an unexpected keyword argument 'explicit_paddings'
> ```
> 
> If I delete the `explicit_padding` attribute when processing my model in `python/tvm/relay/frontend/tensorflow.py` then I don't get any error and everything works fine.

your delete aperation gives me an idea, thx
