### ISSUE TITLE
#3353 (frontend API change) breaks Graph tuning in AutoTVM

### ISSUE THREAD

**Issue by loiccordone** [dmlc/tvm#3432]
Hello,
At the tuner definition (see #2184), #3353 now causes:
```
File "/home/renault/tvm/python/tvm/autotvm/graph_tuner/base_graph_tuner.py", line 149, in __init__
    raise RuntimeError("Unsupported graph type: %s" % str(type(graph)))
RuntimeError: Unsupported graph type: <class 'tvm.relay.module.Module'>
```

graph = graph[graph.entry_func] solves the problem but it's not clean, and I don't sufficiently understand the BaseGraphTuner module to make it clean and submit a PR.

Can you look into it please? Thanks 
@kevinthesun @zhiics

**Comment by zhiics** [comment]
I think we can just add a checker before

https://github.com/dmlc/tvm/blob/master/python/tvm/autotvm/graph_tuner/base_graph_tuner.py#L143

```python
if isinstance(graph, relay.Module)
    graph = graph[mod.entry_func]
```

**Comment by kevinthesun** [comment]
https://github.com/dmlc/tvm/pull/3434
