### ISSUE TITLE
[Tutorial] tensorflow frontend tutorial specification of tensorflow version

### ISSUE THREAD

**Issue by Shawhey** [dmlc/tvm#3454]
The current TF frontend tutorial python file may throw exception under TF 1.14. May TVM developers specify under which version TF the tutorial was written and tested?

https://discuss.tvm.ai/t/cannot-run-tutorials-frontendl-from-tensorflow-py/3143

**Comment by tqchen** [comment]
Thanks for bringing this up, please open a new thread on https://discuss.tvm.ai/
