### ISSUE TITLE
[RFC][ARITH] Introduce FloorDiv/Mod for Context-Independent Simplifications

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#3478]
Many parts of our code base rely on integer simplifications that involves div/mod. These simplifications are in particular tricky due to the different division mode, and the dependence on knowing the sign of the operand.

### Trunc div/mod
IEEE standard integer division is truncated division, directly maps to the hardware. This is the division used by C and TVM by default. The problem of trunc div is that we usually relies on knowing the sign of both operands. For example, we cannot simplify ```(x * 4 + 3)/4 => x ``` if x can be negative.

### Floor div/mod
Always round down. This is the division mode adopted by python. To simplify floordiv, we usually need to know the sign of divisor, but not necessarily the sign of dividend  ```floordiv(x * 4 + 3,4) => x ```. 

### Euclidean div/mod
Always ensures that the remainder is non-negative. This is the division mode used by Halide by default. Note that when the divisor is positive, Euclidean and floordiv are equivalent. But floordiv will produce a negative remainder when the divisor is negative.

## Discussion

Different division mode has its own advantage and disadvantages. While Floor and Euclidean mode enjoys better invariance in simplification. However, we don't really want to emit those operators in the low-level code, as we cannot find direct instruction correspondence. So ideally we will need to lower them back to truc div/mod after simplification is done, in which case we still want to know the sign of the operands. In summary, the two ways are:

- Always use trunc div, but need to know sign of the operands during every transformation
- Use floor/euclidean div, no need to know the sign of dividend during simplification, but need to know the sign when lowering back to trunc div.
   - We also need to be aware of potential risk of over-simplification (simplify something to a floordiv where we don't know the sign of dividend)

To give a concrete example about the difference, consider the following case:

```c++
for (x = 0; x < 100; x++) {
   // trunc division
   a [(x * 4 + 3)/ 4] =  xyz.
}
```
```(x * 5 + 3)/4``` can be simplified to (x * 5 /4) , if we setup the simplifier, with currect context(```x in [0, 100]```). However, there can be cases where we forget to do so in our code, i that scenario the simplifcation cannot be done. If instead we use

```c++
for (x = 0; x < 100; x++) {
   // floor division
   a [floordiv(x * 4 + 3, 4)] =  xyz.
}
```

```(x * 4 + 3)/4``` can be simplified to x in the analysis. However, to get the most efficient version of the code. We need to lower the floor division to ```x ``` knowing that x is non-negative. The context information is only needed during the floor division lowering.

In summary, using trunc div during analysis requires m
ore information each time we transform it, using floor/euclidean div makes simplification easier, but still requires us to provide context information to most efficiently lowers to trunc div/mod.

## Proposal to be Discussed: Adding Floor Div/Mod

It might be helpful to encourage the use of floor div/mod for integer analysis while providing an effective way to lower to trunc div when necessary. To avoid confusion between division mode, I propose we add an explicit floordiv/floormod node and operator to the IR. 

The reason to choose floordiv/mod over Euclidean is mainly due to floor is more common(used by python) and easier to understand. The difference in behavior happens when the divisor is negative. In most cases, we will know the sign of divisor.

The original truc div/mod simplification will be kept around for a while, but we will encourage most index calculations to use floordiv/mod, and provide rewriter to rewrite truc div/mod into floor version when the sign of the dividend is positive

## Embed more information in the IR

Besides introducing floor div/mod to make the transformation context independent. We can also start to think about embedding more information in the IR.  For example, in the case of ```(x * 4 + 3) / 4```, if we directly embed the bound information about x inside the Var itself, we can directly do the same analysis without manually injecting the context information to the analyzer. This is an interesting design trade-off that we might want to consider in the future.

**Comment by tqchen** [comment]
cc @dmlc/tvm-team

**Comment by jroesch** [comment]
Can you clarify the example above? the simplifications seem invalid to me, how can you drop the addition by 3?

**Comment by tqchen** [comment]
Sorry it should be ```(x * 4 + 3) / 4=>x```

**Comment by tqchen** [comment]
@derisavi @sgrechanik-h @yzhliu @wweic  @merrymercy would be great to also get your thoughts about this.

**Comment by sgrechanik-h** [comment]
I think Euclidean division should be preferred since it is used in Halide and smt-lib, which I think are more relevant than python (e.g. it will be easier to borrow algorithms from Halide and to use SMT solvers to perform some proofs if we ever need it).

**Comment by tqchen** [comment]
I agree that Euclidean and Floor could be an interesting tradeoff. 

When possible, I want to be able to make most of the proofs internally. This is especially true with respect to div/mod simplifications. Given that the division/mod we will ever encounter will most likely have positive divisor, they are just fine and can be viewed as Euclidean if necessary.

I think the main reason to choose floordiv (along with trunc-div support) was to have fewer surprises. For the same reason, we default Div to serve the same behavior as C's division, so the developer won't get confused. Given that floordiv and euclidean div will give us a similar effect for the things we care about, being able to match python's semantics and easy to understand would be a plus here, and that is why I think FloorDiv/Mod should be preferred.

**Comment by derisavi** [comment]
Not sure whether the decision has already been done but I'll put my two cents here.

You have covered all the tradeoffs. Since in most cases, the divisor is positive, I believe the important move was to add one of floordiv or euclideandiv (which you are doing now). The difference between floordiv and euclideandiv will not have drastic effect on how much we can simplify the code.

Nevertheless, IMHO, we should choose Euclidean for the followin reasons:
1) it's more important to care about ease/strength of simplification and analysis and less about familiarity. 
2) familiarity is a subjective matter and it depends on the audience. The audience of this operator (and in general Halide IR) are mostly people who are developing the core compiler. In the long run, this audience cares mostly about what's more powerful in terms of analysis, simplification, and interoperability with other libs and I expect people to become familiar (if they are not already) with euclideandiv very quickly.

**Comment by tqchen** [comment]
Thanks, @derisavi @sgrechanik-h for putting in your thoughts. Let me try to summarize the trade-offs dimensions so far.

## Power of simplification
- They are going to be similar because in most cases divisors are positive.
- Floordiv and euclidean div are the same when divisors are positive.

## Consistency with Existing Choices
- Floordiv is used by python, which means we could in the future change operator overload in python to make use of it for better consistency.
- Euclidean div is used by Halide and smt-libs.
- Floordiv seems was used by isl and MLIR.

## Developer familarity
Floordiv is relatively easier to explain, and can be written as ```floor(a/b)```. Low-level compiler developers might be able to understand both after some time.

## Cost of Lowering
Need to think about the cost of lowering: 
- When both signs of dividend and divisor are known, can lower to trunc div
- When sign of divisor is known, floordiv and eucildean div are can have the same rule.
- A bit unclear when the sign of divisor is unknown, which I hope would never happen, but need to discuss the rules.

**Comment by tqchen** [comment]
To summarize the discussion so far. I think everyone agrees that we should introduce one of FloorDiv or EuclideanDiv, and this is a pretty close call (see the technical summary above).

@derisavi @sgrechanik-h suggested eucildean div for the reason of being consistent with Halide smt-libs. My understanding atm is that while we have different thoughts, we mostly agree that adding either floordiv or eucildean div would be a good improvement. We just need to decide which one. I am still slightly lean toward floordiv given that it is conceptually easier and consistent with python3, MLIR, but would still love to hear further thoughts if we have a strong opinion against the choice.

**Comment by yzhliu** [comment]
+0.5 to floordiv given the familarity and the usage in isl and MLIR.

**Comment by wweic** [comment]
I also prefer floordiv as its use in MLIR.

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/issues/3977

**Comment by tqchen** [comment]
Move the thread to https://github.com/dmlc/tvm/issues/3977
