### ISSUE TITLE
how to get the config log of nvidia gpu p4 for int8 mode using autotvm

### ISSUE THREAD

**Issue by herbiezhao** [dmlc/tvm#3484]
https://docs.tvm.ai/tutorials/autotvm/tune_relay_cuda.html
The tutorial gives us the example of creating config log for different gpu devices. But the config type  is float32.
How to get the config log of nvidia gpu p4 for int8 mode using autotvm.
Could you give me some examples？

**Comment by tqchen** [comment]
Please use https://discuss.tvm.ai/ for related questions
