### ISSUE TITLE
LLVM installation problem

### ISSUE THREAD

**Issue by ysh329** [dmlc/tvm#351]
I'm going to install tvm on arm platform, but after executing `apt update` and `apt install llvm`. I found the version of LLVM, which apt source providede, is 3.8. However, tvm requires minimal version of LLVM is 4.0. 

Thus, I go to [LLVM Download Page](http://releases.llvm.org/download.html#4.0.1) and [LLVM Debian/Ubuntu nightly packages](https://apt.llvm.org/). I'm confused which version should I download from [LLVM Download Page](http://releases.llvm.org/download.html#4.0.1), or build from source code? Another question, I'm also confused about page [LLVM Debian/Ubuntu nightly packages](https://apt.llvm.org/), can APT auto-install/choose verison of LLVM and how to configure? 

Hope anyone could give any advice or suggestions. Thanks in advance.

**Comment by ZihengJiang** [comment]
Try `LLVM 4.0.0 Clang for x86_64 Ubuntu (.sig)` in [LLVM Download Page]( http://releases.llvm.org/download.html) if you use linux.

**Comment by ysh329** [comment]
@ZihengJiang Thanks

**Comment by ysh329** [comment]
How To Cross-Compile Clang/LLVM using Clang/LLVM — LLVM 6 documentation
https://llvm.org/docs/HowToCrossCompileLLVM.html

**Comment by ysh329** [comment]
How To Build On ARM — LLVM 6 documentation
https://llvm.org/docs/HowToBuildOnARM.html

**Comment by tqchen** [comment]
@ysh329 a reminder, you do not have to build llvm on arm. We can use tvm on your server and do cross compile, see http://docs.tvmlang.org/tutorials/cross_compilation_and_rpc.html
