### ISSUE TITLE
Support ROCm

### ISSUE THREAD

**Issue by adityaatluri** [dmlc/tvm#353]
Hi,
Do you have plans for supporting AMDGPU backend through ROCm?

**Comment by tqchen** [comment]
Amd gpu should already been supported via Opencl. 

We can add additional  support to HIP or HSa, if there is reason to do so

**Comment by tqchen** [comment]
Of course contribution is more than welcomed

**Comment by adityaatluri** [comment]
I would like to discuss more about the architecture of how ROCm code will be organized. Can I shoot you a detailed mail at: tqchen@cs.washington.edu ?

**Comment by tqchen** [comment]
Yes please

**Comment by tqchen** [comment]
OK, here is an issue to check this https://github.com/dmlc/tvm/issues/360
