### ISSUE TITLE
[RFC] Deprecation

### ISSUE THREAD

**Issue by MarisaKirisame** [dmlc/tvm#3530]
Currently, when we want to deprecate a feature, we add LOG(WARNING) or warning at python side. However, they do slowly creep back into the master's CI.
For example, I once removed all deprecation warning at build_module.py:186, but it got reintroduced to the CI.
![image](https://user-images.githubusercontent.com/3397377/61006726-d6870f80-a31f-11e9-985e-e127c2924729.png)
I proposed that we add a deprecate(msg, version, ci_count) to battle this.
`msg` is the warning messaged print.
`version` is the version number that this feature will go completely unsupported. If the current version is greater or equal then `version`, it will be an error rather than a warning.
`ci_count` is the number of time this function could be called. after it got exceed it will fail the ci. this will stop pr that add more deprecated used to pass the ci.

**Comment by tqchen** [comment]
It is a bit harder to build into the CI infra, but would be great if we could work to fix deprecation warnings as much as we can

**Comment by tqchen** [comment]
Close this RFC for now as it has been inactive
