### ISSUE TITLE
Support LLVM Mainline

### ISSUE THREAD

**Issue by Andrechang** [dmlc/tvm#354]
I am using llvm 5.0.0svn and enabled the LLVM flag in make/config.mk
but it gives this error.
```
src/codegen/llvm/llvm_common.cc: In function ‘llvm::TargetMachine* tvm::codegen::GetLLVMTargetMachine(const string&, bool)’:
src/codegen/llvm/llvm_common.cc:100:7: error: ‘class llvm::TargetOptions’ has no member named ‘LessPreciseFPMADOption’
   opt.LessPreciseFPMADOption = true;
```
I wasn't able to find LessPreciseFPMADOption in TargetOptions.h
I think they removed this for later llvm
https://www.mail-archive.com/cfe-commits@lists.llvm.org/msg52412.html

**Comment by tqchen** [comment]
You are right, we need to add support for mainline llvm. For now please use llvm4.0

**Comment by tqchen** [comment]
Should be fixed by #356

**Comment by xqdan** [comment]
got this issue when building directly using LLVM 6.0 on my local machine. How to fix it, thanks!

**Comment by tqchen** [comment]
PLease use the latest code from master, which should already resolved this issue
