### ISSUE TITLE
NNVM compiler doesn't support tensors. Crashes with "AttributeError: 'Tensor' object has no attribute 'node'"

### ISSUE THREAD

**Issue by vsahil** [dmlc/tvm#3542]
I was trying to use NNVM compiler for a toy TF program, but could not get it compiled, because the model was a tensor. I have the file attached. It was run on CPU machine running Ubuntu 18, TF version 1.8.0. 

[singlefile.zip](https://github.com/dmlc/tvm/files/3389331/singlefile.zip)

**Comment by tqchen** [comment]
Please open a new thread in discuss.tvm.ai
