### ISSUE TITLE
`tvm::ir::Simplify` no longer simplifies `let` 

### ISSUE THREAD

**Issue by yinghai** [dmlc/tvm#3547]
It seems that after https://github.com/dmlc/tvm/pull/3368, the `tvm::ir::Simplify` no longer simplifies `let` statement. The following stmt can be reduced to `20` previously
```
let n = 20 in n
```
But now it's no longer the case. 

cc: @ajtulloch @tqchen

**Comment by tqchen** [comment]
This is a case that was overlooked in the new infra, we can send a patch to add it back
