### ISSUE TITLE
How can I get the Intermediate results using debug_get_output(All the Intermediate results are wrong except the final result)?

### ISSUE THREAD

**Issue by LilAiTT** [dmlc/tvm#3548]
I load the model from onnx and use debug_get_output(nodename, out) from debug_runtime trying to get the Intermediate results. But all the Intermediate results are wrong except the final results.  Here is my part of codes(Not complete for pithy).
`from tvm.contrib.debugger import debug_runtime as graph_runtime`

`m.run()`

`inA = np.array([])`
`outT = []`

`for nodename in nodenames:`

     `outT.append(m.debug_get_output('fused_nn_relu_4_0', inA).asnumpy())`

eg:The relu operation in my onnx model is max(x, 0) but there are many negative  numbers in the debug_runtime version relu results. Another example is that the final dense result is the same as the final softmax. So much unbeliveable  results just happended. It's weird and I can't figure it out through my tough trying. Crying for help~plz

**Comment by tqchen** [comment]
Please open a new thread on discuss.tvm.ai
