### ISSUE TITLE
How to add new hardware backend to TVM

### ISSUE THREAD

**Issue by crazyhank** [dmlc/tvm#3549]
TVM now supports X86, Nvidia GPU, ARM, I wonder how can I add a new hardware backend, for example an asic AI chip to TVM stack, is there some general guide?

**Comment by Ravenwater** [comment]
@crazyhank  the discussion group has one discussion: 
https://discuss.tvm.ai/t/tensor-expression-add-hardware-specific-schedule/1893

Anyone working on a RISC-V port?

**Comment by tqchen** [comment]
Please move discussions to the discuss forum
