### ISSUE TITLE
Autotvm skips depthwise_conv2d_nchw workloads for llvm x86_64

### ISSUE THREAD

**Issue by apivovarov** [dmlc/tvm#3557]
Details: https://discuss.tvm.ai/t/autotvm-skips-depthwise-conv2d-nchw-workloads-for-llvm-x86-64/3353/1

Problematic PR: https://github.com/dmlc/tvm/pull/3264

**Comment by tqchen** [comment]
Let us keep the discussion in the discuss forum, once we have an actionable item, we can have an issue tracker to track it
