### ISSUE TITLE
[TOPI][C++]conv2d_nchw mistake?

### ISSUE THREAD

**Issue by zacario-li** [dmlc/tvm#3562]
Hi,
    file: topi/include/topi/nn.h
    conv2d_nchw()
    `T(b, i, stride_h * h + kh, stride_w * w + kw) * W(i, o, kh, kw)`
    I think `W(i, o, kh, kw)` should be `W(o, i, kh, kw)`, am I right?
    
@ashokei

**Comment by tqchen** [comment]
This seems to be indeed a mistake. @zacario-li can you send in a patch?
