### ISSUE TITLE
AttributeError: module tvm.relay._make has no attribute Any

### ISSUE THREAD

**Issue by SerenaC94** [dmlc/tvm#3576]
Hi,
I updated TVM with a `git pull`, and now any program that uses Relay returns the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/curzel/tvm/python/tvm/relay/__init__.py", line 22, in <module>
    from . import ty
  File "/home/curzel/tvm/python/tvm/relay/ty.py", line 23, in <module>
    Any = _make.Any
AttributeError: module 'tvm.relay._make' has no attribute 'Any'

```

It's been some days and I found nobody else reporting this on the discussion forum, so could it be my fault? Did I miss some change in the way Relay is imported in python?

**Comment by wweic** [comment]
Hi @SerenaC94, we usually use https://discuss.tvm.ai/ for questions. Also please provide the code you use to produce such error.

**Comment by SerenaC94** [comment]
> we usually use https://discuss.tvm.ai/ for questions. 

I am aware of that, but I wrote the same thing there last week and there was no answer

> Also please provide the code you use to produce such error.

That was the error when writing
`from tvm import relay`
in a python3 prompt

**Comment by tqchen** [comment]
Would be great if you can update on the discuss thread. The reason that you get the errror was likely due to you did not rebuild the libtvm.so

**Comment by SerenaC94** [comment]
Ok, thanks. That is probably the issue, I will update the discussion thread if anything else comes up.

**Comment by pfk-beta** [comment]
In my situation, I had only tvm_runtime. After building whole tvm, and reinstalling python, it works.
