### ISSUE TITLE
[Relay] Possible bug in multi-target code

### ISSUE THREAD

**Issue by gussmith23** [dmlc/tvm#3579]
https://github.com/dmlc/tvm/blob/e686da79198f7a25f7ca13ed125c8e90d6886e32/src/relay/backend/build_module.cc#L315-L322

I think the `==` here should be a `!=`. I don't have a broken test case or anything; I just ran into this code today and other Relay developers said it looks like a bug. If it's not a bug, perhaps add a comment as to what's going on?

cc @zhiics @antinucleon

**Comment by zhiics** [comment]
I think it should be `==`. It means that we only do target dependent optimization (e.g. layout alteration) for homogeneous execution. I guess the reason why we have the for loop here is because we cannot get the first element directly?

**Comment by tqchen** [comment]
it is quite subtle, perhaps a comment on the codeblock, @zhiics please act and close this

**Comment by zhiics** [comment]
close by #4091
