### ISSUE TITLE
[RFC][relay][vm] Relay virtual machine serialization

### ISSUE THREAD

**Issue by zhiics** [dmlc/tvm#3594]
# VM Serialization

Serializing and deserializing the bytecode emitted by the Relay VM is a must as we may want to save the model and run it later. Previously, Relay has produced a serialized form in a json file for the graph runtime to reuse the runtime and keep backward compatibility to NNVM. However, the same format is not directly applicable to the VM as it emits bytecode instead of graph-style programs. Therefore, this RFC attempts to design a new serialization format for the VM.

## Components need to be serialized/saved:

- Bytecode
- Globals
- Constants
- Lowered code for relay primitives (HW dependent)

## Proposed Design

VM has the following fields to be handled:

```c++
std::vector<VMFunction> functions  
std::vector<Object> constants  
std::unordered_map<GlobalVar, size_t> global_map  
runtime::module lib
```

### Serialization: Relay VM -> Bytecode + HW dependent library
Serialization separates the VM into two parts. The hardware dependent module/library and Relay VM related part (e.g. constant pool and bytecode, etc.). After serialization, we could therefore have 3 files, param, lib, and code. The first two have been widely used in the TVM codebase. We here only focus on serializing the VM into the serialized form that contains multiple sections, namely global section, constant section, and code section. The serialized code could be directly stored to disk.

- `global_map` serialization -> Global section
	  This map contains globals (`string`) to their index (`int`) mapping. The serialization therefore only needs to consider about the C++ built-in types which are easy to handle.
- `constants` serialization -> constant section
 `constants` are essentially tensor objects. Therefore, `constants` serialization is boiled down to `NDArray` serialization. Fortunately, TVM has supported the serialization of `params` which should simplify the serialization of `constants`.
- `functions` serialization -> code section
	  functions are essentially VMFunction objects.
	  A VMFunction is serialized as the following:
	  
	   func_name, register_file_size, num_instructions
	   param1, param2, ..., paramN
	   instruction1
	   instruction2
	   ...
	   instructionN
		  
	 Serializing an VM instruction requires us to deal with the bytecode. Each line of them could be formatted as the following:
	
	   hash, opcode, f1, f2, ..., fN, field with variable length
	   1. hash: the hash of the serialized instruction. It will be used for sanity check when decoding a serialized instruction.
	   2. opcode: the opcode code of the instruction.
	   3. f1, f2, ..., fN. These fields together represent the fixed fields in an instruction, e.g. from and dst fields Move instruction. Note that `DLDataType` will be unpacked into three fields (code, bits, lanes).
	   4. The rest of the line indicates the field with variable length. For example, the shape of tensor, the args used for an invokpacked instruction, etc.
	Suppose we have an instruction `inst` which is an `AllocTensor` instruction. This instruction has the 3 fields (type), `dtype` (`DLDataType`), `dst` register (`int64_t`), and `shape`(`std::vector<int64_t>`). The length of the first two fields are fixed, but it varies for the `shape` field. We will serialize this instruction into the following format:
	 5, `4 + inst.alloc_tensor.ndim`, `dtype.code`, `dtype.bits`, `dtype.lanes`, `dst_register`, `val1,` `val2`, ..., `valN`
	 - 5 is opcode of `AllocTensor`.
	 - `4 + inst.alloc_tensor.ndim` is the total length of this instruction, where 4 includes the size of both `DLDataType` and `dst_register`, `inst.alloc_tensor.ndim` is the dimension of the tensor to be allocated.
	 - The next three fields represent the serialization of the `dtype`.
	 - `dst_register` is the id of the destination register.
	 - The rest of the instruction, `val*`, saves the size of each dimension. For example, it could `[10, 10]` if the tensor to be allocated is 2-dimensional and the size of each dimensional is 10.
 - `packed_funcs` serialization
	   `packed_funcs` are essentially lowered code obtained from a `runtime::module`. We therefore only need to save the runtime module into a library directly.

#### The design:
```c++  
	class Serializer : public runtime::Module {  
	  public:    
		// Print the detailed info of the given code, i.e. number of vars  
		// and constants, etc.  
		std::string GetByteCode() const;
		// Get the library that contains hardware dependent code for primitive ops.
		runtime::Module GetLib();
		// More helpers
		// ...
		// Serialize the information in vm_  
		TVMByteArray Serialize();
		  
	  private:		
		void SerializeGlobalSection();
		void SerializeConstantSection();
		void SerializeCodeSection();
		void SerializePrimitiveOpNames();

		std::shared_ptr<VirtualMachine> vm_;
		dmlc::Stream* strm_;
	};
```

### Deserialization: Bytecode + HW dependent library -> Relay VM

Deserializer targets the given bytecode and saved library emitted by the serializer. Its major work is to extract the information from these files and set up the corresponding field of a Relay virtual machine.

```c++
class Deserializer : public runtime::Module {  
 public:  
  void Init(const std::string& code, const& runtime::Module& lib);  

  std::shared_ptr<VirutalMachine> Deserialize();
  
private:  
  void DeserializeGlobalSection();
  void DeserializeConstantSection();
  void DeserializePrimitiveOpNames();
  void DeserializeCodeSection();

  std::shared_ptr<VirutalMachine> vm_;
  std::string code_;
  dmlc::*strm_ strm_;
};
```

## Example
```python
# serialize.
ser = relay.serializer.Serializer(vm)
code = ser.serialize()
lib = ser.lib
# save and load the code and lib file.
tmp = tvm.contrib.util.tempdir()
path_lib = tmp.relpath("lib.so")
lib.export_library(path_lib)

with open(tmp.relpath("code.bc"), "wb") as fo:
	fo.write(code)
loaded_lib = tvm.module.load(path_lib)
loaded_code = bytearray(open(tmp.relpath("code.bc"), "rb").read())

# deserialize.
deser = relay.deserializer.Deserializer(loaded_code, loaded_lib)
des_vm = deser.deserialize()
# execute the deserialized vm.
des_vm.init(ctx)
res = des_vm.run(args)
```

cc @jroesch @tqchen @icemelon9 @slyubomirsky @wweic @MarisaKirisame @yongwww @ajtulloch

**Comment by icemelon9** [comment]
One question I have is whether we should put `length` of *all fields* in the beginning, or just put the `length` of *one array field* `val*` immediately before this field. It's possible that we may have an instruction with more than one field that are arrays in the future. However, the current design is not able to support this case.

**Comment by MarisaKirisame** [comment]
I imagine not all opcode has variable length. Is there a need for the length field? Can we just has a optional variable_length field that just store length of all of the variable length field?

**Comment by zhiics** [comment]
@icemelon9 Yeah, thanks. Putting the `length` before the filed with variable length seems reasonable.

**Comment by zhiics** [comment]
@MarisaKirisame I think we need it to make deserialization easier. Otherwise, we may need many checks.

**Comment by zhiics** [comment]
@icemelon9 we probably don't need to have the length for each field with variable length because we should be able to derive it based on the fixed fields? It means we usually put the length of it as a field of an instruction, right?

**Comment by icemelon9** [comment]
@zhiics I mean if there are two fields with variable length, though not very likely, what do you plan to support? Also do we expect every fields have same data type? Another point Marisa is making that we don't need to put `length` for every instructions since many have fixed length.

**Comment by zhiics** [comment]
@icemelon9 The length is mainly for sanity check before we decode the instructions. We could remove it. There could be multiple fields with variable length. I thought we should always have a field in the fixed field to indicate the length of the variable one, is this right? 

For example, https://github.com/dmlc/tvm/blob/master/src/runtime/vm/vm.cc#L272

**Comment by tqchen** [comment]
Some high level comment: the interface of the serializer should be implementation details and should not be exposed. 

I think we should focus on the serialization format(text and bytecode), which could be more important(as we can always change the implementations)

**Comment by zhiics** [comment]
@tqchen My bad. The APIs started with `Serialize` and `Deserialize` are actually not exposed.

**Comment by wweic** [comment]
Could you also comment on how to encode heterogeneous execution information?

**Comment by zhiics** [comment]
I feel heterogenous execution will be mainly related to memory management in the VM. We don't need to encode any information in VM for the compilation and codegen. I think we probably need to handle `AllocTensor` a little differently, e.g. making it device aware.

**Comment by kuonangzhe** [comment]
Does serialization/deserialization handles the quantized models? Currently the quantized model cannot be used when loaded from saved files.

**Comment by zhiics** [comment]
The serialization itself doesn't have much to do with quantization. If quantized model needs new opcode in the VM, we need to introduce them first and then extend the serialization/deserialization to support these instructions.

**Comment by zhiics** [comment]
#3647
