### ISSUE TITLE
[Backend] ROCm/HSA Support for AMD GPUs

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#360]
Here is a detailed issue for Rocm support
## CheckList
- [x] Rocm runtime in  to load and run Rocm related binaries 
   - reference src/runtime/opencl, src/runtime/cuda, src/runtime/metal
   - [x]  Pass test https://github.com/dmlc/tvm/blob/master/tests/python/unittest/test_runtime_ndarray.py
- [x] LLVM codegen for hsa
     - We already added support for mainline, so can pick either 5.0 or 6.0 depend on the availability of exsiting gpu backends. 
     - Use TVM_LLVM_VERSION to guard in case only a few version of LLVM is supported. Use pragma error to report error, if ROCM is enabled but LLVM version does not match requirement
- [x] Add Rocm toolchain(seems to be libhcc given the current Makefile) to our docker image used by jenkins c.f. https://github.com/dmlc/tvm/blob/master/tests/ci_build/Dockerfile.gpu  
     - Basically we need a bash script that download and setup related things.
     - Please provide a prebuild script first and let us do some verification, as changing  docker image a lot costs a lot of spaces
     - It would be nice if there is pre-build binary available.
- [x] Integration cases pass by adding "rocm" as a target in tests/python/integration

## Questions to discuss
- Can we reuse opencl's runtime or do we need a special device type and runtime for rocm? what are the benefits?

**Comment by tqchen** [comment]
cc @adityaatluri @vchuravy

**Comment by JammyZhou** [comment]
I think the OpenCL runtime is different from what AMD is doing for HIP and MIOpen, which is their new focus for machine learning based on the ROCm platform. So to have better support for AMD GPUs, adding a separate backend seems reasonable.

**Comment by tqchen** [comment]
close this for now. As a basic milestone of rocm backend has been reached. thanks to @adityaatluri and @masahi
