### ISSUE TITLE
vta_config problem!

### ISSUE THREAD

**Issue by patrick20190725** [dmlc/tvm#3625]
when I change the vta_config.json configuration，it will display that A fallback configuration is used, which may bring great performance regression. and the amount of  loaded data and weight is huge. How to configure the correct parameters?
![VTA config](https://user-images.githubusercontent.com/53302474/61874941-24089c80-af1c-11e9-9a8e-3b908c786372.png)
![tvm issue](https://user-images.githubusercontent.com/53302474/61874949-27038d00-af1c-11e9-9060-c830dc921753.png)
![tvm issue2](https://user-images.githubusercontent.com/53302474/61874951-28cd5080-af1c-11e9-8b62-0446c9140bd1.png)

**Comment by tqchen** [comment]
Thanks for reporting the problem. Please use https://discuss.tvm.ai/ to involve more community members
