### ISSUE TITLE
compile error for IRPrinter.cpp with MSVC14 on x86_64 Windows7 machine

### ISSUE THREAD

**Issue by li7hui** [dmlc/tvm#363]
hi i got the multi template instantilization problem when compiling IRPrinter.cpp (line 105)with MSVC14 on x86_64 on Windows 7 machine.      it complains about two candidate templates, one is 

tvm::IRFunctor<void (const tvm::NodeRef &,Halide::Internal::IRPrinter *)> &tvm::IRFunctor<void (const tvm::NodeRef &,Halide::Internal::IRPrinter *)>::set_dispatch<Halide::Internal::IntImm>(std::function<R (const Halide::Internal::IntImm *,Halide::Internal::IRPrinter *)>)

the other is 
tvm::IRFunctor<void (const tvm::NodeRef &,Halide::Internal::IRPrinter *)> &tvm::IRFunctor<void (const tvm::NodeRef &,Halide::Internal::IRPrinter *)>::set_dispatch<Halide::Internal::IntImm>(std::function<R (const tvm::NodeRef &,Halide::Internal::IRPrinter *)>)”

btw my __cpulsplus in MSVC is 199711. the code goes through with my centos gcc 4.8.5 with c++11

**Comment by tqchen** [comment]
@sxjscience Do you know if we need a higher version of MSVC?

**Comment by li7hui** [comment]
that could be
it seems that lamda expression is not well support in MSVC14.

**Comment by sxjscience** [comment]
I'm using VS 2015 Update 3

**Comment by li7hui** [comment]
ok , i will try later, thanks

**Comment by tqchen** [comment]
@sxjscience can you open a PR to installation guide to add the minimum requirement? Thanks!

**Comment by sxjscience** [comment]
@tqchen OK, I'll do it soon.

**Comment by li7hui** [comment]
you can close this issue, it works now by using VS 2015 Update 3. thanks.
