### ISSUE TITLE
[TOPI] conv2d schedule code

### ISSUE THREAD

**Issue by mingwayzhang** [dmlc/tvm#3648]
We find a potential issue in the following line of the code:

[https://github.com/dmlc/tvm/blob/master/topi/python/topi/cuda/conv2d_direct.py#L93](https://github.com/dmlc/tvm/blob/master/topi/python/topi/cuda/conv2d_direct.py#L93)

Line 93: `ryo, ryi = cfg['tile_rx'].apply(s, OL, ry)`

Should `tile_rx` be `tile_ry`?

**Comment by merrymercy** [comment]
Good catch. This is a bug when KH != KW.
We have to fix the schedule code and update records in TopHub.  Other users should also update their local autotvm records.

**Comment by mingwayzhang** [comment]
could I submit a patch to fix this?

**Comment by merrymercy** [comment]
Thanks! Please also update the latest version of record here https://github.com/uwsampl/tvm-distro/tree/master/tophub

**Comment by mingwayzhang** [comment]
Do you mean I need to exchange the value of tile_x and tile_y in all these files? Please clarify. Thanks.

**Comment by merrymercy** [comment]
1. Exchange `tile_rx` and `tile_ry` in `tvm-distro/tophub/cuda_v0.04.log`, and save it to `tvm-distro/tophub/cuda_v0.05.log`
2. Update the version number in https://github.com/dmlc/tvm/blob/83591aa5a139108976baf3febc7263c6f069ce9c/python/tvm/autotvm/tophub.py#L42

**Comment by merrymercy** [comment]
@mingwayzhang any updates?

**Comment by mingwayzhang** [comment]
will finish it ASAP. Sorry about the delay.
