### ISSUE TITLE
how to convert tensorflow saved models to pb models which can be run on tvm?

### ISSUE THREAD

**Issue by chenaili6** [dmlc/tvm#3659]
Take inception-v1 for example, I used tf-to-nvmm.py to convert the original tensorflow pb model, frozen_inception_v1.pb, to frozen_inception_v1-shapes.pb, but when the frozen_inception_v1-shapes.pb was run on tutorials/frontend/from_tensorflow.py, an error occurred :

 /home/tvm/src/runtime/graph/graph_runtime.cc:94: Warning: cannot find "DecodeJpeg/contents" among input
Traceback (most recent call last):
  File "from_tensorflow_v1.py", line 158, in <module>
    m.set_input('DecodeJpeg/contents', tvm.nd.array(x.astype(dtype)))
  File "/home/chenaili/tvm/python/tvm/contrib/graph_runtime.py", line 149, in set_input
    self._get_input(key).copyfrom(value)
  File "/home/chenaili/tvm/python/tvm/_ffi/_ctypes/function.py", line 209, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (3) /home/chenaili/tvm/build/libtvm.so(TVMFuncCall+0x48) [0x7fe4804cc588]
  [bt] (2) /home/chenaili/tvm/build/libtvm.so(+0xef92ab) [0x7fe4805272ab]
  [bt] (1) /home/chenaili/tvm/build/libtvm.so(+0xef9195) [0x7fe480527195]
  [bt] (0) /home/chenaili/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x24) [0x7fe47fdc94f4]
  File "/home/chenaili/tvm/src/runtime/graph/graph_runtime.cc", line 450
TVMError: Check failed: in_idx >= 0 (-1 vs. 0) :

**Comment by yongwww** [comment]
You can feed savedmodel into tf converter as below, relay version is recommended. 
```
from tvm.relay.frontend.tensorflow_parser import TFParser
model_dir = <your savedmodel dir>
graph_def = TFParser(model_dir).parse()
sym, params = relay.frontend.from_tensorflow(graph_def) or nnvm.frontend.from_tensorflow(graph_def)
```

**Comment by tqchen** [comment]
Please use for related questions https://discuss.tvm.ai/:)
