### ISSUE TITLE
docker: tvm.ci_cpu docker image fails to build

### ISSUE THREAD

**Issue by mshawcroft** [dmlc/tvm#3696]
The ci_cpu docker image currently fails to build, issue appears to be in:

Step 15/29 : RUN bash /install/ubuntu_install_rust.sh

Which results in 12 build errors, first of which is:

   Compiling tokio-service v0.1.0
error[E0412]: cannot find type `NonZeroI8` in module `num`
    --> /opt/rust/registry/src/github.com-1ecc6299db9ec823/serde-1.0.98/src/de/impls.rs:2416:5
     |
2416 |     NonZeroI8,
     |     ^^^^^^^^^ help: a struct with a similar name exists: `NonZeroU8`

**Comment by mshawcroft** [comment]
@nhynes are you able to help with this?

**Comment by nhynes** [comment]
Is this still an issue?

**Comment by mshawcroft** [comment]
Yep still an issue.

**Comment by tqchen** [comment]
can also confirm locally. cc @tmoreau89 the docker rebuild will likely depend on this as well.

**Comment by tmoreau89** [comment]
Reopening as it seems to be affecting some PRs: 
https://github.com/dmlc/tvm/pull/3772
https://github.com/dmlc/tvm/pull/3762

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/4019
