### ISSUE TITLE
[PY test failure][llvm codegen] test_codegen_llvm.py

### ISSUE THREAD

**Issue by harouwu** [dmlc/tvm#3697]
Hi, I got these errors when running `test_codegen_llvm.py` on the trunk hash `a88b2842`. I bisected the test functions and have these:

this one comes from `test_llvm_intrin()`
```
py3 test_codegen_llvm.py
Assertion failed: (Index < Length && "Invalid index!"), function operator[], file /Users/ywu/code/llvm-project/llvm/include/llvm/ADT/ArrayRef.h, line 240.
[1]    2692 abort      /Users/ywu/anaconda3/bin/python test_codegen_llvm.py
```

this one comes from `test_llvm_lookup_intrin()`
```
py3 test_codegen_llvm.py
Assertion failed: ((i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"), function init, file /Users/ywu/code/llvm-project/llvm/lib/IR/Instructions.cpp, line 405.
[1]    2828 abort      /Users/ywu/anaconda3/bin/python test_codegen_llvm.py
```

My clang version is 10.0 and I have set `USE_LLVM` in config.cmake. Could someone take a look? My llvm is built from src. this might caused the problem

btw, it would be great to have test icon on the github page :)

**Comment by tqchen** [comment]
It would be great if you can dig deeper. Also please open a new thread on https://discuss.tvm.ai/ as we use the discuss forum for trouble shooting.

It could due to the fact that the intrinsic def changes. We do have a test ci which is currently green in the frontend readme
