### ISSUE TITLE
tvm_exec.rpc_server start error: /usr/bin/python: /usr/lib/liblapack.so.3: undefined symbol: sgetrs_N_single

### ISSUE THREAD

**Issue by ysh329** [dmlc/tvm#371]
I executed `python -m tvm.exec.rpc_server --host 0.0.0.0 --port=9090` smoothly on FireflyRK3399(ARM A72), but met a problem on A53.

## Env.
- raspberrypi ARM A53;
- Target: arm-linux-gnueabihf
- Linux raspberrypi 4.4.38-v7+

## config.mk

Only changed below:

```mk
DEBUG = 1
USE_RPC = 1
USE_BLAS = openblas
```

## Error Log

After `make runtime` below root directory of TVM and `python setup.py install --user`, I set relative env. variable in `~/.bashrc` as below:

```bash
# tvm
export TVM_HOME=/home/yuanshuai/code/tvm
export PATH=$PATH:$TVM_HOME/lib
export PYTHONPATH=$PYTHONPATH:$TVM_HOME/python
```

I executed `python -m tvm.exec.rpc_server --host 0.0.0.0 --port=9090`. However, it outputs messages below:

```Shell
yuanshuai@raspberrypi:~/code/tvm/python $ python -m tvm.exec.rpc_server --host 0.0.0.0 --port=9090
/usr/bin/python: /usr/lib/liblapack.so.3: undefined symbol: sgetrs_N_single
```

**Comment by tqchen** [comment]
Seems to be problem of importing numpy in the python env. Can you check simply import numpy on the board ?

**Comment by ysh329** [comment]
Indeed! I found there's a problem with `numpy` and failed to re-install numpy with same error. I'm trying to update `numpy` using `pip install -U numpy`.

**Comment by tqchen** [comment]
closing this issue now as it is problem of numpy

**Comment by eric-wieser** [comment]
That error is not the same error as the numpy one - lapack_lite and liblapack are different things, and only the former is owned by numpy
