### ISSUE TITLE
ZeroDivisionError when compile mxnet model target cuda under Windows

### ISSUE THREAD

**Issue by yanlei08** [dmlc/tvm#3714]
When I compile a mxnet model target cuda under windows7, it happed a ZeroDivisionError .
space.py(207):RuntimeWarning :divide by zero encountered in long_scalars
   if self.product % np.prod(tmp_stack) == 0:

![error](https://user-images.githubusercontent.com/26413147/62516153-d9a9e880-b856-11e9-89e6-1eb94b9e8727.png)

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/
