### ISSUE TITLE
[Relay] FuseOps pass won't work after ToANormalForm pass

### ISSUE THREAD

**Issue by icemelon9** [dmlc/tvm#3720]
The following code can reproduce the bug:
```python
from tvm import relay
from tvm.relay import transform

x = relay.var('x', shape=(5, 4), dtype='float32')
y0 = x + relay.const(1.0, 'float32')
y1 = y0 * relay.const(2.0, 'float32')
mod = relay.module.Module()
mod["main"] = relay.Function([x], y1)
seq = transform.Sequential([transform.FuseOps()])
mod1 = seq(mod)
seq = transform.Sequential([transform.ToANormalForm(), transform.FuseOps()])
mod2 = seq(mod)
print(mod1)
print(mod2)
```
From output, we can see that there is no op fusion in `mod2`.
```bash
v0.0.3
def @main(%x: Tensor[(5, 4), float32]) -> Tensor[(5, 4), float32] {
  %1 = fn (%p0: Tensor[(5, 4), float32], Primitive=1) -> Tensor[(5, 4), float32] {
    %0 = add(%p0, 1f /* ty=float32 */) /* ty=Tensor[(5, 4), float32] */;
    multiply(%0, 2f /* ty=float32 */) /* ty=Tensor[(5, 4), float32] */
  };
  %1(%x) /* ty=Tensor[(5, 4), float32] */
}

v0.0.3
def @main(%x: Tensor[(5, 4), float32]) -> Tensor[(5, 4), float32] {
  let %x1: float32 = 1f /* ty=float32 */;
  %0 = fn (%p0: Tensor[(5, 4), float32], %p1: float32, Primitive=1) -> Tensor[(5, 4), float32] {
    add(%p0, %p1) /* ty=Tensor[(5, 4), float32] */
  };
  let %x2: Tensor[(5, 4), float32] = %0(%x, %x1) /* ty=Tensor[(5, 4), float32] */;
  let %x3: float32 = 2f /* ty=float32 */;
  %1 = fn (%p01: Tensor[(5, 4), float32], %p11: float32, Primitive=1) -> Tensor[(5, 4), float32] {
    multiply(%p01, %p11) /* ty=Tensor[(5, 4), float32] */
  };
  let %x4: Tensor[(5, 4), float32] = %1(%x2, %x3) /* ty=Tensor[(5, 4), float32] */;
  %x4
}
```

**Comment by icemelon9** [comment]
cc @jroesch @wweic @MarisaKirisame

**Comment by MarisaKirisame** [comment]
@icemelon9 in fuse_ops.cc line 321, there is the single LetNode occurrence, with the comment "do not fuse through let". It shouldnt be very hard to fix.
Unfortuantely, I am busy for 3 weeks for some internal deadline, and cannot help code on this.

**Comment by masahi** [comment]
Shouldn't we apply A normal transform after fusion? Or are fusion and A normal transform commutative?

**Comment by zhiics** [comment]
I think we usually perform fusion as the last opt. But this problem seems more related to handling of `LetNode`.

**Comment by MarisaKirisame** [comment]
The problem is indeed more fundamental: FuseOps dont handle LetNode (and LetNode is needed for scope/reference).

**Comment by tqchen** [comment]
This is something that we should move to https://discuss.tvm.ai/ Likely a solution could be to transform to graph normal form, apply fusion, and then back to ANF. 

Currently, most of our optimizations expect a minimum use of lets as possible. The original intention of the fusor is that If a let is necessary for scoping reasons, then we should not fuse through the let.
