### ISSUE TITLE
compute_at problem!

### ISSUE THREAD

**Issue by Zzmc** [dmlc/tvm#3722]
i have two produce

- [ ] produce A{

 

-  for (1, 16)

    

- for (1, 32)

      

- for (1, 64)

}

- [ ] produce B{

 

-  for (1, 1)

  

-  for(1,16)

}
when make the B compute_at to A(axis[0]), can it keep the "for (1,16)" unchanged?  like that:

- [ ] produce A{

  

- for (1, 16)

   

- [ ] produce B{

    

-  for (1, 1)

     

-   **for(1, 16)**

   }
    

- for (1,32)

      

- for (1, 64)

}

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/
