### ISSUE TITLE
Incorrect classification result for CoreML

### ISSUE THREAD

**Issue by fink-stanislav** [dmlc/tvm#3725]
## Summary

- Inference results of converted CoreML models are not correct
- The tutorial example shows the incorrect result as expected one

## Description

I am trying to convert CoreML model into something, that can be used for inference on Linux machine. I took a snippet from the tutorial and it did not work correctly. Curiously, even in the tutorial itself, the incorrect result [is shown as expected](https://docs.tvm.ai/tutorials/frontend/from_coreml.html#look-up-synset-name):

> Top-1 id 470 class name candle, taper, wax light

Since the test image has a cat on it, not a candle, I assume the result is wrong. I was able to reproduce the very same result on my machine using CPU and GPU. Unconverted [model](https://docs-assets.developer.apple.com/coreml/models/MobileNet.mlmodel) used in the tutorial produces way more correct prediction while running on macOS (282, tiger cat).

I also tried another [model](https://github.com/ytakzk/CoreML-samples/blob/master/CoreML-samples/Resnet50.mlmodel) taken from [here](https://github.com/likedan/Awesome-CoreML-Models). The result was different but also incorrect (473 can opener, tin opener).

Please see [gist](https://gist.github.com/fink-stanislav/5f3dcd32d44c43dfe978272a8fc65781) for code to reproduce the issue.

**Comment by tqchen** [comment]
@kazum @zhreshold can you look into what is happening?

**Comment by FrozenGene** [comment]
I saw before very long ago. The issue is our pad mechanism.  I could see and solve this issue this weekend. Thanks.

**Comment by FrozenGene** [comment]
@fink-stanislav You could refer PR https://github.com/dmlc/tvm/pull/3800, we could get the correct result now (Top-1 id 282 class name tiger cat). Please be careful this PR also update the tutorial of CoreML corresponding to your script. Because CoreML mobilenet model input image format is BGR, but we open image format is RGB by default. You could check my PR and see the modified place.

**Comment by tqchen** [comment]
Thanks @FrozenGene ! and thanks @fink-stanislav for reporting the issue.
