### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by ritesh2212** [dmlc/tvm#3747]
Hi all,
I'm getting build error in TVM runtime.

[ 98%] Built target tvm_runtime
[ 99%] Building CXX object CMakeFiles/vta.dir/vta/src/device_api.cc.o
[ 99%] Building CXX object CMakeFiles/vta.dir/vta/src/runtime.cc.o
In file included from /home/cs18mtech11033/tvm/vta/src/runtime.cc:29:0:
/home/cs18mtech11033/tvm/vta/include/vta/hw_spec.h:104:33: error: ‘VTA_LOG_UOP_BUFF_SIZE’ was not declared in this scope
 #define VTA_LOG_UOP_BUFF_DEPTH (VTA_LOG_UOP_BUFF_SIZE - VTA_LOG_UOP_WIDTH + 3)
                                 ^
/home/cs18mtech11033/tvm/vta/include/vta/hw_spec.h:303:29: note: in expansion of macro ‘VTA_LOG_UOP_BUFF_DEPTH’
   uint64_t uop_bgn        : VTA_LOG_UOP_BUFF_DEPTH;
                             ^
/home/cs18mtech11033/tvm/vta/include/vta/hw_spec.h:104:33: error: ‘VTA_LOG_UOP_BUFF_SIZE’ was not declared in this scope
 #define VTA_LOG_UOP_BUFF_DEPTH (VTA_LOG_UOP_BUFF_SIZE - VTA_LOG_UOP_WIDTH + 3)
                                 ^
/home/cs18mtech11033/tvm/vta/include/vta/hw_spec.h:305:29: note: in expansion of macro ‘VTA_LOG_UOP_BUFF_DEPTH’
   uint64_t uop_end        : VTA_LOG_UOP_BUFF_DEPTH + 1;
                             ^
/home/cs18mtech11033/tvm/vta/include/vta/hw_spec.h:104:33: error: ‘VTA_LOG_UOP_BUFF_SIZE’ was not declared in this scope
 #define VTA_LOG_UOP_BUFF_DEPTH (VTA_LOG_UOP_BUFF_SIZE - VTA_LOG_UOP_WIDTH + 3)
                                 ^
/home/cs18mtech11033/tvm/vta/include/vta/hw_spec.h:367:29: note: in expansion of macro ‘VTA_LOG_UOP_BUFF_DEPTH’
   uint64_t uop_bgn        : VTA_LOG_UOP_BUFF_DEPTH;
                             ^
/home/cs18mtech11033/tvm/vta/include/vta/hw_spec.h:104:33: error: ‘VTA_LOG_UOP_BUFF_SIZE’ was not declared in this scope
 #define VTA_LOG_UOP_BUFF_DEPTH (VTA_LOG_UOP_BUFF_SIZE - VTA_LOG_UOP_WIDTH + 3)
                                 ^
/home/cs18mtech11033/tvm/vta/include/vta/hw_spec.h:369:29: note: in expansion of macro ‘VTA_LOG_UOP_BUFF_DEPTH’
   uint64_t uop_end        : VTA_LOG_UOP_BUFF_DEPTH + 1;
                             ^
/home/cs18mtech11033/tvm/vta/include/vta/hw_spec.h:62:33: error: ‘VTA_LOG_UOP_BUFF_SIZE’ was not declared in this scope
 #define VTA_UOP_BUFF_SIZE (1 << VTA_LOG_UOP_BUFF_SIZE)
                                 ^
/home/cs18mtech11033/tvm/vta/include/vta/hw_spec.h:102:29: note: in expansion of macro ‘VTA_UOP_BUFF_SIZE’
 #define VTA_UOP_BUFF_DEPTH (VTA_UOP_BUFF_SIZE / VTA_UOP_ELEM_BYTES)
                             ^
/home/cs18mtech11033/tvm/vta/src/runtime.cc:489:37: note: in expansion of macro ‘VTA_UOP_BUFF_DEPTH’
   static constexpr int kMaxNumUop = VTA_UOP_BUFF_DEPTH;
                                     ^
CMakeFiles/vta.dir/build.make:86: recipe for target 'CMakeFiles/vta.dir/vta/src/runtime.cc.o' failed
make[2]: *** [CMakeFiles/vta.dir/vta/src/runtime.cc.o] Error 1
CMakeFiles/Makefile2:247: recipe for target 'CMakeFiles/vta.dir/all' failed
make[1]: *** [CMakeFiles/vta.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Can anyone help me to resolve this error?

**Comment by drord9** [comment]
same thing for me.
I think it has something to do with : #3650

**Comment by drord9** [comment]
@ritesh2212 try `git pull` 
Worked for me.

**Comment by tqchen** [comment]
Please open a new thread in https://discuss.tvm.ai/

**Comment by jayle19930918** [comment]
@ritesh2212  Hello, I have the same roblem, have you solved it?
