### ISSUE TITLE
Is there a way to compute in-place result

### ISSUE THREAD

**Issue by ghostplant** [dmlc/tvm#3753]
Except to compute: C += A * B;
TVM actually computes: D = C + A * B and D is not C;

Although D = C + A * B can also work for C += A * B in some cases, but they cost different number of registers so the tuning results of `D = C + A * B` is not the best for `C += A * B`.

So is there a way to compute in-place result?

**Comment by tqchen** [comment]
For general discussion related questions, the community prefers to use https://discuss.tvm.ai/, see related discussions in https://discuss.tvm.ai/t/rfc-implement-add-to-semantic-in-tvm/3618/7
