### ISSUE TITLE
[TEST] Not assuming HOME in tvm/download.py 

### ISSUE THREAD

**Issue by goodhart** [dmlc/tvm#3759]
Hello TVM team,

In tvm/download.py - https://github.com/dmlc/tvm/blob/master/python/tvm/contrib/download.py#L122 - there is a line that calls: 

`TEST_DATA_ROOT_PATH = os.path.join(os.path.expanduser('~'), '.tvm_test_data')
 `

Unfortunately there is no guarantee that a user has a home directory. For system accounts, such as those used by our automated test infrastructure, this resolves to '/dev/null.tvm_test_data' and results in an exception being thrown. Worse, this file is imported implicitly via an __init__.py chain, so I can't simply avoid this file.

**Comment by tqchen** [comment]
Contribution is more than welcomed. I think it is reasonable to make it configurable through env variable.

**Comment by cchung100m** [comment]
Hi @goodhart , @tqchen ,

I'm interested in working on this if no one else has signed up. I would appreciate if you can suggest which files should I dig for environment variable setting/getting.

Many thanks,

**Comment by cchung100m** [comment]
Hi @tqchen ,

The [current design](https://github.com/dmlc/tvm/blob/master/python/tvm/contrib/download.py#L122) :

```
TEST_DATA_ROOT_PATH = os.path.join(os.path.expanduser('~'), '.tvm_test_data')
os.makedirs(TEST_DATA_ROOT_PATH, exist_ok=True)
```

would check the directory from env variable according to python document: [os.path.expanduser(path)](https://docs.python.org/3/library/os.path.html#os.path.expanduser)
> On Unix, an initial ~ is replaced by the environment variable HOME if it is set; otherwise the current user’s home directory is looked up in the password directory through the built-in module pwd. An initial ~user is looked up directly in the password directory.
> 
> On Windows, HOME and USERPROFILE will be used if set, otherwise a combination of HOMEPATH and HOMEDRIVE will be used.

Therefore, I'd like to know your thought on making the **TEST_DATA_ROOT_PATH** configurable through env variable.

many thanks,

**Comment by tqchen** [comment]
Yes, i think we should make it reconfigurable via TVM_TEST_DATA_PATH and default to the original one if the env variable is not set

**Comment by tqchen** [comment]
#3803 Thanks to @cchung100m
