### ISSUE TITLE
[Simplifier] [Regression] Bounds checks for variable-extent loops not eliminated by simplifier

### ISSUE THREAD

**Issue by ajtulloch** [dmlc/tvm#3770]
Reproduction script:

```.py
import tvm

n = tvm.var('n')
X = tvm.placeholder(shape=(n,), name="x")
W = tvm.placeholder(shape=(n + 1,), dtype="int32", name="w")

def f(i):
    start = W[i]
    extent = W[i+1] - W[i]
    rv = tvm.reduce_axis((0, extent))
    return tvm.sum(X[rv + start], axis=rv)
Y = tvm.compute(X.shape, f, name="y")
s = tvm.create_schedule([Y.op])
with tvm.build_config(add_lower_pass=[(2, lambda stmt: tvm.ir_pass.LoopPartition(stmt, False))]):
    print(tvm.lower(s, [X, W, Y], simple_mode=True))
```

At 60607eff494ab0b40ec21d6faf72c2f3dcef502f, the output is:

```
produce y {
  for (i, 0, n) {
    y[i] = 0f
    for (rv, 0, (w[(i + 1)] - w[i])) {
      if ((rv < (w[(i + 1)] - w[i]))) {
        y[i] = (y[i] + x[(rv + w[i])])
      }
    }
  }
}
```

Where we have an unnecessary bounds check on the inner loop.

at 52179338f3ed7cba17ebe2ac68b5eab6ee3f5179, the output is:

```
produce y {
  for (i, 0, n) {
    y[i] = 0.000000f
    for (rv, 0, (w[(i + 1)] - w[i])) {
      y[i] = (y[i] + x[(w[i] + rv)])
    }
  }
}
```

That is, we avoid any bounds checks in the inner loop. The loop partition pass makes no difference here.

This seems to be a bug in the new simplifier infrastructure? cc @tqchen.

https://github.com/ajtulloch/tvm/tree/fix-cond-in-variable-extent-loo is a fix, but it's quite ugly and there should be a better fix in the simplifier.

**Comment by ajtulloch** [comment]
Still running the `git bisect` (3 iterations to go), but it looks like it blames to https://github.com/dmlc/tvm/pull/3368. @tqchen do you have any ideas on how to cleanly get the simplifier to recognize this pattern?

**Comment by tqchen** [comment]
Great observation! I think the main reason here is that when comparing the bounds, we can try different relaxations.

While in our normal cases it is fine to just relax i, in this particular case, the best way is to not do so and makes the bound of r dependent on i. 

We might want to think about whether or not if we can try both, if we can list the other failure case you mentioned, we can also dig a bit deeper

**Comment by tqchen** [comment]
specifically to that PR, I think one possible change is not to eagerly resolve the bound that is context depend, but marks it to be so, and then try to recursively simplify min and max after we get a bound that we know is context dependent(so we will do simplification that involves i dependent  first, then relax i if necessary)

**Comment by ajtulloch** [comment]
@tqchen I don't fully understand your idea. In general, how robust do you think that approach is? One thing I was thinking of adding would be a trivial step in Simplifier which, when visiting a Range(min, extent) node, adds the constraints `loop_var >= min` and `loop_var < min + extent`, and then detects expressions which exactly match one of these and replace them with const(1). This is a simple thing and should remove these bugs going forward.

**Comment by tqchen** [comment]
To elaborate, in the example below, we have the following range bound to to the loop vars
```
r: 0 to w[i+1] - w[i]
i: 0 to n
```

Our previous approach eagerly expand the bound of each variable, so we use bind to bind the bound of r, it get relaxed to ```Union_{i \in bound of i} {0 to w[i+1] - w[i]}```, before it starts simplification. So``` r -  w[i+1] - w[i]``` can no longer get simplified.

The proposed idea is to make such expansion lazy. i.e. when we evaluate r, we would return the bound ```0 to w[i+1] - w[i]```.  So if we call evalset for r+1, it would be ```1 to w[i+1] - w[i]+1```. However, we find that the new bound is still dependent on some of the relaxed variables, in this case i, and we will continue to relax the min and max value after we get the resulting set.

**Comment by tqchen** [comment]
@ajtulloch after thinking a bit more about the issue. I started to think that your idea of adding bound constraints may be the best way to go, can you send in a PR?

**Comment by tqchen** [comment]
ping @ajtulloch can you follow up on this thread:)

**Comment by ajtulloch** [comment]
@tqchen  sure  - are you saying you want something like https://github.com/ajtulloch/tvm/commit/ca1088c63c51e14a9d3c02df7eaa44fd60c23ce4?

**Comment by tqchen** [comment]
looks great! Although this is a solution that only works for the exact condition, it fits our purpose and is a pragmatic solution

**Comment by ajtulloch** [comment]
@tqchen followed up in https://github.com/dmlc/tvm/pull/4076.
