### ISSUE TITLE
[Relay] Share Relay op Infer Type functions

### ISSUE THREAD

**Issue by anijain2305** [dmlc/tvm#3784]
Currently, all the infer types functions for Relay are present in *.cc file. This prevents us from reusing these functions among dialects like QNN. This issue is to discuss how do we share them.

I added a PR that moves relevant functions to a header file for transform.cc as a possible proposal - https://github.com/dmlc/tvm/pull/3783

Please advise - @jroesch @tqchen @vinx13 @zhiics @ZihengJiang

**Comment by anijain2305** [comment]
Ping :) 

Many QNN related ops are gated by it. I am able to get good accuracy for all the TFLite hostel models locally. Will be good if we can solve these problems and ungate a bunch of QNN PRs.

**Comment by tqchen** [comment]
A proper way would be open a thread with RFC tag, so it would get forwarded to the dev@. I think we could move forward with templatization for now.

**Comment by anijain2305** [comment]
Thank you @tqchen 
I will keep that in mind
