### ISSUE TITLE
[installation] Make fail with CUDA enabled:  build_cuda.cc:12:19: fatal error: nvrtc.h: No such file or directory

### ISSUE THREAD

**Issue by LiyuCode** [dmlc/tvm#379]
### Env
1. OS: Ubuntu 16.04 LTS x64
2. CUDA:  V8.0.61
3. CUDNN: cuDNN_v7.0
4. PYTHON: python 3.5
5. TVM `git rev-parse HEAD`: e318d0ac472cb827892ac6ee7fc9c501134bc794

### Reproduction the error
git clone --recursive https://github.com/dmlc/tvm ~/hub/tvm
cp ~/hub/tvm/make/config.mk ~/hub/tvm
vi ~/hub/tvm/config.mk 

after set `USE_CUDA = 1` , `USE_BLAS = openblas` and `USE_CUDNN = 1` in `config.mk`,  `make` leads to the error:

```bash
g++ -std=c++11 -Wall -O2 -Iinclude -I/home/u/hub/tvm/dlpack/include -I/home/u/hub/tvm/dmlc-core/include -IHalideIR/src -Itopi/include -fPIC -DTVM_CUDA_RUNTIME=1 -DTVM_ROCM_RUNTIME=0 -DTVM_OPENCL_RUNTIME=0 -DTVM_METAL_RUNTIME=0 -DTVM_USE_CUDNN=1 -I/include -MM -MT build/codegen/build_cuda.o src/codegen/build_cuda.cc >build/codegen/build_cuda.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -I/home/u/hub/tvm/dlpack/include -I/home/u/hub/tvm/dmlc-core/include -IHalideIR/src -Itopi/include -fPIC -DTVM_CUDA_RUNTIME=1 -DTVM_ROCM_RUNTIME=0 -DTVM_OPENCL_RUNTIME=0 -DTVM_METAL_RUNTIME=0 -DTVM_USE_CUDNN=1 -I/include -c src/codegen/build_cuda.cc -o build/codegen/build_cuda.o
src/codegen/build_cuda.cc:12:19: fatal error: nvrtc.h: No such file or directory
```
### Desc
However, if explicitly set `CUDA_PATH= /usr/local/cuda` in the `config.mk` also, no such error.

**Comment by LiyuCode** [comment]
Sorry, this is because I was use the `CUDA_HOME` for the directory, not `CUDA_PATH`

**Comment by zhangqiaorjc** [comment]
yes, setting CUDA_PATH= /usr/local/cuda in the config.mk

fixes the error for me as well

src/codegen/build_cuda.cc:12:19: fatal error: nvrtc.h: No such file or directory
compilation terminated.
