### ISSUE TITLE
[codegen_cuda.cc] pull request check

### ISSUE THREAD

**Issue by ZQPei** [dmlc/tvm#3812]
I have fixed an error when compiled with float16 model in cuda.
Related question in TVM Discuss can be found [here](https://discuss.tvm.ai/t/failed-to-convert-mxnet-float16-model-to-tvm/1557/2).
Can someone check my pull request?
[https://github.com/dmlc/tvm/pull/3811](https://github.com/dmlc/tvm/pull/3811)

**Comment by tqchen** [comment]
Please keep most of design discussions in the discuss forum :)
