### ISSUE TITLE
CUDA compilation failed for float16 maxpool 

### ISSUE THREAD

**Issue by zxy844288792** [dmlc/tvm#3816]
I got some errors when I try to compile a float16 maxpool operator with CUDA.

The script I used is shown as below:

    import numpy as np
    import tvm
    from tvm import relay
    from tvm.relay import transform
    from tvm.relay.testing import ctx_list
    import topi.testing

    dtype = 'float16'
    n, c, h, w = 1, 3, 224, 224
    x = relay.var("x", relay.TensorType((n, c, h, w), dtype))
    y = relay.nn.max_pool2d(x)
    mod = relay.Module.from_expr(y)

    print(mod)
    with tvm.relay.build_config(opt_level=3):
        graph, lib, params = relay.build(mod, target='cuda', target_host='llvm -target=x86_64-linux-gnu')

The output and errors:

    v0.0.3
    def @main(%x: Tensor[(1, 3, 224, 224), float16]) -> Tensor[(1, 3, 224, 224), float16] {
      nn.max_pool2d(%x, pool_size=[1, 1]) /* ty=Tensor[(1, 3, 224, 224), float16] */
    }
    
    Traceback (most recent call last):
    
      File "test.py", line 23, in <module>
        graph, lib, params = relay.build(mod, target='cuda', target_host='llvm -target=x86_64-linux-gnu')
    
      File "/home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/relay/build_module.py", line 207, in build
        graph_json, mod, params = bld_mod.build(func, target, target_host, params)

      File "/home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/relay/build_module.py", line 108, in build
        self._build(func, target, target_host)

      File "tvm/_ffi/_cython/./function.pxi", line 310, in tvm._ffi._cy3.core.FunctionBase.__call__

      File "tvm/_ffi/_cython/./function.pxi", line 245, in tvm._ffi._cy3.core.FuncCall

      File "tvm/_ffi/_cython/./function.pxi", line 234, in tvm._ffi._cy3.core.FuncCall3

      File "tvm/_ffi/_cython/./base.pxi", line 171, in tvm._ffi._cy3.core.CALL

    tvm._ffi.base.TVMError: Traceback (most recent call last):
      [bt] (8) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::relay::backend::RelayBuildModule::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<tvm::runtime::ModuleNode> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#3}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const+0x259) [0x7f51ce2e6c19]
      [bt] (7) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::relay::backend::RelayBuildModule::BuildRelay(tvm::relay::Function, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::runtime::NDArray, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, tvm::runtime::NDArray> > > const&)+0xbcf) [0x7f51ce2e657f]
      [bt] (6) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::build(tvm::Map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::LoweredFunc, void>, void, void> const&, tvm::Target const&, tvm::BuildConfig const&)+0x449) [0x7f51cde06dc9]
      [bt] (5) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::build(tvm::Map<tvm::Target, tvm::Array<tvm::LoweredFunc, void>, void, void> const&, tvm::Target const&, tvm::BuildConfig const&)+0x295) [0x7f51cde04655]
      [bt] (4) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::DeviceBuild(tvm::Array<tvm::LoweredFunc, void> const&, tvm::Target const&)+0x61) [0x7f51cddfc461]
      [bt] (3) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::codegen::Build(tvm::Array<tvm::LoweredFunc, void> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1ee) [0x7f51cde0c66e]
      [bt] (2) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::runtime::TypedPackedFunc<tvm::runtime::Module (tvm::Array<tvm::LoweredFunc, void>)>::AssignTypedLambda<tvm::runtime::Module (*)(tvm::Array<tvm::LoweredFunc, void>)>(tvm::runtime::Module (*)(tvm::Array<tvm::LoweredFunc, void>))::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)+0x4f) [0x7f51cde3c40f]
      [bt] (1) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::codegen::BuildCUDA(tvm::Array<tvm::LoweredFunc, void>)+0x3c4) [0x7f51ce40c844]
      [bt] (0) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(+0x1285a6b) [0x7f51ce465a6b]
      File "tvm/_ffi/_cython/./function.pxi", line 56, in tvm._ffi._cy3.core.tvm_callback
      File "/home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/autotvm/measure/measure_methods.py", line 585, in tvm_callback_cuda_compile
    ptx = nvcc.compile_cuda(code, target="ptx", arch=AutotvmGlobalScope.current.cuda_target_arch)
      File "/home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/contrib/nvcc.py", line 98, in compile_cuda
        raise RuntimeError(msg)
    RuntimeError: Compilation error:
    /tmp/tmpcr346zlp/my_kernel.cu(5): error: more than one instance of overloaded function             "max" matches the argument list:
            function "max(int, int)"
            function "max(unsigned int, unsigned int)"
            function "max(int, unsigned int)"
            function "max(unsigned int, int)"
            function "max(long, long)"
            function "max(unsigned long, unsigned long)"
            function "max(long, unsigned long)"
            function "max(unsigned long, long)"
            function "max(long long, long long)"
            function "max(unsigned long long, unsigned long long)"
            function "max(long long, unsigned long long)"
            function "max(unsigned long long, long long)"
            function "max(float, float)"
            argument types are: (half, half)

    1 error detected in the compilation of "/tmp/tmpxft_0000d872_00000000-6_my_kernel.cpp1.ii".

**Comment by anijain2305** [comment]
@vinx13 @kevinthesun @jroesch Have you seen these type of errors?

**Comment by vinx13** [comment]
Likely CUDA doesn't overload max for half

**Comment by cchung100m** [comment]
Hi @zxy844288792 , 

there is a PR for it #3811 , could you help to verify that patch?

**Comment by ZQPei** [comment]
@zxy844288792 @anijain2305 This PR #3811   will help!

**Comment by zxy844288792** [comment]
@cchung100m @ZQPei  Thanks! I will try this patch

**Comment by anijain2305** [comment]
Thanks everyone for such a prompt response :)

**Comment by zxy844288792** [comment]
This [PR #3811](https://github.com/dmlc/tvm/pull/3811)  works for maxpool. However, I got another error message for tvm.relay.op.reduce.sum operator. 
The code is shown as below:

    import numpy as np
    import tvm
    from tvm import relay
    from tvm.relay import transform
    from tvm.relay.testing import ctx_list
    import topi.testing

    dtype = 'float16'
    n, c, h, w = 1, 3, 224, 224
    x = relay.var("x", relay.TensorType((n, c, h, w), dtype))
    z = tvm.relay.op.reduce.sum(x)
    mod = relay.Module.from_expr(z)

    print(mod)
    with tvm.relay.build_config(opt_level=3):
        graph, lib, params = relay.build(mod, target='cuda', target_host='llvm -target=x86_64-linux-gnu')
And the errors are:

    v0.0.3
    def @main(%x: Tensor[(1, 3, 224, 224), float16]) -> float16 {
      sum(%x) /* ty=float16 */
    }

    Traceback (most recent call last):

      File "test_plus.py", line 16, in <module>
        graph, lib, params = relay.build(mod, target='cuda', target_host='llvm -target=x86_64-linux-gnu')

      File "/home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/relay/build_module.py", line 207, in build
        graph_json, mod, params = bld_mod.build(func, target, target_host, params)

      File "/home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/relay/build_module.py", line 108, in build
        self._build(func, target, target_host)

      File "tvm/_ffi/_cython/./function.pxi", line 310, in tvm._ffi._cy3.core.FunctionBase.__call__

      File "tvm/_ffi/_cython/./function.pxi", line 245, in tvm._ffi._cy3.core.FuncCall

      File "tvm/_ffi/_cython/./function.pxi", line 234, in tvm._ffi._cy3.core.FuncCall3

      File "tvm/_ffi/_cython/./base.pxi", line 171, in tvm._ffi._cy3.core.CALL

    tvm._ffi.base.TVMError: Traceback (most recent call last):
      [bt] (8) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::relay::backend::RelayBuildModule::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<tvm::runtime::ModuleNode> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#3}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const+0x259) [0x7f6d579bbc39]
      [bt] (7) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::relay::backend::RelayBuildModule::BuildRelay(tvm::relay::Function, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::runtime::NDArray, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, tvm::runtime::NDArray> > > const&)+0xbcf) [0x7f6d579bb59f]
      [bt] (6) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::build(tvm::Map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::LoweredFunc, void>, void, void> const&, tvm::Target const&, tvm::BuildConfig const&)+0x449) [0x7f6d574dbdc9]
      [bt] (5) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::build(tvm::Map<tvm::Target, tvm::Array<tvm::LoweredFunc, void>, void, void> const&, tvm::Target const&, tvm::BuildConfig const&)+0x295) [0x7f6d574d9655]
      [bt] (4) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::DeviceBuild(tvm::Array<tvm::LoweredFunc, void> const&, tvm::Target const&)+0x61) [0x7f6d574d1461]
      [bt] (3) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::codegen::Build(tvm::Array<tvm::LoweredFunc, void> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1ee) [0x7f6d574e166e]
      [bt] (2) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::runtime::TypedPackedFunc<tvm::runtime::Module (tvm::Array<tvm::LoweredFunc, void>)>::AssignTypedLambda<tvm::runtime::Module (*)(tvm::Array<tvm::LoweredFunc, void>)>(tvm::runtime::Module (*)(tvm::Array<tvm::LoweredFunc, void>))::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)+0x4f) [0x7f6d5751142f]
      [bt] (1) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::codegen::BuildCUDA(tvm::Array<tvm::LoweredFunc, void>)+0x3c4) [0x7f6d57ae1864]
      [bt] (0) /home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(+0x1285a8b) [0x7f6d57b3aa8b]
      File "tvm/_ffi/_cython/./function.pxi", line 56, in tvm._ffi._cy3.core.tvm_callback
      File "/home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/autotvm/measure/measure_methods.py", line 585, in tvm_callback_cuda_compile
        ptx = nvcc.compile_cuda(code, target="ptx", arch=AutotvmGlobalScope.current.cuda_target_arch)
      File "/home/ubuntu/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/contrib/nvcc.py", line 98, in compile_cuda
        raise RuntimeError(msg)
    RuntimeError: Compilation error:
    /tmp/tmpxvn_x6i5/my_kernel.cu(14): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(17): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(17): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(17): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(17): error: no operator "+" matches these operands
                operand types are: volatile half + volatile half

    /tmp/tmpxvn_x6i5/my_kernel.cu(21): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(21): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(21): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(21): error: no operator "+" matches these operands
                operand types are: volatile half + volatile half

    /tmp/tmpxvn_x6i5/my_kernel.cu(25): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(25): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(25): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(25): error: no operator "+" matches these operands
                operand types are: volatile half + volatile half

    /tmp/tmpxvn_x6i5/my_kernel.cu(29): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(29): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(29): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(29): error: no operator "+" matches these operands
                operand types are: volatile half + volatile half

    /tmp/tmpxvn_x6i5/my_kernel.cu(33): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(33): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(33): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(33): error: no operator "+" matches these operands
                operand types are: volatile half + volatile half

    /tmp/tmpxvn_x6i5/my_kernel.cu(37): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(37): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(37): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(37): error: no operator "+" matches these operands
                operand types are: volatile half + volatile half

    /tmp/tmpxvn_x6i5/my_kernel.cu(38): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(38): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(38): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(38): error: no operator "+" matches these operands
                operand types are: volatile half + volatile half

    /tmp/tmpxvn_x6i5/my_kernel.cu(39): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(39): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(39): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(39): error: no operator "+" matches these operands
                operand types are: volatile half + volatile half

    /tmp/tmpxvn_x6i5/my_kernel.cu(40): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(40): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(40): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(40): error: no operator "+" matches these operands
                operand types are: volatile half + volatile half

    /tmp/tmpxvn_x6i5/my_kernel.cu(41): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(41): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(41): warning: attribute "__shared__" does not apply here

    /tmp/tmpxvn_x6i5/my_kernel.cu(41): error: no operator "+" matches these operands
                operand types are: volatile half + volatile half

    /tmp/tmpxvn_x6i5/my_kernel.cu(45): warning: attribute "__shared__" does not apply here

    10 errors detected in the compilation of "/tmp/tmpxft_0000edc2_00000000-6_my_kernel.cpp1.ii".

**Comment by tqchen** [comment]
Thanks for great discussions, let us move the rest of discussions to https://discuss.tvm.ai/
