### ISSUE TITLE
Missing Halide acks

### ISSUE THREAD

**Issue by abadams** [dmlc/tvm#3822]
The following file/class pairs contain too much of the same functionality using the same names to have been independently invented, but there's no credit to Halide:

https://github.com/dmlc/tvm/blob/master/include/tvm/expr_operator.h
https://github.com/halide/Halide/blob/master/src/IROperator.h

https://github.com/dmlc/tvm/blob/master/include/tvm/dtype.h#L34
https://github.com/halide/Halide/blob/master/src/Type.h#L268

https://github.com/dmlc/tvm/blob/master/src/arithmetic/int_set.h#L41
https://github.com/halide/Halide/blob/master/src/Interval.h#L15

Also, many of the TVM scheduling directives are directly taken from Halide, but there's no acknowledgement of that in schedule.h (except for rfactor):
https://github.com/dmlc/tvm/blob/master/include/tvm/schedule.h
https://github.com/halide/Halide/blob/master/src/Func.h

These files are pretty old. A more recent piece of logic taken from Halide has attribution, so hopefully practices have changed:
https://github.com/dmlc/tvm/blob/master/src/arithmetic/rewrite_simplify.cc#L25

You're very welcome to take this sort of code from Halide. We'd much rather you reuse it with acknowledgements than reinvent it without.

**Comment by tqchen** [comment]
Thanks @abadams for bringing this up.

To explain why did we miss some of the attribution in the code. When the code was written from scratch while reflecting the same API semantics of the Halide as well as other tools such as loopy, we did not add attributions in the code. Our intention was that the attribution in the Readme to Loopy and Halide (wrt to the design) would suffice. 

This is of course an oversight and we would like to fix it in whatever way you think is better. Pease also feel free to send in PRs about the way that you think is proper.

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/3824 added the missing acks bought up by @abadams

**Comment by abadams** [comment]
Thanks!
