### ISSUE TITLE
Tvm.reduce_axis() does not support dynamic parameter input in tvm0.4 version

### ISSUE THREAD

**Issue by melo19890618** [dmlc/tvm#3827]
When I use Tvm.reduce_axis() to calculate, for example: tvm.reduce_axis(0,end-start), where end and start are both tensor, and an error will be reported:Cannot match type handle64 vs int 32!
    But when I enter a fixed value in tvm.reduce_axis(), for example: tvm.reduce_axis(0,2), it works fine.
    Since my input must  tensor, I would like to ask how to solve this problem or avoid it.

**Comment by tqchen** [comment]
Thanks for bringing this up, please  open a new thread on https://discuss.tvm.ai/ The community uses the forum for general developer discussions
