### ISSUE TITLE
ReLU in keras converter

### ISSUE THREAD

**Issue by yongwww** [dmlc/tvm#3835]
ReLU in Keras Converter missed the case "f(x) = negative_slope * (x - threshold)" defined in https://keras.io/layers/advanced-activations/#relu

**Comment by ethanjyx** [comment]
@tqchen i'm interested in taking this, just to get more familiar with the code base, can you assign this to me?

**Comment by zhiics** [comment]
Thank you for your interest. The TVM community always encourages and welcomes people to contribute. You can ping reviewers when the PR is sent.
