### ISSUE TITLE
This repository is mislabeled: the last release is 0.5 done in February, but the current version is 0.4-based: v0.4-1442-g19b8b3a4

### ISSUE THREAD

**Issue by yurivict** [dmlc/tvm#3848]
```
#!/bin/sh
  
REPO=$1
REV=$2

DIR=$(echo $1 | sed -e 's|.*/|| ; s|\.git$||')

(
  git clone $REPO &&
  (cd $DIR && git describe --tags $2) &&
  rm -rf $DIR
)
```

**Comment by tqchen** [comment]
I believe we have backported certain changes into the v0.5 so that the v0.5 tag have some additional backported changes. For further general discussions, please open a new thread on https://discuss.tvm.ai/

**Comment by yurivict** [comment]
The automated release detection system shows that 0.5 is the latest release and packages need to be updated to 0.5, while you do active development in 0.4 branch.
