### ISSUE TITLE
[AutoTVM][conv2d_cuda] confusing reorder?

### ISSUE THREAD

**Issue by snowolfhawk** [dmlc/tvm#3860]
`
s[OL].reorder(rco, ryo, rxo, rcm, rym, rxm, rci, ryi, rxi, n, f, y, x)`

In tune_conv2d_cuda.py, reoder OL‘s **[n, f, y, x]** as the inner axis, what it means?

why not reorder  **[n, f, y, x]**  as the outer axis?

I get the lower code for OL, there is no differences if or not reorder with **[n, f, y, x]**.

**Comment by tqchen** [comment]
Please use https://discuss.tvm.ai/ for follow up discussions
