### ISSUE TITLE
Version 0.5 fails to build:  fatal error: 'ir/Expr.h' file not found, etc

### ISSUE THREAD

**Issue by yurivict** [dmlc/tvm#3866]
```
/usr/ports/math/tvm/work/tvm-0.5/include/tvm/ir.h:9:10: fatal error: 'ir/Expr.h' file not found
#include <ir/Expr.h>
         ^~~~~~~~~~~
/usr/ports/math/tvm/work/tvm-0.5/include/tvm/expr.h:9:10: fatal error: 'ir/Expr.h' file not found
#include <ir/Expr.h>
         ^~~~~~~~~~~
#include <tvm/node/node.h>
         ^~~~~~~~~~~~~~~~~
```

FreeBSD 12 amd64

**Comment by yurivict** [comment]
If 0.5 is an older version, and 0.4+ is the newer version - you should just release the latest code under the next version number.

**Comment by tqchen** [comment]
This was likely due to missing submodules. You can clone the tag and do``` git submodule update --init --recursive``` to solve the problem

For followup trouble shooting related topics, please open new thread on https://discuss.tvm.ai/ :)

**Comment by yurivict** [comment]
No, submodules are present.

**Comment by tqchen** [comment]
Please confirm that, as these files are included via:

https://github.com/dmlc/tvm/blob/v0.5/CMakeLists.txt#L213
in the 3rdparty/HalideIR submodule , see https://github.com/dmlc/tvm/tree/v0.5/3rdparty
