### ISSUE TITLE
[TOPI] [CUDA] Not in feed graph consumer = extern(argsort_gpu, 0xd3c1490)

### ISSUE THREAD

**Issue by blacklong617** [dmlc/tvm#3882]
I have called the function argsort_gpu in topi/cuda, and I got the log :
/tvm/src/schedule/bound.cc:129: not in feed graph consumer = extern(argsort_gpu, 0xd3c1490)
The input tensor is Tensor(shape=[1, 80, 15130], op.name=argsort_gpu)
I used by call `argsort(scores,axis=2, is_ascend=False,dtype="int32")`
I got the argsort result but it is very slowly,  the argsort cast about 7000ms.
Can someone give me some solutions or suggestion?

**Comment by cchung100m** [comment]
Hi @blacklong617 

Please open a thread in [tvm forum](discuss.tvm.ai) and provide more details of what you're doing.

**Comment by zhiics** [comment]
Yeah, as @cchung100m suggested, please open a thread in the discussion forum.
