### ISSUE TITLE
Possibly missing lines in relay types doc

### ISSUE THREAD

**Issue by vmiheer** [dmlc/tvm#3890]
Hi I ma looking at: https://github.com/dmlc/tvm/blob/master/docs/langref/relay_type.rst#type-relation
> For example we can define an identity relation to be:

> It is usually convenient to type operators in Relay by defining a relation specific to that operator that encodes all the necessary constraints on the argument types and the return type. For example, we can define the relation for flatten:

> If we have a relation like Broadcast it becomes possible to type operators like add:

I think a line is missing after each colon (:) maybe some code/math snippet that didn't get exported?

**Comment by zhiics** [comment]
Thanks for reporting this. I think it is probably because of the parsing problem. We need a blank line after `..code-block:: language` to correctly parse it. Would you be interested submitting a PR to fix them?

**Comment by vmiheer** [comment]
Oh definitely.

**Comment by vmiheer** [comment]
Added PR #3892. Seems like also docs needed to marked so as to not invoke build pipelines.
