### ISSUE TITLE
[RFC] Adding posit/bfloat16/float9 to VTA data path

### ISSUE THREAD

**Issue by Ravenwater** [dmlc/tvm#3938]
Feature proposal: add posit/bfloat16/float9 as data types to the VTA data path

We would like to add different floating point types to the VTA data path so that VTA can be used to study learning rates and recall accuracy across a variety of number systems.

Posits are a tapered floating point system providing independent control over precision and dynamic range.

Bfloat16 is the Brain Floating Point Format that Google introduced in its TPUs

float9 is the format that Microsoft introduced in its project BrainWave

We are seeking feedback from the community on the design and integration of new number systems into the VTA instruction set and micro-architecture.

**Comment by tqchen** [comment]
The standard format for proposals needs to have RFC prefix. atm this seems to be a development discussion stage and the issue do not have a timeline that we can act on.
 I would recommend opening a development thread on https://discuss.tvm.ai Once we have a full proposal, we can move back to an RFC thread.

**Comment by Ravenwater** [comment]
https://discuss.tvm.ai/t/rfc-vta-bfloat16-fp8-fp9-posit-tensor-core/4014

**Comment by tqchen** [comment]
moved to the discuss thread :)
