### ISSUE TITLE
Why tvm is slower than clang with same code.

### ISSUE THREAD

**Issue by doldre** [dmlc/tvm#394]
This is my TVM code for matrix multiplication.
```python
import tvm
import numpy
import time

# The size of the square matrix
N = 1024
# The default tensor type in tvm
dtype = "float32"
# Random generated tensor for testing
a = tvm.nd.array(numpy.random.rand(N, N).astype(dtype), tvm.cpu(0))
b = tvm.nd.array(numpy.random.rand(N, N).astype(dtype), tvm.cpu(0))
c = tvm.nd.array(numpy.zeros((N, N), dtype = dtype), tvm.cpu(0))
# Algorithm
k = tvm.reduce_axis((0, N), 'k')
A = tvm.placeholder((N, N), name = 'A')
B = tvm.placeholder((N, N), name = 'B')
C = tvm.compute(
           A.shape,
           lambda x, y: tvm.sum(A[x, k] * B[k, y], axis = k),
           name = 'C')

s = tvm.create_schedule(C.op)

xi, xj = C.op.axis
s[C].reorder(xi, k, xj)
# print('Normal\n', tvm.lower(s, [A, B, C], simple_mode=True))
func = tvm.build(s, [A, B, C], name='mmult')
assert func
evaluator = func.time_evaluator(func.entry_name, tvm.cpu(0), number=10)
print('Normal: %f' % evaluator(a, b, c).mean)

s[C].vectorize(xj)
# print('Vectorized\n', tvm.lower(s, [A, B, C], simple_mode=True))
func = tvm.build(s, [A, B, C], name='mmult')
assert func
evaluator = func.time_evaluator(func.entry_name, tvm.cpu(0), number=10)
print('Vectorized: %f' % evaluator(a, b, c).mean)

#Normal: 0.685580
#Vectorized: 0.295779
```

In my work station(E5-2650 2.30GHz) , the result of normal is 0.685580s and vectorized is 0.295779s.
But I tried the same algorithm with clang like this.
```cpp
const int N = 1024;
float A[N*N], B[N*N], C[N*N];

void run() {
    for (int i = 0; i < 1024; i++) {
        for (int j = 0; j < 1024; j++) {
            C[i*1024 + j] = 0.0f;
        }
        for (int k = 0; k < 1024; k++) {
            for (int j = 0; j < 1024; j++) {
                C[i*1024+j] += A[i*1024+k] * B[k*1024+j];
            }
        }
    }
}


int main() {
    for (int i = 0; i < 10; i++) {
        run();
    }
}
```

```
% clang --version
clang version 3.8.1-16 (tags/RELEASE_381/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

clang -Ofast gemm.cpp -o gemm
time ./gemm

% time ./gemm

real	1.59s
user	1.55s
sys	0.00s
max_res	5kb
```
The clang version is 0.152s which is much faster than TVM. 
I am curious why TVM is slower with the same llvm backend. Is TVM not turn on the llvm optimization or other reason?

**Comment by tqchen** [comment]
Tvm uses the same llvm backend as clang uses, and actually turns on aggressive memory optimization . maybe there is difference in terms of set of optimization.

I do not know what exactly happens in your case, could due to better cache locality because everything is allocated in global memory consecutively or maybe clang turns on other set of optimizations to optimize the plain code better.

Try follow the tutorial and optimize further, that should brings tvm speed to become faster.

Also if your machine support avx2, set target to be llvm -mcpu=avx2 will help

**Comment by tqchen** [comment]
The option would be -mcpu=core-avx2

**Comment by doldre** [comment]
I tried the "-mcpu=core-avx2",  but it produced the same result.
I use func.save('mmul.o') to export the binary file, then take objdump to disassemble it. I find out the tvm version has 256 **mulps** instruction while clang version has only 8 **mulps**. It looks like tvm unrolled the innermost loop and increased the binary code size. This may cause increasing instructions cache missing rate. This may be the reason why tvm is slower. 
Another question: In tvm, I must set the vectorize manually while clang can auto detect it and generate the vectorized code using instructions like **mulps** . Can tvm support auto vectorization like clang?

**Comment by tqchen** [comment]
We can enable auto vectorization pass in LLVM. Though again this won't give us the most effective code. In a nutshell, clang's auto vectorization might work to get us to the medium perf, but using TVM primitives gives possibility to get to the peak

Try to follow the [tutorial](http://docs.tvmlang.org/tutorials/opt_gemm.html#sphx-glr-tutorials-opt-gemm-py) and

**Comment by doldre** [comment]
I have tried that tutorial . I just wanted to know what level the naive code can achieve with clang and find this problem in the progress.

Thanks very much for your patience.
