### ISSUE TITLE
Cannot compile and run yolov3-tiny ONNX model.

### ISSUE THREAD

**Issue by Bienqq** [dmlc/tvm#3990]
Hello, 

I have train yolov3-tiny model using following PyTorch implementation:
https://github.com/ultralytics/yolov3

Then I exported this trained yolov3-tiny model to ONNX format in order to compile and run it with TVM and LLVM but I don't know how to get output.

Input shape is 1 RGB image with size 608 x 352 so input tensor shape will be `(1, 3, 608, 352)`

My code:
```python

import numpy as np
import onnx
import tvm
import tvm.relay as relay
from PIL import Image

# parameters
model_path = 'yolov3-tiny.onnx'
img_path = '2.jpg'
img_size = (608, 352)
target = 'llvm'
input_name = '0'
dtype = 'float32'

def preprocess(img):
    image_data = np.array(img, dtype='float32')
    image_data /= 255.
    image_data = np.transpose(image_data, [2, 0, 1])
    image_data = np.expand_dims(image_data, 0)
    return image_data

# loading image
image = Image.open(img_path).resize(img_size)
# input
image_data = preprocess(image)

# loading ONNX yolov3-tiny model
onnx_model = onnx.load(model_path)

x = np.asarray(image_data)
# compile the model with relay
shape_dict = {input_name: x.shape}
mod, params = relay.frontend.from_onnx(onnx_model, shape_dict)

with relay.build_config(opt_level=1):
    intrp = relay.build_module.create_executor('graph', mod, tvm.cpu(0), target)

# how to get class label, probability, bounding box coordinates and plot result ???
tvm_output = intrp.evaluate()(tvm.nd.array(x.astype(dtype)), **params)
```

How can I get class label, probability, bounding box coordinates and plot result image from `tvm_output` ?

I expect to receive something like that:

![image](https://user-images.githubusercontent.com/35897213/65376399-a3f27f00-dc9f-11e9-937f-e5e8726c0da4.png)

Thanks in advance

**Comment by tqchen** [comment]
Thanks for reporting the problem, can you please open a new troubleshooting thread on https://discuss.tvm.ai/ , it would also be great if you can produce more information(error messages etc)
