### ISSUE TITLE
Error while Auto tuning for GPU using opencl "CL_OUT_OF_RESOURCES"

### ISSUE THREAD

**Issue by eslambakr** [dmlc/tvm#3992]
I face the following error 
`tvm/src/runtime/module_util.cc:73: Check failed: ret == 0 (-1 vs. 0) : TVMError: Check failed: e == CL_SUCCESS: OpenCL Error, code=-5: CL_OUT_OF_RESOURCES`
while auto-tuning for firefly rk3399 GPU following the tutorial for auto-tuning for mobile GPUs [https://docs.tvm.ai/tutorials/autotvm/tune_relay_mobile_gpu.html](url)

I changed the target from "opencl -device=mali" to "opencl".
`#target = tvm.target.create('opencl -device=mali')`
`target = tvm.target.create('opencl')`
It seems the same problem descibed at #761 
I faced this error while evaluating inference time cost, after the tuning process was finished.

BTW It works fine for target "opencl -device=mali"
`target = tvm.target.create('opencl -device=mali')`
after disabling the tophub as mentioned at #3980

**Comment by tqchen** [comment]
Let us consolidate to #3980 Since you are using rk3399, the mali target is the right one. For followup questions, please open a new thread on https://discuss.tvm.ai/
