### ISSUE TITLE
onnx auto-tune problem

### ISSUE THREAD

**Issue by flynnamy** [dmlc/tvm#3995]
I have a problem when I do auto-tune by using onnx model.Any ideas to solve this?
![image](https://user-images.githubusercontent.com/20398890/65495327-2d48c200-dee9-11e9-8213-74ace51ef7e5.png)

**Comment by tqchen** [comment]
Thanks for bringing up this problem, please open a new thread on https://discuss.tvm.ai, ideally provide a bit more information for reproducing the error.
