### ISSUE TITLE
[QNN] Support for tflite quantized model with per-channel scales in weights.

### ISSUE THREAD

**Issue by mingwayzhang** [dmlc/tvm#3999]
Hi TVM developers,

I noticed that recent TFLite quantized models generated by post-training quantization have multiple scales per weight tensor. I am not entirely sure whether qnn operators support per-channel based requantization or not. If not, do you guys have any plan on the roadmap?

Thanks.
-Mingwei

**Comment by tqchen** [comment]
Thanks for bringing up the discuss thread, please open a new thread on https://discuss.tvm.ai/ as that is our main medium for technical discussions within the community.
