### ISSUE TITLE
How to inspect lower code after compiling a TensorFlow model?

### ISSUE THREAD

**Issue by Maximilianxu** [dmlc/tvm#4011]
I built a small TensorFlow model: LeNet by 
```python
mod, params = relay.frontend.from_tensorflow(graph_def, layout='NCHW', shape=[1, 28, 28, 1])
with relay.build_config(opt_level=3):
    graph, lib, params = relay.build(mod, target='llvm', target_host='llvm', params=params)
```
This is a tiny piece for testing and I want to inspect the lower code after the optimization. For instance, the code after unrolling, vectorization for a convolutional layer. Can I obtain the lower code or the IR during the compiling of a TensorFlow model?

**Comment by tqchen** [comment]
Thanks for bringing up the problem. The community uses https://discuss.tvm.ai for general topics like this one. Please open a new thread there
