### ISSUE TITLE
[DOCKER] make demo images consistent with ci images when possible

### ISSUE THREAD

**Issue by ibeltagy** [dmlc/tvm#4020]
I want to mention that all the prebuilt docker images here https://hub.docker.com/u/tvmai can't be used to run the tutorials. Either they are very old and missing pytorch (demo-gpu and demo-cpu) or they don’t have tvm installed (ci-gpu and ci-cpu). 
As a person who just want to see if tvm is the right tool for my use case, I would really appreciate a prebuilt docker image that can easily run the tutorials.

Thanks

**Comment by tqchen** [comment]
Thanks for the suggestion. The ci images does not contain a version of TVM because they are used to build the image. We shall update the demo images to include the necessary tools you mentioned.

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/4024

**Comment by tqchen** [comment]
tvmai/demo-gpu has been updated with the additional deps
