### ISSUE TITLE
[Question] How to only compute diagonal band of matrix multiplication output?

### ISSUE THREAD

**Issue by ibeltagy** [dmlc/tvm#4021]
I want to do matrix multiplication of 2D tensors where I only care about a few diagonals of the resulting matrix. Is this something that can be done with Tensor Expression? How would you express the code below in the lambda function of `tvm.compute` ?
I need this for PyTorch/GPU, but here's the numpy code just for illustration.

```import numpy as np
M = 16000  # huge, can't do the O(n^2) operations
N = 64
c = 100  # size of diagonal band. A lot smaller than M
t1 = np.random.rand(M, N)  
t2 = np.random.rand(M, N) 
r = np.zeros((M, d))

for i in range(M):
    for j in range(-c, c):  
        r[i][j] = np.dot(t1[i], t2[i + j])  # `(i + j)` should be `min(max(i + j, 0), M - 1)`
                                            # to take care of boundry condition, but let's skip that for now```

Thanks

**Comment by tqchen** [comment]
It looks like you want a special band matrix support. Likely you will also need pytorch support of sparse matrix to do so, or specially store your matrix in the format of ```r[2* c, d]```. if you just want the gpu to run the dense version of compute, you can use tvm.expr.Select to do that. 

For following up thread, please open new threads on https://discuss.tvm.ai/ as that is where community discuss most of the related questions

**Comment by shenshanf** [comment]
It seems like to build cost volume in stereo matching algorithm.
