### ISSUE TITLE
Windows support is not good, doomed to do little.

### ISSUE THREAD

**Issue by zcc199710** [dmlc/tvm#4030]
对windows支持不好，注定做不大 

\codes\tvm-master\include\tvm\base.h(27): fatal error C1083: 无法打开包括文件: “dmlc/logging.h”: No such file or directory (编译源文件 F:\Codes\tvm-master\src\api\api_arith.cc)
2>  api_pass.cc
2>f:\codes\tvm-master\include\tvm\base.h(27): fatal error C1083: 无法打开包括文件: “dmlc/logging.h”: No such file or directory (编译源文件 F:\Codes\tvm-master\src\api\api_codegen.cc)
2>  api_schedule.cc
2>f:\codes\tvm-master\include\tvm\base.h(27): fatal error C1083: 无法打开包括文件: “dmlc/logging.h”: No such file or directory (编译源文件 F:\Codes\tvm-master\src\api\api_ir.cc)
2>  api_test.cc
2>f:\codes\tvm-master\include\tvm\base.h(27): fatal error C1083: 无法打开包括文件: “dmlc/logging.h”: No such file or directory (编译源文件 F:\Codes\tvm-master\src\api\api_lang.cc)
2>  dsl_api.cc
2>f:\codes\tvm-master\include\tvm\base.h(27): fatal error C1083: 无法打开包括文件: “dmlc/logging.h”: No such file or directory (编译源文件 F:\Codes\tvm-master\src\api\api_pass.cc)
2>  analyzer.cc
2>F:\Codes\tvm-master\src\api\dsl_api.cc(25): fatal error C1083: 无法打开包括文件: “dmlc/base.h”: No such file or directory
2>  bound_deducer.cc
2>f:\codes\tvm-master\include\tvm\base.h(27): fatal error C1083: 无法打开包括文件: “dmlc/logging.h”: No such file or directory (编译源文件 F:\Codes\tvm-master\src\api\api_test.cc)
2>  canonical_simplify.cc
2>f:\codes\tvm-master\include\tvm\base.h(27): fatal error C1083: 无法打开包括文件: “dmlc/logging.h”: No such file or directory (编译源文件 F:\Codes\tvm-master\src\api\api_schedule.cc)
3>  builtin_fp16.cc
2>  const_int_bound.cc
2>f:\codes\tvm-master\include\tvm\base.h(27): fatal error C1083: 无法打开包括文件: “dmlc/logging.h”: No such file or directory (编译源文件 F:\Codes\tvm-master\src\arithmetic\bound_deducer.cc)
3>F:\Codes\tvm-master\include\tvm/runtime/c_runtime_api.h(68): fatal error C1083: 无法打开包括文件: “dlpack/dlpack.h”: No such file or directory (编译源文件 F:\Codes\tvm-master\src\runtime\builtin_fp16.cc)
3>  c_dsl_api.cc

**Comment by tqchen** [comment]
Thanks for reporting the problem, please open a new thread on https://discuss.tvm.ai/ as that is where most of our community members used for trouble shooting. In your particular case, it seems that you have forgotten to clone with ```--recursive``` option to get all the git submodules
