### ISSUE TITLE
Build breaks: fatal error: 'tvm/node/node.h' file not found

### ISSUE THREAD

**Issue by yurivict** [dmlc/tvm#4063]
```
In file included from /usr/ports/math/tvm/work/tvm-0.5/src/schedule/schedule_lang.cc:5:
In file included from /usr/ports/math/tvm/work/tvm-0.5/include/tvm/schedule.h:10:
/usr/ports/math/tvm/work/tvm-0.5/include/tvm/base.h:11:10: fatal error: 'tvm/node/node.h' file not found
#include <tvm/node/node.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
```

There is no such file in the source tree: ```tvm/node/node.h```.

The other error is:
```
In file included from /usr/ports/math/tvm/work/tvm-0.5/src/schedule/message_passing.cc:6:
In file included from /usr/ports/math/tvm/work/tvm-0.5/include/tvm/arithmetic.h:12:
/usr/ports/math/tvm/work/tvm-0.5/include/tvm/expr.h:9:10: fatal error: 'ir/Expr.h' file not found
#include <ir/Expr.h>
         ^~~~~~~~~~~
1 error generated.
```

**Comment by tqchen** [comment]
Thanks for bringing up the problem. it should be an issue with git submodule, the dependency is in a submodule. you can resolve by recursively cloning the repo. For follow up questions, please open a new on discuss.tvm.ai

**Comment by wweic** [comment]
@yurivict you can follow the build instruction here: https://docs.tvm.ai/install/from_source.html

**Comment by yurivict** [comment]
Both  https://github.com/dmlc/dmlc-core and https://github.com/dmlc/dlpack don't have any submodules.

Where is ```tvm/node/node.h``` supposed to come from?

**Comment by tqchen** [comment]
For 0.5 the tvm/node/node comes from 3rdparty/HalideIR submodule
