### ISSUE TITLE
plevel 

### ISSUE THREAD

**Issue by mn-dl** [dmlc/tvm#4068]
while installing python setup of incubator-mxnet we are getting following error:
terminate called after throwing an instance of 'dmlc::Error'
what(): [11:22:26] 3rdparty/tvm/nnvm/include/nnvm/op.h:461: Check failed: p.second != plevel Attribute FCompute<gpu> of operator signsgd_update is already registered with same plevel=10

We are able to generate libmxnet.so .
and trying to install mxnet(sudo python setup.py install) 

As per the /tvm/nnvm/include/nnvm/op.h code in this file we can register operator with one plevel value only once. 

Can anyone help me on  this...

**Comment by tqchen** [comment]
Given that this is an issue of mxnet, please open a new thread there. For questions related to tvm, please open a new thread on https://discuss.tvm.ai/
