### ISSUE TITLE
[CodeGen] LLVM codegen doesn't respect mfloat-abi=hard

### ISSUE THREAD

**Issue by mbarrett97** [dmlc/tvm#4072]
For versions of LLVM < 6.0, the mfloat-abi=hard flag does not appear to be respected resulting in operators such as exp and softmax giving incorrect results on Raspberry Pi 3. This issue is discussed [here](https://discuss.tvm.ai/t/softmax-layer-not-working-on-raspberry-pi-4/4191). I've tested with LLVM versions 4.0, 5.0 and 6.0 and only 6.0 gives the correct result.

I've got a small patch (PR: [4071](https://github.com/dmlc/tvm/pull/4071)) to throw a fatal error in the case of trying to use mfloat-abi=hard with a version of LLVM < 6.0 so that this problem isn't silent.

**Comment by tqchen** [comment]
Closed by #4071  Thanks @mbarrett97 !
