### ISSUE TITLE
build failed: /usr/bin/ld: cannot find -ledit

### ISSUE THREAD

**Issue by zhiqiu** [dmlc/tvm#4111]
Hi, I followed [Install from Source](https://docs.tvm.ai/install/from_source.html#) to compile tvm on ubuntu-16.04, but got failure from linker.

`/usr/bin/ld: cannot find -ledit`

I have install the requirements like this,
`sudo apt-get update &&
sudo apt-get install -y python3 python3-dev python3-setuptools gcc libtinfo-dev zlib1g-dev build-essential cmake`

Would you please tell how to install `edit` library? Thanks.

**Comment by zhiqiu** [comment]
OK, I find the solution. 
`apt-get install libedit-dev`
`apt-get install libxml2-dev`
I suggest add these two libs to the documentation[Install from Source](https://docs.tvm.ai/install/from_source.html#).

**Comment by tqchen** [comment]
Thanks for the suggestion, please send a PR to fix the docs https://github.com/dmlc/tvm/tree/master/docs this is a dependency of LLVM

For subsequent trouble shooting related question, please open a new thread on https://discuss.tvm.ai/

**Comment by nft30001** [comment]
sudo apt-get install libgmp3-dev
