### ISSUE TITLE
NNVM Error

### ISSUE THREAD

**Issue by AnneChen** [dmlc/tvm#4137]
I installed tvm from source,but when i use import  nnvm.compiler 
>>> import nnvm.compiler
terminate called after throwing an instance of 'dmlc::Error'
  what():  [03:06:13] /media/leopard/Share/Anne/server/tvm/nnvm/include/nnvm/op.h:473: Check failed: pmap->type() == typeid(OpMap<ValueType>): Attribute FInferShape of operator max_pool2d is registered as inconsistent types previously N4nnvm5OpMapISt8functionIFbRKNS_9NodeAttrsEPSt6vectorIN5mxnet6TShapeESaIS7_EESA_EEEE current N4nnvm5OpMapISt8functionIFbRKNS_9NodeAttrsEPSt6vectorINS_6TShapeESaIS6_EES9_EEEE
Stack trace:
  [bt] (0) /media/leopard/Share/Anne/server/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x32) [0x7f86406a90a2]
  [bt] (1) /media/leopard/Share/Anne/server/tvm/nnvm/python/nnvm/../../../build/libnnvm_compiler.so(nnvm::Op& nnvm::Op::set_attr<std::function<bool (nnvm::NodeAttrs const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> >*, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> >*)> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<bool (nnvm::NodeAttrs const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> >*, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> >*)> const&, int)::{lambda(dmlc::any*)#1}::operator()(dmlc::any*) const+0x173) [0x7f863f63cd03]
  [bt] (2) /media/leopard/Share/Anne/server/tvm/nnvm/python/nnvm/../../../build/libnnvm_compiler.so(nnvm::Op::UpdateAttrMap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (dmlc::any*)>)+0xcc) [0x7f863f56ee8c]
  [bt] (3) /media/leopard/Share/Anne/server/tvm/nnvm/python/nnvm/../../../build/libnnvm_compiler.so(nnvm::Op& nnvm::Op::set_attr<std::function<bool (nnvm::NodeAttrs const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> >*, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> >*)> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<bool (nnvm::NodeAttrs const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> >*, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> >*)> const&, int)+0x1cc) [0x7f863f62c64c]
  [bt] (4) /media/leopard/Share/Anne/server/tvm/nnvm/python/nnvm/../../../build/libnnvm_compiler.so(+0xa1c07) [0x7f863f512c07]
  [bt] (5) /lib64/ld-linux-x86-64.so.2(+0x106ca) [0x7f87254646ca]
  [bt] (6) /lib64/ld-linux-x86-64.so.2(+0x107db) [0x7f87254647db]
  [bt] (7) /lib64/ld-linux-x86-64.so.2(+0x158f2) [0x7f87254698f2]
  [bt] (8) /lib64/ld-linux-x86-64.so.2(+0x10574) [0x7f8725464574]

how can i resolve this problem?Thank you!

**Comment by zhiics** [comment]
@AnneChen Thanks for reporting this. Can you please open a thread on the discussion forum: https://discuss.tvm.ai/

I am going to close it here.
