### ISSUE TITLE
[Relay] Resolve cyclic dependency in Closure

### ISSUE THREAD

**Issue by MarisaKirisame** [dmlc/tvm#4139]
Right now relay leak memory for all of the executor (aot, interpreter, vm), for even the simplest program (id = fun x => x). They all happened to be caused by the exact same problem.
In Relay Implementation, a closure capture over all the free variables, holding a reference to all of them. However, it also hold a reference of itself (as long as it has a name, while ANF give everything a name). This make all closure cyclic data structure.
I propose to solve it by making the two following modification:
add a new Value, RecFunc. RecFunc hold a shared_ptr of a vector of closure, and a size_t index into it.
Every Closure will now have another field, a Map<Var, size_t> which store all recursive call (if any, including mutually recursive one) from the parent RecFunc.
This is in inspiration from https://cs.indiana.edu/ftp/techreports/TR73.pdf - 
![L2 )_)GS48MTGU8~RILJ{D8](https://user-images.githubusercontent.com/3397377/66977930-ba041d00-f05c-11e9-8780-84476089c623.png)
I will submit a PR soon, issuing here for visibility so ppl can avoid the same problem again.

**Comment by tqchen** [comment]
I am not sure I get it, as for recursive call we are capturing Variable, as opposed to the its binding I think this problem worth a bit of more thoughts. Essentially it was the same problem in the global modules, in which case we resolve by global var. Do you think if it is possible to do the same thing, eg lamda lift then only capture global vars. You will need the module map to be able to run closure

**Comment by tqchen** [comment]
@MarisaKirisame given that it is an interesting design question, can you open an RFC discuss thread ?

**Comment by MarisaKirisame** [comment]
let's take this standard program, the factorial, for example.
let fact = \x -> if x == 0 then 1 else x * fact (x - 1)
The closure object of x contain the value of all free variable of fact - in that case, also a shared_ptr reference to the fact closure too!
I will open an RFC later.

**Comment by tqchen** [comment]
consolidate to #4143
