### ISSUE TITLE
Batch normalisation requiring gamma (InceptionV3 Keras) 

### ISSUE THREAD

**Issue by Gentatsu** [dmlc/tvm#4149]
I'm trying to load InceptionV3 via Keras and using relay to convert the model, I receive a `TypeError: batch_norm() missing 1 required positional argument: 'gamma'` error.

After looking through the keras layer a bit, it seems that scale is not set in the layer, and is being handled in the layer. 

Could gamma be an optional param in underlying cpp function?

**Comment by tqchen** [comment]
please open a new thread on https://discuss.tvm.ai/
