### ISSUE TITLE
[TEST][FLAKY] test_topi_pooling. test_adaptive_pool

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#4167]
http://ci.tvm.ai:8080/blue/rest/organizations/jenkins/pipelines/tvm/branches/PR-4166/runs/1/nodes/238/log/?start=0

**Comment by tqchen** [comment]
@kevinthesun can you look into that?

**Comment by kevinthesun** [comment]
@tqchen I can reproduce this issue locally and will try to fix.

**Comment by kevinthesun** [comment]
Close it for now. Fell free to reopen if this issue pops up again.
