### ISSUE TITLE
[installation] error: too many decimal points in number

### ISSUE THREAD

**Issue by xqdan** [dmlc/tvm#418]
on ubuntu 14.0.4,  GNU 4.8.4, LLVM 4.0,

**1, mkdir build
2, cd build && cmake . ../
3, make -j, then I got:**

<command-line>:0:18: error: too many decimal points in number
/home/danxiaoqiang/tvm/src/codegen/llvm/codegen_cpu.cc:318:5: note: in expansion of macro ‘TVM_LLVM_VERSION’
 #if TVM_LLVM_VERSION >= 50
     ^
<command-line>:0:18: error: too many decimal points in number
/home/danxiaoqiang/tvm/src/codegen/llvm/codegen_llvm.cc:121:5: note: in expansion of macro ‘TVM_LLVM_VERSION’
 #if TVM_LLVM_VERSION >= 50
     ^
<command-line>:0:18: error: too many decimal points in number
/home/danxiaoqiang/tvm/src/codegen/llvm/codegen_llvm.cc:178:5: note: in expansion of macro ‘TVM_LLVM_VERSION’
 #if TVM_LLVM_VERSION >= 50
     ^
<command-line>:0:18: error: too many decimal points in number
/home/danxiaoqiang/tvm/src/codegen/llvm/codegen_llvm.cc:187:5: note: in expansion of macro ‘TVM_LLVM_VERSION’
 #if TVM_LLVM_VERSION >= 50
     ^
<command-line>:0:18: error: too many decimal points in number
/home/danxiaoqiang/tvm/src/codegen/llvm/llvm_common.cc:103:7: note: in expansion of macro ‘TVM_LLVM_VERSION’
   #if TVM_LLVM_VERSION < 50
       ^

**When I grep TVM_LLVM_VERSION**:

~/tvm/build$ grep -rn TVM_LLVM_VERSION *
CMakeFiles/tvm_runtime.dir/DependInfo.cmake:26:  "TVM_LLVM_VERSION=**4.0.0**"
CMakeFiles/tvm_runtime.dir/flags.make:7:CXX_DEFINES = -DTVM_CUDA_RUNTIME=1 -DTVM_LLVM_VERSION=4.0.0 -DTVM_OPENCL_RUNTIME=0 -Dtvm_runtime_EXPORTS
CMakeFiles/tvm.dir/DependInfo.cmake:133:  "TVM_LLVM_VERSION=**4.0.0**"
CMakeFiles/tvm.dir/flags.make:7:CXX_DEFINES = -DTVM_CUDA_RUNTIME=1 -DTVM_LLVM_VERSION=4.0.0 -DTVM_OPENCL_RUNTIME=0 -Dtvm_EXPORTS

**When I modify 4.0.0 to 4.0, it works.

I'm not sure the way I was building is inappropriate, or it's a bug.

Thanks!**

**Comment by tqchen** [comment]
Thanks for reporting this, should be fixed by https://github.com/dmlc/tvm/pull/421, for now you can try to use the makefile directly
