### ISSUE TITLE
compiling warnings 

### ISSUE THREAD

**Issue by xqdan** [dmlc/tvm#419]
/tvm/src/pass/inject_double_buffer.cc: In member function ‘virtual Halide::Internal::Stmt tvm::ir::DoubleBufferInjector::Mutate_(const Halide::Internal::For*, const Halide::Internal::Stmt&)’:
/home/danxiaoqiang/tvm/src/pass/inject_double_buffer.cc:126:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (size_t i = 0; i < split_loop_; ++i) {
                                ^
/tvm/src/pass/inject_double_buffer.cc:136:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (size_t i = 0; i < split_loop_; ++i) {
                                ^
[ 99%] Linking CXX shared library libtvm_runtime.so
[ 99%] Built target tvm_runtime
/tvm/src/codegen/llvm/codegen_llvm.cc: In member function ‘virtual void tvm::codegen::CodeGenLLVM::VisitStmt_(const Halide::Internal::AssertStmt*)’:
/home/danxiaoqiang/tvm/src/codegen/llvm/codegen_llvm.cc:1162:44: warning: ‘offset’ may be used uninitialized in this function [-Wmaybe-uninitialized]
           e.base = static_cast<int>(offset);
                                            ^

**Comment by tqchen** [comment]
The first warning has been fixed by https://github.com/dmlc/tvm/pull/415 already, the second one is a false positive. Which does not occur in latest compilers, never-the less, i will submit a PR to suppress that
