### ISSUE TITLE
LLVM error when running  scripts

### ISSUE THREAD

**Issue by xqdan** [dmlc/tvm#420]
:~/tvm$ sh ./tests/scripts/task_python_topi.sh
: CommandLine Error: Option 'debug-pass' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine option

Probably it's some mistake when building or LLVM related environment issues, could you guys give some clues? thanks.

ubuntu 14.0.4 & GNU 4.8.4 & LLVM 4.0

**Comment by tqchen** [comment]
Try to use llvm's official binary repo. This does not seems to be a tvm issue. For quick fresh llvm installation. 

You can try https://apt.llvm.org/ or http://releases.llvm.org/download.html to get prebuild binary

**Comment by xqdan** [comment]
thanks, will try.
