### ISSUE TITLE
Rename from input to output index.

### ISSUE THREAD

**Issue by koolkoffee** [dmlc/tvm#4200]
https://github.com/dmlc/tvm/blob/493c98d3020fefa9f6dd3c291a9eca674838d520/python/tvm/contrib/graph_runtime.py#L203

**Comment by tqchen** [comment]
Good catch, please feel free to open a new PR

**Comment by tqchen** [comment]
ping @koolkoffee would love to send a PR to fix the problem :)

**Comment by koolkoffee** [comment]
okay will do.
