### ISSUE TITLE
Segfault while building YOLO on Jetson TX2

### ISSUE THREAD

**Issue by Flova** [dmlc/tvm#4201]
Hey,
I tried to compile a tiny yolov3 for execution on an NVidia Jetson TX2 using CUDA. 
The TVM instance is compiled for CUDA and LLVM.
The conversion of the yolo model runs without problems, but when I try to build the model on the Jetson I get the following error:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
The compilation is done using the following code. The rest of the code bases on the yolo TVM tutorial.
```python
target = tvm.target.cuda()
data = np.empty([batch_size, net.c, net.h, net.w], dtype)
shape = {'data': data.shape}
print("Compiling the model...")
with nnvm.compiler.build_config(opt_level=2):
    graph, lib, params = nnvm.compiler.build(mod, target=target, target_host='llvm -target=aarch64-linux-gnu')
```

**Comment by tqchen** [comment]
Thanks for reporting the problem, the community uses the discuss forum for troubleshooting please open a new troubleshooting thread on https://discuss.tvm.ai
