### ISSUE TITLE
errors while Compiling the TVM from source

### ISSUE THREAD

**Issue by OriAlpha** [dmlc/tvm#4202]
I am trying to build the TVM from source but it overs below issues and not able to build the TVM on my machine. 

Steps done are 
i have cloned the package of TVM, did the build and modified the cmake file, 
When i give make -j4 following errors 

error: ‘floor’ is not a member of ‘std’
return FloatImm::make(rtype, std::floor(fa->value / fb->value));

**Comment by KimBioInfoStudio** [comment]
pls make sure u r follow https://docs.tvm.ai/install/from_source.html

**Comment by OriAlpha** [comment]
I have followed the same instructions 

> pls make sure u r follow https://docs.tvm.ai/install/from_source.html

I have followed the same instructions
