### ISSUE TITLE
tvm/relay/grammar/py3 module is missing after the installation

### ISSUE THREAD

**Issue by apivovarov** [dmlc/tvm#4215]
I built TVM with LLVM and ANTLR and installed tvm using 
```
cd python
sudo python3 setup.py install
```
Ubuntu 19.10 , Python 3.7

tvm is installed to `/usr/local/lib/python3.7/dist-packages/tvm-0.6.dev0-py3.7-linux-x86_64.egg/tvm`

But I do not see `tvm/relay/grammar/py3` folder after the installation. I only see `__init__.py` under `tvm/relay/grammar`

The following py files are not installed
https://github.com/dmlc/tvm/tree/master/python/tvm/relay/grammar/py3

**Comment by KimBioInfoStudio** [comment]
also find  that because  this pr https://github.com/dmlc/tvm/pull/4176
in cmake/util/FindANTLR.cmake,
```cmake 
 set(ANTLR4 ${JAVA_PROGRAM} -jar ${use_antlr})
```
cmake will  ignore the  "space"

**Comment by OriAlpha** [comment]
This is the issue with the latest build of TVM, Now we can't even use the TVM packages of python.

**Comment by apivovarov** [comment]
Related issue https://github.com/dmlc/tvm/issues/4226
`tvm/relay/std/prelude.rly` is missing
