### ISSUE TITLE
Plan for auto-tuner

### ISSUE THREAD

**Issue by xqdan** [dmlc/tvm#423]
Hi all, 
   After went through paper of Halide,  noticed that hailde has implemented an auto-tuning optimizer, see links here: http://graphics.cs.cmu.edu/projects/halidesched/.
   If I'm correct, TVM is pretty much the same as stage 1 of Halide, which was published at the year of 2013,  see links here: http://people.csail.mit.edu/jrk/halide-pldi13.pdf

  So, my question is, is there any plan for auto-tuning optimizer? BTW, IMO, in graph IR, we can get more information across kernels, maybe it's a better place to decide the schedule, or make the trade off. Which abstraction is better for the auto-tuning optimizer anyway?   

  Thanks!

**Comment by tqchen** [comment]
In order to get a good autotuned kernels, there are two part to get the ingredients right: 

- A large enough space of schedules to cover the state of art techniques in handcrafting kernels,
- A auto tuner that can effectively explore the space.

The focus of the project so far has been on part one, because if the schedule space is not good enough,  we never get the comparable performance, however clever the enumeration is. There was a quite a a lot of heavy lifting to close in this part and I think we are getting quite enough ingredient here.

with the scripts API we have, it is pretty straight forward to get some quick auto-tuning scripts for the workloads we care, which is the techniques we use to get some of the optimized kernels.

A more principled auto tuner is on our roadmap

**Comment by tqchen** [comment]
for relation with existing projects like Halide you mentioned

**Comment by xqdan** [comment]
Thanks, @tqchen , look forward to detailed plan for principled auto-tuner in the future.

**Comment by xqdan** [comment]
Hi, @tqchen , a follow up question, what's the difference between TVM and Halide, if TVM can use Hailide's IR,, why don't we just use the whole Halide directly?

**Comment by tqchen** [comment]
http://docs.tvmlang.org/faq.html#tvm-s-relation-to-other-ir-dsl-projects  answers the difference from existing projects, including Halide.  In short, we specifically focus on deep learning, and optimize for multiple hardware backends.

As I mentioned in the first post, the major challenge is to make the schedule space complete enough to cover the state of art kernels for hardware back-ends we want to support, specifically gpu and other hardwares. The second challenge is to build the dsl representation to cover things we care about in deep learning(e.g. recurrence). The other issues include the ease of deployment and interpolation.

These challenges are not well addressed by existing frameworks(including Halide) and requires rethink and design of the stack as opposed to simply reuse an existing one.

You can also find that the TVM's IR itself is evolving, and we continuously learn new lessons from hand optimization and tuning for various backends.

**Comment by tqchen** [comment]
As for your question in multi-stage scheduling. I think you already answered your own question, in a sense that tvm is intended to be used with graph level IR like nnvm, which gives you graph information and libraries like TOPI will make this problem easier

**Comment by xqdan** [comment]
I think graph IR is a better place to do optimization of auto-multiple-stages, because of you will get more information about the whole pipeline, TOPI is just a temporary and practical solution in involving. 
For example,  the main idea in the paper of Halide 2016 is to partition the functions/stages in a large Halide program into groups (subprograms), and independently perform producer-consumer locality and input reuse locality transformations on these groups. 

About differences between Halide and TVM,  still confused to me.
1)"Schedule space“ you mentioned above,  what are they Hailde can't have? or will it be hard to extend this on Halide? 
2)why TVM cares about the ability of representation, if TVM is a back-end IR of whole stack， that's the question graph engines should care. 

Will there be a paper or something to elaborate your points above? I think this might be a often asked question with TVM growing. All of us might wanna know TVM is a new idea or just another wheel.

Thanks!

**Comment by tqchen** [comment]
I think your also raises an valuable point here, in a sense that graph ir is necessary to work together with the low level ir for the workload optimization, that is exactly the approach we are taking right now. With nnvm for the graph level stack and tvm/topi as tensor level stack

**Comment by xqdan** [comment]
figure out problems, and solve them on the

**Comment by xqdan** [comment]
The things we need to do in whole stack
1) Coarse-grained operators optimization: operators/kernels/stages fusion and layout optimization, which are main issues XLA/NNVM, or other graph engines are trying to improve.
2) Fine-grained operators optimization: single kernel/across kernels performance,  on which tvm/halide focus.

So differences between halide and tvm, 
1)  halide is a tensor type dsl/IR，which don't have coarse-grained operators optimization, which are on graph engines, 
2) it might be very hard or limited to do these coarse-grained operators optimizations on tensor IR
3) also I guess auto-tuner on graph IR might be simpler and easier than on tensor.

It seems that Tvm itself might  be similar with Halide, but with graph ir, they will be much more powerful.
It makes more sense to me now.

Thanks.

**Comment by tqchen** [comment]
Your comment on the importance of two level stack is good. On the other hand, on the tensor ir level alone also  contains quite a lot of innovations, mainly on the scheduling primitives and language(e.g. recurrence support) to get more effective kernels on gpus and other hardwares, that is what I mean by representation power.

**Comment by xqdan** [comment]
Hi Tianqi,  I've done some research on NNVM, notice that, there is no true IR in NNVM, user can register IR information via attributes, and user implements pass based on these attributes. also I don't see classical compiler related analysis like data flow, control flow, dependence test. Please confirm my understanding is correct first.
If I'm correct on most of part, I think NNVM is a good layer for domain specific optimization, like algebraic transformation in deep learning, which is not covered by traditional compiler technologies.  
But it might be hard for NNVM to flow into a true compiler IR like TVM.

Besides, when you look into XLA that has true IR, you will notice that graph related optimization chances (which is orthogonal to  algebraic transformation on NNVM) do exist on this layer, also layer like XLA is 
suitable for auto-tuner/auto-scheduler.

IMO, maybe NNVM + something like XLA + TVM is a better IR stack. 

Thanks!

**Comment by tqchen** [comment]
@xqdan I totally agree with what you said on graph ir based solution and the original version of nnvm lacks core operator support for that(the comment seems to be deleted). we have been working on such a graph ir based solution, you can checkout https://github.com/dmlc/nnvm for the end to end compiler. Maybe we could move the discussion over to NNVM

**Comment by xqdan** [comment]
that's cool
