### ISSUE TITLE
Windows build fails due to standalone micro runtime

### ISSUE THREAD

**Issue by JoshNoel** [dmlc/tvm#4232]
Attempting to build on Windows fails with config.cmake options [set(USE_CUDA ON), set(USE_LLVM ON)]. The build process followed instructions @ https://docs.tvm.ai/install/from_source.html

By default the micro runtime is built, however this fails due to incompatibility with Windows.
For example, see unix-specific library export macro definitions:
- "TVM_MICRO_RUNTIME_API_API" - include/tvm/runtime/micro/standalone/utvm_runtime.h
- "TVM_MICRO_RUNTIME_API_BACKEND_API" - src/runtime/micro/standalone/utvm_graph_runtime.h

(Note, further incompatibilities exist after resolving these definitions, however I did not debug further)

I was able to successfully build by disabling compilation of the micro runtime [config.cmake option set(USE_MICRO_STANDALONE_RUNTIME **ON->OFF**)]. While this resolved the problem for me, I am unsure if this runtime is a general requirement.

**Comment by tqchen** [comment]
Given that the micro runtime is only works under unix, perhaps it makes sense to disable ti by default, but explicitly enable it in ci, cc @ajtulloch

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/4240
