### ISSUE TITLE
Option to set the step/stride in reduce_axis 

### ISSUE THREAD

**Issue by wetliu** [dmlc/tvm#426]
@Huyuwei and I found that it may be useful to support step/stride, the distance between two adjacent values, in reduce axis (for dilation). It could help skip step number of elements for the reduce axis, instead of branching.

**Comment by tqchen** [comment]
Would this be equivalent to (stride =2)

```
tvm.sum(A[k*2], k=tvm.reduce_axis((0, n/2))
```

**Comment by wetliu** [comment]
Yes. It is equivalent to modify the compute in this way. Thank you!
