### ISSUE TITLE
Dot product involving one binary vector

### ISSUE THREAD

**Issue by mitscha** [dmlc/tvm#454]
Hi, suppose I want to compute the dot product between two vectors **a** and **b** on a GPU, where **a** has entries in {0,1}, with a percentage of zeros between 50 and 80%, and **b** has arbitrary values as entries. **a** is constant and known at compile time, whereas **b** takes a different value at every evaluation. Thanks to the structure of **a**, the dot product in principle reduces to the sum over a subset of entries of **b**. Is there a way to implement this dot product in TVM explicitly as a sum, and if so, will I observe speedups compared to naively computing the dot product?

Thanks

**Comment by tqchen** [comment]
```python
import tvm

a = [1, 0, 2, 3]
b = tvm.placeholder((4,), name="B")
c = tvm.compute((1,), lambda i: tvm.sum(*[v * b[i] for i, v in enumerate(a) if v]))
print(c.op.body)
```

**Comment by tqchen** [comment]
I am not sure though if this will speedup computation. You might, however, this means fully unroll the dot product instead of using a loop, where you save in terms of compute but requires more instruction cache. You should try it out on your workload and I am curious to see what you could get :)

**Comment by wetliu** [comment]
I printed out the naive schedule and it seems like this is what he is looking for. I am wondering why it costs more instruction cache though, once the code is generated at compile time? Thanks

**Comment by mitscha** [comment]
Yeah, this is what I had in mind, thanks!! I'll update once I have results.

**Comment by tqchen** [comment]
Many cases the reduction contains many levels, and can be done with a for loop, in that way you get instruction cache reuse across because of the for loop. To do the sparse aware optimisation means  the need of fully unroll the loop, which increases the cost of instruction cache.

This might be less of the problem if the sparsity is structured, e.g. we are dense on one dimension and sparse on another, so we still get instruction reuse on the dense dimension

**Comment by wetliu** [comment]
Interesting. I have learned a lot. Thank you!

**Comment by wetliu** [comment]
Is it possible sum beyond the 1024 elements if we don't have things like global sync or atomic add? @tqchen

**Comment by tqchen** [comment]
I agree that atomic add should be added at some moment, as this seems to be a more common pattern we might use
