### ISSUE TITLE
How to install the libtvm.dll？

### ISSUE THREAD

**Issue by Arthur-Shi** [dmlc/tvm#493]
I cannot install successfully because 

Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    LIB_PATH = libinfo['find_lib_path']()
  File "./tvm/_ffi/libinfo.py", line 85, in find_lib_path
    str('\n'.join(lib_dll_path + runtime_dll_path)))
RuntimeError: Cannot find the files.
List of candidates:
C:\tvm-master\python\tvm\libtvm.dll
C:\tvm-master\build\libtvm.dll
C:\tvm-master\build\Release\libtvm.dll
C:\tvm-master\lib\libtvm.dll
C:\libtvm.dll
C:\tvm-master\python\tvm\tvm.dll
C:\tvm-master\build\tvm.dll
C:\tvm-master\build\Release\tvm.dll
C:\tvm-master\lib\tvm.dll
C:\tvm.dll
C:\tvm-master\python\tvm\libtvm_runtime.dll
C:\tvm-master\build\libtvm_runtime.dll
C:\tvm-master\build\Release\libtvm_runtime.dll
C:\tvm-master\lib\libtvm_runtime.dll
C:\libtvm_runtime.dll
C:\tvm-master\python\tvm\tvm_runtime.dll
C:\tvm-master\build\tvm_runtime.dll
C:\tvm-master\build\Release\tvm_runtime.dll
C:\tvm-master\lib\tvm_runtime.dll
C:\tvm_runtime.dll

I think it is due to fail to build the Shared Library, isnot it？

But how can I install the libtvm.dll?

**Comment by tqchen** [comment]
You need to build libtvm.dll with CMake, see http://docs.tvmlang.org/how_to/install.html#building-on-windows

**Comment by Arthur-Shi** [comment]
I had installed successfully,
C:\tvm-master\build>cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES="Release" ..
-- Build with RPC support...
-- Build with Graph runtime support...
-- Configuring done
-- Generating done
-- Build files have been written to: C:/tvm-master/build

But still 

C:\tvm-master\python> python setup.py install --user
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    LIB_PATH = libinfo['find_lib_path']()
  File "./tvm/_ffi/libinfo.py", line 85, in find_lib_path
    str('\n'.join(lib_dll_path + runtime_dll_path)))
RuntimeError: Cannot find the files.
List of candidates:
C:\tvm-master\python\tvm\libtvm.dll
C:\tvm-master\build\libtvm.dll
C:\tvm-master\build\Release\libtvm.dll
C:\tvm-master\lib\libtvm.dll
C:\libtvm.dll
C:\tvm-master\python\tvm\tvm.dll
C:\tvm-master\build\tvm.dll
C:\tvm-master\build\Release\tvm.dll
C:\tvm-master\lib\tvm.dll
C:\tvm.dll
C:\tvm-master\python\tvm\libtvm_runtime.dll
C:\tvm-master\build\libtvm_runtime.dll
C:\tvm-master\build\Release\libtvm_runtime.dll
C:\tvm-master\lib\libtvm_runtime.dll
C:\libtvm_runtime.dll
C:\tvm-master\python\tvm\tvm_runtime.dll
C:\tvm-master\build\tvm_runtime.dll
C:\tvm-master\build\Release\tvm_runtime.dll
C:\tvm-master\lib\tvm_runtime.dll
C:\tvm_runtime.dll

What should I do?

**Comment by tqchen** [comment]
Please double check if the file is already in the path listed in the candidate

**Comment by tqchen** [comment]
After you build cmake in windows, you will need to open visual studio and compile that with VS

**Comment by Arthur-Shi** [comment]
Yes, I cannot find these files listed. and what it compiling that with VS?
I had tried run the tvm.sln in the build folder by VS, But nothing changed.

I am so sorry about these stupid questions, Thank you for your patient reply so much.

**Comment by tqchen** [comment]
YOu need to open the solution and do build in visual studio to create the dll

**Comment by Arthur-Shi** [comment]
Thanks for your help,
 I installed it successfully,
