### ISSUE TITLE
can't run get_start tutorial

### ISSUE THREAD

**Issue by gengtsh** [dmlc/tvm#517]
hello, i'm new in tvm. i encounter some problem when i run get_start.py in tutorial, i'd appreciate if someone can help me out, thanks in advance. 

here are my basic experiment configuration:
1. run tvm in ubutu 16 VM
2. install llvm, cuda-compiler, but didn't install nvidia driver, because of my vm can't access my nvidia graphic card.
3. install python following the install doc. and my python version is 3.5.
4. set flags (use_cuda, cuda_path, llvm-config-5.0) in config.mkrun make, succeed. 

here is my problem:
1. fadd_cuda = tvm.build(s, [A, B, C], "cuda", target_host="llvm", name="myadd")
my error is cuda is not enable.

**Comment by tqchen** [comment]
the tutorial will indeed need a real cuda machine to run nvidia code. But you can also explore other targets like cpu or target supported by y9our machine

**Comment by tqchen** [comment]
you can also directly browse the tutorials via http://docs.tvmlang.org/tutorials/index.html

**Comment by gengtsh** [comment]
thanks for you prompt reply. 
i have one more question, i want to run it on ARM, is there example talking about how to do it?

**Comment by tqchen** [comment]
http://docs.tvmlang.org/tutorials/deployment/cross_compilation_and_rpc.html#sphx-glr-tutorials-deployment-cross-compilation-and-rpc-py
