### ISSUE TITLE
[Tutorial] Use OpenCL on ARM Board

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#525]
While http://docs.tvmlang.org/tutorials/deployment/cross_compilation_and_rpc.html#sphx-glr-tutorials-deployment-cross-compilation-and-rpc-py covers how to cross compile and deploy CPU code on ARM board, it did not touch how to do so for the OpenCL code.

We have unittest examples to demonstrate that https://github.com/dmlc/tvm/blob/master/tests/python/unittest/test_runtime_rpc.py#L92 already. It would be nice to translate these lessons into the cross compilation tutorial

**Comment by jielingTang** [comment]
i am trying  generate OpenCL code  and run it . my device is [ubuntu]Firefly-RK3288
the test file   is  "get_start.py"    on  "Get Started with TVM" 
How should I solve this problem  
<class 'tvm.tensor.Tensor'>
[14:40:33] src/runtime/opencl/opencl_device_api.cc:195: Initialize OpenCL platform 'ARM Platform'
[14:40:33] src/runtime/opencl/opencl_device_api.cc:215: opencl(0)='Mali-T760' cl_device_id=0xb3948938
[14:40:33] /home/tang/tvm/dmlc-core/include/dmlc/logging.h:308: [14:40:33] src/runtime/opencl/opencl_module.cc:210: Check failed: e == CL_SUCCESS OpenCL Error, code=-51: CL_INVALID_ARG_SIZE
Traceback (most recent call last):
  File "get_started.py", line 49, in <module>
    fadd_cl(a, b, c)
  File "/home/tang/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-armv7l.egg/tvm/_ffi/function.py", line 128, in __call__
    return f(*args)
  File "/home/tang/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-armv7l.egg/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/tang/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-armv7l.egg/tvm/_ffi/base.py", line 62, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [14:40:33] src/codegen/llvm/llvm_module.cc:59: Check failed: ret == 0 (-1 vs. 0) [14:40:33] src/runtime/opencl/opencl_module.cc:210: Check failed: e == CL_SUCCESS OpenCL Error, code=-51: CL_INVALID_ARG_SIZE

**Comment by ma-xiaodong** [comment]
Here is an example of using OpenCL on ARM Board.
https://github.com/ma-xiaodong/tvm_tuning/blob/master/02_conv_order.py
which corresponding the program
http://docs.tvmlang.org/tutorials/optimize/opt_conv_cuda.html#sphx-glr-tutorials-optimize-opt-conv-cuda-py
of optimizing conv on cuda.

**Comment by kaishijeng** [comment]
ma-xiaodong:
Are you to tune Mali-T860 opencl to  pass test_topi_conv2d_nchw.py unittest in topi/tests/python directory? 

I always encounter an error because of insufficient resources on a firefly3399 platform running Ubuntu 16.04
https://github.com/dmlc/tvm/issues/530

Thanks,

**Comment by ma-xiaodong** [comment]
I also encountered the error CL_OUT_OF_RESOURCES.
In order to use opencl, you must split a dimension of an array and  bind the results to threadIdx and blockIdx.
I guess this error occurs because three reasons:
1. You split a inner dimension instead of an outer dimension. 
2. You split a dimension whose length is short.
3. Maybe the split factor is too big. 

I suggest:
1. Split the out dimension first
2. Split dimension with big length (you can reorder the array if needet)
3. Use a small factor(4, or 8, no big than 16)

**Comment by ma-xiaodong** [comment]
#530

**Comment by kaishijeng** [comment]
>>In order to use opencl, you must split a dimension of an array and bind the results to threadIdx and >>blockIdx.

Which file do I need to change threadidx and blockidx? Is there a program which can tune to get optimal values of threadidx and blockidx?

**Comment by ma-xiaodong** [comment]
> Which file do I need to change threadidx and blockidx? Is there a program which can tune to get optimal values of threadidx and blockidx?

Here is an example of using OpenCL on ARM Board.
https://github.com/ma-xiaodong/tvm_tuning/blob/master/02_conv_order.py

**Comment by kaishijeng** [comment]
@ma-xiaodong 

Why are you not using the following conv2d modules

https://github.com/dmlc/tvm/blob/master/topi/python/topi/cuda/conv2d_nchw.py
https://github.com/dmlc/tvm/blob/master/topi/python/topi/cuda/conv2d_hwcn.py

conv2d_nchw.py looks more complex than your 02_conv_order.py. 
My firefly 3399 has a problem to pass conv2d_nchw.py due to insufficient resources.

Thanks,

**Comment by titikid** [comment]
@ma-xiaodong i couldn't access to your file: [https://github.com/ma-xiaodong/tvm_tuning/blob/master/02_conv_order.py](url), can you update the link?

**Comment by ma-xiaodong** [comment]
@titikid My example is too old, so I remove it. TVM already has good example.
https://github.com/dmlc/tvm/blob/master/topi/python/topi/cuda/conv2d_hwcn.py

**Comment by titikid** [comment]
@ma-xiaodong i see. Anyway, after use smaller split factor in conv2d_nchw.py as your hint i could solve my issue related to openCL. Thank you
