### ISSUE TITLE
Not all runtime headers installed

### ISSUE THREAD

**Issue by doctaweeks** [dmlc/tvm#527]
It's not clear to me whether the problem is here or in nnvm. [nnvm references a runtime header directly](https://github.com/dmlc/nnvm/blob/d78387e0669c0d661908da9f8a09a9d57db6da0e/src/compiler/graph_runtime.h#L12), however, it's not installed when INSTALL_DEV is enabled.

It seems either NNVM should not be using a private header otherwise it should be installed by tvm.

**Comment by tqchen** [comment]
Thanks for pointing this out. It should be able to be solved by https://github.com/dmlc/nnvm/pull/163
