### ISSUE TITLE
[WINDOWS] LLVM pre build binaries do not include cmake files

### ISSUE THREAD

**Issue by cudawarped** [dmlc/tvm#533]
Hi,
Is there a way to install tvm on windows with the LLVM pre build binaries if the windows binaries do not include the cmake files?

**Comment by austingg** [comment]
yes, so I build llvm from source on windows.

**Comment by cudawarped** [comment]
I had build llvm from source but I get errors in get_started.py when I try to save the model.  Specifically

> Traceback (most recent call last):
  File "get_started.py", line 184, in <module>
    cc.create_shared(temp.relpath("myadd.so"), [temp.relpath("myadd.o")])
  File "C:\Users\cudawarped\Anaconda3\lib\site-packages\tvm-0.1.0-py3.6-win-amd64.egg\tv
m\contrib\cc.py", line 48, in create_shared
    msg += out
TypeError: must be str, not bytes

Is this related to the way I have build llvm or is this an issue with tvm on windows?

**Comment by BigJerry** [comment]
@cudawarped which tutorial you follow for compilation of llvm. I'd try compile it but it always stuck without throw an error..

**Comment by cudawarped** [comment]
@BigJerry from memory I just used the 5.0 source with cmake, building with Visual Studio 2015 Community with update 3.  

I did pass the [host=x64](https://jamesbowley.co.uk/wp-content/uploads/2017/11/llvm_host.png) to cmake as suggested in the llvm documentation but it built fine without it.   Where is your build failing?

**Comment by austingg** [comment]
@BigJerry  I have met that problem， which caused by not enough memory， You may select another device  to compile LLVM, since LLVM is a big project.

**Comment by BigJerry** [comment]
It's weird that compilation process stop at random file.Even sometimes it stuck at generating(by cmake) period. I use 5.0 src too,and I pass -Thost=x64 to command line.Anyway compilation can't be finished successfully...btw, my computer has 16GB memory in case if you curious. @cudawarped

**Comment by BigJerry** [comment]
Why you so sure It's caused by memory capacity? I checked that It's not using too much memory (around 4GB) while compiling . what is your memory capacity in your case, and I want to know if you had succeed by now? How you get there? @austingg

**Comment by austingg** [comment]
@BigJerry  My laptop has only 4G memory， during the compilation(linking phase),  the memory has be run out, and it began to use the swap segmentation.  
That's On Ubuntu. On Windows, there is no problem.

**Comment by BigJerry** [comment]
did you ever install clang before building llvm?or any other dependence?can you offer your workflow for building it ? thanks in advance. @austingg

**Comment by austingg** [comment]
@BigJerry , Just download llvm source code and use cmake and visual studio 2015 community to build, nothing special.

**Comment by cudawarped** [comment]
@BigJerry same as austingg, the exact details are
OS: Windows 8.1
CMake: 3.9.1
RAM: 16GB
LLVM 5.0  - http://releases.llvm.org/5.0.0/llvm-5.0.0.src.tar.xz
Visual Studio 2015 Community (14.0.25431.01) with Update 3

**Comment by BigJerry** [comment]
I've built it via a .. um... strange way . I'm not sure if I have built it correctly. how many libs and bins you'd got from building(llvm 5.0.0) ? @cudawarped

**Comment by BigJerry** [comment]
ok, I've built it successfully by randomly killing some process while building. anyway , thanks for your reply. @austingg

**Comment by Fighting-JJ** [comment]
> ok, I've built it successfully by randomly killing some process while building. anyway , thanks for your reply. @austingg

How do you know you had build it correctly? Can it make TVM works well?  @BigJerry
