### ISSUE TITLE
Is there api for dump nnvm params to file?

### ISSUE THREAD

**Issue by nkyle04** [dmlc/tvm#534]
I have run a mxnet model at nnvm. 
As I want to deploy it with tvm, but i can't find any api to dump params to bytearray, which was need ed in "load_params" funtion. 
As described at http://nnvm.tvmlang.org/how_to/deploy.html

**Comment by tqchen** [comment]
http://nnvm.tvmlang.org/api/python/compiler.html#nnvm.compiler.load_param_dict

**Comment by tqchen** [comment]
Since this might be a common need, do you mind open a PR and add this information to the how to deploy document?
