### ISSUE TITLE
wasm engine npm publication

### ISSUE THREAD

**Issue by Jabher** [dmlc/tvm#539]
Hi! I'd be happy to experiment with tvm in JS, but I was not able to find any releases on npm.

I can try to help if you need any assistance with that.

**Comment by tqchen** [comment]
You should be able to find everything you need in here https://github.com/dmlc/tvm/tree/master/web

TVM is a bit non-typical than a traditional js package as it allows you to "generate new javascript code" from TVM DSL (which current supported in python and c++ so all infrastructure can be reused). We provide a simple runtime to allow you to dynamically plugin the generated code and even run it on the browser which is remotely connected to your python script.

**Comment by Jabher** [comment]
I've been thinking more about 
- calling C++ functions in node.js (to make some machine learning with node.js)
- calling WASM code in browser without any RPC - plain math on web browser/mobile browser.

I can probably try to make some isomorphic API/WASM wrapper for JS if you will advice me about where to look first.

**Comment by tqchen** [comment]
The javascript runtime is already in there, and you do not have to use it via RPC. see example scripts in https://github.com/dmlc/tvm/tree/master/tests/web

The RPC component is just used to make the testing and exploration easier, so we can generate and ship from python end without having to write verification code in javascript

**Comment by tqchen** [comment]
you can also find a document here http://docs.tvmlang.org/api_links.html
