### ISSUE TITLE
[WINDOWS] Error in cc.create_shared following update #531

### ISSUE THREAD

**Issue by cudawarped** [dmlc/tvm#555]
Hi, I have recompiled tvm following the latest update, and I am getting a new error in get_started.py

> Traceback (most recent call last):
  File "get_started.py", line 184, in <module>
    cc.create_shared(temp.relpath("myadd.so"), [temp.relpath("myadd.o")])
  File "C:\Users\b8\Anaconda3\lib\site-packages\tvm-0.1.0-py3.5-win-amd64.egg\tv
m\contrib\cc.py", line 34, in create_shared
    _windows_shared(output, objects, options)
  File "C:\Users\b8\Anaconda3\lib\site-packages\tvm-0.1.0-py3.5-win-amd64.egg\tv
m\contrib\cc.py", line 84, in _windows_shared
    cl_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "C:\Users\b8\Anaconda3\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Users\b8\Anaconda3\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by tqchen** [comment]
cc @yajiedesign

**Comment by cudawarped** [comment]
I also get a lot of unresolved external symbols when I try to use the latest build of tvm when compiling nnvm

> 1>compile_engine.obj : error LNK2019: unresolved external symbol "public: virtual bool const __cdecl tvm::Node::_DerivedFrom(unsigned int)const " (?_DerivedFrom@Node@tvm@@UEBA?B_NI@Z) referenced in function "public: virtual bool const __cdecl nnvm::compiler::GraphCacheEntryNode::_DerivedFrom(unsigned int)const " (?_DerivedFrom@GraphCacheEntryNode@compiler@nnvm@@UEBA?B_NI@Z)
1>graph_fuse.obj : error LNK2001: unresolved external symbol "public: virtual bool const __cdecl tvm::Node::_DerivedFrom(unsigned int)const " (?_DerivedFrom@Node@tvm@@UEBA?B_NI@Z)
1>graph_hash.obj : error LNK2001: unresolved external symbol "public: virtual bool const __cdecl tvm::Node::_DerivedFrom(unsigned int)const " (?_DerivedFrom@Node@tvm@@UEBA?B_NI@Z)
1>packed_func_ext.obj : error LNK2001: unresolved external symbol "public: virtual bool const __cdecl tvm::Node::_DerivedFrom(unsigned int)const " (?_DerivedFrom@Node@tvm@@UEBA?B_NI@Z)
1>compile_engine.obj : error LNK2019: unresolved external symbol "public: static unsigned int __cdecl tvm::Node::TypeKey2Index(char const *)" (?TypeKey2Index@Node@tvm@@SAIPEBD@Z) referenced in function "public: virtual unsigned int const __cdecl nnvm::compiler::GraphCacheEntryNode::type_index(void)const " (?type_index@GraphCacheEntryNode@compiler@nnvm@@UEBA?BIXZ)
1>graph_fuse.obj : error LNK2001: unresolved external symbol "public: static unsigned int __cdecl tvm::Node::TypeKey2Index(char const *)" (?TypeKey2Index@Node@tvm@@SAIPEBD@Z)
1>graph_hash.obj : error LNK2001: unresolved external symbol "public: static unsigned int __cdecl tvm::Node::TypeKey2Index(char const *)" (?TypeKey2Index@Node@tvm@@SAIPEBD@Z)
1>packed_func_ext.obj : error LNK2001: unresolved external symbol "public: static unsigned int __cdecl tvm::Node::TypeKey2Index(char const *)" (?TypeKey2Index@Node@tvm@@SAIPEBD@Z)
1>compile_engine.obj : error LNK2019: unresolved external symbol "public: static char const * __cdecl tvm::Node::TypeIndex2Key(unsigned int)" (?TypeIndex2Key@Node@tvm@@SAPEBDI@Z) referenced in function "public: class tvm::IRFunctor<void __cdecl(class tvm::NodeRef const &,class Halide::Internal::IRPrinter *)> & __cdecl tvm::IRFunctor<void __cdecl(class tvm::NodeRef const &,class Halide::Internal::IRPrinter *)>::set_dispatch<struct nnvm::compiler::GraphFuncNode>(class std::function<void __cdecl(class tvm::NodeRef const &,class Halide::Internal::IRPrinter *)>)" (??$set_dispatch@UGraphFuncNode@compiler@nnvm@@@?$IRFunctor@$$A6AXAEBVNodeRef@tvm@@PEAVIRPrinter@Internal@Halide@@@Z@tvm@@QEAAAEAV01@V?$function@$$A6AXAEBVNodeRef@tvm@@PEAVIRPrinter@Internal@Halide@@@Z@std@@@Z)
1>graph_hash.obj : error LNK2001: unresolved external symbol "public: static char const * __cdecl tvm::Node::TypeIndex2Key(unsigned int)" (?TypeIndex2Key@Node@tvm@@SAPEBDI@Z)

**Comment by tqchen** [comment]
This can be resolved already, if you update the nnvm version to latest and do git submodule update --recursive

**Comment by yajiedesign** [comment]
please run it in `x64 Native Tools Command Prompt for VS`.

**Comment by tqchen** [comment]
is this an environment variable issue?

**Comment by yajiedesign** [comment]
@tqchen This should be added to the document. Which one is the relevant document?

**Comment by yajiedesign** [comment]
normally not add vs to the environment variable. when necessary, start a console with the vs environment.

**Comment by yajiedesign** [comment]
Automatic lookups can be considered, but it is hard to automatically  choose when there are multiple versions of visual studio.
Or just give a friendly hint.

**Comment by tqchen** [comment]
I think if cl.exe is not found in the env, give a hint error message is a reasonable way to go. What I normally do is to add that to the env variable.

**Comment by yajiedesign** [comment]
ok.i am add error message.

**Comment by cudawarped** [comment]
Thank you, running get_started.py from 

> x64 Native Tools Command Prompt for VS

worked perfectly.

When I perform git submodule update --recursive in nvvm, tvm is set to 
Submodule path 'tvm': checked out 'eb761f36302d24c740b77281ecdcdddb588edf36'
is this the correct commit, because I still get the above linking error when trying to compile nvvm?
