### ISSUE TITLE
How to lower to matrix instructions?

### ISSUE THREAD

**Issue by xqdan** [dmlc/tvm#569]
Hi, all,

How to lower tensor to matrix instructions, like 16*16 matrix/tensor multiply or add, rather than two nests loops with operations in tvm?

Thanks!

**Comment by tqchen** [comment]
this is a planned feature that is yet to be officially announced so please stay tuned

**Comment by derisavi** [comment]
I'm interested in this too. Do you have any rough timeline on developing this feature or the required infrastructure?

**Comment by tqchen** [comment]
All the elements are in, it is mainly effort of documentation and testing

**Comment by xqdan** [comment]
that's great!

**Comment by tqchen** [comment]
close this for now and will update when more documents get in
