### ISSUE TITLE
Module[stackvm] does not support SaveToFile， What should I install ?

### ISSUE THREAD

**Issue by Arthur-Shi** [dmlc/tvm#580]
python '/tvm/tutorials/get_started.py' 
TVM: Initializing cython mode...
<class 'tvm.tensor.Tensor'>
-----CUDA code-----
extern "C" __global__ void myadd__kernel0(float* __restrict__ C, float* __restrict__ A, float* __restrict__ B, int n) {
  if (((int)blockIdx.x) < ((n + -127) / 64)) {
    C[((((int)blockIdx.x) * 64) + ((int)threadIdx.x))] = (A[((((int)blockIdx.x) * 64) + ((int)threadIdx.x))] + B[((((int)blockIdx.x) * 64) + ((int)threadIdx.x))]);
  } else {
    if ((((int)blockIdx.x) * 64) < (n - ((int)threadIdx.x))) {
      C[((((int)blockIdx.x) * 64) + ((int)threadIdx.x))] = (A[((((int)blockIdx.x) * 64) + ((int)threadIdx.x))] + B[((((int)blockIdx.x) * 64) + ((int)threadIdx.x))]);
    }
  }
}

[17:59:29] /tvm/dmlc-core/include/dmlc/logging.h:308: [17:59:29] src/runtime/module.cc:77: Module[stackvm] does not support SaveToFile

Stack trace returned 10 entries:
[bt] (0) /home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f5e650094dc]
[bt] (1) /home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so(_ZN3tvm7runtime10ModuleNode10SaveToFileERKSsS3_+0x2c6) [0x7f5e653e91d6]
[bt] (2) /home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so(+0x59c952) [0x7f5e653ee952]
[bt] (3) /home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so(TVMFuncCall+0x5a) [0x7f5e653f364a]
[bt] (4) /home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/_cy2/core.so(+0x18ca7) [0x7f5e621f2ca7]
[bt] (5) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (6) python(PyEval_EvalFrameEx+0x2ad1) [0x4c6ad1]
[bt] (7) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (8) python(PyEval_EvalFrameEx+0x68d1) [0x4ca8d1]
[bt] (9) python(PyEval_EvalCodeEx+0x255) [0x4c2765]

Traceback (most recent call last):
  File "/home/aries/testtvm/tvm/tutorials/get_started.py", line 182, in <module>
    fadd_cuda.save(temp.relpath("myadd.o"))
  File "/home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/module.py", line 68, in save
    _SaveToFile(self, file_name, fmt)
  File "/home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/function.py", line 255, in my_api_func
    return flocal(*args)
  File "tvm/_ffi/_cython/./function.pxi", line 264, in core.FunctionBase.__call__
  File "tvm/_ffi/_cython/./function.pxi", line 213, in core.FuncCall
  File "tvm/_ffi/_cython/./function.pxi", line 205, in core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 131, in core.CALL
tvm._ffi.base.TVMError: [17:59:29] src/runtime/module.cc:77: Module[stackvm] does not support SaveToFile

Stack trace returned 10 entries:
[bt] (0) /home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f5e650094dc]
[bt] (1) /home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so(_ZN3tvm7runtime10ModuleNode10SaveToFileERKSsS3_+0x2c6) [0x7f5e653e91d6]
[bt] (2) /home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so(+0x59c952) [0x7f5e653ee952]
[bt] (3) /home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so(TVMFuncCall+0x5a) [0x7f5e653f364a]
[bt] (4) /home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/_cy2/core.so(+0x18ca7) [0x7f5e621f2ca7]
[bt] (5) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (6) python(PyEval_EvalFrameEx+0x2ad1) [0x4c6ad1]
[bt] (7) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (8) python(PyEval_EvalFrameEx+0x68d1) [0x4ca8d1]
[bt] (9) python(PyEval_EvalCodeEx+0x255) [0x4c2765]

**Comment by tqchen** [comment]
Please build with llvm support

**Comment by Arthur-Shi** [comment]
OK, thank you
