### ISSUE TITLE
Where can I find the saved compiled modules files?

### ISSUE THREAD

**Issue by Arthur-Shi** [dmlc/tvm#589]
In get_started with TVM,

temp = util.tempdir()
fadd_cuda.save(temp.relpath("myadd.o"))
fadd_cuda.imported_modules[0].save(temp.relpath("myadd.ptx"))
cc.create_shared(temp.relpath("myadd.so"), [temp.relpath("myadd.o")])

fadd_cuda.export_library(temp.relpath("myadd_pack.so"))

How can I save them files /tmp/tmpcIyJYu/myadd.o even if I finished running the files.

The compiled modules of TVM only depends on a minimum runtime library. So after I saved the compiled modules and exported it into shared library,  I can call them without running again from any thread, on any GPUs？

Can I run the compiled files without installing the Cuda&LLVM&TVM on other compuer?

**Comment by tqchen** [comment]
You can simply save compiled modules into the path you want. tempdir is only a util to get a temp directory. You don't have to use it, just do save and other functions with the files will do.

You will need tvm runtime to deploy the module see http://docs.tvmlang.org/how_to/deploy.html

**Comment by tqchen** [comment]
You do not need compiler toolchain to deploy, so no LLVM, TVM. If you compile GPU code, cuda runtime is indeed needed

**Comment by Arthur-Shi** [comment]
@tqchen Thank u for ur help.
When I run the cpp_deploy.cc to learn how to use them, output: 
g++ '/home/aries/tvm/apps/howto_deploy/cpp_deploy.cc' 
/home/aries/tvm/apps/howto_deploy/cpp_deploy.cc:7:27: fatal error: dlpack/dlpack.h: No such file or directory
 #include <dlpack/dlpack.h>
                           ^
compilation terminated.

But I find the dlpack.h in the /home/aries/tvm/dlpack/include/dlpack, and then I tried to copy it into /home/aries/tvm/include, the outputs are same.
Why?

And I find the .so file only save one function tvm.build, which means that if I would like to design a faster-rcnn, I need to save different .so files when the tvm.compute are different. 
Is it right? Or I can save whole python file into .so file?

**Comment by tqchen** [comment]
You will need to add the path to dlpack during compilation.  In normal mode tvm.build only build one function. But actually there is no such restriction. We can link multiple functions together. NNVM compiler does that automatically for you and packs all functions of a net  into one module.

**Comment by Arthur-Shi** [comment]
I tried to move these files in include to the C++ include.
root@aries:/home/aries/tvm/include# cp -r /home/aries/tvm/dmlc-core/include/dmlc /usr/include/c++/4.9.3 
root@aries:/home/aries/tvm/include# cp -r /home/aries/tvm/dlpack/include/dlpack /usr/include/c++/4.9.3 

But it still ...
In file included from /usr/include/c++/4.9/unordered_map:35:0,
                 from /usr/include/c++/4.9/tvm/runtime/module.h:15,
                 from /home/aries/tvm/apps/howto_deploy/cpp_deploy.cc:7:
/usr/include/c++/4.9/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /usr/include/c++/4.9/dmlc/io.h:14:0,
                 from /usr/include/c++/4.9/tvm/runtime/module.h:11,
                 from /home/aries/tvm/apps/howto_deploy/cpp_deploy.cc:7:
/usr/include/c++/4.9/dmlc/logging.h: In constructor ‘dmlc::LogCheckError::LogCheckError()’:
/usr/include/c++/4.9/dmlc/logging.h:67:25: error: ‘nullptr’ was not declared in this scope
   LogCheckError() : str(nullptr) {}
                         ^
/usr/include/c++/4.9/dmlc/logging.h: In destructor ‘dmlc::LogCheckError::~LogCheckError()’:
/usr/include/c++/4.9/dmlc/logging.h:69:33: error: ‘nullptr’ was not declared in this scope
   ~LogCheckError() { if (str != nullptr) delete str; }
                                 ^
/usr/include/c++/4.9/dmlc/logging.h: In member function ‘dmlc::LogCheckError::operator bool()’:
/usr/include/c++/4.9/dmlc/logging.h:70:34: error: ‘nullptr’ was not declared in this scope
   operator bool() {return str != nullptr; }
                                  ^
In file included from /usr/include/c++/4.9/dmlc/io.h:14:0,
                 from /usr/include/c++/4.9/tvm/runtime/module.h:11,
                 from /home/aries/tvm/apps/howto_deploy/cpp_deploy.cc:7:
/usr/include/c++/4.9/dmlc/logging.h: In destructor ‘dmlc::LogMessageFatal::~LogMessageFatal()’:
/usr/include/c++/4.9/dmlc/logging.h:297:17: error: ‘nullptr’ was not declared in this scope
     if (msgs != nullptr) {
                 ^
In file included from /home/aries/tvm/apps/howto_deploy/cpp_deploy.cc:7:0:
/usr/include/c++/4.9/tvm/runtime/module.h: At global scope:
/usr/include/c++/4.9/tvm/runtime/module.h:32:34: error: expected ‘)’ before ‘<’ token
   explicit Module(std::shared_ptr<ModuleNode> n)
                                  ^
/usr/include/c++/4.9/tvm/runtime/module.h:66:8: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
   std::shared_ptr<ModuleNode> node_;
        ^
/usr/include/c++/4.9/tvm/runtime/module.h:98:18: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
       const std::shared_ptr<ModuleNode>& sptr_to_self) = 0;
                  ^
/usr/include/c++/4.9/tvm/runtime/module.h:98:28: error: expected ‘,’ or ‘...’ before ‘<’ token
       const std::shared_ptr<ModuleNode>& sptr_to_self) = 0;
                            ^
/usr/include/c++/4.9/tvm/runtime/module.h:140:8: error: ‘unordered_map’ in namespace ‘std’ does not name a template type
   std::unordered_map<std::string,
        ^
/usr/include/c++/4.9/tvm/runtime/module.h:147:1: error: ‘constexpr’ does not name a type
 constexpr const char* tvm_module_ctx = "__tvm_module_ctx";
 ^
/usr/include/c++/4.9/tvm/runtime/module.h:147:1: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
/usr/include/c++/4.9/tvm/runtime/module.h:149:1: error: ‘constexpr’ does not name a type
 constexpr const char* tvm_dev_mblob = "__tvm_dev_mblob";
 ^
/usr/include/c++/4.9/tvm/runtime/module.h:149:1: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
/usr/include/c++/4.9/tvm/runtime/module.h:151:1: error: ‘constexpr’ does not name a type
 constexpr const char* tvm_dev_mblob_nbytes = "__tvm_dev_mblob_nbytes";
 ^
/usr/include/c++/4.9/tvm/runtime/module.h:151:1: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
/usr/include/c++/4.9/tvm/runtime/module.h:153:1: error: ‘constexpr’ does not name a type
 constexpr const char* tvm_set_device = "__tvm_set_device";
 ^
/usr/include/c++/4.9/tvm/runtime/module.h:153:1: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
/usr/include/c++/4.9/tvm/runtime/module.h:155:1: error: ‘constexpr’ does not name a type
 constexpr const char* tvm_global_barrier_state = "__tvm_global_barrier_state";
 ^
/usr/include/c++/4.9/tvm/runtime/module.h:155:1: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
/usr/include/c++/4.9/tvm/runtime/module.h:157:1: error: ‘constexpr’ does not name a type
 constexpr const char* tvm_prepare_global_barrier = "__tvm_prepare_global_barrier";
 ^
/usr/include/c++/4.9/tvm/runtime/module.h:157:1: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
/usr/include/c++/4.9/tvm/runtime/module.h:159:1: error: ‘constexpr’ does not name a type
 constexpr const char* tvm_module_main = "__tvm_main__";
 ^
/usr/include/c++/4.9/tvm/runtime/module.h:159:1: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
/usr/include/c++/4.9/tvm/runtime/module.h: In member function ‘tvm::runtime::ModuleNode* tvm::runtime::Module::operator->()’:
/usr/include/c++/4.9/tvm/runtime/module.h:164:10: error: ‘node_’ was not declared in this scope
   return node_.get();
          ^
/usr/include/c++/4.9/tvm/runtime/module.h: In member function ‘const tvm::runtime::ModuleNode* tvm::runtime::Module::operator->() const’:
/usr/include/c++/4.9/tvm/runtime/module.h:168:10: error: ‘node_’ was not declared in this scope
   return node_.get();
          ^
In file included from /usr/include/c++/4.9/tvm/runtime/module.h:174:0,
                 from /home/aries/tvm/apps/howto_deploy/cpp_deploy.cc:7:
/usr/include/c++/4.9/tvm/runtime/packed_func.h: At global scope:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:69:9: error: expected nested-name-specifier before ‘FType’
   using FType = std::function<void (TVMArgs args, TVMRetValue* rv)>;
         ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:76:29: error: expected ‘)’ before ‘body’
   explicit PackedFunc(FType body) : body_(body) {}
                             ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:92:37: error: expected ‘,’ or ‘...’ before ‘&&’ token
   inline TVMRetValue operator()(Args&& ...args) const;
                                     ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:92:49: error: parameter packs not expanded with ‘...’:
   inline TVMRetValue operator()(Args&& ...args) const;
                                                 ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:92:49: note:         ‘Args’
/usr/include/c++/4.9/tvm/runtime/packed_func.h:100:10: error: ‘FType’ does not name a type
   inline FType body() const;
          ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:102:24: error: ‘std::nullptr_t’ has not been declared
   bool operator==(std::nullptr_t null) const {
                        ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:106:24: error: ‘std::nullptr_t’ has not been declared
   bool operator!=(std::nullptr_t null) const {
                        ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:112:3: error: ‘FType’ does not name a type
   FType body_;
   ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h: In member function ‘bool tvm::runtime::PackedFunc::operator==(int) const’:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:103:12: error: ‘body_’ was not declared in this scope
     return body_ == nullptr;
            ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:103:21: error: ‘nullptr’ was not declared in this scope
     return body_ == nullptr;
                     ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h: In member function ‘bool tvm::runtime::PackedFunc::operator!=(int) const’:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:107:12: error: ‘body_’ was not declared in this scope
     return body_ != nullptr;
            ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:107:21: error: ‘nullptr’ was not declared in this scope
     return body_ != nullptr;
                     ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h: In member function ‘tvm::runtime::TVMPODValue_::operator void*() const’:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:242:37: error: ‘nullptr’ was not declared in this scope
     if (type_code_ == kNull) return nullptr;
                                     ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h: In member function ‘tvm::runtime::TVMPODValue_::operator TVMArray*() const’:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:248:37: error: ‘nullptr’ was not declared in this scope
     if (type_code_ == kNull) return nullptr;
                                     ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h: At global scope:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:347:37: error: ‘enable_if’ in namespace ‘std’ does not name a template type
            typename = typename std::enable_if<
                                     ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:347:46: error: expected ‘>’ before ‘<’ token
            typename = typename std::enable_if<
                                              ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:349:23: error: default template arguments may not be used in function templates without -std=c++11 or -std=gnu++11
   inline operator T() const;
                       ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:351:37: error: ‘enable_if’ in namespace ‘std’ does not name a template type
            typename = typename std::enable_if<
                                     ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:351:46: error: expected ‘>’ before ‘<’ token
            typename = typename std::enable_if<
                                              ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:353:28: error: default template arguments may not be used in function templates without -std=c++11 or -std=gnu++11
   inline bool IsNodeType() const;
                            ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:357:15: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
   inline std::shared_ptr<Node>& node_sptr();
               ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:376:26: error: expected ‘,’ or ‘...’ before ‘&&’ token
   TVMRetValue(TVMRetValue&& other)
                          ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:376:34: error: invalid constructor; you probably meant ‘tvm::runtime::TVMRetValue (const tvm::runtime::TVMRetValue&)’
   TVMRetValue(TVMRetValue&& other)
                                  ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:425:37: error: expected ‘,’ or ‘...’ before ‘&&’ token
   TVMRetValue& operator=(TVMRetValue&& other) {
                                     ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:437:31: error: declaration of ‘operator=’ as non-function
   TVMRetValue& operator=(std::nullptr_t value) {
                               ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:437:24: error: expected ‘;’ at end of member declaration
   TVMRetValue& operator=(std::nullptr_t value) {
                        ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:437:41: error: expected ‘)’ before ‘value’
   TVMRetValue& operator=(std::nullptr_t value) {
                                         ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:492:37: error: ‘enable_if’ in namespace ‘std’ does not name a template type
            typename = typename std::enable_if<
                                     ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:492:46: error: expected ‘>’ before ‘<’ token
            typename = typename std::enable_if<
                                              ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:494:40: error: default template arguments may not be used in function templates without -std=c++11 or -std=gnu++11
   TVMRetValue& operator=(const T& other) {
                                        ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:526:37: error: ‘enable_if’ in namespace ‘std’ does not name a template type
            typename = typename std::enable_if<
                                     ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:526:46: error: expected ‘>’ before ‘<’ token
            typename = typename std::enable_if<
                                              ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:528:23: error: default template arguments may not be used in function templates without -std=c++11 or -std=gnu++11
   inline operator T() const;
                       ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:532:44: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
   inline TVMRetValue& operator=(const std::shared_ptr<Node>& other);
                                            ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:532:54: error: expected ‘,’ or ‘...’ before ‘<’ token
   inline TVMRetValue& operator=(const std::shared_ptr<Node>& other);
                                                      ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:532:23: error: ‘tvm::runtime::TVMRetValue& tvm::runtime::TVMRetValue::operator=(int)’ cannot be overloaded
   inline TVMRetValue& operator=(const std::shared_ptr<Node>& other);
                       ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:452:16: error: with ‘tvm::runtime::TVMRetValue& tvm::runtime::TVMRetValue::operator=(int)’
   TVMRetValue& operator=(int value) {
                ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h: In member function ‘tvm::runtime::TVMRetValue& tvm::runtime::TVMRetValue::operator=(tvm::runtime::TVMRetValue)’:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:427:14: error: ‘other’ was not declared in this scope
     value_ = other.value_;
              ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h: In member function ‘void tvm::runtime::TVMRetValue::Assign(const T&)’:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:558:23: error: ‘shared_ptr’ is not a member of ‘std’
         SwitchToClass<std::shared_ptr<Node> >(
                       ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:558:23: error: ‘shared_ptr’ is not a member of ‘std’
/usr/include/c++/4.9/tvm/runtime/packed_func.h:558:9: error: parse error in template argument list
         SwitchToClass<std::shared_ptr<Node> >(
         ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:559:46: error: ‘shared_ptr’ is not a member of ‘std’
             kNodeHandle, *other.template ptr<std::shared_ptr<Node> >());
                                              ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:559:46: error: ‘shared_ptr’ is not a member of ‘std’
/usr/include/c++/4.9/tvm/runtime/packed_func.h:559:42: error: parse error in template argument list
             kNodeHandle, *other.template ptr<std::shared_ptr<Node> >());
                                          ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:559:70: error: expected primary-expression before ‘)’ token
             kNodeHandle, *other.template ptr<std::shared_ptr<Node> >());
                                                                      ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h: In member function ‘void tvm::runtime::TVMRetValue::Clear()’:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:600:36: error: ‘shared_ptr’ is not a member of ‘std’
       case kNodeHandle: delete ptr<std::shared_ptr<Node> >(); break;
                                    ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:600:36: error: ‘shared_ptr’ is not a member of ‘std’
/usr/include/c++/4.9/tvm/runtime/packed_func.h:600:32: error: parse error in template argument list
       case kNodeHandle: delete ptr<std::shared_ptr<Node> >(); break;
                                ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:600:32: error: type ‘<unresolved overloaded function type>’ argument given to ‘delete’, expected pointer
/usr/include/c++/4.9/tvm/runtime/packed_func.h:600:60: error: expected primary-expression before ‘)’ token
       case kNodeHandle: delete ptr<std::shared_ptr<Node> >(); break;
                                                            ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h: In member function ‘void tvm::runtime::PackedFunc::CallPacked(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const’:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:684:17: error: ‘body_’ was not declared in this scope
   body_(args, rv);
                 ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h: At global scope:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:687:20: error: ‘FType’ in ‘class tvm::runtime::PackedFunc’ does not name a type
 inline PackedFunc::FType PackedFunc::body() const {
                    ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:697:32: error: expected ‘,’ or ‘...’ before ‘&&’ token
   static void run(const F& f, T&& value, Args&&... args) {  // NOLINT(*)
                                ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h: In static member function ‘static void tvm::runtime::detail::for_each_dispatcher<stop, I, F>::run(const F&, T)’:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:698:10: error: ‘forward’ is not a member of ‘std’
     f(I, std::forward<T>(value));
          ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:698:24: error: expected primary-expression before ‘>’ token
     f(I, std::forward<T>(value));
                        ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:698:26: error: ‘value’ was not declared in this scope
     f(I, std::forward<T>(value));
                          ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:700:18: error: ‘forward’ is not a member of ‘std’
         ::run(f, std::forward<Args>(args)...);
                  ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:700:35: error: expected primary-expression before ‘>’ token
         ::run(f, std::forward<Args>(args)...);
                                   ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:700:37: error: ‘args’ was not declared in this scope
         ::run(f, std::forward<Args>(args)...);
                                     ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h: At global scope:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:710:38: error: expected ‘,’ or ‘...’ before ‘&&’ token
 inline void for_each(const F& f, Args&&... args) {  // NOLINT(*)
                                      ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:710:48: error: parameter packs not expanded with ‘...’:
 inline void for_each(const F& f, Args&&... args) {  // NOLINT(*)
                                                ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:710:48: note:         ‘Args’
/usr/include/c++/4.9/tvm/runtime/packed_func.h: In function ‘void tvm::runtime::detail::for_each(const F&, <type error>)’:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:712:16: error: ‘forward’ is not a member of ‘std’
       ::run(f, std::forward<Args>(args)...);
                ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:712:33: error: expected primary-expression before ‘>’ token
       ::run(f, std::forward<Args>(args)...);
                                 ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:712:35: error: ‘args’ was not declared in this scope
       ::run(f, std::forward<Args>(args)...);
                                   ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h: At global scope:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:723:37: error: ‘enable_if’ in namespace ‘std’ does not name a template type
            typename = typename std::enable_if<
                                     ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:723:46: error: expected ‘>’ before ‘<’ token
            typename = typename std::enable_if<
                                              ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:725:38: error: default template arguments may not be used in function templates without -std=c++11 or -std=gnu++11
   void operator()(size_t i, T value) const {
                                      ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:739:34: error: ‘std::nullptr_t’ has not been declared
   void operator()(size_t i, std::nullptr_t value) const {
                                  ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:798:37: error: ‘enable_if’ in namespace ‘std’ does not name a template type
            typename = typename std::enable_if<
                                     ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:798:46: error: expected ‘>’ before ‘<’ token
            typename = typename std::enable_if<
                                              ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:800:52: error: default template arguments may not be used in function templates without -std=c++11 or -std=gnu++11
   inline void operator()(size_t i, const T& value) const;
                                                    ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h: In member function ‘void tvm::runtime::TVMArgsSetter::operator()(size_t, int) const’:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:740:25: error: invalid conversion from ‘int’ to ‘void*’ [-fpermissive]
     values_[i].v_handle = value;
                         ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h: At global scope:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:813:47: error: expected ‘,’ or ‘...’ before ‘&&’ token
 inline TVMRetValue PackedFunc::operator()(Args&& ...args) const {
                                               ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:813:20: error: prototype for ‘tvm::runtime::TVMRetValue tvm::runtime::PackedFunc::operator()(Args) const’ does not match any in class ‘tvm::runtime::PackedFunc’
 inline TVMRetValue PackedFunc::operator()(Args&& ...args) const {
                    ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:92:22: error: candidate is: template<class ... Args> tvm::runtime::TVMRetValue tvm::runtime::PackedFunc::operator()(<type error>) const
   inline TVMRetValue operator()(Args&& ...args) const;
                      ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h: In static member function ‘static tvm::runtime::ExtTypeVTable* tvm::runtime::ExtTypeVTable::Register_()’:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:879:88: error: there are no arguments to ‘static_assert’ that depend on a template parameter, so a declaration of ‘static_assert’ must be available [-fpermissive]
                 "require extension_class_info traits to be declared with non-zero code");
                                                                                        ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:879:88: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
In file included from /home/aries/tvm/apps/howto_deploy/cpp_deploy.cc:8:0:
/usr/include/c++/4.9/tvm/runtime/registry.h: At global scope:
/usr/include/c++/4.9/tvm/runtime/registry.h:47:13: error: expected ‘;’ at end of member declaration
   Registry& set_body(PackedFunc::FType f) {  // NOLINT(*)
             ^
/usr/include/c++/4.9/tvm/runtime/registry.h:47:34: error: ‘tvm::runtime::Registry& tvm::runtime::Registry::set_body’ conflicts with a previous declaration
   Registry& set_body(PackedFunc::FType f) {  // NOLINT(*)
                                  ^
/usr/include/c++/4.9/tvm/runtime/registry.h:42:21: note: previous declaration ‘tvm::runtime::Registry& tvm::runtime::Registry::set_body(tvm::runtime::PackedFunc)’
   TVM_DLL Registry& set_body(PackedFunc f);  // NOLINT(*)
                     ^
/usr/include/c++/4.9/tvm/runtime/registry.h:47:40: error: expected ‘)’ before ‘f’
   Registry& set_body(PackedFunc::FType f) {  // NOLINT(*)
                                        ^
In file included from /usr/include/c++/4.9/dmlc/io.h:14:0,
                 from /usr/include/c++/4.9/tvm/runtime/module.h:11,
                 from /home/aries/tvm/apps/howto_deploy/cpp_deploy.cc:7:
/home/aries/tvm/apps/howto_deploy/cpp_deploy.cc: In function ‘void Verify(tvm::runtime::Module, std::string)’:
/home/aries/tvm/apps/howto_deploy/cpp_deploy.cc:14:14: error: ‘nullptr’ was not declared in this scope
   CHECK(f != nullptr);
              ^
/home/aries/tvm/apps/howto_deploy/cpp_deploy.cc:46:9: error: no match for call to ‘(tvm::runtime::PackedFunc) (DLTensor*&, DLTensor*&)’
   f(x, y);
         ^
In file included from /usr/include/c++/4.9/tvm/runtime/module.h:174:0,
                 from /home/aries/tvm/apps/howto_deploy/cpp_deploy.cc:7:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:49:7: note: candidate is:
 class PackedFunc {
       ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:92:22: note: template<class ... Args> tvm::runtime::TVMRetValue tvm::runtime::PackedFunc::operator()(<type error>) const
   inline TVMRetValue operator()(Args&& ...args) const;
                      ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:92:22: note:   template argument deduction/substitution failed:
/home/aries/tvm/apps/howto_deploy/cpp_deploy.cc: In function ‘int main()’:
/home/aries/tvm/apps/howto_deploy/cpp_deploy.cc:63:92: error: no match for call to ‘(const tvm::runtime::PackedFunc) ()’
   tvm::runtime::Module mod_syslib = (*tvm::runtime::Registry::Get("module._GetSystemLib"))();
                                                                                            ^
In file included from /usr/include/c++/4.9/tvm/runtime/module.h:174:0,
                 from /home/aries/tvm/apps/howto_deploy/cpp_deploy.cc:7:
/usr/include/c++/4.9/tvm/runtime/packed_func.h:49:7: note: candidate is:
 class PackedFunc {
       ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:92:22: note: template<class ... Args> tvm::runtime::TVMRetValue tvm::runtime::PackedFunc::operator()(<type error>) const
   inline TVMRetValue operator()(Args&& ...args) const;
                      ^
/usr/include/c++/4.9/tvm/runtime/packed_func.h:92:22: note:   template argument deduction/substitution failed:
/home/aries/tvm/apps/howto_deploy/cpp_deploy.cc:63:92: note:   candidate expects 1 argument, 0 provided
   tvm::runtime::Module mod_syslib = (*tvm::runtime::Registry::Get("module._GetSystemLib"))();
                                                                                            ^

**Comment by tqchen** [comment]
checkout Makefile here for detailed usage. It appears that you did not turn on-std=c++11 https://github.com/dmlc/tvm/blob/master/apps/howto_deploy/Makefile

**Comment by tqchen** [comment]
please keep one problem for  each issue and close the original solved ones and move to new ones, so status can be easily tracked. I am going to close this one for now
