### ISSUE TITLE
Argument Positions of Generated Function

### ISSUE THREAD

**Issue by Arthur-Shi** [dmlc/tvm#603]
I have saved the module f3 in the tvm/topi/tests/python/test_topi_depthwise_conv2d.py 

        f3 = tvm.build(s3, [Input, Filter, Scale, Shift, Relu], device)

and get 4 files: .ptx, .o, .so and .json.

I am trying to run these files. But I have to define and assign the inputs in the /home/aries/tvm/apps/howto_deploy/cpp_deploy.cc

thats what I add:

  DLTensor* x;
  DLTensor* y;
  DLTensor* a;
  DLTensor* b;
  DLTensor* c;

  int dtype_code = kFloat;
  int dtype_bits = 32;
  int dtype_lanes = 1;
  int device_type = kCPU;
  int device_id = 0;
  TVMArrayAlloc(shape, 4, dtype_code, dtype_bits, dtype_lanes,
                device_type, device_id, &x);
  TVMArrayAlloc(shape, 4, dtype_code, dtype_bits, dtype_lanes,
                device_type, device_id, &y);
  TVMArrayAlloc(shape, 1, dtype_code, dtype_bits, dtype_lanes,
                device_type, device_id, &a);
  TVMArrayAlloc(shape, 1, dtype_code, dtype_bits, dtype_lanes,
                device_type, device_id, &b);
  TVMArrayAlloc(shape, ndim, dtype_code, dtype_bits, dtype_lanes,
                device_type, device_id, &c);

But How to assign multimensional array to Input, Filter, Scale, Shift ?

  native int tvmArrayAlloc(long[] shape, int dtypeCode, int dtypeBits, int dtypeLanes,
int deviceType, int deviceId, Base.RefLong refHandle); 
It cannot help.

And I tried 

    int i[]={{{{1}}}};
    static_cast<float*>(x->data)[i] = i;

But It also cannot work.

For example, If I want to assign  {{{{1}}}}  to a ,
what should I do?

and also , how to print relu? DLpack is not able to be printed in C++

**Comment by Arthur-Shi** [comment]
If I save the modules in .o, .so, .ptx, Can i run the .so files without tvm & llvm and DLpack defination .cpp files?

**Comment by tqchen** [comment]
You will need tvm runtime, but not LLVM or compilation stack

**Comment by tqchen** [comment]
checkout http://docs.tvmlang.org/how_to/deploy.html

**Comment by Arthur-Shi** [comment]
I saw the documents and tried run ./run_example.sh. And I edited the makefile and cpp to let me run the other built modules (for example f3) by C++. But How to assign arrayies to Input, Filter, Scale, Shift in cpp files?

**Comment by tqchen** [comment]
these arguments are passed as positional arguments in the same order you pased to tvm.build

**Comment by Arthur-Shi** [comment]
I think TVMArrayAlloc is like tvm.placeholder,

  TVMArrayAlloc(shape, ndim, dtype_code, dtype_bits, dtype_lanes,
                device_type, device_id, &x);

 But why I cannot device_type set kGPU??
int device_type = kGPU;
/testtvm/tvm/dmlc-core/include/dmlc/./logging.h:308: [09:51:36] ../../src/runtime/c_runtime_api.cc:83: Check failed: allow_missing Device API gpu is not enabled.

is it due to no cuda in tvm.build? 

And if I want to set X as a two dimensional array。
  int ndim = 2;
  for (int i = 0; i < shape[0]; ++i) {
   for (int j = 0; j < shape[0]; ++j) {
    static_cast<float*>(x->data)[i][j] = i;
    }
  }

cpp_deploy.cc: In function ‘void Verify(tvm::runtime::Module, std::string)’:
cpp_deploy.cc:46:38: error: invalid types ‘float[int]’ for array subscript
     static_cast<float*>(x->data)[i][j] = i;

What should I do？ @tqchen

**Comment by tqchen** [comment]
you need to build runtime with gpu enabled to use gpu. Since you are using c++, you can only work on the array as flattened and not two dimensional one

**Comment by Arthur-Shi** [comment]
When I build runtime with gpu, I should uncomment 
#include "../../src/runtime/metal/metal_device_api.mm"
#include "../../src/runtime/metal/metal_module.mm"

But, 

In file included from ../../src/runtime/metal/metal_device_api.mm:5:0,
                 from tvm_runtime_pack.cc:48:
../../src/runtime/metal/./metal_common.h:9:2: warning: #import is a deprecated GCC extension [-Wdeprecated]
 #import <Metal/MTLBuffer.h>
  ^
../../src/runtime/metal/./metal_common.h:9:28: fatal error: Metal/MTLBuffer.h: No such file or directory
 #import <Metal/MTLBuffer.h>
                            ^
compilation terminated.
Makefile:19: recipe for target 'lib/libtvm_runtime_pack.o' failed

Where can find this file?

**Comment by tqchen** [comment]
you only need to build with cuda but not the metal runtime

**Comment by Arthur-Shi** [comment]
Sorry， Now I added the cuda cc files in the tvm_runtime_pack.

#include "../../src/runtime/cuda/cuda_device_api.cc"
#include "../../src/runtime/cuda/cuda_module.cc"

But output the similar problem

In file included from tvm_runtime_pack.cc:42:0:
../../src/runtime/cuda/cuda_device_api.cc:13:26: fatal error: cuda_runtime.h: No such file or directory
 #include <cuda_runtime.h>
                          ^
compilation terminated.

Is my method wrong?

**Comment by tqchen** [comment]
You will need to add the cuda's include path to the compilation command

**Comment by Arthur-Shi** [comment]
my cuda's include path is /usr/local/cuda-8.0/include
Where should I add? makefile or cpp files?

PKG_CFLAGS = -std=c++11 -O2 -fPIC\
	-I${TVM_ROOT}/include\
	-I${DMLC_CORE}/include\
	-I${TVM_ROOT}/dlpack/include\
        -I$/usr/local/cuda-8.0/include

For makefile, it cannot work.

And I cannot find cuda_runtime.h in cuda folder and tvm folder！

**Comment by Arthur-Shi** [comment]
PKG_CFLAGS = -std=c++11 -O2 -fPIC\
	-I${TVM_ROOT}/include\
	-I${DMLC_CORE}/include\
	-I${TVM_ROOT}/dlpack/include\
        -I${TVM_ROOT}/../../../local/cuda-8.0/include\

It cannot work

where is the compilation command?

**Comment by tqchen** [comment]
As the error message indicate, it cannot find cuda_runtime.h Please make sure it is in your search path. Note usually you use absolute path like

```
/usr/local/cuda-8.0/include
```

**Comment by Arthur-Shi** [comment]
Still same problem:
In file included from tvm_runtime_pack.cc:42:0:
../../src/runtime/cuda/cuda_device_api.cc:13:26: fatal error: cuda_runtime.h: No such file or directory
 #include <cuda_runtime.h>
                          ^
What I did is : 
1. add cc in tvm_runtime_pack .cc
#include "../../src/runtime/cuda/cuda_device_api.cc"
#include "../../src/runtime/cuda/cuda_module.cc"

2.  add cuda path in Makefile
PKG_CFLAGS = -std=c++11 -O2 -fPIC\
	-I${TVM_ROOT}/include\
	-I${DMLC_CORE}/include\
	-I${TVM_ROOT}/dlpack/include\
        -I$/usr/local/cuda-8.0/include\

But It still cannot work.

**Comment by tqchen** [comment]
Check if cuda_runtime.h is in your include path

**Comment by tqchen** [comment]
Note that you need to add backslash for each line so the next line code is included in the makefile

**Comment by Arthur-Shi** [comment]
cuda_runtime.h is in /usr/local/cuda-8.0/include\.
Actually, I added backslash on each line, Just did not shown above.

**Comment by tqchen** [comment]
I have no idea what happens on your side, as the compiler reported not being able to find the cuda runtime.h file. I am afraid that you need to figure it out on your own. Possibly by print out the build command and build a single file that only contains cuda runtime.h

**Comment by Arthur-Shi** [comment]
OK, Thank you so much.

**Comment by tqchen** [comment]
I am going to close this as the original question is answered and there is no additional information can be obtained to resolve the second one(seems to be problem of build configuration with cuda rather than the code issue)

**Comment by Arthur-Shi** [comment]
Actually， as far as now, I have no idea to deal with these two problems above. I will open two new issues.
