### ISSUE TITLE
TVMError: [11:28:52] E:\Git_sources\TVM\tvm\src\runtime\c_runtime_api.cc:83: Check failed: allow_missing Device API gpu is not enabled.

### ISSUE THREAD

**Issue by BigJerry** [dmlc/tvm#604]
here is my codes:
`from __future__ import absolute_import , print_function

import tvm
import numpy as np

n = tvm.var("n")
A = tvm.placeholder((n,),name = 'A')
B = tvm.placeholder((n,),name = 'B')
C = tvm.compute(A.shape,lambda i: A[i] + B[i], name = 'C')

s = tvm.create_schedule(C.op)

bx, tx = s[C].split(C.op.axis[0], factor = 64)

s[C].bind(bx, tvm.thread_axis("blockIdx.x"))
s[C].bind(tx, tvm.thread_axis("threadIdx.x"))

fadd_cl = tvm.build(s, [A,B,C], "opencl",name = "myadd")

ctx = tvm.gpu(0)
n = 1024
a = tvm.nd.array(np.random.uniform(size=n).astype(A.dtype), ctx)
b = tvm.nd.array(np.random.uniform(size=n).astype(B.dtype), ctx)
c = tvm.nd.array(np.zeros(n, dtype=C.dtype), ctx)
fadd_cl(a,b,c)
np.testing.assert_allclose(c.asnumpy(), a.asnumpy() + b.asnumpy())`

**Comment by tqchen** [comment]
Please build with cuda support enabled

**Comment by BigJerry** [comment]
OK, I'll try

**Comment by myproject24** [comment]
Hi, @tqchen @BigJerry I am also getting the same error I am deploying tvm compiled model in c++ statically, i built tvm with enabling support to llvm, OpenCL, and Cuda. And i am able to deploy tvm model with llvm all optimization levels but Cuda and OpenCL models are throwing this error.
