### ISSUE TITLE
compile error(enable CUDA already)  :tvm.dll : fatal error LNK1120: 7 unresolved externals

### ISSUE THREAD

**Issue by BigJerry** [dmlc/tvm#605]
Here's key msg:
3>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\Win32\cuda.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
3>E:\Git_sources\TVM\tvm\build\Release\tvm_runtime.dll : fatal error LNK1120: 7 unresolved externals

**Comment by tqchen** [comment]
as the error indicated, seems you linked to 32 bit cuda library while your target code is x64

**Comment by BigJerry** [comment]
I solved this by reset my evironment variable "Path". It seems that the compilation need CUDA lib, and somthing search system "Path" first to find cuda.lib instead of getting the path directly from "CUDA_LIB_PATH". Thanks for your reply. Have a good day!
