### ISSUE TITLE
Question:  How to import .ptx file into the example (tvm/apps/howto_deploy) ?

### ISSUE THREAD

**Issue by Arthur-Shi** [dmlc/tvm#607]
After Using the command shown below, we can get the files ( .so, .o , .json, .ptx).

dylib_path3 = os.path.join (base_path, "test_depthcuda.o")
f3.save (dylib_path3)
dylib_path2 = os.path.join(base_path, "test_depthcuda.ptx")
dev_module.save(dylib_path2)
cc.create_shared("/home/aries/tvm/apps/test/lib/test_depthcuda.so", ["/home/aries/tvm/apps/test/lib/test_depthcuda.o"])

And .so file saves the tvm function code and .ptx file saves the device module code.

How to import .ptx file into the example (tvm/apps/howto_deploy) ?

And I still see the TVM C function in .cpp file, So I Think this method in this example is not run the .so file without TVM.

But How can we run the .so and .ptx files directly only with CUDA?

**Comment by tqchen** [comment]
Use export_library is the quickest way to get a packed version of library. which can get around this issue

**Comment by tqchen** [comment]
Otherwise, we need to load the device module(ptx) and link separately

**Comment by Arthur-Shi** [comment]
yeah, export_library enable to output .so file and _sys.o file. And I need save device module(ptx) separately.

And then I need link ,so and _sys.o by cc.create_shared ?

But how to load ptx file? I did not find the example for that?

And How to run them without tvm? I cannot use the example in tvm/apps/howto_deploy. Because this method still use the TVM C API in CPP file.

Could give me a simple example for that? Actually, My recent questions are around this topic.

Thank you so much for your patient answer.

**Comment by tqchen** [comment]
You are asking two questions, it is better to open new issues for new questions so they can be tracked.

But to answer your second question, you will need tvm runtime(note this is not entire tvm) to run compiled libraries of tvm. You can get it by typing make runtime or use the all in one deployment file.  If you want something that is stand alone. Tvm runtime is usually around 300 to 600k and minimum

**Comment by tqchen** [comment]
Export library will pack the device module into shared library so when you load, you get a module that contains device module already.

If you use create shared directly, however, you need to save and load device module separately. You can load device module using module.load with the ptx file(but you also need the json file in the same folder)
