### ISSUE TITLE
Installation guide for optional dependency library

### ISSUE THREAD

**Issue by edmBernard** [dmlc/tvm#608]
Is there a place in the Doc to add installation guide.
Currently the doc only give sparse information. 
For some dependency like nnpack, installation is not straight forward.
Something similar to this for mxnet : https://mxnet.incubator.apache.org/how_to/nnpack.html

**Comment by tqchen** [comment]
Yes, we can add this to https://github.com/dmlc/tvm/tree/master/docs/how_to and point to here.

**Comment by edmBernard** [comment]
thanks
