### ISSUE TITLE
[windows] no file named "llvm-config" under windows version of llvm

### ISSUE THREAD

**Issue by BigJerry** [dmlc/tvm#611]
as the title , so I can't build with llvm support , and my corresponding compilation option is -LLVM_CONFIG = "mypath/llvm-config"

**Comment by tqchen** [comment]
For windows, you need to build with cmake instead of makefile

**Comment by BigJerry** [comment]
yes, so I use option -DUSE_LLVM=1 under command line (just similar to your tutorial about cmake usage). however, pre-built binary version of llvm doesn't have the file llvm-config under folder /bin... I'm wondering if I have to build llvm from sources so I can get the file llvm-config for configuration of tvm (compile with llvm).

**Comment by tqchen** [comment]
It seems in windows you will need to build from source

**Comment by tqchen** [comment]
I mean build llvm from source

**Comment by BigJerry** [comment]
ye,I'm trying so , however ,It's another story. I want to know if anything would be done for using llvm's pre-built binary version directly, since build llvm from source is a time-consuming task...

**Comment by tqchen** [comment]
I agree that being able to use prebuild is nice and would love to know if such solution is exists. since this is an issue more of llvm build how to, I am going to close this for now.

I would love to find a solution and add it to doc if such solution exists

**Comment by nouiz** [comment]
Does anaconda provide llvm on Windows? I would think so.
