### ISSUE TITLE
What is the Relationship Between tvm, nnvm and nnvm compiler?

### ISSUE THREAD

**Issue by shuokay** [dmlc/tvm#612]

**Comment by tqchen** [comment]
Nnvm compiler is a compiler product based on nnvm and tvm

**Comment by shuokay** [comment]
After reading 12's Halide paper, I think tvm is somehow like "Tensor" aimed Halide. Halide compile its code using Halide compiler, does tvm have its own compiler or tvm use nnvm compiler to compile code? Does nnvm compiler have any other role in the tvm system?

**Comment by tqchen** [comment]
TVM itself is a compiler. nnvm compiler have two level stack, graph level ir with nnvm and tensor level optimizer with tvm, see http://www.tvmlang.org/2017/08/17/tvm-release-announcement.html
