### ISSUE TITLE
[FRONTEND] Clojure Integration

### ISSUE THREAD

**Issue by cnuernber** [dmlc/tvm#614]
Hey, I feel this is a better discussion for a google group or something like that but I would like to start a longer term discussion around a deep integration with Clojure in order to provide a nice environment for doing high performance numeric computing in general (with nn support).

I would expect this integration to start at the tvm level similar to python and move up into the nnvm level; but I would be first interested in replacing all math operation implementations in cortex (https://github.com/thinktopic/cortex) with implementations in tvm.  

I have been reading through the code quite a bit and have a couple questions around implementing some of the features in the base cortex math implementation.

Here is a short document about the cortex math backend:

https://github.com/thinktopic/cortex/blob/master/docs/tensor.md

The NDArray implementation in tvm supports some stride and dimension size.  This is perfect and appears to allow for things like in-place transpose and such.  I am less sure how someone would implement a feature like the generic broadcasting support that we have in cortex which, for the generic unary, binary, and ternary operations means considering all tensors included in the operation and indexing into the dimensions with knowledge of the max size of that dimension involved in the operation.

Here is the current code for finding the offset of a given element given a global element-index (which is the same is (i*max_dim_i + j*max_dim_j + k*max_dim_k):

https://github.com/thinktopic/cortex/blob/master/resources/index_system.h#L25

So specifically, how would someone add the cortex style broadcasting solution in a generic way to the three classes of elementwise operations (and potentially more)?  I have read through the prefetch and the flatten code and it appears that it would require systematic changes throughout the codebase (which is fine but I wanted to ensure my understanding was correct).

It would also be possible that broadcasting could be supported in some slower generic way and then faster kernels generated without this support where possible.  I am just not sure where it would fit. 

A similar question arises to using an index tensor for a given dimension instead of assuming the dimension is indexed monotonically increasing (which cortex doesn't support in a generic way at the moment).  Is it possible to, in some generic way, implement the indexing code such that all generic assignment, unary, binary, and ternary operations support at most one index buffer for all arguments leaving the specializing involving multiple index buffers or index buffers in the fastest-changing-dimension as an optimization? 

Another question I have is about mixing datatypes in one operation.  So currently cortex supports marshaling copies so we can convert from one datatype to another but only on assignment.  This of course allows for broadcasting so that is another factor and I would expect it would fall into the above category.

My initial feeling is that all of this is possible given just a generic binding to the system *and* some in depth understanding of the binding of the tvm system to the halide IR but I thought that, in addition to reading a lot of code asking questions here may be a good pathway.

The potential to build a generic HPC platform that has multiple backend support out of the box and allows custom kernel programming (which includes a lot of the hard work around kernel combining and such that this project has already achieved) combined with a high level generic language like clojure that can be used as a systems language due to the strengths of the jvm seems to me like something incredible.  This would benefit this project in that there would be another set of documentation, examples, and test code coming from a different perspective and I think this could address one of the major shortcomings of the JVM ecosystem.

**Comment by tqchen** [comment]
You can take a look at topi, which contains generic numpy like broadcasting https://github.com/dmlc/tvm/tree/master/topi

Most of TVM's kernel target compact data space for more optimizations, but also allows target strided data structure for efficiency. There is an initial jvm binding https://github.com/dmlc/tvm/tree/master/jvm of runtime which everything can be build on top on by @javelinjs

**Comment by cnuernber** [comment]
I now have time to start working on the clojure exploration of this library.

I would like to begin by building out the jvm add_cpu test but completely from clojure; meaning doing the dynamic compilation step from clojure in the first place.

I have the library loading and from the python code, the first step is to create a var object.  Scanning through the python, this calls _api_internal._Var, which appears to be a function that is exported via the global function names list.

When I call Function/listGlobalFuncNames, however, I do not see *any* of the functions that should appear in the _api_internal module.  

Here is the list that I got from the list-global-func-names call:

```["tvm.graph_runtime.remote_create"
 "contrib.rpc._CreateEventDrivenServer"
 "contrib.rpc._LoadRemoteModule"
 "contrib.rpc._ModuleHandle"
 "module._RPCTimeEvaluator"
 "tvm.contrib.rpc.server.download"
 "contrib.rpc._ImportRemoteModule"
 "tvm.contrib.rpc.server.upload"
 "module.loadbinary_opencl"
 "module.loadfile_cl"
 "device_api.opencl"
 "module.loadbinary_cuda"
 "_GetDeviceAttr"
 "contrib.rpc._SessTableIndex"
 "module.loadfile_clbin"
 "__tvm_set_device"
 "module.loadfile_ptx"
 "module.loadfile_so"
 "module._GetSource"
 "module._ImportsSize"
 "module._GetSystemLib"
 "module._GetImport"
 "module._Enabled"
 "module._GetTypeKey"
 "module._LoadFromFile"
 "contrib.rpc._ServerLoop"
 "module._SaveToFile"
 "tvm.contrib.cublas.matmul"
 "module.loadfile_cubin"
 "tvm.contrib.cblas.matmul"
 "device_api.rpc"
 "device_api.cpu"
 "tvm.graph_runtime.create"
 "contrib.rpc._Connect"
 "device_api.gpu"]
```
In fact, this list seems quite small for the global names; like there is an initialization step I missed.

**Comment by tqchen** [comment]
these are APIs for the runtime stack, which get registered by default, if we want to add compiler stack, we need to link libtvm.so instead of libtvm_runtime.so

**Comment by cnuernber** [comment]
As a test I changed the JNI bindings to link to the libtvm.so like you noted and was presented with a large list of functions as a result (elided, the one I was looking for was in there).  I don't know what you want to make of this but I am guessing that there are reasons the runtime was linked specifically as opposed to the compiler infrastructure.

https://github.com/tech-ascent/tvm/tree/link-compiler-into-jar

I went through the binding pathway used and am now curious why a bespoke pathway was chosen (.cc file and hand-written java files) as opposed to more automated pathways, the best of which I have found is javacpp.

I have had a lot of success (and frustrations) with javacpp in the past will attempt some javacpp bindings for this project; it appears like the c-bindings (c_runtime_api.h, c_dsl_api.h, c_backend_api.h) are sufficient to get the full functionality of the system assuming the correct shared library is linked.  The advantage of the javacpp system really is in interop between c and java; it's pointer system works well and I already have fast paths for converting i.e java float arrays into c double pointers and things like that.

**Comment by tqchen** [comment]
By default the java binding was used to minimally deploy the workload with minimum runtime dependency, that is why a runtime API is chosen.

The current binding is designed in a way so that it can be exposed to any front end language, like python or java. If we only want to expose one type of binding, maybe we would have done it differently.

The current binding system do offers nice properties, such as data structure and callback interop. The most important thing is that it has a minimum C ABI to depend on, which makes it easier to port across compilers. The compiler API itself can be build solely on top of this runtime system without having to write any FFI functions. We have done this in python and it works great. I would highly recommend to build java binding on top of current runtime system.

**Comment by cnuernber** [comment]
Let's differentiate between building new c-functions or some c++ wrapper into the TVM system and the specific means of binding java to the *existing* exported c layer.

I completely agree that there is no need for new c-functions or any more c++ or anything like that; the C ABI is very well designed and I cannot tell you how much I appreciate that.

It is simply the means of binding to the existing C ABI that I think could be improved; the javacpp method of binding to C ABI's gives the user with a lot more flexibility and power.  

So I am not suggesting that I add any more c or c++ code; I think that your team did a fantastic job there and it obviously works from python as it is.  What I am suggesting is that using a slightly different system of exposing the C ABI to the java ecosystem leaves consumers of the library with a far more flexible system with no additional work from your team or the binding mechanism.

So, we agree on the most important thing; I see your point and I am aligned there.  I aim to show, however, that the specific means of binding to the underlying system leads to a less flexible and ultimately less powerful JVM library than if the lowest level exposure of the C-functions to java is through javacpp and then any required supporting layers are added above those.

**Comment by tqchen** [comment]
OK, I see. I think we are open to these changes. One reason we built things on top of JNI, is to make the dependency and final jar minimum when deployed on say android devices. The initial project was written in scala and moved to java for the same reason.

My understanding is that as long as there is a java runtime for the core API(which can be either implemented via javacpp or JNI), and everything can be built on top of them. But if there are examples of code-path that might be easier via javacpp, we are open to that option.

cc @yzhliu who is the main author of jvm package

**Comment by cnuernber** [comment]
Here is the output of auto-generating the tvm bindings for the runtime API alone:

https://gist.github.com/cnuernber/e5117d79d7290a34ed1fb78bb2294674

And here is the clojure project that will compile them assuming you follow the readme directions:

https://github.com/tech-ascent/tvm-clj

**Comment by cnuernber** [comment]
Do you mind if I close this issue?  I am having some success with the javacpp bindings I was able to generate and I think that perhaps I would just like some time to proof out this pathway.
