### ISSUE TITLE
How to assign the input in C++？

### ISSUE THREAD

**Issue by Arthur-Shi** [dmlc/tvm#617]
For the simple example in  tvm/apps/howto_deploy， I tried to run an example with the input (Multidimensional array). 

I changed the module in the howto_deploytest/prepare_test_libs.py.

    A = tvm.placeholder((2,2), name='A')
    B = tvm.compute(A.shape, lambda *i: A(*i) + 1.0, name='B')

And then I changed the cpp_deploy.cc, to input x = {2,2,2,2}

    int ndim = 2;
    int64_t shape[2] = {2, 2};
    for (int i = 0; i < shape[0]; ++i) {
    for (int j = 0; j < shape[1]; ++j) {
    static_cast<float*>(x->data)[i*shape[1]+j] = 2;
    }
    }

and

    for (int i = 0; i < shape[0]; ++i) {
    for (int j = 0; j < shape[1]; ++j) {
    CHECK_EQ(static_cast<float*>(y->data)[i*shape[1]+j], 2 + 1.0f);
    }
    }

But output: 
[17:48:28] cpp_deploy.cc:73: Verify dynamic loading from test_addone_dll.so
[17:48:28] /home/aries/tvmnew/tvm/dmlc-core/include/dmlc/./logging.h:308: [17:48:28] ../../src/runtime/module_util.cc:46: Check failed: ret == 0 (-1 vs. 0) Assert fail: (1 == tvm_struct_get(arg0, 0, 4)), arg0.ndim is expected to equal 1

What should I do?

**Comment by WolffyChen** [comment]
I can not reproduce your problem. I change the code above as you said and run successfully. Have you update the project to the latest version and use (kDLFloat, kDLCPU) to replace (kFloat, kCPU)?

**Comment by Arthur-Shi** [comment]
DLTensor* x;
  DLTensor* y;

  int dtype_code = kDLFloat;
  int dtype_bits = 32;
  int dtype_lanes = 1;
  int device_type = kDLCPU;
  int device_id = 0;

   int ndim = 2;
   int64_t shape[2] = {2, 2};
  TVMArrayAlloc(shape, ndim, dtype_code, dtype_bits, dtype_lanes,
                device_type, device_id, &x);
  TVMArrayAlloc(shape, ndim, dtype_code, dtype_bits, dtype_lanes,
                device_type, device_id, &y);


    for (int i = 0; i < shape[0]; ++i) {
    for (int j = 0; j < shape[1]; ++j) {
    static_cast<float*>(x->data)[i*shape[1]+j] = 2;
    }
    }

  // Invoke the function
  // PackedFunc is a function that can be invoked via positional argument.
  // The signature of the function is specified in tvm.build
  f(x, y);
  // Print out the output

    for (int i = 0; i < shape[0]; ++i) {
    for (int j = 0; j < shape[1]; ++j) {
    CHECK_EQ(static_cast<float*>(y->data)[i*shape[1]+j], 2 + 1.0f);
    }
    }
  LOG(INFO) << "Finish verification...";

YES， I did！ But I cannot work。

**Comment by Arthur-Shi** [comment]
@WolffyChen Did you change something in other files? in python file?

**Comment by Arthur-Shi** [comment]
OUTPUT:
Run the example
Run the deployment with all in one packed library...
[13:40:44] cpp_deploy.cc:73: Verify dynamic loading from test_addone_dll.so
[13:40:44] /home/aries/tvmnew/tvm/dmlc-core/include/dmlc/./logging.h:308: [13:40:44] ../../src/runtime/module_util.cc:46: Check failed: ret == 0 (-1 vs. 0) Assert fail: (1 == tvm_struct_get(arg0, 0, 4)), arg0.ndim is expected to equal 1

**Comment by WolffyChen** [comment]
I change the code in python just as you said. `A = tvm.placeholder((2,2), name='A')`
I copy your code and run it successfully. So I think you can create a new project to try it again.

**Comment by Arthur-Shi** [comment]
It works. My bad, I forgot to change it. Thank you for your patient answer.
