### ISSUE TITLE
Failed to run the example in tvm/apps/howto_deploy/ in GPU mode

### ISSUE THREAD

**Issue by Arthur-Shi** [dmlc/tvm#618]
I added the include path in tvm_runtime_pack.cc 

#include "../../src/runtime/cuda/cuda_device_api.cc"
#include "../../src/runtime/cuda/cuda_module.cc"

and I add the cuda path in Makefile

PKG_CFLAGS = -std=c++11 -O2 -fPIC\
	-I${TVM_ROOT}/include\
	-I${DMLC_CORE}/include\
	-I${TVM_ROOT}/dlpack/include\
        -I$/usr/local/cuda/include\

But the output:
../../src/runtime/cuda/cuda_device_api.cc:13:26: fatal error: cuda_runtime.h: No such file or directory
 #include <cuda_runtime.h>
                          ^

But
And I make sure cuda_runtime.h in /usr/local/cuda/include\. And I can run other test files and /home/aries/tvmnew/tvm/topi/recipe/conv/depthwise_conv2d_test.py successfully.

What should I do?

**Comment by WolffyChen** [comment]
`-I$/usr/local/cuda/include` should be `-I/usr/local/cuda/include`.

**Comment by Arthur-Shi** [comment]
Thank you so much!!! @WolffyChen

**Comment by Arthur-Shi** [comment]
@WolffyChen Do you know how to assign the input? #617 
I saw you write a simple example for C++ in NNVM, Could you help me find a way to assign the inputs in TVM? 
I am trying to load the input and other parameters in TVM, But I dont know how to load them in DLTensor and your example use the NVMM API.

**Comment by Arthur-Shi** [comment]
It still cannot work.  

Build the libraries..
g++ -std=c++11 -O2 -fPIC -I/home/aries/tvmnew/tvm/include -I/home/aries/tvmnew/tvm/dmlc-core/include -I/home/aries/tvmnew/tvm/dlpack/include -I/usr/local/cuda/include  -o lib/cpp_deploy_pack  cpp_deploy.cc lib/test_addone_sys.o lib/libtvm_runtime_pack.o -L/home/aries/tvmnew/tvm/lib -ldl -lpthread
lib/libtvm_runtime_pack.o: In function `tvm::runtime::CUDADeviceAPI::StreamSync(DLContext, void*)':
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI10StreamSyncE9DLContextPv[_ZN3tvm7runtime13CUDADeviceAPI10StreamSyncE9DLContextPv]+0x2b): undefined reference to `cudaSetDevice'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI10StreamSyncE9DLContextPv[_ZN3tvm7runtime13CUDADeviceAPI10StreamSyncE9DLContextPv]+0x40): undefined reference to `cudaGetErrorString'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI10StreamSyncE9DLContextPv[_ZN3tvm7runtime13CUDADeviceAPI10StreamSyncE9DLContextPv]+0xb4): undefined reference to `cudaStreamSynchronize'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI10StreamSyncE9DLContextPv[_ZN3tvm7runtime13CUDADeviceAPI10StreamSyncE9DLContextPv]+0xc9): undefined reference to `cudaGetErrorString'
lib/libtvm_runtime_pack.o: In function `tvm::runtime::CUDADeviceAPI::FreeDataSpace(DLContext, void*)':
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI13FreeDataSpaceE9DLContextPv[_ZN3tvm7runtime13CUDADeviceAPI13FreeDataSpaceE9DLContextPv]+0x2b): undefined reference to `cudaSetDevice'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI13FreeDataSpaceE9DLContextPv[_ZN3tvm7runtime13CUDADeviceAPI13FreeDataSpaceE9DLContextPv]+0x40): undefined reference to `cudaGetErrorString'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI13FreeDataSpaceE9DLContextPv[_ZN3tvm7runtime13CUDADeviceAPI13FreeDataSpaceE9DLContextPv]+0xb4): undefined reference to `cudaFree'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI13FreeDataSpaceE9DLContextPv[_ZN3tvm7runtime13CUDADeviceAPI13FreeDataSpaceE9DLContextPv]+0xc9): undefined reference to `cudaGetErrorString'
lib/libtvm_runtime_pack.o: In function `tvm::runtime::CUDADeviceAPI::SetDevice(DLContext)':
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI9SetDeviceE9DLContext[_ZN3tvm7runtime13CUDADeviceAPI9SetDeviceE9DLContext]+0x26): undefined reference to `cudaSetDevice'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI9SetDeviceE9DLContext[_ZN3tvm7runtime13CUDADeviceAPI9SetDeviceE9DLContext]+0x43): undefined reference to `cudaGetErrorString'
lib/libtvm_runtime_pack.o: In function `tvm::runtime::CUDADeviceAPI::GPUCopy(void const*, void*, unsigned long, cudaMemcpyKind, CUstream_st*)':
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI7GPUCopyEPKvPvm14cudaMemcpyKindP11CUstream_st[_ZN3tvm7runtime13CUDADeviceAPI7GPUCopyEPKvPvm14cudaMemcpyKindP11CUstream_st]+0x31): undefined reference to `cudaMemcpyAsync'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI7GPUCopyEPKvPvm14cudaMemcpyKindP11CUstream_st[_ZN3tvm7runtime13CUDADeviceAPI7GPUCopyEPKvPvm14cudaMemcpyKindP11CUstream_st]+0x46): undefined reference to `cudaGetErrorString'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI7GPUCopyEPKvPvm14cudaMemcpyKindP11CUstream_st[_ZN3tvm7runtime13CUDADeviceAPI7GPUCopyEPKvPvm14cudaMemcpyKindP11CUstream_st]+0xe1): undefined reference to `cudaMemcpy'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI7GPUCopyEPKvPvm14cudaMemcpyKindP11CUstream_st[_ZN3tvm7runtime13CUDADeviceAPI7GPUCopyEPKvPvm14cudaMemcpyKindP11CUstream_st]+0xf6): undefined reference to `cudaGetErrorString'
lib/libtvm_runtime_pack.o: In function `tvm::runtime::CUDADeviceAPI::CopyDataFromTo(void const*, unsigned long, void*, unsigned long, unsigned long, DLContext, DLContext, void*)':
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI14CopyDataFromToEPKvmPvmm9DLContextS5_S4_[_ZN3tvm7runtime13CUDADeviceAPI14CopyDataFromToEPKvmPvmm9DLContextS5_S4_]+0xe2): undefined reference to `cudaSetDevice'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI14CopyDataFromToEPKvmPvmm9DLContextS5_S4_[_ZN3tvm7runtime13CUDADeviceAPI14CopyDataFromToEPKvmPvmm9DLContextS5_S4_]+0xf7): undefined reference to `cudaGetErrorString'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI14CopyDataFromToEPKvmPvmm9DLContextS5_S4_[_ZN3tvm7runtime13CUDADeviceAPI14CopyDataFromToEPKvmPvmm9DLContextS5_S4_]+0x17c): undefined reference to `cudaSetDevice'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI14CopyDataFromToEPKvmPvmm9DLContextS5_S4_[_ZN3tvm7runtime13CUDADeviceAPI14CopyDataFromToEPKvmPvmm9DLContextS5_S4_]+0x191): undefined reference to `cudaGetErrorString'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI14CopyDataFromToEPKvmPvmm9DLContextS5_S4_[_ZN3tvm7runtime13CUDADeviceAPI14CopyDataFromToEPKvmPvmm9DLContextS5_S4_]+0x214): undefined reference to `cudaSetDevice'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI14CopyDataFromToEPKvmPvmm9DLContextS5_S4_[_ZN3tvm7runtime13CUDADeviceAPI14CopyDataFromToEPKvmPvmm9DLContextS5_S4_]+0x23e): undefined reference to `cudaMemcpyPeerAsync'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI14CopyDataFromToEPKvmPvmm9DLContextS5_S4_[_ZN3tvm7runtime13CUDADeviceAPI14CopyDataFromToEPKvmPvmm9DLContextS5_S4_]+0x258): undefined reference to `cudaGetErrorString'
lib/libtvm_runtime_pack.o: In function `tvm::runtime::CUDAModuleNode::GetFunc(int, std::string const&)':
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime14CUDAModuleNode7GetFuncEiRKSs[_ZN3tvm7runtime14CUDAModuleNode7GetFuncEiRKSs]+0x72): undefined reference to `cuModuleGetFunction'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime14CUDAModuleNode7GetFuncEiRKSs[_ZN3tvm7runtime14CUDAModuleNode7GetFuncEiRKSs]+0xc8): undefined reference to `cuGetErrorName'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime14CUDAModuleNode7GetFuncEiRKSs[_ZN3tvm7runtime14CUDAModuleNode7GetFuncEiRKSs]+0x14d): undefined reference to `cuModuleLoadData'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime14CUDAModuleNode7GetFuncEiRKSs[_ZN3tvm7runtime14CUDAModuleNode7GetFuncEiRKSs]+0x170): undefined reference to `cuGetErrorName'
lib/libtvm_runtime_pack.o: In function `tvm::runtime::CUDAPrepGlobalBarrier::operator()(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*) const':
tvm_runtime_pack.cc:(.text._ZNK3tvm7runtime21CUDAPrepGlobalBarrierclERKNS0_7TVMArgsEPNS0_11TVMRetValueE[_ZNK3tvm7runtime21CUDAPrepGlobalBarrierclERKNS0_7TVMArgsEPNS0_11TVMRetValueE]+0x2d): undefined reference to `cudaGetDevice'
tvm_runtime_pack.cc:(.text._ZNK3tvm7runtime21CUDAPrepGlobalBarrierclERKNS0_7TVMArgsEPNS0_11TVMRetValueE[_ZNK3tvm7runtime21CUDAPrepGlobalBarrierclERKNS0_7TVMArgsEPNS0_11TVMRetValueE]+0xcf): undefined reference to `cuModuleGetGlobal_v2'
tvm_runtime_pack.cc:(.text._ZNK3tvm7runtime21CUDAPrepGlobalBarrierclERKNS0_7TVMArgsEPNS0_11TVMRetValueE[_ZNK3tvm7runtime21CUDAPrepGlobalBarrierclERKNS0_7TVMArgsEPNS0_11TVMRetValueE]+0x1a7): undefined reference to `cuMemsetD32_v2'
tvm_runtime_pack.cc:(.text._ZNK3tvm7runtime21CUDAPrepGlobalBarrierclERKNS0_7TVMArgsEPNS0_11TVMRetValueE[_ZNK3tvm7runtime21CUDAPrepGlobalBarrierclERKNS0_7TVMArgsEPNS0_11TVMRetValueE]+0x1eb): undefined reference to `cudaGetErrorString'
tvm_runtime_pack.cc:(.text._ZNK3tvm7runtime21CUDAPrepGlobalBarrierclERKNS0_7TVMArgsEPNS0_11TVMRetValueE[_ZNK3tvm7runtime21CUDAPrepGlobalBarrierclERKNS0_7TVMArgsEPNS0_11TVMRetValueE]+0x268): undefined reference to `cuGetErrorName'
tvm_runtime_pack.cc:(.text._ZNK3tvm7runtime21CUDAPrepGlobalBarrierclERKNS0_7TVMArgsEPNS0_11TVMRetValueE[_ZNK3tvm7runtime21CUDAPrepGlobalBarrierclERKNS0_7TVMArgsEPNS0_11TVMRetValueE]+0x2bf): undefined reference to `cuGetErrorName'
tvm_runtime_pack.cc:(.text._ZNK3tvm7runtime21CUDAPrepGlobalBarrierclERKNS0_7TVMArgsEPNS0_11TVMRetValueE[_ZNK3tvm7runtime21CUDAPrepGlobalBarrierclERKNS0_7TVMArgsEPNS0_11TVMRetValueE]+0x33d): undefined reference to `cuModuleLoadData'
tvm_runtime_pack.cc:(.text._ZNK3tvm7runtime21CUDAPrepGlobalBarrierclERKNS0_7TVMArgsEPNS0_11TVMRetValueE[_ZNK3tvm7runtime21CUDAPrepGlobalBarrierclERKNS0_7TVMArgsEPNS0_11TVMRetValueE]+0x370): undefined reference to `cuGetErrorName'
lib/libtvm_runtime_pack.o: In function `tvm::runtime::CUDADeviceAPI::AllocDataSpace(DLContext, unsigned long, unsigned long)':
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI14AllocDataSpaceE9DLContextmm[_ZN3tvm7runtime13CUDADeviceAPI14AllocDataSpaceE9DLContextmm]+0x30): undefined reference to `cudaSetDevice'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI14AllocDataSpaceE9DLContextmm[_ZN3tvm7runtime13CUDADeviceAPI14AllocDataSpaceE9DLContextmm]+0x45): undefined reference to `cudaGetErrorString'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI14AllocDataSpaceE9DLContextmm[_ZN3tvm7runtime13CUDADeviceAPI14AllocDataSpaceE9DLContextmm]+0x16b): undefined reference to `cudaMalloc'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI14AllocDataSpaceE9DLContextmm[_ZN3tvm7runtime13CUDADeviceAPI14AllocDataSpaceE9DLContextmm]+0x180): undefined reference to `cudaGetErrorString'
lib/libtvm_runtime_pack.o: In function `tvm::runtime::CUDADeviceAPI::GetAttr(DLContext, tvm::runtime::DeviceAttrKind, tvm::runtime::TVMRetValue*)':
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE[_ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE]+0x79): undefined reference to `cudaDeviceGetAttribute'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE[_ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE]+0x89): undefined reference to `cudaGetErrorString'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE[_ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE]+0x11f): undefined reference to `cudaDeviceGetAttribute'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE[_ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE]+0x12f): undefined reference to `cudaGetErrorString'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE[_ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE]+0x2d5): undefined reference to `cudaDeviceGetAttribute'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE[_ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE]+0x2ed): undefined reference to `cudaGetErrorString'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE[_ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE]+0x3a5): undefined reference to `cudaDeviceGetAttribute'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE[_ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE]+0x3dd): undefined reference to `cudaDeviceGetAttribute'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE[_ZN3tvm7runtime13CUDADeviceAPI7GetAttrE9DLContextNS0_14DeviceAttrKindEPNS0_11TVMRetValueE]+0x3fd): undefined reference to `cudaGetErrorString'
lib/libtvm_runtime_pack.o: In function `tvm::runtime::CUDAWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*, void**) const':
tvm_runtime_pack.cc:(.text._ZNK3tvm7runtime15CUDAWrappedFuncclENS0_7TVMArgsEPNS0_11TVMRetValueEPPv[_ZNK3tvm7runtime15CUDAWrappedFuncclENS0_7TVMArgsEPNS0_11TVMRetValueEPPv]+0x32): undefined reference to `cudaGetDevice'
tvm_runtime_pack.cc:(.text._ZNK3tvm7runtime15CUDAWrappedFuncclENS0_7TVMArgsEPNS0_11TVMRetValueEPPv[_ZNK3tvm7runtime15CUDAWrappedFuncclENS0_7TVMArgsEPNS0_11TVMRetValueEPPv]+0x12d): undefined reference to `cuLaunchKernel'
tvm_runtime_pack.cc:(.text._ZNK3tvm7runtime15CUDAWrappedFuncclENS0_7TVMArgsEPNS0_11TVMRetValueEPPv[_ZNK3tvm7runtime15CUDAWrappedFuncclENS0_7TVMArgsEPNS0_11TVMRetValueEPPv]+0x17b): undefined reference to `cudaGetErrorString'
tvm_runtime_pack.cc:(.text._ZNK3tvm7runtime15CUDAWrappedFuncclENS0_7TVMArgsEPNS0_11TVMRetValueEPPv[_ZNK3tvm7runtime15CUDAWrappedFuncclENS0_7TVMArgsEPNS0_11TVMRetValueEPPv]+0x1f0): undefined reference to `cuGetErrorName'
lib/libtvm_runtime_pack.o: In function `tvm::runtime::CUDAModuleNode::~CUDAModuleNode()':
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime14CUDAModuleNodeD2Ev[_ZN3tvm7runtime14CUDAModuleNodeD5Ev]+0x6c): undefined reference to `cudaSetDevice'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime14CUDAModuleNodeD2Ev[_ZN3tvm7runtime14CUDAModuleNodeD5Ev]+0x7c): undefined reference to `cudaGetErrorString'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime14CUDAModuleNodeD2Ev[_ZN3tvm7runtime14CUDAModuleNodeD5Ev]+0xf5): undefined reference to `cuModuleUnload'
tvm_runtime_pack.cc:(.text._ZN3tvm7runtime14CUDAModuleNodeD2Ev[_ZN3tvm7runtime14CUDAModuleNodeD5Ev]+0x10e): undefined reference to `cuGetErrorName'
collect2: error: ld returned 1 exit status
Makefile:29: recipe for target 'lib/cpp_deploy_pack' failed
make: *** [lib/cpp_deploy_pack] Error 1
Run the example
Run the deployment with all in one packed library...
./run_example.sh: line 10: lib/cpp_deploy_pack: No such file or directory
Run the deployment with all in normal library...

Whether  int device_type = kDLGPU; or kDLCPU, the same problem (./run_example.sh: line 10: lib/cpp_deploy_pack: No such file or directory) is shown. 
What should I do?  
@WolffyChen  @tqchen

**Comment by WolffyChen** [comment]
You should add cuda library. Like `-L/usr/local/cuda/lib64 -lcudart -lcublas -lcurand` and so on.
This is just a reference. You can try it according to your own project.

**Comment by Arthur-Shi** [comment]
Thank you so much, It works well!

**Comment by Arthur-Shi** [comment]
@WolffyChen But how can I know which library I need ?

**Comment by Arthur-Shi** [comment]
And my ~/.bashrc is including all library.
export PATH=/usr/local/cuda-8.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:$LD_LIBRARY_PATH

It should can do that, I think.

**Comment by Arthur-Shi** [comment]
@WolffyChen I write what I try to do in #626 , I really have no idea on solving this problem.

**Comment by Arthur-Shi** [comment]
AS shown in #626 , I close this issue which is the same problem as that one.
