### ISSUE TITLE
NVIDIA GPU Int8 Support

### ISSUE THREAD

**Issue by ZihengJiang** [dmlc/tvm#620]
- Wrap CUDNN Int8 Operators @reminisce
  - [ ] fully connected
  - [ ] conv
  - [ ] pooling (max, avg)
  - [ ] activation (relu)
- Pascal Int8 Operators @reminisce
- Volta Int8 Operators @Laurawly 

Please feel free to edit and extend the details. @reminisce @Laurawly

**Comment by mli** [comment]
we only have a single gpu, tesla p4, supporting int8 well. let's just focus on it.

**Comment by tqchen** [comment]
close due to stale state, will open a new issue when there is ongoing int8 ops
