### ISSUE TITLE
implement PSROIPooling via TVM DSL

### ISSUE THREAD

**Issue by xqdan** [dmlc/tvm#637]
Hi all,
    I'm going to implement  PSROIPooling via TVM DSL.
   notice that ops already in tvm are simple in compute but kinda complex in schedule. it would not be hard to figure out what compute part is thru related paper or implementation in other frameworks,  but a little confused  with how to deal with schedule.
  for my case, I can try to port the compute part from c++ version into tvm DSL, what about the schedule part, no clue right now.
   guys who have done other ops via tvm, @tqchen @Huyuwei, could you give me some tips of implementing compute and schedule of PSROIPooling?

Thanks,

**Comment by Huyuwei** [comment]
If you mean GPU schedule, you can try https://github.com/dmlc/tvm/blob/master/topi/python/topi/cuda/injective.py as a start. The schedule is simple, only using split, fuse, and bind. It should work for most operators.

You can first use llvm naive schedule (no schedule) to confirm the correctness of the compute declaration on CPU.

**Comment by xqdan** [comment]
ok

**Comment by xqdan** [comment]
ok, thanks.
BTW, for compute part, notice that there is a CUDA_KERNEL_LOOP in PSROIPoolForwardKernel. https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/psroi_pooling.cu;

should tvm dsl include the CUDA_KERNEL_LOOP in compute part?
