### ISSUE TITLE
Question: How to run a large Network in the simple way without TVM and LLVM?

### ISSUE THREAD

**Issue by Arthur-Shi** [dmlc/tvm#639]
I am trying to write a FASTER RCNN network by TVM. I would like to run the network by only one shared library to run faster. I am thinking about how to save these modules.

One way is using different schedule method and using different building. 
For example, I can save the modules one by one. And then run by many shared library.

            s4 = topi.cuda.schedule_pool(pool)
            s5 = topi.cuda.schedule_injective(change)
            s6 = topi.cuda.schedule_dense(dense)
            s7 = topi.cuda.schedule_softmax(Softmax)
            s8 = topi.cuda.schedule_depthwise_conv2d_nchw(NewDepthwiseConv2d)

        f4 = tvm.build(s4, [Pool, pool], device)
        f5 = tvm.build(s5, [reshape, change], device)
        f6 = tvm.build(s6, [reshape1, weight, dense], device)
        f7 = tvm.build(s7, [softmax, Softmax], device)
        f8 = tvm.build (s8,[Input, Filter, Scale, Shift, NewDepthwiseConv2d], device)

But the problem of this method is how to link different libraries, I have no idea about saving output of one module and then using it on the next module as input.

And another way is build all modules using the same schedule so that I can save everything in one shared library.
For example，

            s1 = topi.cuda.schedule_depthwise_conv2d_nchw(DepthwiseConv2d)
            s2 = topi.cuda.schedule_depthwise_conv2d_nchw(ScaleShift)
            s3 = topi.cuda.schedule_depthwise_conv2d_nchw(Relu)
        f1 = tvm.build(s1, [Input, Filter, DepthwiseConv2d], device)
        f2 = tvm.build(s2, [Input, Filter, Scale, Shift, ScaleShift], device)
        f3 = tvm.build(s3, [Input, Filter, Scale, Shift, Relu],device)

But this method make the program run fastest.

I dont know which method is suitable for the large network(e.g. Faster RCNN), or two methods both are wrong. I am trying to run only the testing stage of Faster Rcnn, So I dont need train them. That's why I want to run by shared library and Cpp file.

**Comment by tqchen** [comment]
You should use nnvm compiler which compiles and save a network for you, instead per operator

**Comment by Arthur-Shi** [comment]
I know NNVM can help to save a network as a shared library, but it has not the example for running the saved module by C++. And my C++ is not good.

And I would like to run a network without TVM and NNVM, ONLY by shared library and Cpp file, does it work well?

**Comment by Arthur-Shi** [comment]
I saw the example for running .o file in /home/aries/nnvm/tutorials/deploy_model_on_rasp.py. 

Does it include the device module?

**Comment by tqchen** [comment]
nnvm compiles the module directly into a module that only depend on TVM runtime. You will be able to run it with only the all in one runtime or the runtime built with tvm

**Comment by Arthur-Shi** [comment]
Thank you so much!!!
