### ISSUE TITLE
[CUDA] Support popcount intrinsic

### ISSUE THREAD

**Issue by jwfromm** [dmlc/tvm#644]
Using tvm.popcount in a function seems to cause problem when a gpu schedule is applied. For example, the function
`matmul = tvm.compute((batch, out_dim), lambda i, j: \
                          tvm.sum(tvm.popcount(data[i, k] ^ weight[j, k]), axis=k), \
                          tag='binary_dense')`
runs fine on cpu but throws the error 
`TVMError: [04:35:49] src/codegen/llvm/codegen_llvm.cc:630: unknown intrinsic popcount`
when scheduled for the GPU despite a popcount intrinsic existing for cuda. This is quite an important feature for supporting binarization which is an increasingly popular method of network optimization.

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/629 is yet to be merged.  To enable gpu schedule, we will need to explicit bind things into threads to enable cuda codegen. 

The default schedule which do not bind anything won't work on gpu

**Comment by jwfromm** [comment]
I completely understand and am doing this testing with a very simple GPU schedule that does the bindings. I've added the two functions
`def schedule_binarize_pack_gpu(outs):
    # outs is an array of Tensors (computation graph description)
    # returns schedule s
    
    outs = [outs] if isinstance(outs, tvm.tensor.Tensor) else outs
    s = tvm.create_schedule([x.op for x in outs])
    def _schedule(Out):
        bx, tx = s[Out].split(Out.op.axis[0], factor=64)
        s[Out].bind(bx, tvm.thread_axis("blockIdx.x"))
        s[Out].bind(tx, tvm.thread_axis("threadIdx.x"))
    def traverse(OP):
        if OP.tag == "binarize_pack":
            Out = OP.output(0)
            _schedule(Out)
        else:
            raise RuntimeError("Unssuported operator: %s" % OP.tag)
    traverse(outs[0].op)
    return s`
and 
`def schedule_binary_dense_gpu(outs):
    """Schedule for dense operator.
    Parameters
    ----------
    outs: Array of Tensor
        The computation graph description of dense
        in the format of an array of tensors.
    Returns
    -------
    s: Schedule
        The computation schedule for dense.
    """
    outs = [outs] if isinstance(outs, tvm.tensor.Tensor) else outs
    s = tvm.create_schedule([x.op for x in outs])
    def _schedule(Dense):
        num_thread = 64
        k = Dense.op.reduce_axis[0]
        ko, kf = s[Dense].split(k, factor=num_thread)
        DenseF = s.rfactor(Dense, kf)

        if Dense.op in s.outputs:
            Out = Dense
        else:
            Out = outs[0].op.output(0)
            s[Dense].compute_at(s[Out], s[Out].op.axis[1])
        s[Out].bind(s[Out].op.axis[0], tvm.thread_axis("blockIdx.y"))
        s[Out].bind(s[Out].op.axis[1], tvm.thread_axis("blockIdx.x"))

        tx = s[Dense].op.reduce_axis[0]
        thread_x = tvm.thread_axis("threadIdx.x")
        s[Dense].bind(tx, thread_x)
        s[DenseF].compute_at(s[Dense], tx)
        s[Dense].set_store_predicate(thread_x.var.equal(0))
        s[Out].set_store_predicate(thread_x.var.equal(0))

    def traverse(OP):
        # inline all one-to-one-mapping operators except the last stage (output)
        if tag.is_broadcast(OP.tag):
            if OP not in s.outputs:
                s[OP].compute_inline()
            for tensor in OP.input_tensors:
                if tensor.op.input_tensors:
                    traverse(tensor.op)
        # schedule dense
        elif OP.tag == 'binary_dense':
            Dense = OP.output(0)
            _schedule(Dense)
        else:
            raise RuntimeError("Unsupported operator: %s" % OP.tag)

    traverse(outs[0].op)
    return s`

The binary packing actually works quite well on GPU, I'm only having trouble with the dense due to this popcount intrinsic issue.

**Comment by tqchen** [comment]
So if binding is properly done, we only have to register lowering rule for popcount in https://github.com/dmlc/tvm/blob/master/src/codegen/intrin_rule_cuda.cc#L39 as discussed in https://github.com/dmlc/tvm/pull/629

**Comment by jwfromm** [comment]
I see, that does seem like the solution. I'll give it a shot, thanks!

**Comment by tqchen** [comment]
@jwfromm want to open a PR on this specific issue?

**Comment by tqchen** [comment]
I mean send a patch to enable popcount for cuda backend so we could close this issue

**Comment by jwfromm** [comment]
I haven't had time to implement and test this yet, it's on my list though. We can close this for now though to reduce the number of issues.

**Comment by tqchen** [comment]
any update on this?

**Comment by Huyuwei** [comment]
#774
