### ISSUE TITLE
[RUNTIME] Support Limited Save to Module without OpenCL Cross Compile

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#648]
Currently we require a local opencl module in order to be able to save a module. This is not strictly necessary.  Since we only need the SaveToBinary feature which can be supported without enable OpenCL in local env (the execution won't work).  This is likely to make life easy for local env who do not have OpenCL  like in case of #641 

- [ ] Support a GPUSourceModule that support SaveToBinary and GetSource
- [ ] Return GPUSourceModule when CL/CUDA  is not enabled.

**Comment by merrymercy** [comment]
Shall we just add SaveToFile and SaveToBinary to tvm::codegen::SourceModule or add a new class in tvm::runtime?

**Comment by tqchen** [comment]
@merrymercy We can create a tvm::codegen::DeviceSourceModule that subclass SourceModule(let us not put it in runtime as it creates new files into runtime).

The reasoning behind this is that DeviceSourceModule might save different from source(if it is a host side c++ file)
