### ISSUE TITLE
tensorize with non-stride-1 data layout

### ISSUE THREAD

**Issue by derisavi** [dmlc/tvm#651]
I noticed that in tests/python/unittest/test_schedule_tensorize.py, in test_tensorize_matmul(), the algorithm for matmul corresponds to A*(B^T), i.e., A multiplied by tranpose of B. My guess it that this is done to make accesses of the reduction iteration variable (i.e., k) stride-1 in B. That way it would easily match with intrin_gemv. 
Is that correct? If yes, how can we change the example so that we can tensorize gemv in A*B as well?

**Comment by tqchen** [comment]
You can do that, by specifying a buffer when declaring intrinsics(which gives you symbolic stride information)

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/issues/585
