### ISSUE TITLE
can't install tvm when i update tvm

### ISSUE THREAD

**Issue by gengtsh** [dmlc/tvm#656]
hi, i encountered a problem, i'd appreciate if someone can help me out.
before i updated this morning, i could run nnvm + tvm , but when i updated tvm, i found i couldn't  run make successfully.
i got the following errors:
include/tvm/././runtime/./packed_func.h:220:37: error: ‘kDLFloat’ was not declared in this scope
     TVM_CHECK_TYPE_CODE(type_code_, kDLFloat);

include/tvm/././runtime/./packed_func.h:224:37: error: ‘kDLInt’ was not declared in this scope
     TVM_CHECK_TYPE_CODE(type_code_, kDLInt);

i also noticed that i can't   install python package, i get the following errors:
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    LIB_PATH = libinfo['find_lib_path']()
  File "./tvm/_ffi/libinfo.py", line 85, in find_lib_path
    str('\n'.join(lib_dll_path + runtime_dll_path)))
RuntimeError: Cannot find the files.
List of candidates:
/tvm/python/tvm/libtvm.so
/tvm/build/libtvm.so
/tvm/build/Release/libtvm.so
/tvm/lib/libtvm.so
/libtvm.so
/tvm/python/tvm/libtvm_runtime.so
/tvm/build/libtvm_runtime.so
/tvm/build/Release/libtvm_runtime.so
/tvm/lib/libtvm_runtime.so
/libtvm_runtime.so

**Comment by tqchen** [comment]
do``` git submodule update --recursive``` to update to latest dlpack

**Comment by gengtsh** [comment]
thanks, it works.
