### ISSUE TITLE
More powerful simplification for Tensorize

### ISSUE THREAD

**Issue by derisavi** [dmlc/tvm#657]
Hi,
   I have an example where tensorize is not working as expected. I digged a little bit and I observe the following in tensorize.cc:VerifyTensorizeBody() function. Inside the loop and for a some i I have:
body[i] (expression before CanonicalSimplify) is 
`reduce(combiner=comm_reducer(result=[(x + y)], lhs=[x], rhs=[y], identity_element=[0.000000h]), source=[(aa((((i + ((x.c.c.outer*16) + ((x.outer*512) + (x.inner.outer*256)))) % 16) - 0), (((k + ((k.outer*32) + (k.inner.outer*16))) % 16) - 0))*bb((((k + ((k.outer*32) + (k.inner.outer*16))) % 16) - 0), (((j + ((y.c.c.outer*16) + ((y.outer*512) + (y.inner.outer*256)))) % 16) - 0)))], axis=[iter_var(k, Range(min=0, extent=16))], where=(uint1)1, value_index=0)`
and lhs (expression after CanonicalSimplify) is
`reduce(combiner=comm_reducer(result=[(x + y)], lhs=[x], rhs=[y], identity_element=[0.000000h]), source=[(aa((((((x.outer*512) + (x.inner.outer*256)) + (x.c.c.outer*16)) + i) % 16), ((((k.outer*32) + (k.inner.outer*16)) + k) % 16))*bb(((((k.outer*32) + (k.inner.outer*16)) + k) % 16), (((((y.outer*512) + (y.inner.outer*256)) + (y.c.c.outer*16)) + j) % 16)))], axis=[iter_var(k, Range(min=0, extent=16))], where=(uint1)1, value_index=0)`
Note that CanonicalSimplify has only simplified a-0 to a. I expected that x*(y*z) % z is also simplified to 0. It seems that there are some simplification rules in Simplify.cc but for some reason they are not used at all. 
Am I missing something here? If not and this is a real bug, I'd appreciate a fix or an idea on where to look or where to fix this. Thanks!

**Comment by tqchen** [comment]
CanonicalSimplify and Simplify are two simplifier that have different strength. For your case we can possibly combine  the two. Feel free to put a reproducible example and patch to donso

**Comment by derisavi** [comment]
I made some changes and I'm now down to 
`reduce(combiner=comm_reducer(result=[(x + y)], lhs=[x], rhs=[y], identity_element=[0.000000h]), source=[(aa((i % 16), (k % 16))*bb((k % 16), (j % 16)))], axis=[iter_var(k, Range(min=0, extent=16))], where=(uint1)1, value_index=0)`
The only remaining problem is simplifying i%16 to i. i is an iteration variable in the definition of the intrinsic. There is already a rule in % that can do that simplification if it can be proved that i is less than 16. Somehow I need to send the scope information for the intrinsic to Simplify. How can I do that?

**Comment by derisavi** [comment]
Thanks for #663. I guess we need to make a similar change for CanonicalSimplify. Is that correct?
Here is my understanding: Some ops are defined in HalideIR and some in TVM. In particular, `Reduce` is in the latter. Moreover, Simplify is part of HalideIR, and therefore, can be applied only on expressions that have only HalideIR ops. And CanonicalSimplify can be applied on TVM expressions (which can include any TVM-specific or HalideIR ops). To simplify an expression that has a `Reduce` op at the top, we can only apply CanonicalSimplify on it (while passing range information to resolve original problem).

**Comment by tqchen** [comment]
Yes, I agree. Usually the indices do not contain reduction, so both should work out of box. In the long term I would love to rethink the symbolic simplification and integer set analysis to create a more formal one that can be used in all scenarios

**Comment by tqchen** [comment]
going to close this for now as the original question is resolved

**Comment by tqchen** [comment]
contribution of improvement is more than welcomed
