### ISSUE TITLE
Register Extension Support for PyCapsule

### ISSUE THREAD

**Issue by jwfromm** [dmlc/tvm#658]
Currently, the method of enabling DLTensors for tvm relies on python having access to the data attribute. However, pytorch's _to_dlpack operator returns a PyCapsule that is opaque to python, making incompatible with the way register_extension is set up. If PyCapsules were allowed, integration with PyTorch would be much more efficient. As a caveat, I may be totally missing something about how registering extensions work, and would be thrilled to be corrected. My goal is to use a PyTorch tensor buffer without having to copy to an ndarray. I imagine the code would look similar to this:

```
@tvm.register_extension
class FireTensor(object):
    _tvm_tcode = tvm.TypeCode.ARRAY_HANDLE

    def __init__(self, tensor):
        self.handle = torch._C._to_dlpack(tensor)

    @property
    def _tvm_handle(self):
        return self.handle
```

**Comment by tqchen** [comment]
cc @soumith  @prigoyal @zdevito who might have better knowledge on how we could enable this.

**Comment by tqchen** [comment]
Your code gives a natural  way to support this, the necessary workflow, from TVM's side is that

- Provide a python function in the PyCapsule to grab out the address  of the underlying DLMangedTensor(which is also address of DLTensor)
- Return such address(in int) when override _tvm_handle.

register the extension to TVM's runtime system. This will allow the result TVM function invoke the FireTensor object and treat it as DLTensor

**Comment by jwfromm** [comment]
I think the main issue is that as far as I know, there's no way to get the underlying DLTensor from a python as PyCapsules are opaque objects (and appear to have no attributes).

**Comment by prigoyal** [comment]
@jwfromm if I understand correctly, are you trying to access the underlying DLTensor (C/C++) tensor from the PyObject (a PyCapsule holding DLTensor)? Inside C++ itself, you can get the underlying DLTensor using below:

assume you have pycapsule
```PyObject *input```
 extract the tensor using below
```
(DLManagedTensor *)PyCapsule_GetPointer(input, "dltensor");
```

DLTensor is supposed to be a way of exchanging tensors between frameworks. So once you have the pycapsule coming from anywhere, I assume writing a simple pybind code which takes this pycapsule, extracts the dltensor using above line and converts it to the framework tensor like caffe2 tensor, pytorch tensor etc.

**Comment by jwfromm** [comment]
I was hoping to get this working purely inside python. In TVM, there's a register extension function that allows TVM to use DLTensors in it's computation. However, it requires the ability to access the data pointer. Right now, the PyCapsule prevents me from doing this. I agree that it seems like the solution is to go to the C++ and change how register extension works, I was just hoping there was something a little smoother.

**Comment by soumith** [comment]
@jwfromm you could probably do this with ctypes, purely inside python land (albeit a bit hacky)

**Comment by tqchen** [comment]
OK, I think it becomes clear that what is needed is to get address value in integer and override ```_tvm_handle``` function. 

You can do that with ctypes(it is also supported in cython) via ``` ctypes.pythonapi.PyCapsule_GetPointer ```. 

Since this is a commonly needed feature, maybe it makes sense to provide such function as an API. either in pytorch(something like ```torch._C._dlpack_address``` ) or tvm.

**Comment by prigoyal** [comment]
btw, to use dlpack conversions from pytorch, you can simply do the following instead of calling the torch C Module.
```
from torch.utils.dlpack import from_dlpack, to_dlpack
a = to_dlpack(tensor)
b = from_dlpack(a)
```

I guess, we can easily add the python function call in pytorch that @tqchen suggested. PRs welcome :)

**Comment by jwfromm** [comment]
ctypes looks like it works for getting the dltensor pointer out, but I'm getting some other errors when using the new extension in a simple test.

```
@tvm.register_extension
class FireTensor(object):
    _tvm_tcode = tvm.TypeCode.ARRAY_HANDLE

    def __init__(self, tensor):
        self.handle = torch._C._to_dlpack(tensor)
        self.name = self.get_name()
    def get_name(self):
        ctypes.pythonapi.PyCapsule_GetName.restype = ctypes.c_char_p
        ctypes.pythonapi.PyCapsule_GetName.argtypes = [ctypes.py_object]
        return ctypes.pythonapi.PyCapsule_GetName(self.handle)
    @property
    def _tvm_handle(self):
        ctypes.pythonapi.PyCapsule_GetPointer.restype = ctypes.c_void_p
        ctypes.pythonapi.PyCapsule_GetPointer.argtypes = [ctypes.py_object, ctypes.c_char_p]
        return ctypes.pythonapi.PyCapsule_GetPointer(H, name)

n = tvm.var("n")
A = tvm.placeholder((n,), name='A')
B = tvm.placeholder((n,), name='B')
C = tvm.compute(A.shape, lambda i: A[i] + B[i], name="C")
s = tvm.create_schedule(C.op)
fadd = tvm.build(s, [A, B, C], target_host="llvm", name="myadd")
n = 10
a = FireTensor(torch.randn(n,))
b = FireTensor(torch.randn(n,))
c = FireTensor(torch.zeros(n,))
fadd(a, b, c)

---------------------------------------------------------------------------
TVMError                                  Traceback (most recent call last)
<ipython-input-36-5b5f23f104e8> in <module>()
     12 b = FireTensor(torch.randn(n,))
     13 c = FireTensor(torch.zeros(n,))
---> 14 fadd(a, b, c)
     15 #np.testing.assert_allclose(c.asnumpy(), a.asnumpy() + b.asnumpy())

/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/tvm-0.1.0-py3.6-linux-x86_64.egg/tvm/_ffi/function.py in __call__(self, *args)
    126             return self._entry(*args)
    127         f = self.entry_func
--> 128         return f(*args)
    129 
    130 

/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/tvm-0.1.0-py3.6-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py in __call__(self, *args)
    181         check_call(_LIB.TVMFuncCall(
    182             self.handle, values, tcodes, ctypes.c_int(num_args),
--> 183             ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
    184         _ = temp_args
    185         _ = args

/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/tvm-0.1.0-py3.6-linux-x86_64.egg/tvm/_ffi/base.py in check_call(ret)
     60     """
     61     if ret != 0:
---> 62         raise TVMError(py_str(_LIB.TVMGetLastError()))
     63 
     64 

TVMError: [19:46:35] src/codegen/llvm/llvm_module.cc:59: Check failed: ret == 0 (-1 vs. 0) Assert fail: tvm_handle_is_null(arg0.strides), arg0.strides: expected to be nullptr for contiguous array
```

Am I missing something with how extensions are meant to be used or is this a bug?

**Comment by tqchen** [comment]
When build tvm functions the function expects different dltensor input. By default, it build expecting compact tensor(strides equals null ) and this offers more optimization. We can either make sure pytorch detect compactness and return such tensor when possible. Or make tvm generate function with strides support(by specify a buffer binding in build)

Note that supporting strides introduces restrictions like vectorization because it makes it harder to deduce alignment

**Comment by jwfromm** [comment]
I notice that tvm.decl_buffer has a strides argument. Is there a way to make the simple fadd function above work using this?

**Comment by tqchen** [comment]
Try https://github.com/dmlc/tvm/pull/669  which checks if the buffer is compact even when strides is available. This is a recommended approach when the data buffer is compact.

Alternatively, use ``` tvm.decl_buffer``` to declare a buffer with strides array, and specify them with binds argument in  http://docs.tvmlang.org/api/python/build.html#tvm.build

see also http://docs.tvmlang.org/api/python/tvm.html#tvm.decl_buffer and https://github.com/dmlc/tvm/issues/585

**Comment by jwfromm** [comment]
Your commit resolves the problem, everything is working great now! Thanks. For reference, here's what the custom tensor for pytorch ended up looking like.

```
@tvm.register_extension
class FireTensor(object):
    _tvm_tcode = tvm.TypeCode.ARRAY_HANDLE

    def __init__(self, tensor):
        self.handle = torch._C._to_dlpack(tensor)
        self.name = self.get_name()
    def get_name(self):
        ctypes.pythonapi.PyCapsule_GetName.restype = ctypes.c_char_p
        ctypes.pythonapi.PyCapsule_GetName.argtypes = [ctypes.py_object]
        return ctypes.pythonapi.PyCapsule_GetName(self.handle)
    def to_torch(self):
        return torch._C._from_dlpack(self.handle)
    @property
    def _tvm_handle(self):
        ctypes.pythonapi.PyCapsule_GetPointer.restype = ctypes.c_void_p
        ctypes.pythonapi.PyCapsule_GetPointer.argtypes = [ctypes.py_object, ctypes.c_char_p]
        return ctypes.pythonapi.PyCapsule_GetPointer(self.handle, self.name)
```
