### ISSUE TITLE
where to find class "TVMAPIHandleException"?

### ISSUE THREAD

**Issue by BigJerry** [dmlc/tvm#661]
I have a runtime error , and I wanna debug it. which exception should I use and how to include it correctly?

**Comment by tqchen** [comment]
it is in here https://github.com/dmlc/tvm/blob/master/src/runtime/runtime_base.h#L29 by default tvm outputs the stacktrace trace and the c++ exception is caught  at API boundary

**Comment by BigJerry** [comment]
so, for using this exception class ,what I need is only including this  header? @tqchen

**Comment by BigJerry** [comment]
ok, I added this header into my codes.However , it seems this exception won't give string information , thus I still get an error when running it. I'll distribute a new issue about it. Anyway, thank you.
