### ISSUE TITLE
[multi-stage optimization]How to optimize the computation using tvm after nnvm's graph optimization

### ISSUE THREAD

**Issue by BigJerry** [dmlc/tvm#662]
In your announcement you illustrated with a picture that before tvm optimizes ops , it is nnvm who's responsible for graph optimization. I 'm wondering how does this completed workflow (tvm optimization 
after nnvm graph optimization) implement? Any tutorial?

**Comment by tqchen** [comment]
checkoud https://github.com/dmlc/nnvm for tutorials

**Comment by BigJerry** [comment]
ok, seems nnvm.compiler.build method calls tvm to optimize already.. but in my case , it only brings 10ms improvment, and doesn't match the result here: http://tvmlang.org/2017/08/22/Optimize-Deep-Learning-GPU-Operators-with-TVM-A-Depthwise-Convolution-Example.html, I'll launch this issue to nnvm.
