### ISSUE TITLE
conv2d error when modify in_channel 

### ISSUE THREAD

**Issue by xqdan** [dmlc/tvm#666]
Hi all,

When we do this modification,  in_channel 3->8

```
--- a/tests/python/contrib/test_cudnn.py
+++ b/tests/python/contrib/test_cudnn.py
@@ -32,7 +32,7 @@ def test_softmax():
    verify()

def test_conv2d():
-    in_channel = 3
+    in_channel = 8
    out_channel = 32
    filter_h = 3
    filter_w = 3
@@ -43,7 +43,7 @@ def test_conv2d():
    dilation_h = 1
    dilation_w = 1

-    xshape = [4, 3, 32, 32]
+    xshape = [4, 8, 32, 32]
    if not tvm.module.enabled("cuda"):
        print("skip because cuda is not enabled...")
        return
```

gets error 

`[16:19:03] src/codegen/llvm/llvm_module.cc:59: Check failed: ret == 0 (-1 vs. 0) [16:19:03] src/contrib/cudnn/conv_forward.cc:83: Check failed: e == CUDNN_STATUS_SUCCESS (9 vs. 0) cuDNN: CUDNN_STATUS_NOT_SUPPORTED`

when do in_channel 3->64, gets error

`[16:20:54]………/nnvm/tvm/dmlc-core/include/dmlc/logging.h:308: [16:20:54] src/contrib/cudnn/conv_forward.cc:155: Check failed: e == CUDNN_STATUS_SUCCESS (3 vs. 0) cuDNN: CUDNN_STATUS_BAD_PARA`

however, if we call cudnn directly, it's ok.

**Comment by tqchen** [comment]
cc @antinucleon @ZihengJiang

**Comment by masahi** [comment]
@xqdan #708 should solve your issue.
