### ISSUE TITLE
Interaction with TACO

### ISSUE THREAD

**Issue by yangjunpro** [dmlc/tvm#671]
The github is here: https://github.com/tensor-compiler/taco
Also their paper can be found here: http://tensor-compiler.org/kjolstad-oopsla17-tensor-compiler.pdf

Although up to now, taco only supports sparse agains dense algebra operations, it still looks interesting. 

Any suggestion for incorporating things like taco into tvm? Since the essential computation of deep learning actually is tensor algebra stuffs.  

Thanks

**Comment by tqchen** [comment]
TACO is a great work focusing on sparse algebra. It is a great work. You can find tvm's native tensor expression language quite similar with what taco have, and so far tvm focus on dense tensor algebra and supporting GPUs and more hardware backends. 

There is definitely something interesting interaction can be done between the frameworks, although there is no concrete plan on this yet.
