### ISSUE TITLE
opencl and vectorization on mali-T860 gpu

### ISSUE THREAD

**Issue by ma-xiaodong** [dmlc/tvm#680]
https://github.com/dmlc/tvm/blob/0824de5489a6f7a9c94a804a7127d7536107edbf/src/codegen/build_opencl.cc#L25
For some opencl kernels, pragma is needed. For example, on mali-T860 gpu, if you want to use half8 data type,  cl_khr_fp16 must be enabled.
I add a line here:
**code = "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n" + code;**
Then it ok to run the kernel.
I know it is not a good way and there may be some good way to support pragma.

**Comment by tqchen** [comment]
cc @merrymercy do you encounter similar issue? Maybe we could enable it by default in codegen when fp16 is used?

**Comment by merrymercy** [comment]
Yes, I see the same error and can get rid of it by adding this #pragma

**Comment by merrymercy** [comment]
I agree to enable it by default.
@ma-xiaodong  To support more pragma, for now you can register tvm_callback_opencl_postproc.
