### ISSUE TITLE
Comparison to Halide

### ISSUE THREAD

**Issue by binarybana** [dmlc/tvm#682]
It'd be very helpful to compare TVM to Halide in the [FAQ](https://github.com/dmlc/tvm/blob/master/docs/faq.md). We already have experience working with Halide on our side and are trying to evaluate the merits of TVM versus Halide's maturity. Especially given that TVM uses HalideIR and has lowering inspired by Halide.

**Comment by tqchen** [comment]
http://docs.tvmlang.org/faq.html#tvm-s-relation-to-other-ir-dsl-projects answers the difference from existing projects, including Halide. In short, we specifically focus on deep learning, and optimize for multiple hardware backends (GPUs and other accelerators).

The major challenge is to make the schedule space complete enough to cover the state of art kernels for hardware back-ends we want to support, specifically gpu and other hardwares. The second challenge is to build the dsl representation to cover things we care about in deep learning(e.g. recurrence). The other issues include the ease of deployment and interpolation.

These challenges are not well addressed by existing frameworks(including Halide) and requires rethink and design of the stack as opposed to simply reuse an existing one.

You can also find that the TVM's IR itself is evolving, and we continuously learn new lessons from hand optimization and tuning for various backends.

**Comment by tqchen** [comment]
This being said, I think Halide is a great project, we benefit a lot from it, and this comment only reflects the current state of the projects and difference comes from the different focus on goals.

**Comment by jackwish** [comment]
@tqchen It seems the tvmlang.org is broken, where should it link now? Thanks!
