### ISSUE TITLE
parameter binding doesn't happen for reduce_init in tensorize

### ISSUE THREAD

**Issue by derisavi-huawei** [dmlc/tvm#689]
This is a bug report. The following is a modified and simplified version of tests/python/unittest/test_schedule_tensorize.py. The difference between this and the original unit test is that the intrinsic `intrin_gemv` is defined as a dynamically sized gemv.

```python
import tvm

def intrin_gemv():
    m = tvm.var("m")
    n = tvm.var("n")
    ldw = tvm.var('ldw')
    w = tvm.placeholder((m, n), name='w')
    x = tvm.placeholder((n,), name='x')
    k = tvm.reduce_axis((0, n), name='k')
    z = tvm.compute((m,), lambda i:
                    tvm.sum(w[i, k] * x[k], axis=k), name='z')
    Wb = tvm.decl_buffer(w.shape, w.dtype,
                         name="W",
                         offset_factor=16,
                         strides=[ldw, 1])
    def intrin_func(ins, outs):
        ww, xx = ins
        zz = outs[0]
        ww_ptr = ww.access_ptr("r")
        xx_ptr = xx.access_ptr("r")
        zz_ptr = zz.access_ptr("w")
        body = tvm.call_packed(
            "gemv", ww_ptr, xx_ptr, zz_ptr, n, ldw)
        reset = tvm.call_packed(
            "fill_zero", zz_ptr, n, ldw)
        update = tvm.call_packed(
            "gemv_add", ww_ptr, xx_ptr, zz_ptr, m, n, ldw)
        return body, reset, update

    with tvm.build_config(data_alignment=16,
                          offset_factor=16):
        return tvm.decl_tensor_intrin(z.op, intrin_func,
                                      binds={w: Wb})


def test_tensorize_matmul():
    n = 1024
    m = n
    l = n
    A = tvm.placeholder((n, l), name='A')
    B = tvm.placeholder((m, l), name='B')
    k = tvm.reduce_axis((0, l), name='k')
    C = tvm.compute((n, m), lambda i, j:
                    tvm.sum(B[j, k] * A[i, k], axis=k), name='C')


    def check_rfactor(factor, rfactor):
        s = tvm.create_schedule(C.op)
        x, y = C.op.axis
        rk = C.op.reduce_axis[0]
        yo, yi = s[C].split(y, factor=factor)
        ro, ri = s[C].split(rk, factor=rfactor)
        s[C].reorder(yo, ro, yi, ri)
        print(tvm.lower(s, [A,B,C], simple_mode=True))
        gemv = intrin_gemv()
        s[C].tensorize(yi, gemv)
        s = s.normalize()
        print(tvm.lower(s, [A,B,C], simple_mode=True))

    check_rfactor(16, 16)


if __name__ == "__main__":
    test_tensorize_matmul()
```

If you run this example, you will get the following output, which shows the HalideIR before and after tensorize.
```
produce C {
  for (i, 0, 1024) {
    for (j.outer, 0, 64) {
      for (j.inner.init, 0, 16) {
        C[((((i*64) + j.outer)*16) + j.inner.init)] = 0.000000f
      }
      for (k.outer, 0, 64) {
        for (j.inner, 0, 16) {
          for (k.inner, 0, 16) {
            C[((((i*64) + j.outer)*16) + j.inner)] = (C[((((i*64) + j.outer)*16) + j.inner)] + (B[(((((j.outer*1024) + k.outer) + (j.inner*64))*16) + k.inner)]*A[((((i*64) + k.outer)*16) + k.inner)]))
          }
        }
      }
    }
  }
}

produce C {
  for (i, 0, 1024) {
    for (j.outer, 0, 64) {
      tvm_call_packed("fill_zero", tvm_address_of(C[(((i*64) + j.outer)*16)]), n, ldw)
      for (k.outer, 0, 64) {
        tvm_call_packed("gemv_add", tvm_address_of(B[(((j.outer*1024) + k.outer)*16)]), tvm_address_of(A[(((i*64) + k.outer)*16)]), tvm_address_of(C[(((i*64) + j.outer)*16)]), 16, 16, 1024)
      }
    }
  }
}
```

Note that the first `tvm_call_packed` call (`fill_zero`) of the second loop nest (i.e., after tensorize) has arguments `n` and `ldw` which are not bound to values while the second call (`gemv_add`) uses the same arguments but they are bound to values 16 and 1024.

**Comment by derisavi-huawei** [comment]
`n` in `fill_zero` will be bound to 16 (i.e., the correct value) if I add `init = Substitute(init, vmap);`in tensorize.cpp:469. This basically performs the variable substitutions given in vmap. The same has already been done for `update` part.
The other issue is whether `ldw` should also be bound to 1024 or not, for `fill_zero`. Note that `ldw` is a parameter of `Wb` buffer (associated with tensor `w`) and not tensor `z` which are filling with zeros in the intrinsic. We either need to do the binding or emit an error message. The binding in this case happens in StorageFlatten where the buffer is bound to the tensor. Currently, since `fill_zero`  has only `z` as its AttrStmt and `ldw` is associated with `w` (and not `z`), `ldw` doesn't get bound. The question is whether we should add all *update*'s AttrStmt to 
*init* as well. 
In my opinion, we should because in some usages, fill_zero may depend on parameters of tensors other than the one initialized to zero.

**Comment by derisavi-huawei** [comment]
To add all AttrStmts to *init* as well, I guess we need to add `init = MergeNext(input_bind_nest, init)` as well at tensorize.cpp:469. @tqchen, can you please comment? If it makes sense, I'll send a patch. Thx.

**Comment by tqchen** [comment]
I think it makes sense, to make sure the bind size pass through. However, this approach will still break things when we compute the input within reduction loop(thus they are not available to init loop).

**Comment by derisavi-huawei** [comment]
I don't understand your second sentence. 
1) Do you mean currently working things will break? Or some cases that don't work now will keep not working after the change?
2) What do you mean by "compute the input within reduction loop"? Maybe a small example clarifies it.

**Comment by tqchen** [comment]
if the reduction loop becomes something like

```c++
fill_zero(C)
for k in reduction_rang:
    alloc A[16]
    some_tensor_op(C, A)
```

A is only available within the reduction loop
