### ISSUE TITLE
problem in test_cudnn

### ISSUE THREAD

**Issue by solin319** [dmlc/tvm#691]
We downloaded the current tvm today, and meet a problem in test_cudnn.
llvm-version:5.0.0
cuda-version:9
cudnn-version:7

llvm-5.0.0.src/lib/IR/Type.cpp:619: static llvm::PointerType* llvm::PointerType::get(llvm::Type*, unsigned int): Assertion `isValidElementType(EltTy) && "Invalid type for pointer element!"' failed.
Aborted (core dumped)

Does this problem caused by llvm-5.0?

**Comment by solin319** [comment]
We changed the llvm to 4.0.1, but the problem was not solved.
 llvm-4.0.1.src/lib/IR/Type.cpp:619: static llvm::PointerType* llvm::PointerType::get(llvm::Type*, unsigned int): Assertion `isValidElementType(EltTy) && "Invalid type for pointer element!"' failed.
Aborted (core dumped)

@tqchen

**Comment by tqchen** [comment]
sorry for the delayed action, it takes a bit time to find a reproducible code. should be fixed by https://github.com/dmlc/tvm/pull/753
