### ISSUE TITLE
Can tvm dump IR for each pass ?

### ISSUE THREAD

**Issue by xqdan** [dmlc/tvm#693]
Can we dump IR into different file for each pass in build, it would be helpful to debug and tune.

**Comment by derisavi-huawei** [comment]
I think this is a very good idea. I have seen it in all mature compilers. I don't think there is infrastructure to do this in TVM at this time. We may need to add a C++ base class for all passes and we use it to do common things like dumping IR, time measurement for each pass, etc.

**Comment by tqchen** [comment]
You can simply do at each phase which gives you the dump

**Comment by xqdan** [comment]
That's how I dump right now, however as @derisavi-huawei said, we should build a powerful IR dump.
```
+++ b/python/tvm/build_module.py
@@ -323,6 +323,7 @@ def build(sch,
             func = ir_pass.ThreadSync(func, "shared")
             warp_size = target.thread_warp_size
             func = ir_pass.LowerThreadAllreduce(func, warp_size)
+            print(func.body)
             fsplits = [s for s in ir_pass.SplitHostDevice(func)]
             fhost.append(fsplits[0])
             for x in fsplits[1:]:
```

**Comment by tqchen** [comment]
insert print in here serves the purpose for now as it is the most straight forward way. There is also a build_add_pass in build config which allows you to add dump pass to the build

**Comment by tqchen** [comment]
going to close this for now, as the optional callback function already enables this

**Comment by xqdan** [comment]
@tqchen callback function, do you mean add_lower_pass in lower? 
```
cfg = BuildConfig.current
    add_lower_pass = cfg.add_lower_pass if cfg.add_lower_pass else []
    lower_phase0 = [x[1] for x in add_lower_pass if x[0] == 0]
    lower_phase1 = [x[1] for x in add_lower_pass if x[0] == 1]
    lower_phase2 = [x[1] for x in add_lower_pass if x[0] == 2]
    lower_phase3 = [x[1] for x in add_lower_pass if x[0] > 2]
```
But what I want is like this, dumping ir for each pass, is there a better way to do this in tvm?
```
+def static_vars(**kwargs):
+    def decorate(func):
+        for k in kwargs:
+            setattr(func, k, kwargs[k])
+        return func
+    return decorate
+
+@static_vars(num = 0)
+def save_ir(_str, stmt):
+    save_ir.num += 1
+    name = str(save_ir.num)+ "_"+_str + ".ir"
+    with open(name, 'w') as f:
+         print >> f, stmt

 def lower(sch,
           args,
@@ -209,19 +222,27 @@ def lower(sch,
     # Phase 0
     bounds = schedule.InferBound(sch)
     stmt = schedule.ScheduleOps(sch, bounds)
+    save_ir("ScheduleOps" , stmt)
     stmt = ir_pass.InjectPrefetch(stmt)
+    save_ir("InjectPrefetch" , stmt)
```

**Comment by tqchen** [comment]
add your printer as a  callback function for add_lower_pass that runs the print and return the identical stmt, this will print out the result under certain phase.

If you want more in-depth hacking, hack up a lower function that does so is easier than simply add an official option to do so.

**Comment by xqdan** [comment]
the way i'm thinking is add save_ir in convert_to_tvm_func or cfun, check if this is a pass call, add a save_ir from them,
would this work for my case?

maybe the best way is just add dump function in each pass in c++, and control the dump via flags.

**Comment by tqchen** [comment]
Adding such feature create additional lines without creating additional benefit, as you can already do so for debug purpose by just modifying the python script

**Comment by tqchen** [comment]
to make use of ```add_lower_pass```, do 

```python
def print_ir(stmt):
     print logic here
     return stmt

# the following code insert a print pass at stage 0
with tvm.build_config(add_lower_pass=[(0, print_ir)]):
    tvm.lower(...)
```

**Comment by tqchen** [comment]
IR dumping is useful, we prefer to do it in a composable way. So instead of have a bulk API that have a dump option, just use callback function or simply modify the lower script to insert the inspection we need at right place

**Comment by xqdan** [comment]
@tqchen I have a patch to do dumping as the compiler way, and I'm asking for your advice for it,

The way i'm trying is to dump for each ir_pass call, dumping files i got are like,
```
10_Simplify_ir.cc                12_RemoveNoOp_ir.cc           14_MakeAPI_ir.cc        2_StorageFlatten_ir.cc     4_LoopPartition_ir.cc  6_InjectVirtualThread_ir.cc  8_StorageRewrite_ir.cc
11_LowerStorageAccessInfo_ir.cc  13_RewriteUnsafeSelect_ir.cc  1_InjectPrefetch_ir.cc  3_CanonicalSimplify_ir.cc  5_VectorizeLoop_ir.cc  7_InjectDoubleBuffer_ir.cc   9_UnrollLoop_ir.cc 
```
there are some TODO work,
1, only stmt type return pass should be dumped, 
2, can the path work for 'add_lower_pass'?
3, passes in c++ should have the same functionality, need to look into
4, need a flag to control dumping or not for each lower/build

```
diff --git a/python/tvm/_ffi/_ctypes/function.py b/python/tvm/_ffi/_ctypes/function.py
index ec278bc..36efdf0 100644
--- a/python/tvm/_ffi/_ctypes/function.py
+++ b/python/tvm/_ffi/_ctypes/function.py
@@ -148,7 +148,7 @@ def _make_tvm_args(args, temp_args):
 
 class FunctionBase(object):
     """Function base."""
-    __slots__ = ["handle", "is_global"]
+    __slots__ = ["handle", "is_global", "pass_name"]
     # pylint: disable=no-member
     def __init__(self, handle, is_global):
         """Initialize the function with handle
@@ -163,6 +163,7 @@ class FunctionBase(object):
         """
         self.handle = handle
         self.is_global = is_global
+        self.pass_name = ''
 
     def __del__(self):
         if not self.is_global:
diff --git a/python/tvm/_ffi/function.py b/python/tvm/_ffi/function.py
index b89da71..92d701e 100644
--- a/python/tvm/_ffi/function.py
+++ b/python/tvm/_ffi/function.py
@@ -233,10 +233,18 @@ def list_global_func_names():
         fnames.append(py_str(plist[i]))
     return fnames
 
-
-def _get_api(f):
+pass_idx = 0
+def dump(pass_name, stmt):
+    if pass_name != '':
+        global pass_idx; pass_idx += 1
+        name = str(pass_idx) + "_" + pass_name + "_" + "ir.cc"
+        with open(name, 'w') as f:
+             print >> f, stmt
+
+def _get_api(f, pass_name=''):
     flocal = f
     flocal.is_global = True
+    flocal.pass_name = pass_name
     def my_api_func(*args):
         """
 
@@ -252,7 +260,10 @@ def _get_api(f):
         value : int, float, None, Node or Function
         The result of the API function call.
         """
-        return flocal(*args)
+        ret = flocal(*args)
+        dump(flocal.pass_name, ret)
+        return ret
+
     return my_api_func
 
 def _init_api(namespace):
@@ -278,10 +289,11 @@ def _init_api(namespace):
             fname = name[len(prefix)+1:]
             target_module = module
 
+        pname = fname if prefix == "ir_pass" else '' 
         if fname.find(".") != -1:
             continue
         f = get_global_func(name)
-        ff = _get_api(f)
+        ff = _get_api(f, pname)
         ff.__name__ = fname
         ff.__doc__ = ("TVM PackedFunc %s. " % fname)
         setattr(target_module, ff.__name__, ff)
```

**Comment by tqchen** [comment]
PackedFunc is more than pass name and is used to support other features. I think given that the print and callback can already achieve this feature and based on principle of occam's razor, we do not want to introduce this officially

**Comment by xqdan** [comment]
Actually, print stmt is not the same as **dumping IR for each pass**, which is very important and fundamental  feature for a mature compiler. you can checkout gcc or llvm, it's easy for a compiler develop to dump ir for all passes or any specific pass, we should do the same thing in tvm.

see this link below, flags to control dumping IR in gcc. BTW, rtl  is backend IR in gcc. 
https://gcc.gnu.org/onlinedocs/gcc/Developer-Options.html#Developer-Options

**Comment by tqchen** [comment]
I agree it is important to be able to quickly inspect and look into what is happening.

As I explained in this thread we can simply insert dumping function or callback(as ```add_lower_pass```) into the stage to do the dump.  Adding dump into python statement achieves the same thing.

So my point is API already support this it does not make sense to complicate the API to specifically add another dump support.

**Comment by tqchen** [comment]
I think a better approach might be add document to docs/dev to explain how to quickly add dump decorator into the functions in tvm.ir_pass by modifying things in build_module.py and ```add_lower_pass```, that is more important than adding API.

If we really want to do it programmatically, such functionality do not have to affect how current api is implemented. Instead, we could provide a decorator function that inplacely replace the functions under certain namespace like tvm.ir_pass,  something like the following example (everything happens in debug and inject things direct into the location)

```python
# decorate a single function
with tvm.debug.add_ir_dump(tvm.ir_pass.InjectPrefetch):
     # everything
# recover the function

# decorate everything under tvm.ir_pass
with tvm.debug.add_ir_dump(tvm.ir_pass):
     # everything
# recover the function    
```

**Comment by xqdan** [comment]
I think add lower pass is still not the same as dumping for each pass. 
I've considered the way in your latest comment, you need to modify all the pass caller in the lower function, so I tried to find a unified point.
Anyway, I can try your solution. thanks

**Comment by xqdan** [comment]
also I think stuff like dump or useful debug functions should be in tvm rather than let developers hack it locally. it would be crazy for compiler developers if we don't have this in gcc or llvm.

**Comment by tqchen** [comment]
Since it is only three lines of python code, it won't make that much of difference, as long as it is properly documented. Having the injection based method also works fine and do not touch the original namespace.

PackedFunc is more than pass functions, it is used for things like executions, decorating that is not a very good choice.

**Comment by sirish-cadence** [comment]
@xqdan @derisavi-huawei 
Did you guys add dump functions (like llvm or glow compiler)  regarding this conversation? Without those functions, it's very tidious to run TVM undergdb and peek thorugh functions/expressions etc.
