### ISSUE TITLE
Support FP16 in CUDA

### ISSUE THREAD

**Issue by abergeron** [dmlc/tvm#699]
This is because the "half" type doesn't exist in cuda.

The options to make this work somewhat painlessly are:
  1) Only support float16 for storage not computation.  This would have us create a struct to represent float16 and some extra ops/functions to convert to and from float32.
  2) Masquerade as a native type by making a class that overloads the typical operations and uses the builtin cuda functions to make this work.

I think we should support option 1, mostly because it's less work and can always be extended to option 2 later.

I'm willing to work on this since I already did similar work elsewhere, but I want to make sure it's ok with the rest of the team here.

**Comment by tqchen** [comment]
Thanks @abergeron  this makes sense. I agree that having a buildin function to do limited overloading makes sense here.

**Comment by abergeron** [comment]
So I'll start work on option 1 then.

**Comment by abergeron** [comment]
I have something that woks if you enable the nvcc callback to compile.

The only problem with nvrtc is that it doesn't find the cuda_fp16.{h,hpp} headers.  In the previous project we worked around that by embedding the 2-3 functions that we wanted for conversion, but that did limit our options.  It also puts the burden of maintenance on us if we embed the functions and it's a lot of code if we want the full replacement class (which is provided by nvidia in those headers).

I'm wondering if you want to go this way, of you prefer to require the nvcc callback for now.

Also, another issue is that we might want to separate the float16 for storage only and float16 for storage and compute.  It seems there are issues with float16 for compute in many models due to the severely reduced precision.  The nvidia class seems to do float16 storage and compute.

**Comment by tqchen** [comment]
as long as we do ```data_fp16.astype("float32")```, which forces a cast to fp32, we should be able to do 32 bit reduction

**Comment by abergeron** [comment]
Also to really benefit from the memory savings of doing float16 for storage, you have to make sure that the casts are fused with whatever operation is performed.

This also affects some other things like dot product.  cuBLAS gives us a number of options ranging from full float16 compute to cast and float32 compute.  We have to establish the semantics we want for the float16 data type to be able to make these choices correctly.

So, yes technical problems have some solutions, but if we provide a inconsistent interface, it's not really usable for clients and that is a problem.

**Comment by tqchen** [comment]
The general guideline is to not do implicit cast, and leave the choice to the users. To support mixed precision operation. 

Here is an example to show how we can do mixed precision sum

```python
x = tvm.placeholder((m, n), dtype="float16")
k = tvm.reduce_axis((0, n))
res = tvm.compute((m), lambda i:tvm.sum(x[i, k].astype("float32") , k)) 
```

To store things back as fp16, just add a truncation stage afterwards. They are masked as elem-wise, so will be automatically fused to the compute.

```python
x = tvm.placeholder((m, n), dtype="float16")
k = tvm.reduce_axis((0, n))
res = tvm.compute((m,), lambda i:tvm.sum(x[i, k].astype("float32") , k)) 
res_final = tvm.compute((m,), lambda i: res[i].astype("float16"))
```

These choices are needed to make proper API for topi library, for example specify the output dtype for certain operation, to indicate it is mixed precision

**Comment by abergeron** [comment]
Ok, I'll check up on how casting works then.

**Comment by tqchen** [comment]
supported by #1413
