### ISSUE TITLE
module get source output in C

### ISSUE THREAD

**Issue by taknevski** [dmlc/tvm#703]
Hi,
Is there a way to output C code in the module get source function? I see the supported targets are cuda, llvm, metal,opencl , etc.. I just want to view the c code as I incrementally apply the schedule.

**Comment by tqchen** [comment]
you can simply print out the ir by doing things like
```
print(tvm.lower(s, args, simple_mode=True))
```

see examples here http://docs.tvmlang.org/tutorials/language/schedule_primitives.html#sphx-glr-tutorials-language-schedule-primitives-py
