### ISSUE TITLE
schedule conv for different size

### ISSUE THREAD

**Issue by xqdan** [dmlc/tvm#706]
Hi all,

We've ran thru a net, however the performance is not good, 10 times worse than mxnet version. The main issue here is conv ops.

As you can see, the 2nd Column is the time in ms for the conv.
And we are gonna optimize them, could you guys give us any suggestions for optimization? 

![image](https://user-images.githubusercontent.com/23742050/34026795-71eb973e-e193-11e7-9e81-d4306d47cc77.png)

thanks,

**Comment by tqchen** [comment]
related issues https://github.com/dmlc/nnvm/issues/230  https://github.com/dmlc/nnvm/issues/206

**Comment by tqchen** [comment]
@Laurawly might some tips, as this question is asked a few times, maybe it makes sense to have a master reference issue where we accumulate tips, without doing this repeatively

**Comment by tqchen** [comment]
close this for now and let us open more detailed thread for per workload discussion
