### ISSUE TITLE
Problem while building tvm on Aarch64

### ISSUE THREAD

**Issue by Mani-Sadhasivam** [dmlc/tvm#707]
Hello,

I am trying to build tvm natively on an Aarch64 board (HiKey960) and found some issues. Below are the steps I have tried so far:

1. Installed LLVM to `/usr/` by compiling from source
2. copied `make/config.mk` to tvm/config.mk
3. Modified LLVM_CONFIG as `LLVM_CONFIG = /usr/bin/llvm-config`
4. make

Link to error log: https://pastebin.com/h5BT2RkX

**Comment by tqchen** [comment]
Please note that you do not have to do it, use cross compile mode instead. Build tvm on your desktop and set target compilation to be arch64

**Comment by tqchen** [comment]
see http://docs.tvmlang.org/tutorials/deployment/cross_compilation_and_rpc.html#sphx-glr-tutorials-deployment-cross-compilation-and-rpc-py

**Comment by Mani-Sadhasivam** [comment]
Ok. So, after building the tvm runtime on my device I need to build tvm on my host right? According to this section: http://docs.tvmlang.org/tutorials/cross_compilation_and_rpc.html#set-up-rpc-server-on-device 

Do I need to cross compile tvm on host as mentioned here: http://nnvm.tvmlang.org/how_to/install.html ?

**Comment by tqchen** [comment]
You can just natively build tvm on your host
