### ISSUE TITLE
cpp testcast runtime error

### ISSUE THREAD

**Issue by Vernlium** [dmlc/tvm#710]
hi guys,
I transplanted the tvm cpp testcase to our test framework,and found a runtime error:

```
[----------] 1 test from IRSIMPLIFY
[ RUN      ] IRSIMPLIFY.Basic
llt/tvm/ut/../../../nnvm/tvm/HalideIR/src/ir/IR.cpp:32:11: runtime error: left shift of negative value -2147483648
Simplify test passed
[       OK ] IRSIMPLIFY.Basic (295 ms)
```

The error occered in **tvm\tests\cpp\ir_simplify_test.cc**.

I don't know how to fix it.

**Comment by tqchen** [comment]
it would be great if you can provide a reproducible example on this. Since the original gtest based testcase seems to pass. 

you can also try to use gtest to see if the original version works well

**Comment by tqchen** [comment]
close this due to inactivity, please reopen when we have followup
