### ISSUE TITLE
Ask: TVM vs TensorRT

### ISSUE THREAD

**Issue by edmBernard** [dmlc/tvm#713]
If I understand correctly, TensorRT and TVM search to accelerate prediction. .
TensorRT optimise prediction on GPU and TVM optimised prediction on almost all platform support GPU, ARM, Mobile ...

Is there a comparison between both on GPU ?

**Comment by tqchen** [comment]
so far tvm does not yet optimizes for int8 which TensorRT is optimized for. But there are some on going effort on this, so answer is TensorRT is faster currently and we are keep improving TVM to cover optimizations used in TensorRT for all platforms

**Comment by edmBernard** [comment]
thanks for your answer

**Comment by ouceduxzk** [comment]
SO basically TVW will be a generic tensorrt, looking forward to see the new version

**Comment by austinmw** [comment]
Hi @tqchen , curious if there's any updated perspective on TVM vs. TensorRT?

**Comment by tqchen** [comment]
Some updates https://tvm.apache.org/2019/04/29/opt-cuda-quantized please feel free to followup on https://discuss.tvm.ai/
