### ISSUE TITLE
vectorize schedule primitive

### ISSUE THREAD

**Issue by taknevski** [dmlc/tvm#715]
In  tvm/src/pass/vectorize_loop.cc , I see specializations for vector multiply and add operations. Is support for fused multiply add(FMA) supported/being planned? I'm guessing llvm supports FMA code generation and that tvm has to expose the operation in the above file.

Thanks,
Anand

**Comment by tqchen** [comment]
- https://github.com/dmlc/tvm/blob/master/src/pass/lower_intrin.cc#L36 which will redirect to LLVM's FMA 
- Even without doing so, LLVM will automatically generate FMA via pattern matching so we do not have to do it in TVM

**Comment by taknevski** [comment]
Hi,
Thanks for the response.  My goal is to get FMA instructions corresponding to the reduction in convolution.
Is vectorize the right schedule primitive to try? Because I see a separate vector multiply and add generated by llvm when I call the vectorize schedule primitive in my sequence. Or maybe I should add the  intrinsic in the algorithm itself?

Thanks,
Anand

**Comment by tqchen** [comment]
can you please elaborate? for example a simple code snippet on what you want before and after transformation will put discussion into context

**Comment by taknevski** [comment]
Sure,

suppose I have the following loop nest for convolution
-- before transformation
for(n)
    for(ff)  -- filter loop blocked by Vector Length(VLEN)
        for(h)
             for(w)
                 for f
                  output[n][ff][h][w][f] = 0
                   for(c)  -- reduction loop
                       for(r)  -- reduction
                            for(s)  --reduction
                                  for(f)  --  blocked filter loop
                                         output[n][ff][h][w][f] +=   input[n][c][h+r][w+s]*weight[ff][c][r][s][f]                                      

-- I call vectorize(f)

can I get something like:
--after transformation
for(n)
    for(ff)  -- filter loop blocked by Vector Length(VLEN)
        for(h)
             for(w)
                 for f
                  output[n][ff][h][w][f] = 0
                   for(c)  -- reduction loop
                       for(r)  -- reduction
                            for(s)  --reduction
                                 //for(f) -- loop vectorized
                                      **FMA(output,  broadcast(input), weight)//broadcast input to vector length**  
                                         //output[n][ff][h][w][f] +=   input[n][c][h+r][w+s]*weight[ff][c][r][s][f]

**Comment by tqchen** [comment]
Yes, you should be able to use vectorize for this purpose.

**Comment by taknevski** [comment]
Thanks for the clarification. When I print  using get_source I see 
llvm.fmuladd.v16f32 instructions. However when I save to assembly format, it is not getting lowered to fma. Instead it is getting lowered to a multiply followed by an add.
Looks like llvm is determining that the cost of an fma is more than the combined cost of a multiply and an add or is not detecting the presence of FMA instructions

**Comment by taknevski** [comment]
Probably using the cross compile mechanism specifying the llvm target with the fma  flag would sort out this problem. I'll keep you updated.

**Comment by taknevski** [comment]
Yes, this worked, adding the appropriate target fixed the problem, able to see fma instructions
