### ISSUE TITLE
Turning off auto-unroll

### ISSUE THREAD

**Issue by taknevski** [dmlc/tvm#717]
Hi,

Is there a way to turn off automatic unroll?
I tried setting auto_unroll_max_step = 1, auto_unroll_max_depth=1,auto_unroll_max_extent=1
in the build config but it still unrolled the loops 'rx' and 'ry' with trip count 3.

batch = 128
in_channel = 4
out_channel = 4
in_size = 56
kernel = 3
pad = 1
stride = 1
vlen = 16

rco = tvm.reduce_axis((0, in_channel), name='rco')
ry = tvm.reduce_axis((0, kernel), name='ry')
rx = tvm.reduce_axis((0, kernel), name='rx')
rci = tvm.reduce_axis((0, vlen), name='rci')
 
# Compute the convolution
B = tvm.compute(
    (batch, out_channel,out_size, out_size,vlen),
    lambda nn,ff,yy, xx, vlen1: tvm.sum(
        A[nn, rco, yy * stride + ry, xx * stride + rx,rci] * W[ff,rco,ry, rx,rci,vlen1],
        axis=[ry, rx, rco,rci]),
    name='B')

....
with tvm.build_config(unroll_explicit=True, auto_unroll_max_step = 1, 
         auto_unroll_max_depth=1,auto_unroll_max_extent=1):
      func = tvm.build(s, [A, W, B], target='llvm')

Thanks

**Comment by derisavi-huawei** [comment]
Have you tried with those variables set to negative values (say, -1) instead of 1?

**Comment by taknevski** [comment]
Thanks for the response.
It does not work with negative values..
The decision to unroll seems dependent on the inner loop nest bounds. But I can't seem to control it 
via the flags

**Comment by masahi** [comment]
@taknevski You can try unroll_explicit = False

**Comment by tqchen** [comment]
Can you try to look at the IR in lowering

```python
print(tvm.lower(s, [A, W, B], simple_mode=True))
```
The unroller option only controls the TVM's unroll pass and it could be possible the decision is made later by LLVM's unroller instead

**Comment by taknevski** [comment]
Yes this is possible. What is the way to supply llvm optimization options from tvm?

**Comment by derisavi-huawei** [comment]
`build` under this:
`with tvm.target.create("llvm -mattr=+avx2"):` 
Obviously, replace that with the option of your choice.

**Comment by taknevski** [comment]
Thanks,
mattr is for target specific optimizations, If i understand correctly. But unroll might not be, so I'm wondering how to supply something like '-fno-unroll-loops'

**Comment by derisavi-huawei** [comment]
try this:
`with tvm.target.create("llvm -fno-unroll-loops"):`

**Comment by tqchen** [comment]
the option for the llvm is consistent with ```llc```

**Comment by tqchen** [comment]
close this for now as the original question is already answered (unfortunately such option is not yet available through API). Please open another issue if we want to actually bring in llvm tuning knobs
