### ISSUE TITLE
LoopPartition doesn't work for loop with constant boundary

### ISSUE THREAD

**Issue by kun-zh** [dmlc/tvm#719]
In the following case, loop partition pass doesn't work, we need to enhance it.

#n = tvm.var('n')
    n = 17
    A = tvm.placeholder((n, ), name='A')
    B = tvm.placeholder((n, ), name='B')

    T = tvm.compute((n, ), lambda i: A[i]+B[i])
    s = tvm.create_schedule(T.op)
    xo, xi = s[T].split(T.op.axis[0], factor=4)

    bounds = tvm.schedule.InferBound(s)
    stmt = tvm.schedule.ScheduleOps(s, bounds)
    print(stmt)
    stmt = tvm.ir_pass.LoopPartition(stmt)
    stmt = tvm.ir_pass.Simplify(stmt)
    print(stmt)
    assert('if' not in str(stmt.body.body.body.first))

**Comment by tqchen** [comment]
we can fix this by adding an option on whether allowing split on constant loop bound. @ZihengJiang can you look into this?

**Comment by xqdan** [comment]
I'm trying to split the outermost axis with nparts=1, then bind new outermost axis to blockIdx.x,
`def default_bind(sch):
    # bind
    out = sch.outputs[0]
    outter_stage = sch.stage_map[out] 

    if len(outter_stage.leaf_iter_vars) > 0:
        outter_axis = outter_stage.leaf_iter_vars[0]
    else:
        outter_axis = outter_stage.all_iter_vars[0]

    bx, by = sch[out].split(outter_axis, nparts=1)
    sch[out].bind(bx, api.thread_axis("blockIdx.x"))`
ok for simple cases, but failed under complex cases, when we applied split and bind in python case or in build, reports:
`/home/danxiaoqiang/davinci/nnvm/tvm/src/schedule/graph.cc:204: Check failed: start_attach Invalid Schedule: cannot find attach point iter_var(bo.outer, ) in the schedule of compute(C, 0x1d47d90)`

is there anything wrong with the way using split and bind, or is it a bug?

**Comment by xqdan** [comment]
@tqchen @kun-zh @ZihengJiang please review #732

**Comment by tqchen** [comment]
fixed by #732
