### ISSUE TITLE
Customize Host Device Split

### ISSUE THREAD

**Issue by xqdan** [dmlc/tvm#725]
Hi all,

Tvm generates kernel function based on binded axis in Cuda. However, it's a different case for accelerators which have vector or matrix instructions, because you may put a whole axis in a single core. We can reuse split and bind mechanism to do that for accelerators for now though,  is there a better way to generate host and device code for accelerators?

thanks,

**Comment by tqchen** [comment]
The only thing that need to be done is the splitHostDevice function, so you can introduce whatever boundary annotation and split pass to make it work

**Comment by xqdan** [comment]
I'm trying to split the outermost axis with nparts=1, then bind new outermost axis to blockIdx.x,
```
def default_bind(sch):
    out = sch.outputs[0]
    outter_stage = sch.stage_map[out] 

    if len(outter_stage.leaf_iter_vars) > 0:
        outter_axis = outter_stage.leaf_iter_vars[0]
    else:
        outter_axis = outter_stage.all_iter_vars[0]

    bx, by = sch[out].split(outter_axis, nparts=1)
    sch[out].bind(bx, api.thread_axis("blockIdx.x"))
```
ok for simple cases, but failed under complex cases, when we applied split and bind in python case or in build, reports:
`nnvm/tvm/src/schedule/graph.cc:204: Check failed: start_attach Invalid Schedule: cannot find attach point iter_var(bo.outer, ) in the schedule of compute(C, 0x1d47d90)`

is there anything wrong with the way using split and bind, or is it a bug of tvm?

**Comment by xqdan** [comment]
Another approach:

1, mark the outermost with pragma;
```
+def mark_kernel_axis(sch):
+    # bind
+    out = sch.outputs[0] #compute(B, 0x22bc758)
+    outter_stage = sch.stage_map[out] #stage(B, 0x22c1468)
+
+    if len(outter_stage.leaf_iter_vars) > 0:
+        outter_axis = outter_stage.leaf_iter_vars[0]
+    else:
+        outter_axis = outter_stage.all_iter_vars[0]
+
+    outter_stage.pragma(outter_axis, "device")

 def build(sch,
           args=None,
@@ -291,6 +325,7 @@ def build(sch,
     if isinstance(sch, schedule.Schedule):
         if args is None:
             raise ValueError("args must be given for build from schedule")
+        mark_kernel_axis(sch)
         flist = lower(sch, args,
                       name=name,
                       binds=binds)
```
2, split when we get pragma above
```
--- a/src/pass/split_host_device.cc
+++ b/src/pass/split_host_device.cc
@@ -148,7 +148,9 @@ class HostDeviceSplitter : public IRMutator {
  public:
   Stmt Mutate_(const AttrStmt *op, const Stmt& s) final {
     if (op->attr_key == attr::thread_extent ||
-        op->attr_key == attr::pipeline_exec_scope) {
+        op->attr_key == attr::pipeline_exec_scope ||
+        (op->attr_key == attr::pragma_scope &&
+         op->value.as<StringImm>()->value == "device")) {
       return SplitDeviceFunc(s);
     }
```

**Comment by kun-zh** [comment]
Can we have a way to split the host and device code when there is no the outermost axis?  For example, there are produce A and B, and I don't want to use "compute _at". But I want to put A and B into one kernel function and run it in one core.

**Comment by tqchen** [comment]
i think a best way would still have an auto detection pass that detect a block of code belongs to certain device via a recursive algorithm like lift scope, then mark the scope as device which do not need users's involvement

**Comment by xqdan** [comment]
auto detection is a better way, i can try. 
also I have some questions,
1, auto detection pass is just for customize host device split, or also for cuda?
2, how do generate device code for blocks? IMO, if we have some independent blocks, we may generate device code for each for better parallelism;  if we have some blocks with dependence, we may generate just one device code. is this the thing we should consider?

**Comment by tqchen** [comment]
GPU code split on thread launch boundary is sufficient. option 2 could be interesting, but not necessary in most cases of interest in turns of priority.

**Comment by xqdan** [comment]
I see, we can have a basic auto detection pass first

**Comment by xqdan** [comment]
@tqchen I have a simple version now, just insert a attr in the ProducerConsumer's body, work well for @kun-zh 's scenario, I'm not familiar with IR at this time, so I'm asking for your advice here, are there any complex scenario we should consider?

the pass is simple
```
class DetectDevice : public IRMutator {
 public:
  DetectDevice(){}

  Stmt Detect(Stmt stmt) {
    stmt = Mutate(stmt);
    return stmt;
  }

  Stmt Mutate_(const ProducerConsumer* op, const Stmt& s) final {
    Stmt body = AttrStmt::make(make_zero(Int(32)),
                               ir::attr::pragma_scope,
                               StringImm::make("device"),
                               op->body);
    Stmt stmt = ProducerConsumer::make(op->func, op->is_producer, body);
    return stmt;
  }
};

Stmt DeviceMark(Stmt stmt) {
  return DetectDevice().Detect(stmt);
}
```
I place this pass in lower_phase0 for our target.

when I run this case below, we can get two kernels
```
import tvm

def test_reduce_prims():
    n = tvm.var('n')
    m = tvm.var('m')
    A = tvm.placeholder((n, m), name='A')
    R = tvm.compute((n, ), lambda i: tvm.select((i > 1), 1, 0), name='R')
    k = tvm.reduce_axis((0, m))
    B = tvm.compute((n,), lambda i: tvm.sum(A[i, k], axis=k, where=(R[i]==1)), name='B')
    # schedule
    s = tvm.create_schedule(B.op)
    # create iter var and assign them tags.
    num_thread = 1
    xo, xi = s[B].split(B.op.axis[0], factor=num_thread)
    #s[B].bind(xo, tvm.thread_axis("blockIdx.x"))
    #s[B].bind(xi, tvm.thread_axis("threadIdx.x"))
    #s[R].compute_inline()
    freduce = tvm.build(s, args=[A, B],
                           target="cuda", target_host="stackvm",
                           name="myreduce")
    print(freduce.imported_modules[0].get_source())

test_reduce_prims()
```

**Comment by tqchen** [comment]
This will essentially tag everything as device, which is fine for specific usecase you consider when everything needs to fit into one stage. It is not as general if there is a need to divide the workload into a few kernel calls, I would recommend to use this as workaround for now

**Comment by xqdan** [comment]
I see. we might have a need to the workload into a few kernel calls, but no usecase for now. we'll improve this pass once we get usecases. I'll keep it locally until things become clear.
