### ISSUE TITLE
schedule.normalize() causes problem for subsequent tensorize call

### ISSUE THREAD

**Issue by derisavi-huawei** [dmlc/tvm#733]
Consider the following test case. It's a simple for loop and we are trying to tensorize two parts of the code. After each `tensorize()` we also call `normalize` on the schedule.

```python
import tvm

################ define intrinsic #############################                                     
def intrin_mul (n, dtype):
    A = tvm.placeholder((n,), dtype, name='A')
    C = tvm.compute((n,), lambda i: A[i]*4, name='C')
    def intrin_func(ins, outs):
        A = ins[0]
        C = outs[0]
        return tvm.call_packed("MUL",
                               A.data
                               )

    with tvm.build_config(offset_factor=1):
        return tvm.decl_tensor_intrin(C.op, intrin_func)


def intrin_load(m, n, dtype):
    A = tvm.placeholder((m, n), dtype, name='A')
    A_local = tvm.compute((m, n), lambda i, j: A[i, j], name='A_local')
    def intrin_func(ins, outs):
        A = ins[0]
        A_local = outs[0]
        A_local_ptr = A_local.access_ptr("w")
        return tvm.call_packed("load",
                               A.data,
                               A_local_ptr)

    with tvm.build_config(offset_factor=4):
        return tvm.decl_tensor_intrin(A_local.op, intrin_func)
###################### algorithm begin ###########################

def gemm(dtype):

    M = 256
    N = 256
    A = tvm.placeholder((M, N), dtype, name = 'A')
    C = tvm.compute(
        (M, N),
        lambda x, y: (A[x, y]*4),
        name = 'C')

    # Default schedule
    s = tvm.create_schedule(C.op)

    ##############  buffer mapping ######################
    subA = s.cache_read(A, "global", [C])
    subC = s.cache_write(C, "global")
    ###############  buffer mapping ######################
    s[subC].compute_at(s[C], C.op.axis[0])
    s[subA].compute_at(s[C], C.op.axis[0])

    print(tvm.lower(s, [A, C], simple_mode=True))

    # tensorize load
    loadA = intrin_load(1, 256, dtype)
    s[subA].tensorize(subA.op.axis[1], loadA)
    ############### If I comment out the following normalize() call, this test case works properly.
    s = s.normalize()
    print(tvm.lower(s, [A, C], simple_mode=True))

    # tensorize mul
    gemm_tensor = intrin_mul(256, dtype)
    s[subC].tensorize(subC.op.axis[1], gemm_tensor)
    s = s.normalize()
    print(tvm.lower(s, [A, C], simple_mode=True))


gemm('float32')
```

If I run the above test case as is, I'll get the following error message during the second python `tensorize` call:
```
Traceback (most recent call last):
  File "../1/huawei/examples/test_gemm_reorder2.py", line 68, in <module>
    gemm('float32')
  File "../1/huawei/examples/test_gemm_reorder2.py", line 63, in gemm
    s[subC].tensorize(subC.op.axis[1], gemm_tensor)
  File "/home/s00327669/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/schedule.py", line 502, in tensorize
    _api_internal._StageTensorize(self, var, tensor_intrin)
  File "/home/s00327669/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/function.py", line 255, in my_api_func
    return flocal(*args)
  File "/home/s00327669/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/s00327669/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/base.py", line 62, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [15:44:52] src/schedule/schedule_lang.cc:30: Operate on iter var iter_var(y.c, Range(min=0, extent=256))that has already been splitted
```

Now if I comment the first call of `normalize()` (shown in the code above), both `tensorize` calls are successfully completed and I get the following lowered code at the end:
```
// attr [A.global] storage_scope = "global"
allocate A.global[float32 * 1 * 256]
// attr [C.global] storage_scope = "global"
allocate C.global[float32 * 1 * 256]
produce C {
  for (x, 0, 256) {
    produce A.global {
      tvm_call_packed("load", A, tvm_address_of(A.global[0]))
    }
    produce C.global {
      tvm_call_packed("MUL", A.global)
    }
    for (y, 0, 256) {
      C[((x*256) + y)] = C.global[y]
    }
  }
}
```

I tried to debug it but I couldn't get to the bottom of it. Here is my observations though, in case someone wants to pick it up from here:
The chains of calls are `Stage::tensorize` -> `UpdateIterVarAttr` -> `FindLeafVar` -> `FindNodeRef` (all in schedule_lang.cc). When in `FindLeafVar` [link](https://github.com/dmlc/tvm/blob/master/src/schedule/schedule_lang.cc#L26), the method tries to find `v` in `leaf_vars` but it can't even though `leaf_vars` has a variable with the same name as the name of the one pointed to by `v`. Also, `all_vars` contains pointers to variables with the same names as variables pointed to by `leaf_vars` but the pointer values are different and pointer value of `v` matches one variable pointer in `all_vars`. 
My guess is that there are two copies of the variables (one set in `leaf_vars` and one set in `all_vars`), and therefore, `FindLeafVar` may not always work correctly because it works by comparing pointer values (as opposed to comparison by content). I'm not sure though and therefore, not sure how to fix it. @tqchen, any ideas?

**Comment by xqdan** [comment]
I've got this,  normalize() is called in lower by default, seems normalize() can not be called twice, don't know why

**Comment by tqchen** [comment]
after normalize is called,(as well as cache write/read). The dataflow get rewritten. So you cannot use the axis of the original op(since they belong to original one).  ```s[Tensor].op``` may no longer be the same as ```Tensor.op```. This decision is made because we try to make data structures immutable, and if the dataflow get rewritten, the op correspond to a stage will change to a new one

Use ```s[Tensor].op.axis``` instead to give you the correct access

**Comment by derisavi-huawei** [comment]
@tqchen, I understand your point but it doesn't seem that's the culprit in this case. When I changed all instances of `Tensor.op.axis` to `s[Tensor].op.axis`, I still get the same error message. I still observe the same symptoms I explained in the first comment above.

**Comment by derisavi-huawei** [comment]
@tqchen, I digged more. Seems like the problem happens in `RebaseNonZeroMinLoop()` (which is called by `Schedule::normalize()`). Here is the initial part of `RebaseNonZeroMinLoop()`.
```c++
void RebaseNonZeroMinLoop(const Schedule& sch) {
  std::unordered_map<IterVar, IterVar> rebase_map;
  for (Stage s : sch->stages) {
    if (s->attach_type == kInlinedAlready) continue;

    auto root_iter_vars = s->op->root_iter_vars();
    ArrayNode* leaf_vars = s->leaf_iter_vars.CopyOnWrite();
    for (IterVar iv : root_iter_vars) {
      size_t idx = FindNodeRef(leaf_vars, iv);
      auto it  = s->iter_var_attrs.find(iv);
      // don;t need to rebase path that are binded.
      if (it != s->iter_var_attrs.end() &&
          (*it).second->bind_thread.defined()) {
        continue;
      }
      if (idx < leaf_vars->data.size()) {
        // insert rebase
        IterVar rebased = IterVarNode::make(
            Range(), iv->var.copy_with_suffix(""), iv->iter_type);
        s->relations.push_back(RebaseNode::make(iv, rebased));
        if (s->iter_var_attrs.count(iv)) {
          s->iter_var_attrs.Set(rebased, s->iter_var_attrs.at(iv));
        }
        leaf_vars->data[idx] = rebased.node_;
        rebase_map[iv] = rebased;
      }
    }
  }
/* the rest of the method */
}
```

For the specific test case above, what happens is that before `RebaseNonZeroLoop`, there is a stage (call it `s1`) in which both `leaf_iter_vars` and `all_iter_vars` refer to the same pair of `IterVar`s.
After the loop above that goes over the stages, stage `s1` is modified as follows: Each of the two `IterVar`s of `leaf_iter_vars` are replaced by another newly created `IterVar` ([see this line](https://github.com/dmlc/tvm/blob/8a3dbd7971a3d7df7c3a728d18c7c6124bf68989/src/schedule/schedule_dataflow_rewrite.cc#L258). However, the two `IterVar`s in `s1.all_iter_vars` stay as before. Therefore, `all_iter_vars` end up referring to two different pairs of `IterVar`s causing problems later on.
It seems to me that the solution is to make the `IterVar` replacement everywhere in the stage when we replace it in `leaf_iter_vars`. How can this be done properly?

This is related to #738 in the sense that we have stale `IterVar`s here and there, AFAIK, we have stale tensors.

**Comment by derisavi-huawei** [comment]
updating only `all_iter_vars` is not enough. I think we have to update all references to the old `IterVar`, in that stage, needs to be replaced by the new `IterVar`. This includes updating all references under `s.op`.

**Comment by tqchen** [comment]
can you try change 
```s[subC].tensorize(subC.op.axis[1], gemm_tensor) ->s[subC].tensorize(s[subC].op.axis[1], gemm_tensor)```

**Comment by derisavi-huawei** [comment]
I did make that change, as I mentioned in of the comments above. But it didn't resolve the problem. I double checked now.

**Comment by derisavi-huawei** [comment]
As far as I can tell, the tensor is not stale but `tensor.op.axis` is referring to stale `IterVar`s.  `tensor.op.axis` refer to the same thing as `s[tensor].op.axis`

**Comment by tqchen** [comment]
OK, I think i know what is going on. The normalize have the same effect as 
```python
rebased_axis = s[subC].rebase(s[subC].op.axis[1])
```

The further operations(tensorization) need to be acting on ```rebased_axis``` instead.  Avoid calling normalize or explicit calling rebase (to get handle of the axis) will resolve the problem

**Comment by tqchen** [comment]
I think a good way is always avoid calling normalize manually as it will be called right before we do lowering, it might be good to add this to the document

**Comment by derisavi-huawei** [comment]
Fair enough regarding the workaround. Thanks.
However, is a stage in a "well-defined" state if it has multiple copies of the same IV and different parts of the data structure of the stage point to different copies? In other words, do later processing of schedule (i.e., after `normalize()`) make any assumption that is not satisfied by the state mentioned above? If the answer is yes, we need to fix `normalize()` or the assumptions made by later processing. If the answer is no, we can leave things as is and suffice to avoiding calling `normalize()`.

**Comment by tqchen** [comment]
The normalize is a sugar to do automatic schedule transformation, and such transformation that calls rebase is well defined. The lowering procedure only looks at the result schedule relation tree, which is always well defined
