### ISSUE TITLE
How to reuse the buffer

### ISSUE THREAD

**Issue by libing4752** [dmlc/tvm#735]
How can I reuse the same local buffer in different cache_read or cache_write, exp:
for i: 0 to 100
    A[i] = A[i] + 3 
the src buffer and the dst buffer are the same one.

**Comment by tqchen** [comment]
This is done through storage rewrite that analyze the life cycle of the buffers, instead of manually forcing them. Currently we did not yet do inplace analysis, which means the input and output cannot yet alias, we plan to add it for elementwise ops

**Comment by derisavi-huawei** [comment]
@tqchen, IMHO, if it's in the plans, is this documented somewhere, e.g., in its own open issue or part of another open issue?

**Comment by tqchen** [comment]
@derisavi-huawei I think that deserves its own issue for tracking the progress.

**Comment by kun-zh** [comment]
@tqchen Do u has the schedule to add it for elementwise ops? The issue is critical because the buffer size on the chip is very limited, we want to can reuse the buffer inplace and not allocate a new one.

**Comment by tqchen** [comment]
need an update to storage_rewrite pass to be able to detect inplace safe op and reuse buffers

**Comment by kun-zh** [comment]
OK, if u have no time recently, I can investigate the issue. How can it be limited in elementwise ops? User decided by an option?

**Comment by tqchen** [comment]
move to https://github.com/dmlc/tvm/issues/746 This is an blocking issue on my side, so i will likely fix it this week

**Comment by kun-zh** [comment]
Great!

**Comment by tqchen** [comment]
it is not limited to element-wise ops, but we need to be able to prove that sharing is safe. For example, sharing output buffer with relu is safe
