### ISSUE TITLE
tensorize's limitation with a computation containing tvm_if_then_else

### ISSUE THREAD

**Issue by derisavi-huawei** [dmlc/tvm#737]
This is to document what is, I believe, a limitation of current tensorize implementation. In short, when you have a computation that contains conditional statements (such as tvm_if_then_else), (depending on the conditions) tensorize won't be able to pattern match the computation and it gives an error. Here is a test case (simplified from a more useful and complicated code), and what I think is the reason behind this limitation:
```python
import tvm
dtype = "float32"

def intrinsic():
    x = tvm.placeholder((5, 5), dtype, name='x')
    y = tvm.compute((9, 25),
        lambda i,j: tvm.select(
                    tvm.all(j+i >= 1, j+i < 6,
                            j+2*i >= 1, j+2*i < 6),
                    x[j+i - 1, j+2*i - 1],
                    tvm.const(0, dtype)))

    def ifunc(ins, outs):
        xx, = ins
        zz = outs[0]
        return tvm.call_packed("intrinsic", xx, zz)

    with tvm.build_config(offset_factor=2):
        return tvm.decl_tensor_intrin(y.op, ifunc)

A = tvm.placeholder((5, 5), dtype, name='A')
B = tvm.compute((9, 25),
    lambda i,j: tvm.select(
                tvm.all(j+i >= 1, j+i < 6,
                        j+2*i >= 1, j+2*i < 6),
                A[j+i-1, j+2*i-1],
                tvm.const(0, dtype)))

s = tvm.create_schedule(B.op)
x,y = B.op.axis
bt = intrinsic()
s[B].tensorize(x, bt)
s = s.normalize()
print(tvm.lower(s, [A, B], simple_mode=True))
```
And the error is 
```
tvm._ffi.base.TVMError: [11:33:54] src/op/tensorize.cc:318: Check failed: Equal(lhs, rhs) Failed to match the compute with TensorIntrin tensor_intrin's declaration  
provided= select((((((1 - i) <= j) && (j < (6 - i))) && ((1 - (i*2)) <= j)) && (j < (6 - (i*2)))), x((i + j),       ((i*2) + j)), 0.000000f), 
intrin=   select((((((1 - i) <= j) && (j < (6 - i))) && ((1 - (i*2)) <= j)) && (j < (6 - (i*2)))), x(((i + j) - 1), (((i*2) + j) - 1)), 0.000000f)
```
Note how the indices of `x` in `provided` and `intrin` are off by just 1.
In tensorize, TVM needs to calculate the part (domain) of `A` used by `B`. In reality, because of the conditions given in `tvm.all`, the domain of `A` used by `B` is [0,4], [0,4] along its first and second dimensions, respectively. However, currently TVM doesn't (and I think can't) take those conditions into consideration. Therefore, it thinks the domain of `A` is [-1,31], [-1,39], and therefore, the rest of the computations will go wrong, including matching an intrinsic with an algorithm. That means that tensorize won't work correctly in the presence of if_then_else statements. The 1 offsets mentioned above are coming from the lower bound of the domain calculated for `A`, that is, -1 on both dimensions.

**Comment by tqchen** [comment]
For padded copy pattern, there is a copy  intrinsic pass to over come this limitation

**Comment by tqchen** [comment]
These are the cases where a different kind of pattern detector can benefit from. Having conditions in the domain is hard because it is hard to define exactly what is the domain of consideration. Most of such cases are padding operation in convolution.

This is temporary resolved by a specialized template detector for detecting padded copy pattern, which can be found in pass inject_copy_intrin.cc

**Comment by tqchen** [comment]
close this for now as the copy pattern detector serves as a alternative
