### ISSUE TITLE
Process 'command 'sh'' finished with non-zero exit value 127

### ISSUE THREAD

**Issue by nightfox8** [dmlc/tvm#739]
Hello,

Trying to run this demo on android
I have compiled TVM4J and installed that in local maven repo.
After that when I tried to run that on Android I am getting the below error,

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:buildJni'.
> > Process 'command 'sh'' finished with non-zero exit value 127

Can anyone help me with this?

**Comment by zhyj3038** [comment]
same problem
