### ISSUE TITLE
Making python schedules available to C++

### ISSUE THREAD

**Issue by alex-weaver** [dmlc/tvm#749]
It looks like many of the schedules in TOPI are implemented with python - what would be the best way to make these available to C++? They could be ported directly but that would increase maintenance work - is there a way to make schedules serializable?

**Comment by tqchen** [comment]
python is mainly for quick prototyping purpose. Once we have a clear idea about what they should look like, we can start port most of them to C++, and just call the c++ function from python side.

Currently, I feel that most operators except for those convolutions can already be safely ported to c++

**Comment by alex-weaver** [comment]
Ok that makes sense. I'm interested in contributing to this - looking over the TOPI code I have one question: I can't see any C++ equivalent to the target.generic_func annotation for picking target-specific specializations. How should this be handled in C++ ops?

**Comment by tqchen** [comment]
I need to put more thought into how to define proper target and dispatching system in c++. In the meanwhile, most of the declaration(except for conv2d) are target generic.

The target-specific schedule functions can also be readily added and the topi can work by calling ```topi::cuda::schedule_conv2d```

The generic dispatching system could be an addition to these afterwards
