### ISSUE TITLE
How to set the llvm-config & cuda  path for windows

### ISSUE THREAD

**Issue by Arthur-Shi** [dmlc/tvm#754]
I know on ubtuntu, LLVM_CONFIG = /path/to/bin/llvm-config

But I have no idea about how to set on windows.

I tried to set : LLVM_CONFIG = C:\llvm\build\tools\llvm-config 

And I cannot run get_started.py successfully.

tvm._ffi.base.TVMError: [15:20:55] C:\tvm\src\codegen\codegen.cc:27: Check failed: bf != nullptr Target llvm is not enabled

**Comment by Arthur-Shi** [comment]
And I think that maybe the setting for cuda for windows is wrong, too.
CUDA_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0

How to set CUDA path in windows.

**Comment by tqchen** [comment]
for windows, use CMake instead of the makefile, which do not require you to setup these path

**Comment by Arthur-Shi** [comment]
@tqchen  But I met the problem.

I can import tvm/nnvm successfully but I cannot use CUDA & LLVM. 

What should I do?

**Comment by tqchen** [comment]
enable CUDA and LLVM on your cmake, see https://github.com/dmlc/tvm/blob/master/CMakeLists.txt#L19

**Comment by Arthur-Shi** [comment]
Thank you. 

tvm_option(USE_CUDA "Build with CUDA" ON)
tvm_option(USE_LLVM "Build with LLVM" ON)

and cmake
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0 (found version "8.0")
-- Build with CUDA support
-- Build with RPC support...
-- Build with Graph runtime support...
-- Build with LLVM 7.0.0svn
-- Set TVM_LLVM_VERSION=70
-- Configuring done
-- Generating done
-- Build files have been written to: C:/nnvm/tvm/build

The problem is when building with Visual Studio, 
2>LINK : fatal error LNK1181: 无法打开输入文件“C:\llvm\build\Release\lib\LLVMDemangle.lib”
2>已完成生成项目“tvm.vcxproj”的操作 - 失败。

and I cannot run get_started.py successfully.
tvm._ffi.base.TVMError: [17:32:36] C:\tvm\src\codegen\codegen.cc:27: Check failed: bf != nullptr Target llvm is not enabled

**Comment by Arthur-Shi** [comment]
@tqchen How to set llvm path？

**Comment by tqchen** [comment]
you will have to build with llvm enabled sucessfully first

**Comment by Arthur-Shi** [comment]
yeah, but how to build with llvm and cuda enabled? I set:

tvm_option(USE_CUDA "Build with CUDA" ON)
tvm_option(USE_LLVM "Build with LLVM" ON)

What else should I do before cmake?

**Comment by tqchen** [comment]
after you build cmake, make sure your vs build is successful

**Comment by Arthur-Shi** [comment]
-- The C compiler identification is MSVC 19.11.25547.0
-- The CXX compiler identification is MSVC 19.11.25547.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0 (found version "8.0")
-- Build with CUDA support
-- Build with RPC support...
-- Build with Graph runtime support...
-- Build with LLVM 7.0.0svn
-- Set TVM_LLVM_VERSION=70
-- Configuring done
-- Generating done
-- Build files have been written to: C:/nnvm/tvm/build

How to know whether it is successful or not?

**Comment by tqchen** [comment]
this is only building MSVC solution, you need to open the solution file and build with Visual Studio

**Comment by Arthur-Shi** [comment]
2>已完成生成项目“tvm.vcxproj”的操作 - 失败。
5>------ 已启动生成: 项目: ALL_BUILD, 配置: Release Win32 ------
5>Building Custom Rule C:/nnvm/tvm/CMakeLists.txt
5>CMake does not need to re-run because C:/nnvm/tvm/build/CMakeFiles/generate.stamp is up-to-date.
6>------ 已跳过生成: 项目: INSTALL, 配置: Release Win32 ------
6>没有为此解决方案配置选中要生成的项目 
========== 生成: 成功 3 个，失败 1 个，最新 0 个，跳过 2 个 ==========

And I think when I failed to build by VＳ

**Comment by Arthur-Shi** [comment]
What should I do? 

What is tvm.vcxproj?

**Comment by prob1995** [comment]
I also got this error. After trying to build tvm.sln, got 3 successe and 1 fail which is something like  "can't find "...Release\lib\LLVMDemangle.lib"'"  

@Arthur-Shi  how do you solve this error?

**Comment by Arthur-Shi** [comment]
Did you install llvm successfully?

**Comment by prob1995** [comment]
Yes, I build it successfully after I select "release" instead of "debug".
You can try it! 
<img width="573" alt="2018-01-31 2 40 42" src="https://user-images.githubusercontent.com/9880748/35608701-2a564668-0695-11e8-91ec-1ecd8ae17ed0.png">

**Comment by smartwell** [comment]
> Yes, I build it successfully after I select "release" instead of "debug".
> You can try it!
> <img alt="2018-01-31 2 40 42" width="573" src="https://user-images.githubusercontent.com/9880748/35608701-2a564668-0695-11e8-91ec-1ecd8ae17ed0.png">

i had finish LLVM， and no error,but when i build tvm.sln with cuda and llvm "on",like this picture, do  you solve this problem?
![20181225142620](https://user-images.githubusercontent.com/37239387/50415214-cb253880-0854-11e9-9d96-424940d322f5.png)

**Comment by Coderx7** [comment]
@prob1995 may I ask, how you compiled LLVM? after downloading the source, what sets of commands did you use? I'd greatly appreciate
