### ISSUE TITLE
Performance Drop of JITModule

### ISSUE THREAD

**Issue by taknevski** [dmlc/tvm#764]
Hi,

Is there a way to fully distribute and separate the reduction initialization to zero from the actual convolution accumulation using tvm?
Right now to describe a convolution I need the sum operator, which automatically initializes the output to zero and inserts it into the same loop nest as the computation. But I want to separate this initialization from the computation and time it separately , is there a way to do this?

**Comment by tqchen** [comment]
so far the initialization is tied with computation, how-ever, timing-wise  initialization cost little time.

**Comment by taknevski** [comment]
Thanks, 

For my test case in the generated llvm code, I see 2 functions: default_function and default_function_compute. Default function has a lot of checks and assertions on the inputs and
I just want to time the default_function_compute running time. Is there a way to do this?
Right now, I'm having to write a wrapper around the default_function_compute function interfacing to the assembly code  and am timing it. I get drastically different times, the compute time is much less than the time that does all the assertions and checks.

**Comment by taknevski** [comment]
I'm trying to do the above timing for benchmarking the performance in terms of FLOPS.

**Comment by tqchen** [comment]
We should be able to modify function generator to remove those checks and assertions by modifying MakeAPI. However, the relative time cost of the input consistency checking should be negligible compared to the time cost of actually running the code, both in terms of complexity and cost of running it for the normal workload we care, so we should not worry that much on the overhead of this function launch.

**Comment by taknevski** [comment]
If possible, could the function that does the computation (default_function_compute_) be exported from the module , so that it would be  possible to invoke it using time_evaluator and passing in some arguments ? A debug mode could be added for this..

**Comment by tqchen** [comment]
The only additional workload the default_function add to are consistency checks, for example. If we compile a function that only accepts tensor of size ```(4,4)```, it checks

```c++
void default_function(DLTensor *v) {
   CHECK(v->shape[0] == 4);
   CHECK(v->shape[1] == 4);
   default_compute_function(v);
}
```

We can modify the MakeAPI function to not emit those checks, and expose the risk to the user. However, 
such check should not really affect FLOPS number you get for the general operator of interest, so it is really not necessary to do the raw function calls. 

For example, compiling a CPU kernel and a CUDA kernel will have the same default checks, but you can observe very different FLOPS, in terms of TFLOPS to GFLOPS level, this indicate that the checks is not the bottleneck at all

**Comment by tqchen** [comment]
One thing we need to be careful about is the timing methodology. When you do the timing, the time you get from first calling the function and second time you call the function can differ. Since data need to be loaded into cache, as well as the instructions(or something like PTX that need to be JITed).

So we always need to skip first invocation when measuring the time

**Comment by taknevski** [comment]
I am observing a factor of ~6x slowdown on a single core of Skylake when running the convolution via tvm as opposed to running just the computation code generated from tvm via  a c driver. I am attaching a simple source archive below, which if you could try on your end to verify, I'd greatly appreciate.
It has a README and a Makefile below:
[performance.tar.gz](https://github.com/dmlc/tvm/files/1624213/performance.tar.gz)


Thanks,
Anand

**Comment by tqchen** [comment]
There are two possibilities in here

- The difference was due to as you mentioned, the cost in the initializer(this is your conjecture)
- The difference was due to the fact that the way things are created and linked.
    - The default function uses LLVM's JITModule
    - Your benchmark uses direct C module

We did observe sometimes LLVM's JITModule being slower than directly export the module to a .so file and then load it back later.

To verify which one is the case, please do two things:

- Do a f.export_library("xx.so") preferably with icc, and load it back later using tvm.module.load then run the time evaluator benchmark
- Do a normal call into the wrapped function. The calling convention follows, with the same parameter definition in here https://github.com/dmlc/tvm/blob/master/include/tvm/runtime/c_runtime_api.h#L256 

```c++
extern "C" wrapped_func(TVMValue* arg_values, int* type_codes, int num_args);
```

**Comment by taknevski** [comment]
Oh, thanks a lot, for this information, I'll try it out..

Regards,
Anand

**Comment by taknevski** [comment]
Yes the export  to a library and then running gave me the same performance as calling from the c driver,
this is great, thanks!

**Comment by tqchen** [comment]
@yidawang @yzhliu something to note during our intel exploration

**Comment by tqchen** [comment]
@taknevski Thanks for bringing this issue to the attention.

**Comment by tqchen** [comment]
cc @yidawang @

**Comment by tqchen** [comment]
I am going to reopen it since this seems to due to improper handling of target machine selector in our JITModule.

**Comment by tqchen** [comment]
@taknevski can you see if #778 fixed the problem of JIT module?

**Comment by taknevski** [comment]
@tqchen Is it committed ? Please let me know the commit id, I can check it

**Comment by taknevski** [comment]
Sorry, got the commit id, will try

**Comment by taknevski** [comment]
@tqchen  Yes it fixed the problem, thanks
