### ISSUE TITLE
cannot import name decorate

### ISSUE THREAD

**Issue by YuqiongQi** [dmlc/tvm#765]
When I import tvm in python, there is some error.
>>> import tvm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tvm/__init__.py", line 16, in <module>
    from . import ir_builder
  File "tvm/ir_builder.py", line 4, in <module>
    from . import api as _api
  File "tvm/api.py", line 20, in <module>
    from . import tag as _tag
  File "tvm/tag.py", line 8, in <module>
    raise err_msg
ImportError: cannot import name decorate

**Comment by tqchen** [comment]
need to pip install decorator as dependency

**Comment by YuqiongQi** [comment]
Thanks, but I have already installed the decorator.


/usr/lib/python2.7/dist-packages# pip install decorator
Requirement already satisfied: decorator in /usr/lib/python2.7/dist-packages


原始邮件
发件人:Tianqi Chennotifications@github.com
收件人:dmlc/tvmtvm@noreply.github.com
抄送:YuqiongQiqiyuqiong1993@qq.com; Authorauthor@noreply.github.com
发送时间:2018年1月8日(周一) 14:45
主题:Re: [dmlc/tvm] cannot import name decorate (#765)


need to pip install decorator as dependency

**Comment by tqchen** [comment]
Make sure decorator is updated to latest version

**Comment by YuqiongQi** [comment]
Thank you!


原始邮件
发件人:Tianqi Chennotifications@github.com
收件人:dmlc/tvmtvm@noreply.github.com
抄送:YuqiongQiqiyuqiong1993@qq.com; Authorauthor@noreply.github.com
发送时间:2018年1月8日(周一) 14:59
主题:Re: [dmlc/tvm] cannot import name decorate (#765)


Make sure decorator is updated to latest version
