### ISSUE TITLE
nullptr Cannot find function

### ISSUE THREAD

**Issue by AndyQi93** [dmlc/tvm#768]
When I  executed  extern_op.py, something is wrong. 
And I have already installed the cblas.

src/runtime/module.cc:99: Check failed: f != nullptr Cannot find function tvm.contrib.cblas.matmul in the imported modules or global registry

**Comment by AndyQi93** [comment]
And my code just include:

n = 1024
l = 128
m = 235
bias = tvm.var('bias', dtype=tvm.float32)
A = tvm.placeholder((n, l), name='A')
B = tvm.placeholder((l, m), name='B')
C = tvm.extern((n, m), [A, B],
               lambda ins, outs: tvm.call_packed(
                   "tvm.contrib.cblas.matmul",
                   ins[0], ins[1], outs[0], False, False), name="C")
D = tvm.compute(C.shape, lambda i, j: C[i,j] + bias, name="D")
s = tvm.create_schedule(D.op)

ctx = tvm.cpu(0)
f = tvm.build(s, [A, B, D, bias], "llvm")
a = tvm.nd.array(np.random.uniform(size=(n, l)).astype(A.dtype), ctx)
b = tvm.nd.array(np.random.uniform(size=(l, m)).astype(B.dtype), ctx)
d = tvm.nd.array(np.zeros((n, m), dtype=D.dtype), ctx)
bb = 10.0
f(a, b, d, bb)
np.testing.assert_allclose(
    d.asnumpy(), np.dot(a.asnumpy(), b.asnumpy()) + 10, rtol=1e-5)

**Comment by tqchen** [comment]
you will need to build tvm with cblas support enabled by change config.mk. The default installation do not install cblas contrib

**Comment by derisavi-huawei** [comment]
Supported values for USE_BLAS are `openblas`, `atlas`, `blas`, and `apple`.

**Comment by wu-yy** [comment]
I install the openblas, and it is ok.you can install openblas with the following command on Ubuntu.
`sudo apt-get install libopenblas-dev`
