### ISSUE TITLE
More robust testcase for argmax argmin

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#771]
There are time when we have random failures of argmax/argmin test in topi on CI. This is likely due to the difference in tie handling (when two values are close or equal and there is a difference in breaking a tie). 

To fix this issue, we need to fix the verification of argmax/argmin to instead check the value of corresponding index is close to the value returned by max/min

**Comment by tqchen** [comment]
@sxjscience can you look into this?

**Comment by sxjscience** [comment]
@tqchen OK, I'll revise the test

**Comment by tqchen** [comment]
@sxjscience #784 add the test for argmin/max but the assert of index closeness is still there for argmin/argmax, please remove that codepath so random failure won't happen again due to ties

**Comment by sxjscience** [comment]
Sorry for my oversight. I've revised https://github.com/dmlc/tvm/pull/788
