### ISSUE TITLE
Ptr type reservation in non-global scope

### ISSUE THREAD

**Issue by kun-zh** [dmlc/tvm#785]
When use the intrisinc for internal memory copy, just like tvm.call_extern("int32", memcpyfromSrctoDst, dstBuffer.access_ptr("w"), srcBuffer.access_ptr("r")), it will error out if either of dstBuffer and srcBuffer is not global scope in storage_access pass. I look into the pass and think it make sense for array index access, but we want to get the pointer type for instrisinc argument. Now we have 2 ways: 
1、generate "memcpyfromSrctoDst( tvm_address_of( base+offset), tvm_address_of(base + offset))" after the storage_access pass.  And we can do the type cast in codegen when we get "tvm_address_of"
2、generate "memcpyfromSrctoDst( reinterpret_cast<ptrtype>( base+offset),reinterpret_cast<ptrtype>(base + offset))" after storage_access pass.

@tqchen Do u think there is a better solution?

**Comment by tqchen** [comment]
address_of is a better solution if you want to get a pointer back

**Comment by kun-zh** [comment]
OK, I will go ahead per your suggestion
