### ISSUE TITLE
Memory overhead(?) for Convolution schedule

### ISSUE THREAD

**Issue by yzhliu** [dmlc/tvm#792]
Not sure whether it is something with the memory pool.

For this schedule, https://github.com/yzhliu/topi-intel/blob/master/mem_issue/conv.py , if I simply separate data pack and convolution calculate (then add up the costs), I can always get 10% speedup against that is combined:

$ TVM_NUM_THREADS=4 python2 conv.py 
MKLDNN - g1mb1_ic3ih224iw224_oc64oh112ow112_kh7kw7_sh2sw2_ph3pw3_n : 0.773982 ms
Run separately ...
Use memoize topi.tests.test_topi_conv2d.verify_con2d_nchw.get_ref_data.pkl(5, (1, 3, 224, 224), 'float32', 3, 2, (64, 3, 7, 7))
--- schedule data packing ---
data -> data_vec: 8.82842e-05 secs/op
--- schedule kernel packing ---
kernel -> kernel_vec: 2.59738e-05 secs/op
--- schedule conv & unpack ---
conv & unpack: 0.00110448 secs/op
**total = 0.001219 sec/op**
Run together ...
Use memoize topi.tests.test_topi_conv2d.verify_con2d_nchw.get_ref_data.pkl(5, (1, 3, 224, 224), 'float32', 3, 2, (64, 3, 7, 7))
**conv all: 0.00146011 secs/op**

MKLDNN - g1mb1_ic64ih56iw56_oc64oh56ow56_kh3kw3_sh1sw1_ph1pw1_n : 0.72514 ms
Run separately ...
Use memoize topi.tests.test_topi_conv2d.verify_con2d_nchw.get_ref_data.pkl(5, (1, 64, 56, 56), 'float32', 1, 1, (64, 64, 3, 3))
--- schedule data packing ---
data -> data_vec: 0.000432787 secs/op
--- schedule kernel packing ---
kernel -> kernel_vec: 2.77567e-05 secs/op
--- schedule conv & unpack ---
conv & unpack: 0.00089618 secs/op
**total = 0.001357 sec/op**
Run together ...
Use memoize topi.tests.test_topi_conv2d.verify_con2d_nchw.get_ref_data.pkl(5, (1, 64, 56, 56), 'float32', 1, 1, (64, 64, 3, 3))
**conv all: 0.001539 secs/op**

While I don't see similar issue with this simple GEMM schedule: https://github.com/yzhliu/topi-intel/blob/master/mem_issue/gemm.py

The test was made on an AWS C5 instance.

**Comment by yzhliu** [comment]
And on my MacBook with AVX2, I got similar results

**Comment by tqchen** [comment]
can you do a big investigation into this? We can use pragma debug_skip_region to remove regions in compute and only keep the memory allocation.

**Comment by yidawang** [comment]
I am guessing that the speedup of separate measuring comes from the cache warm-up in the packing steps. When measuring the packing separately, the data to-be-packed stays in the cache for repeated running. The data will be flushed out if the convolution takes place right after packing, i.e. measured together.

**Comment by tqchen** [comment]
closing for now as @yidawang 's answer might be the case, can reopen and investigate later
