### ISSUE TITLE
WebGL Followup

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#799]
#672 Provide basic support for WebGL features. This Issue lists the followup items to be done.

- [x] Store large data into 2D texture
      - We can use canonical form of [1024, y] (always make lowest dimension 1024).  
- [x] GEMM 1024x1024
- [x] TOPI support of gl functions
- [x] End to end example of resnet/mobielnet
- [ ] Optimize the bottleneck operators(conv2d_nchw), possibly via intermediate layout change

**Comment by tqchen** [comment]
@phisiart

**Comment by phisiart** [comment]
- [ ] conv2d_nchw
- [ ] dense
- [ ] injective
- [ ] pool
- [ ] softmax

**Comment by tqchen** [comment]
#836 #817

**Comment by tqchen** [comment]
https://github.com/dmlc/nnvm/pull/369

**Comment by tqchen** [comment]
Now the only item that is left is the perf improvement of conv2d

**Comment by phisiart** [comment]
I feel like I can't continue working on this. My full-time job starts on Monday.

I took a look at deeplearn.js today. They don't seem to have special treatment for their [WebGL conv2d operator](https://github.com/PAIR-code/deeplearnjs/blob/master/src/kernels/webgl/conv_gpu.ts#L38): it's just several layers of for loops. There's no layout transformation either (no transpose or tiling) in [model construction](https://github.com/PAIR-code/deeplearnjs/blob/master/models/mobilenet/mobilenet.ts#L80).

Last semester when we were doing the course project, we [experimented matrix multiplication](https://phisiart.github.io/418-proj/), and transpose doesn't really change performance. We didn't try tiling though.

**Comment by tqchen** [comment]
close this for now as most of stuffs are checked in thanks to @phisiart , followup with perf on another issue
