### ISSUE TITLE
[BACKEND] Vulkan and SPIRV

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#811]
This issue lists the necessary steps into support Vulkan runtime to run TVM on a Vulkan environment when OpenCL driver is not available. the steps are

- [x] src/runtime/vulkan that reflects other runtimes like OpenCL/CUDA/Metal
- [x] SPIR-V code generator. After looking into SPIRV spec, i think it is best to generate SPIRV directly and take advantage of possible existing toolchain for optimizing the code
- [x] Basic test-cases that can take a spirv binary and runs the vulkan runtime.
- [ ] Support text style ASM loading and save of spirv 
- [ ] Tutorials on how to use vulkan backend
- [ ] Tutorials on using vulkan on android.

I think the first step of this issue would be supporting the runtime and verify them with some form of glsl, then spirv code generator

**Comment by PENGUINLIONG** [comment]
Was anyone assigned? If not I'd like to work on this one.

**Comment by tqchen** [comment]
I am drafting on a basic version of runtime, if you are interested in SPIRV code generator or something related, you are more than welcomed to do so

**Comment by PENGUINLIONG** [comment]
Great. I will work on the codegen, then.

**Comment by tqchen** [comment]
@PENGUINLIONG Because there is a blocking issue on my side on this. I decided to check in a basic SPIRV code-gen in one or two days. The best way to coordinate might be improving the backend after that PR checks in. Sorry I was being unclear in my last comment.  In the meanwhile, there is definitely something around SPIRV module which we need contributions, for example, load/store of asm style format of the spirv module.

**Comment by tqchen** [comment]
The development process will be in https://github.com/tqchen/tvm/commits/vulkan currently the vulkan runtime part is ready

**Comment by PENGUINLIONG** [comment]
>  ... load/store of asm style format of the spirv module.

Of course, to test your code, you need to load spirv, and when you do it, there is nothing let for me. But I think it's alright! I focused on composing binary spirv module from IR. So I can do something interesting without interupting your work. Just set up an interface so that I can stuff spirv asm into TVM with filesystem kept untouched. -w-

**Comment by tqchen** [comment]
Here is the PR to add support to vulkan https://github.com/dmlc/tvm/pull/861 I tested on Nvidia driver and NNVM compiler runs. We would definitely love more contributions to try it out, write tutorials and run it on mobile devices.

**Comment by tqchen** [comment]
@PENGUINLIONG would you be interested in contributing a tutorial or android usage guide?

**Comment by PENGUINLIONG** [comment]
@tqchen I can try but I don't have a vulkan-capable device. My laptop is vulkan capable, so if Android emulator supports forwarding vulkan calls, I can work on this.

**Comment by PENGUINLIONG** [comment]
Failed to set up Android SDKs here due to poor network. I will check if there is any workaround.

**Comment by tqchen** [comment]
close this for now and will open another issue for android
