### ISSUE TITLE
how to get the model layer running time

### ISSUE THREAD

**Issue by renjiangyong** [dmlc/tvm#813]
Hi, I have a simple question, how to get the every layer running time , I add print the time in file tvm/src/runtime/graph/graph_runtime.cc, but get the operation in _op_exec_ vector running time.
thank you !

**Comment by srkreddy1238** [comment]
I am not sure I understood your question.

The for loop in the [Run](https://github.com/dmlc/tvm/blob/814b46dccb3c340be7611d113a303a546f7b2b2a/src/runtime/graph/graph_runtime.cc#L52) function calls the packed functions for all layers of final graph.
Each op_exec here corresponding to each layer compute.

But one difference here is the operation represented by the packed function op_exec here is a fused (optimized) [Ref](https://github.com/dmlc/nnvm/blob/69f0b75786786121569f25ced29bbff8826c2cc9/python/nnvm/compiler/build_module.py#L251) version of one or more nodes of original graph before nnvm compilation process.

Siva

**Comment by renjiangyong** [comment]
thank you very much. @srkreddy1238 
Did you mean the element in op_exec is a operation or a layer? I have other question, how can I get the function name of the std::function<void()> in op_exec[]? the true name of the fuction in op_exec[]
thank you.
jiangyong

**Comment by srkreddy1238** [comment]
The function names are in the graph definition (for example "func_name": "fuse_broadcast_add",) produced by nnvm compiling process. Which is noting but the symbol which is part of the library produces by nnvm compiler process.

TVM run time just does a dlopen to map func_name from graph definition to a callable function in library.

Element in op_exec is a fused operation of multiple layers some times (Ex: fuse_conv2d_broadcast_add_relu).

Siva

**Comment by srkreddy1238** [comment]
I have a local patch to disable operator fusing in nnvm compilation process for debugging purpose. I will upload it soon.

Siva

**Comment by srkreddy1238** [comment]
https://github.com/dmlc/nnvm/pull/333
check this patch to disable fuse partitioning.

**Comment by renjiangyong** [comment]
thank you very much @srkreddy1238 , I will try the path you provided, thank you .
jiangyong
