### ISSUE TITLE
Support Tanh intrinsic in LLVM

### ISSUE THREAD

**Issue by chenqy4933** [dmlc/tvm#821]
I use this code to compile the mnist model ,but with the erro????

      # for a normal mxnet model, we start from here
      mx_sym, args, auxs = mx.model.load_checkpoint('Mnist', 10)
      # now we use the same API to get NNVM compatible symbol
      nnvm_sym, nnvm_params = nnvm.frontend.from_mxnet(mx_sym, args, auxs)
      # repeat the same steps to run this model using TVM
      data_shape = (1, 1, 28, 28)
      graph2, lib2, params2 = nnvm.compiler.build(nnvm_sym, target, shape={"data": data_shape},              params=nnvm_params)
     m2 = graph_runtime.create(graph2, lib2, ctx)

Out put the erro !!!!!
         

  File "/usr/local/lib/python3.6/site-packages/tvm-0.1.0-py3.6-macosx-10.13-x86_64.egg/tvm/_ffi/function.py", line 255, in my_api_func
    return flocal(*args)
  File "/usr/local/lib/python3.6/site-packages/tvm-0.1.0-py3.6-macosx-10.13-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/usr/local/lib/python3.6/site-packages/tvm-0.1.0-py3.6-macosx-10.13-x86_64.egg/tvm/_ffi/base.py", line 62, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [13:50:37] src/codegen/llvm/codegen_llvm.cc:630: unknown intrinsic tanh

Stack trace returned 10 entries:
[bt] (0) 0   libtvm.dylib                        0x000000011021c26b dmlc::StackTrace() + 299
[bt] (1) 1   libtvm.dylib                        0x000000011021bfff dmlc::LogMessageFatal::~LogMessageFatal() + 47
[bt] (2) 2   libtvm.dylib                        0x00000001104a5a49 tvm::codegen::CodeGenLLVM::CreateIntrinsic(HalideIR::Internal::Call const*) + 5353
[bt] (3) 3   libtvm.dylib                        0x000000011048eed3 tvm::IRFunctor<llvm::Value* (tvm::NodeRef const&, tvm::ir::ExprFunctor<llvm::Value* (HalideIR::Expr const&)>*)>::operator()(tvm::NodeRef const&, tvm::ir::ExprFunctor<llvm::Value* (HalideIR::Expr const&)>*) const + 323
[bt] (4) 4   libtvm.dylib                        0x00000001104a91c7 tvm::codegen::CodeGenLLVM::VisitStmt_(HalideIR::Internal::Store const*) + 471
[bt] (5) 5   libtvm.dylib                        0x00000001102b3a23 tvm::IRFunctor<void (tvm::NodeRef const&, tvm::ir::StmtFunctor<void (HalideIR::Internal::Stmt const&)>*)>::operator()(tvm::NodeRef const&, tvm::ir::StmtFunctor<void (HalideIR::Internal::Stmt const&)>*) const + 323
[bt] (6) 6   libtvm.dylib                        0x00000001104a2f33 tvm::codegen::CodeGenLLVM::CreateSerialFor(llvm::Value*, llvm::Value*, llvm::Value*, HalideIR::VarExpr const&, HalideIR::Internal::Stmt const&) + 691
[bt] (7) 7   libtvm.dylib                        0x00000001104a998c tvm::codegen::CodeGenLLVM::VisitStmt_(HalideIR::Internal::For const*) + 412
[bt] (8) 8   libtvm.dylib                        0x000000011049cb1c tvm::codegen::CodeGenCPU::VisitStmt_(HalideIR::Internal::For const*) + 172
[bt] (9) 9   libtvm.dylib                        0x00000001102b3a23 tvm::IRFunctor<void (tvm::NodeRef const&, tvm::ir::StmtFunctor<void (HalideIR::Internal::Stmt const&)>*)>::operator()(tvm::NodeRef const&, tvm::ir::StmtFunctor<void (HalideIR::Internal::Stmt const&)>*) const + 323

How to solve it ,I wiil appreciate .......

**Comment by ANSHUMAN87** [comment]
I think currently Tanh is not supported in TVM framework, if you want to execute your model you may have to write an operator @nnvm/tvm/topi/python/topi/nn/elemwise.py

**Comment by tqchen** [comment]
this should have already been supported after #868
