### ISSUE TITLE
[TOPI] Support LRN Operator

### ISSUE THREAD

**Issue by renjiangyong** [dmlc/tvm#823]
when I running the vgg model on nnvm, I got an error "Operator: LRN is not supported in nnvm",  maybe the LRN is not implement, Did we have a plan to support LRN layer in nnvm, pls tell me the schedule when have a plan. thank you very much!

jiangyong

**Comment by kevinthesun** [comment]
VGG pretrained model in gluon can be directly imported into nnvm and run. Have you tried that?

**Comment by tqchen** [comment]
LRN itself can be supported by composing the current reduction and broadcast based operators, contribution is more than welcomed

**Comment by PariksheetPinjari909** [comment]
LRN support is added https://github.com/dmlc/tvm/pull/1000
