### ISSUE TITLE
[Image] Operations

### ISSUE THREAD

**Issue by srkreddy1238** [dmlc/tvm#832]
How about image decoder operations in TVM ?
i.e, an operator to take encoded byte stream or image path and convert to a Tensor (w x h x c).
and other version of it like crop ..etc.

Could have generic operator interface which call native library API for actual decode.

**Comment by tqchen** [comment]
see http://docs.tvmlang.org/tutorials/language/extern_op.html#sphx-glr-tutorials-language-extern-op-py which might be relevant.
