### ISSUE TITLE
Support TopK

### ISSUE THREAD

**Issue by tomflinda** [dmlc/tvm#838]
Recently, I try to write two kernels with tvm dsl. The first one is tensorflow tile :
Its api is like this:
extern Error_t TFTileOp(Tensor* input, Tensor* multiples, Tensor* output);
its parameters is explained as bellow：                                          
@param input tensor: N dimension. its length of shape is N, i.e, its shape is (l1, l2, ..., lN)                                             
@param input multiples: 1 dimension，its length of dimension is N，which must be the same as the input tensor, for example [m1, m2, ..., mN] 
@param output tensor:N dimension, its shape is (l1*m1, l2*m2, ..., lN*mN).
One example like this， input = [[1, 2],                                                    
                                                      [3, 4]]，2 dimension，its shape(2, 2)                             
   multiples = [2, 3]，its length must be 2,which is the same as the input tensor's dimension.                             
   output = [[1, 2, 1, 2, 1, 2],                                       
             [3, 4, 3, 4, 3, 4],                                       
             [1, 2, 1, 2, 1, 2],                                       
             [3, 4, 3, 4, 3, 4]]，its shape is (4, 6)                  
                                                                           
@return Error_t error number                                                

When I implement this api with tvm dsl, I meet a problem, the shape of output tensor is related with the shape of input tensor and the value of multiples, not only the multiples’s shape.
But in tvm dsl, its lamda description showed as bellow.
def _compute(*indices):
    out_shape = …
        …
        return ret
    return tvm.compute(out_shape, _compute)

However, out_shape is related with the shape of input tensor and the value of multiples, in lambda function's description, I cannot get the value's description of multiples, only the multiples index variable list, How do I solve this problem?

The second one is tensorflow topK kernel, this kernel function is to find the k best value and its location from the input tensor’s last dimension, on the assumption that the input tensor is N dimension(N >0).
As topK Involves k best sort, Is it suitable for description with tvm dsl?

**Comment by tqchen** [comment]
These are better dealt with native library functions as in http://docs.tvmlang.org/tutorials/language/extern_op.html#sphx-glr-tutorials-language-extern-op-py

**Comment by tomflinda** [comment]
OK, thanks.
