### ISSUE TITLE
there is no  dependency management in coproc_sync

### ISSUE THREAD

**Issue by lingfeiwu-hw** [dmlc/tvm#842]
Hi, all
I find that, there is no dependency management in coproc_sync.cc so, it will insert "coproc_dep_push" or "coproc_dep_pop" between two neighboring scopes which have different scope values. But there is no need to inert "coproc_dep_push" or "coproc_dep_pop" when two different scopes have no dependency. So i want to consider dependency when deal with coproc_sync. But there is a problem that when i try to recognize "load" or "store" for each buffer, it has been turned to be intrinsic form. The buffer is a "call" like "tvm_access_ptr", so i decide to use this call's 4th argument to recognize whether it is "load" or "store". Is it a right way to judge the buffer is "load" or "store" according to the 4th argument in "tvm_access_ptr"?

**Comment by tqchen** [comment]
See https://github.com/dmlc/tvm/blob/master/include/tvm/ir.h#L259 there is a rw_mask, which gives you information about whether it is a write or store access
