### ISSUE TITLE
consumer was deleted in lift_attr_scope

### ISSUE THREAD

**Issue by lingfeiwu-hw** [dmlc/tvm#843]
Hi all, 
I find that in the function "FlattenSeq" which is in the pass "lift_attr_scope", the "consumer" node was deleted, is it necessary to delete all the "consumer" at here ?

**Comment by tqchen** [comment]
it is not necessary, consumer was a tag that do not bear any meaning, it is deleted in FlattenSeq so we can see through this scope.
