### ISSUE TITLE
[LANGUAGE] Verify Reduce only Appears in Top level

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#848]
Currently, we restrict reduction to be at top level of the compute. The further compositions of the reduction will cause error without a clear error message. 

We need to implement a ComputeVerifier, which get called in compute, that checks reduce only appears at top level, and produce a more friendly error message like
```
reductions are only allowed at the top level of compute, please create another tensor for further composition.
```

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/1006

**Comment by roastduck** [comment]
Sorry for bringing up the issue again. I think the top-level-reduction-only restriction still exists in TVM today.

I noticed that `relay.transform.transform.FuseOps` fuses a `conv2d` and a following `relu` into one single function. If I understand correctly, this means, in the underlying TOPI implementation, there will be a `relu` operation outside the reduction from `conv2d` (scheduled via `inline`, `compute_at` or something like that). Such as:

```
for (...) {
  for (...) {
    x += ... // conv2d
  }
  x = relu(x) // relu
}
```

So the reduction loop is no longer at top level any more.

Is the aforementioned fusion really meaningful? Or is the fusion only used for third-party backends such as cuDNN?
