### ISSUE TITLE
Allocate temp buffer for tensorize

### ISSUE THREAD

**Issue by DengLLy** [dmlc/tvm#851]
As the example below:
```
produce B {
  for (i, 0, 12) {
    B[i] = 0.000000f
    for (k.outer, 0, 16) {
      for (k.inner, 0, 4) {
        B[i] = (B[i] + A[((((i*16) + k.outer)*4) + k.inner)])
      }
    }
  }
}
```
The number of elements in vector instruction is fixed, like 4. If we want to tensorize the k.inner, we need to allocate a extra buffer to store the intermediate result, or else it would be overwritten.
Here may be what we expect:
```
produce B {
  for (i, 0, 12) {
    B[i] = 0.000000f
    for (k.outer, 0, 16) {
      tmp = intrinsic("summation", A)
      B[i] = B[i] + tmp
    }
  }
}
```
So is there any way to allocate buffer for  intermediate result?

**Comment by tqchen** [comment]
rfactor might be related, @merrymercy might have some experience on related issues

**Comment by DengLLy** [comment]
Thank you ! I have tried rfactor and it works. With modification in schedule:
```
ko, ki = s[B].split(k, 4)
B_rfactor = s.rfactor(B, ki)    
s[B_rfactor].compute_at(s[B], s[B].op.axis[0])
```
The output result is what I expect. Now the lower IR turns into this:
```
realize B([0, 12]) {
  produce B {
    for (ax0, 0, 12) {
      // attr [compute(B.rf, 0x1204368)] realize_scope = ""
      realize B.rf([0, 4], [ax0, 1]) {
        produce B.rf {
          for (k.inner, 0, 4) {
            B.rf(k.inner, (0 + ax0)) =0.000000f
            for (k.outer, 0, 16) {
              B.rf(k.inner, (0 + ax0)) =(B.rf(k.inner, (0 + ax0)) + A((0 + ax0), (k.inner + (k.outer*4))))
            }
          }
        }
        B(ax0) =0.000000f
        for (k.inner.v, 0, 4) {
          B(ax0) =(B(ax0) + B.rf(k.inner.v, ax0))
        }
      }
    }
  }
}
```
I tried to tensorize the k.inner and the k.outer.v, it failed. 
The reason is that rfactor move the rfactor_axis to first dimension, and the shape of new tensor B.rf is [rfactor, axo]. Tensorize with intrinsic shape [rfactor] would not success.
The shape of B.rf cause similar problem for the tensorize of k.outer.v
I think there are two solution:
1. allow using rfactor without moving rfactor_axis to first dimension
1. enhance tensorize to match [n, m, 1] -> [n, m]. while currently the tensorize only allow the match [1, n, m]->[n, m] 

Do you have other better suggestions? @tqchen

**Comment by tqchen** [comment]
@merrymercy You mentioned a similar problem right? Do you have a local patch that enhances rfactor ?

**Comment by merrymercy** [comment]
Yes, I met the same problem. I added a new bool argument `transpose` to `s.rfactor` to indicate whether transpose `B.rf`.
But latter I didn't need this feature any more. So I didn't push or save this patch.

If you think the solution 1 is OK, I can rewrite the patch.

**Comment by tqchen** [comment]
I think we need an factor axis argument which indicate which axis we want to insert the factor dimension

**Comment by tqchen** [comment]
move to https://github.com/dmlc/tvm/issues/867
