### ISSUE TITLE
CodeGen C Ramp implementation

### ISSUE THREAD

**Issue by PENGUINLIONG** [dmlc/tvm#860]
I wonder what this method is used for. Is it used for generating ascending sequence of number?

https://github.com/dmlc/tvm/blob/91222e66a532a383fc8d7eb6bb54b6b0bacac2c9/src/codegen/codegen_c.cc#L668-L676

If it is so, the code seems not working. Say we have `base = 0; lanes = 3; stride = 1`, then the codegen will be generating:

```c
((int3)((0)+(1*0), (0)+(1*1), (0)+(1*2)))
```

And that will not work, because there is no type called `int3`. Even if it's turned into int[3] it's still rejected by MSVC. The correct output should be like this:

```c
{(int)((0)+(1*0)), (int)((0)+(1*1)), (int)((0)+(1*2))}
```

If this is confirmed,  I will PR it.

**Comment by tqchen** [comment]
CodeGenC is mainly aimed to be used by OpenCL, CUDA C and Metal, where int3 type exists. It is not meant to be used to generate code for the host side.

**Comment by PENGUINLIONG** [comment]
Okay. Closing this.

**Comment by tqchen** [comment]
I think you make a good point as you are right to ask this question, you are more than welcomed to open a PR to add comment to clarify the codeblock, see example https://github.com/dmlc/tvm/pull/815
