### ISSUE TITLE
[SCHEDULE] Add factor_axis to rfactor

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#867]
See https://github.com/dmlc/tvm/issues/851 We want to enhance rfactor so it contains an additional argument factor_axis, which takes list of axis in factored tensor, on which axis each factor corresponds to. This can enhance the ability to do vectorization and other things.

**Comment by DengLLy** [comment]
I take a look at the code. The additional argument is supposed to indicate the position of the new axis. But I don't know how to define the arg.
1. s.rfactor(tensorA, reduce_axis, pos). It is simple, but I think you would not prefer this way.
2. s.rfactor(tensorA, reduce_axis, factor_axis). The factor_axis is a list of axis refer to the generated factor_tensor, including the new axis. But it would suggest a reorder of axes, which could not be support.

Could you give me a simple example the explain how to design the api ? Then I could start to fix this.

**Comment by tqchen** [comment]
@DengLLy Interested in pushing a patch?

**Comment by tqchen** [comment]
supported by #895
