### ISSUE TITLE
#include<dmlc/thread_local.h> not found

### ISSUE THREAD

**Issue by iihihiuh** [dmlc/tvm#884]
I am trying to deploy an compiled model on my iPhone. While I am building libtvm_runtime, using tvm_runtime_pack.cc, I encountered this error.

In file included from runtime.cc:23:
./../../src/runtime/c_runtime_api.cc:6:10: fatal error: 'dmlc/thread_local.h' file not found
#include <dmlc/thread_local.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.

I feel like this is a package located outside tvm repository.
Is there any way I could include dmlc package into my local machine? (tvm and nnvm work pretty well)

Yongqin

**Comment by tqchen** [comment]
do ``` git submodule update --init --recursive```

**Comment by iihihiuh** [comment]
Tianqi,

I did it in tvm directory but nothing printed out on console. I also tried to do this in nnvm repository.

Submodule path 'tvm': checked out '3a91764ec919b7a0034e104c7fac40ed5a840d12'
Submodule path 'tvm/HalideIR': checked out 'aadbf02d6bd7a545edbf6652494a7b07a97a06c1'

I rebuilt after doing update things. However, I still have this error.

**Comment by tqchen** [comment]
Try to clone tvm from scratch with option --recursive, the key problem is still not being able to clone submodules

**Comment by iihihiuh** [comment]
Actually, I indeed cloned this repository with option --recursive. 
I am building runtime library (in c++) and I am afraid I might need to do something to include dmlc to c++ library?

I am not so sure.

**Comment by tqchen** [comment]
add the dmlc/include to the include search path of your project

**Comment by iihihiuh** [comment]
Yeah! Thanks that indeed resolve the issue.
