### ISSUE TITLE
Xcode having trouble seeing all namespaces

### ISSUE THREAD

**Issue by iihihiuh** [dmlc/tvm#893]
I am trying to deploy a saved graph on actual IOS devices. However, it seems to me that Xcode can only see namespace tvm::runtime in a single file.
It gave me an error when I tried to access other identifiers in other files(I can only access functions and variables defined in metal_device_api.mm and when I uncommented include line for metal_device_api.mm, I can only access namespace in metal_module.mm) 

![screen shot 2018-02-11 at 20 12 34](https://user-images.githubusercontent.com/35404098/36083508-f5ff6846-0f67-11e8-8c3c-70a2046789ea.png)

Is there any way to resolve this issue?
(I have read the tutorial on how to deploy a rpc on metal but I does not give me too much insights)

Thank you,
Yongqin

**Comment by tqchen** [comment]
try to add the tvm-path/include to your search path and include it
