### ISSUE TITLE
Xcode 114 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by iihihiuh** [dmlc/tvm#900]
Hi,

I am trying to load a pre-trained module on to metal. When I built the project, xcode is giving me 

"ld: 114 duplicate symbols for architecture x86_64"

I fixed some of the error but I do not know to to fixed remaining 114 ones.
Attached are screen shot for my viewcontroller and deploy file.

![screen shot 2018-02-13 at 21 22 25](https://user-images.githubusercontent.com/35404098/36188904-2b2d4cca-1104-11e8-911f-39782b824270.png)

![screen shot 2018-02-13 at 21 22 42](https://user-images.githubusercontent.com/35404098/36188906-2e6d6f64-1104-11e8-96ce-c878fa30d984.png)

Thanks,

Yongqin

**Comment by tqchen** [comment]
I am not sure what is happening on your side, but maybe it is related to https://stackoverflow.com/questions/24298144/duplicate-symbols-for-architecture-x86-64-under-xcode?

**Comment by iihihiuh** [comment]
I also ran into this post when I was debugging, but as far as I can tell, I do not have -ObjC in my additional linker.

**Comment by tqchen** [comment]
This might happen, for example, if you include a header file in two places which contains functions that are not inlined. Closing this for now as we cannot offer more evidence toward this and seems it do not correspond to a problem on TVM side.
