### ISSUE TITLE
[NHWC]  support lost

### ISSUE THREAD

**Issue by srkreddy1238** [dmlc/tvm#904]
Recent port of topi to C++ lost NHWC support which was there in python.

Siva

**Comment by alex-weaver** [comment]
@srkreddy1238 The C++ port does not include any convolutions, as @tqchen mentioned the convolution schedules are currently undergoing more churn than the other ones.

Has the change broken NHWC support in python, or is it just missing from the C++ port? The latter is intended, the former is definitely not.

**Comment by alex-weaver** [comment]
Unless you mean with pooling/softmax ops - NHWC support for those was added to python after the C++ ops were added. I can fix that disparity up once the GenericFunc PR is resolved.

**Comment by masahi** [comment]
@alex-weaver do you mean I don't have to port updated python pooling and softmax to c++?

**Comment by alex-weaver** [comment]
If you are able to port them, that would be appreciated because that would let me focus on getting the C++ interface up to speed in other areas in topi, tvm and nnvm.

**Comment by masahi** [comment]
No problem, will be done soon.

**Comment by srkreddy1238** [comment]
Appreciate quick response.

I am aware of the convolution status. Current issue is about the pool ops.

@masahi: appreciate your initiative & waiting for your PR :)

Siva

**Comment by tqchen** [comment]
fixed by #905
