### ISSUE TITLE
get_started using C runtime API

### ISSUE THREAD

**Issue by nhynes** [dmlc/tvm#907]
Hi,

I'm trying to run the `get_started.py` TVM function using the C runtime API but the program (listed below) segfaults when it makes the call to `__tvm_main__`/`myadd`. I'm guessing my invocation of `TVMFuncCall` is incorrect?

For reference, everything is statically linked and gdb says that `myadd` is where it should be. This is the code that causes the error (extracted from [`c_runtime_api.cc`](https://github.com/dmlc/tvm/blob/master/src/runtime/c_runtime_api.cc#L278)):

`PackedFunc the_func = (*static_cast<const PackedFunc*>(func));`

It doesn't even make it past the constructor. (Maybe constructing the `FType` goes wrong?).

Thanks for any pointers [on fixing my pointers]!

```c
#include <stdlib.h>
#include "runtime/c_runtime_api.h"

int64_t shape[] = {3};
int64_t strides[] = {1};

extern void* __tvm_main__;

TVMArray* mk_tensor(int8_t* data) {
  TVMArray *t = (TVMArray*)malloc(sizeof(TVMArray));

  t->data = data;
  t->ndim = 1;
  t->shape = shape;
  t->strides = strides;
  t->byte_offset = 0;

  t->ctx.device_type = kDLCPU;
  t->ctx.device_id = 1;

  // int8
  t->dtype.code = 0;
  t->dtype.bits = 8;
  t->dtype.lanes = 1;

  return t;
}

int main() {
  int8_t a_data[] = {1, 2, 3};
  int8_t b_data[] = {2, 3, 4};
  int8_t c_data[] = {0, 0, 0};

  TVMValue arg_vals[3];
  arg_vals[0].v_handle = mk_tensor(a_data);
  arg_vals[1].v_handle = mk_tensor(b_data);
  arg_vals[2].v_handle = mk_tensor(c_data);

  TVMValue ret_val;
  int ret_type_code;

  int arg_type_codes[] = {kArrayHandle, kArrayHandle, kArrayHandle};

  TVMFuncCall(&__tvm_main__, arg_vals, arg_type_codes, 3, &ret_val, &ret_type_code);
}
```

**Comment by tqchen** [comment]
see https://github.com/dmlc/tvm/tree/master/apps/howto_deploy

**Comment by nhynes** [comment]
Right, except for the part where I'm forced to use C instead of CPP and can only use a stripped down version of the runtime which doesn't include dylib loading.

I appreciate the link, but I'd also appreciate if you left the issue open so that it remains visible to someone who is more willing to answer my [albeit very specific and constrained] question.

**Comment by tqchen** [comment]
I see, feel free to reopen the issue, we tend to close issue aggressively and only reopen when necessary

**Comment by tqchen** [comment]
If you use can cxx, likely the deploy example serves what you need(stripped down, no dependency)

If you want to remove dynamic library loader, follow the system loader module.

If you cannot use cxx, read the cxx example and you should be able to find a C counterpart  in the API

**Comment by nhynes** [comment]
Thanks! I'll try all of those things. There's no getting around the static linking constraint, though.
I respect that you want to keep your issue tracker clear, so I'll continue debugging today and close this issue if I can (or fail to) make progress.

**Comment by tqchen** [comment]
In your specific code, we will need to get a correct function handle first from a TVM module,(the tvm main) handle is not by default available as a symbol. You need to retrieve it from a Module 

You can do this by either create a DSOModule, which you can do dynamic load, or get the system module(add system lib option when you build the library)

**Comment by tqchen** [comment]
The system library module, which registers the function table to a global table works with static linking if you want to link everything together.

That cpp example shows how to retrieve the system module , although it is mixed together with the dll loading.

Feel free to keep the issue open, I just thought that answer might be suffice for fixing the issue, but we definitely want to resolve your problem :)

**Comment by tqchen** [comment]
In short, statistically link the generated .o with your main application, use a stripped version of runtime that includes the system module support. And follow the example after GetSystemLib line in deployment example

**Comment by nhynes** [comment]
Cool, that seemed to work. Thanks for your advice and patience!
