### ISSUE TITLE
[TOPI][CONTRIB] Object Detection Operators

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#908]
There has been quite some interests in supporting detectors in nnvm compiler. While most of the detector API are easy to express via compute, there are a few that are not. There are two ways this can be achieved.

- option 1 Support these detector operators as extern function, and register them as contrib
   - This requires a per target type implementation, which is fine as long as we restrict to a few
- option 2 . Write the detector operators using ir_builder and tvm.extern
   - This allows us to have unified implementation for all CPU, and another version for all GPUs. 
   - The only concern is ```ir_builder``` might be less intuitive than C. 

Personally I prefer option 2 because it requires less code rewriting per target. The problem of ```ir_builder``` can likely be fixed by hacking a python AST parser to accept a subset of python into the IR.

**Comment by tqchen** [comment]
@zhreshold can you help to provide a concrete list of operator that is needed?

**Comment by tqchen** [comment]
Contributions are  more than welcomed

**Comment by zhreshold** [comment]
Will do, let me figure out some related projects first

**Comment by kaishijeng** [comment]
@zhreshold 

  I will wait for proper changes to support multiboxprior. It should support your mxnet-ssd pretrained model for end2end object detection when this task completes.

Thanks,

**Comment by tqchen** [comment]
#911

**Comment by tqchen** [comment]
@kevinthesun

**Comment by kaishijeng** [comment]
@zhreshold 

Do you have a plan to implement ssd-mobilenet in near future?

Thanks,

**Comment by zhreshold** [comment]
@kaishijeng Not particularly which model, but I will revisit ssd models in late April hopefully.

**Comment by kaishijeng** [comment]
@zhreshold 

Any SSD model should be fine.

Thanks,

**Comment by tqchen** [comment]
http://nnvm.tvmlang.org/tutorials/from_darknet.html#sphx-glr-tutorials-from-darknet-py Implements YOLOv2, but still the last two layers, nms are not in TVM yet

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/1095

**Comment by liangfu** [comment]
@kevinthesun @tqchen It's great to see an implementation of `topi.vision.ssd.multibox`, as you said earlier, the implementation is based on `ir_builder` and `tvm.extern`, and it plays a role for unified CPUs.
However, I can see no way to bind any axis in `ExternOp` to make it parallelized for GPUs.
As mentioned in #1095, the most of code can be reused for other backends. Can you provide a guide how to reused the code implemented with `ir_builder` for GPUs? Thanks in advance.

**Comment by kevinthesun** [comment]
@liangfu Current plan is to support multibox_detection on cpu. We can then split SSD model into two parts: major network and final multibox_detection op. Major network can be run on various hardwares and then copy the output to cpu to run multibox_detection. This functionality will be added through https://github.com/dmlc/nnvm/pull/482

**Comment by liangfu** [comment]
@kevinthesun Thank you for your reply. My interest is focus on `opencl` as a final target. I'm good with the major network and the nnvm part ( dmlc/nnvm#482 ), since it can already run on top of GPU. But when implemented with `ir_builder` in `topi`, is it possible to target `opencl` or `cuda` ? How can I implement reuse the code in `ir_builder` for `opencl` ?

**Comment by tqchen** [comment]
close as basic ssd is checked in, the next steps are tracked in #1269
