### ISSUE TITLE
[TOPI]Why Conv2d supports HWCN format?

### ISSUE THREAD

**Issue by ANSHUMAN87** [dmlc/tvm#915]
I found from current topi code that it supports Conv2D for Layout- NCHW, NHWC, HWCN.
As per i understand, NCHW is for GPU, NHWC is for CPU based faster processing.

But i could not find an instance where HWCN will be used, can anyone please share where this layout is used?

**Comment by tqchen** [comment]
This layout is not used in any places so far, but serves as a good reference on how to implement the batched GPU kernel
