### ISSUE TITLE
behaviour of cache_write

### ISSUE THREAD

**Issue by derisavi-huawei** [dmlc/tvm#916]
Assume a 2D tensor `C` is computed using one reduction axis. When we apply `cache_write` to it and create a new tensor `newC`, reduction axis of `C` will be moved to `newC`. 
To my understanding, that prevents us from having the reduction axis (or a part of it, if we split it) at the level of tensor `C`. That is, we can't have something like (`i` and `j` are iteration variables of the 2 dimensions and `k` is reduction axis. All 3 iteration variables have been split)
```
produce C {
  for i1 {
    for j1 {
      for k1 {
        produce newC {
          for i2 {
            for j2 {
              for k2 {
          ...
        }
      }
    }
  }
}
```

Is there a way around this? I thought of `rfactor` but AFAIK the problem with `rfactor` is that it adds one dimension to the matrix, and therefore, makes it larger than required in this case.

**Comment by tqchen** [comment]
I see what you mean. Is there any motivation for supporting such computation pattern? A workaround would be creating two stages, one that does local reduction over a few axis, and then reduce the result(this is the same artifact as rfactor).

Then using ```compute_at``` to move things around into the reduction axis(so that dependency inference will only realize part of the result at each iteration)

**Comment by derisavi-huawei** [comment]
motivation: let's say we have a matmul (C=A*B) and we want to bring a tile of A and a tile of B into from global to local, compute a partial result for a tile of C in local and accumulate it back in global.

**Comment by derisavi-huawei** [comment]
In the workaround you explain, you still need to temporarily store a number of partial results (the number depends on how you split the reduction axis). Wouldn't that increase the memory requirement of the resulting code?

**Comment by tqchen** [comment]
in that workaround, you pay one additional local memory equal to  tile size. This is invariant to reduction axis. Because you are computing inside the reduction axis

**Comment by derisavi-huawei** [comment]
Thanks @tqchen . Here is a solution based on your workaround (in case other people are interested). As you said, it only consumes one extra `C` tile in terms of memory consumption, although it would be nicer if it didn't consume that extra memory either :-)
```python
import tvm
dtype = "float32"

k = tvm.reduce_axis((0, 64), 'k')
kk = tvm.reduce_axis((0, 16), 'kk')
A = tvm.placeholder((512, 1024), dtype, name='A')
B = tvm.placeholder((1024, 2048), dtype, name='B')
C = tvm.compute((512, 2048), lambda y, x: tvm.sum(A[y,kk*64+k]*B[kk*64+k, x], axis=[kk,k]), name="C")

s = tvm.create_schedule(C.op)

AA = s.cache_read(A, "local", [C])
BB = s.cache_read(B, "local", [C])
CC = s.cache_write(C, "local")

CC_rf = s.rfactor(CC, kk)

yo, xo, yi, xi = s[CC_rf].tile(s[CC_rf].op.axis[1], s[CC_rf].op.axis[2], 512//16, 2048//16)
s[CC_rf].reorder(yo, xo, s[CC_rf].op.axis[0])
s[AA].compute_at(s[CC_rf], s[CC_rf].op.axis[0])
s[BB].compute_at(s[CC_rf], s[CC_rf].op.axis[0])

yo, xo, yi, xi = s[CC].tile(s[CC].op.axis[0], s[CC].op.axis[1], 512//16, 2048//16)
s[CC].reorder(yo, xo, s[CC].op.reduce_axis[0], yi, xi)
s[CC_rf].compute_at(s[CC], s[CC].op.reduce_axis[0])

yo, xo, yi, xi = s[C].tile(s[C].op.axis[0], s[C].op.axis[1], 512//16, 2048//16)
s[CC].compute_at(s[C], xo)

print(tvm.lower(s, [A, B, C], simple_mode=True))
```

which generates

```
// attr [C.local] storage_scope = "local"
allocate C.local[float16 * 32 * 128]
// attr [A.local] storage_scope = "local"
allocate A.local[float16 * 32 * 64]
// attr [B.local] storage_scope = "local"
allocate B.local[float16 * 64 * 128]
// attr [C.local.rf] storage_scope = "global"
allocate C.local.rf[float16 * 1 * 32 * 128]
produce C {
  for (y.outer, 0, 16) {
    for (x.outer, 0, 16) {
      produce C.local {
        for (ax0.inner.init, 0, 32) {
          for (ax1.inner.init, 0, 128) {
            C.local[((ax0.inner.init*128) + ax1.inner.init)] = 0.000000h
          }
        }
        for (kk.v, 0, 16) {
          produce C.local.rf {
            produce A.local {
              for (ax0, 0, 32) {
                for (ax1, 0, 64) {
                  A.local[((ax0*64) + ax1)] = A[(((((y.outer*512) + kk.v) + (ax0*16))*64) + ax1)]
                }
              }
            }
            produce B.local {
              for (ax0, 0, 64) {
                for (ax1, 0, 128) {
                  B.local[((ax0*128) + ax1)] = B[((((x.outer + (kk.v*1024)) + (ax0*16))*128) + ax1)]
                }
              }
            }
            for (y.c.inner, 0, 32) {
              for (x.c.inner, 0, 128) {
                C.local.rf[((y.c.inner*128) + x.c.inner)] = 0.000000h
                for (k, 0, 64) {
                  C.local.rf[((y.c.inner*128) + x.c.inner)] = (C.local.rf[((y.c.inner*128) + x.c.inner)] + (A.local[((y.c.inner*64) + k)]*B.local[(x.c.inner + (k*128))]))
                }
              }
            }
          }
          for (ax0.inner, 0, 32) {
            for (ax1.inner, 0, 128) {
              C.local[((ax0.inner*128) + ax1.inner)] = (C.local[((ax0.inner*128) + ax1.inner)] + C.local.rf[((ax0.inner*128) + ax1.inner)])
            }
          }
        }
      }
      for (y.inner, 0, 32) {
        for (x.inner, 0, 128) {
          C[(((((y.outer*512) + x.outer) + (y.inner*16))*128) + x.inner)] = C.local[((y.inner*128) + x.inner)]
        }
      }
    }
  }
}
```

**Comment by derisavi-huawei** [comment]
The storage scope of `C.local.rf` is `global` while that of `C.local` is `local`. Is that by design or is it a bug? I expected their storage scopes to be the same. Any ideas @tqchen?

**Comment by tqchen** [comment]
We can change this behavior by setting the scope to be the same. The scope can be changed by set_scope later
