### ISSUE TITLE
[FRONTEND] Object Ownership (when to call TVMNodeFree)

### ISSUE THREAD

**Issue by cnuernber** [dmlc/tvm#918]
I have a question about the object ownership rules that should be followed when working with TVM's C ABI:

```clojure
#'tvm-clj.core/n
tvm-clj.core> n
#tvm_clj.base.NodeHandle
{:dtype "int32",
 :name "n",
 :tvm-jcpp-handle #<tvm_clj.tvm.runtime$NodeHandle@545b460d tvm_clj.tvm.runtime$NodeHandle[address=0x7f72846d3000,position=0,limit=0,capacity=0,deallocator=null]>,
 :tvm-type-index 1,
 :tvm-type-kwd nil}
tvm-clj.core> (def A (placeholder [n] :name "A"))
#'tvm-clj.core/A
tvm-clj.core> A
#tvm_clj.base.NodeHandle
{:dtype "float32",
 :op #tvm_clj.base.NodeHandle
 {:dtype "float32",
  :name "A",
  :shape [#tvm_clj.base.NodeHandle
          {:tvm-jcpp-handle #<tvm_clj.tvm.runtime$NodeHandle@5a977e75 tvm_clj.tvm.runtime$NodeHandle[address=0x7f72840c02d0,position=0,limit=0,capacity=0,deallocator=null]>,
           :tvm-type-index 1,
           :tvm-type-kwd nil}],
  :tvm-jcpp-handle #<tvm_clj.tvm.runtime$NodeHandle@5e304b13 tvm_clj.tvm.runtime$NodeHandle[address=0x7f72846fffc0,position=0,limit=0,capacity=0,deallocator=null]>,
  :tvm-type-index 47,
  :tvm-type-kwd nil},
 :shape [#tvm_clj.base.NodeHandle
         {:tvm-jcpp-handle #<tvm_clj.tvm.runtime$NodeHandle@2a4a4b7 tvm_clj.tvm.runtime$NodeHandle[address=0x7f72847000a0,position=0,limit=0,capacity=0,deallocator=null]>,
          :tvm-type-index 1,
          :tvm-type-kwd nil}],
 :tvm-jcpp-handle #<tvm_clj.tvm.runtime$NodeHandle@7e7441ab tvm_clj.tvm.runtime$NodeHandle[address=0x7f72846fff20,position=0,limit=0,capacity=0,deallocator=null]>,
 :tvm-type-index 60,
 :tvm-type-kwd nil,
 :value_index 0}
```

I created a variable 'n', and I created a placeholder 'A'.  I then dereferenced all of the fields on both objects using node-get-field-names  and node-get-attr.

Let's say I finish my work here (although I obviously haven't computed anything).

How many times should TVMNodeFree be called at this point and on which objects?  What are the rules governing this?

For instance, if TVMNodeGetAttr returns a TVMValue that points to a TVMNodeHandle, should this node-handle be freed?

**Comment by tqchen** [comment]
when you get a NodeHandle in front end, you should always call NodeFree to free it when it goes out of scope. So for instance, we should free the handle returned by TVMNodeGetAttr

**Comment by cnuernber** [comment]
OK, this makes sense.  In particular, the address returned for the variable 'n', which is represented above 3 different times is different for each time.  In particular, 
* the call to (variable "n"): `0x7f72846d3000`
* the shape of the placeholder: `0x7f72847000a0`
* the shape of placeholder.op: `0x7f72840c02d0`

Thus, in this instance, the logical variable 'n' would be freed 3 times from the binding code.

If this is an accurate understanding, do you mind if I close this bug?

**Comment by tqchen** [comment]
Yes
