### ISSUE TITLE
Error while running Tvm on Android with OpenCL

### ISSUE THREAD

**Issue by dayanandasiet** [dmlc/tvm#921]
@tqchen 

Am trying to run android rpc test script (https://github.com/dmlc/tvm/tree/master/apps/android_rpc) "Build with OpenCL" with my following environment with OpenCL enable in make/config.mk.  

Environment : 
Laptop::
Description:	Ubuntu 17.10
Release:	17.10
Target::
Huawei Mate 9
Mali G71 GPU

Error :
```
xxxxxxx@Dayananda:~/shared-windows7/nnvm/nnvm/tvm/apps/android_rpc$ python tests/android_rpc_test.py 
TVM: Initializing cython mode...
[16:03:39] src/runtime/opencl/opencl_device_api.cc:190: No OpenCL platform matched given existing options ...
Traceback (most recent call last):
  File "tests/android_rpc_test.py", line 75, in <module>
    test_rpc_module()
  File "tests/android_rpc_test.py", line 34, in test_rpc_module
    f = tvm.build(s, [A, B], "opencl", target_host=target, name="myadd")
  File "/home/xxxxxxx/.local/lib/python3.6/site-packages/tvm-0.2.0-py3.6-linux-x86_64.egg/tvm/build_module.py", line 449, in build
    mdev = codegen.build_module(fdevice, str(target_device))
  File "/home/xxxxxxx/.local/lib/python3.6/site-packages/tvm-0.2.0-py3.6-linux-x86_64.egg/tvm/codegen.py", line 20, in build_module
    return _Build(lowered_func, target)
  File "/home/xxxxxxx/.local/lib/python3.6/site-packages/tvm-0.2.0-py3.6-linux-x86_64.egg/tvm/_ffi/function.py", line 255, in my_api_func
    return flocal(*args)
  File "tvm/_ffi/_cython/./function.pxi", line 264, in core.FunctionBase.__call__
  File "tvm/_ffi/_cython/./function.pxi", line 213, in core.FuncCall
  File "tvm/_ffi/_cython/./function.pxi", line 205, in core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 131, in core.CALL
tvm._ffi.base.TVMError: b'[16:03:39] src/runtime/opencl/opencl_module.cc:94: Check failed: workspace_->context != nullptr No OpenCL device
```

Note : For compilation success purpose libOpenCl.so is pointing with "/usr/lib/x86_64-linux-gnu/libOpenCL.so.1"

Questions::
1. How to resolve this problem? 
2. "Build with OpenCL" tutorial i couldn't find any much information related to OpenCl installation??
3. Why tvm.build is depending on host libOpenCl.so?

tvm.build with CPU  is success but tvm.build with OPENCL is failure.

**Comment by tqchen** [comment]
TVM uses a cross compiler. For android, you will need to download specific OpenCL library from the vendor or find it in your phone.

**Comment by dayanandasiet** [comment]
@tqchen  
phone libOpenCl.so  is not compatible when we are trying to compile tvm with phone libOpenCl.so. So couldn't figure to resolve this problem.

**Comment by tqchen** [comment]
You don't have to build tvm itself with OpenCL library on phone. Instead, try link the final of compiled library to the phone OpenCL

**Comment by dayanandasiet** [comment]
@tqchen 

am facing above error which i mentioned in first post of this thread.
[](https://github.com/dmlc/tvm/blob/master/apps/android_rpc/tests/android_rpc_test.py)
`f = tvm.build(s, [A, B], "opencl", target_host=target, name="myadd")`

why this depend on OpenCl device while building on respective target? if in case depend where to configure to resolve this problem?

**Comment by tqchen** [comment]
it is fine to build your host code without opencl support, by setting USE_OPENCL=0 while still being able to cross compile to opencl

**Comment by dayanandasiet** [comment]
@tqchen 

you mean to be while building host code with target USE_OPENCL=0 and later cross compile host compiled  library and deploy on target host?

if in that case what could be the reason to enable USE_OPENCL=1 under [Build with OpenCL](https://github.com/dmlc/tvm/tree/master/apps/android_rpc) and run test script code [here](https://github.com/dmlc/tvm/blob/master/apps/android_rpc/tests/android_rpc_test.py)

**Comment by dayanandasiet** [comment]
@tqchen 

Thanks for your feedback, i understand the OPENCL macro in depth with android application.


Addition to this am not able to load DlTemsor.data from my input image running TVM standalone (excpet RPC)., from [this](https://github.com/dmlc/nnvm/blob/master/docs/how_to/deploy.md) reference code will you please provide how "cat.bin" is created??

```
    std::ifstream data_fin("cat.bin", std::ios::binary);
    data_fin.read(static_cast<char*>(x->data), 3 * 224 * 224 * 4);
```

**Comment by tqchen** [comment]
You can ignore cat.bin as that is the image data. You can simply create your own TVMArray in java and feed it to TVM

**Comment by siju-samuel** [comment]
Do we need to add topi compute and schedule in CPP to support for running in Android device with OpenCL? or the ones with python alone can work fine?

**Comment by huanglishan6** [comment]
Please I don't know how to link the opencl library for RK3288.
"The cross compiled library: runs on your phone, this must be built with USE_OPENCL=1, and link to proper opencl library on your phone"
Help
