### ISSUE TITLE
Enhance cache_write to support multiple outputs

### ISSUE THREAD

**Issue by libing4752** [dmlc/tvm#933]
I tried to add schedule to argmax with topi.argmax, when using compute_inline , tvm raise errors:
    
    tvm._ffi.base.TVMError: [11:33:22] /nnvm/tvm/src/pass/inline.cc:61: Check failed: f->num_outputs() == 1 (2 vs. 1) can only inline output single value operation

and whe using cache_write, I get:

    tvm._ffi.base.TVMError: [13:34:16] /nnvm/tvm/src/schedule/schedule_dataflow_rewrite.cc:231: Check failed: compute->num_outputs() == 1 (2 vs. 1) cache write only support single output ComputeOp

DSL code is:
    
    import tvm, topi
    data = tvm.placeholder((256,256), dtype = "float16", name = "data")
    res = topi.argmax(data, axis = 0)
    s = tvm.create_schedule(res.op)
    #s[res.op.input_tensors[0]].compute_inline()
    s.cache_write(res.op.input_tensors[0],"local")
    print(tvm.lower(s, [data, res], simple_mode = True))

the IR code with no schedule is:

    // attr [0] pragma_scope = "device"
    // attr [data_red_temp.v0] storage_scope = "global"
    allocate data_red_temp.v0[int32 * 256]
    // attr [data_red_temp.v1] storage_scope = "global"
    allocate data_red_temp.v1[float16 * 256] 
    produce data_red_temp {
      for (i0, 0, 256) {
         data_red_temp.v0[i0] = -1
        data_red_temp.v1[i0] = -65504.000000h
        for (k0, 0, 256) {
          data_red_temp.v0[i0] = tvm_if_then_else((data_red_temp.v1[i0] < data[(i0 + (k0*256))]), k0, data_red_temp.v0[i0])
          data_red_temp.v1[i0] = tvm_if_then_else((data_red_temp.v1[i0] < data[(i0 + (k0*256))]), data[(i0 + (k0*256))], data_red_temp.v1[i0])
        }
      }
    }
    produce data_red {
      for (i0, 0, 256) {
        data_red[i0] = data_red_temp.v0[i0]
      }
    }

to simplify the case, my first step is to do cache_write, and expected IR is:

    for (i0, 0, 256)
        for (i1, 0, 256)
           data.local[i0 * 256 + i1] =  data[i0 * 256 + i1]

    produce data_red_temp {
      for (i0, 0, 256) {
        data_red_temp.v0.local[i0] = -1
        data_red_temp.v1.local[i0] = -65504.000000h
        for (k0, 0, 256) {
          data_red_temp.v0.local[i0] = tvm_if_then_else((data_red_temp.v1.local[i0] < data.local[(i0 + (k0*256))]), k0, data_red_temp.v0.local[i0])
          data_red_temp.v1.local[i0] = tvm_if_then_else((data_red_temp.v1.local[i0] < data.local[(i0 + (k0*256))]), data.local[(i0 + (k0*256))], data_red_temp.v1.local[i0])
        }
      }
    }
    for (i0, 0, 256) {
        data_red[i0] = data_red_temp.v0.local[i0]
      }

the XXX.local data is data in local buffer, so how can I do cache_write on computeOp with more than ONE outputs, Or  to evade this problem by some tricky use like construct two stages

**Comment by tqchen** [comment]
The cache_write is equivalent to directly create a stage 

```python
# result of cache local
index, value = topi.argmax(input)
# copy stage
data_global = tvm.compute(data_red_local[0].shape, 
      lambda *i: (index(*i), value(*i)))
```

**Comment by libing4752** [comment]
Thanks very much!! I tried with set_scope, and simulate cache_write successfully. So should we  wrapped the them together?

**Comment by tqchen** [comment]
We can enhance cache_write to support such case of multiple outputs

**Comment by tqchen** [comment]
@libing4752 any updates on this?

**Comment by libing4752** [comment]
Sorry for the late to reply. I'm looking a problem when I tried to tensorize on the axis of  argmax part, for example , `i2` axis in the following IR code : 

     for (i2, 0, 510) {
            data_red_temp.v0[i2] = tvm_if_then_else((data_red_temp.v0[(i2 + 1024)] < data_red_temp.v0[(i2 + 1536)]), k0, data_red_temp.v0[i2])
            data_red_temp.v0[(i2 + 1024)] = tvm_if_then_else((data_red_temp.v0[(i2 + 1024)] < data_red_temp.v0[(i2 + 1536)]), data_red_temp.v0[(i2 + 1536)], data_red_temp.v0[(i2 + 1024)])
          }

this problem cost me some times. I can enhance cache_write first and try to fix this issue in this week.

**Comment by libing4752** [comment]
sorry for the late to update msg. I tried the case of argmax in python code with set_scope and it works fine. But the case is cache_write + compute_inline. But when I tried to realize single cache_write with python code, I find some problems.

**Comment by libing4752** [comment]
The difference of process between python programming and C++ programming is that, In python programming ,we change scope of computeOp and add two computeOp from cache to DDR.I C++ code , we insert a new computeOp to the stage and substitute orig_stage to new stages.
