### ISSUE TITLE
It appears to be a bug. invoking .dll failed. 

### ISSUE THREAD

**Issue by BigJerry** [dmlc/tvm#940]
I constructed a simple network using nnvm.symbol system. The network only contain two layers: inputs and nnvm.symbol.conv2d_transpose. Compiling this network succeeded , but the generated dll could not be invoked and an error was thrown -----OSError: exception: access violation reading 0x00000007023FFD7C.

**Comment by BigJerry** [comment]
here's how I construct the network:
def op_to_test(layout):
    inputs = sym.Variable("data")
    outputs = sym.conv2d_transpose(data=inputs,channels=1,groups=1,
                                  kernel_size=(4,4),strides=(2,2),
                                  padding=(1,1),use_bias=False,
                                  layout=layout,name='test_op')
    return outputs

**Comment by BigJerry** [comment]
here's how I compile it:
    with nnvm.compiler.build_config(opt_level=3):
        with tvm.build_config(auto_unroll_max_step=128,
                              auto_unroll_max_depth=4,
                              unroll_explicit=False,
                              double_buffer_split_loop=50):
            graph_net, lib, params = nnvm.compiler.build(test_op, 
                                target='cuda', shape={"data":data_shape}, 
                                dtype="float32",params=params)

**Comment by tqchen** [comment]
It would be great if you can provide a complete python script that can reproduce the problem, which helps us to look into it.

**Comment by BigJerry** [comment]
This is the script to generate and save dll file.

`import numpy as np
import tvm
import nnvm
from nnvm import symbol as sym
from tvm.contrib import nvcc,util

@tvm.register_func
def tvm_callback_cuda_compile(code):
    ptx = nvcc.compile_cuda(code, target="ptx")
    return ptx
        
def save_module(module,graphpath,libpath,paramspath):
    temp = util.tempdir()
    for m in module:
        if isinstance(m,nnvm.graph.Graph):
            with open(temp.relpath(graphpath),"w") as f:
                f.write(m.json())
        elif isinstance(m,tvm.module.Module):
            libpath = temp.relpath(libpath)
            m.export_library(libpath)
        else:
            with open(temp.relpath(paramspath),"wb") as f:
                f.write(nnvm.compiler.save_param_dict(m))
    
def op_to_test(layout):
    inputs = sym.Variable("data")
    outputs = sym.conv2d_transpose(data=inputs,channels=1,groups=1,
                                  kernel_size=(4,4),strides=(2,2),
                                  padding=(1,1),use_bias=False,
                                  layout=layout,name='upsampling_L2_1_prime')
    return outputs
    
def extract_params(ctx):
    params = {}
    params['upsampling_L2_1_prime_weight'] = tvm.nd.array(np.random.random_sample((1,1,4,4)).astype(np.float32),ctx=ctx)  #generate random weight
    return params
    
if __name__=='__main__':
    paramspath = r'path\to\save\test_op.params'
    libpath = r'path\to\save\test_op.dll'
    graphpath = r'path\to\save\test_op.json'
    ctx = tvm.gpu(0)
    layout = "NCHW"
    image_shape = (1,128,160)
    batch_size = (1,)
    data_shape = batch_size + image_shape
    #construct model
    op = op_to_test(layout)
    print("model constructed.")
    #extract params
    params = extract_params(ctx)
    print("params have been prepared.")
    #compilation
    print("now compiling...")
    with nnvm.compiler.build_config(opt_level=3):
        with tvm.build_config(auto_unroll_max_step=128,
                              auto_unroll_max_depth=4,
                              unroll_explicit=False,
                              double_buffer_split_loop=50):
            graph_net, lib, params = nnvm.compiler.build(op, 
                                target='cuda', shape={"data":data_shape}, 
                                dtype="float32",params=params)
    print("finished!")
    module = (graph_net,lib,params)
    save_module(module,graphpath,libpath,paramspath)`

**Comment by BigJerry** [comment]
This is the script to load and run dll.

`import tvm
import numpy as np
from tvm.contrib import graph_runtime,util

def load_module(graphpath,libpath,paramspath):
    temp = util.tempdir()
    loaded_lib = tvm.module.load(temp.relpath(libpath))
    loaded_json = open(temp.relpath(graphpath)).read()
    loaded_params = bytearray(open(temp.relpath(paramspath),"rb").read())
    module = graph_runtime.create(loaded_json, loaded_lib, tvm.gpu(0))
    module.load_params(loaded_params)
    return module
    
def run_module(module,input_data):
    module.run(data=input_data)
    output = module.get_output(0,out=tvm.nd.empty(1,1,256,320))
    return output.asnumpy().reshape((256,320))
    
if __name__ == '__main__':
    paramspath = r'path\to\test_op.params'
    libpath = r'path\to\test_op.dll'
    graphpath = r'path\to\test_op.json'
    data_shape = (1,1,128,160)
    inputs = np.random.random_sample(data_shape).astype(np.float32)
    module = load_module(graphpath,libpath,paramspath)
    outputs = run_module(module,inputs)`

**Comment by tqchen** [comment]
closing due to inactive status and not being able to act further on this. further discussions are encouraged at https://discuss.tvm.ai
