### ISSUE TITLE
[FRONTEND] device stream management

### ISSUE THREAD

**Issue by cnuernber** [dmlc/tvm#943]
The C-ABI has calls for setting the current (thread?) stream and stream sync.  It doesn't have calls for creating the stream in the first place.  There is no creation mechansim for TVMStreamHandle.  

No where in the entire cuda bindings is cudaStreamCreate called.  

This makes the bindings somewhat incomplete, matching create/free calls for streams must be somewhere when the system is actually used else you can't do something like interleaving compute and memory transfer in a device independent way.

**Comment by tqchen** [comment]
We can add TVMStreamCreate and TVMStreamFree API to the runtime, are you interested in taking a stab on this?

**Comment by cnuernber** [comment]
It would be my pleasure.  I don't know that I can speak for every backend but cpu, cuda, opencl I can do this for.

A stream is a method of serializing commands.  This means that streams on the CPU may be bound to actual CPU streams; an abstraction I have used in the past with success; it means the cpu device semantics (and error conditions) match closer to the GPU than if the CPU has no threads or implements them in other ways.  For instance not synchronizing between streams correctly when doing memory transfer will appear to mis-behave similarly on both cpu and gpu *if* the cpu streams are actually based on actual threads.

What I don't know is how this compares to webassembly or opengl.  I think (the stream abstraction) also maps pretty precisely to vulkan but I would have to research it.  As long as the changes are additive and thought out then perhaps we can use the device attribute system to indicate what is exposed and what is not; then code can choose how to react if the new api isn't there for some different backend.



What do you think about the API presented here:

```clojure
(defprotocol PStream
  "Basic functionality expected of streams.  Streams are an abstraction of a stream of execution
and can be synchonized with the host or with each other using events."
  (copy-host->device [stream host-buffer device-buffer byte-count])
  (copy-device->host [stream device-buffer host-buffer byte-count])
  (copy-device->device [stream dev-a dev-b byte-count])
  (create-event [stream]
    "Create an event for synchronization.  The event is triggered when the stream
executes to the event.")
  (sync-event [stream event]
    "Have this stream pause until a given event is triggered."))

(defprotocol PEvent
  (wait-for-event [event]
    "Wait on the host until an event is triggered."))

(defprotocol PDevice
  (memory-info [device]
    "Get a map of {:free <long> :total <long>} describing the free and total memory in bytes.")
  (create-stream [device]
    "Create a stream of execution.  Streams are independent threads of execution.  They can be synchronized with each other and the main thread using events.")
  (allocate-device-buffer [device byte-count]
    "Allocate a device buffer.  This is the generic unit of data storage used for computation.")
  (free-device-buffer [buf-ptr]))
```

I think not all of it is required and the interfaces exposed allow me to do 90% of this already, just in a somewhat more tedious way.  

We can discuss more of this later; at the end of the day I need to know:
1.  cpu streams...threads ok?
2.  stream-to-stream event synchronization?  Important once you start juggling streams.

**Comment by cnuernber** [comment]
How about I do this for cuda and opencl.  I can mimic streams myself in the jvm for the cpu, I don't need to add the code to tvm.  For Vulkan, a stream would correspond to being able to create a vctx.queue.  For web assembly and node.js, a stream really would be a web-worker.  

So I will implement stream management and a bit more of the event api for only cuda and opencl alone and submit that as an initial PR.  I can continue what I am working on (a tvm-backed implementation of the compute abstraction out of cortex) from there.

**Comment by cnuernber** [comment]
https://github.com/dmlc/tvm/pull/953

**Comment by tqchen** [comment]
Close this for now, we can followup with PRs with more stream API support for other devices
