### ISSUE TITLE
[FRONTEND] device enumeration

### ISSUE THREAD

**Issue by cnuernber** [dmlc/tvm#944]
I am missing a way to query for the number of devices of a given device type in the backend api.  So if a system has 2 GPU's, how does one ascertain this fact?  

I think I am missing part of the abstraction somewhere.

**Comment by tqchen** [comment]
For now we can do things like
```
tvm.gpu(i).exist
```

to check if such device exist, a query listing API would have been better, but this one also serves most of the purposes.

**Comment by cnuernber** [comment]
got it, makes sense.
