### ISSUE TITLE
TVM support on Android with OpenCL

### ISSUE THREAD

**Issue by siju-samuel** [dmlc/tvm#947]
With reference to the issue,https://github.com/dmlc/tvm/issues/921   i want to know one thing.

Do we need to add topi compute and schedule in CPP to support for running in Android device with OpenCL? or the ones with python alone can work fine?

**Comment by tqchen** [comment]
no, the current example should run fine

**Comment by sgxu** [comment]
Now I get the cross-compiled xxx_aarch64.so, but how can I use this lib in android? I can hardly find the C++ API.
I want to write a android app using the cross-compiled xxx_aarch64.so, can you give some examples ?
@tqchen @ezyang
