### ISSUE TITLE
./topi/recipe/conv/depthwise_conv2d_test.py Segmentation Fault when USE_MANUAL_CODE is set to True

### ISSUE THREAD

**Issue by moderato** [dmlc/tvm#952]
Hello! I encountered a weird bug when I run the depthwise conv2d unit test. The code throws me a segmentation fault when I simply set USE_MANUAL_CODE to True and try to test the manual kernel which is a duplicate of the generated CUDA kernel. The TVM is built with Ubuntu 16.04 and CUDA 9.0. Anyone has an idea of the cause of this bug? Thanks!

**Comment by tqchen** [comment]
no idea what is the problem in here. Likely there is some mismatch in code, can you debug a bit? For example, print out again the cuda code in the module by
```python
print(mod.imported_modules[0].get_source())
```

and see if it really matches to the case that is generated

**Comment by tqchen** [comment]
close due to inactivity, feel free to reopen
