### ISSUE TITLE
[FRONTEND] Lower level bindings to device memory

### ISSUE THREAD

**Issue by cnuernber** [dmlc/tvm#959]
Currently the only bindings to device memory are through the array interface.

I would like access to the actual device api bindings (alloc/free/copy data space).  The reason is so that I can have more flexibility with how I update parts of my tensors and in fact so in some cases I can allocate a large block of memory that is some times interpreted as a single tensor and sometimes interpreted as many different tensors with potentially conflicting or overlapping shapes.  Or so I can repeated update small parts of a larger tensor or any number of things.

In any case, there are 3 paths I could go down to get the functionality I would like to use:

1.  update c_runtime_api.h/cc [TVM PR]
2.  update update c_device_api.h/cc [TVM PR]
3.  Build a header-only addition when I am building my JNI bindings so that only the jvm systems have access to the lower level primitives and hook directly into device_api.h during the jni-build [cowboy all the way].

Which pathway is most appropriate at this time?

**Comment by tqchen** [comment]
The simplest thing to build on top of current API, is that you can allocate a Tensor of 1D and re-interpret that, by setting same header but different offset. 

One thing that we need to be particularly careful about though, is that not all memory are addressable. i.e. we cannot take a single chunk of device ptr, add an offset and get another slice. The DLTensor 's byte_offset mechanism is used to combat this.

**Comment by cnuernber** [comment]
I have tried the reinterpret currently but I didn't realize that not all backends' memory is byte or word or double-word addressable.  This fact means that my work around will only work on a backend where the memory handle is in fact byte or word addressable.

Cuda, cpu, openCL all are.  I can see now, however, that openGL and maybe not vulcan and who knows in the future.  Do you know offhand how many backends are not word-addressable?  I see now the byte-offset mechanism is a way to work around something like an openGL buffer handle; thank you for that I had not realized this.

I am not certain that we want to expose the device API yet and I don't want expose an API that later we decide was a mistake so if I could have just a little more of your time.  I will then go off and make it happen.

Here is the API for the tech.compute low level compute system:
```clojure
(defprotocol PStream
  "Basic functionality expected of streams.  Streams are an abstraction of a stream of execution
and can be synchonized with the host or with each other using events."
  (copy-host->device [stream host-buffer host-offset
                      device-buffer device-offset elem-count])
  (copy-device->host [stream device-buffer device-offset
                      host-buffer host-offset elem-count])
  (copy-device->device [stream dev-a dev-a-off dev-b dev-b-off elem-count])
  (memset [stream device-buffer device-offset elem-val elem-count])
  (create-event [stream]
    "Create an event for synchronization.  The event is triggered when the stream
executes to the event.")
  (sync-event [stream event]
    "Have this stream pause until a given event is triggered."))
```

Even without exposing a buffer offset mechanism, the copy operations allow for datatype-sized offsets and an element count.

Here is the device API analogue and it matches roughly above with the exception that every backend for tvm now has to have logic to divine if it is a host->device or device->host or device->device operation:

```C++
virtual void CopyDataFromTo(const void* from,
                              size_t from_offset,
                              void* to,
                              size_t to_offset,
                              size_t size,
                              TVMContext ctx_from,
                              TVMContext ctx_to,
                              TVMStreamHandle stream) = 0;
```

Here is the runtime api (comments elided):
```C
TVM_DLL int TVMArrayCopyFromBytes(TVMArrayHandle handle,
                                  void* data,
                                  size_t nbytes);
TVM_DLL int TVMArrayCopyToBytes(TVMArrayHandle handle,
                                void* data,
                                size_t nbytes);
TVM_DLL int TVMArrayCopyFromTo(TVMArrayHandle from,
                               TVMArrayHandle to,
                               TVMStreamHandle stream);
```

So looking at this I see 5 things relevant to this discussion:

1.  The device API matches the compute stream api...because compute streams operate at the same level as the device.
2.  No stream parameter in either array copy to or array copy from.  This I believe is an oversight; for cuda at least the stream is very important and using a null stream means you are using the default stream which enforces blocking semantics that are absolutely not optimal, especially if you are copying several separate things.
3.  No offset provided to allow copying sub-portions of data.
4.  No byte count provided to allow copying sub-portions of data.
5.  No formal access to the byte_offset mechanism we were talking about above.  In fact, searching the codebase I don't see it being assigned to often but I do see it being used in computation.

Given the above, it does seem to me that exposing the lower level device API to the the jvm runtime is the most logical option.  The alternative would be adding new copy from/to functions for arrays that look like clumsier, more verbose versions of the device api.
  
What do you think about this line of reasoning?

**Comment by cnuernber** [comment]
Closing this.  After re-reading tqchen's comment I read the runtime's TVMArrayCopyFromTo code.  I can do anything with TVMArrayCopyFromTo.  It will work with no further changes to tvm and the byte_offset mechanism's point is clear to me now which means I can in fact do offsetting like suggested.  It just hadn't occurred to me to always use cpu arrays on the host side and of course I hadn't seen the offsetting mechanism.
