### ISSUE TITLE
anyone getting this compilation error about logging.h ?

### ISSUE THREAD

**Issue by siju-samuel** [dmlc/tvm#961]
g++ -c -std=c++11 -Wall -O2 -Iinclude -I/workspace/dlpack/include -I/workspace/dmlc-core/include -IHalideIR/src -Itopi/include -fPIC -DTVM_CUDA_RUNTIME=0 -DTVM_ROCM_RUNTIME=0 -DTVM_OPENCL_RUNTIME=0 -DTVM_VULKAN_RUNTIME=0 -DTVM_OPENGL_RUNTIME=1 -DTVM_METAL_RUNTIME=0 -c src/pass/split_pipeline.cc -o build/pass/split_pipeline.o

g++ -c -std=c++11 -Wall -O2 -Iinclude -I/workspace/dlpack/include -I/workspace/dmlc-core/include -IHalideIR/src -Itopi/include -fPIC -DTVM_CUDA_RUNTIME=0 -DTVM_ROCM_RUNTIME=0 -DTVM_OPENCL_RUNTIME=0 -DTVM_VULKAN_RUNTIME=0 -DTVM_OPENGL_RUNTIME=1 -DTVM_METAL_RUNTIME=0 -c src/pass/ssa.cc -o build/pass/ssa.o

## make: *** No rule to make target 'include/tvm/logging.h', needed by 'build/pass/arg_binder.o'.  Stop.

make: *** Waiting for unfinished jobs....

**Comment by tqchen** [comment]
was due to build cache problem in jenkins, cleaning up the workspace and retrigger test will resolve this, just ping me when your test encounter this problem
