### ISSUE TITLE
Error in "python setup.py install --user"

### ISSUE THREAD

**Issue by algoton** [dmlc/tvm#964]
Hi I am new to TVM. I have followed the installation guide but seen below error in compiling the TVM python binding. Any suggestion on what could be wrong here:

sxie@ /home/proj/flow/tvm/python [124]% python setup.py install --user
Compiling tvm/_ffi/_cython/core.pyx because it changed.
Cythonizing tvm/_ffi/_cython/core.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        DLContext ctx
        int ndim
        DLDataType dtype
        int64_t* shape
        int64_t* strides
        uint64_t byte_offset;
                           ^
------------------------------------------------------------

tvm/_ffi/_cython/./base.pxi:40:28: Syntax error in C variable declaration
Traceback (most recent call last):
  File "setup.py", line 122, in <module>
    ext_modules=config_cython(),
  File "setup.py", line 80, in config_cython
    return cythonize(ret)
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 713, in cythonize
    cythonize_one(*args[1:])
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 780, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: tvm/_ffi/_cython/core.pyx

**Comment by tqchen** [comment]
seems that uint64_t is not defined in your system

**Comment by tqchen** [comment]
OK, after take a second look at the error message, this seems can be fixed by remove the ```;``` at https://github.com/dmlc/tvm/blob/master/python/tvm/_ffi/_cython/base.pxi#L40 

Interestingly it does not affect the system that I have. Can you try to do the update and see if the fix works for you? If it does, please send a PR to TVM so this fix can help others who have the same situation as you do. Thanks for reporting the issue

**Comment by algoton** [comment]
After removing ";" from these three lines from tvm/_ffi/_cython/./base.pxi:

Line 40:   uint64_t byte_offset;
Line 67:   void TVMAPISetLastError(const char* msg);
Line 68:   const char *TVMGetLastError();

Now new error like this. FYI I am using centOS 7.

xie@ /home/proj/flow/tvm/python [112]% python setup.py install --user
Compiling tvm/_ffi/_cython/core.pyx because it changed.
Cythonizing tvm/_ffi/_cython/core.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        tcode[0] = kFuncHandle
        temp_args.append(arg)
    else:
        raise TypeError("Don't know how to handle type %s" % type(arg))

cdef inline bytearray make_ret_bytes(void* chandle):
           ^
------------------------------------------------------------

tvm/_ffi/_cython/./function.pxi:156:12: 'bytearray' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        CALL(TVMNodeFree(self.chandle))

    def __getattr__(self, name):
        cdef TVMValue ret_val
        cdef int ret_type_code, ret_succ
        CALL(TVMNodeGetAttr(self.chandle, c_str(name),
                                              ^
------------------------------------------------------------

tvm/_ffi/_cython/./node.pxi:59:47: Obtaining 'char const *' from temporary Python value

Error compiling Cython file:
------------------------------------------------------------
...
            pyargs.append(c_make_array(value.v_handle, True))
    try:
        rv = local_pyfunc(*pyargs)
    except Exception:
        msg = traceback.format_exc()
        TVMAPISetLastError(c_str(msg))
                               ^
------------------------------------------------------------

tvm/_ffi/_cython/./function.pxi:42:32: Obtaining 'char const *' from temporary Python value
Traceback (most recent call last):
  File "setup.py", line 122, in <module>
    ext_modules=config_cython(),
  File "setup.py", line 80, in config_cython
    return cythonize(ret)
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 713, in cythonize
    cythonize_one(*args[1:])
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 780, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: tvm/_ffi/_cython/core.pyx

**Comment by tqchen** [comment]
OK, please try update your cython, it seems likely due to the low version of your cython

**Comment by algoton** [comment]
Compile worked after upgrading to python2-Cython-0.25.2-3.el7.x86_64.rpm

Thx.
