### ISSUE TITLE
API question (ir_pass module)

### ISSUE THREAD

**Issue by cnuernber** [dmlc/tvm#965]
My question pertains to exactly when the compilation system will produce both device and host functions and when it will only produce host functions.

Here are the relevant details of the python target constructor:
```python
        self.thread_warp_size = 1
        if target_name in ("llvm", ):
            self.keys += ("cpu",)
        elif target_name in ("cuda", "nvptx"):
            self.keys += ("cuda", "gpu")
            self.max_num_threads = 512
            self.thread_warp_size = 32
        elif target_name in ("rocm", "opencl"):
            # For now assume rocm schedule for opencl
            self.keys += ("rocm", "gpu")
            self.max_num_threads = 256
        elif target_name in ("metal", "vulkan"):
            self.keys += (target_name, "gpu",)
            self.max_num_threads = 256
        elif target_name in ("opengl",):
            self.keys += ("opengl",)
        elif target_name in ("stackvm", "ext_dev"):
            # Do not now class for stackvm or ext_dev
            pass
        else:
            raise ValueError("Unknown target name %s" % target_name)
```

The thread warp size is only ever *not* one if the target is cuda or nvptx.  This means that, for instance, opencl will have a thread warp size of 1.

Here are the relevant details of the python compilation system:
```python
for func in flist:
        if func.func_type == container.LoweredFunc.MixedFunc:
            if BuildConfig.current.detect_global_barrier:
                func = ir_pass.ThreadSync(func, "global")
            func = ir_pass.ThreadSync(func, "shared")
            warp_size = target.thread_warp_size
            func = ir_pass.LowerThreadAllreduce(func, warp_size)
            fsplits = [s for s in ir_pass.SplitHostDevice(func)]
            fhost.append(fsplits[0])
            for x in fsplits[1:]:
                fdevice.append(x)
        elif func.func_type == container.LoweredFunc.HostFunc:
            fhost.append(func)
        elif func.func_type == container.LoweredFunc.DeviceFunc:
            fdevice.append(func)
        else:
            raise ValueError("unknown function type %d" % func.func_type)

    if "gpu" in target.keys and not fdevice:
        warnings.warn(
            "Specified target %s, but cannot find device code, did you do bind?" % target)
```

It appears to me that device functions are only created if the ir_pass.LowerThreadAllreduce pass receives a warp size != 1.

This *only* ever happens for cuda.  Never for any of the other tvm backends.  Hence the final error message in the second bit of code above.

1.  Did I read this code correctly?
2.  Is this the intended behavior?

**Comment by cnuernber** [comment]
(Answering part of my question)

1.  No, there is more to it.

```python
            if "cpu" not in target.keys:
                s[B].bind(bx, tvm.thread_axis("blockIdx.x"))
                s[B].bind(tx, tvm.thread_axis("threadIdx.x"))
```

This paradigm is used throughout the unit tests.  This means that these backends:
```python
        check_device("llvm")
        check_device("cuda")
        check_device("opencl")
        check_device("metal")
        if dtype == "uint32":
            check_device("vulkan")
```
 non-cpu backends have the same 2-level breakdown of blocks and threads that Cuda introduced.

And for this specific test (popcount), vulkan only supports uint32.  

As to the second part; max_num_threads and thread_warp_size...

max_num_threads seems like an extremely odd property to have on the target and not on the device.  There is no device attribute for this property.  And I believe it is 3 orders of magnitude too low for a modern gpu.

**Comment by tqchen** [comment]
Your understanding is correct:) max_num_threads are attributes that actually works well for certain device, so these emperical number is used.
