### ISSUE TITLE
TVM error

### ISSUE THREAD

**Issue by pallabdatta** [dmlc/tvm#966]
Hi @tqchen 

I build TVM with LLVM support on my mac 10.13.3 with CUDA disabled. 
Now when I import a small toy graph with a bunch of conv2d nodes, add and Mul nodes and some other new nodes which I have registered according to your suggestion as per (https://github.com/dmlc/nnvm/issues/361) I get this new error..
Things were working fine before I did a git pull on nnvm/tvm couple of days back...
Any suggestions? 

A related question, if we are writing a new Pass in NNVM, and dont want that function to be lowered via TVM call ? is it possible? 
thanks so much,
pallab

>>> import nnvm.compiler
>>> target = 'llvm'
>>> shape_dict = {'input_0': a.shape}
>>> opt_level = 0
>>> with nnvm.compiler.build_config(opt_level=opt_level):
...     graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, params=params)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/pallabdatta/nnvm/python/nnvm/compiler/build_module.py", line 252, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/Users/pallabdatta/nnvm/python/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/Users/pallabdatta/nnvm/python/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "tvm/_ffi/_cython/./function.pxi", line 39, in core.tvm_callback
  File "/Users/pallabdatta/nnvm/python/nnvm/compiler/build_module.py", line 119, in _build
    return tvm.build(funcs, target=target, target_host=target_host)
  File "/Users/pallabdatta/anaconda/lib/python3.6/site-packages/tvm-0.2.0-py3.6-macosx-10.9-x86_64.egg/tvm/build_module.py", line 467, in build
    mhost = codegen.build_module(fhost, str(target_host))
  File "/Users/pallabdatta/anaconda/lib/python3.6/site-packages/tvm-0.2.0-py3.6-macosx-10.9-x86_64.egg/tvm/codegen.py", line 20, in build_module
    return _Build(lowered_func, target)
  File "/Users/pallabdatta/anaconda/lib/python3.6/site-packages/tvm-0.2.0-py3.6-macosx-10.9-x86_64.egg/tvm/_ffi/function.py", line 280, in my_api_func
    return flocal(*args)
  File "tvm/_ffi/_cython/./function.pxi", line 264, in core.FunctionBase.__call__
  File "tvm/_ffi/_cython/./function.pxi", line 213, in core.FuncCall
  File "tvm/_ffi/_cython/./function.pxi", line 205, in core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 131, in core.CALL
tvm._ffi.base.TVMError: b'[13:43:38] /Users/pallabdatta/nnvm/tvm/src/codegen/codegen.cc:27: Check failed: bf != nullptr Target llvm is not enabled\n\nStack trace returned 10 entries:\n[bt] (0) 0   libtvm.dylib                        0x0000000102e7119b dmlc::StackTrace() + 299\n[bt] (1) 1   libtvm.dylib                        0x0000000102e70f2f dmlc::LogMessageFatal::~LogMessageFatal() + 47\n[bt] (2) 2   libtvm.dylib                        0x0000000102ef61be tvm::codegen::Build(tvm::Array<tvm::LoweredFunc, void> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 414\n[bt] (3) 3   libtvm.dylib                        0x0000000102e79d1b std::__1::__function::__func<tvm::codegen::$_0, std::__1::allocator<tvm::codegen::$_0>, void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>::operator()(tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&) + 379\n[bt] (4) 4   libtvm.dylib                        0x00000001031cfbd8 TVMFuncCall + 72\n[bt] (5) 5   core.cpython-36m-darwin.so          0x00000001036394a2 __pyx_pw_4core_12FunctionBase_5__call__(_object*, _object*, _object*) + 482\n[bt] (6) 6   python                              0x0000000100b16cde PyObject_Call + 62\n[bt] (7) 7   python                              0x0000000100c66781 _PyEval_EvalFrameDefault + 47457\n[bt] (8) 8   python                              0x0000000100c59beb _PyEval_EvalCodeWithName + 427\n[bt] (9) 9   python                              0x0000000100c68cec fast_function + 348\n\n'

>>>

**Comment by tqchen** [comment]
the error message suggest that you built tvm not with llvm enabled, try to set LLVM_CONFIG correctly and rebuild with llvm enabled

**Comment by pallabdatta** [comment]
Thanks..that worked. 
As to my other Question, is it possible to do what I asked? 

Also I was wondering if there is a No-OP implementation in tvm registry? or can we implement an operator without having a lowering function or have a lowering function as an identity operator.

**Comment by tqchen** [comment]
if we want to do that for perf profiling reasons, the graph runtime now recognizes "__nop", also you can simply register one by yourself

**Comment by pallabdatta** [comment]
Thanks a lot..!!

**Comment by tqchen** [comment]
FYI https://github.com/dmlc/tvm/blob/master/src/runtime/graph/graph_runtime.cc#L563
Usually what I do is to replace the func_name in the final deploy graph to __nop

**Comment by shreyashvi** [comment]
Check failed: (bf != nullptr) is false: target.build.llvm is not enabled

I already do:
set(USE_LLVM ON)
set(USE_LLVM /usr/lib/llvm-10/bin/llvm-config)

in tvm/build/config.cmake

still this problem persist
