### ISSUE TITLE
Cannot build tvm with CUDA 

### ISSUE THREAD

**Issue by 103yiran** [dmlc/tvm#967]
I follow the [Installation Guide](https://github.com/dmlc/tvm/blob/master/docs/how_to/install.md) to build tvm with CUDA in Ubuntu. My operation is that 
```shell
cp make/config.mk .
vim config.mk
make -j
```
I got `-DTVM_CUDA_PATH = 0`, even if I have modefied the `USE_CUDA` option. 
Finilly, I used the CMake Configuration file and achieved compilation。

**Comment by PariksheetPinjari909** [comment]
Please enable CUDA_PATH = /usr/local/cuda also in config.mk file

**Comment by 103yiran** [comment]
Yes, I have done that. @PariksheetPinjari909

**Comment by PariksheetPinjari909** [comment]
edit the config.mk file in the 'make' folder itself
vi make/config.mk
make -j4

**Comment by 103yiran** [comment]
Still the same print. @PariksheetPinjari909

**Comment by tqchen** [comment]
This is strange. Unfortunately it is harder to reproduce locally. My guess is something get messed up in the Makefile or config, it would be great if you can dig into the Makefile to see what happened. Otherwise using the CMake would also solve the problem

**Comment by tqchen** [comment]
close due to inactivity, feel free to reopen if there is still problem

**Comment by lewisgit** [comment]
after I delete the whole line of USE_CUDA,
and insert a newline with USE_CUDA = 1
I get the compilation works fine with cuda

So I think there might be an encoding problem
