### ISSUE TITLE
questions about C++ API

### ISSUE THREAD

**Issue by sgxu** [dmlc/tvm#968]
Now I get the cross-compiled xxx_aarch64.so, but how can I use this lib in android? I can hardly find the C++ API.
I want to write a android app using the cross-compiled xxx_aarch64.so, can you give some examples ?
If I do not use rpc.

**Comment by srkreddy1238** [comment]
NNVM compilation results in xxx.so, xxx.params & xxx.graph.

[this](https://github.com/dmlc/nnvm/blob/master/docs/how_to/deploy.md) ref has a sample c++ native example to deploy above compiled model.

You could follow below steps to have android app with out RPC:
1 : tvm_runtime.so should be cross compiled for your target.
2 : Use above c++ reference implementation in android native linking tvm_runtime.so which can be invoked from android application via JNI. 

Siva

**Comment by edmBernard** [comment]
@sgxu 
```python
    with open("deploy_param.params", "wb") as fo:
        fo.write(nnvm.compiler.save_param_dict(params))
```

**Comment by tqchen** [comment]
close this issue as the question has been answered
