### ISSUE TITLE
Identity operator from ONNX

### ISSUE THREAD

**Issue by pallabdatta** [dmlc/tvm#969]
Hi @tqchen

Is the Identity operator defined in ONNX experimental Ops as 
in onnx/defs/experiments/defs.cc as 

OPERATOR_SCHEMA(Identity)
    .SetSupportLevel(SupportType::EXPERIMENTAL)
    .NumInputs(1)
    .NumOutputs(1)
    .SetDoc("Identity operator")
    .Input(0, "input", "Input tensor", "T")
    .Output(
        0,
        "output",
        "Tensor to copy input into.",
        "T")
    .TypeConstraint("T", { "tensor(float16)", "tensor(float)", "tensor(double)" },
        "Constrain input and output types to float tensors.");

implemented for import within NNVM? I see a copy operator in 
python/nnvm/frontend/onnx.py:    'Identity'      : Renamer('copy') ..is this the same?

**Comment by tqchen** [comment]
They are the same
