### ISSUE TITLE
Android Standalone Deployment Tutorial

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#973]
We have everything we need to deploy TVM compiled module directly to android without RPC. The http://www.tvmlang.org/2017/11/08/android-rpc-introduction.html contains all the necessary materials and a java runtime that we can reuse. We just need to make a tutorial on specifically this can be done

- [x] Tutorial under docs/how_to/deploy_android.md
- [x] Talk about how to use the java API
- [x] Talk about how to deploy opencl applications
- [ ] Talk about example on how to deploy vulkan applications

**Comment by PariksheetPinjari909** [comment]
I have some version of 

Tutorial under docs/how_to/deploy_android.md
Talk about how to deploy opencl applications

which I could cleanup and  PR soon. It basically explain up to running compiled model (llvm+opencl) on android native.

Siva

**Comment by PariksheetPinjari909** [comment]
Ref. https://github.com/dmlc/tvm/pull/978 PR for 1 & 3 for review.

**Comment by janboeye** [comment]
@PariksheetPinjari909 @tqchen 

which type is used in native for float16?
Thanks

**Comment by PariksheetPinjari909** [comment]
Are you referring to #980 deploy utility ?

If yes, now this example assumes imput & output types to be float32.
You need to check the platform(toolchain) types for float16 and modify the tool accordingly.

**Comment by janboeye** [comment]
@PariksheetPinjari909 
Yes, I refer to #980.

````
    cnpy::NpyArray in_arr = cnpy::npy_load(model_input + ".npy");
    float* loaded_data = in_arr.data<float>();
````
to
````
    cnpy::NpyArray in_arr = cnpy::npy_load(model_input + ".npy");
    uint16_t* loaded_data = in_arr.data<uint16_t>();
````
is right?

**Comment by PariksheetPinjari909** [comment]
Should be good as loaded_data is just an intermediate pointer before copying to input tensor.

Hope you have changed the dtype_code to float16 and created the input tensor.

Change the below as required to properly copy the loaded_data to input tensor x with out loss.
```
for (int ii=0; ii < num_samples; ii++)
    (static_cast<float*>(x->data) + x->byte_offset/4)[ii] = loaded_data[ii];
```

**Comment by janboeye** [comment]
@PariksheetPinjari909 
Yes, I created float16 input tensor.
I changed the code which you point out like following
````
    for (int ii=0; ii < num_samples; ii++)
        (static_cast<uint16_t*>(x->data) + x->byte_offset/2)[ii] = loaded_data[ii];
````
Is it ok?

**Comment by tqchen** [comment]
close by #980 open another Issue for vulkan tutorial
