### ISSUE TITLE
How to make the GPU to CPU memory copy faster?

### ISSUE THREAD

**Issue by siju-samuel** [dmlc/tvm#979]
Im running yolo model and the gpu to cpu copy (get_output) takes considerable amount of time. Any method to optimize this copy operation?

**Comment by cnuernber** [comment]
https://devblogs.nvidia.com/how-optimize-data-transfers-cuda-cc/

This may give you some ideas to start with.  In general you want to use pinned memory *and* you want to interleave computation with copying; so you want to be upload the next thing while you are computing the current thing while you are downloading the last thing.

I recommend nvprof.

**Comment by tqchen** [comment]
Please confirm if it is really the case, or because the copy is slow due to previously issued asynchronous CUDA functions. To check, do a ```tvm.gpu(0).sync()``` before you run get_output

**Comment by dayanandasiet** [comment]
@tqchen

We are using openCL(on Mali GPU), with tvm.cl(0).sync() still get_output(copying from GPU to CPU) is consuming comparatively more time. Where we can check to troubleshoot?

**Comment by dayanandasiet** [comment]
@tqchen

We are using openCL(on Mali GPU), with tvm.cl(0).sync() still get_output(copying from GPU to CPU) is consuming comparatively more time. Where we can check to troubleshoot?

**Comment by janboeye** [comment]
@dayanandasiet 
clEnqueueReadBuffer will take 3 seconds, right?

**Comment by dayanandasiet** [comment]
@janboeye 

not clEnqueueReadBuffer, instead clFinish consuming 2.7 seconds.

**Comment by tqchen** [comment]
If you are running this through RPC, then there could be rpc overhead through networking. 

The RPC overhead won't be the real problem when you are deploying it to the phone(and no RPC is used). If you just time the clEnqueueReadBuffer and see the perf on the Mali, you might get an idea on what the overhead is. But there is less we can do here because it is overhead of opencl runtime

**Comment by siju-samuel** [comment]
We tried both the methods, RPC and standalone APP.  The RPC overhead is negligible compared to OpenCL overhead. clEnqueueReadBuffer in synchronous/asynchronous mode will take 2.7seconds for me for each getoutput(gpu to  cpu copy). And the whole advantage of using GPU is lost with this delay. My output size is only 425x19*19 = 153425.  Any tricks to reduce this overhead?

**Comment by tqchen** [comment]
I am not very sure how does the cost compares in other cases. This definitely sound super slow compared to the memory bandwidth you could get, in mobile the CPU and GPU even shares the memory. I would recommend you do some standalone testing of just copy API in OpenCL and possibly report that to the related OpenCL driver writer

**Comment by janboeye** [comment]
@siju-samuel 

Could you add clFinish before clEnqueueReadBuffer and then measure the time consumed by  clEnqueueReadBuffer? Maybe it is not blocked by clEnqueueReadBuffer.

**Comment by dayanandasiet** [comment]
please find the performance bench mark for api invocation
```
Iteration 1. No any changes in Opencl_device_api.cc
set_input->(consume 186ms)
    ->CopyDataFromTo
        ->kDLOpenCL to kDLCPU
            ->clEnqueueWriteBuffer
            ->clFinish
get_output->(consume 2891ms)
    ->CopyDataFromTo
        ->kDLOpenCL to kDLCPU
            ->clEnqueueReadBuffer
            ->clFinish

Iteration 2. comment clFinish while clEnqueueReadBuffer Opencl_device_api.cc
set_input->(consume 3185ms)
    ->CopyDataFromTo
        ->kDLOpenCL to kDLCPU
            ->clEnqueueWriteBuffer
            ->clFinish
get_output->(consume 174ms)
    ->CopyDataFromTo
        ->kDLOpenCL to kDLCPU
            ->clEnqueueReadBuffer
            ->//clFinish

Iteration 3. comment clFinish for both clEnqueueWriteBuffer and clEnqueueReadBuffer Opencl_device_api.cc
set_input->(consume 257ms)
    ->CopyDataFromTo
        ->kDLOpenCL to kDLCPU
            ->clEnqueueWriteBuffer
            ->clFinish
get_output->(consume 54ms)
    ->CopyDataFromTo
        ->kDLOpenCL to kDLCPU
            ->clEnqueueReadBuffer
            ->//clFinish
```
Note Iteration 1 and 2 i can get proper output but in iteration 3 i don't get output from target.

**Comment by janboeye** [comment]
please add clFinish before clEnqueueReadBuffer in get_output, this will make sure all works finished by GPU before clEnqueueReadBuffer

**Comment by dayanandasiet** [comment]
@janboeye 

after add clfinish before clEnqueueReadBuffer in get_output, prediction is proper but operation consume 2855ms and memory copy slow still exist

**Comment by tqchen** [comment]
close this for now as the problem may not be on the tvm side bu on the opencl driver

**Comment by zhiics** [comment]
Did anyone look into this? I am also having the same problem. I split the graph into OpenCL part and GPU part. Three data copy nodes were inserted. It turned out that the first data copy operation takes about (2.7s), the second takes around 40ms, and the third one only needs ~0.5ms. Any idea why is it getting faster?

**Comment by daweili1226** [comment]
Samiliar issue here.

**Comment by eqy** [comment]
Please open a discuss board issue for this topic.
