### ISSUE TITLE
The implementation of function in the TVM

### ISSUE THREAD

**Issue by AndyQi93** [dmlc/tvm#992]
The function register in the NNVM, like
TVM_REGISTER_GLOBAL("nnvm.graph._move_graph")
.set_body([](TVMArgs args, TVMRetValue *rv) {
    const nnvm::Graph& g = args[0].AsExtension<Graph>();
    std::string key = args[1];
    if (g.attrs.count(key)) {
      *rv = const_cast<nnvm::Graph*>(&g)->
          MoveCopyAttr<nnvm::Graph>(key);
    } else {
      *rv = nullptr;
    }
  });
 
Could you tell me the next implementation in the TVM?

**Comment by tqchen** [comment]
check out http://docs.tvmlang.org/dev/index.html if you are asking for internal design details

**Comment by AndyQi93** [comment]
Thank you!

2018-03-12 12:57 GMT-04:00 Tianqi Chen <notifications@github.com>:
