### ISSUE TITLE
[TOPI] Support PReLU

### ISSUE THREAD

**Issue by sgxu** [dmlc/tvm#994]
Is there any plan to support PReLU ?

**Comment by tqchen** [comment]
PReLU can easily added given similar to http://docs.tvmlang.org/api/python/topi.html#topi.nn.leaky_relu

Contribution is more than welcomed

**Comment by sgxu** [comment]
in PReLU, the coefficient of leakage is learned, not a constant, so I need to modify struct LeakyReLUParam in nnvm?
// --------------------------------------------------------
struct LeakyReLUParam : public dmlc::Parameter<LeakyReLUParam> {
  double alpha;

  DMLC_DECLARE_PARAMETER(LeakyReLUParam) {
    DMLC_DECLARE_FIELD(alpha).set_lower_bound(0.0).set_default(0.25)
        .describe("slope coefficient for the negative half axis.");
  }
};
// --------------------------------------------------------

and modify NNVM_REGISTER_OP(leaky_relu) ?
