### ISSUE TITLE
RK3399 graph runtime error

### ISSUE THREAD

**Issue by yarneer** [dmlc/tvm#995]
tutorials example:
http://nnvm.tvmlang.org/tutorials/deploy_model_on_mali_gpu.html

How to solve this problem , thx 

======================
TVMError: Except caught from RPC call: [16:12:44] src/runtime/graph/graph_runtime.cc:485: Check failed: storage_id >= 0 (-1 vs. 0) Do not support runtime shape op

Stack trace returned 10 entries:
[bt] (0) /home/firefly/DL/tvm/lib/libtvm_runtime.so(dmlc::StackTrace[abi:cxx11]()+0x118) [0x7fb03abe40]
[bt] (1) /home/firefly/DL/tvm/lib/libtvm_runtime.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x44) [0x7fb03ac79c]
[bt] (2) /home/firefly/DL/tvm/lib/libtvm_runtime.so(tvm::runtime::GraphRuntime::SetupStorage()+0x670) [0x7fb0414930]
[bt] (3) /home/firefly/DL/tvm/lib/libtvm_runtime.so(tvm::runtime::GraphRuntimeCreate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::runtime::Module, int, int)+0x238) [0x7fb0415a00]
[bt] (4) /home/firefly/DL/tvm/lib/libtvm_runtime.so(+0x8d1b8) [0x7fb04161b8]
[bt] (5) /home/firefly/DL/tvm/lib/libtvm_runtime.so(tvm::runtime::RPCSession::EventHandler::HandlePackedCall()+0x2ec) [0x7fb03f4d4c]
[bt] (6) /home/firefly/DL/tvm/lib/libtvm_runtime.so(tvm::runtime::RPCSession::EventHandler::SwitchToState(tvm::runtime::RPCSession::EventHandler::State)+0x2bc) [0x7fb03fae8c]
[bt] (7) /home/firefly/DL/tvm/lib/libtvm_runtime.so(tvm::runtime::RPCSession::EventHandler::HandleRecvPackedSeqArg()+0x5f4) [0x7fb03fbd7c]
[bt] (8) /home/firefly/DL/tvm/lib/libtvm_runtime.so(tvm::runtime::RPCSession::EventHandler::HandleNextEvent(tvm::runtime::TVMRetValue*, bool, tvm::runtime::PackedFunc const*)+0x398) [0x7fb03fc320]
[bt] (9) /home/firefly/DL/tvm/lib/libtvm_runtime.so(tvm::runtime::RPCSession::HandleUntilReturnEvent(tvm::runtime::TVMRetValue*, bool, tvm::runtime::PackedFunc const*)+0x1f8) [0x7fb03f67d0]

**Comment by tqchen** [comment]
I cannot reproduce this problem locally. Please try upgrade your nnvm and tvm to the latest master and rebuild the graph runtime on the board, along with the nnvm/tvm on your host and try again

**Comment by tqchen** [comment]
OK, confirmed with @yidawang this is due to the fact that latest version of TVM graph runtime depend on the latest version of NNVM, please update your nnvm to latest version
